### ISSUE TITLE
Chaos - Chaos Space Marines: Warp Talons can't select a Mark of Chaos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1005]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** *Warp Talons can take a LEGION and MARK OF CHAOS, which is not currently included in the list options.

**Comment by ilaunchbury** [comment]
Warp Talons already have the <LEGION> keyword. Mark will be in the next release.
