### ISSUE TITLE
Point costs for wargear and units for non Codex chapters is wrong

### ISSUE THREAD

**Issue by winter-ibt** [BSData/wh40k#1014]
Non Codex Chapters should have their unit costs updated where changed in the Space Marine Codex (Predator, Inceptor etc).

Similarly wargear costs (Powerfist, Thunder hammer etc) should be updated also.

**Comment by alphalas** [comment]
No, because Index prices are still legal for non-codex. Want codex units, multi-detachment in C:SM.

**Comment by winter-ibt** [comment]
Source:

https://www.warhammer-community.com/2017/07/22/the-other-angels-of-death-and-codex-space-marines/

"Blood Angels, Dark Angels and Space Wolves army lists in Index: Imperium 1 all let you use units from the Space Marines section of that book. If you own the new codex, you should feel free to use those same units’ Datasheets from that book instead, until your own codex comes out."

So everything that can be pulled from the Codex, can be pulled from the Codex.

**Comment by amis92** [comment]
@winter-ibt I think in your last sentence you meant "... can be pulled from the Index, can be pulled from the Codex".

You can do that. Imagine that catalogue Space Marines is the Codex, and what you have in DA, BA, SW is Index. You can mix and match them. See #77.

**Comment by winter-ibt** [comment]
I mean that if there is an update for a unit that is listed in the Index in the Codex, you can use the update in the Codex.

This is now absolutely confirmed for units themselves with this PDF: https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf

I don't see why you would have units being pulled from the Codex where possible and Wargear not being pulled from the Codex. Especially where the weapons in the Index refer to the Space Marine versions.

Who knows if @alphalas will re-open the issue for resolution though now it has been confirmed that it is an issue...

**Comment by alphalas** [comment]
You missed the point that @amis92 made – you can absolutely do what you want to do right now, without any changes made. #77. 
The other thing you seem to be missing is that those things you cited say "can" or "may", not "would" and "should". Index values are still completely legal, and not invalidated.

**Comment by winter-ibt** [comment]
Ah right, gotcha. Please excuse my ignorance of how Battlescribe works. On mobile it looks like separate detachments, but they are linked at the rules level.

It still seems a somewhat strange approach. The Index+Data PDFs define what units may be taken by non Codex chapters and you have one definition of the units in the non Codex chapter catalogue, but not the other definition. Why does one definition make it in the catalogue but the other not when both are perfectly valid? The argument that they are in the same book seems strange when they are in the same book but under a different section of the Index. 

Are you not going to add Aggressors, Reivers, Redemptor Dread etc to the non Codex chapter catalogues because they are only defined in the Codex and so the multi catalogue detachment approach handles that scenario?

**Comment by alphalas** [comment]
Pretty much the reason why were doing it this way is because of bad experiences from the previous ruleset with Codex: Imperial Agents. Because GW did not invalidate the old units in the Inquisition Codex, we were obligated to have duplicates of almost every unit in the codex in the cat, effectively doubling the  actual size of the datafile. By doing it the way we are now, we keep the file small (means shorter load times), and still support people who use index values instead of the codex values for their armies.  But yes, the new Primaris will be added to the cats, because they are specifically called out as being usable in those armies, and having keyword whatever that army is.

**Comment by winter-ibt** [comment]
So say Hellblasters will still be more expensive in the non-codex cats or does the downloadable PDF overwrite the Index? 

I don't think there are any cases where points went up for non-codex cats so it seems kind of pedantic (for it's own sake) to keep them separate.

**Comment by alphalas** [comment]
The PDF doesn't actually change the primaris in the Index - it only provides the primaris in the codex to non-codex armies. The point is the Index is still legal, and should be supported as such.

**Comment by winter-ibt** [comment]
Actually it does change the Primaris in the Index. Inceptor and Hellblasters are in the Index and have been available to some of the non-Codex Chapters since the Index. 

They are now cheaper as per the PDF points cost. If that isn't updating the Primaris in the Index, I don't know what you are requiring before updating the catalogues...

If I could figure out how to update the Catalogues in BattleScribe 2 (all your examples are for older versions and I can't seem to follow the instructions from 1.x for 2.x) I'd just make a branch, but I can't work it out :-/

**Comment by alphalas** [comment]
Ok, I missed that one, sorry - those will be updated as it is stated as specifically for BA/DA/SW.
