### ISSUE TITLE
Chaos - Chaos Space Marines - Fabious Bile movement

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1015]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Space Marine HQ Fabius Bile is stating he has a movement of 4" however in the Index it states he has a movement of 6"

Hope this can be updated guys thanks. I also checked to see if this has been raised but didn't see anything active.

**Comment by ilaunchbury** [comment]
This is correct in CSM v19. Please check you have the latest version of the catalogues.
