### ISSUE TITLE
Chaos - Heretic Astartes - CSM daemon prince vs ephemeral form 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#1017]
Hello,

By raw , I don't think the CSM daemon prince gets the ephemeral form ability when selecting Tzeentch as a god. Maybe it was clarified somewhere?

![img_2051](https://user-images.githubusercontent.com/16340056/28744928-4de82602-743a-11e7-94fc-2dbb55c7af9d.PNG)

![img_2052](https://user-images.githubusercontent.com/16340056/28744929-4df74f38-743a-11e7-806f-002fbdd9daad.PNG)

**Comment by Rasputinprime** [comment]
The core issue appears to be that the CSM Daemon Prince entry is using the text from the Daemon version as it also lacks the Legion specific reroll text from the above image.

**Comment by ilaunchbury** [comment]
@Rasputinprime, you're absolutely right. I copied Daemonic Allegiance across from Daemons and forgot to update it.
