### ISSUE TITLE
FW Astartes Relic Unit bug

### ISSUE THREAD

**Issue by RPWoten** [BSData/wh40k#1018]
**File/Catalogue:** Warhammer 40,000 8th Edition v1.0.37

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Attached FW Astartes to Space Marines, It doesn't count units from the Space Marine List toward validating relic units. Not sure if it matters but i selected space marine first the added FW Astartes to it.

**Comment by ilaunchbury** [comment]
It does matter. As per the Wiki (https://github.com/BSData/wh40k/wiki/Using-FW-Relic-units), you need to add the FW units first.
