### ISSUE TITLE
Imperium - Space Marines - Honour Guard weapon options missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1019]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** In the "Honour Guard" entry the weapons options are missing!

**Comment by alphalas** [comment]
dupe #1032

**Comment by marneuscalgar** [comment]
Sorry, my mistake: in the new Space Marines codex, the Honour Guard has no weapon options!
