### ISSUE TITLE
Imperium - Space Wolves - FAQ Changes

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k#1022]
Significant changes were introduced via the FAQ v1.1. 

These include wargear changes to nearly every Wolf Guard model, including pack leaders. Wargear changes regarding certain characters. A points increase for Wolf Claws. The ability to take a Company Ancient from the Space Marine section.

**Comment by ilaunchbury** [comment]
The FAQ 1.1 changes are in progress and will be released soon.

**Comment by Gnofry** [comment]
Who is the data author actually assigned to update the SW catalog to 1.1?

**Comment by Gnofry** [comment]
Or rather, simply is there a data author assigned to update 1.1? Glancing through the closed issues, and the lack of a FAQ v1.1 checklist issue like with most, if not all, major content updates, it really seems like this particular catalog fell through the cracks.
