### ISSUE TITLE
Imperium - DKOK: Earthshaker Battery missing.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1023]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 1.04.91

**Platform:** Windows

**Dropbox:** No

**Description:** In Death Korps of Krieg there is no entry for Earthshaker Battery - There is only Earthshaker Carriage.

**Comment by CrusherJoe** [comment]
I'm not sure what's missing? Both the carriage and the cannon are present:

![screen shot 2017-07-30 at 9 40 15 am](https://user-images.githubusercontent.com/9998385/28754470-50efcdce-750b-11e7-8682-52e798bb8499.png)
![screen shot 2017-07-30 at 9 40 31 am](https://user-images.githubusercontent.com/9998385/28754471-53e321ca-750b-11e7-8b0f-eb1744540609.png)

**Comment by CrusherJoe** [comment]
Checking the FAQ DKOK don't have access to the Earthshaker battery.
