### ISSUE TITLE
Deathwatch - Specialist Ammo

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1027]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Error with specialist ammunition, it keeps looping mistakes, such as adding multiple of the choice to one unit after correcting it from another

**Comment by FarseerVeraenthis** [comment]
This error is not present in V9 so I think this can now be closed.
