### ISSUE TITLE
 Deathwatch Primaris - Codex Space Marines Update required

### ISSUE THREAD

**Issue by Inquisitorbane0069** [BSData/wh40k#1029]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 
Per Game's Workshop website Deathwatch may now include all Primaris Marines. Please update accordingly. See source Document PDF Download: https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf

**Comment by alphalas** [comment]
duplicate #987
