### ISSUE TITLE
Crusader Squad Missing; Index Honor Guard options Missing.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1032]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** Yes

**Description:** Since the update to include the new space marine codex the troop choice "Crusader Squad" is no longer available. in addition if a unit had options for war gear in the index they retain the options but the index costs for wargear ie Honor Guard.

**Comment by marneuscalgar** [comment]
In the new Space Marines codex, the Honour Guard has no weapon options
