### ISSUE TITLE
Index vs Codex Unit options

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#1034]
https://www.warhammer-community.com/2017/07/05/codexes-your-questions-answered-july-5gw-homepage-post-2/

As stated here, options that are in the Index but not in the Codex (specific examples given are Dreadnought Arm options and Characters on Bikes) can be taken. This means units such as Dreadnoughts will have to have their own unit entry with index points values and weapon options.

**Comment by alphalas** [comment]
... afaik that much is obvious and will be implemented?
