### ISSUE TITLE
Captain should have a bolt pistol by default

### ISSUE THREAD

**Issue by Aldran** [BSData/wh40k#1048]
Imperium - Space Marine

BattleScribe version: 2.01.03

Platform: Windows

Description: By the Codex Space Marine:

"A Captain is [...] armed with a chainsword, a master-crafted boltgun, a bolt pistol, frag and krak grenades."

Right now Battlescribe gives an error if you give the Captain all the above weapons because it considers it 3 selections when the maximum is 2. However the Captain comes with a bolt pistol by default.

**Comment by flakpanda** [comment]
This has been fixed in v21+
