### ISSUE TITLE
Death Korps super heavy point costs

### ISSUE THREAD

**Issue by AsinineFutility** [BSData/wh40k#1051]
**File/Catalogue:** FW Death Korps of Krieg v14

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**

Most of the point costs for the forge world astra militarum super heavy vehicles are incorrect and choices are missing. For example, the macharius vulcan charges points for all sponson options and has no choice of which you want, as well as producing an error for "2 too many selections fron heavy stubber (maximum 1)"  

In addition, the forge world super heavies only appear to be accessible via the death korps rather than through the astra militarum option; they should either be added to astra militarum super heavies, or added as a separate force (i.e. 'FW Astra Militarum Super Heavies' as a separate force option).

**Comment by AsinineFutility** [comment]
Also, hot-shot lasguns are options in tge death korps ranged weapon list, but is unavailable for:
- death rider squadron commander
- marshal
- field officer
- grenadier storm squad watchmaster
- infantry squad watchmaster
- combat engineer watchmaster
- commissar
- quartermaster revenant
- death rider squadron ridemaster

Thank you for your continued work on this project.

**Comment by alphalas** [comment]
@AsinineFutility i can't reproduce your comment, make sure you're running v12. i'm about to push v13+ which will fix the superheavy thing.
