### ISSUE TITLE
Imperium - Space Wolves - Wolf Guard Pack Leader

### ISSUE THREAD

**Issue by MandaPii** [BSData/wh40k#1057]
**Imperium - Space Wolves** 

**BattleScribe version Windows:** 2.01.04
**BattleScribe version Android:** 2.01.06

**Dropbox:** Yes

**Description:** 
The Index: Imperium 1 FAQ 1.1 update on Wolf Guard Pack Leaders hasn't been updated yet as of datafile v7 for the Imperium - Space Wolves. With other words I'm still unable to select two Wolf Claws for the Wolf Guard Pack Leader in Terminator Armour of my Blood Claw Pack, but the new FAQ does allow the unit to.

These changes apply to the Wolf Guard Pack Leader for the Blood Claws, Grey Hunters, Skyclaws (except for terminator), Long Fangs and anywhere else a Wolf Guard Pack Leader is included.

**FAQ 1.1**
Pages 148  – Blood Claws, Wargear Options Change the fourth bullet point to read:
•  The Wolf Guard Pack Leader may replace his chainsword with a plasma pistol, storm shield or an item from the Space Wolves Melee Weapons  list; he may also replace his bolt pistol with a plasma pistol or an item from the Space Wolves Melee Weapons  or Space Wolves Combi-weapons  lists.’ 

Change the fifth bullet point to read: ‘
•  The Wolf Guard Pack Leader in Terminator Armour may replace his power sword with a storm shield or an item from the Space Wolves Terminator Melee Weapons  list; he may also replace his storm bolter with an item from the Space Wolves Terminator Melee Weapons  or Space Wolves Combi-weapons  lists.’

**Comment by FarseerVeraenthis** [comment]
this is included in version 8
