### ISSUE TITLE
Imperium - Space Marines: Aggressor costs incorrect.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1063]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Bug Found in SpaceMarines v21.

Elites Squads - Aggressors. Equipment Auto Boltstorm Gauntlets & Fragstorm Grenade Launchers are 4pts too expensive for 3,4,5, and 6 men selections. In each instance it appears as if an additional Fragstorm Grenade Launcher is being added for 4pts. Each Aggressors equipment should cost 18pts. (14 for the Boltstorm Gauntlets, and 4 for the Fragstorm Grenade Launchers.)

A three man squad should be 129pts, not 133.

**Comment by flakpanda** [comment]
This has been fixed in v21+
