### ISSUE TITLE
Imperium - Space Marines: Redemptor Dreadnought wargear points value incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1064]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Bug found in Space Marines v21

Redemptor Dreadnought Weapon Option 3 has no cost for two (2x) Fragstorm Grenade Launchers. They should be 4pts each, so the equipment selection for two should be 8pts. 
ALSO: They are spelled incorrectly in the current v21. They are spelled "Granade" when they should be spelled "Grenade."

**Comment by flakpanda** [comment]
This has been fixed in v21+
