### ISSUE TITLE
Vehicle Point Cost Change for BA, DA, GK, and SW Armies 

### ISSUE THREAD

**Issue by Ragnarok2070** [BSData/wh40k#1072]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Ragnarok2070** [comment]
First I know your busy and thanks for the hard Work keeping up to date with 8th. 

Per most recent FAQ from Games Workshop all Astartes Armies use the same point cost for vehicles, Predator, Whirlwind, Land Speeder, Drop Pods, and Vindicators as is in the data sheets in the new Space Marine Codex. When can we expect to see Blood Angels, Dark Angels, and Space Wolves Battlescribe lists reflect the same vehicle point cost as is in the Adeptus Astartes codex. Thanks.

**Comment by alphalas** [comment]
Do you have a source for this, because we're going off of the FAQ about indices versus codices that said BA/DA/SW all use their index points costs.  Otherwise, if you want to use SM point values, use a child detachment of SM to replace those units.
