### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Macharius weapon options incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1080]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** All of the Macharius tanks incorrectly have three pairs of heavy stubber sponsons. Also there is no way to change the heavy stubbers to heavy bolters or Flamers.

**Comment by drdaniel5** [comment]
also I'm using BS 2.01.04.92 but the form wouldn't let me add in the last two digits.

**Comment by CrusherJoe** [comment]
What version of the DKOK catalog are you using?

**Comment by drdaniel5** [comment]
V14

**Comment by alphalas** [comment]
It's fixed in the next release (v15+)
