### ISSUE TITLE
Chaos - Chaos Space Marines: Chosen unable to take plasma pistol

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1083]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Elite Unit "Chosen" is missing the option to replace the Boltpistol with a Plasma Pistol

**Comment by ilaunchbury** [comment]
This has already been reported under #1077 and will be fixed soon.
