### ISSUE TITLE
Detachment requirements in its name

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1084]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Add minimum  units required description to detachment drop down menu?  I.e. Patrol Detachment: +0cp, (req. 1hq, 1troop)

**Comment by amis92** [comment]
Personally I don't think it's a good idea because this same name is printed in View and as such would clutter it.

I'd say we need more than my single opinion though.

**Comment by ilaunchbury** [comment]
It's not a bad idea, but as you say i think it would introduce unnecessary clutter into the output. The minimum requirements are already shown via constraints once you add the detachment to your roster.

**Comment by FarseerVeraenthis** [comment]
I'm down voting. If you're using Battlescribe, a) you should have the book for reference, and b) it tells you what is required in the validation at the bottom.

TL:DR Learn your detachments.

**Comment by BaconCatBug** [comment]
Only thing I can think would be nice would be to use chess Unicode symbols to properly order them in BRB order but apparently this breaks the mobile app?

**Comment by alphalas** [comment]
Also downvoted.
