### ISSUE TITLE
Chaos - Daemons: Price is wrong on Blue Horror escort option for Burning Chariot

### ISSUE THREAD

**Issue by MisterTsumi** [BSData/wh40k#1087]
**File/Catalogue:** Chaos - Daemons

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** The option to take Blue Horrors as an escort for the Burning Chariot is listed as No cost.  However, even though the three horrors are not combatants, they do still cost 5 points each in order to grant the Irritating Chant ability.  This was correct in earlier versions of the datafile, I am unsure why it was made free in the most recent version.

**Comment by ilaunchbury** [comment]
I accidentally dropped the cost when I took out the separate profile for the Horrors after it was clarified that they aren't an actual unit in FAQ 1.1.
