### ISSUE TITLE
Chaos : Space Marine Emperor's Children Hellbrute missing Blastmaster and doom sirene options.

### ISSUE THREAD

**Issue by superrugdr** [BSData/wh40k#1089]
**File/Catalogue:**  40k v1.00 -> Chaos Space marinve v19

**BattleScribe version:** 2.01.05

**Platform:** iOS

**Dropbox:** No

**Description:** 
when you select Legion : Emperor children's and add a Hellbrute in the Elite section.
as per Forgeword FAQ 1.0 the sonic dreadnought as the hellbrute profile with two added options.
1. swap multi-melta to two blastmaster
2. take a doom siren.
both are missing.

Thank you.

**Comment by ilaunchbury** [comment]
The Sonic Dreadnought is an FW choice, You need to add the FW Heretics Astartes catalogue into your force to select it. It has its own entry in that catalogue.
