### ISSUE TITLE
Imperium - Space Marines: Redemptor fragstorm launchers missing cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1096]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** Yes

**Description:** Redemptor dreadnought under battalion listing for v21 shows "No cost for 2 fragstorm grenade launchers. Per the new codex. These should be 4 pts per launcher for a total of 8pts. Alternate choice of 2 storm bolters is showing correctly at 4.

**Comment by flakpanda** [comment]
This has been fixed in v23+ (unreleased).
