### ISSUE TITLE
Imperium - Blood Angel Assault Squad special weapon choices

### ISSUE THREAD

**Issue by Oz-Mister-Q** [BSData/wh40k#1098]
**File/Catalogue:**  BA v17

**BattleScribe version:** 2.01.04

**Platform:** Mac & Windows

**Description:** Special weapon choices for assault marines are allowing melta and plasma guns. Current 8th ed Blood Angel assault squads are the same as regular Space Marines, and can only take a flamer or plasma pistol/chainsword for special weapons.

**Comment by alphalas** [comment]
It was updated in an FAQ – they can even take infernus pistols now in addition to the melta and plasma guns.
