### ISSUE TITLE
Imperium - Space Marines - Dreadnought Weapon Selection Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1099]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 1.00.41

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Dreadnoughts are allowed to take the weapon option included in the imperium index as well as the weapon options in the codex. Please see GW FAQ https://www.warhammer-community.com/2017/07/05/codexes-your-questions-answered-july-5gw-homepage-post-2/

**Comment by FarseerVeraenthis** [comment]
duplicate of #1067
