### ISSUE TITLE
Bug Report - Imperium - Codex Space Marines - Aggressors costs

### ISSUE THREAD

**Issue by evilmerlin** [BSData/wh40k#1101]
**File/Catalogue:  Imperium - Space Marines.catz

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** The point costs of Aggressors do not increase when more models are added to the squad. It stays at the point cost for 3 models. The unit cost also appears to be wrong. An Aggressor with Auto Boltstorm gauntlet and Fragstorm launcher costs 43pts, so 3 of them should be 129 and not 133.

**Comment by flakpanda** [comment]
This in a know bug with battlescribe itself. If you select a different option, and reselect the boltstorm gauntlets, it should readjust itself.

**Comment by evilmerlin** [comment]
But the point cost per model is still wrong though. In the way the points are listed in software.
2x Aggressor (50pts)
Aggressor Sergeant (25pts)
Auto boltstorm Gauntlets/Fragstorm Grenade Launcher (58pts) <----This is wrong. It should be 54pts.
-Auto boltstorm gauntlets
-Fragstorm Grenade Launcher (4pts)   <----Not sure why there is a point cost here but it is adding this as well when it shouldn't be.

**Comment by flakpanda** [comment]
there was a points descrepance with FGLs, and is being release in v24+ about noon cst
