### ISSUE TITLE
Missing options like Rifleman-Dreads

### ISSUE THREAD

**Issue by Hellgore1974** [BSData/wh40k#1107]
**File/Catalogue:** Space Marines v24

**BattleScribe version:** 2.01.

Hello,

I quote from the GW Codex-FAQ:
"Q: There are a few options that are missing in the codex that appear in the index: why is that? Does that mean I can’t use these models in my army anymore?
A: While the indexes are designed to cover a long history of miniatures, the codexes are designed to give you rules for the current Warhammer 40,000 range. There are a few options in the indexes for some Characters and vehicles that are no longer represented in the Citadel range – certain Dreadnought weapons that don’t come in the box, or some characters on bikes, for example.
Don’t worry though, you can still use all of these in your games if you have these older models. In these instances, use the datasheet from the index, and the most recent points published for that model and its weapons (currently, also in the index).
They still gain all the army wide-bonuses for things like Chapter Tactics and can use Space Marines Stratagems and the like, so such venerable heroes still fit right in with the rest of your army."

This means, that (like in Version 1.0.40 of the Warhammer 40k Data) units like the Rifleman Venerable Dread are still viable. There was no need to exclude it from the file.

**Comment by acebaur** [comment]
Not sure what you are talking about. I'm looking at SM v24 and the rifleman dread options are still there, along with other stuff excluded from the codex like bikers etc. Can you post a screenshot so we can see what the issue is?

Thanks

**Comment by Hellgore1974** [comment]
Wow, how embarissing... My Vendread-options on my roster got kicked when I reopened it with the new database and I didn't find the weapons as I was used to... of course they are still there and I'm a dud... duh! Sorry for bothering!
