### ISSUE TITLE
Chaos - FW Heretic Astartes: Soulburner Petard cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1123]
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Pls edit the points cost on the decimators soulburn petard , it is listed as 60pts per arm wherwin it should be 30pts per arm

**Comment by ilaunchbury** [comment]
The cost of the Soulburner petard was increased to 60 points in the FW FAQ.
