### ISSUE TITLE
T'au Empire: Razorshark turret missing rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1125]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** At the razorshark's quad ion turret you must add this rule: When attacking with this weapon, choose one of the profiles below. Add 1 to hit rolls for this weapon against
targets that can’t FLY.

**Comment by amis92** [comment]
Oh my, completely missed it! Never suspected these texts contained anything else than "choose one profile".
