### ISSUE TITLE
Dark Eldar Transports and Ynnari

### ISSUE THREAD

**Issue by AeldariBRC** [BSData/wh40k#113]
**File/Catalogue:** Aeldari - Ynnari v5

**BattleScribe version:** 2.01.

**Platform:** iOS/

**Dropbox:** No

**Description:** You currently can't select Raiders or Venoms as transports in the Ynnari Army, only Starweavers and Wave Serpents.
This might be because in the keywords for the Raiders and Venoms, they have the option of being either the Kabal, Wych Cult or the Coven and the app might be viewing it as always being part of the Coven, which the Ynnari can't take.

**Comment by FarseerVeraenthis** [comment]
Those pesky Drukhari!

**Comment by USSX-Hares** [comment]
@AeldariBRC, @FarseerVeraenthis, i'll have a look.
