### ISSUE TITLE
Chaos - FW Renegade and Heretics: Marauders missing Sniper Rifle option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1132]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Renegade Marauder Squad should have the Sniper Rifle entry under their special weapons allocation.

**Comment by Penallegion** [comment]
Reworked the whole marauder unit and added sniper should close with next merge
