### ISSUE TITLE
Chaos - FW Renegade and Heretics: PL for Disciple squad incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1133]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Renegade Disciple Squad is listed as 9 power instead of 3 power. In addition the unit choices for Vox Caster/Sigil etc still hasn't been resolved. Instead of allocationg the equipment to an existing member of the squad it insists on adding more models to the unit and incorrectly increasing the power.

**Comment by alphalas** [comment]
remove a plain guy to get the counts correct.

**Comment by Penallegion** [comment]
What Alphalas said. you add model including Vox/Sigil, by popular demand. and you have to remove plain disciples according to restrictions in unit size
