### ISSUE TITLE
Chaos - FW Renegade and Heretics: PL value for Command Squad incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1134]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Renegade Command Squad incorrectly listed at 6 Power, please amend to 3 Power.

**Comment by Penallegion** [comment]
this is working just fine in the edition i have, but have changed Min/max to abide with restricitons
