### ISSUE TITLE
Imperium - Space Marines: A few typos

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#1139]
**File/Catalogue:** Space Marines 27

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** 

- _Position_ is misspelled in the text for Roboute Gulliman's Armour of Fate
- In the Ultramarines chapter tactics, it should have "hit rolls **in** the Shooting phase."
- In the Imperial Fists chapter tactics, it should have "receive **the** benefit" and "re-roll **any failed** wound rolls"
- the Imperial Fists chapter tactic is misspelled. It should be **Siege** Masters.
- Raven Guard Chapter Tactics should be "hit rolls **when** shooting".
- Salamanders Chapter tactics should be "and **a** single failed wound roll", "for **a** SALAMANDERS unit and "shoots **or** fights".
- White Scars chapter tactics should be "**Whenever** a WHITE SCARS", "**it moves** an extra", and "In addition, WHITE **SCARS** units". It is also missing the text about Bikers and there's a missing space after 2".

**Comment by GMTemplar** [comment]
Also the Crimson Fists relic Fist of Vengeance has a capital "I" in "FIst".
