### ISSUE TITLE
Imperium - Space Wolves - Some puppies don't know where their weapons are

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1145]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Wolf guard pack leadees are unable to take melee weapons instead of their pistol even though the FAQ said they could. This means that combos such as twin wolf claws and thunder hammer storm shield can not be taken.

Wolf guard battle leaders in terminator armour are selecting from a list of weapons available to power armoured characters and not to the terminator armoured characters. This means weapons such as chain fists cannot be taken whilst plasma pistols can.

**Comment by MandaPii** [comment]
This issue is the same as I posted earlier.
https://github.com/BSData/wh40k/issues/1057
