### ISSUE TITLE
Chaos Space Marines - Daemonic allies

### ISSUE THREAD

**Issue by GMTemplar** [BSData/wh40k#1147]
**File/Catalogue:** Daemons v14

**BattleScribe version:** 2.01.04.92

**Platform:** Windows

**Dropbox:** Yes

**Description:** When adding allied Horrors to a Chaos Space Marine detachment the point cost of blue and brimstone horrors is calculated incorrectly (only 5/2pts for the entire group, not per model).

**Comment by ilaunchbury** [comment]
This sounds like the Battlescribe bug where point costs in child detachments are not calculated correctly. We're waiting on a fix.
