### ISSUE TITLE
FW Heretic Astartes - Hellforged Predator

### ISSUE THREAD

**Issue by GMTemplar** [BSData/wh40k#1148]
**File/Catalogue:** FW Heretic Astartes v7

**BattleScribe version:** 2.01.04.92

**Platform:** Windows

**Dropbox:** Yes

**Description:** Hellforged Predator has the stat line of Land Raider Achilles.

**Comment by ilaunchbury** [comment]
This was fixed in #1126 and is in the latest release (1.0.45).
