### ISSUE TITLE
DA Intercessor and Hellblaster Options missing

### ISSUE THREAD

**Issue by Artanor** [BSData/wh40k#1157]
**File/Catalogue:** Dark Angels v19

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The Intercessor and Hellblaster squads do not have the options that became available in the new kits.

**Comment by CubanoConGitHub** [comment]
This also applies to the Space Wolves catalog. The options appear to be available when added to the Space Marines catalog.
