### ISSUE TITLE
DA Primaris

### ISSUE THREAD

**Issue by DacierCellius** [BSData/wh40k#1158]
The following units has incorrect point cost and is not able to be edited for the Dark Angels
Hellblaster
Inceptor
Intercessor

The following units are in the wrong location for the Dark Angels
Aggressor Squad (listed as Heavy Support instead of Elite)
Redemptor Dreadnaught (listed as Heavy Support instead of Elite)
Repulsor (listed as Heavy Support instead of Dedicated Transport)

**Comment by DacierCellius** [comment]
I don't know how this is a duplicate when it still isn't fixed. Hopefully it will be on the next update.

**Comment by Thairne** [comment]
It was a duplicate because the same problems were reported in another issue. You mark one, close it and work on the other.

**Comment by DacierCellius** [comment]
Ok I was just worried since the other Primaris didn't mention the units being in the incorrect location or the point cost not being correct.
