### ISSUE TITLE
Imperium - Space Marines: Power fist cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1164]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** When using black templars, I can equip a power fist instead of a heavy weapon. The points for a powerful is 20 instead of the 12 listed on the codex.

**Comment by CubanoConGitHub** [comment]
This is also true for Space Wolves. 

This was corrected in commit e66fd8d (line 22338) for the Space Marines catalog. I suspect there is more than one catalog file with references to `targetId="f122-3720-fa32-4215"`.

**Comment by ilaunchbury** [comment]
Which unit(s) is this a problem on?

**Comment by CubanoConGitHub** [comment]
Still getting the hang of reading the cat files but below is a list of references for what seems to be the offending ID in all the catalog files.  

~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:6892:                     <entryLink id="a5d3-76fd-3b2f-b3a9" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:16873:         <entryLink id="7809-62b0-7e84-d4e3" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:16944:         <entryLink id="ef59-7ccd-bc08-c9e2" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:17428:         <entryLink id="dd9c-0844-2888-f3ea" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:17616:             <entryLink id="f829-8638-038e-5253" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:17702:             <entryLink id="bbba-75b7-e038-9286" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:17966:             <entryLink id="a922-db13-b05f-a6e3" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Chaos Space Marines.cat:18573:         <entryLink id="1b93-828f-f8a0-24be" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Death Guard.cat:1916:                     <entryLink id="5696-0c50-1745-e778" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Death Guard.cat:7463:         <entryLink id="550d-ac84-1d61-21b2" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Death Guard.cat:7601:         <entryLink id="7809-62b0-7e84-d4e3" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Death Guard.cat:7663:         <entryLink id="ef59-7ccd-bc08-c9e2" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Thousand Sons.cat:8029:         <entryLink id="550d-ac84-1d61-21b2" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Thousand Sons.cat:8159:         <entryLink id="7809-62b0-7e84-d4e3" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Chaos - Thousand Sons.cat:8313:         <entryLink id="cab2-2a18-c022-5cce" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Adeptus Mechanicus.cat:2748:         <entryLink id="6dfc-fa73-0c59-694a" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Astra Militarum.cat:10857:             <entryLink id="90c7-841e-6b3c-e277" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Astra Militarum.cat:11206:             <entryLink id="1b32-e08c-affc-59d0" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Astra Militarum.cat:11610:         <entryLink id="3368-a4a7-20ef-2451" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Astra Militarum.cat:21784:                 <entryLink id="87df-650c-8bf8-c793" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Astra Militarum.cat:30486:         <entryLink id="9930-11ce-b1cc-1218" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:3651:             <entryLink id="18c1-a591-8197-d06a" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:3855:             <entryLink id="5b18-d1c3-295c-f572" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:10889:             <entryLink id="93c2-8100-8c63-4fd9" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:11124:             <entryLink id="0294-2d99-61e1-e382" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:11294:                 <condition field="selections" scope="7fc2-e1ed-6a70-1677" value="1.0" percentValue="false" shared="true" includeChildSelections="false" includeChildForces="false" childId="f122-3720-fa32-4215" type="equalTo"/>
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:11327:             <entryLink id="8e70-2af7-6857-0e59" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:12099:                     <entryLink id="e7ae-3ff5-6d77-2767" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:12485:                 <entryLink id="94fa-4343-6888-bfb7" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:18926:         <entryLink id="b167-4625-2194-1443" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:19072:         <entryLink id="8a8c-47d9-9370-b3c2" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Dark Angels.cat:19252:         <entryLink id="2126-25eb-cf0e-52aa" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:3065:         <entryLink id="fe19-a70f-b473-0074" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:4298:         <entryLink id="8c7c-1316-a240-f140" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:6170:         <entryLink id="8de7-8e7f-11f1-f731" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:6547:         <entryLink id="92a9-1d18-e269-f377" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:6745:         <entryLink id="b7e3-fa0c-7571-4b7c" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:7259:         <entryLink id="27af-703c-872c-253e" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:7411:         <entryLink id="473f-70b4-fead-a1b3" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:7601:         <entryLink id="3f78-44d5-bfac-8020" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Deathwatch.cat:7755:         <entryLink id="5ff4-6375-e172-9c95" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - FW Death Korps of Krieg.cat:3082:                 <entryLink id="6e26-f638-e247-1727" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - FW Death Korps of Krieg.cat:15626:         <entryLink id="d6ed-484d-c041-5aae" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - FW Elysians.cat:6710:         <entryLink id="3ca3-3c6d-1054-2baa" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Inquisition.cat:1354:             <entryLink id="c0e8-c58e-e693-1dc8" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Inquisition.cat:3222:         <entryLink id="7410-cd7f-4822-534d" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Marines.cat:21350:         <entryLink id="a785-b9a7-b837-9aed" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:7222:                     <entryLink id="564f-8db3-cbc8-ec86" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:8908:                     <entryLink id="233a-b9f7-9fcc-22b4" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:9057:                     <entryLink id="f8d0-72c3-1c01-c3bf" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:12454:                     <entryLink id="b594-53d1-19c9-01d6" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:18357:         <entryLink id="8a8c-47d9-9370-b3c2" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:18501:         <entryLink id="8b75-d70b-1b4e-fd5d" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:18681:         <entryLink id="ce1d-62e3-6d0b-9174" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:19704:         <entryLink id="6902-a823-3b95-b967" name="New EntryLink" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Imperium - Space Wolves.cat:19780:         <entryLink id="29bd-68a1-f7d0-9cdc" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Warhammer 40,000 8th Edition.gst:3817:     <selectionEntry id="f122-3720-fa32-4215" name="Power fist" hidden="false" collective="false" type="upgrade">
~/Documents/GitHub/wh40k/Warhammer 40,000 8th Edition.gst:7155:                         <entryLink id="a001-967d-61b9-189a" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
~/Documents/GitHub/wh40k/Warhammer 40,000 8th Edition.gst:8782:         <entryLink id="30f0-a567-31bc-2379" name="Power fist" hidden="false" targetId="f122-3720-fa32-4215" type="selectionEntry">
