### ISSUE TITLE
Space Marines Codex equipment option reduction on several units

### ISSUE THREAD

**Issue by gamesprecipice** [BSData/wh40k#1166]
**File/Catalogue:** 
**BattleScribe version:** 2.01.
**Platform:** Windows
**Dropbox:** No
**Description:**

Options for landspeeders are reduced, no longer can a model have two of the same weapon.
Honour guard have power axes by default and no longer have the option to switch them out.

**Comment by ilaunchbury** [comment]
As per various GW publications, it is still possible to use the Index datasheets for models/units if there are options which do not appear in the Codex, therefore those options are still available in the catalogues.
