### ISSUE TITLE
Space Marines - the cost of the Inceptors weapon doesn't change as you change the number of Inceptors

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#1170]
**File/Catalogue:** Space Marines v 27

**BattleScribe version:** 2.01.

**Platform:** Windows/Android/

**Dropbox:** No

**Description:** The cost for the assault bolters is always 90pts, and the plasma exterminators is always 168.
It should be 30 x the number of models for the assault bolters, and 56 x the number of models for the plasma exterminators.

**Comment by flakpanda** [comment]
This is a known bug with Battlescribe itself and has been sent up the chain already before. If you select a different option, then re-select the option you want it should change. There have been reports of this not working for child detachments though, and the only way to fix it is by reloading the roster.
