### ISSUE TITLE
Space Marines: Heavy Plasma Incinerator cost incorrect

### ISSUE THREAD

**Issue by Aldran** [BSData/wh40k#1180]
Space Marines v27

BattleScribe version: 2.01.

Platform: Windows/Android/Linux

Description: Hellbaster Squad equipment cost for Heavy Plasma Incinerator is wrong. The weapons have an initial cost of 36 points + 17 per member in the squad. In the codex it only says that it should cost 17 per member in the squad.

Thanks

**Comment by ilaunchbury** [comment]
Duplicate of #1151
