### ISSUE TITLE
Space Wolves - Validation issue with Wolf Guard Pack Leaders for Grey Hunters and Blood Claws

### ISSUE THREAD

**Issue by dvanherten** [BSData/wh40k#1186]
**File/Catalogue:** Imperium - Space Wolves v8

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Validation issue with Pack Leaders for Grey Hunters and Blood Claws

Steps to Reproduce:

1. Add a unit of Grey Hunters or Blood claws
2. Add the Wolf Guard Pack Leader
3. Select Bolt Pistol for the Replace Bolt pistol section.
4. Select Frost Sword for the Replace Chainsword section

Expected: Valid combination.
Actual: Wolf Guard Pack Leader has 1 too many selections from Replace Bolt Pistol (maximum 1).

Assumption: Space Wolves Melee Weapons group in Replace Chainsword is attached to the Replace Bolt Pistol validation rule.

Side note: Sky Leader appears to work as intended.

**Comment by FarseerVeraenthis** [comment]
Thanks for the bug report :smile: I was working on this the other day to include the FAQ update, but I obviously missed something... I'll have a look and see if I can fix it :+1:
