### ISSUE TITLE
Imperium - Astra Militarum: Tank Commander and Pask lacks Hunter Killer missile upgrade

### ISSUE THREAD

**Issue by RaeveSpam** [BSData/wh40k#1187]
**File/Catalogue:** Imperium - Astra Militarum v40

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Imperial Guard Tank Commander units and Knight Commander Pask should be able to take a Hunter Killer missile upgrade per the Errata https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Index_Imperium_2_ver_1.1.pdf

**Comment by alphalas** [comment]
Already been implemented, will be in the next release
