### ISSUE TITLE
Sternguard Veteran Squad Missing Weapon Choices

### ISSUE THREAD

**Issue by Tavern-lexicon** [BSData/wh40k#1188]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Sergent's Weapon list includes a Thunderhammer in the official 2017 Imperium 1 Index, which does not show in the list of weapon choices in BS.Blood Angels

**Comment by GenWilhelm** [comment]
The Sergeant Equipment list specifies that a Sternguard Sergeant may not take a thunder hammer, and I can't see anything in the FAQ relating to this.

**Comment by Tavern-lexicon** [comment]
The Sternguard details do not say anything about not being able to bring a Thunderhammer. All it says is it can take something from the sergent special list which does include Thunderhammers. I’ve attached two screenshots from the official Index that I bought through Apples iTunes store ibooks.

[cid:07565429-FC40-4920-AAF4-C8EDF77494FE@localdomain][cid:7A8DEBF8-137D-425C-804D-11365B1C2F24@localdomain]



Alexander Fernandez
LexIcon@tavernsavepoint.com<mailto:LexIcon@tavernsavepoint.com>



On Aug 14, 2017, at 5:35 AM, GenWilhelm <notifications@github.com<mailto:notifications@github.com>> wrote:


The Sergeant Equipment list specifies that a Sternguard Sergeant may not take a thunder hammer, and I can't see anything in the FAQ relating to this.

**Comment by alphalas** [comment]
![img_1661](https://user-images.githubusercontent.com/15703066/29271636-70f4dc0c-80ca-11e7-8e48-d4d7a1095425.PNG)

Also, my paper Index agrees.
