### ISSUE TITLE
DA Primaris Pt 2

### ISSUE THREAD

**Issue by DacierCellius** [BSData/wh40k#1195]
The cost of the Primaris Hellblasters are incorrect. Total it should be 165 for the Plasma Incinerator, 170 for the Assault Plasma Incinerator, and 175 for the Heavy Plasma Incinerator. 

Primaris Intercessors had a faqs for the the Auxiliary Grenade Launcher to cost 1 point now. This should be on all Space Marine chapters. 

Primaris Aggressors cost is incorrect. The Flamestorm Gauntlets are 4 points more than the Auto Boltstorm Gauntlets with the Fragstorm Grenade Launcher. This should be on all Space Marine chapters.

**Comment by Thairne** [comment]
Nope. Bolstorm Gauntlets are 14, Fragstorm is 4. Flamestorm is 18.
Therefore 14 + 4 = 18.

**Comment by DacierCellius** [comment]
Ah that's right. I stand corrected on the Aggressors :)
