### ISSUE TITLE
Sub-Faction Selector for Druhkari?

### ISSUE THREAD

**Issue by ztey** [BSData/wh40k#1203]
File/Catalogue: Druhkari v.11

BattleScribe version: 2.01.

Platform: Windows

Dropbox: No

Description: Could a system similar to the CSM's, where you have the option to select a legion be added to the Druhkari? With options for Kabal, Wych Cult, and Haemonculus Coven, automatically restricting your units? I think this would help speed up army creation and I for one, as well as other Druhkari players, would greatly appreciate it. Thanks for all the great work!

**Comment by Toreador13** [comment]
I think maybe keep this in mind for the future, or if someone wants to do this on their own, go for it. I at this point think that it is more work than it's worth. 

If they do kabals, cults or covens with differing traits, I would definitely work to implement it, but right now you would have to hide and unhide all units based on those categories, which introduces a lot more areas for failure right now. We might wait until the codex hits to see what they do.
