### ISSUE TITLE
Imperium - Space Wolves: validation error with Logan on Stormrider

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1204]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** When adding a Logan Grimnar on Stormrider to any detachment, it states "has one too many selections of Logan Grimnar on Stormrider (maximum 0)."

**Comment by ilaunchbury** [comment]
I can't replicate this. Logan on Stormrider only gets restricted if you've already select standard Logan somewhere else in your roster or if you've got two of him.

**Comment by ilaunchbury** [comment]
Managed to replicate this on Android and then on Windows. It seems to be a Battlescribe bug as I can't find anything in the catalogue that should be causing this.

**Comment by GenWilhelm** [comment]
The conditions to check for the other type of Logan are looking for links, rather than entries, which has always been somewhat buggy. Changing them to look for the appropriate entries should fix the issue.
