### ISSUE TITLE
Imperium - Space Marines: Aux grenade launcher cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1206]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** The Space Marines FAQ changed the point costs of the auxiliary grenade launcher of the Intercessors.

**Comment by bonds0097** [comment]
I have addressed this in PR #1213 waiting for approval.
