### ISSUE TITLE
Missing csm legion traits

### ISSUE THREAD

**Issue by z258** [BSData/wh40k#1210]
![img_0807](https://user-images.githubusercontent.com/25120579/29265233-a713b480-8123-11e7-8018-d81cf456929f.PNG)
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Missing night lords, alpha, iron warriors, word bearers and renegade traits

**Comment by ilaunchbury** [comment]
The Codex CSM changes have not been released yet. Please check the release notes to see when it's actually been released.
