### ISSUE TITLE
Chaos - Thousand Sons: Blue Horrors on Burning Chariot should be free?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1214]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Blue horrors upgrade was said to be 0 cost for a burning chariot. Currently listed as 15 points on the file.

**Comment by Drachnyen** [comment]
From the index Chaos FAQ:

![img_2072](https://user-images.githubusercontent.com/16340056/29322569-fc0d5cec-81ab-11e7-8f10-311082413a41.PNG)

**Comment by ilaunchbury** [comment]
That doesn't say that they are free, just that they are not actually models with their own profile.

**Comment by Drachnyen** [comment]
Yeah.  Not super clear on GW part

**Comment by GenWilhelm** [comment]
If they're not models, then they are wargear. Therefore they should be free for two reasons:
1. They do not have a points value listed in the wargear section.
2. The Burning Chariot's model includes wargear in its cost.
