### ISSUE TITLE
Index/Codex Validity

### ISSUE THREAD

**Issue by skaigh** [BSData/wh40k#1217]
Hope this is allowed, as it isn't specific, but:

As Codexes come out and are different from Index entries, GW has said that things left out of Codexes can still be used from the Index. An example would be Dreadnoughts and Venerable Dreadnoughts from the Codex lacking the option to take 2 Autocannons. Since the Index entry is still valid, how can this be reflected in Battlescribe?

Evidence: 
"**There are a few options that are missing in the codex that appear in the index: why is that? Does that mean I can’t use these models in my army anymore?**"
"_While the indexes are designed to cover a long history of miniatures, the codexes are designed to give you rules for the current Warhammer 40,000 range. There are a few options in the indexes for some Characters and vehicles that are no longer represented in the Citadel range – certain Dreadnought weapons that don’t come in the box, or some characters on bikes, for example.
Don’t worry though, you can still use all of these in your games if you have these older models. In these instances, use the datasheet from the index, and the most recent points published for that model and its weapons (currently, also in the index).
They still gain all the army wide-bonuses for things like Chapter Tactics and can use Space Marines Stratagems and the like, so such venerable heroes still fit right in with the rest of your army._"

From: https://www.warhammer-community.com/2017/07/05/codexes-your-questions-answered-july-5gw-homepage-post-2/

Thank you,
Skaigh

**Comment by CubanoConGitHub** [comment]
To me it seems more elegant from a UX perspective to tackle this on a case by case basis instead of having multiple entries for units that have "evolved" their weapons options. Perhaps the codex entry is used as the default with any weapons options from the Index added as if it's in the codex?

**Comment by skaigh** [comment]
Due to GW's phrasing - "_In these instances, use the datasheet from the index, and the most recent points published for that model and its weapons_" - it should be legal simply adding the weapon options and costs from the Index onto the model cost from the Codex.
