### ISSUE TITLE
T'au Empire: Taunar missing Cluster Shells ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1219]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** At the kx139 taunar entry you forgot this rule, Cluster Shells: Roll a dice for each enemy model that ends a charge move within 3" of this model. On a 4+,
that model’s unit suffers a mortal wound.

**Comment by amis92** [comment]
The behavior is correct, the ability is activated (shown) only when Heavy Rail Cannon is selected as main weapon. (Read Options sections on Datasheet)
