### ISSUE TITLE
Imperium - Deathwatch - Black Shield pair of Lightning Claws not calculating correctly

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#1220]
**File/Catalogue: Imperium - Deathwatch.cat V8** 

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** For the Black Shield, if you select two lightning claws you get a different total to just ticking the lightning claw (Pair) option. 
A Black Shield should be 19 points + pair of claws (13) = 32 pts.
Selecting two individual claws comes to 28 points.

**Comment by acebaur** [comment]
Not sure how you are getting this? I'm seeing it calculate fine on my screen. Can you provide a screenshot so I can see what you are seeing?

**Comment by FarseerVeraenthis** [comment]
On V9 it seems to be working fine so, ignore me and carry on 👍
