### ISSUE TITLE
Chaos - Chaos Space Marines: Daemon troops are missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1221]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Missing the chaos demons troops (blood letters, daemonettes, etc.) Are,missing for troop choices.

**Comment by ilaunchbury** [comment]
For now, just add Daemons as a child force and use the ones from there. They've been updated to the latest points values and rules.
