### ISSUE TITLE
[Anon] Bug report: Imperium - Legion of the Damned.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1222]
**File:** Imperium - Legion of the Damned.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** When I try to select a Vanguard Detachment so I can use all Legion of the Damned, it always says HQ choice not validated, but you can't select an HQ choice because none are available.  I checked with GW and I am correct to use it this way, and of course I can do it on paper, but it isn't working out for LOD.  This makes me wonder if the rest of entries that are not in Codex Space Marines might not have the same problem.

**Comment by ilaunchbury** [comment]
I'm not sure what you mean. Legion of the Damned don't have any HQ choices of their own, so you'll always need to add one from a different IMPERIUM or ADEPTUS ASTARTES army (by adding a child force in BS).

The only way to take them without an HQ choice is to take them in an Auxiliary Support detachment.

Eldar Corsairs have the same "issue".
