### ISSUE TITLE
Chaos - Chaos Space Marines: Chosen Champ weapon validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1224]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Mac

**Dropbox:** No

**Description:** Can't add Berserkers as troops with World Eaters Legion type selected.

Error with chosen with 2 lightning claws showing to many weapons selected.

**Comment by WindstormSCR** [comment]
as of the codex berserkers can no longer be troops. check updated FAQ and your codex.

**Comment by ilaunchbury** [comment]
As above, Berzerkers are no longer troops for World Eaters.

Added Chosen weapon validation issue to #1212.

**Comment by ilaunchbury** [comment]
I can't find a problem with the Chosen Champion. Giving him two lightning claws gives no validation error.
Are you trying to give him a ranged weapon as well? That's not allowed.
