### ISSUE TITLE
Heretic Astartes - Magnus has access to the full CSM dark Hereticus powers 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#1235]
Hello!

As clarified in the FAQ : https://www.warhammer-community.com/2017/08/13/daemons-and-thousand-sons-in-codex-chaos-space-marines-aug-13gw-homepage-post-2/

Magnus has access to the full list of Dark Hereticus powers contained in the CSM Codex. 

He is currently limited to the initial 3 of the index 

Thanks in advance,

**Comment by ilaunchbury** [comment]
Yes, I forgot him because he didn't use the selection list; previously he just had all of the ones available.
