### ISSUE TITLE
Feature Request: Warlord Trait selection

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#1238]
From [/r/BattleScribe](https://www.reddit.com/r/BattleScribe/comments/6tqjwz/warlord_traits/):
>Is there a place to designate a Warlord and trait to be included on the summary rules view for your force?

---

In a similar vein as psychic powers, might it be worthwhile adding the option to select which Warlord Trait your Warlord is taking, since this is now done at the army building stage, rather than being randomly generated at the start of a game?

I understand this is a much bigger undertaking for armies with access to a lot of characters (ie. Space Marines), so I'll leave this up for discussion.

**Comment by ilaunchbury** [comment]
The validation is tough IMO. How do you make sure a detachment is valid for a chapter/legion trait? 
Or do we just leave it up to the player to ensure it's valid, like with relics/artefacts?

Implementing the second option is more time-consuming than it is difficult, as it should just be a pick list with max 1 in roster for each option.

**Comment by alphalas** [comment]
I say we stay on the same track as we settled on last edition- no picking warlord, no warlord traits.

**Comment by alphalas** [comment]
Adding in the ability for every character/sgt model to be WL will just add unnecessary  bloat to files.

**Comment by tekton** [comment]
I may have added it to Grey Knights with limitations given to certain characters, too. That said, it's a small codex so it's no where near as bad as core SM, AM, etc.

**Comment by GenWilhelm** [comment]
It's not much more effort than adding the psychic powers selection - a shared entry group and with some entries being modified based on chapter (or equivalent), then linked to each character. And sergeants aren't characters anymore, so they wouldn't need to have it attached to them.

**Comment by elodingens** [comment]
Maybe attach it to Chapter / Legion and not attach it to a char.

**Comment by tekton** [comment]
At least for Grey Knights there are characters that are only allowed to take certain traits, not sure if other codices are going to continue that trend.

**Comment by GenWilhelm** [comment]
The same is true of both SM and CSM, so I would imagine so.

**Comment by alphalas** [comment]
Are the basic WL Traits in GST?

**Comment by flakpanda** [comment]
Closing. No comments in 3 months.
