### ISSUE TITLE
CSM PL/Point values are wrong

### ISSUE THREAD

**Issue by ShaneLillieGlu** [BSData/wh40k#1242]
**File/Catalogue:** Chaos - Chaos Space Marines

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** No

**Description:** A lot of the power levels/points of units is wrong per the codex. For instance Chaos Lord in Terminator Armor is 6 PL / 105 points now. There are also a lot of units left in that are no longer available, eg - lords in bikes, discs, juggernaut, and steeds are all gone. I would list them all out, but after a quick glance it appears most of the updates are not in.

**Comment by ilaunchbury** [comment]
All of the old Index units which are not in the Codex are still valid as per several posts on Warhammer Community.

The Terminator Lord change was missed and will be fixed. If you have other specific examples, please let me know.

**Comment by ShaneLillieGlu** [comment]
Oh awesome, I didn't realize that about the missing units. That's great. Here's a couple other incorrect PL/points I ran into:

Daemon Prince is now 8PL (9 with wings) / 146 points (170 with wings)
Sorcerer is now 6PL (8 in terminator armor) / 90 points (140 in terminator armor)
Warpsmith is now 5 PL / 45 points
Helbrute is now 7 PL / 72 points

**Comment by ilaunchbury** [comment]
Weird. I'm sure I fixed those. I'll look at them later tonight.

**Comment by ilaunchbury** [comment]
Daemon Prince already correct in v26.
All the rest are now fixed.
