### ISSUE TITLE
CSM Helbrute fist is missing options

### ISSUE THREAD

**Issue by ShaneLillieGlu** [BSData/wh40k#1243]
**File/Catalogue:** Chaos - Chaos Space Marines

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** No

**Description:** New rule in the codex allows integrating a combi-bolter or a heavy flamer into each Helbrute fist.

**Comment by ilaunchbury** [comment]
The options for the fist were already in the catalogue and can be selected by clicking on the fist on both Android and PC.. I don't have a Mac to test on, I'm afraid, so it could a Mac-specific problem?

Can you provide a screenshot?

**Comment by ShaneLillieGlu** [comment]
Ah, indeed, this one is user error. Sorry about that.
