### ISSUE TITLE
Chaos - Chaos Space Marines: Hades autocannon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1244]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Windows

**Dropbox:** No

**Description:** Forgefiend points for 2 hades autocannon should be 50 instead of 66

Powerfist for champions should be 12 instead of 20.

Powerfist for Lords is correct

**Comment by ilaunchbury** [comment]
Power fist cost should be fixed in the latest release (1.0.51).

I'll get the autocannon fixed.
