### ISSUE TITLE
Chaos - Chaos Space Marines: missing artefact for Khorne characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1245]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** The relic option for talisman of burning blood is missing for khorne characters

**Comment by ilaunchbury** [comment]
Can you specify which characters? It seems to be there for all the ones I have checked after selecting a Mark of Khorne.

**Comment by Rasputinprime** [comment]
They may be looking at a character when it doesn't have the mark applied; I just looked at a Chaos Lord in a World Eaters detachment and it auto-populated the Collar of Borgaster (or whatever) without the Khorne mark selected but not the Talisman. The Talisman appeared as an option after I selected the Khorne mark.

**Comment by ilaunchbury** [comment]
Yes, the Collar triggers off having World Eaters as a Legion, but the Talisman is available to everyone, so it triggers on selecting the Mark of Khorne.
