### ISSUE TITLE
Imperium - Astra Militarum: Weapon cost issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1247]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Heavy Bolter price incorrectly listed as 10pts, should be 8pts.
Twin Lascannon price incorrectly listed as 50pts, should be 40.

**Comment by alphalas** [comment]
What specific units have the issue? Need further info.

**Comment by GenWilhelm** [comment]
Tarantula has it's Twin Lascannon at 25pts.
Vendetta has it's compulsory Twin Lascannon at 50pts.
Vulture has it's Twin Lascannon at 50pts.
Vulture has it's compulsory Heavy Bolter at 10pts.

**Comment by alphalas** [comment]
I swear I've fixed those at least once -.-

**Comment by lotlp** [comment]
You did. I reported those before, along with the crassus issues, which /are/ fixed. So *shrug*

Additionally, the dominus triple bombard can only choose one from the weapons listed, save for the autocannon, while it is supposed to take up to two weapons in any combinations from the list.

**Comment by alphalas** [comment]
Sounds like the same issue the crassus had, max1s on the linked weapons kicking in
