### ISSUE TITLE
Chaos - Chosen validation errors with 2 lightning claws

### ISSUE THREAD

**Issue by darkscion0** [BSData/wh40k#1252]
![chosen](https://user-images.githubusercontent.com/8334966/29345621-55c717a4-8216-11e7-862a-46ae165cd620.JPG)
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Validation errors for Chosen with 2 lightning claws. 
Codex says up to 4 may "Replace his boltgun and bolt pistol with two lightning claws"

Validation Errors:
See attached.

**Comment by ilaunchbury** [comment]
This is fixed in v26 of the CSM file (in release 1.0.51). Please update your data.

**Comment by ilaunchbury** [comment]
This will be fixed when CSM v27 is released.
