### ISSUE TITLE
Grey Knights Relic restrictions 

### ISSUE THREAD

**Issue by Joshua137** [BSData/wh40k#1253]
**File/Catalogue:** Grey Knights v8

**BattleScribe version:** 2.01.05

**Platform:** iOS

**Dropbox:** No

**Description:** Currently in catalogue, relics are restricted to the selected warlord. While your warlord must be a Grey Knight in order to have access, they may be given to any Grey Knight Character.

**Comment by tekton** [comment]
I'm not sure I follow on this one- the relic section doesn't say that it goes to the Warlord just to a Grey Knight Character, which is how the selection currently works; you can mark Voldus as your warlord and take a relic on a Brother-Captain.

**Comment by Joshua137** [comment]
My apologies, tekton. Upon further investigation, issue was determined to be operator error.

**Comment by tekton** [comment]
@Joshua137 thanks for letting us know!
