### ISSUE TITLE
Space Marines - Inceptors have 2 assault bolters each

### ISSUE THREAD

**Issue by brestfloda** [BSData/wh40k#1254]
**File/Catalogue:** v21

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Each inceptor has 2 assault bolters in the codex, but they are only docked for 1 each in the roster

**Comment by flakpanda** [comment]
They are being charged correctly. Each assault bolter is 15 point, so 30 points a model.
