### ISSUE TITLE
Space Marines - devastators too many heavy weapons

### ISSUE THREAD

**Issue by brestfloda** [BSData/wh40k#1255]
**File/Catalogue:** v21

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** There is a constraint saying that you must equip 4 devastator marines with heavy weapons, but the codex says up to 4

**Comment by flakpanda** [comment]
There is nothing stopping you from removing the default 4 w.heavy weapons and adding regular boltgun marines. 
<img width="1498" alt="screen shot 2017-08-18 at 9 34 55 pm" src="https://user-images.githubusercontent.com/19719565/29482759-3cbaf4ee-845d-11e7-9e23-e756de191b7e.png">
