### ISSUE TITLE
T'au Empire: Longstrike's Fire Caste Exemplar ability missing from summary

### ISSUE THREAD

**Issue by nsmaassel** [BSData/wh40k#1265]
**File/Catalogue:** T'au Empire v11

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes

**Description:** When 'Summary' is selected under 'Include Profiles?', Longstrike's Fire Caste Exemplar ability disappears from his profile and the Selection Rules section.

**Comment by amis92** [comment]
Although true, please refer to #677. All other abilities are to be redone as profiles and will not show under model entry when `Summary` for `Include Profiles?` will be selected.

**Comment by nsmaassel** [comment]
Oh, didn't see it under the abilities section.  Thanks.
