### ISSUE TITLE
Chaos - Chaos Space Marines: Reaper Autocannon cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1266]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 1.04.92

**Platform:** Windows

**Dropbox:** No

**Description:** The point value of the Reaper Autocannon in the CSM Datafile is still shown with 18 points, it should be 15 according to the new Codex Heretic Astartes

**Comment by ilaunchbury** [comment]
This is fixed in v27 of the CSM file. It will be in the next release.
