### ISSUE TITLE
Chaos - Heretic Astartes - Black legion +1 to leadership

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#1275]
Hello!

A black legion detachment gives +1 LD to infrantry, bikes and helbrutes this is currently not reflected on the roster sheet.  

Any plans to include the +1 automatically?  
(Sounds like a painful request I'm sorry in advance)

**Comment by ilaunchbury** [comment]
I'm going to have to leave this one up to the player, I'm afraid. It's a change to the majority of units in the catalogue, adding a whole bunch of extra code, for something that should be managed by the player.
