### ISSUE TITLE
Chaos - Chaos Space Marines: Lord on Juggernaut should be able to take Khorne artefacts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1280]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Lord on juggernaut should be able to take the talisman of burning blood

**Comment by ilaunchbury** [comment]
Fixed in v29. All characters on god-specific steeds now have access to the relevant artefacts.
