### ISSUE TITLE
Feature request - Show Validation errors on roster

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#1284]
Hello!

As a tournament organiser, I receive a lot of battlescribe lists for validation.  It would be nice if the roster would show validation errors at the bottom of the output.    I could quickly see if a submitted list contains something strange. 

Thanks in advance

**Comment by alphalas** [comment]
That's an app feature, not something we can code in

**Comment by amis92** [comment]
Also @Drachnyen just keep in mind it would be insanely easy to just remove these warnings from print output. It's better if you require roster files and just open them in BScribe. :)
