### ISSUE TITLE
Chaos - Havoc Heavy Weapon / Champion Validation Error

### ISSUE THREAD

**Issue by darkscion0** [BSData/wh40k#1285]
**File/Catalogue:** File: Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Selecting invalid gear configuration for the Chosen Champion also triggers a validation error on the Havoc w/ heavy weapons (which are actually valid). When you correct the gear for the champion the validation error for the Havocs w/ heavy weapons goes away. See attachment. 

![havocs](https://user-images.githubusercontent.com/8334966/29439650-7225b6fa-8395-11e7-9b25-326f7b2a2a45.JPG)

**Comment by ilaunchbury** [comment]
Hi, your title said Chosen, but your screenshot shows Havocs? I'm assuming from the screenshot that you meant the aspiring champ in the Havoc squad.

I can't replicate this in v28 (which has just been released). Please try again in that version if you don't have it.

**Comment by darkscion0** [comment]
Yes, sorry, Havocs. 

I was on v28 but I can't reproduce it myself anymore either. I tried loading the old roster and I tried creating a new one and using the same scenario doesn't show the validation errors.

**Comment by ilaunchbury** [comment]
OK, I'll close this for now then.
