### ISSUE TITLE
Chaos - Chaos Space Marines: Plasma pistol Chosen should be able to take a chainsword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1287]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Chosen: there is an error when you select Chosen w/ Weapon Options. 
Any chosen can swap their boltgun for a chainsword. Also, up to 4 can swap a bolt pistol for a plasma pistol. This option treats them as mutually exclusive i.e. if you swap the boltgun for a chainsword, you cannot then swap the bolt pistol for a plasma pistol. This is incorrect. You can do both, provided that only 4 members in the unit swap their bolt pistol for plasma pistols. 
Thanks for all your hard work! Keep it up dudes!

**Comment by ilaunchbury** [comment]
Fixed in v29. Chosen w/ weapon option can take a plasma pistol and chainsword OR plasma pistol and boltgun.
