### ISSUE TITLE
Chaos - World eaters should have Berserkers as troops

### ISSUE THREAD

**Issue by Jeace** [BSData/wh40k#1288]
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** refering to chaos index p.45, khorne berserkers are troops instead of elites for World Eaters Keyword. Unable to find anything countering this in any FAQ or in the new Codex.

**Comment by ilaunchbury** [comment]
The rules in the Codex replace the rules in the Index for World Eaters. There is no rule in the Codex which allows World Eaters to take Berzerkers as Troops.

Unless GW release an FAQ which says they can be Troops, they cannot be Troops.

**Comment by Jeace** [comment]
https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/08/40K_8th_ed_Update_Codex_Chaos_Space_Marines_ver_1.0.pdf

new FAQ : berserkers are now officially troops for world eaters (and noise marines for emperor's children)
