### ISSUE TITLE
CODEX: SPACE MARINES - Official Update Version 1.0

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#1291]
**File/Catalogue:**  Space Marines

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.

Changes by the faq:
Page 131 – Sergeant Equipment
Add ‘Combi-grav’

Page 137 – Chaplain Grimaldus, Unmatched Zeal
Change the first sentence of this ability to read:
‘If you roll a hit roll of 6+in the Fight phase for a model
in a friendly Black Templars unit that is within 6" of
Chaplain Grimaldus, that model can immediately make
another close combat attack using the same weapon.’

Pages 139 and 190 – Wrist-mounted grenade launcher
Change the AP value to read ‘-1’.

Page 148 – Tactical Squad, Wargear Options
Add a new bullet point as follows:
‘The Space Marine Sergeant may take melta bombs.’

Page 149 – Scout Squad, Concealed Positions
Change this ability to read:
‘Concealed Positions: When you set up this unit during
deployment, it can be set up anywhere on the battlefield
that is more than 9" from the enemy deployment zone
and any enemy models.’

Page 154 – Company Veterans, Wargear Options
Change the second bullet point to read:
‘• Any model may replace their bolt pistol with a
storm shield or an item from the Melee Weapons or
Pistols lists.’

Page 156 – Reiver Squad
Replace the first bullet point with the following:
‘• All Reivers in the unit may replace their bolt carbine
with a combat knife.
• The Reiver Sergeant may replace either his bolt
carbine or heavy bolt pistol with a combat knife.

Pages 160, 161 and 188 – Grenade harness
Change the AP value to read ‘-1’.

Pages 162, 169 and 189 – Melta bomb
Change the Abilities text to read:
‘You can re-roll failed wound rolls for this weapon if the
target is a Vehicle.’

Page 175 – Stalker, Damage chart
Change the third value under ‘Remaining W’ to
read ‘1-2’.

Page 196 – Relics of the Chapter
Add the following sentence:
‘You can only use this Stratagem once per battle.’

Page 201 – The Sanctic Halo
Change the first sentence to read:
‘Ultramarines Captain or Chapter Master only.’

Page 208 – Space Marine Points Values, Other Wargear
Add the following lines:
‘Auxiliary grenade launcher | 1
Centurion assault launchers | 3
Ironclad assault launchers | 5’

**Comment by Guy-Markman** [comment]
[](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/08/40K_8th_ed_Update_Codex_Space_Marines_ver_1.0.pdf)

**Comment by ilaunchbury** [comment]
There is already an open task for these updates, #1172. Closing this as a duplicate.
