### ISSUE TITLE
Chaos - Heretic Astartes - Incorrect point Value for Baleflamer 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#1299]
Baleflamer is listed as 60 points in datafiles, new cost in codex is 30 points.

Thanks.

**Comment by ilaunchbury** [comment]
What unit is this on? It's correct on the Heldrake in v29.

**Comment by Drachnyen** [comment]
Hello @ilaunchbury 

Yeah on the heldrake, sorry for lack of precision 

My files are using v29 and I'm still seeing 60 points 

![img_2081](https://user-images.githubusercontent.com/16340056/29495188-b1fc57d6-8587-11e7-9b4a-74d6aa8b3ec1.PNG)

**Comment by GenWilhelm** [comment]
It was fixed in v30, which was 3 hours ago. It typically takes about a day for updates to appear on appspot.

**Comment by Drachnyen** [comment]
Just deleted all data and updated to v30 and I'm still getting heldrake baleflamer at 60 points

![img_2083](https://user-images.githubusercontent.com/16340056/29497610-f46900fc-85b8-11e7-9efc-35d6ea5eb1d4.PNG)

**Comment by GenWilhelm** [comment]
I just download the catalogue from appspot, and it's showing as 30pts on my end.

Does it still show the incorrect cost if you start a new roster?

**Comment by Drachnyen** [comment]
Ok found the issue

The CSM heldrake is ok. 

It's the heldrake in the Thousand Sons catalog that is incorrect

**Comment by ilaunchbury** [comment]
That one won't get updated until Thousand Sons get a Codex.

**Comment by Drachnyen** [comment]
Good to know!  Thanks
