### ISSUE TITLE
GK GMDK can select one too many Psychic Powers

### ISSUE THREAD

**Issue by splitstriker** [BSData/wh40k#1301]
**Description:** 

Thanks for the GK update. The Grandmaster in Nemesis dreadknight comes armed with 2 nemesis dreadknight fists, rather than paying 25+10 points for them. He also can manifest 2 psychic powers, but can actually only pick one power Sanctic discipline (rather than the two that is on battlescribe currently). This is from the latest GK codex.

**Comment by tekton** [comment]
It's 35 for a pair of fists, and 25 for a single fist- so that is accurate.
