### ISSUE TITLE
Other Grey Knight inaccuracies

### ISSUE THREAD

**Issue by splitstriker** [BSData/wh40k#1302]
**Description:** 

- Grey knight Justicars / Paragon (for paladins), cannot adjust their melee weapon (e.g. to falchions or hammers)
- Stormraven Gunship comes with two stormstrike missiles and doesn't have to pay for them.

**Comment by tekton** [comment]
1) This does work right now, not sure what you're seeing
2) They do have to pay for them, just like all other wargear
