### ISSUE TITLE
Grey Knight Apothecary should not be able to take falchions

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k#1306]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** In wargear section states apothecary cannot take falchions.

**Comment by GenWilhelm** [comment]
An apothecary may take a single falchion, according to their datasheet.

**Comment by tekton** [comment]
But it does say it can take a single Flachion, which is what is there as an option.
