### ISSUE TITLE
Astra Militarum Cyclop Demolition Vehicle in wrong location

### ISSUE THREAD

**Issue by neonthefox** [BSData/wh40k#1310]
**File/Catalogue:**  

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** no

**Description:** The Cyclops demolition vehicle for Astra Militarum ( No Death Korps of Krieg) is listed as a fast attack. This is incorrect as the Cyclops Demolition vehicle should be in heavy support.

**Comment by GenWilhelm** [comment]
This was fixed in 1bef27e12ae2e356aaa6cba83e4a4650ae2a1fdf, which should be out with tonight's release.
