### ISSUE TITLE
Dark Angels - Deathwing Terminator Points

### ISSUE THREAD

**Issue by Smellageddon** [BSData/wh40k#1311]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

The weapon costs for Deathwing Terminators need to be updated in line with the new points costs from the Space Marine Codex.

Powerfist - 12
Thunder Hammer - 16
Lightning Claws 8/12 (single/pair)

Thanks

**Comment by Thairne** [comment]
Non-codex marines don't have access to the codex points.
