### ISSUE TITLE
Chaos - Chaos Space Marines - Obilterator Mark of Chaos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1313]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Obliterators get to choose a mark of chaos, which is missing in the list of options. 

Keep up the great work.

**Comment by ilaunchbury** [comment]
As this and more have been reported in #1314, I'm closing this one.
