### ISSUE TITLE
Chaos - Chaos Space Marines: Units missing Mark option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1314]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Mutilators, chaos spawn, defiler, forgefiend, maulerfiend, and obliterators should all be able to choose a mark of chaos now.  It's not available as of v 29.

Keep up the great work, folks!

**Comment by ilaunchbury** [comment]
Fixed in v31.
