### ISSUE TITLE
Chaos - Chaos Space Marines: Plague sword points incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1315]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Hello,

I noticed the plague sword option for the Plague Marine Champion is still listed as the Index value of 3 points. This dropped down to 1 point in the new codex.

Sincerely,

Matthew Murrell

**Comment by ilaunchbury** [comment]
Fixed in v31
