### ISSUE TITLE
Renegades and Heretics - Chimera - Lasgun arrays entry missing in exported rosters

### ISSUE THREAD

**Issue by rajcze** [BSData/wh40k#1324]
**File/Catalogue:** Chaos - FW Renegade and Heretics v12

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** Chimera entries are missing "2x Lasgun Arrays" entry in all the export formats - Save as HTML, Share, View, Print...  The Hull/Pintle/Turret weapons are listed just fine.

**Current state:**
```
+ Dedicated Transport +
Chimera [5 PL, 104pts]: Heavy Flamer, Multi-laser, Storm Bolter
````

**Expected state:**
```
+ Dedicated Transport +
Chimera [5 PL, 104pts]: 2x Lasgun Array, Heavy Flamer, Multi-laser, Storm Bolter
````

**Comment by ilaunchbury** [comment]
This seems to be ok in v13.  Please update your files and try again.

**Comment by rajcze** [comment]
Updated to v13 (had battlescribe remove and download all data, to be specific), and still the same.
I have:
"BattleScribe v2.01.04.92" (Running on Linux, should that make any difference)
"Warhammer 40,000 8th Edition v23"
"Chaos - Renegade & Heretics v13"
"Imperium - Astra Militarium v42"

Both R&H and Astra miss the "2x Lasgun Array" in exports/prints. Anything else I should/could try to debug/fix the issue?

Thanks!

**Comment by ilaunchbury** [comment]
Are you using Full output or minimal output? Minimal will only display selected options, not defaults.

**Comment by rajcze** [comment]
Ah, that seems to be it - the "save as html" and "share roster" options seem to be producing the minimal output, but "view"/"print" can be set to "full".
Definitely not a bug in the datafile, then, thanks for pointing out the full/minimal output difference - using the view/print option is a workable workaround. Thank you!

**Comment by Penallegion** [comment]
easiest ticket i ever did :)
