### ISSUE TITLE
Battleforged Army can't add Relic unit

### ISSUE THREAD

**Issue by Zanetsuken** [BSData/wh40k#1339]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:**  Have a spearhead detachment with 3x Hellblasters and 1x Captain. Have added the FW Astartes as a child of this spearhead detachment, but when adding a relic i get an error saying maximum relic units is 0

"Relic: If your army is Battle-forged, no Detachment can contain more Relic units than it does non-Relic units of the same Battlefield Role. You can, however, include a single Relic Lord of War unit in your army even if it contains no non-Relic Lord of War units (you cannot include second and subsequent Relic Lord of War units unless they are taken in a Detachment that contains at least as many non-Relic Lord of War units). In addition, as long as a Battle-forged army included at least one RELIC unit, you gain access to the RELIC OF ANCIENT GLORY stratagem.
"

So in a spearhead detachment with 3 heavy support units, it should be able to add a relic unit.

**Comment by alphalas** [comment]
Do the forge world detachment first then the regular as a child.
