### ISSUE TITLE
Imperium - Blood Angels: Assault marines should be able to take melta gun

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1340]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Blood Angels Assault Marines can take meltaguns as can any other SM Assault Marines (FAQ released by GW). Point value: 17

**Comment by ilaunchbury** [comment]
If you add a marine with a special weapon, he has the option to take a flamer, meltagun or plasma gun. Click on the Marine and then his weapon after adding him to select his weapon.
