### ISSUE TITLE
Death Guard Plague Marines haven't been updated

### ISSUE THREAD

**Issue by OnkelMo** [BSData/wh40k#1343]
As the title says, the Plague Marines for the Death Guard haven't been updated. If you select them, they still cost 21 points and can't take any of the new weapons (except for the Blight Launcher).

The updated version of the Plague Marines is already available for the general Chaos Space Marines. Please update them for the Death Guard as well!

Thanks.

**Comment by ilaunchbury** [comment]
As Death Guard are still an Index Legion (until their Codex is released next month), we are only supporting the Index options within the catalogues. The same applies to Thousand Sons and the Space Marine chapters not included in Codex: Space Marines.

**Comment by alphalas** [comment]
If you want to include the new points values units; add a child attachment of codex CSM.
