### ISSUE TITLE
Imperium - Space Wolves: Terminator Njal validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1348]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Validation error when using Njal Stormcaller in Runic Terminator Armuor: "Roster has 1 too many selections of Njal Stormcaller in Runic Terminator Armour (maximum 0)". Occurs every time the character in question is added, but appears only after any other unit is added to roster. Does not occur for non-terminator variant of the character.

**Comment by ilaunchbury** [comment]
@penguin20000, replicated this in v10. I wasn't able to fix it except by deleting the constraints completely and recreating them.
