### ISSUE TITLE
UPDATE KHORNE BERSERKERS TO TROOPS

### ISSUE THREAD

**Issue by Karkhash** [BSData/wh40k#1350]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

In the recent GW FAQ, they update the abilities for the Khorne Berserkers, and now they are troop choice when they're in a World Eaters Detachment. Please update the BS Repository

**Comment by GenWilhelm** [comment]
This has already been changed. Please ensure your data is up to date (CSM v31).
