### ISSUE TITLE
Cultists, Soulreaper cannon have Incorrect Points

### ISSUE THREAD

**Issue by Spibb** [BSData/wh40k#1354]
**File/Catalogue:** 

**BattleScribe version:** 2.01.
2.01

**Platform:** Windows/iOS/Android/Mac/Linux

iOs

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Cultists are listed as 5 points each but the Chaos Index FAQ / Errata indicates they are 4 points each. The Soulreaper Cannon is lsited at 18 points but it is clarified as 15 points in the eratta.

**Comment by ilaunchbury** [comment]
Please update your files. These were both fixed in 1.0.56, three days ago.
