### ISSUE TITLE
Aeldari FW Corsairs - Felarch Weapon Swap

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k#1355]
Felarch for Skyreavers and Reavers has not been updated for the FAQ. Felarch can select any standard weapon (Lasblaster, Shardcarbine, Shuriken Catapult) and the void sabre and dissonance pistol are added in addition to the standard weapon.

**Comment by FarseerVeraenthis** [comment]
Oh, I missed that one...!
