### ISSUE TITLE
Imperium - Space Wolves: Add keywords to entries

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1360]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** 

Any chance we can get keywords to show on overview for units like Necrons data

**Comment by ilaunchbury** [comment]
The Skyclaw issue has already been logged under #1286 so I'm removing it from your ticket. I'll leave it open for the request to add keywords.

**Comment by ilaunchbury** [comment]
No longer required following BS updates.
