### ISSUE TITLE
Chaos - Chaos Space Marines - Relic validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1361]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Daemon Prince cannot take Murder Sword because they are not able to field power swords.

**Comment by GenWilhelm** [comment]
That is correct.

**Comment by balldrix** [comment]
You have closed this issue but the murder sword is still showing as an option for a Daemon Prince

**Comment by GenWilhelm** [comment]
Oh I see, you're requesting relics to be validated.

**Comment by ilaunchbury** [comment]
Unfortunately, it is not currently possible to support this level of validation in Battlescribe without implementing relics individually for each character, which is a significant piece of work.

Until such time as this becomes an option, you will need to use the honour system. Each relic does contain a note (where needed) as to the constraints on equipping it.

**Comment by cartag** [comment]
This is completely possible to do, and you'd really only need to set up something separate for the daemon prince. Right now you don't even hide the base weapon when anybody takes a relic, something else easily possible.

**Comment by cartag** [comment]
Now that I think about it, you could just add the relic weapons to the champion equipment groups. Set validation in the entry itself, just link to the group. 

Say, Axe of Blind Fury. Add in the champion melee equipment since a power axe is in the entry group also.

**Comment by ilaunchbury** [comment]
I've updated it so that it at least doesn't give you the option to take a relic weapon until you select the prerequisite base weapon. I'll look at adding the relics into the character weapon list once I'm back from holiday.
