### ISSUE TITLE
Chaos - FW Heretic Astartes - Sonic Dreadnought doom siren

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#1372]
**File/Catalogue:** FW Heretic Astartes v9

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Sonic Dreadnought's doom siren still has the old profile - Assault D3 instead of Assault D6.

**Comment by ilaunchbury** [comment]
I'm not entirely convinced it should be updated, given it's a "FW" model and the updated profile hasn't been released for them. It also still has the Index PL value.

I'm on holiday for a week now, so if you want to go ahead and update it, feel free.
