### ISSUE TITLE
Chaos - Chaos Space Marines: Champion Equipment choice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1374]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Space Marine v31:  Aspiring Champions have been faq'd to let them take 1 melee weapon and 1 boltgun/combi, whereas the Codex is either 2 melee or 1 boltgun/combi.

**Comment by ilaunchbury** [comment]
Not sure what you're saying here? What you have described is how it is working in CSM v31. Champions can take up to two weapons, one of which can be a combi.
