### ISSUE TITLE
T'au Empire - Keyword Display Request

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1375]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** This is not a bug but a recommendation, I think you should put keywords to the models and units because at that version of the game is very crucial. 
Thanks on advance.

**Comment by amis92** [comment]
Unless someone else does it, it'll wait for BattleScribe to support category display.
