### ISSUE TITLE
Aeldari - Craftworlds - Keyword Display Request

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1381]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.04

**Platform:** Android

**Dropbox:** No

**Description:** Keywords will help a lot if added.
Thank you in advance.

**Comment by FarseerVeraenthis** [comment]
Just for information, all units currently have keywords assigned to them, they are just not displayed by Battlescribe at present.
We have requested this upgrade but it has not been forthcoming so far, the work around is to recreate all the keywords as profiles and attach them to each unit - a massive task on a CAT as big as the Aeldari one, hence why I have labelled it as such.
This "bug" report will stay open until it is fixed - one way or the other :smile:
