### ISSUE TITLE
Imperium - Blood Angels: How to add FW units?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1382]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.04

**Platform:** Android

**Dropbox:** No

**Description:** Forgeworld units to be added?
Beucase as things are now you need to add the Imperial - FW Adeptus Astartes detachment to add things from Forgeworld and that mess up the army build. Please tell me I'm just doing it wrong :)

**Comment by Crowbar90** [comment]
Forgeworld units are in the FW Adeptus Astartes catalogue, which should be used as a child or (preferably) parent force. Just read the Wiki pages [Creating Detachments Using Multiple Factions](https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions) and [Using FW Relic units](https://github.com/BSData/wh40k/wiki/Using-FW-Relic-units) and everything will be clear.
