### ISSUE TITLE
Genestealer Cult Purestrain Genestealer Points

### ISSUE THREAD

**Issue by Falco4077** [BSData/wh40k#1385]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Falco4077** [comment]
Damn it. Didn't mean to post this yet. Anyway, I have the 40k 8th ed Aug 7th version of Battlescribe mobile. It lists Purestrain Genestealer as 18 pts per model and 3 pts per model for their talons. The points were reduced to 10 pts per model to match Tyranid Genestealers, a couple of errata ago,and their talons dropped to 0 pts. I know that their per model pts went up to 15 in the July errata. Just thought someone would like to know that the points are wrong.

**Comment by GenWilhelm** [comment]
Mobile format data is a separate repo, which you can find here: https://github.com/BSData/wh40k-mobile-format
