### ISSUE TITLE
Chaos - Thousand Sons: Updated points values from C:CSM

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1389]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Fixes from the Chaos Space Marines codex needs to be added to the Thousand Sons.
Heldrake Baleflamer is 30 pts, not 60
Predator is 90 pts base not 102
Vindicator is 135 base, not 160
Cultists are 4 pts, not 5
Soul Reaper Cannon is 15 pts, not 20
Forgefiend Hades Autocannon is 25 pts, not 33
Reaper Autocannon is 15 pts, not 18
Daemon Prince melee weapons are all 10 pts
Rubric Marines can always have 1 soul reaper cannon and 2 in a squad of 20

**Comment by flakpanda** [comment]
Thousand Sons Legion still uses the Index, and they are not apart of Codex: Chaos Space Marines as they cannot be selected as a legion. If you wish to use the new points, please use a child detachment of CSM.

**Comment by amareisdk** [comment]
I'm sorry but this is a misconception.
The tournaments are playing with the new point values and even Games Workshop has verified that Thousand Sons can use the new psychic powers. The psychic powers have even been updated in the Battlescribe file, why not the points?

**Comment by flakpanda** [comment]
Yes is it true that GW said you can use the new psychic power, but that is the only thing they said you can use. C:CSM clearly states nothing from the book can choose <Legion> Thousand Sons. Because of this Thousand Sons, and Death Guard, still use the Index for non specific units.

**Comment by amareisdk** [comment]
For rules yes, not for points values. This would invalidate units simply based on the points cost.
Why would rubric marines have different pts costs and rules between the codex and index?
I've asked them to clarify this in an faq, but come on. It's quite clear that there is 1 pts cost for each unit. They even updated the pink horrors and other troops demons pts cost for this reason.
Thousand Sons predators has no advantage over a csm predator. So why should there be a points difference?

**Comment by amareisdk** [comment]
If the points cost went up I bet you wouldn't have a problem changing it.

Anyway, I'll get GW to release an official reply. Then I'll be back. Unless you change your mind.

Until then I guess I'll just not use Battlescribe for my Thousand Sons. Like every other tournament player.

**Comment by alphalas** [comment]
It's the same exact thing with DG, BA, DA, and SW. And they do say to use the index for everything default.

**Comment by amareisdk** [comment]
Yeah, that's just not making sense. So SW vinidcators are being played at 160 pts? Don't think so.
The vindicator pts cost is even the same between the two codi.

**Comment by flakpanda** [comment]
After talking about it with someone, there is a community article I was unaware of doing the same thing for Chaos as it did for Marines.

**Comment by amareisdk** [comment]
Thank you for reopening :)
Much appreciated. Looking forward to using Battlescribe for my Tsons again.

**Comment by amareisdk** [comment]
And just to clarify. I really appreciate the work you guys do and that you are keeping to the the rules so strictly even if it means I have to post counter arguments ;)

**Comment by ilaunchbury** [comment]
At this time, there has been nothing official from GW to say that non-Codex CSM factions should **always** use the point values from the Codex. This is because people who haven't bought the Codex (which doesn't cover Thousand Sons) should be able to solely use the Index, and the points, abilities and rules for Thousand Sons in Battlescribe therefore reflect that.

As mentioned in the earlier comments, if you really want to use the new points, you can add a child detachment of vanilla CSM.

Alternatively, go ahead and update your copy of the files. It doesn't require any major programming knowledge and will probably only take you a couple of hours.

**Comment by amareisdk** [comment]
As I asked GW and they replied with this article: https://www.warhammer-community.com/2017/07/05/codexes-your-questions-answered-july-5gw-homepage-post-2/

I'm this is stated this part:
"In all future publications and official events though, it will be assumed that you’re using the most recent rules and Datasheets. It will also be assumed that you’re using the most up to date points for matched play, in this case, those included in the codex."

As I've said, there is one pts cost. The most recent. Now, backed by GW. Can we please have the points cost updated?

**Comment by alphalas** [comment]
#1414 - read it
