### ISSUE TITLE
Imperium - FW Death Korps of Krieg V18 - Formating

### ISSUE THREAD

**Issue by jShepherddog** [BSData/wh40k#1390]
**File/Catalogue:**  FW Death Korps of Krieg V18

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** 
Is it possible to we can have the formatting cleaned up for the **Death Korps of Krieg Infantry Squad** entry and the **Death Korps Combat Engineer Squad**? Each individual model in the unit is listed out below the Squad entry and it makes the Army list many more pages then it needs to be, Having just 3 or four these squads caused the roster list to be way to big and redundant to have to scroll through during game play, especially for a mostly Infantry heavy Army like the Death Korps of Krieg. Also I'm not sure why the Grenades and Shotguns need to be added to each individual engineer as these are their standard equipment.
![dkokinfantry](https://user-images.githubusercontent.com/30080443/29838183-772fabf6-8cc8-11e7-8fc8-ec9d299788ed.JPG)
![image](https://user-images.githubusercontent.com/30080443/29839018-dd8d8628-8cca-11e7-9f7f-196c56e38748.png)

Both of these entries would really benefit from following the ** Death Korps Grenadier Storm Squad** formatting, as it is concise and still offers all the editable options that the Engineer Squad and the Infantry Squad entries would need to have.

![image](https://user-images.githubusercontent.com/30080443/29839064-ff2a4c8a-8cca-11e7-8ba0-01dcd7904c97.png)

**Comment by CrusherJoe** [comment]
I'm almost certain there was a reason I did it the way I did, but that may have been due to my limited understanding of how to do things correctly at that time. I agree that's a mess -- I'll look at it and see what can be done to clean it up.
