### ISSUE TITLE
[Update] Space Wolves Wargear is at Index values, not updated to follow Codex Adeptus Astartes

### ISSUE THREAD

**Issue by halsterr** [BSData/wh40k#1394]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** The points for wargear in the Space Wolves section is the Index values when they should match those of the Codex Adeptus Astartes/Space Marines as per in this article. https://www.warhammer-community.com/2017/07/22/the-other-angels-of-death-and-codex-space-marines/

For example, a Space Wolves Powerfist is 20 points (as per the index) when it should be 12 (as per the Codex).

**Comment by alphalas** [comment]
No it shouldn't. Space wolves, Blood angels, and dark angels all should continue to use their index values until the codex is released.  In the meantime, if you want to use units that are updated in the codex,  you can use a child attachment from Cat Codex space Marines
