### ISSUE TITLE
Imperium - Dark Angels: Company Master rules question

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1395]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Small complaint but I believe the dark angels company master follows the captain rules and gives "rites of battle" to `<chapter>` models whereas in the data log it states `<dark angels>`  am I wrong in thinking that a successor chapter following dark angels rules would lose out on company master (captain) benefits?

---
Edited to fix formatting.

**Comment by Phoenixdirk** [comment]
Sorry I posted this and didn't realise certain symbols made text disappear. So to clarify rites of battle to chapter models whereas in the log its dark angels only
