### ISSUE TITLE
Chaos - Death Guard: Updated points values from C:CSM

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1398]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos codex point and power level values have not been updated into the Death Guard roster yet.

**Comment by ilaunchbury** [comment]
At this time, there has been nothing official from GW to say that non-Codex CSM factions should use the point values from the Codex.

In addition, DG will be getting their Codex in a couple of weeks. Until then, add a child detachment of CSM if you really want to use the new points.
