### ISSUE TITLE
Imperium - Dark Angels

### ISSUE THREAD

**Issue by likwid-dzign** [BSData/wh40k#1401]
Currently no option to equip Company Veterans with Combat Shields.

Index1, pg 107, clause 3 under the selectable datasheets.

**Comment by Thairne** [comment]
I dont see it.
Said page links to Company Veterans on P26.
3rd clause tells you they can take pistol or melee weapons.
Neither pistol nor melee weapon lists contain a combat shield.

You can take a Storm Shield however, which is available.

**Comment by likwid-dzign** [comment]
![screenshot_20170902-170312](https://user-images.githubusercontent.com/29274769/29993676-032f4766-9001-11e7-95eb-29cebcc6189b.jpg)
