### ISSUE TITLE
Primaris Captain with Power Fist - Unit to Add

### ISSUE THREAD

**Issue by thebiggeordiegeek** [BSData/wh40k#1408]
The store Birthday Captain has his own profile, I have uploaded a copy to drop box so you can see it for yourself.

But unit or option to change the Captain needs adding to the Space Marines catalogue, assuming that Blood Angles, Space Wolves and Dark Angels can take him too.

https://www.dropbox.com/s/hblyxpv9v3g5mf6/Captain%20with%20Power%20Fist%20Rules.pdf?dl=0

**Comment by thebiggeordiegeek** [comment]
The unit has appeared in Blood Angels, but I can’t see it in the vanilla Space Marine list yet

**Comment by alphalas** [comment]
I think @flakpanda's been a bit busy dealing with Harvey aftermath - I'm sure someone will get it added soon

**Comment by thebiggeordiegeek** [comment]
Oh cripes now I feel like a dick!

Hope he is ok and stuff, I guess stuff like that is something that never springs to mind living in such a mild climate here in the UK.

**Comment by alphalas** [comment]
It's cool man - I'm in a similar boat living up in the mid Atlantic area - the one meme I've seen floating around that is a radar image of a hurricane with the caption of "this is why I live where the air hurts my face" is very apt lol
