### ISSUE TITLE
Elysia Tarantulas: THB

### ISSUE THREAD

**Issue by quindraco** [BSData/wh40k#1409]
**File/Catalogue:** FW Elysians V8

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Tarantula turrets, under Heavy for the Elysians, can take Twin Heavy Bolters for 14 points.  My copy of Battlescribe lists them as 17.  I tried submitting a patch modifying the cost to 14, but I guess I screwed up, because the issue is persisting.

**Comment by alphalas** [comment]
There hasn't been a release pushed yet. It'll be fixed when we do that.
