### ISSUE TITLE
REFERENCE: CODEX vs INDEX; SW, Codex omitted options.

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#1414]
16/11/2017 Update:
https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/warhammer_40000_designers_commentary_en-1.pdf

![n3g7779rddyz](https://user-images.githubusercontent.com/22036809/32919930-6b27d406-cb1f-11e7-8356-444a10cfbe71.jpg)

**Comment by amareisdk** [comment]
But you are only including the top part of that answer from the community article. Please read the entire thing. One part is related to changing the rules. The second part is concerning official rules and events:
"In all future publications and official events though, it will be assumed that you’re using the most recent rules and Datasheets. It will also be assumed that you’re using the most up to date points for matched play, in this case, those included in the codex."

"...most up to date points...in the codex."

Are you just going to ignore this part?

**Comment by alphalas** [comment]
No - because you're looking at the bit that says in the future- right now, the most up-to-date publication that applies to TS/DG/BA/DA/SW is the Index, not any of the codecies because THEY ARE SEPARATE FROM THE CODECIES.

**Comment by amareisdk** [comment]
The future bit is referring to the fact that GW will assume that you are using the most up to date points when talking about points in their publocations. 

You can't take two words from a sentence and bend to your fit your views.

**Comment by alphalas** [comment]
I just edited the OP to address your question- this is the stance of This Repo until GW says otherwise.

**Comment by amareisdk** [comment]
Link in bottom doesn't work.

**Comment by alphalas** [comment]
Fixed

**Comment by MisterTsumi** [comment]
Does the 16/11/2017 update indicate that you have reconsidered updating outdated Index points costs based upon Codex updates?  Because the GW FAQ definitely seems to indicate that points costs for models and wargear should come from the most recently released book, and not just for those which have a released Codex (i.e. DA/BA/SW/TS/etc).

**Comment by alphalas** [comment]
We’re waiting on confirmation that explicitly states it; more then a FB comment that is unsure of itself.

**Comment by GenWilhelm** [comment]
It's stated in the examples at the bottom, namely the last paragraph.

> *Codex: Craftworlds* contains rules and points costs for all your Autarch's wargear so you would use those in place of the ones from *Index: Xenos 1*.

**Comment by MisterTsumi** [comment]
Which is exactly the point.  Codex: Chaos Space Marines contains rules and points costs for all the Heldrake wargear (along with the Vindicator, Rubric Marines, Reaper Autocannon, and all the other mis-costed Thousand Sons models and wargear).  Therefore they should be used in place of the ones from Index: Chaos.  Exactly as described in the most recent FAQ.

**Comment by alphalas** [comment]
Except that you're talking about two separate distinct factions(CSM vs TS), not one (Aeldari). Like I said, until it is officially confirmed, it says as is.

**Comment by GenWilhelm** [comment]
Ah yes, I should have read more closely. As @alphalas says, both examples are within a contained faction, rather than borrowing from another faction.

I'm personally of the opinion that sub-factions should use their parent's codex for points, rules, etc. but there are significant costs involved in making these kinds of sweeping changes, and we don't want to jump the gun only to have to undo everything later.

**Comment by skonk** [comment]
![image](https://user-images.githubusercontent.com/621514/32950017-c13851fe-cb9c-11e7-9af4-3f9349ddbc06.png)

**Comment by alphalas** [comment]
@skonk that’s still saying “if you have it”, meaning default is still Index. We are not changing it unless GW addresses it in faq.

**Comment by skonk** [comment]
![image](https://user-images.githubusercontent.com/621514/32950298-c39e4df8-cb9d-11e7-95d6-461a43df9ba2.png)

**Comment by StealthKnightSteg** [comment]
Is it an idea to mark index options in the lists? I was looking at Space Marines Venerable Dreadnought and only having the Codex made me question the options and needed to look it up why it was so.

**Comment by alphalas** [comment]
We are trying to avoid that in most cases - tags are generally agreed upon to be a bad idea in BS

**Comment by StealthKnightSteg** [comment]
maybe as groups then? now you have Dreadnought Arm Weapons and Dreadnought Heavy Weapons, could add Dreadnought Index Heavy Weapons, might be a bit more work that way. (just thinking aloud)

**Comment by alphalas** [comment]
This really is a discussion that belongs on the gitter more I think - not to cut you off here but I think more discussion can happen there

**Comment by StealthKnightSteg** [comment]
true.
