### ISSUE TITLE
Impreium - Space Marines - Space Marine Captain has unremovable pistol

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#1422]
**File/Catalogue:** Imperium - Space Marines

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:**
The basic Space Marine captain is added to my rosters with a bolt pistol that cannot be removed via the wargear selections.  It still shows up on the roster, even if the pistol selection is set to (None) or another pistol (including a second bolt pistol)

**Comment by flakpanda** [comment]
The captain comes with a bolt pistol and has no way of exchanging it.

<img width="513" alt="screen shot 2017-09-03 at 2 48 28 pm" src="https://user-images.githubusercontent.com/19719565/30006137-49f06b92-90b7-11e7-91a2-0b8c0641a959.png">

**Comment by toadchild** [comment]
My apologies!  Thanks for the detailed response.
