### ISSUE TITLE
Space Marine Terminator Captain Wrist Mounted Grenade Launcher 

### ISSUE THREAD

**Issue by nwrobinson** [BSData/wh40k#1424]
**warhammer 40,000 base / space marines** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS

**Dropbox:** Yes

**Description:** thanks for the work you do. Space Marine Captain in Terminator option should be able to equip a wrist mounted grenade launcher with his power first, as seen in the new store promo figure.

**Comment by flakpanda** [comment]
After selecting a power fist, the option appears to take one

<img width="1498" alt="screen shot 2017-09-04 at 1 07 33 am" src="https://user-images.githubusercontent.com/19719565/30013729-c8f45588-910d-11e7-88a6-59d2df25a6cf.png">
