### ISSUE TITLE
Imperium - Dark Angels: Veterans should be able to take Combat Shields

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1425]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Dark Angels Company Veterans, as per the footnote on the index, can take Combat Shields in addition to the standard wargear for 5 points. This option is not currently in Dark Angels V25

**Comment by Thairne** [comment]
Where? I cannot find Combat Shield in the entry anywhere. You get Storm Shields, which are available.

**Comment by Totally-Not-Cypher** [comment]
http://imgur.com/nS29wXz

**Comment by Thairne** [comment]
Oh. I see. So this is specific to our chapter for.. reasons.
