### ISSUE TITLE
Imperium - Adeptus Mechanicus: Sydonian Dragons shouldn't have access to phosphor serpenta

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1426]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Sydonian dragons can not buy the phosphor serpenta.
Thanx for fixing 😃

**Comment by Thairne** [comment]
From the Index:
Any model cmay take a phosphor serpenta.
