### ISSUE TITLE
 Imperium - Adeptus Mechanicus: Dunecrawler weapon profile incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1427]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Onager dunecrawler.
When choosing the wespon "neutron laser". It should instead be "neutron laser and cognis heavy stubber". This is NOT the same extra heavy stubber that you can pic with the other weapon chooises. 
So if you choose "Neutron laser and heavy stubber" you can have two heavystubbers, and both must be payed for in points. 
Sorry for my poor english and thanx for the help 😃

**Comment by Thairne** [comment]
And this is exactly how it is.

![grafik](https://user-images.githubusercontent.com/8590840/30111804-6a4067da-930f-11e7-94af-62c1b4f4b02e.png)

It may be different on an iFruit, but I do now own such a thing. If it is, it is a bug in BS.
