### ISSUE TITLE
Brimstone cost not correct

### ISSUE THREAD

**Issue by flakpanda** [BSData/wh40k#1428]
Brimstones cost 3 points period, instead of 3 points per model.

<img width="293" alt="screen shot 2017-09-04 at 1 15 11 pm" src="https://user-images.githubusercontent.com/19719565/30035784-3f798ab0-9173-11e7-9cc4-ba34468b86d1.png">

**Comment by flakpanda** [comment]
Blue horrors also have same problem.

**Comment by ilaunchbury** [comment]
Child detachment?
