### ISSUE TITLE
Space Marines: Only first camo cloak costs points

### ISSUE THREAD

**Issue by robinmtb** [BSData/wh40k#1431]
**File/Catalogue:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.04.92

**Platform:** Windows/

**Dropbox:** No

**Description:** Adding the first camo cloak on a scout unit cost 3 pts, but adding any more doesn't cost anything. It should be 3 pts per cloak.

**Comment by alphalas** [comment]
Is this in a child detachment?

**Comment by robinmtb** [comment]
Not 100% sure what a child detachment is. But yes, I have an Admech battalion first and then I have added more to that post. My forces look like this:
Admech Battalion detachment
   - Astra militarium detach
   - Adeptus Ministorum detach
   - Space Marines detach

So I only have 1 detachment, which is a battalion detachment.

**Comment by alphalas** [comment]
Yeah it's a known battlescribe bug with points - if you use a child detachment (secondary faction inside another) sometimes nested points don't initially increment.

**Comment by alphalas** [comment]
If you save, close, and then reload the roster the point should increment correctly

**Comment by robinmtb** [comment]
Ah ok, sorry then. I didn't Know that! Thanks!

**Comment by alphalas** [comment]
It's alright - like I said, it's a Battlescribe bug - so not much we can do to help other then direct you around it. Cheers!
