### ISSUE TITLE
Grey Knights too many Heavy support

### ISSUE THREAD

**Issue by Celibarin** [BSData/wh40k#1433]
**File/Catalogue:** Imperium - Grey Knights.cat

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Unable to take 3 Heavy support Dreadknights and a Grandmaster Dreadknight. States "Too many selections from Heavy Support"

**Comment by tekton** [comment]
What detachment are you trying to do that in? Patrol, Vanguard, and Outrider only allow 3.

Spearhead allows 3-6, and that seems to work ok. Brigade 3-5 and seems ok.

**Comment by Celibarin** [comment]
I was on a battalion detachment. They allow 3 yes, but that would be considered 3 Heavy Support, the 3 Dreadknights, and 1 HQ, being the Grand Master in Dreadknight armor.On Sep 10, 2017 18:07, tekton <notifications@github.com> wrote:What detachment are you trying to do that in? Patrol, Vanguard, and Outrider only allow 3.
Spearhead allows 3-6, and that seems to work ok. Brigade 3-5 and seems ok.

**Comment by Celibarin** [comment]
Yeah, I just went through them all and it seems like it only is affecting the Battalion Detachment.On Sep 10, 2017 18:07, tekton <notifications@github.com> wrote:What detachment are you trying to do that in? Patrol, Vanguard, and Outrider only allow 3.
Spearhead allows 3-6, and that seems to work ok. Brigade 3-5 and seems ok.

**Comment by ilaunchbury** [comment]
@tekton, the problem here is that the Grandmaster Dreadknight still has the "Heavy Support" category in the data file, as well as HQ. It needs removing.

**Comment by tekton** [comment]
@ilaunchbury that's one of the issues, you are correct :) i was still testing it across other devices

**Comment by tekton** [comment]
Just to finish this one, there's a *different* issue if you have an old GST file (which one of my test devices did have) that causes a very similar issue- yay coincidence!
