### ISSUE TITLE
Eldar Shining Spears incorrect points

### ISSUE THREAD

**Issue by hatchetboy** [BSData/wh40k#1437]
**File/Catalogue:** 
Aeldari - Craftworld

**BattleScribe version:** 2.01.05

**Platform:** iOS/

**Dropbox:** Yes

**Description:** 

Eldar Shining spears - if you start with 3 in the unit, it correctly prices them at 129.  If you add or remove from the unit, it seems to delta the points by 24 points, which is the base cost without equipment.  It should move it by 24+10+9 for the change in equipment.

**Comment by hatchetboy** [comment]
Bit of further research - Windriders do the same thing.  This may be a widespread bug.

**Comment by hatchetboy** [comment]
Doesn't occur on desktop version - think it's an iOS bug.

**Comment by GenWilhelm** [comment]
Is this in a nested detachment?

**Comment by hatchetboy** [comment]
Yes

**Comment by alphalas** [comment]
it's a known BS bug. Close and reload roster to fix.
