### ISSUE TITLE
Imperium - Astra Militarum: Hellhound and Quad Launcher issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1440]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.04

**Platform:** Mac

**Dropbox:** No

**Description:** Imperial ~ Astra Militarum Missing the following: 
HellHound is missing Stats for all tank variants; Hellhound, Bane Wolf, Devil Dog
Heavy Quad Launcher / Thudd Gun is missing Stats for the weapon, only the crew is listed
thx!

**Comment by ilaunchbury** [comment]
The Hellhound variants all have the identical stats, except for their weapons, so there's not really any need to duplicate them?

The Heavy Quad Launcher does need its stats though.

**Comment by Rhombus1** [comment]
I agree on the Hellhounds, can't take pintle mounts.
Also, the Artemia pattern Hellhound points cost is off. The Artemia Pattern Inferno Cannon it comes with should be 0 extra points instead of the 20 it's listed at per Imperial Armor AM Index. Base tank should be 108 pts not 128.
