### ISSUE TITLE
Imperium - Grey Knights - Chaplain missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1448]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Chaplain is not an option for HQ in battlescribe for Grey Knights although it is found in the new Grey Knights codex.

**Comment by ilaunchbury** [comment]
Please make sure you have the latest version of the files (v9). The Chaplain is there (under Grey Knight Chaplain).
