### ISSUE TITLE
Death Guard Codex Update

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#1456]
Work is being done in https://github.com/BSData/wh40k/tree/DG-Codex-update.

- Add new units
  - [x] Mortarion
  - [x] Deathshroud Terminators
  - [x] Nurglings
  - [x] Plague Drones
  - [x] Plaguebearers
  - [x] Blightlord Terminators
  - [x] Plagueburst Crawler
  - [x] Myphitic Blight-hauler
  - [x] Tallyman
  - [x] Plague Surgeon
  - [x] Biologus Putrifier
  - [x] Foul Blightspawn
  - [x] Beasts of Nurgle
- Review existing units for rules and points
  - [x] Typhus
  - [x] Lord of Contagion
  - [x] Malignant Plaguecaster
  - [x] Noxious Blightbringer
  - [x] Daemon Prince
  - [x] Chaos Lord
  - [x] Chaos Lord in Terminator Armour
  - [x] Chaos Lord on Palanquin
  - [x] Sorceror
  - [x] Sorceror in Terminator Armour
  - [x] Sorceror on Palanquin
  - [x] Plague Marines - updated based on CSM
  - [x] Poxwalkers
  - [x] Cultists
  - [x] Possessed
  - [x] Helbrute
  - [x] Foetid Bloatdrone
  - [x] Rhino
  - [x] Spawn
  - [x] Defiler
  - [x] Predator
  - [x] Land Raider
- Update Contagion Discipline
  - [x] Blades of Putrefaction
  - [x] Putrescent Vitality
  - [x] Curse of the Leper
- Add Relics of Decay
  - [x] Pandemic Staff
  - [x] Suppurating Plate
  - [x] Dolorous Knell
  - [x] Plaguebringer
  - [x] Fugaris' Helm
  - [x] The Plague Skull of Glothila
- Other stuff
  - [x] Update Dark Hereticus discipline

**Comment by radionausea** [comment]
If it helps any, Blood of Kittens has a a compilation of the leaks, including the third psychic power, relics, warlord traits etc
http://bloodofkittens.com/blog/2017/09/08/death-guard-8th-edition-codex-leak-compilation/

**Comment by ilaunchbury** [comment]
@radionausea, thanks, I'll take what I can from there.

**Comment by GenWilhelm** [comment]
Points costs from the Dakka news/rumour thread: https://imgur.com/a/dA3e7

And the contents page, for a list of all units: http://image.bolterandchainsword.com/uploads/gallery/album_7255/med_gallery_59703_7255_972522.png

**Comment by mrsneezy** [comment]
all  details are easily gotten online now is there anything I can do to help

**Comment by ilaunchbury** [comment]
Everything but Relics are done. See the assumed amendments in #2.

**Comment by ilaunchbury** [comment]
All updates done.
