### ISSUE TITLE
Imperium - Dark Angels - Hellblasters power

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1457]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi
Hellblaster unit cost listed as 12, index lists them as 8. Have checked errata at GW

**Comment by Thairne** [comment]
Nope, Hellblasters are 12 in index.

![grafik](https://user-images.githubusercontent.com/8590840/30416992-7cc84808-992e-11e7-9393-341d1bc5efba.png)
