### ISSUE TITLE
Warhammer 40,000 8th Edition: "Too many Heavy Support" when creating a battalion

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1458]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** In the Battalion Detachment Portion it always says invalid whenever I pick a Heavy Support Choice it always say I have too many selections even if I just picked one

**Comment by Thairne** [comment]
What army are you using?
