### ISSUE TITLE
Warhammer 40,000 8th Edition: No stat lines in output on Android

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1459]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** When viewing my lists, no stat lines are showing up.  Please help!  I support your app financially, so please help.  never had an issue until now.  -Daemons, Renegade knight, and CSM's all showing no character or weapon stat lines.  what is going on?

**Comment by Thairne** [comment]
We dont get a cent from that financial support. We do all this as volunteers.

Are you running on low memory mode?
