### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Combat Engineer weapon validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1464]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Death Korps Combat Engineer Squad - Watch Master cannot remove stock Krieg combat shotgun, resulting in a "1 too many selections from Engineer Watch Master Ranged Weapons (maximum 1)" error

**Comment by OxideUK** [comment]
To clarify, this happens when you try and select an alternative ranged weapon.
