### ISSUE TITLE
Emperor's Champion cost incorrect.  Should be 75, is 108

### ISSUE THREAD

**Issue by DrewEdgar** [BSData/wh40k#1492]
**File/Catalogue:** 
Space Marines

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux
All

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
Emperor's Champion listed in the Codex is only 75 points including all wargear.  App has him at 108

**Comment by acebaur** [comment]
Not sure what version you are using because the most recent (v33) has him at 75. Can you post a screenshot?

**Comment by DrewEdgar** [comment]
Ah apologies.  Battlescribe was insistent that I had the most up to date version, but it was definitely not v33. (was stuck on v25!!)  Re-pulled the index file and that fixed it.
