### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Several issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1503]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** Yes

**Description:** According to my downloaded copy of Imperial Armor Index Forces of the Astra Militarum The DKK is only able to use the Hydra Battery, which is an Artillery piece and only worth 90 points and 4 power.
Also, the Heavy Quad Launcher "Thudd Gun" weapon profile is not appearing when you try to view it.
Finally for the Death Rider Squadron Commander, the weapon profile for his mount does not appear, the Savage claws.

**Comment by ilaunchbury** [comment]
- [x] Please also download the FAQ for that Index. DKK got a whole load of extra units added in that update.
- [x] Quad launcher issue is already fixed in #1440, which hasn't been released yet.
- [ ] The mount weapon does need to be added for this unit.
