### ISSUE TITLE
Imperium - Grey Knights: Librarian shouldn't be forced to take a Storm Bolter

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1507]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Not really a bug, but Librarian has the option to take a stormshield, I think this is incorrect.

**Comment by ilaunchbury** [comment]
Also, he shouldn't have a storm bolter by default, it's an option for him.

**Comment by tekton** [comment]
The index still allows it, so the shield is legit. I'll add the None option for the ranged weapon though.
