### ISSUE TITLE
Imperium - Dark Angels: Assault squad issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1508]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Unable to give Assault Squad Sergeant an Eviscerator. When attempting to add, it says max allowed 0

**Comment by ilaunchbury** [comment]
In addition, the PL and point cost for Jump Packs isn't scaling with the unit. It should be 3 pts per model, and 2PL for 5+ models. It's currently fixed at 1PL and 19 points.

You may want to consider copying the entry from the SM cat.

**Comment by Thairne** [comment]
Thanks, I can fix my own stuff rather well 📦 
Most of the time.

**Comment by Thairne** [comment]
Forgot the #close
