### ISSUE TITLE
Missing units in FW Heretic Astartes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1532]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Chaos FW Heretic Astartes file is missing the LoW tanks as well as a few heavy support options

**Comment by ilaunchbury** [comment]
Please can you provide some clarification as to which units you think are missing? LoW require a Super Heavy detachment. I can see all 9 LoW units when I add a Super Heavy detachment.
