### ISSUE TITLE
Appspot - Wh40k Datafiles missing

### ISSUE THREAD

**Issue by Tordokdur** [BSData/wh40k#1539]
**File/Catalogue:** 
warhammer40k
**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Warhammer40k 8th datafiles not available on http://battlescribedata.appspot.com/#/repos
I tried to update my files but there are no longer wh40k repos. What happend?

**Comment by ilaunchbury** [comment]
They sometimes do disappear for a while. It's not our site, we're just the volunteers who update the files, so we don't have control over it.

They'll come back at some point.
