### ISSUE TITLE
Imperium - Space Marines: Lieutenant's additional pistols conflict with bolt pistol

### ISSUE THREAD

**Issue by GMTemplar** [BSData/wh40k#1540]
**File/Catalogue:** Space Marines v33

**BattleScribe version:** v2.01.04.92

**Platform:** Windows

**Dropbox:** Yes

**Description:** Choosing plasma pistol, grav pistol, or additional bolt pistol for a Lieutenant conflicts with the existing bolt pistol. Additional pistols should only conflict with the master-crafted boltgun, not with the bolt pistol.

**Comment by ilaunchbury** [comment]
I don't see an issue here? Adding an additional pistol in place of the boltgun does not give an error in v33.

![image](https://user-images.githubusercontent.com/29306451/30909926-bca46db6-a37a-11e7-957a-ee52c5bf280c.png)

**Comment by GMTemplar** [comment]
It seems to be way more complicated issue than I thought. It has something to do with picking two lieutenants as a single choice. Try the following combo 1st Lt Storm bolter + chainsword, 2nd Lt Plasma pistol + chainsword. The second lieutenant will produce a conflict.

**Comment by ilaunchbury** [comment]
@flakpanda , this is an issue with the scope of the validation constraint on the Pistols group. It's checking at the unit level instead of the model level.
