### ISSUE TITLE
Imperium - Adeptus Mechanicus: PL cost issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1543]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Still is issue in v13
Incorrect power levels:
Skitarii Vanguard and Rangers - should be 7 PL per 10 models (currently 8 PL)
Sicarian Ruststalkers - should be 6 PL (currently 5 PL)
Onager Dunecrawler - should be 7 PL (currently 6 PL)

**Comment by Thairne** [comment]
I could've sword I fixed those days ago.... harumpf.
