### ISSUE TITLE
Imperium - Adeptus Mechanicus: Enginseer missing Graia relic option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1544]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** When choosing Forgeworld Graia there is no option for the Enginseer to take the Graia Relic (works on the Tech Priest though)

**Comment by ilaunchbury** [comment]
The Cerebral Techno-mitre is only available for Toehpriest Dominus, not for Enginseers, as per the Codex.
