### ISSUE TITLE
Imperium - AdMech - Power Level on several units changed with codex release, needs to be adjusted

### ISSUE THREAD

**Issue by AdeptusIneptus** [BSData/wh40k#1549]
**File/Catalogue:** Imperium - Adeptus Mechanicus.cat

**BattleScribe version:** 2.01.04

**Platform:** iOS

**Dropbox:** No

**Description:** 
Skitarii Vanguard - PL for base unit (5-man) remains the same (4), but PL for larger units (6-10 man) is now 7 instead of 8.
Skitarii Rangers - PL for base unit (5-man) remains the same (4), but PL for larger units (6-10 man) is now 7 instead of 8.
Sicarian Ruststalkers - PL for base unit (5-man) is now 6 instead of 5.  PL for unit of 6-10 is now 12 instead of 10.  Additionally, Power Level in BattleScribe is currently incrementing when unit size reaches 10, rather than when it exceeds 5.
Onager Dunecrawlers - PL per model is now 7 instead of 6.

**Comment by GenWilhelm** [comment]
Think looks very similar to #1543.

@Thairne, how much of this was fixed in yesterday's update?

**Comment by Thairne** [comment]
Everything except the Ruststalker unit count thingy.
