### ISSUE TITLE
Imperium - Space Marines: Company Veteran boltgun is collective

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1550]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marines - Company Veterans - Wargear error
Only able to choose a combi-weapon for a single Space Marine Veteran.
Per the codex:
"*Any Space Marine Veteran may replace their bolt pistol with a storm shield or an item from the Melee Weapons or Pistols list."
"*Any Space Marine Veteran may replace their chainsword with a storm shield, a boltgun, or an item from the Melee Weapons, Pistols, Combi-Weapons or Special Weapons list"

**Comment by ilaunchbury** [comment]
Not sure what the problem is exactly?  The weapon options on the Veterans match the Codex, and what you have quoted above. Perhaps try making sure you have the latest release, 1.0.71.

**Comment by ilaunchbury** [comment]
Found the problem! If you give one Veteran a boltgun, they all get given boltguns, which then breaks the validation. Combi weapons themselves work fine.
