### ISSUE TITLE
Orks: Gargantuan Squiggoth should have 2x twin big shootas by default.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1556]
**File:** Orks.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** Yes

**Description:** Points errors:
Gargantuan squiggoth should come base with two twin shootas at 14 points each. Currently has only options to add big shootas

Thanks for all you do maintaining this!

**Comment by ilaunchbury** [comment]
Zhardsnark issue has already been reported in #1447 so removed from ticket.
