### ISSUE TITLE
T'au Empire: XV81 weapon choice issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1559]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Hq choice Commander in xv81 crisis suit doesn't allow for replacement of smart missile system for 20pts along with the burst cannon for 2 replacements from weapons and support systems, so it registers as always equiped. The smart missile system needs to be changed to be able to unequip it and deduct the points

**Comment by amis92** [comment]
Index states (IA Index: Xenos p.42 @epub):

> * The XV81 Commander may replace their burst cannon with a single item from the *Ranged Weapons* and/or *Support Systems* list - see *Warhammer 40,000 - Index: Xenos 2*.
> * This model may take an additional item from the *Ranged Weapons* and/or *Support Systems* list - see *Warhammer 40,000 - Index: Xenos 2*.

FAQ has no errata pertaining this part. The text above doesn't allow removing SMS from equipment of this model. Essentially, XV81 is equipped with SMS and 1 or 2 items from Weapons or Support System lists (by default Burst Cannon).
