### ISSUE TITLE
Index files and codex available? 

### ISSUE THREAD

**Issue by Mikey-Consto** [BSData/wh40k#1560]
**File/Catalogue:**  All

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux All

**Dropbox:** Yes/No N/A

**Description:** Hi folks, please delete if not appropriate. Will indexes be available as we as codexes (ie if I only intend to use indexes post a codex release?)

Thanks in advance, 

Mike

**Comment by ilaunchbury** [comment]
No. Once a Codex is released, we will update the data files to use the latest details. Any Index-only units or options will continue to be supported, as per guidance from GW.

Please see #1414 for further details.
