### ISSUE TITLE
Imperium - Space Wolves: Improve Wolf Guard weapon selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1562]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** All of the wolf guard units' weapon selection is unnecessarily complex, with several repeating options. Is it possible to just have two radio lists, one defaulting to chainsword, one defaulting to bolt pistol. Both lists could include all of the weapon options (melee and ranged), including storm shield where appropriate.

**Comment by CrusherJoe** [comment]
Yes, you're right.
