### ISSUE TITLE
T'au Empire - Shas'o R'alai points cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1563]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Shas'o R'alai should cost 163 instead of 155. Shas'o (130) + two black markerlight drones (11+3 each) + Drone Controller (5) = 163.

**Comment by ilaunchbury** [comment]
Blacklight Marker Drones were reduced in cost to 7 points per model in the FAQ for the FW Index Xenos

https://www.forgeworld.co.uk/resources/PDF/Downloads/40K_8th_ed_Update_Imperial_Armour_Index_Xenos_ver_1.0.pdf
