### ISSUE TITLE
 Imperium - Grey Knights: Icarus Stormcannon cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1564]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 1.00.72

**Platform:** Android

**Dropbox:** No

**Description:** icarus stormcannon cost 22 not 17 points for this weapon.

**Comment by tekton** [comment]
I copied the points from the Index just to prep for the release, swore I looked at that before it went out, doh. Thanks for the heads up!
