### ISSUE TITLE
T'au Empire: Incorrect details in Homing Beacon ability for XV25

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1569]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** The Description of the Homing Beacon entry for the XV-25 Steath Battlesuit states that the beacon may be deployed within two (2) inches of the unit.  Index Xenos 2 states the beacon must be deployed within one (1) inch of the unit.

**Comment by ilaunchbury** [comment]
Already reported in #1568, closing this ticket.
