### ISSUE TITLE
T'au Empire - Strike Team - Weapon Profiles Missing From HTML Document

### ISSUE THREAD

**Issue by madlou** [BSData/wh40k#1570]
**File/Catalogue:** T'au Empire.cat

**BattleScribe version:** 2.01.05

**Platform:** iOS

**Dropbox:** No

**Description:** When exporting my army to a HTML Document, all units have weapon profiles, except "Strike Teams".

**Comment by ilaunchbury** [comment]
Check you are exporting the full output. There appears to be a bug in Battlescribe where weapon profiles which have no point cost are not shown unless you use the full output option.

You'll also need to report that bug to the application developers; this is for problems with the datafiles.
