### ISSUE TITLE
Aeldari: Missing aeldari missile launchers for dark reapers 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#1571]
Cannot select Aeldari missiles for dark reapers 

![3d95d794-088d-44e6-b815-f0a5c2b8df45](https://user-images.githubusercontent.com/16340056/31192470-4f8dea0a-a90f-11e7-891b-fab583d028f4.png)
![482cea0c-ac90-4674-8b4e-143430f3e57c](https://user-images.githubusercontent.com/16340056/31192471-4fa41b7c-a90f-11e7-9207-1099183d1c72.png)

**Comment by ilaunchbury** [comment]
Standard Reapers cannot take a missile launcher, only the Exarch can. Once you select the Exarch, you can then equip that model with an alternative weapon.
