### ISSUE TITLE
FW Adeptus Astartes - Relic Contemptor Dreadnought

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k#1575]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:**/No

**Description:** Relic Contemptor Dreadnought is missing the option to take a Cyclone Missile Launcher.  These rules were missing int he original Index, but were added in the FAQ.  https://whc-cdn.games-workshop.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Adeptus_Astartes_ver_1.2.pdf

**Comment by Crowbar90** [comment]
I'll fix it as soon as possible!

Il gio 5 ott 2017, 17:31 Iain Launchbury <notifications@github.com> ha
scritto:
