### ISSUE TITLE
Necrons: Warriors missing Reanimation Protocols

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1580]
**File:** Necrons.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Necron warriors do not have the "Reanimation Protocols" attached to them when viewing a roster. Other units do. They should have the "Reanimation Protocols" attached.

**Comment by ilaunchbury** [comment]
This is a bug in Battlescribe. If you do not select Full output, the rules for units which have 0 cost weapons will be hidden. Change your output settings to Full and Reanimation Protocols will be shown.
