### ISSUE TITLE
Imperium - Adeptus Mechanicus - Forcing Forge World selection when not appropriate

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1581]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi so it keeps asking you to choose a forge world for each detachment when you have other imperium units within the detachment. 

The forge world should only have to be chosen if it is only admech in the detachment. 

Thanks for your help

**Comment by Thairne** [comment]
I don't think we can do that due to technical limitations. 
Even if - you loose the dogma, yet you still need something to relate your keywords to. You still get access to relics which are determined by forge world, as is your warlord trait.
