### ISSUE TITLE
Imperium - Space Wolves - Primaris Librarians should use faction discipline

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1586]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Space Wolves Primaris Librarian should get it's abilities from The Tempestus Discipline as per GWs errata for Primaris.

**Comment by GenWilhelm** [comment]
Edited to remove personal information.
