### ISSUE TITLE
Imperium - Space Marines - Primaris Aggressors cost wrong

### ISSUE THREAD

**Issue by dstretch** [BSData/wh40k#1588]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes

**Description:**

Primaris Aggressors are priced at 60pts each including Assault Bolters, but Codex changed them to 45 each including Bolters.

**Comment by flakpanda** [comment]
I am not sure how you came up with 45 points per model. Agggressors are listed at 25 points, boltstorm gauntlets are listed at 14, and fragstorm launchers are 4 listed at 4 points. Thats 43 points per model. Base cost for a squad of 3 would be 129 points. Also it sounds like you have old data at the 60 points per  model price. Please make sure to update to the latest data.

![image](https://user-images.githubusercontent.com/19719565/32070366-b4e0f93a-ba51-11e7-8647-9108fb4e70fb.png)

**Comment by dstretch** [comment]
Ugh, sorry, I didn't mean Aggressors, I meant Inceptors!  They're in the codex at 30 points per model and their Assault Bolters are 15pts making 45 points each.  I'm using the latest data file and they're showing as 60 points each there.

**Comment by flakpanda** [comment]
You are correct about the cost of the model and weapon. However, they carry 2 weapons each. So 30+15+15=60.

**Comment by dstretch** [comment]
You're absolutely right, thanks.  Definitely not worth the points!  Please close :)
