### ISSUE TITLE
Codex: Astra Militarum

### ISSUE THREAD

**Issue by CrusherJoe** [BSData/wh40k#1589]
Make all additions and changes for Codex: Astra Militarum.

---

- [x] New Units
	- [x] Ministorum Priest
	- [x] Crusaders
	- [x] Tech-priest Enginseer
	- [x] Servitors
	- [x] Ogryn Bodyguard
- [x] Existing Units
	- [x] Tank Commander should be 12 PL.
	- [x] Knight Commander Pask should be 13 PL.
	- [x] Colonel Straken should be 4 PL.
	- [x] Tempestor Prime should be 3 PL.
	- [x] Infantry Squad weapons team should be 4pts.
	- [x] Command Squad should be 2 PL.
	- [x] Command Squad weapons team should be 6pts.
	- [x] Special Weapons Squad should be 2 PL.
	- [x] Veterans should be 5 PL.
	- [x] Veteran weapons team should be 6pts.
	- [x] Ogryns should be 5 PL.
	- [x] Hellhounds should be 6 PL each.
	- [x] Hellhounds should have access to vehicle equipment.
	- [x] Scout Sentinels should be 3 PL each.
	- [x] Basilisks should be 1 extra PL.
	- [x] Wyverns should be 6 PL each.
	- [x] Hydras should be 1 extra PL.
	- [x] Manticore should be 8 PL.
	- [x] Leman Russ should be 10 PL each.
	- [x] Chimera should be 6 PL.
	- [x] Valkyries should be 8 PL each, and 1 less in a unit of 3.
	- [x] Update "Steel Behemoth" ability.
	- [x] Baneblade should be 28 PL.
	- [x] Banesword should be 26 PL.
	- [x] Doomhammer should be 27 PL.
	- [x] Hellhammer should be 30 PL.
	- [x] Shadowsword should be 26 PL.
	- [x] Stormlord should be 26 PL.
	- [x] Stormsword should be 26 PL.
	- [x] Tank Commanders, Knight Commander Pask, and Colonel Straken should each allow an additional Command Squad.
	- [x] Update "Avalanche of Muscle" rule
	- [x] Baneblade Cannon should be Heavy 3D6.
	- [x] (Hellhounds, Bane Wolf) Chem Cannon has html tag in abilities.
	- [x] (Leman Russ) Executioner Plasma Cannon has new supercharge ability.
	- [x] Hellhammer Cannon should be Heavy 3D6.
	- [x] (Doomhammer) Magma Cannon should be Heavy 2D6.
	- [x] (Hellhounds, Devil Dog) Melta Cannon should be Assault D3.
	- [x] (Valkyries) Multiple Rocket Pods should be Assault D6.
	- [x] (Banesword) Quake Cannon should be Heavy 2D6.
	- [x] Stormsword Siege Cannon should be Heavy 2D6.
	- [x] (Banehammer) Tremor Cannon should be Heavy 3D6.
	- [x] (Shadowshord) Volcano Cannon should be Heavy 3D3.
- [ ] Misc
	- [x] Add a regiment selector.
	- [x] Add relics to all non-named characters.
	- [x] Standardise Vehicle Equipment List.
	- [x] Add regiment specific orders.

**Comment by GenWilhelm** [comment]
I've compiled a list of changes from the codex that haven't been covered yet.

**Comment by CrusherJoe** [comment]
Okay that's everything under "New Units" and "Existing Units". @alphalas you're up. 👍

**Comment by wdrake3** [comment]
Valkyrie base points should be reduced to 110pts

**Comment by CrusherJoe** [comment]
@wdrake3 You are correct. The actual data file for Codex: AM hasn't been released yet -- it's still a work in progress.

**Comment by wdrake3** [comment]
@CrusherJoe Thank you for everything you do. I just noticed it wasn't on the checklist.

**Comment by GenWilhelm** [comment]
Ah, that one's on me. Joe had already started on the changes before I had a chance to compile a checklist, so pretty much all points changes aren't on the list.

**Comment by wdrake3** [comment]
Y'all are awesome

**Comment by Stus67** [comment]
Any eta on this?

**Comment by alphalas** [comment]
Patience

**Comment by Shadesfox** [comment]
Another commonly overlooked nugget, the Valkyrie multiple rocket pod pod is Assault d6 now rather than Heavy d6

**Comment by monsieurgustav** [comment]
I wonder about "Infantry Squad weapons team should be 4pts."
One can also read they should be 8pts, as they are formed of 2 guardsmen (4 each) + "there is no additional points cost" as said under the asterisk.

**Comment by alphalas** [comment]
That points cost is for the HTW in the Heavy Weapon Squad, not in the infantry squad.

**Comment by monsieurgustav** [comment]
Maybe I was not clear: today on BattleScribe, an Infantry Squad with a HWT costs 36pts (excluding weapons). I think it should be 40pts because you take 1 sarge and 9 guardsmen (40pts), *then* you combine two of them to form a HWT (with no additional cost).
To solve that, the HWT should be 8pts IMHO.

**Comment by alphalas** [comment]
It should be - I didn’t notice that it’s actually not. Will fix

**Comment by Shadesfox** [comment]
Some more bugs, scions are +2 PL for an extra 5, currently listed as +3 so a full squad is listed at 6 PL instead of 5.
The Company Commander is listed at 3 PL, it should be 2.
