### ISSUE TITLE
Imperium - Astra Militarum - Flyers damage tables and inconsistencies

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#1599]
**File/Catalogue:** Imperium - Astra Militarum v47 & v58

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
- Valkyries are missing damage table.
- Vultures are missing damage table.
- Vendettas are missing damage table.
- Vendettas are missing transport profile.
- Valkyries use rules for some abilities, where the other two use profiles. This should be more consistent.

**Comment by CrusherJoe** [comment]
Added shared damage table to all gunships. Cleaned up all rules (by making most of them shared rules and attaching). Added transport ability to Vendetta. All rules are now consistent across all gunships.
