### ISSUE TITLE
Chaos - Death Guard: No option for Jump Pack on Sorcerer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1600]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** No option to add a Sorcerer with Jump Pack in Death Guard list or to set Death Guard legion on CSM Sorcerer with Jump Pack.  Should be available with Dark Hereticus discipline (ie, for Warptime) as it would use the Index data sheet just like the Sorcerer on Palanquin of Nurgle.

**Comment by ilaunchbury** [comment]
This will be fixed in the next release. I've also added the Jump Pack Lord back in.
