### ISSUE TITLE
Necrons: Command Barge missing keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1604]
**File:** Necrons.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Catacomb Command Barge is missing the "Character" keyword. This keyword was added in the Xenos 1 1.0 Errata.

**Comment by ilaunchbury** [comment]
Duplicate of #1576 which has been fixed and will be in the next release.
