### ISSUE TITLE
Imperium: Astra Militarum: Various issues with unreleased Codex version (v58)

### ISSUE THREAD

**Issue by Eerieuk** [BSData/wh40k#1605]
**File/Catalogue:Astra Militarium V58 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Errors

Ogryn Bodygaurd :- 
* Bullgryn Plate current listed as no cost should be 5pts
* Ripper gun can be replaced by a Bullgryn maul or grenadier Gauntlet. But when choosing one of them getting an error that bodyguard must have 1 more selections of Ripper Gun (minimum 1 each)

Plasma cost variance - Plasma Gun cost different depending on ballistic skill
eg. BS4+ costs 7pts, BS3+ costs 13pts
BS4+ Infantry special weapons, guardsmen plus plasma gun = 13pts
BS3+ Veteran or command squad veteran plus plasma gun = 19pts
BS3+ Militarium Tempestus Scion plus plasma gun = 22pts

Option for Ministorum priest to take a plasma gun(BS4+ plasma), they cant take plasma gun in codex but the index still allows for a plasma gun to be taken and GW have stated u can still use options from the index.) 

Armoured Sentinel. They are now Toughness 6

Hot-Shot Volley Gun is now 6 pts

**Comment by Eerieuk** [comment]
Made a Few Additions to main post

**Comment by alphalas** [comment]
Won’t be implementing that ministorum priest thing that you pointed out – the ministorum priest with the plasma gun option is specifically the adeptus ministorum priest, which is only available in AM through souping.

**Comment by Eerieuk** [comment]
no problem:)

**Comment by CrusherJoe** [comment]
Fixed in my commit.
