### ISSUE TITLE
Query: Astra Militarium Codex. Heirlooms.

### ISSUE THREAD

**Issue by Eerieuk** [BSData/wh40k#1615]
**File/Catalogue: Astra Militarium v67

**BattleScribe version:** 2.01.

**Platform:** Windows
**Dropbox:** No

**Description:** Query on relics.

If your army is led by and astra militarium warlord you may give an heirloom of Conquest to an astra militarium character. Only excemption is named characters.

Ogryn bodyGuard is an astra militarium infantry character.   Miltarium Auxilia can be included in a detachment they just cant benefit from Regimental Doctrines. But are able to take Heirlooms if they meet the requirement of that Heirloom.

So The Query is

**The Deathmask of Ollanius** -  Requirements - Infantry Model Only.
Ogryn bodyguard is Astra militarium, A Character and Infantry Model. So he Should be able to Take this relic

It would be the only relic available to the bodyguard unit as it doesnt meet the requirement for the others heirlooms.

**Comment by GenWilhelm** [comment]
They should also have access to **The Dagger of Tu'sakh**.
