### ISSUE TITLE
Why no keywords in the profiles ?

### ISSUE THREAD

**Issue by Nokhal** [BSData/wh40k#1623]
A huge part of the rules are now centered on keywords, and it's not shown which units have it or not. 

Was it a deliberate choice, and if so what is the logic behind it ?     
   
As it stand now, having to consult the rule-book every time to check if a one model unit is a character or not, or if it can embark on this transport or not is kinda annoying.

**Comment by alphalas** [comment]
It’s an app feature that is supposed to be added with the next update – the keywords are there, the app just doesn’t currently show them unless we specifically add them in again
