### ISSUE TITLE
Imperium: Astra Militarum - Astra Militatrum Melee Weapons Options Incorrect

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#1625]
**File/Catalogue:** 

Codex: Astra Militarum (IG - Astra Militarum v 69)

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** Astra Militarum Melee options now ONLY include Power Sword and Power First, but Battle Scribe still allows Power Maul, Power Axe, etc. to be selected.

**Comment by alphalas** [comment]
We are still supporting Index options; GW has said they're not invalidated.
