### ISSUE TITLE
Chaos - Thousand Sons v19

### ISSUE THREAD

**Issue by proposer** [BSData/wh40k#1627]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by proposer** [comment]
Has not been updated based on chaos codex (example: heldrake showing base pts cost of 188pts [compared to new 180], baleflamer still 60pts [compared to new 30])

**Comment by GenWilhelm** [comment]
According to GW, Thousand Sons still use the index for everything.

See #1414 for a full explanation.
