### ISSUE TITLE
Astra Militarum Infantry Squad - Heavy Weapons Team

### ISSUE THREAD

**Issue by Marwynn** [BSData/wh40k#1628]
**File/Catalogue:** 1.0.74 - Astra Militarum v69

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** Heavy Weapons Team should cost 8 points instead of 4. p93 of new Codex says "Two other Guardsmen may form a Heavy weapons Team."

**Comment by GenWilhelm** [comment]
This change has already been made, and will be out with the next release.
