### ISSUE TITLE
 Imperium - Astra Militarum: Typo in Nightshroud power

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1630]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.04

**Platform:** Mac

**Dropbox:** No

**Description:** Nightshroud psychic power description typo - "penality" instead of penalty.

**Comment by CrusherJoe** [comment]
That's not a typo, that's an alternate spelling LOL.

Seriously, though. Fixed. Will be in next release of the file.
