### ISSUE TITLE
FW: Imperium, Death Korps of Krieg - Master of Ordinance Points error

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#1633]
**File/Catalogue:** FW: IG Death Korps of Krieg

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** Death Korps Master of Ordinance uses data from Imperial Guard Codex; cost should be reduced from 38 points to 30 points.

**Comment by CrusherJoe** [comment]
Unfortunately, _Imperial Armour: Forces of the Astra Militarum_, on page 55, specifies Master of Ordnance references _Warhammer 40,000 -- Index: Imperium 2_ not _Codex: Astra Militarum_. 

The latest FAQ released by FW [https://whc-cdn.games-workshop.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf](url) does nothing to change that.

Until a new FW FAQ updates that, DKOK are stuck using Index 2 values and rules references.

**Comment by GenericCola** [comment]
I thought that unit changes, such as rules, points costs, etc. were automatically considered "replaced" in the Index by their newest iteration in whatever the current Codex is, while options for a unit like wargear which were available in the Index but may have been streamlined in the Codex were still allowed.

By the logic here, are you saying that Krieg Basilisks are still AP -2 with their Earthshakers, Krieg Leman Russ tanks use the now outdated Grinding Advance and Plasma Vent rules, and do not have the options of Track Guards, Dozer Blades, etc. added in the Imperial Guard codex?

This is incredibly counter-intuitive to me.

**Comment by alphalas** [comment]
Yes on all counts - Because it specifically references index pages. If FW release is an FAQ that updates the references, we will totally implement new changes.
