### ISSUE TITLE
Astra Militarum Heavy Weapons Team in infantry squads should be 8 points

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k#1635]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS

**Dropbox:** No

**Description:** Heavy weapons team currently are a base of 4 points.  However a heavy weapons team is 2 infantry models making it 8 points base.

**Comment by alphalas** [comment]
Already been fixed, will be released soon.
