### ISSUE TITLE
 Imperium - Astra Militarum - Issues roundup

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#1636]
**File/Catalogue:** Imperium - Astra Militarum v71

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** Yes

**Description:**
*[Github comment](https://github.com/BSData/wh40k/issues/1589#issuecomment-336285821) from @Shadesfox*
- Scions are +2 PL for an extra 5, currently listed as +3 so a full squad is listed at 6 PL instead of 5.
- The Company Commander is listed at 3 PL, it should be 2.

*Comment on [Facebook post](https://www.facebook.com/BattleScribeData/posts/1691933967506899)*
- Melta cannon on a devil dog is showing as 35 points still, it’s only 20 now

**Comment by KartoffelGranate** [comment]
Veteran Heavy Weapons Teams should cost 12 points instead of 6.  They require 2 veterans to take.  Similarly, Heavy Weapons Teams in Infantry squads should be 8 points instead of 4.

**Comment by BigBangA1** [comment]
Astra Telepathica Staves are currently listed as free, but actually coat 6 points.

**Comment by Shadesfox** [comment]
A 👍 for the previous two comments. Also, how will the power weapon situation be handled? In the codex they are limited to power fists and power swords, with no mention of power mauls or power axes like in the index. Given the previous FAQs about index legal models being allowed in a codex army and the general ineffectiveness of AM melee with it's characters, I don't imagine that this will be a problem in practice. But I wanted to raise the issue anyways.

**Comment by GenWilhelm** [comment]
The Codex vs Index issue is simple.

If you have an older model that has wargear that is not available in the codex, you can still use the datasheet from the Index, but using the Codex points costs. Otherwise they behave exactly as though they were taken from the codex, ie. they get doctrines, relics, new warlord traits, etc.

In the case of AM officers, they can still take power axes, mauls, and shotguns as these options were present on the Index datasheet for the units.

**Comment by CrusherJoe** [comment]
Scions PL, fixed.
Company Commander PL, fixed.
Veteran HWT 12 points, fixed
Infantry HWT 8 points, verified
Astra telepathica staves 6 points, verified.

Please check version number of data file -- the current is v72 (what I just pushed up to github). It will be the only data file that contains all the fixes discussed here.
