### ISSUE TITLE
Chaos - Death Guard: Beasts missing Slime Trail

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1638]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Plague Drones mistakenly listed as 44 pts each, should be 34. Also Beasts of Nurgle do both have their Deadly Slime Trail listed when viewing the unit (both sources: Codex Death Guard)

**Comment by radionausea** [comment]
Plague drones are 34 points in v.19, I think you need to update your files

**Comment by ilaunchbury** [comment]
Plague Drone cost is correct in latest version. Added Deadly Slime Trail to Beasts.
