### ISSUE TITLE
This index.bsi is missing from appspot.com page

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k#1641]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Cant update or download the repo.  Seems to missing from the page.

https://battlescribedata.appspot.com/repos/wh40k/index.bsi

**Comment by alphalas** [comment]
Yeah, it happens from time to time. Nothing we can do about it, it’ll come back eventually.
