### ISSUE TITLE
Imperium-Space Wolves Wolf Claws

### ISSUE THREAD

**Issue by xenoserum** [BSData/wh40k#1649]
**File/Catalogue:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.06

**Platform:** iOS

**Dropbox:** No

**Description:** Wolf Claws (pair) are down as 13 points in the codex but 14 on the file. it's showing it on the Thunderwolves

**Comment by GenWilhelm** [comment]
It was changed in the Index: Imperium 1 errata.

>Page 217 – Space Wolves Points Values, Melee Weapons
Change the points per weapon value of ‘Wolf claw
(single/pair)’ to read ‘10/14’

https://www.games-workshop.com/resources/PDF/Errata/Warhammer_40000/Index_Imperium1_ENG.pdf

**Comment by xenoserum** [comment]
Cheers... how the hell i missed that I have no idea get...
