### ISSUE TITLE
Chaos Fire Raptor Reaper Battery

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/wh40k#1650]
**File/Catalogue:** 
FW: Heretic Astartes
**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
The FW index for chaos says the reaper battery is “Heavy 4” in the appendix. But in the Chaos Fire Raptor profile it says its Reaper Battery is “Heavy 6”. I dont know wich is right. But considering that the Heavy Bolter option is “Heavy 12” there isnt much sense in taking the reaper autocannon option

Thanx, and sorry if I got something wrong.

**Comment by Tomakokamikaze** [comment]
The weapon is suposed to be Reaper Battery, but in battlescribe it is as Reaper Autocannon.
Maybe the loyal version has this error too.

**Comment by Drachnyen** [comment]
![7ef6c044-8d19-48df-9dd5-d16c7105578e](https://user-images.githubusercontent.com/16340056/31800817-871d6244-b511-11e7-9e22-04540bbfbc29.jpeg)
