### ISSUE TITLE
Chaos - FW Renegade and Heretics: Militia with Voxcaster incorrect points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1653]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** The point value for a renegade militia with vox caster should be 9 instead of 11 (4 base and 5 for the vox).

**Comment by FSchiltz** [comment]
The renegade militia with a chaos icon point cost looks off too, it's 16 but should be 14
