### ISSUE TITLE
AM Astropath Telepathic Stave Upgrade: Incorrect Point Cost

### ISSUE THREAD

**Issue by shadowofspaz** [BSData/wh40k#1660]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The Astropath for Codex: Astra Militarum has a Telepathic Stave upgrade. This data file has it at no cost. It is **6 Points** according to the codex and latest FAQ (which dropped today and made no adjustment).

**Comment by alphalas** [comment]
update data
