### ISSUE TITLE
Limit of detachements by points

### ISSUE THREAD

**Issue by wismeril** [BSData/wh40k#1661]
**File/Catalogue:** All

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:**
Rules book, page 214 
If you are using matched play for an organised event such as a tournament, we suggest using the table below as a helpful guideline. Of course, if you are organising such an event, you should feel free to modify these guidelines to better suit your event’s own needs, schedule, etc.

POINTS        LIMIT NUMBER OF DETACHMENTS 
Upto1,000     Up to 2 per army 
1,001-2,000 Up to 3 per army 
2,001-3,000 Up to 4 per army 

If you setup 2000 points, you can take 4 or more detachments for example

**Comment by ilaunchbury** [comment]
What exactly are you asking for us to do here? You can already create armies with as many detachments as you like. Are you suggesting that we implement a restriction? The above page quote is only a suggestion, not a rule, so we won't be implementing anything based on that.
