### ISSUE TITLE
Apothecary (biker) can't take the relic eternal shield

### ISSUE THREAD

**Issue by wismeril** [BSData/wh40k#1662]
**File/Catalogue:**  Adeptus Astartes

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** Detailed issue description.
Apothecary and Apothecary biker can't take the relic eternal shield.
Because you need to take a storm shield first to replace it, but that is not an option possible.

**Comment by flakpanda** [comment]
Well about half the relics in the list cannot be taken, but this is by design. I do not have the functionality to check hidden status based on wargear with the current setup. The relics list is used by a lot of nodes, and would require an entire rework to do what you ask.
