### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Baneblade missing from options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1668]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** The option to take a Baneblade for Death Korps of Krieg is missing from the Lord of War options

**Comment by CrusherJoe** [comment]
Fixed in v23 of the DKOK catalog.
