### ISSUE TITLE
Chaos - FW Renegade and Heretics: Renegades Command and Disciples squad count Disciple Weapon Team as one model instead of two

### ISSUE THREAD

**Issue by PrizrakMihhail** [BSData/wh40k#1670]
**File/Catalogue:** FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** When you add Disciple Weapon Team to Command squad, or Disciple squad, it only counts as having one Disciple, instead of two (to fulfill minimum squad Command squad of 4 you will need to have 3 Disciples + Disciple Weapon Team instead of 2 Disciples + DWT).

**Comment by ilaunchbury** [comment]
This is currently true for all HWTs in Renegades squads.
