### ISSUE TITLE
Spacewolf cavalry storm shield value wrong. Shows 15 points should be 5. 

### ISSUE THREAD

**Issue by bigben552** [BSData/wh40k#1674]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by bigben552** [comment]
In warhammer 40k v24. Imperium -spacewolves v12

**Comment by ilaunchbury** [comment]
The cost is 15 points in the Index and hasn't been mentioned in an FAQ as changing.
![image](https://user-images.githubusercontent.com/29306451/32041023-957ea3e8-ba2a-11e7-8fc6-09b1960b00ef.png)

**Comment by bigben552** [comment]
Aaaaarrrggghh. Thanks somehow missed that. Using 5 point as not a character.
