### ISSUE TITLE
Supreme Command Detachment - doesn't count HQs for secondary factions

### ISSUE THREAD

**Issue by PrizrakMihhail** [BSData/wh40k#1676]
**File/Catalogue:** Warhammer 40,000 8th Edition

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** If you select more than one faction for Supreme Command Detachment, it only counts HQs from the first faction. I've checked it on all Imperium and Chaos factions.

**Comment by alphalas** [comment]
![b1635f10-c64f-4c9c-86a0-d484a3e24181](https://user-images.githubusercontent.com/15703066/32057839-6829a8c8-ba36-11e7-87f3-1f8e4e407a49.png)


Make sure all your data is up to date and correct.

**Comment by alphalas** [comment]
![5b3e3771-5afb-44a2-bc14-dc7b05d99e42](https://user-images.githubusercontent.com/15703066/32058001-d9787bbc-ba36-11e7-8712-5a2f4c183476.png)

**Comment by alphalas** [comment]
![48457c80-b498-4673-b3d2-28032d3f6ca7](https://user-images.githubusercontent.com/15703066/32058021-e5b40414-ba36-11e7-8425-29df315c4439.jpeg)

Make sure the secondary detachments are actually child detachments, not just additional detachments- when done correctly you’ll see an indent like in this screen capture.

**Comment by PrizrakMihhail** [comment]
Probably i didn't describe the issue clear enough. When you select more than one faction for Supreme Command and add HQs for both of them, it still gives error, that there is not enough HQs. Also i've checked that all data files are up to date.
![1](https://user-images.githubusercontent.com/33093732/32058131-e6d1e722-ba71-11e7-9b4c-67c3cf5b999e.png)
![2](https://user-images.githubusercontent.com/33093732/32058132-e6ede8fa-ba71-11e7-9efc-bbafe63395f8.png)

**Comment by ilaunchbury** [comment]
^^ You just ninjaed me @PrizrakMihhail.

**Comment by alphalas** [comment]
![4cfead0d-b7fa-49b9-8b03-7a46854a8276](https://user-images.githubusercontent.com/15703066/32058358-c538659e-ba37-11e7-8a6d-51a1a974636b.png)

Works on mobile.

**Comment by PrizrakMihhail** [comment]
@ilaunchbury haha :D happens sometimes
@alphalas i tried it on mobile as well and just as you showed, it doesn't reproduce. But for desktop vrsion the issue is valid, at least for me.

**Comment by alphalas** [comment]
Which means it is a BattleScribe on windows bug, which is unfortunately not our problem. @Jonskichov

**Comment by PrizrakMihhail** [comment]
oh, sorry than

**Comment by alphalas** [comment]
Not a problem- just had to verify if it was actually a data issue or app issue. Thanks!
