### ISSUE TITLE
Chaos - Renegades: Need updates from latest FAQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1679]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Renegades and heretics army list is missing updated lord of wars from the most recent FAQ (access to the Shadowsword and Stormsword)

**Comment by radionausea** [comment]
Could you please direct me to that FAQ? 
I'm looking at 1.1, which Im sure is thea latest, and R&H don't get access to the Shadowsword or Stormsword (DKoK do though)

**Comment by ilaunchbury** [comment]
@radionausea is correct. R&H don't get those super-heavies, but I have made the other relevant changes from the FAQ.
