### ISSUE TITLE
Imperium - Astra Militarum: Master of Ordnance should have OFFICER keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1682]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 1.00.76

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Astra militarum. In the codex, master of ordnance had the officer keyword. Therefore it should be possible to give him the heirloom: kurovs aquila? Right?

**Comment by ilaunchbury** [comment]
He's missing the Officer category in the catalogue so it's getting hidden by mistake.

**Comment by CrusherJoe** [comment]
Fixed in v75 of AM catalog.
