### ISSUE TITLE
Imperium - Astra Militarum: Crusader PL does not scale

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1683]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** Yes

**Description:** Crusaders power level doesn't change when unit size is increased

Crusaders base cost 2 for 2 and are then +1 pl for 2 more, +2 for 4 more, +3 for 6 more and +4 for 8 more

**Comment by CrusherJoe** [comment]
Fixed in v75 of AM catalog.
