### ISSUE TITLE
no eldar update?

### ISSUE THREAD

**Issue by JasonTheGinge** [BSData/wh40k#1688]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by JasonTheGinge** [comment]
wtf guys space marines were out the day before

**Comment by alphalas** [comment]
No, it was day after - and guard was out three days after – it’ll come out when it comes out. We are all volunteers here, we have lives.

Also see #1678
