### ISSUE TITLE
Imperium - Astra Militarum: Regiment selection causes error in Aux. Support Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1689]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** When adding an Auxiliary Support Detachment it requires that you also add a Regiment, which then uses up the selection limitation of 1, preventing you from adding any units.

**Comment by ilaunchbury** [comment]
@alphalas, I think this is because the Regiment selection is uncategorised. In CSM, the Legion selection is explicitly set as "No Force Org", and doesn't cause the same error.
