### ISSUE TITLE
Astra Militarum: Missing spaces in regiment ability descriptions

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#1692]
**File/Catalogue:** Astra Militarum v76

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** Several of the Regiment ability descriptions have missing whitespaces.

Armageddon, Cadian, Catachan, Mordian, Tallarn are all affected.

**Comment by CrusherJoe** [comment]
Fixed in v77 of AM data file.
