### ISSUE TITLE
Tyranids: Tyrannocyte's Invasion Organism has incorrect text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1695]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Tyrannocyte’s Invasion Organism rule is wrong — it seems to be describing the Sporocyst’s Bombardment Organism rule.

**Comment by GenWilhelm** [comment]
Looks fine on my end. Can anyone else confirm?

![tyrann](https://user-images.githubusercontent.com/22036809/32284609-abc4e9f6-bf1f-11e7-8732-3804b9d21e30.png)
