### ISSUE TITLE
Aeldari - Ynnari - Apply Craftworlds Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1699]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Not a bug, but just we need an update of unit price of the craftworld unit, the point are still the same of the index

**Comment by FarseerVeraenthis** [comment]
Yup, considering I've not finished with the Craftworld update yet and the Ynnari CAT is built from it it will be a couple of days yet...
I might consider just updating the points but it depends how long it takes me to get the Craftworlds CAT done.

**Comment by USSX-Hares** [comment]
@FarseerVeraenthis , could you verify changes?

**Comment by danpoynnari** [comment]
Thanks for the craftworld job !
We'ill be very happy when you be able to update the ynnaris.

;D

**Comment by KalChoedan** [comment]
Any danger of a pull request for this? I've been using #1699 for the last two weeks and it looks fine (though it will now need an update for CA Drukhari/Harlequins.)

**Comment by GenWilhelm** [comment]
@FarseerVeraenthis, @USSX-Hares, what's the status on this?

**Comment by amis92** [comment]
@FarseerVeraenthis does it mean that we can remove the branch hares_ynnari? It has 1 unmerged commit, but I guess your work here manually merged these changes?

**Comment by FarseerVeraenthis** [comment]
Erm... After @WindstormSCR has been hacking at the Ynnarii CAT that branch is going to be completely useless...
So it definitely can be killed.
