### ISSUE TITLE
Incorrect power level for rust stalkers 

### ISSUE THREAD

**Issue by lukekellyvf** [BSData/wh40k#1705]
**File/Catalogue:** 
40k
**BattleScribe version:** 2.01.
2.01
**Platform:** Windows/iOS/Android/Mac/Linux
iOS 

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
Sicarian ruststalkers have an initial incorrect power rating (12 instead of 6)

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/32374373-a6e1e4dc-c09d-11e7-9170-fb9e3eb750d9.png)

**Comment by lukekellyvf** [comment]
Please don’t close it’s not right

With one squad it’s right
[image1.png]

With 2 it goes wrong
[image2.png]

These are squads of 5 so they should be 6 each not 12 each

Sent from my iPhone

On 3 Nov 2017, at 10:48 pm, King Heresy <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1705<https://github.com/BSData/wh40k/issues/1705>.

**Comment by Thairne** [comment]
When opening an issue, please be specific on whats wrong. Helps greatly with identifying the issue in the first place ;)
