### ISSUE TITLE
REFERENCE: Failure to download 40k files; BS failure to update

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#1706]
There is a known bug on the appspot page; shortly after releases both WH40k 8e repo and the 30k HH repo “fall off” appspot, meaning they can’t be downloaded and will cause your BS app to throw error messages at you. To verify if this is the issue, Check the appspot link (where BS downloads from). If you don’t see it on the list there, that is what is going on. Unfortunately, we don’t know why this happens, and there’s nothing we can do to fix it. It will eventually come back, usually within 8 hour or so, and you will be able to redownload as normal.

**Comment by amis92** [comment]
For reference, there is an umbrella issue over here: https://github.com/BSData/bsdata/issues/208

**Comment by amis92** [comment]
Since it's pinned, I'll now close the issue again. :)

**Comment by kracktheklown** [comment]
I think the repository isn't visible on Appspot.

**Comment by rabscutle** [comment]
Repository no visible on Appspot

**Comment by hyperlance** [comment]
If I manually try and add the repo I get this error 
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 34

**Comment by amis92** [comment]
@hyperlance manual URI addition doesn't work with plain GitHub repo URL.

You can use BSData Gallery on BattleScribe for Android and on PC (essentially non-iOS devices):

> Follow the steps from there:
> https://github.com/BSData/gallery#usage

For iOS you're left with a legacy distribution system, but it'll work for some time still:
> Import data from URL with the following URL:
> https://github.com/BSData/wh40k/releases/latest/download/wh40k.latest.bsi
