### ISSUE TITLE
Aeldari - Craftworlds: Striking Scorpions Exarch points cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1708]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** The points for the striking scorpion exarch are off.
Base points are 15p - Should be 14p with scorpion chainsword (shuriken pistol is free)
Scorpions claw + scorpion chainsword is 22p - should be 13p (12p for scorpion claw and 1p for chainsword)
Shuriken pistol and biting blade is 12p - Should be 8p (for the biting blade, pistol is free)
Shuriken pistol + scorpion chainsword is 2p - should be 1p

**Comment by FarseerVeraenthis** [comment]
moved to the bug tracker #1704
