### ISSUE TITLE
Aeldari - Craftworlds v19 - Missing Index options

### ISSUE THREAD

**Issue by Khalek** [BSData/wh40k#1709]
Missing weapon options on the non-Index Autarchs. Requesting the Index options get added at Codex prices following the Dreadnought issue with Space Marines and GW's response on the wh community page (Index entries still legal, at codex prices). 

Most likely will be answered by GW in the week 2 FAQ and errata due to the (sorry for the language) shitstorm it has caused in most forums, but so far it is the same case as dreadnought weapon options and those have been accepted in all big tournaments.

Options: 
- Choice for Banshee mask/Mandiblasters on all Autarchs
- Weaponry missing from the gutted entries (too many to list)
- Same for Exarchs in most aspect warrior squads

Also, where can we talk about the choice between Index/Codex for Path of Command? the Codex has the rule outside of the Autarch datasheet, so I have my doubts about if you can choose among the two options

**Comment by FarseerVeraenthis** [comment]
you need to select the other "Path of Command" option, and then the Index options will appear as if by magic :smile:
