### ISSUE TITLE
Admech: Still an issue with ruststalkers 

### ISSUE THREAD

**Issue by lukekellyvf** [BSData/wh40k#1715]
**File/Catalogue:** 
V25
**BattleScribe version:** 2.01.05

**Platform:** Windows/iOS/Android/Mac/Linux
iOS 
**Dropbox:** Yes/No
Yes
**Description:** Detailed issue description.
From issue 1705. please don’t close it’s not right. 
If you add 2 squads of rust stalkers then they become 12 power each instead of 6 each. If you add one squad they are correct at 6 power but as soon as you add another seperate squad it is incorrect.

**Comment by ilaunchbury** [comment]
#1705 reopened
