### ISSUE TITLE
Aeldari - Craftworlds: Runes of Battle range incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1723]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** The ranges for the Runes of Battle, Conceal/Reveal, Embolden/Horrify, Enhance/Drain, are incorrect  . Of the pair only the negative one is the correct range 18" the other says 3".

**Comment by FarseerVeraenthis** [comment]
Drat! I'll get to it

**Comment by FarseerVeraenthis** [comment]
moved to the bug tracker
