### ISSUE TITLE
Chaos-Deathguard Hellbrute Storm Bolter/Heavy Flamer

### ISSUE THREAD

**Issue by wdrake3** [BSData/wh40k#1726]
Chaos-Deathguard

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Hellbrute Fist needs an option to add Storm Bolter, Heavy Flamer, or none

**Comment by ilaunchbury** [comment]
Select the fist after adding the Helbrute to see the fist weapon options.
