### ISSUE TITLE
Aeldari - Craftworlds: Runes of Battle descriptions incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1729]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** The Runes of Battle power Enhance/Drain both parts of the power are wrong. Also the power Conceal/Reveal the Conceal part is wrong, and the Embolden/Horrify the Embolden part is wrong.

**Comment by FarseerVeraenthis** [comment]
I'll have a look

**Comment by FarseerVeraenthis** [comment]
moved to the bug tracker
