### ISSUE TITLE
Aeldari - Craftworlds: Swooping Hawks PL increment error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1730]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Increasing Swooping Hawks from 5 models to 6+ adds 7PL when it should only add 3 (so 6PL for a squad of 6-10). Points costs are correct

**Comment by FarseerVeraenthis** [comment]
moved to the bug tracker
