### ISSUE TITLE
Aeldari - Craftworlds - Can Avatar take relics?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1737]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** Nothing huge, but the Avatar can take the "THE PHOENIX GEM" Remnant of Glory.

**Comment by ilaunchbury** [comment]
This is in no way ambiguous.

1. The Avatar is in the separate section of the unit costs page which contains named characters. p126
1. His wargear is included in his cost, like every other named character. p126
1. You can only take one Avatar of Khaine in an army, like all the other named characters.  p86

There appears to be no way to read this other than that the Avatar is a named character in game terms.

- Relics are specifically forbidden to named characters. c.f. p122

Thus, the Avatar can't take Relics.

**Comment by alphalas** [comment]
Thanks Ian!

**Comment by FarseerVeraenthis** [comment]
I mean, that's why I wrote the file like that in the first place :wink:
