### ISSUE TITLE
Chaos - Death Guard, sorcerer with jump pack

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k#1738]
v21 of the file.
Death Guard sorcerers can't have jump packs in the index, codex nor from FAQs.

**Comment by ilaunchbury** [comment]
It's allowed from the Index. See #1414.

**Comment by radionausea** [comment]
I'm loot at the Death Guard army list on page 57 of the index right now. There's no option for sorcerers with Jump Packs. 
Standard sorcerer, Sorcerer in terminator armour, and sorcerers on Palanquins are allowed. Not with jump packs.

**Comment by radionausea** [comment]
I get it, the that it's an option on the normal Sorcerer datasheet
Rather than a separate entry like most jump pack entries

**Comment by radionausea** [comment]
But sorcerers have an entry in the codex now that doesn't include jump packs as an option. You use the most recent datasheet for rules and DG Sorcerers no longer have the option to have a jump pack. Maybe have an option for index Vs codex like the Eldar codex autarchs

**Comment by alphalas** [comment]
It is just fine the way it is
