### ISSUE TITLE
Aeldari Craftwords: Farseer and Warlock pistols should be mandatory.

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#1739]
They need a min 1 constraint.

**Comment by FarseerVeraenthis** [comment]
I thought they already had one... I bet it's down to the bloody relic validation! Dastardly things!!

**Comment by FarseerVeraenthis** [comment]
I just checked and all of the Warlocks and Farseers in my list automatically come with Shuriken Pistols... Unless you have selected Kurnous' Bow, in which case, the pistols are replaced...
