### ISSUE TITLE
Astra Militarum Master of Ordnance

### ISSUE THREAD

**Issue by Mikle103** [BSData/wh40k#1740]
**File/Catalogue:** Astra Militarum v77

**BattleScribe version:** 2.01.05.93

**Platform:** Windows

**Dropbox:** No

**Description:** Master of Ordnance has both \<REGIMENT> and OFFICER keyword but will not validate battle forged list with a corresponding command squad.

eg 3 command squads in a battle forged army with the following, 1x Company Commander, 1x Platoon Commander, 1x Master of Ordnance

**Comment by GenWilhelm** [comment]
Edited to fix formatting.

**Comment by CrusherJoe** [comment]
Fixed in v78 of AM datafile.
