### ISSUE TITLE
Astra Militarum Primaris Psyker profile is wrong. 

### ISSUE THREAD

**Issue by Toreador13** [BSData/wh40k#1741]
Primaris Profile is listed as 
![image](https://user-images.githubusercontent.com/6875311/32670475-82a11a68-c609-11e7-9e2a-ef3641fdba94.png)

While in fact it should be 
![image](https://user-images.githubusercontent.com/6875311/32670500-92ca4950-c609-11e7-8242-e0a0dcbe5f13.png)

Quite a change in ability ;)

**Comment by CrusherJoe** [comment]
Fixed in v78 of AM datafile.
