### ISSUE TITLE
Craftworld - Incorrect Power Cost for Striking Scorpions and Howling Banshees

### ISSUE THREAD

**Issue by bonds0097** [BSData/wh40k#1742]
**File/Catalogue:** Craftworld Eldar

**BattleScribe version:** 2.01.

**Description:** The PL cost for these 2 units is incorrect. Howling Banshees are  at 8 PL for 10 Banshees and should be 6 PL (3 base +3 for 5 Additional Banshees). Likewise, Striking Scorpions are at 7 PL for 10 and should be 8 PL (4 base +4 for 5 additional Scorpions).

**Comment by FarseerVeraenthis** [comment]
that would be because I didn't update the PL increments then...!!

**Comment by FarseerVeraenthis** [comment]
Howling Banshees are done in version 22 (I'm just completing it now) but actually, Scorpions are already correct - check your Codex :wink: - they are 4 base, +3 for up to 5 extra dudes...

**Comment by bonds0097** [comment]
Awesome!

My bad on the Striking Scorpions, the odd unit with weird scaling always trips me up.
