### ISSUE TITLE
Tyranids: Sporocyst missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1748]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** After creatimg a new Tyranid list, I can't find the sporocyst unit anywhere and I believe it is supposed to be in the heavy support section. I can't find it there or in any other section. Thanks for all your hard work!

**Comment by GenWilhelm** [comment]
Sporocyst is a Fortification, so you need a detachment that allow one of those.

![sporo](https://user-images.githubusercontent.com/22036809/32724764-80600ddc-c86a-11e7-9711-e60759c97659.png)
