### ISSUE TITLE
Auxilliary Support Detachment Validation with Regiment

### ISSUE THREAD

**Issue by IdleMuse** [BSData/wh40k#1750]
**File/Catalogue:** Astra Militarum (+possibly more)

**BattleScribe version:** 2.01.X

**Platform:** Android

**Dropbox:** No

**Description:**  The mandatory selection of a Regiment is counted against the number of units included in an Auxiliary Support Detachment, which is itself limited to 1, so the validation fails either way - either you don't have a regiment, or you have too many selections.

**Comment by ilaunchbury** [comment]
I'm not able to replicate this in v77? Is your regiment selection showing being in the as "No Force Org Slot" category? If not, you need to update your data.

**Comment by IdleMuse** [comment]
Ah yeah, updated data and fixed, my apologies!

Cheers!

**Comment by CrusherJoe** [comment]
Good deal -- closing this one.
