### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Mikle103** [BSData/wh40k#1752]
Hi this isn't an issues just a suggestion and don't know if possible or is in data or with battlescribe itself,

But if you have multiply detachments which are all validated to have a total of command points.

and example is with this list which has a total of +8CP

[15th PDF of Lambad III.zip](https://github.com/BSData/wh40k/files/1469049/15th.PDF.of.Lambad.III.zip)

have added an additional cat file to make valid.

cheers and thanks for the great work

**Comment by Mikle103** [comment]
Just another thought would it also be possible to have a squad count (total number of models) in a selection. As in below example. (Size XX)

![untitled](https://user-images.githubusercontent.com/30399027/32759897-a9cec90c-c93b-11e7-8b94-d26918d92a6c.png)

**Comment by WindstormSCR** [comment]
There is no way to automate display of CP, as you cannot add a modifiable cost value to a Force Entry or Category Entry (the only options the main GST allows)

Unit sizes would cause a very considerable files bloat and require a huge amount of implementation work for minimal gains (I tried them with the mobile set and it was awful even with the way those were set up, which was far easier)

**Comment by Mikle103** [comment]
thanks for the feed back understand limitations, was only suggestions wasn't sure like I stated if it was a Battle Scribe enhancement or done in the data files
Thanks again
