### ISSUE TITLE
Imperium - Grey Knights v12 (Venerable Dreadnought Autocannon)

### ISSUE THREAD

**Issue by blazoncek** [BSData/wh40k#1758]
**File/Catalogue:** Imperium - Grey Knights v12

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** When selecting **Autocannon** as an upgrade for **right hand** on Venerable Dreadnought it gains a new type of Psyker (Grey Knights Psyker) which replaces original (Psyker (Sanctic 1)). It is not possible to unselect original power and the roster becomes invalid.

**Comment by ilaunchbury** [comment]
I suspect this is because the autocannons are an Index option and therefore use the Index datasheet, which has a different psychic profile to the Codex version.

This distinction should probably be removed.

**Comment by tekton** [comment]
That is exactly why, that option is not in the codex.

I had that on my radar already; with the semi-change to what GW said recently about gear there's quite a few things I need to get back to and work on. There's a couple sections that need to be re-worked and I'll get to them last this weekend or early next week.
