### ISSUE TITLE
Imperium - FW Elysians - Valkyrie Sky Talon hellstrike missiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1775]
**File:** Imperium - FW Elysians.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** The Valkyrie Sky Talon must take either 2 Hellstrike Missiles or 2 Multiple Rocket Pods. In the program it only presents an option for 1 Hellstrike Missile or 2 Multiple Rocket Pods. You cannot take a single Hellstrike Missile as they come in pairs and you must pay 40 points for the two of them.

**Comment by CrusherJoe** [comment]
Changed cost of Hellstrike Missiles, indicated they are a pair in v10 of datafile.
