### ISSUE TITLE
Imperium - Astra Militarum - Sergeant chainsword no longer mandatory

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1784]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** Hello,

I noticed a validation error that should not be in the Astra Militarium infantry squad.  For Sergeants, it errors when you de-select the default "Chainsword" option.  According to the Codex, a Sergeant defaults to having a Laspistol and Frag grenades, but not a Chainsword.  They can optionally take, but are not obligated to have, a chainsword or powersword (meaning the power axe and power maul options are also suspect, depending on how the Index-to-Codex transition rules are interpreted).

Thanks,

M.

**Comment by Nokhal** [comment]
>meaning the power axe and power maul options are also suspect, depending on how the Index-to-Codex transition rules are interpreted.   

ARE THERE WARGEAR OPTIONS FOR YOUR MODEL THAT ONLY APPEAR IN THE INDEX VERSION OF ITS DATASHEET?
   
BUT YOU CAN CHOOSE TO USE THE INDEX VERSION FOR ITS WARGEAR OPTIONS

RAI seems pretty clear to me. RAW could imply that loadouts are exclusive, but it also could imply that they are additive.
RAI obvious goal is that any of your cool mini that you converted to be legal with the index should be still playable even if GW is not selling them as out-of-the-box wyswyg (codex options). 
So only THAT guy could argue that potentially sergeants can't wear power maul, and even then it's better to give an options that 99% of players will find legal than lack a legal options that only 1% of player find illegal.    
Best way to represent them in battlescribe imo is to have them additive with Codex costing for index options


The sergeant options are hence as follow :   

All of the costing are from AM codex, unless not listed in said codex and hence from index.

-Come stock with Laspistol and Frags

*May replace the laspitstol with options from the AM codex ranged weapon list (Bolt Pistol, Boltgun, Plasma Pistol)
*May replace the laspistol with options from the index ranged weapon list. As the end result is identical to the option above, we have to discard this option
 
(Limit 1) :
*May take a power sword
*May take extra chainsword
**Said extra chainsword can be replaced with Power Axe => Simply a May take extra Power Axe entry
**Said extra chainsword can be replaced with Power Maul => Simply a May take extra Power Maul entry
**Said extra chainsword can be replaced with Power Sword => No need for twice the same option the same list.

**Comment by alphalas** [comment]
Simple answer is we remove a min1 constraint from the chainsword option- it’s still valid because it was wargear in Index.

**Comment by CrusherJoe** [comment]
Fixed in v79 of AM datafile.
