### ISSUE TITLE
Priest : Wargear costing and Options.

### ISSUE THREAD

**Issue by Nokhal** [BSData/wh40k#1785]
**File/Catalogue:** 
Astra Militarum & Adeptus Ministorum both.

It's a direct application of the november designer commentary
https://spikeybits.com/wp-content/uploads/2017/11/flowchart.jpg

The most recent sheet of the Priest is from the Astra Militarum codex, and hence it's basic options and all of it's rule are those described in this unit sheet.
  
Priest also have however all the  gear options described in the Index Imperium 2, but with AM price if available (meaning plasma price drop but bolter/bolt pistol now costing 1 pts).  
  
So : 
Come stock with laspistol and frag+krak.
● Free Extra autogun (AM codex)
● Free Extra chainsword (AM codex)

Everything below is (Index Imperium 2) wargear options
● Can replace the stock laspistol with : 
-Bolt Pistol  (1pts, AM Codex)
-Plasma Pistol (5pts, AM Codex)
-Inferno Pistol (12pts, Index Imperium 2)

● May take an extra (Limit 1) :
-Eviscerator (22pts, Index Imperium 2)
-Autogun (Free, AM Codex)
-Plasma Gun (7pts, AM Codex)
-Shotgun (Free, AM Codex)

Melee : 
-Chainsword (Free, AM Codex)
-Power Axe (5pts, Index Imperium 2)
-Power Maul (4pts, Index Imperium 2)
-Power Sword (4pts, AM Codex)

Ranged : 
-Boltgun (1pts, AM Codex)
-Combi-Flamer (11pts, Index Imperium 2)
-Combu-Melta (19pts, Index Imperium 2)
-Combi-Plasma (15pts, Index Imperium 2)
-Condemnot boltgun (1pt, Index Imperium 2)
-Storm bolter (2pts, AM Codex)
   

The priest entry should be the same for BOTH catalogs, with the AM one being able to be assigned relics on top.

**Comment by alphalas** [comment]
Not touching it till it’s addressed in a faq.

**Comment by Nokhal** [comment]
Hum....    

IT IS PART OF THE FAQ.  

https://www.warhammer-community.com/faqs/?orderby=post_modified&order=desc#items-warhammer-40000   


More specifically, page 6 of the "Designer commentary".

**Comment by alphalas** [comment]
Yes but Guard didn’t have the priest previously; so it’s not that simple.

**Comment by alphalas** [comment]
If you want to discuss it further, join us on the gitter. Otherwise this stays closed.

**Comment by Nokhal** [comment]
>For example, if you wished to use a Commissar with a power axe, you would check if the codex – 
Codex: Astra Militarum – has a datasheet for Commissars. It does, so you would use this datasheet – however, it does not support the wargear options which allow him to replace his power sword with a power axe, so you would use the Commissar wargear options from Index: Imperium 2.
>Similarly, as Codex: Astra Militarum does not have a weapon profile for the power axe, you would use the one found in Index: Imperium 2. When coming to calculate the points cost, the Commissar himself and the bolt pistol have points in Codex: Astra Militarum, so you would use those alongside the cost for the power axe from Index: Imperium 2.  

Literraly replace comissar with a Priest and power axe with Plasma.
