### ISSUE TITLE
Chaos - Chaos Space Marines: Daemon Prince missing Malefic talon?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1789]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** On Daemon Prince when I right click and view under the Name Malefic Talons do not appear. Even though weapon stats appear. On mobile version there are no problems.

**Comment by ilaunchbury** [comment]
Not sure what the problem is? The Talons appear for me.

![image](https://user-images.githubusercontent.com/29306451/33079422-727bc8a0-cecd-11e7-8087-f78136e2d0c5.png)
