### ISSUE TITLE
Swarmlord Warlord Traits 

### ISSUE THREAD

**Issue by cjcottell** [BSData/wh40k#1801]
The Tyranid Swarmlord only has one warlord trait but should have access to all including fleet specific Traits.

**Comment by GenWilhelm** [comment]
Page 125 of the codex states that if The Swarmlord is your warlord, it must have the Alien Cunning Warlord Trait.

![warlord traits](https://user-images.githubusercontent.com/22036809/33162071-7fe09fae-d01f-11e7-837b-390bc358d4a8.png)

**Comment by cjcottell** [comment]
Shoot, missed that. Many thanks anyway.
