### ISSUE TITLE
Imperium - Adeptus Custodes: Land Raider weapon issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1802]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** The Custodes veneable land raider lists a twin havy bolter in its description, but the datasheet only has a **twin-linked** heavy bolter (using the profile of a single HB).

**Comment by ilaunchbury** [comment]
The lascannons are also using an old twin-linked profile, instead of a twin.

**Comment by CrusherJoe** [comment]
Fixed in v5 of the datafile.
