### ISSUE TITLE
Imperium - Inquisition: Coteaz has 7th ed profile

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1804]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Inquisitor Coteaz has profile from 7-th edition codex, must be from Index Imperium 2.

**Comment by CrusherJoe** [comment]
Fixed in v8 of datafile.
