### ISSUE TITLE
Imperium - Grey Knights: Stratagem "Armoury of Titan"

### ISSUE THREAD

**Issue by new-neon** [BSData/wh40k#1805]
**File/Catalogue:** Imperium - Grey Knights v12

**BattleScribe version:** 2.01.05

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Need possibility to select Stratagem "Armoury of Titan" to get more than one relic without validation errors. (For example, it realized in Catalog "Imperium - Adeptus Mechanicus v16")

**Comment by tekton** [comment]
I thought about that, but the relics were more as a nice to have; I'm already doing some other QoL items this weekend so this will probably get in there since there's finally a request for it.

**Comment by tekton** [comment]
Do note that there's not really a great way to "spend" CP in battlescribe so you'll still need to document that somewhere on your print out!

**Comment by alphalas** [comment]
Really we shouldn’t be implementing the stratagems period; that @thairne went and did it himself is more of an exception. It’s one of those things that because of the limitations of the file, users (and by extension, event organizers) need to self-police.
