### ISSUE TITLE
Aeldari - Craftworlds, Wraithblade Ghostswords Incorrect AP

### ISSUE THREAD

**Issue by Miyth** [BSData/wh40k#1806]
**File/Catalogue:** Craftworlds Codex (2017)

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** Currently the Ghostswords for Wraithblades are listed as having an AP value of -2, while the Craftworlds codex has them listed as a -3.

**Comment by FarseerVeraenthis** [comment]
Yup, they're wrong, I'll look into it :+1:
