### ISSUE TITLE
Imperium - Deathwatch: Terminator captain weapon choice issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1807]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** Per Index, Deathwatch 'Watch Captain in Terminator Armor' uses the 'Captain in Terminator Armor' datasheet on page 12.  

However, a Watch Captain in Terminator Armor cannot swap his storm bolter (should be able to for Term Combi and Term Melee) and can only swap power sword for relic blade ( should also be chainfist, storm shield, or 1 from Term Melee).

Capt. in Term armor works properly in Space Marines 35 as well as Blood Angels 23

**Comment by Crowbar90** [comment]
The file is correct. As you can see in Index: Imperium 1 (page 171), relic blade is the only wargear option available to a Watch Captain in Terminator armour.

![Screenshot](https://user-images.githubusercontent.com/1532866/33202890-65b22cda-d0fe-11e7-8eaa-b414e55761fb.png)
