### ISSUE TITLE
Space Wolves Hellblaster Heavy Plasma Incinerator is showing the wrong profile

### ISSUE THREAD

**Issue by Marcchee** [BSData/wh40k#1808]
**File/Catalogue:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.05.93

**Platform:** Windows

**Dropbox:** No

**Description:** The Hellblaster Squad Unit Weapon Option "Heavy Plasma Incinerator" is showing the profile for a "Heavy Plasma Cannon" in its Standard Fire mode. Should be S8, AP -4, D 1 according to the Space Marines Codex.

**Comment by ilaunchbury** [comment]
SW hasn't been updated with the Codex data yet. This will be updated as part of that work.
