### ISSUE TITLE
Astra Militarum: Pistol options missing.

### ISSUE THREAD

**Issue by Mikle103** [BSData/wh40k#1836]
**File/Catalogue:** Astra Millitarum v80

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Firstly Wonderful Job you all are doing, very great full for your hard work.
Now I know with the latest update to this cat you have added in the indexes wargear option but the pistol options are not there 

Thanks in advance

**Comment by ilaunchbury** [comment]
On which model(s)?

**Comment by alphalas** [comment]
Priest - it’ll be in a later release; be patient

**Comment by Mikle103** [comment]
Thanks will wait was not sure if it was a planned thing or just missed
All good.
