### ISSUE TITLE
Imperium - Grey Knights v12 (Loremaster knows 1 additional power)

### ISSUE THREAD

**Issue by blazoncek** [BSData/wh40k#1842]
**File/Catalogue:** Imperium - Grey Knights v12

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Warlord with Loremaster warlord trait knows 1 additional psykic power. This should be reflected in selection of Sanctic Powers (for any warlord).

**Comment by tekton** [comment]
Unfortunately this is quite difficult and leads to some issues on some machines which is why that was actually taken out as a feature.
