### ISSUE TITLE
Make Abilities show on unit when in "Profile Summary" or "No Profile" view.

### ISSUE THREAD

**Issue by Anthony2017** [BSData/wh40k#1853]
**File/Catalogue:** All Catalogues

**BattleScribe version:** 2.01.05.93

**Platform:** Windows

**Dropbox:** No

**Description:** Since I would like to save paper, if I use the Summary option then I don't know what abilities each unit/model has.

I can think of three options but there are possibly others:
1. Add abilities (names) to Models's weapons/psychic box (this option was used in all but the last two snapshots below)
2. Add abilities (names) using similar logic like the Keywords in Orks and Crafworld (last two snapshots).  This might be a cleaner approach but might take more paper and doesn't give a quick model summary like the first option.
3. Add a Model column to the abilities table.  This makes it easier to see which models have that ability but hard to pull out just the model you are working with.  I'm guessing this would be the worst option.

This snapshot lists only one model with the include profiles = inline option.  I can easily see what abilities this model/unit has:
![image](https://user-images.githubusercontent.com/29674781/33488339-53126948-d67e-11e7-88d3-8ebbb0c085e9.png)

Using the same one model but summary option instead, I no longer know which abilities this model/unit has.  This snapshot only shows one model in roster so it is easy to know what they have but if you add more models like in the next two snaphsots then I no longer know which abilities belong to which model/unit.

One model/unit in Summary mode (with arrow indicating a possible location to list the abilities):
![image](https://user-images.githubusercontent.com/29674781/33487659-f3eb12b4-d67b-11e7-9c35-3c914465f9c6.png)

Multiple models/units in Summary mode (with arrows indicating a possible locations to list the abilities):
![image](https://user-images.githubusercontent.com/29674781/33488125-a4b22636-d67d-11e7-9acb-cd0b07377c6d.png)

Abilities for the multiple models in Summary mode, if 3rd option then add another column to this table listing which model has this ability:
![image](https://user-images.githubusercontent.com/29674781/33488156-c162e18a-d67d-11e7-9821-aa632e2fae29.png)

Ork's Keyword with inline option:
![image](https://user-images.githubusercontent.com/29674781/33489221-3c623b9e-d681-11e7-90db-de2a63212f15.png)

Ork's Keyword with summary option:
![image](https://user-images.githubusercontent.com/29674781/33489495-01c9dd92-d682-11e7-8e49-ac67c5bea511.png)

**Comment by alphalas** [comment]
Related to #1712

**Comment by alphalas** [comment]
Honestly option one is the best option.

**Comment by amis92** [comment]
@alphalas since you seem to understand, can you politely describe in our domain terms what's the thing here? I have vague idea but can't really pin it.

**Comment by Kohato** [comment]
@amis92 Summary view doesn't play well with the ability heavy nature of 8th edition. Abilities are all tied at the model or wargear level.  Summary view hides anything below the unit level.

**Comment by alphalas** [comment]
UNLESS we place ability links inside identically named entry “containers”

**Comment by Kohato** [comment]
Which means a new shared entry for every single ability profile in every single cat.

**Comment by FarseerVeraenthis** [comment]
I'm a little confused what has been assigned to me, the Aeldari Craftworlds CAT has this feature already...
@amis92 this means making abilities the same as mandatory wargear, I. E.  a profile inside a min/max 1 selection entry in the unit/model

**Comment by Anthony2017** [comment]
My son has just began buying Craftworlds so I haven't looked at them much.  After FarseerVeraenthis's response, I pulled a Craftworlds model to see how it is laid out.  Looks like all but 2 abilities are listed at under the model.  I circled them in the snapshot below.  Otherwise, yes, this is what I was thinking and it looks like FarseerVeraenthis has already done this for most (maybe all since I don't know about the two that are circled).  Maybe FarseerVeraenthis's solution would work for all the cats.

![image](https://user-images.githubusercontent.com/29674781/33498344-fa0a2a36-d69e-11e7-93a7-5d0cd6a6d34a.png)

**Comment by FarseerVeraenthis** [comment]
OK, specifically for those two abilities, they are army wide rules and to reduce bloat they're not attached to each unit/model directly. Apart from vehicles EVERY unit in the craftworld CAT has ancient Doom and only Wraith units do not have battle focus...

**Comment by Anthony2017** [comment]
FarseerVeraenthis, thanks for the explanation.  So would FarseerVeraenthis's solution work for the other CATs for consistency?

**Comment by FarseerVeraenthis** [comment]
@Anthony2017 there is no reason why it wouldn't work... the only problem is that it is a LOT of work to update every entry for all the CAT's that have not been written the way I've done the Craftworlds CAT. 
In reality, the reason the Craftworld CAT is in the shape it is in is because it was one of the later CAT's to be created, and I wrote it from scratch for this edition. As such, I could take advantage of other people's solutions and implement them without too much fuss...

**Comment by Jonskichov** [comment]
I just put out a new version which should do this. Also you can add rules/profiles to category entries and they will be added to selections of that category.

Desktop: 2.01.06
Android: 2.01.09
iOS: 2.01.08 (currently awaiting review)

Let me know if that's any better.

**Comment by alphalas** [comment]
I think with @Jonskichov's update we can close this; none still doesn't work but with summary working its not a big deal.

**Comment by Anthony2017** [comment]
Thanks everyone for taking care of this.  Have a great day.
