### ISSUE TITLE
Imperium - Adeptus Mechanicus - Skitarii Alphas points update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1869]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** No

**Description:** Skitarii Vanguard and Ranger Alphas still have the old costs, they should go down 1 point like the rest. Skitarii Vanguard Alpha from 9 to 8 points. Skitarii Ranger Alpha from 8 to 7 points.

**Comment by thejughead** [comment]
Issue Still present on IPhone version

**Comment by alphalas** [comment]
Because it hasn’t been released yet. Be patient ;)

**Comment by thejughead** [comment]
my bad, thanks :)
