### ISSUE TITLE
Space Marines - Aggressor Squad Sergeant cost is wrong

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#1880]
**File/Catalogue:** Space Marines v36

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** The Aggressors have dropped in price to 21pts.  The regular aggressors reflect this change, but the sergeant still costs 25pts.

**Comment by ilaunchbury** [comment]
Duplicate of #1877
