### ISSUE TITLE
Imperium - Astra Militarum - Officer of the Fleet missing OFFICER keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1881]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Officer of the Fleet should can take KUROVS AQUILA. In Addition to his name , he has the necessary keyword „Officer“

**Comment by CrusherJoe** [comment]
Fixed in v83 of datafile.
