### ISSUE TITLE
Imperium - Astra Militarum - Scion Meltagun Cost

### ISSUE THREAD

**Issue by mdmagnusson** [BSData/wh40k#1884]
**File/Catalogue:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05.93

**Platform:** Windows

**Dropbox:** Yes

**Description:** The points value for the Militarum Tempestus Scions Meltagun hasn't been updated

**Comment by CrusherJoe** [comment]
This is fixed in v83 of datafile.
