### ISSUE TITLE
Imperium - Deathwatch - Inceptor unit and weapon costs not updated

### ISSUE THREAD

**Issue by sovitus** [BSData/wh40k#1885]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** Yes

**Description:** Point costs for inceptors and plasma exterminators have not been updated. Name for plasma is also plasma blaster, which is incorrect.

**Comment by toomanyprojects** [comment]
I've also raised this issue. In the meantime, the vanilla space marine army list has the updated points, so a workaround is to add an unbound force to your army list and put the inceptors in there
