### ISSUE TITLE
Imperium - Astra Militarum - Scions plasma gun cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1889]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** No

**Description:** Plasma gun cost stayed the same at 13 pts, they did not raise up to 17 points like melta guns for units with BS3+.

**Comment by IdleMuse** [comment]
This seems to be an issue specifically with Tempestus Commands Squads. Regular Tempestus Scions troops have the updated costs correctly.

**Comment by GenWilhelm** [comment]
There's a different issue for each unit. Meltaguns should be 17pts each, and plasma guns 13pts.

Currently the troops unit have both listed at 17, whereas the command squad has melta at 12 and plasma at 13.

**Comment by CrusherJoe** [comment]
Fixed in v83 of datafile.
