### ISSUE TITLE
Imperium - Space Wolves: Wolf Guard weapon issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1893]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Wolf guard can take a chainsword without losing a bolt pistol or boltgun but this data doesn’t allow this.

Also the cost of wolf guard with jump packs is now down to 19 pts in chapter approved so this needs updating as well.

**Comment by CrusherJoe** [comment]
Looks like the FAQ changes the wargear options so you do have to make choices:

Page 158 – Wolf Guard, Wargear Options
Replace the first three wargear options with
the following:
‘• Any model may replace its boltgun with a plasma
pistol, storm shield or an item from the Space Wolves
Melee Weapons or Space Wolves Combi-weapons lists; it
may also replace its bolt pistol with a plasma pistol,
storm shield or an item from the Space Wolves Melee
Weapons list.’
