### ISSUE TITLE
T'au Hammerhead should lose Attached Drones rule when it swaps out its drones

### ISSUE THREAD

**Issue by BerkshireKnight** [BSData/wh40k#1898]
**File/Catalogue:** T'au Empire

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** No

**Description:** T'au Hammerhead keeps its Attached Drones rule, even when you swap out its gun drones for another option, when it should probably lose it

**Comment by amis92** [comment]
There's no rule saying that it loses this ability. As far as I'm concerned, it'd just be a nice bonus to hide it when definitely unnecessary. Labeling as enhancement.
