### ISSUE TITLE
Militarum Tempestus Scion troops squads plasma loades as 17 pts; the Tempestus Command squad loads plasma properly at 13 pts

### ISSUE THREAD

**Issue by SpearOfAchilles** [BSData/wh40k#1913]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by GenWilhelm** [comment]
This was fixed in 3be7797b654a4836f74958b27d27bfa51030547a.

It'll be out with tonight's release, in Astra Militarum v87 (or higher).
