### ISSUE TITLE
Chaos - Thousand Sons - Vindicator cost error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1924]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** Vindicator should cost 125pts but costs 135 in the app

**Comment by MisterTsumi** [comment]
There are a handful of other costs that are still incorrect in v21 of Thousand Sons.  I'm including them below, but if you would like them in a separate issue, I'd be happy to file that as well.

Rubric Marines - Aspiring Sorcerer base cost is 30, should be 18
Helbrute - Reaper Autocannon cost is 18, should be 15
Forgefiend - 2x Hades Autocannons cost is 66, should be 50

**Comment by ilaunchbury** [comment]
Thanks for the update. Aspiring Sorcerer is a weird one because there's no cost in the CSM Codex for it, but I think I changed it to 18 pts there so I've copied it across.

The others are all fixed now.
