### ISSUE TITLE
Adeptus Mechanicus - Skitarii Alpha Points

### ISSUE THREAD

**Issue by Sentenal** [BSData/wh40k#1932]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Skitarii Ranger Alpha should be 7 points (currently 8), Skitarii Vanguard Alpha should be 8 points (currently 9 points), Skitarii Infiltrator Princep should be 16 points base (currently 18 base)

**Comment by GenWilhelm** [comment]
This was fixed in v18, which should be out tonight or tomorrow.
