### ISSUE TITLE
Grey Knights - Twin Autocannon points incorrect

### ISSUE THREAD

**Issue by gnoxic** [BSData/wh40k#1935]
**File/Catalogue:** Imperium - Grey Knights.cat

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Twin Autocannon is currently listed at 33pts, but per CA is now reduced to 30pts. (Lines 13062 and 13101)

**Comment by tekton** [comment]
I don't see that point drop for Grey Knights anywhere in Chapter Approved- do you have a page number I can flip to?

**Comment by gnoxic** [comment]
Yessir - Bottom of page 120 under "Adeptus Astartes Wargear," in the Forge World Update section. There may be some other relevant changes in there to capture as well, haven't verified.

**Comment by tekton** [comment]
Grey Knights are a special thing, I'll need to go through and make sure there's a fall through that that actually applies to. It's all sorts of weird. Thanks for the heads up!

**Comment by alphalas** [comment]
@tek there were a bunch of GK changes

**Comment by gnoxic** [comment]
No worries - if it helps your search, the TL-Autocannon Dreadnought for GK was not in the codex, but a fall-back to Index: Imperium 1 (under the rule that if not mentioned in a codex a loadout in an index should be allowed)

**Comment by tekton** [comment]
@alphalas I got the rest of them, this was one that I thought about but put off due to some oddities which I will mention in a moment...

@gnoxic yes, BUT some of the Forge World options get weird and specifically do NOT apply to Grey Knights- esp since they weren't able to take those units/weapons from Forge World books when they came out, it would need to be the non FW to really apply to the Index v Codex. Not ignoring it, just want to make sure its right and good for everyone :)

**Comment by tekton** [comment]
After re-reading through Chapter Approved, Index 1, and GK codex (while waiting for some things to compile and a DB to decomission a node) this one just applies to Forge World units which GK couldn't take.

Technically the Designer Commentary and FAQs would also just lead it to only ever having the Index cost, so unless they call out Index points in CA in the future it wouldn't change. That said, I would argue the "Adeptus Astartes" index became the "Space Marines" codex for the case of this- so if the point reduction was there for things only in the Index I would be more inclined to reduce/change the points.

I'm going to close this basically as "Won't Fix" at this point- if we get word from somewhere else that we should re-open it, please do!
