### ISSUE TITLE
Imperium - Space Wolves - CS Update Storm Shield cost for TWolf Cav Pack Leader

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1937]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Thunderwolves Calvary pack leaders storm shield is pointed for 15 it should be pointed for 10 because he is not a character.

**Comment by CrusherJoe** [comment]
Fixed, will be in next release.
