### ISSUE TITLE
Imperium - Space Marines - Lieutenants are missing a weapon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1938]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** Space marine lieutenants are only allowed 2 weapons. They come default with 3, see page 147 of the codex

**Comment by flakpanda** [comment]
You are correct.
I do not see an issue.

![image](https://user-images.githubusercontent.com/19719565/33681390-f743563a-da89-11e7-99ef-4d3a4324ed35.png)
![image](https://user-images.githubusercontent.com/19719565/33681512-69f961c4-da8a-11e7-9494-300aeac68283.png)

**Comment by ilaunchbury** [comment]
The problem here is that you cannot give them the correct loadout. Removing
