### ISSUE TITLE
T'au Empire: Shas'o R'alai issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1943]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** Yes

**Description:** The points cost for Shas'o R'alai blacklight drones are incorrect, they were 11 points but are now 7 as of CA2017, also the sept is wrong, he is kelshan sept

**Comment by amis92** [comment]
I'm sorry, but these are all correct. You had to use Mobile Format. We do not support that any longer.
