### ISSUE TITLE
Imperium - Space Wolves: Jump Pack Wolf Guard points issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1946]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The cost of wolf guard with jump packs should be 19 Pts not 21pts as chapter approved has changed them.

**Comment by ilaunchbury** [comment]
Wolf Guard are fixed, but Pack Leader is not in v15.
