### ISSUE TITLE
Imperium - FW Adeptus Astartes - Relic Sicaran Omega Tank Destroyer

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#1951]
**File/Catalogue:** Imperium - FW Adeptus Astartes v18

**BattleScribe version:** 2.01.08

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** *via [Reddit](https://www.reddit.com/r/BattleScribe/comments/7hj5al/what_is_the_easiest_way_to_contact_the_guys_who/)*

The Relic Sicaran Omega Tank Destroyer is missing.

Rules from Forge World's web store: https://www.forgeworld.co.uk/resources/PDF/Downloads/Relic%20Sicaran%20Omega%20Tank%20Destroyer.pdf

**Comment by Crowbar90** [comment]
Closing this since it's covered in #1966.
