### ISSUE TITLE
Orks: Dakkajet weapons validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1952]
**File:** Orks.catz

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** No

**Description:** Under DakkaJet it gives a warning that you have too many supashootas saying you have above the maximum. It has a base 4 with the option to add 2 more, but the file says you can only have 2.

**Comment by ilaunchbury** [comment]
I can't replicate the issue. The Dakkajet starts with 4 supashootas and can be given up to 6 in Orks v10.

Can you provide a screenshot of the issue?

**Comment by tag8833** [comment]
It works fine for me as well.  Both on PC and Android.
