### ISSUE TITLE
Imperium - Astra Militarum - Company Commander Power Fist

### ISSUE THREAD

**Issue by vanmja** [BSData/wh40k#1953]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by vanmja** [comment]
Power Fist still listed at 10 points. Chapter Approved had changed cost to 8 points. Change has been successfully reflected in the Lord Commissar and Commissar choices. 
Android. No Dropbox

**Comment by GenWilhelm** [comment]
@CrusherJoe, did you check the platoon commander's one as well?

**Comment by CrusherJoe** [comment]
Thanks @GenWilhelm you were right, fixed Platoon Commander and Hades Breaching Drill Sgt. across all datafiles that could take it.
