### ISSUE TITLE
Chaos - Thousand Sons - warpflamer rubric marine points error

### ISSUE THREAD

**Issue by Andy377** [BSData/wh40k#1962]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Warpflamer is 15 points, Rubric marine with warpflamer should be 33 points, but is currently displayed as 30 points

**Comment by ilaunchbury** [comment]
Fixed in next release
