### ISSUE TITLE
Chaos - Thousand sons - rubric marine sorceror points error

### ISSUE THREAD

**Issue by Andy377** [BSData/wh40k#1963]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Rubric marines in Thousand Sons should be treated the same as those in Chaos Space Marine codex.  This means no points premium for the unit sorceror - he is simply a unit champion.  Basic cost 18 points as per other rubric marines.

**Comment by ilaunchbury** [comment]
Already fixed in next release
