### ISSUE TITLE
Chaos - Chaos Space Marines Noise Marine Doom Siren Price incorrect

### ISSUE THREAD

**Issue by Xarlaxas** [BSData/wh40k#1969]
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06.94

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Doom Sirens for the Noise Marine Champion still appear as 22 points, when the price has been lowered to 10 points in Chapter Approved.

The correct value (10 points) is in the Chaos - FW Heretic Astartes.catz file for the Sonic Dreadnought however.

**Comment by ilaunchbury** [comment]
This will be fixed in the next release.
