### ISSUE TITLE
Space Marine Display issue

### ISSUE THREAD

**Issue by Joshua137** [BSData/wh40k#1970]
**File/Catalogue:** Space Marine v37

**BattleScribe version:** 2.01.07

**Platform:** iOS

**Dropbox:** No

**Description: I have a list with a Repulsor and a Redemptor Dreadnought. While viewing the roster with profile summary selected, only the Repulsor’s wound track is shown. With inline summary selected, both wound tracks are visible under their respective units. I check other rosters (Orks,Grey Knights,Daemons) and they show all wound tracks with profile summary selected.

**Comment by GitArdnutz** [comment]
This seems to happen with all vehicles with wound tracks (testing with SM v37 and BS 2.01.10). Selecting "profile summary" means each vehicle displays "wound tracks: track 1, track 2, track 3" in its unit entry but the summary only shows a single set of wound tracks. It seems like it might be the wound tracks associated with the last vehicle in the army but I'd need to test it more to be certain.
