### ISSUE TITLE
Missing variable movement for Marauder units

### ISSUE THREAD

**Issue by ImJasonH** [BSData/wh40k#1974]
**File/Catalogue:** Imperium - Astra Militarum.cat

**BattleScribe version:** 2.01.07

**Platform:** iOS

**Dropbox:** No

**Description:** Marauder Bombers and Marauder Destroyers have variable movement based on remaining wounds. The profile correctly lists M as "*" but the corresponding remaining wound chart doesn't list movement values.

The movement values are:

| W | M |
| ------- | ------- |
| 11-20+ | 20"-45" |
| 5-10 | 20"-30" |
| 1-4 | 20" |

**Comment by alphalas** [comment]
fixed in v90

**Comment by ImJasonH** [comment]
Thanks! :tada:
