### ISSUE TITLE
Wulfen thunder hammer & storm shield wrong cost.

### ISSUE THREAD

**Issue by Nickopold** [BSData/wh40k#1979]
**File/Catalogue:** Imperium - Space Wolves v14 by Penguin20000

**BattleScribe version:** 2.01.05.93

**Platform:** Windows

**Dropbox:** No

**Description:** Wulfen thunder hammer & storm shield option should cost 21pts. Chapter approved 2017 states that thunder hammer for non character models costs 16pts and storm shield for non character models costs 5pts.

**Comment by CrusherJoe** [comment]
This has been fixed and will be out in the next release of the datafile.

**Comment by Nickopold** [comment]
Ok thanks good to know, i also found that the cost for storm shield for Thunderwolf Cavalry Pack Leader is 5pts to high.
