### ISSUE TITLE
Imperium - Astra Militarum - Astropath has no stat line.

### ISSUE THREAD

**Issue by Mikle103** [BSData/wh40k#1983]
**File/Catalogue:** Astra Militarum v88

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Astropth has no state line

 
![image](https://user-images.githubusercontent.com/30399027/33742256-62a7440e-dbf7-11e7-8c77-80765380625e.png)

**Comment by CrusherJoe** [comment]
Yes I noticed this last night and fixed it -- it'll be in the next release.
