### ISSUE TITLE
Stormraven hurricane bolter points incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1986]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** No

**Description:** In the Stormraven gunship Item two hurricane bolters is 8 points, should be 20?

**Comment by ilaunchbury** [comment]
Which catalogue is this in?

**Comment by ilaunchbury** [comment]
Duplicate of #1987
