### ISSUE TITLE
Blood Angels - Scout Sergeants weapon options are wrong

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#2001]
**File/Catalogue:** Blood Angels 26

**BattleScribe version:** 2.01.

**Platform:** Windows/Android/

**Dropbox:** Yes

**Description:** In the latest codex the scout option can no longer take from the Sergeant Equipment list.  His only options are to trade his bolt pistol for a pistol or melee weapon, or trade his bolt gun for a pistol.  This means storm bolters/combi weapons etc are no longer an option.

**Comment by alphalas** [comment]
#1414
