### ISSUE TITLE
Incorrect order of battlefield roles when viewing roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2003]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.10

**Platform:** Android

**Dropbox:** No

**Description:** When I attempt to view the roster the various battlefield roles are in the wrong order. It should be: Uncategorized, No force Org Slot, HQ, Troops, Elites, Fast Attack, Heavy Support, Flyer, Dedicated Transport, Lord of War and Fortifications. What it comes out as however is: No force Org slot, Heavy support , Dedicated Transport, Fortifications, Troops, Uncategorized, Lord of War, Flyer, Fast attack, HQ, and elites.

**Comment by GenWilhelm** [comment]
It's behaving differently on Android compared to desktop; on desktop it appears in the order:

1. Flyer
2. No Force Org Slot
3. Dedicated Transport
4. Heavy Support
5. Lord of War
6. HQ
7. Elites
8. Fast Attack
9. Troops
10. Fortification

I think this might be one for @Jonskichov.

**Comment by Cheexsta** [comment]
This looks like a bug with Flattened Child Forces - it works fine if you change it to Expand instead.

**Comment by amis92** [comment]
I think it was resolved in latest update (2.01.16) on Android at least.
