### ISSUE TITLE
Chaos - FW Heretic Astartes: Zhufor incorrect cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2007]
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Zufhor the impaler cost 150 instead of 130. This was ok till a couple of days ago.

**Comment by radionausea** [comment]
Chapter Approved reduced his cost to 130

**Comment by ilaunchbury** [comment]
As per previous comment, his cost was reduced in Chapter Approved.
