### ISSUE TITLE
Imperium - Blood Angels - Units and points cost

### ISSUE THREAD

**Issue by klemomac** [BSData/wh40k#2008]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android/

**Dropbox:** No

**Description:** Detailed issue description.

-Lieutenants and Lieutenants with jump packs are not listed as an HQ option
-Hand flamers should be 1 point according to codex
-inferno pistols should be 9 points
-Dreadnought points costs and power level is incorrect - dreadnought base cost is 70 points (PL7)
 also option for meltagun on combat weapon is missing
- Death Company dreadnought base points is also incorrect (should be 90) (PL9)
- Sanguinary guard base cost should be 20
- Angelus boltgun cost should be 3
- Librarian with jump pack should be 112 
- Sanguinary ancient should be 84
- Company Champion should be 40 points
- Furioso Dreadnought base cost is 80 points now
-HQ choice Captain base cost is 74
-Librarian Dreadnought base cost is now 130 down from 150

**Comment by Crowbar90** [comment]
I'm currently in the process of updating the catalogue according to the Codex. I'll leave this issue open so that I can use it to check my work when it's finished.

**Comment by klemomac** [comment]
Keep up the good work

Cheers!
