### ISSUE TITLE
Imperium - Blood Angels - Codex updates

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2009]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** Lieutenants and Lieutenants with jump packs are not listed as an HQ option
-Hand flamers should be 1 point according to codex
-inferno pistols should be 9 points
-Dreadnought points costs and power level is incorrect - dreadnought base cost is 70 points (PL7)
also option for meltagun on combat weapon is missing

Death Company dreadnought base points is also incorrect (should be 90) (PL9)
Sanguinary guard base cost should be 20
Angelus boltgun cost should be 3
Librarian with jump pack should be 112
Sanguinary ancient should be 84
Company Champion should be 40 points
Furioso Dreadnought base cost is 80 points now
-HQ choice Captain base cost is 74
-Librarian Dreadnought base cost is now 130 down from 150

**Comment by Crowbar90** [comment]
I'm currently in the process of updating the catalogue according to the Codex. I'll leave this issue open so that I can use it to check my work when it's finished.

**Comment by BAlover** [comment]
Crowbar, what's the ETA on the codex update, maybe another day or two?

**Comment by teraton** [comment]
SHould the changelist in the original post also include the new vehicle additions, such as land speeder storm and new primaris marines equipment?

-land speeder storm
-stalker/hunter
-repulsor
-redemptor
-aggressors
-reivers
-stormhawk

**Comment by Crowbar90** [comment]
@BAlover I guess not more than a couple of days until I'm done. There may be some stuff that needs fixing after that, but it's pretty minor so I'm going to fix it later, my priority is getting the datafile ready for everyday usage. Anyway, I'm pretty sure that a Codex-updated version of the datafile will be included in the next release.

**Comment by BAlover** [comment]
Excellent, thanks for the diligent work!
