### ISSUE TITLE
Imperium - Dark Angels - CA Points Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2011]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Hello, there are many wrong points values for the Dark Angels:

Predator chassis 102 -> 90pts (Codex Space Marines)
Drop Pod 103 -> 83 (Chaper Approved)
Librarian 93 -> 88 (Codex Space Marines)
Librarian in Terminator Armor 155 -> 120 (Codex Space Marines)
Techmarines 58 -> 45 (Codex Space Marines)
Intercessor 20 -> 18 (Chaper Approved)
Inceptor Squad 30 -> 25 (Chapter Approved)
Razorback 65 -> 70 (Chapter Approved)
Assault Bolter 15 -> 10
Plasma Exterminators 28 -> 17 (Chapter Approved)

Some changes from Chapter Approved and Codex Space Marines have already been applied, so this should be the most of the left overs (at least for the profiles i'm using)

**Comment by Thairne** [comment]
I won't update DA to CA levels for one simple reason:
The codex is out in a week. Hopefully there'll be a leak before, so pts will be available earlier than that.
