### ISSUE TITLE
Imperium - Blood Angels - Codex points/units update

### ISSUE THREAD

**Issue by BenBooley** [BSData/wh40k#2027]
**File/Catalogue:**  Blood Angels V28

**BattleScribe version:** 2.01.07

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.

Incorrect points values:
Encarmine Sword - should be 12p

Missing options:
Stormhawk interceptor and stormtalon gunship were added in the codex
Sanguinary Guard death masks are a squad wide option at 2ppm, not individual option (all models rather than any models)

**Comment by ilaunchbury** [comment]
The CA/Codex update for Blood Angels isn't released yet. Please check again once it has been released.

**Comment by BenBooley** [comment]
Is that not what v28 is with all the codex updates other than those?

**Comment by ilaunchbury** [comment]
Sorry, didn't realise you were pulling the master directly rather than getting it from appspot (where v28 isn't out yet).

**Comment by Crowbar90** [comment]
Sorry, I'm a bit busy these days with real life stuff and I almost forgot
this. I'm going to fix it in the next few hours!

Il lun 18 dic 2017, 12:19 XakiteX <notifications@github.com> ha scritto:

**Comment by LemartesX** [comment]
Can't wait would love to go play tomorrow!

**Comment by XakiteX** [comment]
Thanks man. Your the best! Have a great holiday.
