### ISSUE TITLE
Blood Angels: Weapon validation errors

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#2031]
**File/Catalogue:** BA v28

**BattleScribe version:** 2.01.07

**Platform:** Windows

**Dropbox:** No

**Description:** 
- When swapping weapons on a Lieutenant (for instance to give him a Power Sword instead of the default chainsword), I get a validation error "Lieutenant has too many selections from Ranged/melee weapon (maximum 1)". Looks like there's an incorrectly shared constraint somewhere.

- Assault squad sergeants should require 2 weapons minimum if not taking an eviscerator. Currently, they only require 1.

- Devastator Sergeants shouldn't be able to take 2 melee weapons as they can only swap their boltgun, not their pistol.

- Intercessor Squad Sergeant weapon selection is very weird, Would it be better to give a "none" option in the Ranged weapon group and make the chainsword a checkbox? The rules say he can take a chainsword as well as any other weapons, or he can swap his default bolt rifle for one, which effectively means he can always choose to take one, regardless of what else he takes.

**Comment by Crowbar90** [comment]
I hope this version of the Intercessor Sergeant is better. Unfortunately, everything I tried seems a bit too cumbersome.
