### ISSUE TITLE
Death Korps of Krieg Warlord Traits

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2032]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** Death Korps of Krieg only has access to the generic warlord traits from the core rules-- why is this? Krieg Warlords qualify for Imperial Guard Warlord traits, as long as they are not regiment specific-- they are 1) A character with the Astra Militarum keyword, and 2) in a regiment comprised entirely of Astra Militarum units. They meet the criteria for them, and nothing says that they cannot use the Warlord traits from the Codex. I see no reason that they should not be able to.

**Comment by alphalas** [comment]
Except for the FAQ. 

https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/imperial_armour_index_forces_of_the_astra_militarum.pdf
![c662ad55-10b7-4b28-ad6d-6fc6e72a8ecf](https://user-images.githubusercontent.com/15703066/34065966-e1864de0-e1d5-11e7-9dbe-112fdd6f930c.png)

**Comment by GenericCola** [comment]
That FAQ specifies that they cannot use any REGIMENT SPECIFIC rules. The generic Astra Militarum warlord traits are not regiment-specific.

This is exactly what I mean.

**Comment by CrusherJoe** [comment]
I'll get to work on this tomorrow (Monday). It may take a day or two to get fully implemented.

**Comment by GenericCola** [comment]
Hey, I'm seeing that this ticket has been closed, and the code has been updated, but I'm still not seeing the Relics and Warlord trait changes on my side after performing a file update several times.

Has the change not gone live yet? I'm just trying to make sure there isn't something wrong on my end.

**Comment by alphalas** [comment]
Correct, the patches have not yet been released.
