### ISSUE TITLE
Death Korps of Krieg Relics Missing

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2034]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** For the same reason that Krieg is allowed to use any of the Generic Astra Militarum warlord traits (as detailed in a separate ticket #2032 ), they are able to use any Generic Astra Militarum relics. These options are currently missing from Battlescribe. As these are two separate things, I didn't want to clump them in the same ticket together.

I'm not sure how to tag the issue, so apologies for that.

**Comment by CrusherJoe** [comment]
I'll get to work on this tomorrow.

**Comment by CrusherJoe** [comment]
Fixed in v25 of datafile, along with #2032
