### ISSUE TITLE
Update Dark Angels with data from Codex

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k#2035]
File/Catalogue: Warhammer 40K Dark Angels

BattleScribe version: 2.01.

Platform: any

Dropbox: No

Description:

Update Dark Angels Index cat to Dark Angels Codex once data is fully available

- [x] Add new army rules
- [x] Add new psychic powers
- [x] Add new warlord traits
- [x] check pts values
- [x] Add new units
- [x] Add relics
- [x] Update existing units
- [x] Test and optimize UX

**Comment by Noctem84** [comment]
i've the codex in front of me, how should i supply you the new values?

**Comment by Thairne** [comment]
Someone caught me on FB, I got most of what I need now.
I expect to be done in the next 24h or so ;)

**Comment by Thairne** [comment]
First draft is out.
I recommend NOT using it yet though since I didnt have time to test and optimize yet.

**Comment by Teevigone** [comment]
Where can I download the codex data? Please and thank you. Using android if this makes any difference.

**Comment by alphalas** [comment]
Wait for a release first ;)

**Comment by Teevigone** [comment]
I was wondering because he said the first draft is out. So I wouldn't mind trying it

**Comment by alphalas** [comment]
Yeah it’s out on the GitHub- to get it onto BS from git without it appspot is a pain on mobile.

**Comment by alphalas** [comment]
https://github.com/BSData/wh40k-7th-edition/issues/3823 if you *really* want to give it a go

**Comment by Teevigone** [comment]
Yeah I will wait thanks though alpha last, and keep up the amazing work. :)

**Comment by joshdeboer** [comment]
@Thairne I have the codex and am willing to do some testing if that would help you out. Let me know!

**Comment by Thairne** [comment]
I've just finished my work and pushed a release. MOST things should work quite ok, I might have missed a rule or two.. but nothing a quick fix and release shouldn't help with
