### ISSUE TITLE
Ad Mech phospheonix wrong cost

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k#2036]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Should be 4 points now instead of 6.

**Comment by Thairne** [comment]
Fixed in https://github.com/BSData/wh40k/commit/cf61c3c5efa69b6fd40c28ca2b389ac34d825b74 6 days ago
