### ISSUE TITLE
Adeptus Mechanicus Skitarii weapon selection validation

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#2037]
**File/Catalogue:** Imperium - Adeptus Mechanicus

**BattleScribe version:** 2.01.07

**Platform:** Windows

**Dropbox:** Yes

**Description:**
Skitarii Rangers & Vanguards are allowed to have 2 models with special weapons in the unit (3 if the unit is 10 models).  The validator instead allows 2 (or 3) of each different weapon to be added.

For example, it will allow a unit of Rangers that have the leader and 2 troopers with Galvanic Rifles, 2 with Arc Rifles, 2 with Plasma Calivers, and 3 with Arquebuses.  This is not a legal unit composition.

**Comment by Thairne** [comment]
fixed in https://github.com/BSData/wh40k/commit/8262cecedb55285ed65a8e2d4cd66f6d87f2adc7 8 days ago
