### ISSUE TITLE
Imperial Guard Ministorum Priest 

### ISSUE THREAD

**Issue by IdleMuse** [BSData/wh40k#2041]
**File/Catalogue:** Astra Militarum (v1.1.3)

**BattleScribe version:** 2.01.latest

**Platform:** Android

**Description:** Validation fails on Ministorum Priest who tries to take both an Autogun and a Chainsword, a combination which is available in the codex.

Note: I read #1785, but this is the Ministorum Priest from the Astra Militarum catalogue and the Astra Militarum codex, not related to legacy index wargear issues (which seems to be the meat of the issue in #1785). This is simply 'I can't take the options presented in the codex', much narrower scope issue.

**Comment by CrusherJoe** [comment]
Such a seemingly minor change...anyway, fixed.

**Comment by amis92** [comment]
Labeled as reference because of the by-now-classic clause:

> Just Take Whatever, I Give Up:

Referenced mutliple times across social media:
* as a "gem" on Reddit: https://www.reddit.com/r/Warhammer40k/comments/aefhdj/found_this_gem_on_battlescribe/
