### ISSUE TITLE
Craftworld Ynnari Update.

### ISSUE THREAD

**Issue by Nexadd0** [BSData/wh40k#2046]
**File/Catalogue:**  Craftworld Ynnari

**BattleScribe version:** 2.01.11

**Platform:** Andriod

**Dropbox:** No

**Description:** Still has index entries for Craftworld.. Can we get this updated? The previous request was closed but I am haven't seen an update.

**Comment by FarseerVeraenthis** [comment]
It will be in the next release, which will (kinda hilariously ironically) include the Dark Angels Codex update, and some Deathwatch updates...
Sorry for the delay, the maintainer of the Ynnari CAT went dark shortly after the Craftworld update dropped, and it's taken a while for me to find time to make all the updates a second time around, and then add all the Chapter Approved updates to both Aeldari and Ynnari - but it will be beautiful when it's released (hopefully!) :smile:

**Comment by FarseerVeraenthis** [comment]
The release is out so, update your data tomorrow and then you should be the owner of all the Craftworld and Chapter Approved update goodness :smile: if there are issues, please report them here :+1:
