### ISSUE TITLE
Imperium - Deathwatch - Primaris Points Issue

### ISSUE THREAD

**Issue by toomanyprojects** [BSData/wh40k#2051]
**File/Catalogue:**  - Imperium - Deathwatch V16

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** Primaris Hellblasters - Plasma Incinerators are overcosted. Showing as 168 points for 10, when this should be 150 (15 points per gun)

**Comment by ilaunchbury** [comment]
The Heavy Incinerator has no cost in itself so it works correctly. The other two weapons have an innate cost (which is still the pre-Codex cost), so the points aren't working out correctly.

**Comment by FarseerVeraenthis** [comment]
Yeah, that would be one I missed the other day we I was covering for @acebaur

**Comment by acebaur** [comment]
Plasma Incinerators have a cost but the entry isn't local, so I can't edit it in the DW cat. It should be zero in the global entry so that the unit entry increases it by 15 correctly.

**Comment by ilaunchbury** [comment]
Either duplicate it as a local entry (which is what seems to have been done in other cats), or edit the GST yourself.

**Comment by acebaur** [comment]
I'll probably just create my own, don't want to mess with the GST

**Comment by GenWilhelm** [comment]
Would it not be simpler just to use a modifier?

**Comment by FarseerVeraenthis** [comment]
Surely it must work in the space marines CAT, I'd just copy the construction of the entry from there and you'll be golden - auto points updates forever :+1:

**Comment by ilaunchbury** [comment]
Pretty sure I checked the SM one and it uses local entries...

**Comment by FarseerVeraenthis** [comment]
Wtf?! *smacks forehead* that doesn't make a lot of sense...

**Comment by sandres316** [comment]
Issue also exists in Blood Angels v32
Unit of 10 Hellblasters with Plasma Incinerators should be 330. Shows as 333 (153 for Incinerators)
![hbbug](https://user-images.githubusercontent.com/34804309/34324187-49d77fc4-e837-11e7-9f17-2c2ca4aec5d8.PNG)
