### ISSUE TITLE
Relic error coming up when only 1 FW relic present

### ISSUE THREAD

**Issue by frohawk8337** [BSData/wh40k#2052]
**File/Catalogue:** 

**BattleScribe version:** 2.01.
BattleScribe v2.01.11
**Platform:** Windows/iOS/Android/Mac/Linux
Android
**Dropbox:** Yes/No
NO
**Description:** Detailed issue description.
I ensured that everything was updated BS wise and list wise with the latest iteration being Dec 20th.  I think the relic rule is you can have more relic units than nonrelic in the same rule.  I am getting an error saying the maximum is 0.

**Comment by alphalas** [comment]
![f8c58dcc-4608-4f20-baf7-d8c0c77906b1](https://user-images.githubusercontent.com/15703066/34215602-e10c6146-e573-11e7-9f66-6b9c073d1f99.png)

It works correctly in BS if you have the FW detachment be the parent detachment of whatever version of SM detachment.

**Comment by frohawk8337** [comment]
Gotcha, will try it out
