### ISSUE TITLE
Dark Angels - PL values inconsistent with Codex

### ISSUE THREAD

**Issue by matthookbristol** [BSData/wh40k#2053]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.01.08
**Platform:** Windows
**Dropbox:** No
**Description:** Detailed issue description.

Missing Units
Sammael on Sableclaw not available as an option

Power Levels for some Units not updated to match codex, although some are just bonkers, and will probably get FAQ'd out in two weeks.....

HQ Units
Asmodai now 7PL
Interrogator Chaplain - now 5PL
Interrogator Chaplain in Terminator Armour - now 6PL
Ezekiel - now 7PL
Librarian - now 8PL (Yes, higher than the Chief Librarian apparently!)
Librarian in Terminator Armour - 8PL (Yes, the same price as non Terminator)
Master in Terminator Armour - 7
Primaris Master - 6
Techmarine - 4
Primaris Lieutenants - 5, 5 for additional

Troop Units
Scout Squad 4 pl, 4 for additional

Elites Units
Company Champion - 3 PL
Company Veterans 3 pl, +5 for addition 3
Deathwing Terminator Squad 13 PL +12 for additional
Servitors 3PL

Fast Attack Units

Scout Bike Squad missing - 4 PL, +4 for additional
Ravenwing Bike Squad -  5 PL,
Ravenwing Land Speeder Vengeance - 7PL

Heavy Support
Devastators - 8PL
Whirlwind - 5PL
Vindicator - 7PL
Land Raider Crusader - 16PL

Fliers
Ravenwing Dark Talon 8PL

**Comment by ilaunchbury** [comment]
Can you confirm you're using Dark Angels v33, as Sammael in Sableclaw is definitely available in that version?

![image](https://user-images.githubusercontent.com/29306451/34216364-f39adece-e59f-11e7-8fd5-631ac1064fad.png)

**Comment by GenWilhelm** [comment]
v33 is before @Thairne had set about implementing any changes. Released version is v34, and master version is v35.

**Comment by joshdeboer** [comment]
I can confirm that Sammael in Sableclaw is missing from v34

**Comment by Thairne** [comment]
Sableclaw is in v35.

**Comment by matthookbristol** [comment]
![fastattack](https://user-images.githubusercontent.com/13039120/34220367-50a13b5c-e5ac-11e7-826b-24dd0ce365a6.PNG)

No scout bikes visible on windows app

**Comment by joshdeboer** [comment]
@matthookbristol Scout bikes seem to be under the Troops category at the moment.

**Comment by Thairne** [comment]
Oh.

OOOOOH.

I see.

Done.
