### ISSUE TITLE
Imperium - Dark Angels - HQ inconsistencies with new Codex 

### ISSUE THREAD

**Issue by joshdeboer** [BSData/wh40k#2054]
**File/Catalogue:** Dark Angels v34

**BattleScribe version:** 2.01.08.96

**Platform:** Windows

**Dropbox:** No

**Description:**

- Belial shouldn't have any wargear options.
- Sammael should have Inner Circle and not And They Shall Know No Fear.
- ~~Sammael in Sableclaw should not have the Sableclaw rule.~~ _(fixed in v35)_
- ~~Chaplain on Bike, Interrogator-Chaplain on Bike, Librarian on Bike, and Techmarine on Bike aren't options anymore.~~ _(units still available through Imperium 1 Index)_
- ~~Most of the named characters are missing the Warlord option.~~ _(fixed in v35)_
- Ravenwing Talonmaster is using wrong Explodes rule.
- Interrogator-Chaplain should only have access to the Terminator Combi-Weapons for armament options.
- Librarian should not have access to Boltgun or Combi-Weapons.
- Librarian should not have And They Shall Know No Fear.
- Librarian Powers Known should read "Smite, 2 Interromancy".
- Librarian in Terminator Armor shouldn't have access to Storm Shield.
- Librarian in Terminator Armor's armament should have a minimum of 0 not 1.
- Librarian in Terminator Armor should not have And They Shall Know No Fear.
- Librarian in Terminator Armor Powers Known should read "Smite, 2 Interromancy".
- Master should not have Inner Circle.
- Master should have a Bolt Pistol in addition to other wargear options.
- Master in Terminator Armor should not have And They Shall Know No Fear.
- Master in Cataphractii Armor should not have And They Shall Know No Fear.
- Master in Cataphractii Armor is missing Power Sword option in Armament 1.
- ~~Primaris Master is missing Power Sword option (cannot be taken if Power Fist & Plasma Pistol is selected however).~~ _(fixed in v35)_
- Master in Gravis Armor should not have Inner Circle.
- Lieutenants grouping should not have the Warlord option, but the individual Lieutenants should.
- Lieutenant should have Frag and Krak grenades.
- Lieutenant should have a Bolt Pistol in addition to other wargear options.
- Primaris Lieutenants grouping should not have the Warlord option, but the individual Primaris Lieutenants should.
- ~~Primaris Lieutenants grouping should not have Relics options.~~ _(fixed in v35)_
- ~~Primaris Lieutenant is missing Bolt Pistol and Plasma Pistol options.~~ _(fixed in v35)_
- ~~Primaris Lieutenant is missing Master-crafted stalker bolt gun option.~~ _(fixed in v35)_
- Primaris Lieutenant is missing Frag and Krak grenades.
- Techmarine should not have Melee Weapon options.
- Techmarine should always have a Servo-arm, and the Servo Options should be just the Servo-harnes (which is an additional Servo-arm, plasma cutter, and flamer).

**Points Costs**
- Librarian in Terminator Armor base points cost should be 120.
- Lieutenant base points cost should be 60.
- Master in Cataphractii Armor base points cost should be 126.
- Master in Terminator Armor base points cost should be 105.

--

**Comment by Rasputinprime** [comment]
I don't even see Sableclaw as an option, just Corvex.

HQ bikes are still an option through the index and will be pried from my cold, dead, Rogue Trader Era hands.

**Comment by joshdeboer** [comment]
@Rasputinprime Sableclaw is still missing from the released version (v34), but is fixed in the current master (v35).

**Comment by Thairne** [comment]
Are you some kind of QS god?
Mother of all bug reports........

**Comment by joshdeboer** [comment]
Lol, sorry @Thairne... maybe I'll just fix them and submit a pull request next time. Still have to go over the rest of the codex.

**Comment by Thairne** [comment]
Nonononono it's fine, I'm actually quite impressed! Keep going!

**Comment by WindstormSCR** [comment]
Reminder that some of the equipment 'bugs' are legacy wargear options still allowed via designer commentary

**Comment by joshdeboer** [comment]
@WindstormSCR Don't the new Codex rules trump the legacy options though?

**Comment by alphalas** [comment]
@joshdeboer HA! You funny guy.

Seriously though, no.
![586c044a-e923-4c47-a28e-8439fc8e2452](https://user-images.githubusercontent.com/15703066/34232177-2125fdd0-e5ad-11e7-8314-e6c94c05ad4d.jpeg)

**Comment by joshdeboer** [comment]
@alphalas Oh right.. I'll make sure to compare with the Index as well. Thanks!

**Comment by joshdeboer** [comment]
Corrections listed in #2058
