### ISSUE TITLE
Deathwatch Fixes

### ISSUE THREAD

**Issue by el1l** [BSData/wh40k#2056]
**File/Catalogue:**   40k / Deathwatch

**BattleScribe version:** 2.01.

**Platform:** IOS

**Dropbox:** Yes

**Description:**  Thank you for the CA points updates!  However, noticed a few small issues after it propegated:

1). Librarian with jump pack is still missing, even though I saw it was included in the code.

2). Relic is still missing, even though I saw it in the code.

3). Warlord trait shows up 2x for characters, and perhaps that’s related to the relic not showing up.

Thanks for everything you all do to keep these datafiles updated!

**Comment by FarseerVeraenthis** [comment]
Oh yeah!! I forgot to add a root entry for the Libby, so he's there, but not...
I'm not sure what the problem is with the rest though, I did throw it together pretty quickly - more speed and less haste in the future I think!!

**Comment by el1l** [comment]
Been a few weeks, so just wondering if there is any progress on getting this Jump Librarian working.

Also, a quick note on the relic issue.  I noticed it works fine for the “Chaplain”, but all other Deathwatch HQ choices have a second warlord trait instead.
