### ISSUE TITLE
Imperium - Dark Angels - Elite inconsistencies with new Codex

### ISSUE THREAD

**Issue by joshdeboer** [BSData/wh40k#2057]
**File/Catalogue:** Dark Angels v36

**BattleScribe version:** 2.01.08.96

**Platform:** Windows

**Dropbox:** No

**Description:**
- Primaris Apothecary is missing And They Shall Know No Fear.
- Company Veterans group should not be able to take Relics.
- Company Veterans wargear options should be split into Armament 1 (Bolt Pistol, Storm Shield, Melee list, Pistols list) and Armament 2 (Chainsword, Storm Shield, Boltgun, Melee list, Pistols list, Combi-weapons list, Special weapons list, Heavy weapons list) with an additional option for a Combat Shield.
- Company Veterans Sergeant's wargear options should be replaced with regular Sergeant Equipment list, with an additional option for a Combat Shield (he does not have access to Storm Shield or Special Weapons).
- Deathwing Apothecary should have 5" move.
- Deathwing Apothecary should have the Crux Terminatus rule instead of Terminator Armor rule.
- Chapter Ancient should have And They Shall Know No Fear.
- Deathwing Ancient shouldn't have the Terminator Armor rule.
- Deathwing Champion is missing Teleport Strike rule and should have the Crux Terminatus rule instead of Terminator Armor rule.
- Deathwing Terminators shouldn't have the Terminator Armor rule.
- Cataphractii Terminator and Sergeant Melee Weapon choice should be a single Lightning Claw, not a pair.
- Cataphractii Terminators are missing the Cataphractii Armor rule.
- Tartaros Terminator Sergeant's wargear options should Lightning Claw (pair) or a combination of melee/ranged weapons.
- Tartaros Terminators heavy weapon option Assault Cannon should be a Reaper Autocannon.
- Tartaros Terminators are missing the Tartaros Armor rule.
- Dreadnought Heavy Weapons list missing Twin Heavy Bolter (carryover from Imperium 1 Index)
- Venerable Dreadnought should not have the Inner Circle rule.
- Redemptor Dreadnought has the wrong Explodes rule.
- Ravenwing Apothecary and Ravenwing Ancient should not have a Corvus Hammer.
- Aggressor Squad should have And They Shall Know No Fear.
- Reiver Sergeant should be able to replace either his Bolt Carbine or Heavy Bolt Pistol with a Combat Knife.
- Reiver Squad should have And They Shall Know No Fear.

**Point Costs**
- Company Champion should be 40 points.

**Comment by Thairne** [comment]
- Cataphractii Terminator and Sergeant Melee Weapon choice should be a single Lightning Claw, not a pair.

This makes some kind of weird sense actually. You can take a Lightning Claw for each hand, which in turn cheapens the Lightning Claws. A single one is 8 pts, whereas a pair only costs 12 pts.
So you can select a single one for one hand as an option with another weapon or just plain both.
The other solution would be to update pts cost for the lighting claws - but that is slightly buggy in BS and does not update until you do some clicks.
Unless I interpret it wrong and you pay full price for 2 LC's...
