### ISSUE TITLE
Blood Angels Scout Sgt Shared Max1 Constraint incorrect 

### ISSUE THREAD

**Issue by Ratzenkeller** [BSData/wh40k#2059]
**File/Catalogue:** Blood Angels v29

**BattleScribe version:** 2.01.08

**Platform:** Windows/iOS
**Dropbox:** Yes
**Description:** Blood Angels Scout Sergeant Equipment Options incorrect. The data file currently only allows a legal replacement of the bolt pistol OR the boltgun. The BA codex says that the Sgt. can replace his boltgun AND his bolt pistol (pp 187, iPad enhanced edition). Am I reading this incorrectly?

**Comment by alphalas** [comment]
It’s a max1 in the sgt equipment list that’s sharing between the two.

**Comment by Ratzenkeller** [comment]
Correct. There should be an equipment list and then a pistols list.

**Comment by alphalas** [comment]
@crowbar90 I’ll stab at it when I get home
