### ISSUE TITLE
Imperium - Dark Angels - Inconsistencies with new Codex

### ISSUE THREAD

**Issue by joshdeboer** [BSData/wh40k#2067]
**File/Catalogue:** Dark Angels v37

**BattleScribe version:** 2.01.08.96

**Platform:** Windows

**Dropbox:** No

**Description:**

**Dedicated Transport**
- Repulsor has the wrong Explodes rule.

**Flyer**
- Stormraven Gunship Transport rule should exclude Redemptor Dreadnoughts.

**Comment by joshdeboer** [comment]
@Thairne this is the last of it... for now :D Thanks for all of your hard work!

**Comment by Thairne** [comment]
No, I have to thank you for all the work you put into correcting my rushed work (glances @GenWilhelm), making it the smoothest release (in 2 days time) ever!
