### ISSUE TITLE
Imperium - Dark Angels - Sergeants shouldn't have access to relics?

### ISSUE THREAD

**Issue by joshdeboer** [BSData/wh40k#2072]
**File/Catalogue:** Dark Angels v38

**BattleScribe version:** 2.01.08.96

**Platform:** Windows

**Dropbox:** No

**Description:**

According to the codex, a Relic may only be given to a Character. I can't see where Sergeants gain the Character keyword... so should they have access to them?

**Comment by alphalas** [comment]
No they shouldn’t.

**Comment by Thairne** [comment]
well they were characters in 7th... :P
