### ISSUE TITLE
Talonmaster with two swords

### ISSUE THREAD

**Issue by magik1980** [BSData/wh40k#2073]
**File/Catalogue:** Warhammer 40k Dark Angels

**BattleScribe version:** 2.01.08.96

**Platform:** Mac

**Dropbox:** Yes

**Description:** Ravenwing Talonmaster not replace his power sword with relic but relic could be add as second blade (no limit to amount of swords)

**Comment by Thairne** [comment]
You replace your sword.

**Comment by joshdeboer** [comment]
I think he means you can take both a power sword and the relic at the same time, while you should only be able to replace the power sword with the relic.

**Comment by Thairne** [comment]
oh. I see

**Comment by magik1980** [comment]
Yes I'm sorry English is not my first langue. But what joshdeboer said is wright.
BTW great work guys
