### ISSUE TITLE
Space Wolves: wrong error message Rune Priest

### ISSUE THREAD

**Issue by Asuredas** [BSData/wh40k#2082]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.12

**Platform:** Android

**Dropbox:** No

**Description:** By selecting 2 psychic power from Tempestas Dicsipline for Rune Priest (which selection of Rune Priest doesn't matter) results in a error message "Rune Priest has 1 too many selections from Tempestas Discipline (maximum 1)". Due to Index Imperium it is allowed to pick 2 psychic power from that discipline, either there was no change in that rule as far as I saw.
Thanks a lot for your great work and support.

**Comment by CrusherJoe** [comment]
According to the Rune Priest datasheet on pg. 137 of Index Imperium 1 (and ppgs 138 and 139 as well):

"PSYKER: This model can attempt to manifest two psychic powers in each friendly Psychic phase, and attempt to deny one psychic power in each enemy Psychic phase. It knows the _Smite_ power and one psychic power from the Tempestas discipline."

...so, unfortunately, one power from Tempestas is all Rune Priests get.

**Comment by Asuredas** [comment]
Sorry CrusherJoe, I only have a German release. there it says two.
nice language difference though...
nevertheless thank you for your fast support.
