### ISSUE TITLE
FW Astartes Xiphon interceptor cost incorrect

### ISSUE THREAD

**Issue by KyrisGaming** [BSData/wh40k#2084]
**File/Catalogue:** Imperial armor Xiphon Interceptor

**BattleScribe version:** 2.01.

**Platform:** Windows

**Description:** the Xiphon interceptor is listed as 240 points fully kitted out, but it should be 210 - 80 for the ship itself plus the 130 for the wargear

**Comment by ilaunchbury** [comment]
The price for the Interceptor was changed to 110 pts base in Chapter Approved.
