### ISSUE TITLE
AM Tempestus CS

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k#2088]
Max0 should increment according to OFFICER, not Tempestor

**Comment by CrusherJoe** [comment]
Sorry, but that's incorrect.

From page 132 of Codex: Astra Militarum:
"Similarly, if you are playing a matched play game, then in a Battle-forged army, you can include a maximum of one Militarum Tempestus Command Squad (pg 98) in a Detachment for each Tempestor Prime (pg 91) in that Detachment."
