### ISSUE TITLE
BA : Tactical Marines heavy weapons options always 13 points more?

### ISSUE THREAD

**Issue by Takaloy** [BSData/wh40k#2091]
**File/Catalogue:** Warhammer 40k 8th Ed 1.18

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** I can't find anywhere in the codex that says that I have to pay 13 points tax to equip a heavy weapon but when trying to put on a heavy bolter, the data says I need 23 points instead of 10 points.

**Comment by alphalas** [comment]
Because you are spending 13 points for a Marine, and then 10 points for the heavy weapon.
