### ISSUE TITLE
Imperium - FW Death Korps of Krieg Engineer SW points

### ISSUE THREAD

**Issue by plaguedroneofblight** [BSData/wh40k#2095]
**File/Catalogue:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.05

**Platform:** Windows

**Dropbox:** Yes

**Description:** Krieg Engineers should be using BS3+ Special Weapon Points Cost

**Comment by CrusherJoe** [comment]
I could've sworn they were -- give me a little bit and I'll double check.
