### ISSUE TITLE
Orks: Incorrect keyword on Snikrot

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2097]
**File:** Orks.catz

**BattleScribe version:** 2.01.08

**Platform:** Windows

**Dropbox:** Yes

**Description:** Snikrot incorrectly listed having the "fly" keyword.

**Comment by aerospace-venoms** [comment]
Removed FLY keyword from Snikrot. Thanks for the issue report!

**Comment by tag8833** [comment]
Looks good to me.  Closing issue.  Thanks for the help @aerospace-venoms
