### ISSUE TITLE
Aeldari - Drukhari: Tantalus cost not updated from Chapter Approved

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2098]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.12

**Platform:** Android

**Dropbox:** No

**Description:** Tantalus point cost should be 400 not 350 thank you

**Comment by FarseerVeraenthis** [comment]
This was updated two weeks ago, the current file version is v18 and the points are correct.
Please update your data :smile: :wink:
