### ISSUE TITLE
Chaos - Death Guard: Beasts of Nurgle Wounds value incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2110]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.11

**Platform:** Android

**Dropbox:** No

**Description:** Hello,
I found a mistake into characteristics of beast of Nurgle which is 4 in battlescribe.net, but should be 5 like in the codex.

**Comment by Panchimaru** [comment]
I forgot to say That it is WOUND characteristic which is impacted
