### ISSUE TITLE
missing fw craftworld Low

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#2114]
**File/Catalogue:** 
Aeldari - Craftworlds.cat
**BattleScribe version:** 2.01.08

**Platform:** Windows/iOS/Android/Mac/Linux
all
**Dropbox:** Yes/No
Aeldari - Craftworlds.cat
**Description:** Detailed issue description.
missing forge world entrees for forge world models / a force orge for section is needed

**Comment by alphalas** [comment]
Are you taking a detachment  that has a lord of war selection? Lord of wars are only in supreme command detachments or superheavy auxiliaries.

**Comment by williamcaw** [comment]
yes a fiend was wanting to use the forgeworld componiet of the craftworld and he found that the file was missing the fw slection for  comand ,superheavey and super aux

**Comment by GenWilhelm** [comment]
What version of the file are you looking at? (latest is Craftworlds v36)

**Comment by WindstormSCR** [comment]
This is not reproducing in craftworlds V36

**Comment by ilaunchbury** [comment]
Unable to reproduce this error.
