### ISSUE TITLE
Unable to add Lords of War

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2117]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** I can't add lords of war to any list anymore, even selecting the lord of war detachment gives me no option to add the units.

**Comment by GenWilhelm** [comment]
Which catalogue are you using?

It works correctly on the few I tested.

**Comment by ilaunchbury** [comment]
Unable to reproduce this issue.
