### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k#2118]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes

**Description:** I went to redownload new data but for some reason on the site it wont load any of the data packets. it keeeps coming up with "there is an error getting the data files. the site may be overloaded right now. please try again later." it has been doing that all day.

**Comment by WindstormSCR** [comment]
We recently did a release. Check #1706 for more information

**Comment by GenWilhelm** [comment]
There's also the fact that the data site is having some fairly large updates at the moment, so it'll take a little while to settle back down.
