### ISSUE TITLE
Imperium - Space Marines: Supersonic rule degrees symbol not displaying correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2150]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Supersonic ability doesnt show the proper degree symbol ( what it shows instead: `90&#176;`)

**Comment by ilaunchbury** [comment]
Looks like the HTML got left in, but BS now ignores the tagging so it needs changing.
