### ISSUE TITLE
BS Land Speeder Storm (Scout Dedicated Transport) weapon options are not allowed in the Codex

### ISSUE THREAD

**Issue by CDollerup** [BSData/wh40k#2155]
**Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/

**Dropbox:** No

**Description:** Dedicated Transport: Land Speeder Storm can't choose weapon options in the Codex, but in BS it's possible to change options as the normal Land Speeder. It shouldn't be possible, as the Land Speeder Storm is always equipped with the Cerberus Launcher and the Heavy Bolter.

**Comment by GenWilhelm** [comment]
Wargear options from the Index version of the model's datasheet are still legal, as per the latest designers' commentary (see #1414).

**Comment by CDollerup** [comment]
My bad... I'm really sorry! On both issues...

**Comment by GenWilhelm** [comment]
It's no bother :D and not something I would expect a lot of people to know about, unless you own older models.

We appreciate the report either way.
