### ISSUE TITLE
BS Razorback (Space Marine Codex) weapon options are not allowed in the Codex #2155

### ISSUE THREAD

**Issue by CDollerup** [BSData/wh40k#2156]
**File/Catalogue:** Codex Adeptus Astartes / Space Marine Codex

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** It should only be possible to elect Twin Heavy Bolter, Twin Lascannon or Twin Assault Cannon as main weapon. Currently it's possible to elect Twin Heavy Flamer and Lascannon with Twin Plasma Gun (which are both illegal as per Codex).

**Comment by GenWilhelm** [comment]
Wargear options from the Index version of the model's datasheet are still legal, as per the latest designers' commentary (see #1414).
