### ISSUE TITLE
Imperium - Space Wolves - TDA WGPL/GHPL points errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2160]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Wolf Guard Pack Leader Terminators are now 26 points base not 31 as of Chapter Approved; also normal Grey Hunter Pack Leaders should be 13 points not 14 as of Chapter Approved.

To reproduce: Create a new list of Space Wolves (Battalion Detachment) and put in 1 Grey Hunter squad and 1 Blood Claws squad; note that the GH normal leader is 14 points not 13 and that both squads will show the Terminator pack leader as 37 points not 26.

**Comment by CrusherJoe** [comment]
All of these have been fixed in next version of datafile.
