### ISSUE TITLE
Imperium - Space Wolves - Ragnar's wolves points weirdness

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2161]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Ragnar's Svangir and Ulfgir wolves are listed as 6 points each but the entry still reads as 21 when you check the box to add them. They still show up as reading as 6 points and all in the army list but it adds 21 points to the point total.

To reproduce: Open a new Space Wolves Battalion Detachment, add Ragnar, check his Wolves' box off, and note that he goes from 141 to 162 instead of 153 as it should be.

**Comment by CrusherJoe** [comment]
Yeah...the cost for Ragnar's wolves was...well, I'm gonna go with "incorrect" and leave it at that. Fixed in next version of the datafile.
