### ISSUE TITLE
Imperium - Space Wolves - Attack Bike point check?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2162]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Swiftclaws are (I THINK) being incorrectly calculated. I'm looking at them and they read as 25 points, of which 2 points each are added for a bike and twin boltgun. CA has them at 23 base. I also can't figure out what's going on with the Attack Bikes since those are looking to me like they add up to 50 points, you have them listed as 47 in Battlescribe, and CA says they are 35 base. Help?

**Comment by joshdeboer** [comment]
They look correct to me:
**Swiftclaws**
  +23 base (CA)
  +2 for the Twin Boltgun (Imperium 1)
  = 25
**Attack Bike**
  +35 base (CA)
  +2 for the Twin Boltgun (Imperium 1)
  +10 for the Heavy Bolter (Imperium 1)
  = 47

**Comment by CrusherJoe** [comment]
The point costs for both bikes and attack bikes is indeed correct (as @joshdeboer pointed out).
