### ISSUE TITLE
Imperium - Dark Angels: Dreadnought Heavy Plasma Cannon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2163]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** Dreadnought options aren't correct.  Dark Angels dreadnoughts can only take Heavy Plasma Cannon, Twin Lascannon and Multi-Melta.  Also Heavy Plasma Cannon points cost is wrong, should only be 17 points, not 30 points.

**Comment by joshdeboer** [comment]
The legacy wargear options from the Imperium 1: Index are still available per the designer's commentary, the cost on the HPC looks like it should be 17 though.
