### ISSUE TITLE
Imperium - Dark Angels: Intercessor squad size - collective flag issue

### ISSUE THREAD

**Issue by IronTager** [BSData/wh40k#2168]
**File/Catalogue:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows & Android

**Dropbox:** No

**Description:** Opening a list causes validation errors on all Intercessor squads.

**"All Intercessor squads must have the same number of selections from Intercessor."**

I've recreated this on new lists created after the most recent data file was downloaded, and with lists created prior to it. It only gives these errors if you open a file with Intercessor squads in it.

If I have two 10 man Intercessor squads and a single 5 man Intercessor squad, next time I open the roster I'll have that validation error three times over. When that happens, adjusting one of the 10 man squads down in size causes all 3 squads to go down in size simultaneously.

Catalog seems to think all squads should have the same number of models?

**Comment by likwid-dzign** [comment]
Understand this issue is closed but I'm receiving the same validation error for hellblasters. Suggest this could be an issue with other entries and not isolated to just the intercessors, however I haven't tested these personally as of yet.
