### ISSUE TITLE
Imperium - Space Marines: Chapter Relics issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2173]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** 
- The Emperor's Champion should have Relic Options as a non named CHARACTER.
- Chaplains can't have teeth of Terra because there is no option for chainsword for them.
- Suggestion: The chapter tactics should appear in the models that can have them and if these tactics buff a characteristic it should change automatically.

**Comment by flakpanda** [comment]
1. The Emperor's Champion **IS** a named character. Therefor does not have relic access.
2. I understand this as well. However I have to bloat the file and would have to make a custom node for the Chaplains.
3. No. implementation is to difficult.
