### ISSUE TITLE
Shouldn't "skorcha buggies" be "Skorcha trakks"?

### ISSUE THREAD

**Issue by Flamekebab** [BSData/wh40k#2174]
**File/Catalogue:** Orks.cat

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** Yes

**Description:** Why is the Skorcha unit using the name "Skorcha Buggy" when both the statline and model for it are trakks?

On the statline side of things wartrakks have 12" of movement and 6 wounds, warbuggies have 14" and 5 respectively. Skorchas share the wartrakk statline, not the buggy one.

The model is no longer available but it's always been a trak, not a buggy.

**Comment by ilaunchbury** [comment]
They shouldn't really be called "Skorcha Buggy" at all as that's not the name on their datasheet. They are just "Skorcha" in the Index.

Also, their Outrider rule incorrectly references Wartrakks.

**Comment by Flamekebab** [comment]
I figured extending the name was either for clarity or a technical reason.
