### ISSUE TITLE
Imperium - Space Wolves: Warlord validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2175]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** It will not valid my list because it wants both HQ choices to be chosen as the Warlord .
Thanks

**Comment by ilaunchbury** [comment]
I'm unable to replicate this issue. Can you provide some more details?

**Comment by CrusherJoe** [comment]
I have tried to replicate this issue as well using various combinations of SW HQ units but so far no luck. Can you please tell us specifically what units you're choosing that are causing it to trigger the invalidation warning?
