### ISSUE TITLE
Death Korps of Krieg units outdated

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2177]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Several units from the Death Korps of Krieg are using the old Index data sheets in Battlescribe, and have not received the updated rules from the Codex. Back then, the argument was "the Krieg rules specifically reference the Index, therefore those are the rules you play with." However, several changes have come about that lead me to believe that this is the incorrect choice. I have always maintained that the Codex entries are obviously meant to be considered as updates to the Index entries, and should therefore be played as such.

Firstly, all of the Alpha-Mars pattern Leman Russ tanks were updated to have the new Grinding Advance rule in chapter approved, but because the Tank Commander "technically" pulls its data slate from the original Index, it uses the old Grinding Advance rule according to this logic. I think it is evident that the entirety of Krieg tanks were to be brought up to speed, not all of them except Tank Commanders, and as such, we should be using the Codex entry. (This also applies to the wargear options that almost ALL Codex vehicles have, but none in the index do-- track guards, etc.) Why would the company update Grinding Advance for all of the tanks, except for the HQ? Obviously the update to Tank Commanders in the Codex was meant to cover this base.

Secondly, and more importantly, is the flowchart released by GW which states that if a model has a data slate in a Codex, you use the data slate in the codex, as it is considered to be the "update" or "errata" for the unit, and functionally replaces the Index version, with the exception of possible extra wargear options. 

Units that I know offhand have been updated in the Codex from the Index:
>Basilisk (Earthshaker AP increased, Vehicle Equipment wargear options)
>Master of Ordinance (Points reduced to 30 from 38)
>Tank Commander (Vehicle Equipment wargear options, grinding advance rule change)
>Hellhounds (Vehicle Equipment wargear)

Those are the handful of changes I know from the top of my head. I will have to do a full side-by-side comparison to check for any other changes that were made in the Codex from the Index.

**Comment by GenericCola** [comment]
Here's an update of changes I found that need to be made in Battlescribe:

>Hellhound Infernus Cannon is profile 2D6. Incorrectly listed as D6.
>Hydras can choose items from the Vehicle Equipment section.
>Hydras were reduced from 115 points (Index) to 100 points (Codex)
>The AP on the Earthshaker Carriage Battery was increased from -2, to -3 a LONG time ago in the FAQ, but it still reads as -2 in Battlescribe.

**Comment by GenericCola** [comment]
Another update. Is this a helpful place to put these, by the way, or should I be opening a new ticket?

>Baneblade should be 390 points base (Codex), is listed as 430 points base (Index)
>Shadowsword should be 390 points base (Codex), is listed as 430 points base (Index)

**Comment by CrusherJoe** [comment]
Nope this is a good place -- thank you for tracking all these down and raising the issue. I'll fix them in the next couple of days -- should be in the next datafile release.

**Comment by WindstormSCR** [comment]
- [ ] Basilisk (Earthshaker AP increased, Vehicle Equipment wargear options)
- [ ] Master of Ordinance (Points reduced to 30 from 38)
- [ ] Tank Commander (Vehicle Equipment wargear options, grinding advance rule change)
- [ ] Hellhounds (Vehicle Equipment wargear)
- [ ] Hellhound Infernus Cannon should have profile Heavy 2D6. Incorrectly listed as D6.
- [ ] Hydras should be able to choose items from the Vehicle Equipment section.
- [ ] Hydras should be reduced from 115 points (Index) to 100 points (Codex)
- [ ] The AP on the Earthshaker Carriage Battery was increased from -2, to -3 a LONG time ago in the FAQ, but it still reads as -2 in Battlescribe.
- [ ] Baneblade should be 390 points base (Codex), is listed as 430 points base (Index)
- [ ] Shadowsword should be 390 points base (Codex), is listed as 430 points base (Index)

**Comment by GenericCola** [comment]
Hey, I just realized there's another change that I forgot to mention-- the Tank Commander also needs the Emergency Plasma Vents rules change/update.
