### ISSUE TITLE
Cost for power weapons as of Chapter Approved 2017

### ISSUE THREAD

**Issue by Junkman4** [BSData/wh40k#2178]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** the costs of power axe should be 10(currently 5) power sword 8 (4) and power maul 8(4)

**Comment by WindstormSCR** [comment]
You are listing the cost of Force weapons, not power weapons.
