### ISSUE TITLE
Codex: Chaos Daemons updates

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#2183]
Placeholder for Chaos Daemons updates. 

If this isn't closed, Codex: Chaos Daemons updates aren't finished yet!

**Comment by Kohato** [comment]
Why haven't you updated this file yet? The codex was out 116 hours from now!

**Comment by radionausea** [comment]
Could you add the Plague Hulk of Nurgle to the daemons file when you updated please? It's currently in the Heretic Astartes file but doesn't have the relevant keywords - it's a straight up Daemon.

**Comment by ilaunchbury** [comment]
@radionausea, it's in FW Heretic Astartes because it is under the Daemonbound section in Index: Forces of Chaos. This was done before my time.

Once Daemons is done, I'm considering merging all the "FW Heretic Astartes" units into the main catalogues, The main argument against it is having to duplicate a lot of the units.

**Comment by radionausea** [comment]
If you merged the FW units into the main catalogue I will crawl down my internet connection and kiss you

**Comment by GenWilhelm** [comment]
A handful of things I found while building a list; by no means exhaustive.
 - [ ] Fateskimmer should have a default selection for their 'Dagger option'.
 - [ ] Horrors should not have the 'Daemonic' ability.
 - [ ] Coruscating Flames should be S:User.
 - [ ] Bloodreaper should have a Hellblade instead of a Blade of Blood.

**Comment by ilaunchbury** [comment]
@GenWilhelm, I've fixed those.

Locus is interesting. The only constraint on a "Chaos Daemons detachment" according to p124 is that all units have CHAOS and DAEMON faction keywords. So, the way it's currently written, the characters in a multi-god army *also* get the Locus abilities.

**Comment by GenWilhelm** [comment]
Ah right. My understand was that all units in the detachment had to have the same allegiance, similar to how chapter tactics works in other factions.

**Comment by radionausea** [comment]
"if your army is battleforged all characters in Chaos Daemons Detachments gain a daemonic locus, so long as every unit in that detachment owes its allegiance to the same Chaos God."
So it does work like chapter Tactics etc. 
Characters only gain the locus of every unit has the Keyword of that God (choosing an allegiance for non-aligned units like Harpies gives them the keyword).

**Comment by ilaunchbury** [comment]
I think I'm losing it. I somehow managed to miss that.

**Comment by GenWilhelm** [comment]
#### HQ
 - [ ] Models should not be able to take multiple relics from different groups.
 - [ ] Bloodreaper's Hellblade is missing constraints.
 - [ ] Bloodthirster of Insensate Rage's "Sweeping Blow" should be D:1.
 - [ ] Wrath of Khorne Bloodthirster's 3rd wound track should be A:2.
 - [ ] Skullmaster should have the "Devastating Charge" ability.
 - [ ] Blood Throne should have the "Hellblades" weapon.
 - [ ] The Blue Scribes should not be able to take a relic.
 - [ ] Fateskimmer's Chanting Horrors should cost 5pts.
 - [ ] Rotigus should be BS:3+.
 - [ ] Rotigus should have a wound track.
 - [ ] Rotigus should have the "Attendants' Claws and Teeth" weapon.
 - [ ] Epidemius's Balesword is using the wrong profile.
 - [ ] Horticulous Slimux's "Beast Handler" ability has a typo - `youcan`.
 - [ ] Poxbringer's Balesword is using the wrong profile.
 - [ ] Sloppity Bilepiper should have the "Jolly Gutpipes" ability.
 - [ ] Keeper of Secrets should be 12 PL.
 - [ ] Be'lakor's hide condition is broken.
 - [ ] Be'lakor's psyker profile should be Cast:2.
 - [ ] Daemon Prince of Chaos's "Might over Magic" ability has been reworded.

**Comment by radionausea** [comment]
Rotigus should be able to select three powers known - can select two at present.
Selecting the allegiance to filter available units is a nice touch.

**Comment by GenWilhelm** [comment]
Alright, finished my parse. Here's everything else I found:

 - [ ] Be'lakor should have the option to be the Warlord.
 - [ ] Plague Drones should have a "Plaguesword" weapon.
 - [ ] Hellflayer's Alluress's Lashes of Torment is missing constraints.
 - [ ] Skull Cannon should not have the "Bloodletter" unit profile.
