### ISSUE TITLE
Imperium - Space Marines\Space Wolves: Wrong Immobile rule for GW Drop Pod

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#2185]
**File/Catalogue:** Imperium - Space Marines \ Space Wolves

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** The drop pod in the Space Marines and Space Wolves file has the wrong Immobile rule.
They has the FW Immobile rule instead of GW Immobile rule.
Dark Angels and Blood Angels has the right rule.

GW rule (the one they should have):

Immobile:

After this model has been set up on the battlefield it cannot move for any reason, and no units can embark upon it.

FW rule (the one they have right now):

Immobile:
This model cannot move for any reason, nor can it fight in the Fight phase. Enemy models automatically hit this model in the Fight phase - do not make hit rolls. However, this model can still  shoot if there are enemy models within 1" of it, and friendly unit  can still target enemy units that are within 1" of this model.

**Comment by CrusherJoe** [comment]
Both SM and SW datafiles reference the Immobilized rule from the .gst. I updated the rule there, so the commit fixes both Codexes.

**Comment by GenWilhelm** [comment]
@CrusherJoe that ability was created for the fortifications in the GST, which have the same wording as the "FW rule" above.
