### ISSUE TITLE
Imperium - Astra Militarum: Warlord Trait validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2196]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** For list to be valid Company Commander requires a warlord trait even when they are not selected as the warlord. This means it still requires a warlord trait selection if another model (including another Company Commander) is selected as the warlord. But since you can't have two warlords...you can never validate.

I assume this is just a glitch and unless they are selected a warlord this requirement should never show up.

**Comment by ilaunchbury** [comment]
I'm unable to replicate this in AM v95.

**Comment by CrusherJoe** [comment]
Me either. I don't think this is a datafile issue -- I run 2 Company Commanders in every Guard list I've made and I don't have this issue.
