### ISSUE TITLE
Imperium - Dark Angels: Unable to add Cypher to army

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2198]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.13

**Platform:** Android

**Dropbox:** No

**Description:** Why can't I take Cypher as an HQ or the Fallen as an Elite choice? They have the Imperium Keyword,  and I don't see anything in my codex preventing me from fielding them together?

**Comment by skonk** [comment]
Fallen are in the Space Marine codex arn't they? (not the Dark Angels codex).

So you would need to add a nested Space Marine detachment into your Dark Angels detachment to get the fallen dudes to show up and then you can add them.

![image](https://user-images.githubusercontent.com/621514/34795726-1d68985c-f64b-11e7-9b66-8cbab7ef3880.png)

![image](https://user-images.githubusercontent.com/621514/34795746-31fd614e-f64b-11e7-9d0d-bab1900d071c.png)
