### ISSUE TITLE
Dark Angels Vet Sergeants Armament validation errors

### ISSUE THREAD

**Issue by likwid-dzign** [BSData/wh40k#2199]
Imperium - Dark Angels v42

B.S. Ver 2.01.13 (Android)

**Dropbox:** Yes

Currently returning a validation error on the Veteran Sergeant from the Company Veterans; appears similar to this issue:
https://github.com/BSData/wh40k/issues/2107

**Comment by ilaunchbury** [comment]
To clarify, the Company Veteran Sergeant is unable to take more than one alternative weapon. Selecting anything other than the default weapon options results in a validation error.

**Comment by likwid-dzign** [comment]
![screenshot_20180111-200809](https://user-images.githubusercontent.com/29274769/34820053-3d951f54-f70b-11e7-9a8d-ecb7ea8bb494.jpg)
![screenshot_20180111-200452](https://user-images.githubusercontent.com/29274769/34820078-51ac485a-f70b-11e7-9f70-d5855e059b85.jpg)
![screenshot_20180111-200514](https://user-images.githubusercontent.com/29274769/34820092-5c9eeb8c-f70b-11e7-8636-9ece834831ae.jpg)
![screenshot_20180111-200531](https://user-images.githubusercontent.com/29274769/34820111-6590f1f4-f70b-11e7-844b-92592afa3c69.jpg)
