### ISSUE TITLE
Imperium - Space Wolves: Lone Wolves shouldn't have warlord traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2207]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Spacewolves v23 has Lone Wolf listed as a WarLord. Thanks for the work you do.

**Comment by ilaunchbury** [comment]
They can technically be a Warlord, but they shouldn't have access to traits due to the "An Army of One" ability.
