### ISSUE TITLE
Death Korps of Krieg Tank Commander needs updated Emergency Plasma Vents rule

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2218]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** The Tank Commander is still pulling the Emergency Plasma Vents rule from the old Index variant, and needs to be updated with the new Codex rules.

**Comment by CrusherJoe** [comment]
I double checked, and actually ALL the Leman Russ tanks needed the updated version of that rule. It'll be in the next version of the datafile.

**Comment by GenericCola** [comment]
Glad you double checked, I don't play Leman Russes very often, so I had overlooked that detail.
