### ISSUE TITLE
Genestealer mouth options

### ISSUE THREAD

**Issue by Starkhan73** [BSData/wh40k#2225]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** When assembling the brood, the codex reads on page 89 under the wargear options section of the brood entry, point two: For every 4 models in the unit, one model may have flesh hooks and/or one model may have an acid maw. This should mean on a 15 bug brood they can be given 3 flesh hooks and/or 3 acid maws however the validation will only allow 3 total.

**Comment by GenWilhelm** [comment]
What version of the file are you using? (Most recent is v27)

**Comment by ilaunchbury** [comment]
We're unable to reproduce this issue in Tyranids v27. Please try updating your data.
