### ISSUE TITLE
Chaos - Daemons: Beast of Nurgle cost/FW Warlord options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2227]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In Chaos Daemons, Beasts of Nurgle cost 38 points per model, but 34 is right, even in the death guard section it is now wrong.
Then the special characters like Cor’bax or the super heavy daemons need the new daemons warlord thread selections....

Thanks a lot and especially for the fast adding of the new rules!

Greetings 
Knorrfaust/ Benjamin

**Comment by ilaunchbury** [comment]
Death Guard Beasts of Nurgle will remain at 38pts as per that Codex until GW FAQ them to be cheaper.
