### ISSUE TITLE
Death Korps of Krieg Tank Commander Relics still missing. Officer keyword missing.

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2229]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Under the options for Leman Russ Tank Commander, there is now a box for Heirlooms of Conquest, which was previously missing, so we're a step in the right direction... however, none of the options which it qualifies for are appearing. I believe this may be because the "Officer" keyword is missing from its Categories entry, and all of the Relics which it qualifies for can only be equipped to an Officer (Laurels of Command and Kurov's Aquilla). Although, unless I am missing something, a Tank Commander can also take the Dagger of Tu'sakh, which has no requirements at all, and this option is also not present.

**Comment by CrusherJoe** [comment]
The Laurels of Command require an OFFICER with the Voice of Command ability. Tank Commanders don't have Voice of Command, they have Tank Orders -- therefore a Tank Commander isn't eligible for the Laurels.

However, reading over the Dagger of Tu'Sakh rules again...and _again_ it would happily seem that you are correct about there being no other requirement to take it other than being an ASTRA MILITARUM CHARACTER. Hello, outflanking TC in a Punisher with a plasma command squad... 

Could've sworn I fixed the OFFICER missing from the TC Categories previously. I'll have to fix that and the Dagger of Outflank.

**Comment by CrusherJoe** [comment]
Ah, @alphalas the big party pooper pointed out the Dagger of Outflankiness was FAQ'd, page 1 of the AM FAQ:

Page 138 – The Dagger of Tu’Sakh
Add the following sentence at the start of the rules text:
‘Infantry Officer model only'.

...so no Dagger for the TC. Bummer.

**Comment by CrusherJoe** [comment]
Which means, basically, the only Heirloom the TC is eligible for is Kurov's Aquila. It'll be in the next datafile update.

**Comment by GenericCola** [comment]
To be honest, Kurov's Aquilla was the only relic I ever put on my Tank Commander, anyway. I only briefly opened my Codex to make sure I wasn't missing any others. Glad I haven't been accidentally cheating this whole time.

**Comment by GenericCola** [comment]
How often are datafiles released, out of curiosity?

**Comment by ilaunchbury** [comment]
@GenericCola, there's no fixed release schedule as such, but about once a week?
