### ISSUE TITLE
Chaos - Death Guard: Inexorable Advance missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2237]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Inexorable Advance seems to be missing. My army is battle forged and everything seems to be right, but the bonus seems to be missing still.

**Comment by WindstormSCR** [comment]
Generally army wide bonuse/rules that have a "battle forged" requirement are not validated in the cat as it must be done by unit. They should be listed as a general rules entry though
