### ISSUE TITLE
Deathguard - Sorcerer with jump pack discipline selection

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k#2242]
**File/Catalogue:** Death Guard v28

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Detailed issue description.

Death Guard sorcerers whether with jump packs or not can't select powers from Dark Hereticus.  
I've raised this before but the FAQ before Christmas on equipment options from the Index should have put the nail in the coffin. The only valid way to gain DH powers in a pure death guard army is from a sorcerer on a palanquin of Nurgle.

However, if the sorcerers continue to be able choose from both - it  currently throws an error message that you must choose two powers from contagion if you opt to pick powers from Dark Heretics and vice versa.

**Comment by ilaunchbury** [comment]
I couldn't replicate your issue (I got the correct error if I didn't select any powers from the selected discipline). I've removed the alternative selection.
