### ISSUE TITLE
Chaos - Chaos Space Marines: Cultist special weapon limit incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2245]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes

**Description:** The datafile allows too many special weapons in cultists units. There should be a restriction to 1 special weapon per 10 models.

**Comment by balldrix** [comment]
ilaunchbury, this issue has not been resolved correctly. I should not be allowed to take 2 special weapons unless the model count is 20, or 3 for model count of 30. "For every ten models in the unit, one Chaos Cultist may replace their autogun with a heavy stubber or a flamer."

**Comment by ilaunchbury** [comment]
It has been resolved, but not released. You'll need to wait until the next release to see the fix.
