### ISSUE TITLE
Adeptus Mechanicus Cost

### ISSUE THREAD

**Issue by Erkenberken** [BSData/wh40k#2250]
**File/Catalogue:** 
Adeptus Mechanicus Costs (weapon Costs)

**BattleScribe version:** 2.01.
2.01.14

**Platform:** Windows/iOS/Android/Mac/Linux
Windows and android. Probably all.

**Dropbox:** Yes/No
No

**Description:** Detailed issue description.
The Costs for the ranger and vanguard weapons is wrong. It says that an arcrifle costs 11p while it costs 4p. Same for all weapons for Rangers and vanguards.
Correct Price:
Arcrifle: 4p
Plasma caliver: 12p
Transur. Arq.: 25p

BR
Erik

**Comment by ilaunchbury** [comment]
You are paying for a Ranger (7pts) with an Arc rifle (4pts), etc. Not just the weapon on its own.

**Comment by Erkenberken** [comment]
Ahh, good to know. Thanks!

BR
Erik

Den 16 jan. 2018 17:15 skrev "Iain Launchbury" <notifications@github.com>:
