### ISSUE TITLE
Imperium DeathWatch - Point cost correction

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#2252]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Point reduction for Intercessors have not been taken into account in the Deathwatch Data File. The base cost is fine (75pts per 3) The point cost is correct for Plasma (102pts per 3) but wrong for the bolters (100pts per 3) this should be 60 pt per 3. 

The points are correct under Space marines but incorrect under Deathwatch. Many thanks guys.

**Comment by FarseerVeraenthis** [comment]
You mean Inceptors (stupid Primaris names...) it will be fixed when I next merge my branch (in about 10 minutes)
