### ISSUE TITLE
Imperium -- Grey Knights (various inconsistencies)

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k#2253]
**File/Catalogue:**  Imperium - Grey Knights v14

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** 

_Dreadnought & Venerable Dreadnought_ 
- [x] Remove optional number input for "Psyker (Sanctic 1) (No cost)". All Grey Knight Dreadnoughts are psykers by default. (this was due to supporting the index separately, but v14 had the QoL update to merge them that ended up not being very high on the Q of the maintainers work)

_Land Raider Crusader_
- [x] Chapter Approved updated Twin Assault Cannon to 44 pts. Battlescribe currently displays 35 pts.
- [x] Chapter Approved updated Hurricane Bolter to 10 pts. Battlescribe currently displays 20 pts. (these come as a pair, so 20 is correct as a total...just not each; darn you Stormraven)

_Stormhawk Interceptor_
- [x] Why does it have the "Executioner" ability? I don't see that anywhere on it's unit profile. (This used to point to "Interceptor"- I even have a print out with it...so that's just weird)

_Stormraven Gunship_
- [x] Chapter Approved updated Twin Assault Cannon to 44 pts. Battlescribe currently displays 42 pts.

_Stormtalon Gunship_
- [x] Chapter Approved updated Twin Assault Cannon to 44 pts. Battlescribe currently displays 42 pts.
- [x] Skyhammer Missile Launcher is 24 pts. Battlescribe currently displays 21 pts.

_Thunderhawk Assault Gunship_
- [x] Chapter Approved updated Twin Psycannon to 50 pts. Battlescribe currently displays 28 pts.

**Comment by tekton** [comment]
Found the reason, it's a weird one. Still same timeline- thanks for pointing these out!
