### ISSUE TITLE
Imperium - FW Elysians: Officer of the Fleet laspistol should be max 1

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2263]
**File:** Imperium - FW Elysians.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** 

- Elysian Veteran Sergeant should have the option to have a shotgun (as was confirmed with Forgeworld via email). 

- Officer of the fleet has the potential to have more than one laspistol (it shouldn't be a number selected, but instead a tick box).

**Comment by alphalas** [comment]
We don’t change things from emails; if it’s not in a FAQ we don’t change it from RAW.
