### ISSUE TITLE
Imperium - Grey Knights: Storm Raven Assault cannon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2265]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** The twin assult cannon on the storm raven gun ship is displaying as 42 pts it should be 44 following chapter approved 2017. Thanks 

Edd

**Comment by GenWilhelm** [comment]
This was fixed in dbe70c3d85a0ede0767ea6e736cae0577bc2e13e (Grey Knights v15).

It was released this morning, so it should be available sometime today or tomorrow.
