### ISSUE TITLE
Imperium - Death Korps - Grenadier v. Engineer Heavy Weapon Team inconsistency

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2268]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Death Korps of Krieg Combat Engineer Heavy Flamer/Mole Launcher teams come with only one Krieg Shotgun (their stock weapon) by default, but Grenadiers Heavy Flamer teams come with two hotshot lasguns (their own stock weapon). The wording of their formation is the same, so they should either both come with 1 stock weapon, or both come with 2 stock weapons (or 0, as could be argued-- but either way, they should be the same)

My assumption has always been that they follow the pattern of the Krieg Heavy Weapons Teams, and take 1 stock weapon (just as standard Veteran Heavy Weapon Teams follow the pattern of their standard HWS and Infantry Squad counterparts), but given they they're modeled with 0 weapons in their kits, I'd be willing to believe that, as well. It seems to me that 2 stock weapons is their least likely option, but I certainly won't complain if that's the official ruling on how it works. My Grenadiers getting to rapid-fire their hellguns while they let off their heavy flamer has been a nice luxury to enjoy for only 2 points.

**Comment by CrusherJoe** [comment]
The FAQ for IA:FOTAM is actually pretty clear about it:

_Page 60 – Death Korps Grenadier Storm Squad,
Wargear Options
Change the fourth bullet point to read:
‘• Up to two Grenadiers may replace their hot-shot
lasguns with either a heavy stubber or an item from
the Death Korps of Krieg Special Weapons list.’
Add the following bullet point:
‘• Two other Grenadiers may form a Death Korps
Grenadier Weapons Team with a heavy flamer.’_

Note there is no condition that states the Weapons Team replaces their hot-shot lasguns to form the Weapons Team. As you said, the wording is clear for the Combat Engineer Squad, there is no instruction for the Engineer Weapons Team to replace their shotguns.

**Comment by GenericCola** [comment]
Okay, so you don't replace their basic weaponry, you just add their new weapon-- my point remains that the Grenadiers and Engineers should both have TWO of their stock weapon on the HWT base, but the Engineer team is only equipped with 1 shotgun by default, and then you need to manually add the second one.

There shouldn't even be a dialogue box that lets you choose the number of shotguns they can take along with their Mole Launcher or Heavy Flamer, because they ALWAYS have to take 2.

For example, when you create a Grenadier HWT in Battlescribe, the 2 hotshot lasguns is automatically denoted in their wargear and paid for.

When you create an Engineer HWT, though, it is created with 1 shotgun equipped, and you must manually increase the number of shotguns under their weapon options to 2. When creating a roster, this is extremely easy to overlook, and can result in players not paying for the second shotgun.

So, from where I stand, there's still a bug-- just like the title says, there is an inconsistency between the way that Battlescribe handles Grenadiers and Engineers, and that should be fixed. They should both come with 2 stock weapons by default, for 1 point each (totaling 2 extra points) and there should be no option to take any more, or any less-- so I suppose this is an Engineer bug, because they're the profile which doesn't behave this way.

**Comment by GenericCola** [comment]
Are we not addressing the fact that in Battlescribe the Grenadier Weapons Team comes with 2 lasguns, but the Engineer Weapons Team only comes with 1 shotgun? I feel like the point I was making was entirely missed.

**Comment by alphalas** [comment]
@genericcola calm down man - we got a lot going on behind the scenes - it’ll be in the next release

**Comment by GenericCola** [comment]
I'm perfectly calm-- my comment was never responded to, so I was curious if this thread got overlooked because it had been closed. Reasonable question.

**Comment by alphalas** [comment]
Yes, it was - @crusherjoe closed it with a commit - means it will be in the next release. Pestering won’t get us to release any sooner.

**Comment by GenericCola** [comment]
In the history of my contributions, when have I ever pestered the team to try and get something released sooner? Come on now. I'm not trying to make it release any sooner. I don't care when it releases, all I care about is that the issue is being acknowledged. All I saw was the tag "closed-- by design," which was inaccurate, so I had no idea that a fix was being implemented. It seemed that the team read my original post, thought that I was saying that the number of weapons they come with was wrong, and should be changed, and said, "no, 2 weapons is right," and missed the fact that the Engineers only came with 1, and therefore closed the thread. Make sense?

Now that I know that the problem has been recognized and wasn't overlooked in the previous conversation, we can all move on.

**Comment by GenericCola** [comment]
I've just updated my data files with the version released on the Jan 26th (3 days ago) and this bug is still present. This is why I wanted to be sure that we were on the same page, because it seems that the error has still been overlooked or otherwise miscommunicated.

**Comment by alphalas** [comment]
If your version is v30; then you are most up to date. HOWEVER, in the datafile it self, the shotguns are set to min2 max2.

That means it’s not us, it’s a program bug.

Sorry nothing we can do about your annoyance other then tell you to tick up the shotgun entry on the weapon team.
![50358748-8c67-4eb3-8460-b56e31cf3d39](https://user-images.githubusercontent.com/15703066/35546649-21d3c2b6-0543-11e8-9c23-e00ca4b1e498.png)

**Comment by GenericCola** [comment]
It's not "my annoyance," I'm just doing my best to track possible bugs and bring them to your attention for you. You seem to be taking this much more personally than you should. Understand that I have no way of knowing what changes you implemented, I can only see that when I open Battlescribe the issue is persisting, and so it's worth clarifying.

I'm not familiar with how the code is handled in Battlescribe, it's just really weird that the Grenadier teams work fine, but the Engineers are being wonky.

**Comment by CrusherJoe** [comment]
So I did some digging and found a work-around to what we've seen before. I'll commit the fix momentarily, the fix will be in the next version of the datafile (v35).

**Comment by CrusherJoe** [comment]
![shotguns](https://user-images.githubusercontent.com/9998385/35571652-69fab162-0598-11e8-80e5-b433c4543b7f.png)

**Comment by CrusherJoe** [comment]
BTW @GenericCola I just wanted to say thank you for the issues you raise. It's nice having a user that cares enough to write lucid bug reports and test fixes. It's super cool and I appreciate what you do to help us make datafiles better.
