### ISSUE TITLE
Chaos - Daemons - Daemon Prince with wings profile not updating

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2276]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 1.09.99

**Platform:** Windows

**Dropbox:** No

**Description:** Hi guys, thanks for your awesome work! Couple of small things I have found.

1. Deamon prince when adding wings does not show the increase to movement
2. When making a list of multiple patrols its giving an invalid report due to too many HQs. I have 3 patrols with 2 hqs each and its saying there are 4 too many HQs.

Thanks again!

**Comment by GenWilhelm** [comment]
For point 2, make sure you're not nesting your forces. To add new detachments you need to select the Roster before you click Add. For four separate patrols, it should look like this:

![phaw patrol](https://user-images.githubusercontent.com/22036809/35129236-8bd03df0-fcb2-11e7-9bca-05e8834b76ae.png)
