### ISSUE TITLE
Chaos - Death Guard: DG issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2278]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** 

1) Plagueburst Crawler -> Plagueburst Mortar -> Lacking Plague Weapon (DG Codex)
2) Plague Marines -> Icon of Despair -> Should be 6" -1 Leadership instead of 3" (DG Codex)
3) Blades of Putrefaction -> Typo -> "(i.e. a plague sword or any weapon with the Pague Weapon ability)" Pague should be Plague
4) Blightlord Terminators -> PC Issue -> Champion showing up on the bottom of the squad instead of the top of the squad. No issue on Android.

**Comment by ilaunchbury** [comment]
1. Fixed in DG v29 released yesterday, cf. #2241 
2. Fixed in v30.
3. Fixed in DG v29 released yesterday.
4. Fixed in v30. I've changed the name to "Blightlord Champion" (to match the Codex) so that the standard alpha sorting displays him at the top instead of the bottom.
