### ISSUE TITLE
Orks: Squiggoth heavy weapon shouldn't be mandatory

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2285]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Ork Squiggoths are not required to take a heavy weapon yet the option to remove the weapon is no longer available after the last update, forcing you to pick on of the three weapons.

**Comment by ilaunchbury** [comment]
@tag8833, looks like this got broken again following your update for Gorin' Horns (which also gave the Squiggoth 2 copies of Gorin' Horns).
