### ISSUE TITLE
Imperium - Space Marines: Bike veteran sergeant has no Stormshield option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2292]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marines Company Veterans on bikes have error:
Veteran Biker Sergeant does not include the option to take a storm shield.

**Comment by ilaunchbury** [comment]
According to the Index, he can't take a storm shield. He is not a "Space Marine Veteran Biker", he is a "Veteran Biker Sergeant". Only the former have the option to take a storm shield, the Sergeant can only take option from the *Sergeant Equipment* list, which doesn't include a storm shield.
