### ISSUE TITLE
Imperium - Space Wolves: Wolf Guard Sky Leader issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2295]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Skyclaws Wolf Guard Sky Leader has an incorrect value for a Storm Shield (is 15, should be 5). Furthermore when choosing both 'replace bolt pistol' and 'replace chainsword' an error message appears.

**Comment by ilaunchbury** [comment]
The Wolf Guard Sky Leader is a Character, therefore his Storm shield costs 15pts as per Chapter Approved.

I'm not able to replicate the weapon selection issue. When choosing alternative weapons, did you unselect the defaults? If you did, what combination of weapons were you adding?
