### ISSUE TITLE
Access to Forgeworld - Index - Imperial Armour - Adeptus Astartes

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#2300]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** any plans to make Index - Imperial Armour - Adeptus Astartes available in the data file?
Note that as per recent FAQ, these units are also available to Deathwatch,Blood angels, Space Wolves etc.....

**Comment by alphalas** [comment]
See https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions
