### ISSUE TITLE
Chaos - Daemons: Warp Bolter should be CA cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2309]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Warp Bolter for daemon prince is only 3 pts, not 9. Chapter Approved 2017 corrected

**Comment by ilaunchbury** [comment]
Chapter Approved contained no changes for Chaos Daemons. 

Codex Daemons no longer allows a Warp Bolter on a "Daemon Prince of Chaos" so we refer to Index Chaos. The cost for the warp bolter for a "Daemon Prince of Chaos" is listed on p120, where it is 9 points. This value has never been changed in any FAQ, and as such, is the current value for that wargear.

Changes made to a Chaos Space Marine "Daemon Prince" do not apply to a "Daemon Prince of Chaos".
