### ISSUE TITLE
REFERENCE: Psychic Powers Standardization

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2316]
So since we've come to a consensus I think it's fair to edit and finalize:

- Psy Disiplines are to be a SSEG

- Each individual power is to have a max1 constraint on them

- There is to be a max X constraint placed on the link to the SSEG from the unit entries, where X is the maximum number of powers known by that Psyker.

**Comment by amis92** [comment]
It'd also help if every maintainer stated which approach their catalogues currently expose.

**Comment by GenWilhelm** [comment]
Tyranids & Genestealer Cults are currently implemented as optional.

My rationale was that these are not strictly part of roster building, as they are selected at the start of a game, and therefore may change within the same roster.

**Comment by alphalas** [comment]
Copy-pasta from the other thread: 
>As the head maintainer of the non-astartes non-cult mech imperial cats, I prefer the requirement to pick powers at time of list building; but that’s also because unlike GK, most other imperial factions are taking psykers for specific powers and not really worrying about psykic flexibility

**Comment by acebaur** [comment]
I'm against including them. They aren't apart of roster selection any more than decided what unit will ride in what transport. If someone can't remember what powers they want to choose then that is their fault and not our responsibility. It's a lot of work to include all that info and we have enough to deal with

**Comment by alphalas** [comment]
@acebauer it’s really not though when done correctly

**Comment by Kohato** [comment]
I'm for including defaults in everything - Psykers powers, warlord traits, c'tan powers, etc. Though my word means little in this discussion ... I write necrons :p

**Comment by amis92** [comment]
@Kohato right! Forgot to add the third option:

### Required with defaults

It would be essentially the same as required, except for units with one power, it'd be already selected?

**Comment by nairul** [comment]
> Isn't stricly legal (PP state, paraphrasing, "unit has X powers selected from", not "may select")

Can someone explain this further. What is illegal about _not_ nominating psychic powers in your list? 

> often tournaments (and friendly games obviously) allow selecting Warlord Traits and Psychic Powers before each game separaterly.

You can drop the "often." This is just a standard rule that all games abide by AFAIK. 

BRB pg. 178 states:
"If a psyker generates their powers before the battle, do so **immediately before either player starts to deploy their army**."

The ITC has modified this part -- they select psychic powers even earlier, before ANY dice are rolled. But they still select powers on a per-game basis. Not per-list.

**Comment by alphalas** [comment]
>>Isn't stricly legal (PP state, paraphrasing, "unit has X powers selected from", not "may select")

>Can someone explain this further. What is illegal about not nominating psychic powers in your list?

Because psykers are *ALMOST ALWAYS* described has having X amount of powers from Y discipline *KNOWN*, that implies they they *NEED* to have x amount of powers selected, RAW.

>>often tournaments (and friendly games obviously) allow selecting Warlord Traits and Psychic 
Powers before each game separaterly.

>You can drop the "often." This is just a standard rule that all games abide by AFAIK.

Also Incorrect, ive seen just as many events require same psy powers throughout as not, it's just the ITC (which is the most prominent standardized format) doesn't.

**Comment by GenWilhelm** [comment]
This still doesn't dispute the fact that the psyker section in the main rule book says that power selection happens immediately before deployment.

**Comment by alphalas** [comment]
Fair, however, counter-point: If we implement the pre-game stratagems as a function of BS, shouldn't that nullify this whole argument? You pick those strats before the game begins, and you pick psy powers before games begins.

**Comment by nairul** [comment]
> This still doesn't dispute the fact that the psyker section in the main rule book says that power selection happens immediately before deployment.

Yep. And @amis92 you might also add another "Con" to the Required list:

- Reinforces improper user understanding of rules.

Can't tell you how many players I've gone up against who were happy & surprised to hear they're able to "change" their psychic powers pre-deployment from the ones they've selected in Battlescribe list. Players think because Battlescribe requires it then it must be RAW.

**Comment by GenWilhelm** [comment]
>You pick those strats before the game begins, and you pick psy powers before games begins.

This really depends on where you draw the line at where the "battle" starts.

To me, it's pretty clear that powers are supposed to be selected at the same time as your warlord trait - after you've set up the battlefield, but before you determine deployment zones.

**Comment by OftKilted** [comment]
Then a “default” choice selection of something like:

“No Power Selected - Power Must Be Selected in Pre-game”

It both allows folks to “select a power in advance” and “allow folks to select a power immediately ‘pregame’” This encourages folks to understand the rules, while also allowing folks who want to preselect the option to do so.

**Comment by amis92** [comment]
@OftKilted How'd that work with multiple-powers units? I can't remember how default (constrained to max 1) works in a group of min 2+.

**Comment by GenWilhelm** [comment]
@amis92 it would have to not be max 1 on the "Selected in Pre-game" option, so you'd have 3x,2x,etc. of that if you wanted to generate that number of powers per game. I personally don't think it's necessary to go that far.

**Comment by Kohato** [comment]
After Discussion on gitter:

Proposed changes/standardization 

1) set psyker powers as shared groups with no min, but with max 0. Then set max to whatever is allowed by the unit using the discipline
2) set relics to max 0, increment by 1 with a warlord, increment by another 1 w/ -1CP entry or increment by another 2 with -3CP entry. The -1/-3 entries should be tied to rules that state remove x CP from total for this upgrade.
3) Character upgrades, taken from the most recent interpretation of "Before the battle" should remain in battlescribe as options, and those options are tied to Rule entries that state: remove x CP from total for this upgrade.

**Comment by amis92** [comment]
@Kohato I think 2. and 3. are more into #2318

**Comment by tekton** [comment]
Not sure how I feel about Max 0 for psychic powers, I king of get where people are coming from but that seems less than great overall.

**Comment by GenWilhelm** [comment]
Yeah, not sure what the Max 0 is for. It just needs to have the Max constraint set on each link.

**Comment by tekton** [comment]
I think the max 0 is due to the Strategems and relics that let you go over the constraint

**Comment by flakpanda** [comment]
Seems I am late to the discussion, but i maintain Space Marines, and I think all pre-game selections/CP expenditures should not be included in list building. Relics being the exception.

**Comment by OftKilted** [comment]
@amis92 that would depend on how it was coded I would assume. (It is set to 2x 1 Power? Is the power chosen from a list that can be duplicated? If it is minimum X powers ...)

**Comment by FarseerVeraenthis** [comment]
I like @oftkilted 's idea. I don't think there should be a set default, but you should have to make a decision between "choose when in pre-game sequence" and "pick particular powers while list building" this gives players the option of when to select them, without forcing them down one path or another. We can build constraints based around the choice of now/later made when list building.

**Comment by Crowbar90** [comment]
Blood Angels catalogue currently uses the approach outlined in the first post.

**Comment by amis92** [comment]
Yeah I feel @OftKilted's idea was a little lost in discussion.

*@OftKilted wrote:*
> Then a “default” choice selection of something like:
>
>“No Power Selected - Power Must Be Selected in Pre-game”
>
>It both allows folks to “select a power in advance” and “allow folks to select a power immediately ‘pregame’” This encourages folks to understand the rules, while also allowing folks who want to preselect the option to do so.

*@amis92 wrote:*
> @OftKilted How'd that work with multiple-powers units? I can't remember how default (constrained to max 1) works in a group of min 2+.

*@GenWilhelm wrote:*
> @amis92 it would have to not be max 1 on the "Selected in Pre-game" option, so you'd have 3x,2x,etc. of that if you wanted to generate that number of powers per game. I personally don't think it's necessary to go that far.

**I suggest polling. 👍 🎉 = +1, anything else = -1** Comments welcome.

---

I think it's a nice balance between required and optional but it would have to work *by default* ie no user action required to have a warning-less entry.

**Comment by alphalas** [comment]
While that’s a nice idea, I think it adds too much in the way of completely unnecessary constraints and modifiers where they’re not really needed

**Comment by amis92** [comment]
Good point. I've not touched catalogues for so long I start to loose a feeling of how much work goes into them as-is ;D
