### ISSUE TITLE
Before- and mid- game selections

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2318]
There is a need for selections which don't happen during list building but nonetheless are very important part of a list in-game.

From gitter chat:

---
*@alphalas 14:17*
Now I have a question – to make everybody’s lives easier, do we want to make a no force org section for stratagems – the only one that really needs to be in it is the relic stratagem, but since everybody has one of those we can always just put it in GST and have everybody link to it. That way people can set their cats to unlock relics if instance of warlord in roster instead of instance of warlord in detachment

---
*@Kohato 14:19*
Also not a bad idea

---
*@GenWilhelm 14:19*
that would set the precedent for including any "before the battle" stratagems

---
*@alphalas 14:22*
See, it does but it doesn’t; case in point BA: I totally build a list with the fact I’m going to take both angel’s wing and the standard of sacrifice in it; but I don’t build a list planning to Forlorn Fury every single game

---
*@GenWilhelm 14:23*
forlorn fury is done during the battle, not before it

---
*@alphalas 14:24*
They’re both before the game stratagems; but if I have 2 relics on my list it’d be nice for there to be a visual reminder for myself and my opponent that I have 1 (or 3) less CPs then normal

---
*@GenWilhelm 14:24*
i meant stuff like Chapter Master, or the special daemonic icons

---
*@alphalas 14:24*
No it’s before the first game 10
Turn*

---
*@GenWilhelm 14:24*
at the start of BR1, yeah. that's not "before the battle"

---
*@alphalas 14:26*
Ok no I get what your saying now

---
*@CloverFox 14:26*
maybe add the list of powers, but default to a "pick before the battle" option so it doesnt create errors in validation, (which also adds all powers to the rules section for completions sake maybe?)

---
*@alphalas 14:27*
So Death Visions of Sanguinus would be another thing that should technically be on that list?

---
*@GenWilhelm 14:28*
yeah, i would say so

---
*@alphalas 14:28*
Ok that seems reasonable imo

---
Please discuss.

**Comment by alphalas** [comment]
As I stated in the Gitter, I think it'd be a good idea to track before game Strats, so you and your opponent can have a clear reference of how many CPs you have before you're setting your armies up on the table. Tracking midge Strats is kinda useless if you have your list printed out so I don't think we should bother with that.

**Comment by GenWilhelm** [comment]
A agree with @alphalas, we're trying to build as complete of an army list as possible, not reprint the codex. 😄 

Relic stratagems would allow us to do complete validation on relics, but as I said before it sets a precedent, so we'd have to extend it to any stratagems that are "before the battle", "when mustering your army", and any other similar wordings.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/35360517-476452c2-015e-11e8-96a0-d0bc67322052.png)
SO ahead of you for months :P

**Comment by WindstormSCR** [comment]
Custodes are being implemented with an improvement of @Thairne 's relic validation to prevent a 'free relic per force' and being dependent on warlord selection for the free relic instead:

![507fe85ff3](https://user-images.githubusercontent.com/29389845/35459915-0e545308-02b0-11e8-99e7-e8005115faf5.png)
