### ISSUE TITLE
Necrons: Wrong AP for Cutting Beam

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2323]
**File:** Necrons.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** Yes

**Description:** Canoptek Arcanthrite Cutting Beam weapon profile is displaying AP - when it should be AP - 4

**Comment by Kohato** [comment]
That'll happen, for whatever reason, the version of BS I did 8th necrons on had a horrible tendency to just blank out values if I tabbed through.  I'll fix it when I get home tonight.
