### ISSUE TITLE
Imperium - Space Marines: Lieutenant missing weapon?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2324]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** lieutenants are missing 30" bolt rifle on wargear and stats

**Comment by ilaunchbury** [comment]
What wargear are you referring to? There is no weapon that a standard Lieutenant can take which has a range of 30".

Primaris Lieutenants can take a stalker bolt rifle with a 36" range, and this is available in the data.

**Comment by killer00z** [comment]
In Dark Imperium Lieutenant is equiped with bolft rifle 30" same as Intercessors squad. mayby that had change but i dont have new codex to check it. In battlescribe i also dont see any stalker bolt rifle 36" 
![l](https://user-images.githubusercontent.com/35800963/35385613-c6b212a0-01c0-11e8-8d71-b326252decd4.PNG)

**Comment by skonk** [comment]
Thats a Lieutenant, not a Primaris Lieutenant is it not?

**Comment by killer00z** [comment]
oooh we have primaris and non primaris Lieutenant now -_-', i think you we cant close this non bug thing
