### ISSUE TITLE
Imperium - Dark Angels: Scout Sergeant validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2325]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** The options for Scout Squad, Scout Sergeant has an issue with Armament 1.

If I choose any options at the top (Astartes Shotgun, Boltgun, Combat Knife, Sniper Rifle) and leave Sergeant Equipment on "(None)", all I get the error: Scout Sergeant has 1 too many selections from Armament 1 (maximum 1)

If I leave all of those options un-ticked and choose something from the Sergeant Equipment list then I get two error messages:  Scout Sergeant has 1 too many selections from Armament 1 (maximum 1)

and: Scout Sergeant has 1 too many selections from Armament 2 (maximum 1)

At this point, adding something from the top options does not change the error messages.

What this means is that, if I select any weapons at all from Armament 1, then I will have at least one error message.

**Comment by Thairne** [comment]
Fething Shared.

**Comment by ilaunchbury** [comment]
I've had to rework him a bit, but all the validation should be good now.
