### ISSUE TITLE
Chaos - Renegades & Heretics: Points descrepancies

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2327]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Command squad, the point value should be 24pts (4x 6pts per model) and somehow it has 3pts too much for nothing.
- [x] Griffon had a pts increase from 70 to 77pts (base cost) according to chapter approved 2017
- [x] ~~Hydra had a pts decrease from 125 to 100pts (base cost) according to chapter approved 2017~~
- [x] ~~Malcador points for weapons are incorrect, 20pts per lascannon instead of 25, 12pts per autocannon instead of 15, respectively, pair of lascannon should be 40pts and pair of autocannon should be 24pts, according to index imperial armour forces of the astra militarum and chapter approved 2017~~
- [x] ~~Malcador Defender should be 200 base points + 40pts (5x8pts) of heavy bolter, so 240pts base price. Weapon are the same as the malcador heavy tank, see above according to index imperial armour forces of the astra militarum and chapter approved 2017~~

Thank you for your help and have a nice day. 
You may contact me at ~~REMOVED~~ if you need.

**Comment by ilaunchbury** [comment]
- Hydra cost was fixed in #2180, although I can't find it in CA. The last update was in Codex Astra Militarum.
- Malcador weapons were fixed in #2180 
- Fixed in #2180, although a Defender has 7 Heavy Bolters and a Demolisher cannon as its default equipment and should be 296pts before upgrades.
