### ISSUE TITLE
Imperium - Dark Angels: Assault Squad validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2328]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Assault squad - A warning is displayed whenever a 10 marine squad takes 2 eviscerators and 2 flamers. Such a loadout should be legal.

**Comment by ilaunchbury** [comment]
I can only get this to error if I give the Sergeant an Eviscerator. Giving two standard Marines Eviscerators is fine.
