### ISSUE TITLE
Deathwatch Points error - Hellblasters

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#2332]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Deathwatch Hellblasters Point Cost error

Another point change that has been put in the Space Marine list but not copied across to Deathwatch. Hellblaster weapons options have been recosted - showing the wrong points in the unit options. Should be 15pts for incinerators and 17pts for heavy and assault variants (like in Space Marine list)

**Comment by FarseerVeraenthis** [comment]
There is definitely something strange happening. I'm sure I made the update but I couldn't have tested it very well because it's definitely broken...

**Comment by MasterCrafty** [comment]
Thx Siimon
