### ISSUE TITLE
Chaos - Thousand Sons: Predator profile is incomplete

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2337]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Thousand Sons Predator has incorrect or incomplete stat line. The wound table is correct. But it's missing the the stat line itself. All values missing, and the only value on it is an incorrect BS of 4.

**Comment by ilaunchbury** [comment]
I'll fix this when the Codex comes out next week.
