### ISSUE TITLE
Points cost for Space Wolves Predator incorrect

### ISSUE THREAD

**Issue by DuncanSpence** [BSData/wh40k#2346]
**File/Catalogue:** Warhammer 40,000 1.1.15

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Space Wolves Predator points values shown as 90, should be 102

**Comment by ilaunchbury** [comment]
Predator cost is 90pts as per Codex Space Marines, which supersedes the Index costs.
