### ISSUE TITLE
Imperium - Adeptus Mechanicus: Knights missing from catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2347]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Lord of war option is missing when trying to create:
 Adeptus Mechanicus roster
Detachment is super heavy auxcillary detachment
When you are in this roster there is no option to choose Lord of War

**Comment by ilaunchbury** [comment]
Knights are in the Imperial Knights catalogue. If you want to use them in your AdMech army, create a multi-faction detachment.
