### ISSUE TITLE
Tau KV128 Stormsurge Stabilising Anchors special rule incorrect.

### ISSUE THREAD

**Issue by BlackLightUK** [BSData/wh40k#2354]
**File/Catalogue:** T'au Empire.cat

**BattleScribe version:** 2.01.09

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Hi there ! 

After buying a KV128 Stormsurge, I've noticed an inconsistency between the Battlescribe data and the enclosed assembly instructions datasheet. 

The Stabilising Anchors rule reads as follows. 

**Stabilising Anchors:** In your Shooting phase, in addition to firing normally, a Stormsurge can begin deploying it's anchors; from then on the Stormsurge cannot move under any circumstances or make Stomp attacks. In the Shooting phase of your next turn, and in each subsequent Shooting phase, a Stormsurge with it's anchors deployed can fire twice. Make the second shooting attack directly after the first has been resolved. The Stormsurge can retract its anchors at the beginning of any of your Movement phases, and can then move, shoot, and make Stomp attacks normally. 

I hope this helps and keep up the good work, folks :)

**Comment by amis92** [comment]
I'm sorry, but these rules are old, they are 7th edition (there are no Stomp attacks in 8th!).

BasttleScribe has correct text, sourced from Index: Xenos 2.
