### ISSUE TITLE
Imperium - Blood Angels: Relic issue?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2355]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Comes up error when selecting a Relic.Says maximum 0.

**Comment by Mad-Spy** [comment]
I'm not able to replicate this. Can you provide some information on the problem? Which unit are you trying to add a relic to? Which relic?

**Comment by Crowbar90** [comment]
Did you select a Warlord?

**Comment by Mad-Spy** [comment]
@Crowbar90, I couldn't find a way to add a relic without selecting one when I tried to replicate this.

**Comment by Crowbar90** [comment]
The Codex specifically says you must have a BLOOD ANGELS Warlord in order to use relics, so they are not allowed unless you have one.

**Comment by alphalas** [comment]
Except if you use the relic strat, which you have access too as soon as you have a BA detachment
