### ISSUE TITLE
Codex Chaos Daemons - Daemon Prince - Warpbolter should not be available

### ISSUE THREAD

**Issue by amareisdk** [BSData/wh40k#2356]
**File/Catalogue:** Chaos - Daemons v26

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Daemon Prince of Chaos should not have the option for a Warpbolter. This is not in the codex, even after the recent FAQ.

**Comment by Mad-Spy** [comment]
Warp bolter is an Index option for the Daemon Prince of Chaos and is allowed by the Designer's Commentary flowchart.

**Comment by amareisdk** [comment]
If that is case (which makes no sense as there is plenty of entries for the
prince to replace the index option), then it should be 3 pts as is updated
in chapter approved.

Den 29. jan. 2018 10.27 skrev "Iain Launchbury" <notifications@github.com>:

Warp bolter is an Index option for the Daemon Prince of Chaos and is
allowed by the Designer's Commentary flowchart.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/2356#issuecomment-361186795>, or mute
the thread

**Comment by Mad-Spy** [comment]
I'm not sure what you mean about "plenty of entries for the prince to replace the Index option".

The Designer's Commentary clearly states that if there is an Index wargear option which is not in the Codex, you can use the Index details for it.

Regarding the cost, the cost for the Warp Bolter for a "Daemon Prince of Chaos" has never been updated in Chapter Approved or anywhere else. There were no changes at all for Chaos Daemons in Chapter Approved.
It sounds like you are assuming that Chaos Space Marines "Daemon Prince" and a Chaos Daemons "Daemon Prince of Chaos" are the same thing, which they are not. They have separate datasheets, even in the Index.

**Comment by amareisdk** [comment]
So what you're saying is that any wargear option from the index is always
available regardless of what is printed in the codex?

But it's funny though that the warp bolter only has one profile, even
though it is two different pieces of equipment right? It's almost as if
it's only one piece of wargear available for two units with one pts cost,
like all wargear available to several units. And yes, warp bolter is 3 pts.
Not 9.

We already had this discussion with the rubrics, and I was also right back
then. I argued what was then released by GW.

Den 29. jan. 2018 11.35 skrev "Iain Launchbury" <notifications@github.com>:

**Comment by Mad-Spy** [comment]
Not exactly,, I am saying (as per the Designer's Commentary, see #1414) that wargear options that are not in the Codex can still be taken, using their Index profile.

The cost for a Warp Bolter for a "Daemon Prince of Chaos" is listed on p120 of Index: Chaos. That cost has never been updated in an FAQ or in Chapter Approved. Different factions can and do have different costs for wargear.

I am not saying you are wrong, I am saying that the current rules do not permit a Daemon Prince of Chaos to take a Warp Bolter for 3 points.

I suggest you submit your query to the FAQ email address (40kfaq@gwplc.com). Hopefully they will address the discrepancy, as they did with Rubrics previously.

**Comment by amareisdk** [comment]
Yeah, I see what you mean. I read the rules again and there are holes in
the flowchart and the description. Like, what if the wargear has the same
name as in another codex?
Could they have different pts cost?
You say so, but I can't find any proof.
Even the predator is priced the same for CSM and SM.

I sent them an email. Hopefully they'll add it, at least in the March faq.
It makes no sense to have two pts cost. The Daemon Prince should either not
have it or have it at 3 pts. All other pts cost is the same.

Den 29. jan. 2018 12.34 skrev "Iain Launchbury" <notifications@github.com>:
