### ISSUE TITLE
Tyranids: Trygon PL cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2361]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** In the Tyranids section of Battlescribe, Trygons are listed at power level 8. In the Tyranids codex they are listed at power level 9. I have not found a change to the codex's ruling in the current FAQ, and I believe it my be a typo in the program. Thank you.

**Comment by GenWilhelm** [comment]
This was fixed in e0804c5d60baa0f4f24f994d545c847805c884e6 (Tyranids v29).

Please update your data.
