### ISSUE TITLE
Thousands Sons Codex work

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#2369]
Placeholder to cover 1KSons Codex work

**Comment by skonk** [comment]
Magnus is still 415 points, should be 445.

**Comment by GenWilhelm** [comment]
- [ ] Terminator Sorcerer should have the option to take a Familiar.
 - [ ] Rubric w/ Soulreaper is missing constraints on its Soulreaper Cannon.
 - [ ] Tzaangor Enlightened shouldn't be able to mix weapons.
 - [ ] Spawn's "Mutated Beyond Reason" ability has formatting issues.

**Comment by skonk** [comment]
- [ ] Ahriman is showing the old text for his Lord of the Thousand Sons rule

**Comment by GenWilhelm** [comment]
- [ ] Tzaangor Shaman is missing max 1 for Warlord.
 - [ ] Tzaangor Shaman's Sorcerous Elixir should be "...first **failed** Psychic test...".
 - [ ] Mutalith Vortex Beast should have the "Aura of Dark Glory" ability.
 - [ ] Chaos Predator should have the "Smoke Launchers" ability.
 - [ ] Forgefiend should be 9 PL.
 - [ ] Forgefiend should have default weapon selections.
 
Typos:
 - [ ] Maulerfiend, Lasher tendrils - Type: "Mlee"
 - [ ] Helbrute plasma cannon - Abilities: "Hellbrute"
 - [ ] Magnus, Unearthly Power - Abilities: "atttempts"
 - [ ] Boon of Mutation, 12 Daemonhood - Effect: "characer"
 - [ ] Boon of Change - Details: "visble"
 - [ ] Mutalith Vortex Beast, Unstable Energies - Abilities: "remaing"
 - [ ] Mutalith Vortex Beast, 2 Chaotic Infusion - Abilities: "yor"
 - [ ] Coruscator - Abilities: "Cosruscator"
 - [ ] 2. Undying Form - Abilities: "minmum"
