### ISSUE TITLE
Imperium - Space Wolves: Warlord Traits with nested detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2374]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** I created a battalion space wolves list, with ad mach and officio assassinorum added to the space wolves battalion, and a separate super heavy aux of imperial knights. The list was giving a roster error, stating that each of my HQ's needed a warlord trait, even when only one HQ was identified as the warlord. I made a regular space wolves battalion and did not get the error, and upon reproducing the list with the error, I received the same error

**Comment by CrusherJoe** [comment]
Though I didn't reference it, the commit I just made (https://github.com/BSData/wh40k/commit/a52a8cbcceca3753dc1c7c25497a89de98bca0ec) should address this one.
