### ISSUE TITLE
Redemptor - Icarus Rocket Pod change

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#2379]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Since the Jan 14th FAQ, The ICARUS ROCKET POD is no longer included in standard wargear. it is an option. The Data File includes it as a mandatory 6pt piece of wargear. Please could you change in SM and other (Deathwatch etc) detachments. Thanks

**Comment by amis92** [comment]
Hey @CrusherJoe @acebaur how's progress?

**Comment by acebaur** [comment]
DW cat is updated with this, waiting on the branch to be merged.
