### ISSUE TITLE
Imperium - Space Marines: Hurricane bolter cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2381]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Centurion devistators are listed as having hurricane bolters as wargear for 10 points. The 8th edition space Marines codex lists hurricane bolters at 4 points. Unless there has been a change I hadn't seen.

**Comment by Mad-Spy** [comment]
The cost for Hurricane bolters was changed in Chapter Approved.
