### ISSUE TITLE
IMPERIUM - BLOOD ANGELS : Relic Issue

### ISSUE THREAD

**Issue by ZULUST3** [BSData/wh40k#2384]
**File/Catalogue:** Imperium - Blood Angels V36

**BattleScribe version:** 2.01.12

**Platform:** iOS

**Dropbox:** No

**Description:** as reported similar in #2355 the error sign claiming that:
Roster has 1 too many selections from Relics of Baal (maximum 0) appears as soon as you add any second blood angels detachment to already existing one.
Conditions:
All detachments are selected from Imperium - Blood Angels v36
The warlord is Blood Angel captain with thunder hammer 
The relic is Hammer of Baal

Notes:
If there is only one detachment - no problems occur.
Using No Force Org Slot to add one or two additional relics has NO impact upon the error sign, nor has it upon the “(maximum 0)” notification

**Comment by GenWilhelm** [comment]
This was fixed in 11adc2e188b1b53622905e5720d12e0626cdb950 (Blood Angels v37).

It'll be available with the next release in a day or so.
