### ISSUE TITLE
Imperium - FW Adeptus Astartes - Relic Leviathan Dreadnought  Wargear Options

### ISSUE THREAD

**Issue by timbrown81** [BSData/wh40k#2385]
**File/Catalogue:** 

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Imperium - FW Adeptus Astartes - Relic Leviathan Dreadnought improperly handles wargear selection.  You may replace one or both Siege Claw + Meltagun with another weapon. Currently if you add one of the weapon options it does not remove the Seige Claw + Meltagun.

**Comment by alphalas** [comment]
It works just fine - just remove a fist manually. Not everything is automagic.

**Comment by WindstormSCR** [comment]
As an explanation of why this is not automatic: the program doesn't make any distinction between different uses of the same 'item'. in this case the dread fist is a single 'item' that is linked to twice, one for each arm. trying to automatically remove that will remove one of the two at random. 

Using other methods to make it automatic also have difficulties that are not readily apparent to the end user.

**Comment by Mad-Spy** [comment]
@alphalas, @WindstormSCR, I've reimplemented the Lev Dread to match the FWHA implementation so the weapon swaps function as expected.
