### ISSUE TITLE
Idea: Roll FW indexes into respective factions

### ISSUE THREAD

**Issue by zuriel42** [BSData/wh40k#2387]
**File/Catalogue:** Warhammer 40K -  All FW Indexes

Unless I missed an option somewhere, it is currently not possible to build a detachment with mixed FW Index and standard Index/Codex units.  Ex: A SM spearhead detachment with Vindicators, Predators, etc from the codex with a Damocles command rhino from the FW index as HQ.  The 7th edition data files had this ability by including FW units in the main faction data file, hidden until an "Include FW models" option was selected.  
Having this as part of the 8th edition data files would make list building with FW models a much more viable option when using Battlescribe.

**Comment by skonk** [comment]
Battlescribe allows you to nest detachments inside each other, with each being of a different faction/catalogue ; while validating the list as if it was a single detachment.

![image](https://user-images.githubusercontent.com/621514/35738959-22e64632-0828-11e8-8d1f-bee4b70aa9f6.png)

**Comment by zuriel42** [comment]
And that would be the option I missed.  Thanks for clearing that up.
