### ISSUE TITLE
Ork Warbikers Missing 1/2 Dakkaguns

### ISSUE THREAD

**Issue by capitaladot** [BSData/wh40k#2389]
**File/Catalogue:** Orks v12 @tag8833

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Ork Warbikers Missing 1/2 Dakkaguns

**Comment by capitaladot** [comment]
Submitted for my SO, an unlikely Ork player.

**Comment by Mad-Spy** [comment]
Not sure what the problem is? They show as having 2 dakkaguns per model.

![image](https://user-images.githubusercontent.com/29306451/35778774-e2681632-09ba-11e8-879b-6921850cab65.png)

**Comment by toadchild** [comment]
The problem is that on the rendered list, unless you switch the output from minimal to full, there is no indication that a model has more than one dakkagun.  This is a greater battlescribe UI problem, not an issue with this particular unit entry.

**Comment by alphalas** [comment]
@mad-spy it’s one of the many reasons that I very much dislike having units that are all collective’d together

**Comment by Mad-Spy** [comment]
As per previous comments, this is a bug in Battlescribe, not an issue with the data. Please raise a ticket with the BS devs.
