### ISSUE TITLE
Imperium - Astra Militarum: Warlord Trait validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2390]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** When I select multiple Astra Militarium Company Commanders, I am asked to select warlord traits for all Company Commanders, even after a Warlord is chosen

When I select multiple Astra Militarium Platoon Commanders, I am asked to select warlord traits for all platoon commanders, even after a Warlord is chosen

**Comment by CrusherJoe** [comment]
I have tried to duplicate this issue but cannot. What version of the datafile (not BattleScribe) are you using?
