### ISSUE TITLE
Chaos - Daemons: Seeker collective issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2391]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** There appears to be an error with the seekers data that causes them to become collective and change multiple unit sizes when only changing one within the same detachment. I dug into the data and found 2 sets of seeker data and fixed the duplicate on my end.

BattleScribe v2.01.09.99

**Comment by Mad-Spy** [comment]
I can't replicate this in Daemons v29. Try updating your data.
