### ISSUE TITLE
Reinforcement Points

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k#2393]
Any chance you could find a way to make the Reinforcement Points appear in an army listing total points?

**Comment by skonk** [comment]
I would suggest that there is already a simple way to do this; if you have pre-planned which units you will be summoning (which is what I generally do).

Add a new Detachment to your list and select the "Unbound Army" as the Detachment type. This will let you add any units that exist in the selected data file and battlescribe will not try to enforce any detachment validation on it.

Then you can select the units you want to summon and give them the wargear you want them to have and the points will be added to your total.
