### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Points issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2396]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** 

- [x] Defensive Heavy Stunners are listed as 4 pts and should be 0 pts
- [x] Twin Heavy Las gives the wrong point value when mounted to a Mars Pattern Leman Russ. It's reads 25 but should read 40.
- [x] Autocannon on when mounted to a Storm Chimera lists it at 15 pts but should read 12.

**Comment by CrusherJoe** [comment]
Not sure what you mean by "Defensive Heavy Stunners" -- I'm assuming you mean "Heavy Stubbers" but I can't find a reference to "Defensive Heavy Stubbers" in Index: FotAM. JIf you could tell me the page/unit/whatever it's referenced on I'd be happy to take a look at it.

**Comment by alphalas** [comment]
@crusherjoe avenger fighter has defensive HS; it’s in the regular guard points of I:FotAM
