### ISSUE TITLE
Imperium - Astra Militarum: Hellstrike missile points issue.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2397]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Hell strike missiles read as 30 points on a Valk  they should read either 20 or 40 depending on how on interprets the number of missiles the Valk has

**Comment by alphalas** [comment]
Correct; somehow the FW Hellstrike CA points got applied to Codex Hellstrikes. Will be fixed to 20.

**Comment by ImperialNavyPilot** [comment]
Imperial Armour states that a hellstrike missile is 20 pts, yet flyers such as the Thunderbolt are still priced at 120 pts for 4 hellstrikes.

**Comment by GenWilhelm** [comment]
Chapter Approved changed the point costs of Hellstrike Missiles to 30pts in the Forge World section. So any unit from Imperial Armour has to pay this price instead of the old one.
