### ISSUE TITLE
Thousand Sons - Tzaangor Icon of Flame

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#2403]
**File/Catalogue:** Codex Thousand Sons v31

**BattleScribe version:** 2.01.12

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:**
In the Codex, Tzaangors no longer have the ability to include an Icon of Flame.  However, this option is still present in BattleScribe.

**Comment by Mad-Spy** [comment]
Index wargear is still allowed if not in a Codex, as per the Designer's Commentary.
