### ISSUE TITLE
Chaos - Chaos Space Marines - Cultist PL increment not working

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2406]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Cultists listing at 6 PL for 10 models, instead of 3. No change occurs when going up by 10 to a unit total of 20. It stays as 6PL base cost, then 6PL for 20 models as well.

**Comment by Mad-Spy** [comment]
Seems to work fine in CSM v44 for me? Can you provide screenshots and any other details?
