### ISSUE TITLE
Aeldari - Craftwords: Autarch Star Glaive should be optional.

### ISSUE THREAD

**Issue by Amdraz** [BSData/wh40k#2409]
**File/Catalogue** Warhammer 40,000 v1.1.18/Aeldari Craftworlds v37

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** The Autarch is listed with the Star Glaive (+6pts) as an automatic choice. However the Index still allows them to be equipped with just a power sword (or replacement Relic) and no Star Glaive. Can this be changed?

**Comment by WindstormSCR** [comment]
It is not optional, as it is fixed wargear on the Autarch Datasheet that is never replaced by index wargear options. the only section from the index that is valid is the wargear options segment,
