### ISSUE TITLE
Death Guard Rhino

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k#2410]
**File/Catalogue:** Death Guard v33

**Platform:** Android

**Dropbox:** No

**Description:** Rhinos should be able to take 2 combi-bolters.
The datasheet reads it's equipped with a combi bolter and may take one item from the combi weapons list. Doesn't say that this replaces the existing combi-bolters.

**Comment by Mad-Spy** [comment]
A Rhino *can* take 2 combi-bolters in DG v33?

![image](https://user-images.githubusercontent.com/29306451/35778688-a94afdca-09b9-11e8-836f-06cd52ab41af.png)

**Comment by Mad-Spy** [comment]
I see now, you mean you get a validation error if you add two combi-bolters.
