### ISSUE TITLE
Imperium - Astra Militarum: Pask unable to select warlord trait

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2411]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** If you choose a Knight Commander Pask as your warlord, the list of warlord traits dont appear to select, as appear if you choose another other character as your warlord.

**Comment by alphalas** [comment]
Pask is Cadian, which means he has to have the Cadian warlord treat.
