### ISSUE TITLE
Astra Militarum Meltagun Points

### ISSUE THREAD

**Issue by Orkpopper** [BSData/wh40k#2414]
**File/Catalogue:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows 10

**Dropbox:** No

**Description:** Command Squad and Veterans Squad: Meltagun Special Weapon option is 17 points, should be 12 points.

**Comment by alphalas** [comment]
Chapter approved changed the cost for models with better then 4+ bs
