### ISSUE TITLE
Imperium - Dark Angels - Bike as equipment

### ISSUE THREAD

**Issue by magik1980** [BSData/wh40k#2418]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes

**Description:** Librarians, Chaplains and Techmarine should't have access to bikes

**Comment by WindstormSCR** [comment]
the last page of this document is what you are missing: https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/warhammer_40000_designers_commentary_en-1.pdf
