### ISSUE TITLE
Chaos - Thousand Sons: Screamers missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2424]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** *missing fast attack screamers*
“This unit contains 3 Screamers. It can include up to 3 additional Screamers (Power Rating +4) or up to 6 additional Screamers (Power Rating +8). Each model attacks with a lamprey bite.
Lamprey bite   Daemonic Ritual
Ephemeral Daemons
Slashing Attack
 
Chaos, Tzeentch, Daemon
Beast, Fly, Screamers”

Excerpt From
Codex: Thousand Sons
Games Workshop Ltd
https://itunes.apple.com/us/book/codex-chaos-thousand-sons-enhanced-edition/id1335536612?mt=11
This material may be protected by copyright.

**Comment by Mad-Spy** [comment]
Daemons are no longer being included in Chaos Space Marines catalogues as including them causes a detachment to no longer benefit from Legion Traits and coding this is prohibitively complicated.

If you want to include Daemons in your Thousand Sons army, add a detachment of Daemons.
