### ISSUE TITLE
Tousand sons - Exalted Sorcerer with no disk has disk attack profile

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#2431]
Hello,

Exalted sorcerer with no disk is showing a weapon profile for "Blades on Disc of Tzeentch" 

Thanks

**Comment by GenWilhelm** [comment]
This was fixed in e5208256825da3b414240fb8037b80663fb571f0 (Thousand Sons v32).

It'll be out with the next release in a day or two.
