### ISSUE TITLE
Chaos - Death Guard: Death Shroud points cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2443]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Looking through faqs  iv noticed the death shroud havent dropped to the 50pts yet...
Cheers

**Comment by skonk** [comment]
The points are inline with the changes made in Chapter Approved:
35 base + 17 for the manreaper + 8 for the gauntlet = 60 points.

![image](https://user-images.githubusercontent.com/621514/36004056-99da797a-0d28-11e8-8962-992991cb6911.png)
![image](https://user-images.githubusercontent.com/621514/36004084-c511caa8-0d28-11e8-9c44-1db88a0eab23.png)
![image](https://user-images.githubusercontent.com/621514/36004091-d00fa038-0d28-11e8-90e6-262f474b9832.png)
