### ISSUE TITLE
Some death korps options are marked "collective" incorrectly.

### ISSUE THREAD

**Issue by Cultiststeve** [BSData/wh40k#2452]
**File/Catalogue:** FW Death Korps of Krieg v35

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
In the "Grenadier Storm Squad", and in the "Infantry Squad", the standard unit upgrade is marked as "Collective". This causes a bug where you have multiple instances of a squad in a roster, and modifying the number of guardsmen down in one squad also affects all the other squads in the roster.

**Comment by alphalas** [comment]
It’s not the collective itself; it’s a shared constraint. @crusherjoe will fix it

**Comment by Cultiststeve** [comment]
Okay, I am unfamiliar with exactly how this file is structured. Unchecking collective appeared to fix it for me.

**Comment by CrusherJoe** [comment]
This was indeed a weird one. Thanks for finding and reporting!

**Comment by GenericCola** [comment]
This has been happening to me all the damn time, and I couldn't figure out why, lol. I thought it was something I was doing, I never realized it was a bug.
