### ISSUE TITLE
Imperium - Death Korps of Krieg - Deathrider Command Squadron

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2457]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The Death Korps Death Rider Command Squadron is able to take a Relic in Battlescribe for some reason, but it is not a Character unit, and therefore should not be able to.

**Comment by CrusherJoe** [comment]
Well there's a classic "Oops" if ever there was one. Hang on, I'll fix it.
