### ISSUE TITLE
Helbrute heavy flamer/combi-bolter options

### ISSUE THREAD

**Issue by StolidTen129** [BSData/wh40k#2467]
**File/Catalogue:** Chaos Space marines

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** ?

**Description:** there is no Helbrute fist weapons such as heavy flamer or combi-bolter.

**Comment by StolidTen129** [comment]
please fix

**Comment by Mad-Spy** [comment]
Select the fist after adding the Helbrute to select the inbuilt ranged weapon.
