### ISSUE TITLE
Chaos - Thousand Sons: Units missing? No relics?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2469]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** I'm not seeing half of the units in the army as options. I'm also missing most of the relics.

**Comment by Mad-Spy** [comment]
What version of the file are you using? The current released version of Thousand Sons is v32. If you do not have this version, please update your data.

What units do you believe are missing? Daemons are no longer being included in Heretic Astartes catalogues. Please see #2455 for an explanation.

Which relics are missing? Relics will only appear if you select appropriate wargear and/or unit options and have a Warlord selected in your TS detachment.

**Comment by Mad-Spy** [comment]
Without further information, there is nothing more to be done on this.
