### ISSUE TITLE
Grey Knight Warlord Trait - Lore Master

### ISSUE THREAD

**Issue by mstathers** [BSData/wh40k#2470]
**File/Catalogue:** Imperium - Grey Knights v16

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Lore Master (know an addition psychic power from the santic discipline), does not actually change the number of powers known allowed for the selected character.
Eg. If taking Grand Master Voldus as your warlord with this trait (not an optional trait as he is a named character), he should be able to know 4 powers. BS reports an error though if you go over 3 (base without the trait).

**Comment by tekton** [comment]
This is going to sit a while to be honest, still need to change the entire warlord selection based off some central aspects. I opted not to change it until then at any rate.
