### ISSUE TITLE
Zhufor missing for World Eaters

### ISSUE THREAD

**Issue by MountyChris** [BSData/wh40k#2471]
Zhufor had been given the world eaters faction in the IA Chaos index FAQ, but is currently not showing up when Word Eaters Legion is selected.
(he shows up for renegades, which is correct, but should be world eaters too)

**Comment by alphalas** [comment]
Do you have a child detachment of the FW file in your list? He’s a FW character so he’s in there.

**Comment by MountyChris** [comment]
The HQ choices got moved out of the FW catalogue a while back.

**Comment by skonk** [comment]
He should show up when the Legion is set to World Eaters; but I can confirm he currently isn't doing that (only shows up when Renegade Legion is selected).

**Comment by Mad-Spy** [comment]
Yes, totally missed this. He didn't even have the World Eaters keyword. All sorted now, so it will be in the next release.
