### ISSUE TITLE
Imperium - Death Korps of Krieg - Salamander Scout Tank

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2473]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The Salamander Scout Tank is listed with no weapons, and no weapon options, in Battlescribe. It is listed at 55 points (which is just the cost of the chassis). The vehicle should be equipped with a mandatory Autocannon (12 points) and Heavy Bolter (8 points) for a total of 75 points, with the option of an additional pintle-mounted Storm Bolter (2 points) or Heavy Stubber (4 points).

**Comment by Mikle103** [comment]
What version of Astra Militarum are you using v102 is current and works fine
78 points,

**Comment by GenericCola** [comment]
This wasn't an issue with Astra Militarum, it was an issue with DKoK. I don't know if they pull from the same data file, but I'll check again when I return home on Monday.
