### ISSUE TITLE
Chaos Daemons Lord of Change psychic powers

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#2478]
**File/Catalogue:** Chaos Daemons v30

**BattleScribe version:** 2.01.09

**Platform:** Mac

**Dropbox:** Yes

**Description:**
The Lord of change's psyker description says it knows Smite and all powers from the Tzeentch discipline, however the validator says it only should know 3 powers.

**Comment by skonk** [comment]
![image](https://user-images.githubusercontent.com/621514/36144669-ae3f5724-10a6-11e8-8e5b-7a40881324fb.png)

Clearly says Three.
