### ISSUE TITLE
Imperium - Astra Militarum - Tempestor Prime

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2479]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The tempestor Prime is currently allowed to take <Regiment> specific Relics, despite the fact that the Tempestor Prime can never possess any Regiment keyword other than "Militarum Tempestus," and can therefore never take these relics.

**Comment by GenWilhelm** [comment]
The whole regiment-specific relics section needs looking at in general, I think. If I pick a regiment's doctrines for my detachment, I would expect the relics from other regiments to no longer be available.

**Comment by CrusherJoe** [comment]
Man fixing this one wasn't trivial -- but it needed to be done. Everyone should get the correct relics based on <Regiment>. You're on your own for selecting the correct weapons for relics that replace specific wargear choices (Tuskblade, Blade of Conquest, etc.) though. For now, at least. :)
