### ISSUE TITLE
Imperium - Space Marines: Venerable Dreadnought shouldn't have twin autocannon option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2486]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Space marine venerable dreadnought cannot use twin autocannon instead of Dreadnouht combat weapon

**Comment by Mad-Spy** [comment]
Assuming that you mean "should not be able to" rather than "is not able to", your report is incorrect.

Units *can* take Index weapons options, as per the Designer's Commentary flowchart, see #1414.
