### ISSUE TITLE
Feature Request - clearly identify beta units 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#2487]
Hello,

GW is starting to introduce beta rules into their regular pipeline 
(https://www.warhammer-community.com/2018/02/13/adeptus-custodes-forge-world-beta-rules-and-codex-faqgw-homepage-post-4fw-homepage-post-2/)

They have clearly stated that these rules should not be used in a competitive environment as they are not final. 

The Request is the following: Is it possible to clearly identify what’s in beta and what’s final?    This would help a lot event organizers and players in general to understand the differences.  Example just add a beta tag or the word “Beta” in the units name. 

Thanks in advance

**Comment by skonk** [comment]
This was being discussed yesterday and will likely happen the way you describe.

**Comment by GenWilhelm** [comment]
This is something we're currently trying to work out how to include (if at all). This is the current iteration, which I think matches pretty closely what you're asking for:

![beta](https://user-images.githubusercontent.com/22036809/36203358-33a5b312-117f-11e8-8913-37164c556e83.png)

The units with Beta rules are both tagged with `(Beta)` and will be hidden unless you select `Use Beta Rules` from No Force Org Slot.

**Comment by Drachnyen** [comment]
Wow.  That’s awesome guys

Thanks

**Comment by amis92** [comment]
Guideline written: https://github.com/BSData/wh40k/wiki/CAT-Creation-Guidlines/fb1349f6dbd36a329639c9d66ad68ed66e27001a
