### ISSUE TITLE
More Imperium - Adeptus Ministorum.cat missing entries

### ISSUE THREAD

**Issue by jusma15** [BSData/wh40k#2493]
Imperium - Adeptus Ministorum

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Elite units Hospitaller, Dialogus, are missing entries for Shield of faith and Acts of faith.

**Comment by alphalas** [comment]
They are linked rules, not profiles.

**Comment by jusma15** [comment]
So they are not supposed to be displayed on the units profile?

**Comment by alphalas** [comment]
If you have BS set to show rules and profiles they will appear

**Comment by jusma15** [comment]
i do, and both are not displaying the rules the same as the Mistress of Repentance was in the ticket i opened yesterday.

**Comment by alphalas** [comment]
Ok that is strange then; sorry for the confusion

**Comment by jusma15** [comment]
NP

**Comment by jusma15** [comment]
my SO plays Sisters so i never noticed the missing entries until yesterday.
