### ISSUE TITLE
Imperium - Space Wolves: Long Fangs' WGPL cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2494]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Wolf guard pack leaders in long fangs pack has wrong cost - currently 15, should be 14

**Comment by Mad-Spy** [comment]
Terminator WGPL is also incorrect; they all got changed to 26pts in CA2017.

**Comment by THusky1** [comment]
Also: wolf guard battle leader in terminator armor; is 92 should be 91, and wolf guard battle leader on thunder wolf; is 97 should be 94, both changes from chapter approved 2017.

**Comment by THusky1** [comment]
Further, both swiftclaws and all space wolf characters on bikes do not have the cost of the bikes twin Bolter listed or optional - should be 2 points

**Comment by CrusherJoe** [comment]
Okay got both issues fixed -- including the WGPL in TDA (it also got a points reduction in CA).
