### ISSUE TITLE
Hellblaster Sergeant doesn't list Plasma Incinerator as a weapon choice/option

### ISSUE THREAD

**Issue by ntomczek** [BSData/wh40k#2496]
**File/Catalogue:** Imperium - Space Marines.cat

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** Updated my data 2/15 and still saw the following issue. Per the codex a unit of Hellblasters contain "1 Hellblaster Sergeant and 4 Hellblasters. [...] Each model is armed with a plasma incinerator, a bolt pistol, frag grenades, and krak grenades." In the data the options listed for the Sergeant there are only Bolt pistol, Frag grenade, Krak grenade  and you can change the Bolt pistol for a Plasma pistol, no options for the Plasma Incinerators.

**Comment by skonk** [comment]
![image](https://user-images.githubusercontent.com/621514/36278316-69cee0f0-128b-11e8-930d-78dc369641fd.png)

The Plasma Incinerators fir the entire unit are costed together as shown in the image above (15 points each x 5 = 75 points).

if you change between the different variants of the weapon the cost will update accordingly.
