### ISSUE TITLE
Thousand Sons - Daemon Prince Tzaangor Options

### ISSUE THREAD

**Issue by davidsavagejr** [BSData/wh40k#2497]
**File/Catalogue:** Chaos - Thousand Sons.cat

**BattleScribe version:** 2.01.09

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** There are a couple extra options available that shouldn't be based on the recent Codex released.

1. Daemon Princes cannot take a Warp Bolter
1. Tzaangors cannot take an Icon of Flame anymore

**Comment by WindstormSCR** [comment]
These options remain possible because of the Designer Commentary document. Refer to #1414 for more information.
