### ISSUE TITLE
Imperium - Grey Knights - Chapter Approved Terminator Correct Correction

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2500]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** 
- [x] Terminators to 41 ppm

**Comment by tekton** [comment]
This was actually already correct- 41pts + 2pt Storm Bolter = 43 points
