### ISSUE TITLE
Chaos - Chaos Space Marines: Lord of the Red Corsairs rule incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2512]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The lord of the red Corsairs ability by Huron black heart is incorrect. The ability should read,” Lord of the Red Corsairs: You can re-roll hit rolls of 1 for friendly RED CORSAIRS units within 6" of Huron Blackheart.

**Comment by skonk** [comment]
Appears to have the description of the ability as it was in the Index; but it was changed in the Codex.
