### ISSUE TITLE
Imperium - Grey Knights: Librarian in-line smite is wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2515]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Librarian Smite...

Verify the following...
- [x] Purgation Squad Special Weapons Points
- [x] Purifier Squad Special Weapons Points
- [x] Strike Squad Special Weapons Points
- [x] Paladin Squad Special Weapons Points
- [x] Terminator Special Weapons Points

**Comment by WindstormSCR** [comment]
Pretty sure the librarian is missing the army rule that reduces the smite effect on the actual codex data sheet, but I don't have a codex to verify.

**Comment by tekton** [comment]
I swear I fixed that purifier thing a while ago...sigh, well, was going to do a push tonight anyway...

The librarian got messed up in the same merge that messed up the stormhawk due to a gst change, I'll get that in there, too.

**Comment by tekton** [comment]
Purifiers are 26 points each, the Incinerator is 14 points => 40 points, which is what's in Battlescribe right now, the other two are also correct in 2 (psilencer) and 14 (psycannon)

**Comment by tekton** [comment]
Librarian had the army rule, it was just the "smite" shared profile was the "wrong" one ;)
