### ISSUE TITLE
Imperium - Inquisition: Coteaz power validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2516]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Bug happens both in iOS and PC.  Picking a power for Coteaz gives the error message that "Inq Coteaz has one too many selections from the Telethesia Discipline (maximum 0)"

Obviously as a psyker he is allowed to pick a power.  Also, there's no option to pick a power for a normal inquisitor, but that's less annoying than being able to pick one for Coteaz and getting an error.

**Comment by CrusherJoe** [comment]
Okay, fixed Coteaz. 

To select powers on a generic Inquisitor you have to select the "Psyker" option and then click on "Psyker" under the Inquisitor's entry. You select a power from there.

![inquisitor-psyk](https://user-images.githubusercontent.com/9998385/36487353-4737ab62-16e6-11e8-909b-9c11280bb258.PNG)
