### ISSUE TITLE
Imperium - FW Death Korps of Krieg Spelling mistake

### ISSUE THREAD

**Issue by Cultiststeve** [BSData/wh40k#2518]
**File/Catalogue:** FW Death Korps of Krieg v36

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

"Death Korps Centaur Light Assault Carrier" shared profile, the "i" in "light" is incorrectly capitalised.
(Minor thing I know :))

**Comment by CrusherJoe** [comment]
Oops!
