### ISSUE TITLE
Imperium - Space Wolves - No cost on Bikers for the Twin Boltgun 

### ISSUE THREAD

**Issue by PogoNeo** [BSData/wh40k#2530]
**File/Catalogue:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:**

Hi,

I don't see the value of the Twin Boltgun for the Space Wolves Bikers (2pts/model, index value). And when I open the Bikers unit, I see under the fig Chainsword, Bolt pistolet, and not Twin Boltgun. 

I see the same problem on Dark Angel Ravenwing Bikers, perhaps anothers Space  Marine have the same problem. 

Best Regards,
PogoNeo

**Comment by THusky1** [comment]
I brought up this issue in a comment elsewhere and it seems to have been addressed (literally minutes prior to your report) - update hasn’t gone live yet however

**Comment by CrusherJoe** [comment]
That's correct -- I thought I mentioned it in the comments on the fix for the other issue you raised. Regardless, it's fixed now. :) Thanks!
