### ISSUE TITLE
Imperium - Space Marines: Force weapon cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2536]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** In chapter approved pg 116, points increased for power swords (8pts) force staves (8pts) and force axes (10pts).

**Comment by Mad-Spy** [comment]
The costs look correct in the current version of the file (v41). Can you provide an example of where they are wrong?
