### ISSUE TITLE
Imperium - Space Wolves: Error when equipping melee weapon on Lone Wolf Terminator

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2539]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** ~~Long Fang~~ Lone Wolf in terminator Armour throws "too many selections from power sword (maximum 1)" when trying to equip a storm shield in the "power sword" slot and a melee weapon in the "storm Bolter" slot.

**Comment by skonk** [comment]
I can't test this myself on Android; but on Desktop I don't see the same issue, so it should work fine on Android too.

Are you 100% sure you removing all other weapon selections?

![image](https://user-images.githubusercontent.com/621514/36530410-dfdd861c-17b2-11e8-982f-8c16fb4ab899.png)

**Comment by Mad-Spy** [comment]
I think the problem here is not actually with a "Long Fang in Terminator Armour" (which doesn't exist), but actually with the Lone Wolf, which does display the reported error.

**Comment by skonk** [comment]
Ah, I must have misread the unit name.

**Comment by Mad-Spy** [comment]
No, I just updated the comment.

**Comment by CrusherJoe** [comment]
I'll take a look at this one this evening or tomorrow morning -- I'm traveling today.
