### ISSUE TITLE
Imperium - Space Marines: Unable add Warlord or Warlord Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2541]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Cannot give any of my hq units the warlord option. Works on every faction fine. But i cannot get the warlord option to appear for any space marine hq units

**Comment by Mad-Spy** [comment]
Already in progress, see #1838
