### ISSUE TITLE
Chaos - Chaos Space Marines: Chapter-specific units missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2547]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Missing Units:
There is no Abaddon or Kharn the Betrayer units available to select under the CSM.

**Comment by skonk** [comment]
Units with fixed Legion Keywords are hidden unless you select the correct Legion.

If you change the selected Legion to "Black Legion" for example; Abaddon will show up.
