### ISSUE TITLE
Imperium - Space Marines: Primaris Aggressor Flamestorm Gauntlet Point Values

### ISSUE THREAD

**Issue by JPEGtheDev** [BSData/wh40k#2554]
**File/Catalogue:** Imperium - Space Marines v41 

**BattleScribe version:** 2.01.

**Platform:** Windows/Android (may be others)

**Dropbox:** Yes

**Description:** Primaris Aggressor Squad Flamestorm Guntlets point values do not properly calculate when changing the total number of Aggressors in the squad. The auto boltstorm gauntlets do calculate correctly. Issue is present on both Windows 10 and my Android device. Unless there is a special rule that I didn't read, I believe that this is broken. 
![ss1](https://user-images.githubusercontent.com/7024087/36635671-5d3a9958-1987-11e8-96ae-2e3d6e061539.PNG)
![ss2](https://user-images.githubusercontent.com/7024087/36635672-5d461562-1987-11e8-8d5c-35b3cfccdd2a.PNG)
![ss3](https://user-images.githubusercontent.com/7024087/36635673-60fb2ecc-1987-11e8-9753-ab65f61bedec.PNG)

**Comment by Mad-Spy** [comment]
Pretty sure this is a Battlescribe quirk where a selected options points don't update correctly if the point increment in the backend is set up in a particular way. If you select the boltstorms, the flamestorm points will update.

**Comment by JPEGtheDev** [comment]
Verified and @Mad-Spy is right, and it appears to change once you swap back and forth.

**Comment by JPEGtheDev** [comment]
This still appears to happen on Android when you change the total number of Aggressors while flamestorm is selected. I purged the data, reloaded from the web and rebooted my phone for safe measure. I need to verify if this exists on desktop.

**Comment by GenWilhelm** [comment]
@JPEGtheDev, are you pulling data from appspot (via BattleScribe) or direct from the repo?

Changes on the repo aren't available on appspot until we release them, which will likely be in the next day or two in this case.

**Comment by JPEGtheDev** [comment]
@GenWilhelm I realized my mistake. I was looking at the Eisenhorn release. @Mad-Spy published the change at roughly the same times as the Eisenhorn release (different dates). I was on mobile and wasn't paying attention. Loaded up the latest commit and it appears to be working fine. Thanks!
