### ISSUE TITLE
Stratagems affecting list building (eg No. of Relics allowed)

### ISSUE THREAD

**Issue by Pukwudji** [BSData/wh40k#2559]
**File/Catalogue:** WH40k

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes

**Description:** Is it possible to represent the selection of a stratagem that affects list building?  For example, in the Grey Knights Codex, there is a stratagem ARMOURY OF TITAN that allows for the selection of either one or two extra relics.  Every codex I have seen has a similar stratagem, so this may prove universally worthwhile.

**Comment by WindstormSCR** [comment]
These have been slowly added in as catalogs have been updated, some have them and some do not, but they'll be there eventually

**Comment by tekton** [comment]
I'm getting to it this weekend, doing it a bit like Custodes @WindstormSCR ;)
