### ISSUE TITLE
Imperium - Space Wolves: Wulfen is missing the keyword "infantry"

### ISSUE THREAD

**Issue by ViktoriousPersson** [BSData/wh40k#2562]
File/Catalogue: Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

Description: I'm not shure if I'm doing this right!? But the way I see it the keyword "infantry" should be there, and I've googled in alot and can't find any answers. Found this bug report site so I'll try reporting it here. Anyone else seen this bug?

**Comment by ViktoriousPersson** [comment]
I'm not shure if I'm doing this right!? But the way I see it the keyword "infantry" should be there, and I've googled in alot and can't find any answers. Found this butreport-site so I'll try reporting it here. Anyone else seen this bug?

**Comment by skonk** [comment]
Seems you are correct; other units have Infantry as they should but it is missing on Wulfen.

**Comment by ViktoriousPersson** [comment]
I could not find any contact information on the author...

**Comment by skonk** [comment]
It's fine; they will see it here.

**Comment by CrusherJoe** [comment]
Indeed I will. 👍 This morning is bug-squashing-day. Lemme fire up the editor and get that knocked out.
