### ISSUE TITLE
Imperium - Dark Angels -Tartaros reaper autocannon points is 15, and according to the codex its 18.

### ISSUE THREAD

**Issue by Dahenda** [BSData/wh40k#2565]
**File/Catalogue:** 
Warhammer 40,000 8th Edition v39
Imperium - Dark Angels v48

**BattleScribe version:** 
2.01.09

**Platform:** 
Windows

**Dropbox:** No

**Description:** 
Tartaros reaper autocannon points is 15, and according to the codex its 18.

**Comment by skonk** [comment]
It is indeed 18 points in the Codex and I'm not seeing anything that changes this in chapter approved or faqs.

**Comment by Dahenda** [comment]
I think this may also affect vanilla space marines or any marines that have Tartaros terminators.

**Comment by Dahenda** [comment]
I did do quite a bit of digging when before reporting it, but i could not find anything, even more confusing is that for CSM the price did go from 18 ->15 when their codex was released.

**Comment by Thairne** [comment]
This should affect anyone that is using the entry from the GST.
I cannot judge who this affects, so I also cannot say if the GST pts cost needs to be changed.
