### ISSUE TITLE
Aeldari - FW Corsairs: Weapon display issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2573]
**File:** Aeldari - FW Corsairs.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** information for lascarbine and lasblaster refuses to display, as well as other forge world models just behaving strangely in quick view and print options

**Comment by Mad-Spy** [comment]
I'm unable to replicate the issue in Windows or Android app without manually switching off Profiles in the output.

Can you give more details on which other FW units are behaving strangely?

**Comment by FarseerVeraenthis** [comment]
In the Corsairs CAT directly there are no problems. However, the copy to the Ynnari CAT was incomplete so there were no profiles to show there for Corsairs units.
Possibly there might be an issue when creating a soup detachment including a Corsair unit and Ynnari, or one of the other Aeldari CAT's but it is difficult to diagnose without further details.

A screenshot would be awesome :wink:
