### ISSUE TITLE
REMOVAL: Dreadnought - Twin Autocannons

### ISSUE THREAD

**Issue by DoctorMiracles** [BSData/wh40k#2576]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

I've noticed that the Dreadnought and Venerable Dreadnought have the option to replace their Melee weapon with a Twin Autocannon. This isn't an option in either the Codex or the FAQ.

**Comment by Mad-Spy** [comment]
It's an option in the Index, and Index weapon options are allowed as per the Designer's Commentary. See #1414.
