### ISSUE TITLE
Aeldari - Ynnari: Add Felarch weapon options and weapon profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2580]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ynnari dneeds to be updated to allow Corsair felarchs to change weapons and also to show weapon profiles for lasblasters Shuriken catapults etc

**Comment by FarseerVeraenthis** [comment]
noted, thanks :smile:

**Comment by FarseerVeraenthis** [comment]
I obviously can't spell... this is closes by my last commit.
