### ISSUE TITLE
Aeldari - FW Corsairs: Cloud Dancer Felarch is missing weapon choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2581]
**File:** Aeldari - FW Corsairs.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Cloud dancer felarch comes with the same things as a normal cloud dancer (ie twin shuriken catapult) and has the option to change to one of the heavy guns

**Comment by FarseerVeraenthis** [comment]
Yeah, you're right, he's missing his options, because "any model" includes the Felarch... :smile: RTFM - I'll get to it
