### ISSUE TITLE
Imperium - Space Marines: Company Vet Sergeant on bike should be able to take a storm shield

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2583]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** In the company veterans on bikes unit, the veteran biker sergeant should have the option to take a storm shield for 5 points.

**Comment by Mad-Spy** [comment]
I don't believe this is correct. The Veteran Sergeant can swap his weapons for choices from the *Sergeant Equipment* list and that list does not contain a storm shield.

**Comment by flakpanda** [comment]
@Mad-Spy is correct.
