### ISSUE TITLE
Imperium -- Astra Militarum -- Stormblade missing heavy bolter

### ISSUE THREAD

**Issue by CrusherJoe** [BSData/wh40k#2585]
Arkurian Pattern Stormblade is missing a heavy bolter. This will affect DKOK as well.

**Comment by minus67** [comment]
This tank should come to the following. The only options on this tank are pintle weapons and hunter killer missiles

Arkurian Pattern Stormblade |   | 400
-- | -- | --
  | Adamantium Tacks | 0
  | Plasma Blastgun | 0
  | 2x Lascannon | 40
  | Heavy Bolter | 8
  | 2x Twin Heavy Bolter | 28

**Comment by CrusherJoe** [comment]
Yes sir, that it does. I'll need to add another THB and the las cannons. Thanks!
