### ISSUE TITLE
Thousand Sons Forge World Options Missing

### ISSUE THREAD

**Issue by LockeWatts** [BSData/wh40k#2588]
The current Thousand Sons data files do not allow for any Forge World options, despite the Thousand Sons FAQ explicitly allowing for those units to be taken.

**Comment by skonk** [comment]
Add a nested detachment using the Forgeworld Heretic Astartes catalogue and add them via that. By nesting the detachments Battlescribe will validate it as if it was a single Detachment.

**Comment by LockeWatts** [comment]
Ah, thank you. I had no idea those had been refactored into their own catalogue.

**Comment by skonk** [comment]
:) no probs
