### ISSUE TITLE
Warhammer 40,000 8th Edition: Output not displaying profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2590]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** All new lists and updates to old lists do not show profiles or descriptions. They only show names, points, and keywords. Older lists still show profiles and descriptions, but they disappear if edited. This started 2-3 months ago. Wasn't sure if this was a bug or if data files no longer included this info.

**Comment by Mad-Spy** [comment]
The data still exists. It sounds like you have something switched off in your output. Please check your output settings.
