### ISSUE TITLE
No equipment validation for Relics

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#2592]
**File/Catalogue:** v1.1.22 (aka v39)

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Relics have no validation checking that the bearer meets the equipment requirements. e.g. Teeth of Terra requires the model to have a chainsword, Pietrov's Mk 45 requires the model to have a Bolt Pistol, etc.

**Comment by alphalas** [comment]
That’s up to the user and their friends/TOs to verify.

**Comment by BaconCatBug** [comment]
By that logic so are points costs, what's the point of Battlescribe then?

**Comment by FarseerVeraenthis** [comment]
It depends on how the CAT has been written, as I remember it there is validation in the Eldar CAT... which cat are you referring to specifically??

**Comment by BaconCatBug** [comment]
I checked in the Astra Militarum and Space Marines one, and then assumed it
was across all armies. In hindsight I shouldn't have done that.

The Eldar .cat doesn't seem to have validation, it just ascribes points
costs to the relics instead and you add them instead of the base relic.

**Comment by FarseerVeraenthis** [comment]
I think in Eldar you can only choose relevant relics per unit though... I will get into the cat later but I'm out atm
