### ISSUE TITLE
Imperium - Astra Militarum: Hellhound cost and missingbPask

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2593]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Hellhound cost isn't there. Latest update Knight commander Pask isn't on HQ list.

**Comment by Mad-Spy** [comment]
You will need to add a Hellhound variant to the "Hellhounds" unit to get a cost.

Pask is a Cadian unit  and only appears if you select Cadian as your regiment.
