### ISSUE TITLE
Adeptus Mechanicus

### ISSUE THREAD

**Issue by DarthLiles** [BSData/wh40k#2598]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by DarthLiles** [comment]
Adeptus Mechanicus,  Flyers, auxiliary super heavy, and super heavy detachments do not work.

**Comment by Thairne** [comment]
AdMech does not have any flyers or superheavies.
Questoris Mechanicus are in the Knights File and can be accessed from there.

**Comment by DarthLiles** [comment]
Thank you very much.
