### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Titanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2601]
**File:** Imperium - Adeptus Titanicus.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** WarHound Scout Titan in the latest forces of the astra militarum is 1500 points including war gear, not 2000 as per battle scribe. I've checked the GW FAQ's and can't see any points change for the model.

**Comment by skonk** [comment]
![image](https://user-images.githubusercontent.com/621514/37000482-759be192-20bb-11e8-83aa-17b6d4fff210.png)

The points were increased in the Chapter Approved supplement.
