### ISSUE TITLE
removing seekers also removes from other units of seekers in the same detachment

### ISSUE THREAD

**Issue by CloverFox** [BSData/wh40k#2604]
**File/Catalogue:** 
Chaos Daemons v31, BST v39
**BattleScribe version:** 2.01.
2.01.09
**Platform:** Windows/iOS/Android/Mac/Linux
Linux
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
add 2 units of seekers to a detachment
add a number of seekers to each unit
remove seekers from one unit, it will erroniously remove them from the second unit
this is multiplied with more units, eg with 3 units of seekers, removing from 1 will remove from the other 2

**Comment by amis92** [comment]
@CloverFox might that be a similar issue? https://github.com/BattleScribe/Desktop-Alphas/issues/166

I mean, does this happen only in nested/child force, or a root one too?

**Comment by Mad-Spy** [comment]
No, some idiot set Collective on the model.

**Comment by amis92** [comment]
So this actually *is* a BS bug? xD (I mean that it doesn't increment?)
