### ISSUE TITLE
Imperium - FW Adeptus Astartes: Issues adding Relic units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2611]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Whenever I try to add my FW relic elites to my list it says I can’t have them which is really irritating.

**Comment by Crowbar90** [comment]
Are you using the FW detachment as parent?

Il mer 7 mar 2018, 21:18 BSDataAnon <notifications@github.com> ha scritto:

**Comment by Crowbar90** [comment]
For further information, read [Using FW Relic units](https://github.com/BSData/wh40k/wiki/Using-FW-Relic-units).
