### ISSUE TITLE
Dark Angels Aggressor Weapon Costs

### ISSUE THREAD

**Issue by axisofentropy** [BSData/wh40k#2617]
**File/Catalogue:** Imperium - Dark Angels

**BattleScribe version:** v2.01.09.99

**Platform:** Linux (Java)

**Dropbox:** Yes

**Description:** The points values for Dark Angels Aggressor units larger than 3 models are incorrect and also display inconsistently in the desktop Battlescribe.

When armed with Flamestorm Gauntlets (18 points each) the point values are correct. But here's the expected and observed point values for units of various sizes when armed with Auto Boltstorm Gauntlets (12 points each) and Fragstorm Grenade Launchers (4 points each):

Unit Size | Expected | Observed
----------|----------|---------
3 models | 111 | 111
4 models | 148 | 150
5 models | 185 | 189
6 models | 222 | 228

Also, on my desktop Battlescribe, the points values for the weapons does not change when I change the number of Aggressors in the squad.  The weapon points do change when I select a different weapon. Notice in this screenshot that the weapon point values do not reflect the just-changed squad size.
![image](https://user-images.githubusercontent.com/66315/37134391-f3f6ae8e-225d-11e8-8be3-e73ed40d1ebb.png)

I looked at this in the Data Editor but then decided to write this ticket instead of trying to replace this myself. Maybe we can copy the Aggressor implementation from another Astartes catalog?  Or maybe these shared Primaris units should even be within the 40k GST?
![image](https://user-images.githubusercontent.com/66315/37134354-c9ba25ce-225d-11e8-94d4-637c7578374b.png)

**Comment by Mad-Spy** [comment]
Cost increment sounds like the issue from #2554.and the points increment for the boltstorm/launcher combo is too high, it should only be 16pts, not 18. It probably just got missed when the points changed in CA.

**Comment by Thairne** [comment]
Interesting. The option that is not selected DOES update.

**Comment by Thairne** [comment]
Good advice, @Mad-Spy :)

**Comment by Mad-Spy** [comment]
@Thairne, yeah, it's one of those interesting Battlescribe quirks. :)

**Comment by Thairne** [comment]
Especially if you consider that using 'model' to imcrement power levels bugs out sometimes.. le sigh.

**Comment by axisofentropy** [comment]
@Thairne Battlescribe updates better but the points costs are farther off now.  Flamestorm Gauntlets are also affected.

Unit Size | Expected | Observed
----------|----------|---------
3 models | 111 | 129
4 models | 148 | 168
5 models | 185 | 207
6 models | 222 | 246
