### ISSUE TITLE
Imperium - Deathwatch: Terminator Captain wargear issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2624]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 1.09.99

**Platform:** Windows

**Dropbox:** No

**Description:** Watch Captain in Terminator Armour is missing weapon options - to replace storm bolter and/or power sword with terminator melee weapons.

Imperium 1 index  allows captain in terminator armour (page 12) to access terminator melee weapons.
Space Marine codex (update) confirms access to terminator melee weapons.
Chapter Approved - pg 117 Deathwatch Wargear provides updated weapons costs Storm Shield (Character) 15 pts, Thunder Hammer (Characters) 21 pts

**Comment by FarseerVeraenthis** [comment]
we'll include this when we do the Codex update. :smile:
