### ISSUE TITLE
T'au Empire Codex - Stimulant Injector removal

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2634]
*This issue was moved from comments of #2625*

---
*@superrugdr wrote on 2018-03-09 19:11 UTC:*

> Remove no-longer existing entries (Stimulant Injector)

 shouldn't this option stay there under the FAQ that allow taking profile lost in the codex from the index (same case as for shrikes) this is linked to the  #1414 

---
*@alphalas wrote on 2018-03-09 19:59 UTC:*

No, because it’s a list item; not an actual wargear item on a datasheet. Designers commentary only applies to wargear options on datasheets; not to lists

---
*@rider49 wrote on 2018-03-09 20:03 UTC:*

So, I can take might is right and another warlord trait from the brb?
What about in the rule book where it says on page 186?
I am new to the game and too battlescribe so I know I can be wrong I just
want to be sure one way or the other.

---
*@Alvirulan wrote on 2018-03-09 21:18 UTC:*

@alphalas What do you mean with list item? I do not believe that there is such thing. Codex, Index and brb only describe models and wargear.
Stimulant injector is definitively a wargear item.

---
*@alphalas wrote on 2018-03-09 21:19 UTC:*

My point is it’s not a wargear item specifically on the data sheet; so is not subject to the designer’s commentary

---
*@Alvirulan wrote on 2018-03-09 22:45 UTC:*

Well if look at https://i.redd.it/n3g7779rddyz.jpg and at p46 of Index - Imperium 2 (Commissar), you have a similar example (replace stimulant injector by power axe in this case)

**Comment by amis92** [comment]
Thank you for the link to the document in question.

Okay, honestly? Stop this madness. Please, follow step by step:
1. It's pretty clear that Stimulant Injector has new rules in the codex.
2. Therefore, it is a wargear option from Index that has new rules in Codex [irrespective if it still even counts as wargear].
3. Therefore, the Designer's commentary says "use Codex".

Where is that not clear?

**Comment by Coldhalbu** [comment]
With all due respect (and I mean it, BS is one of the best apps I use for managing the lists), it's not "some weird logic", it's a direct result of the document and its interaction with the wargear list. The fact the there is a stratagem called Stimulant Injector doesn't change the fact that there is a wargear option called that in the Index and there is none in the Codex. Unless there is an official FAQ or errata changing this chain of rules, this is the only logical outcome - stratagems are not wargear.

**Comment by amis92** [comment]
Indeed. By virtue of [rule number 0](https://github.com/BSData/wh40k/wiki/CAT-Creation-Guidlines#guidelines) this option will stay annotated as INDEX until an FAQ determines its validity.

**Comment by amis92** [comment]
Actually, I've just noticed that the Injector *link* in Support Systems group was left with hidden checked (so it actually isn't available at all). It'll be fixed soon.
