### ISSUE TITLE
Imperium - Blood Angels: Unable to select Land Speeder Storm

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2635]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Land Speeder Storms have no options in Blood Angels codex

**Comment by Mad-Spy** [comment]
I can't find anywhere that says Blood Angels should have access to the Land Speeder Storm. They didn't have access in the Index, and it wasn't added in the Codex.

**Comment by alphalas** [comment]
Yes it is Iian.

I think OP is more talking about Index vs Codex; and is unfamiliar with #1414 so is confused by LSS having options.

**Comment by Mad-Spy** [comment]
@alphalas, I think that the OP is questioning why there are no options on the BA Storm. However, I agree with the current implementation because the BA didn't have access to the Index version, therefore they shouldn't have access to those options.

**Comment by Crowbar90** [comment]
Yes, that was my exact reasoning. The only datasheet named "Land Speeder Storm" to which Blood Angels have access is the Codex one, which does not have any options.

**Comment by alphalas** [comment]
Is incorrect though considering rule#0 of BattleScribe

**Comment by Crowbar90** [comment]
Indeed, I stand corrected. I'm fixing it right now, sorry for the misunderstanding.
