### ISSUE TITLE
Astra Militarum: Small model count units

### ISSUE THREAD

**Issue by skonk** [BSData/wh40k#2642]
I have sent an email to the GW FAQ address asking what the deal is with using these lower model count unit data sheets included in some of the model kits; but as of right now I don't see why they wouldn't be OK to use.

![image](https://user-images.githubusercontent.com/621514/37332749-7fbee23e-269f-11e8-9b75-af2b2428c846.png)

Thoughts on including this as a unit in the cat?

**Comment by Mad-Spy** [comment]
I've added the similar Chaos units to the Chaos catalogue, using the relevant points values from the full size units.

**Comment by alphalas** [comment]
closed as per gitter convo
