### ISSUE TITLE
Tempestor Primes got changed so old rosters no longer load correctly, why then use the excuse of "backwards compatibility" to not change Leman Russes?

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#2643]
Tempestor Primes got changed so old rosters no longer load correctly, why then use the excuse of "backwards compatibility" to not change Leman Russes? https://github.com/BSData/wh40k/issues/1989

**Comment by Kohato** [comment]
The Issue tracker is hardly the place to air your dirty laundry in regards to the maintenance practices of our data authors.  You clearly have been waiting for something to show up to contradict an earlier decision just so you could bring it up.  If you have something to discuss, please join us on gitter.
