### ISSUE TITLE
Chapter Tactics/Black Templar

### ISSUE THREAD

**Issue by badkarmavp** [BSData/wh40k#2643]
The Emperor's Champion is gone :(
Needs to be re-added

**Comment by Kohato** [comment]
He's there if you select BT tactics. But I goofed - he's 407 points until I release again tomorrow.

**Comment by badkarmavp** [comment]
Yeah, at second look i couldn't find any of the special characters.  But I'll wait for the next release.  Thanks for the quick response

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Nov 3, 2016 at 9:13 PM -0400, "Earl Bishop" <notifications@github.com<mailto:notifications@github.com>> wrote:


He's there if you select BT tactics. But I goofed - he's 407 points until I release again tomorrow.

-
