### ISSUE TITLE
Imperium - FW Elysians: Warlord Trait Selection Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2658]
**File:** Imperium - FW Elysians.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Elysian commanders do not have the option to select a warlord trait other than those in the rule book. 

Option to select generic AM warlord traits is required e.g grand strategist, old grudges etc

**Comment by CrusherJoe** [comment]
I could've sword I did that for Elysians already...guess not. Okay I'll fix it.
