### ISSUE TITLE
Imperium - Dark Angels: Dark Angels Landspeeder Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2661]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Dark angels  ravenwing landspeeder. Change cost from 80 to 70 as per codex values

**Comment by Thairne** [comment]
And 70 it is already.
