### ISSUE TITLE
Imperium - Dark Angels: Boltstorm Gauntlet/Fragstorm Launcher Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2662]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** Yes

**Description:** Points value for auto boltstorm guantlets/fragstorm launcher seems incorrect

**Comment by axisofentropy** [comment]
Probably duplicate of #2617

**Comment by GenWilhelm** [comment]
Yeah, this was fixed in 36efc4b19a612f2d4a5be243175dc5beae9bbe50 (Dark Angels v52).

It should be there if you update your data, as the fix went out alongside the Tau codex.
