### ISSUE TITLE
Appspot appears to be down

### ISSUE THREAD

**Issue by nickbender** [BSData/wh40k#2665]
**File/Catalogue:** 
None

**BattleScribe version:** 
2.01.14

**Platform:** iOS

**Dropbox:** No

**Description:** Unable to refresh repositories or view them on appspot website. Other data limit errors found on reddit, but no recent reports. Error displayed in app is “The remote server returned an error: (500) internal server error.”

**Comment by alphalas** [comment]
See #1706
