### ISSUE TITLE
Tau Codex Cadre Fireblade is 39 points instead of 42

### ISSUE THREAD

**Issue by XakiteX** [BSData/wh40k#2670]
**Tau Codex:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by tekton** [comment]
Fireblade is 39pts
Markerlight is 3pts
Total Base Cost: 42pts
