### ISSUE TITLE
T'au Empire: Improvement to Breacher Team selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2677]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.19

**Platform:** Windows

**Dropbox:** No

**Description:** Hello. For the Tau Breachers troop the option to add the pulse pistol seems weird (you have to select the FW with PP and then equip them with it in their sub menu), can you please apply a similar solution as the Strike team has? Thanks!

**Comment by Mad-Spy** [comment]
Looks like Pulse Pistol is just missing a min1 constraint.

There's another issue though, in that the Shas'ui should be able to un-equip his Pulse Blaster.

**Comment by amis92** [comment]
Uh-oh. Probably copy-paste taking revenge :o
