### ISSUE TITLE
T'au Empire: Plasma Accelerator profile incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2685]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Plasma Accelerator Rifle has the wrong stat-line. It should be range: 30", type: Rapid Fire 1, S: 7, AP: -3, D:2

**Comment by amis92** [comment]
Duplicate of already resolved #2669
