### ISSUE TITLE
T'au: XV25 Stealths and TX4 Piranhas un-flattening

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2688]
After some feedback, I'm going to restructure XV25 and TX4 selections:

* XV25 Stealthsuits will be left with 4 choices:
  * Shas'vre
  * Shas'ui w/ Burst cannon
  * Shas'ui w/ Fusion blaster
  * Shas'ui (customizable)

* TX4 Piranhas will be completely merged into single customizable selection

I think TX-42s can be left like they are. They can't be customized, it's 4 options and collapses nicely (collective).

@alphalas @Mad-Spy @Kohato agreed?

**Comment by alphalas** [comment]
Would it be too complicated to make the stealth squad just be the single customizable ‘ui and the option to take a customizable ‘vre?

**Comment by amis92** [comment]
Definitely not *complicated*. I'm just trying to balance `option usefulness : UX : nice output` ratio :) I'm not sure stealths with support systems are worth it and I guess they won't see much use.

Also, you know, optimizing hot-paths is part of my job, literally, as a programmer, so I may deviate a little in that direction. That's why I discuss and want to be persuaded.

**Comment by alphalas** [comment]
That’s fair lol

**Comment by Mad-Spy** [comment]
The thing is that if you're building a customisable Shas'ui for the XV25s anyway, then there seems little point in making the non-customisable options as well. as the csutomisable one covers them both.

**Comment by amis92** [comment]
I've decided to finally leave XV25s with 3 choices:
* Shas'vre
* Shas'ui w/BC
* Shas'ui w/FB

Honestly, I've left Shas'ui separated because I didn't have time to move logic for counting Fusion Blasters from model to upgrade :) I think it's cool, though.
