### ISSUE TITLE
Twin Autocannon Cost Incorrect

### ISSUE THREAD

**Issue by abaumayr** [BSData/wh40k#2689]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Page120 of Chapter Approved shows the new cost for Twin Autocannons for the Space Marine faction to be 30 points instead of 33.  The Venerable Dreadnought still has the cost listed as 33.

**Comment by GenWilhelm** [comment]
Page 120 is in the Forge World section, so doesn't that change only apply to units from Imperial Armour?

**Comment by alphalas** [comment]
^this.

**Comment by abaumayr** [comment]
The Twin Autocannon is not an option anywhere in the Space Marine Codex.  It's only an item in their Index entries and Imperial Armor books, hence it's lack of inclusion in the normal section.

The Chapter Approved book also states the following: "Note that sometimes a weapon can appear in several different books, each with different points costs (for example, power fists appear in both Codex: Space Marines and Codex: Astra Militarum).  If such an item of wargear appears in one of the tables below, only apply the change to the appropriate Faction."

It's basing it on faction, ie Space Marines, not specific books.

**Comment by alphalas** [comment]
@abaumayr the twin autocannon you’re looking at is from Index, where the points are indeed 33; which the same document you cite states to use the points from index.

**Comment by alphalas** [comment]
![73772e27-bf85-49ef-8923-6ee3351ed607](https://user-images.githubusercontent.com/15703066/37688384-316d3d9c-2c76-11e8-9a4a-08bc9c77daaf.png)
