### ISSUE TITLE
Relic Leviathan Dreadnought - Leviathan Siege Claw Points Not Correct

### ISSUE THREAD

**Issue by TheTechmarine** [BSData/wh40k#2691]
**File/Catalogue:** FW Adeptus Astartes

**BattleScribe version:** 2.01.09.99

**Platform:** Windows

**Dropbox:** No

**Description:** The prices of Leviathan Siege Claws are not correct for the Relic Leviathan Dreadnought. A single Leviathan Siege Claw cost displays 72 points instead of 55 points. For a pair, it states 100 points (49.5 x 2), instead of 65 points for the pair
![wh40k_fwaa_issue](https://user-images.githubusercontent.com/30732023/37681894-3770f5ac-2c45-11e8-844a-42805d939d52.png)
.

**Comment by WindstormSCR** [comment]
Any option with a suboption (in this case a meltagun) is displayed as a total.

55+17 = 72.
