### ISSUE TITLE
T'au Empire: Aun'shi validation error with sept selection.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2695]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Select 2 tau empire detachments
Make first detachment viorla sept
Place aunshi unit in first detachment
Make second detachment any sept apart from viorla
Aunshi's maximum changes to zero like you had made the first detachment an incorrect sept
Additionally no other named characters seem to have any sept restrictions

Thank you for your hard work.

**Comment by amis92** [comment]
Indeed. Only Aun'shi had that kind of constraint implemented, and I've hooked the modifier "set to 0 when..." onto `max in Roster` instead of `max in Force`.
