### ISSUE TITLE
[Anon] No daemons in CSM, DG, TS

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2697]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** No daemons  on chaos marine codex, Death Guard codex, thousand sons codex.

**Comment by Mad-Spy** [comment]
You are correct. Daemons were removed from these catalogues to help guide users into making lists which don't lose Legion Traits by including Daemons in what should be a "Chaos Space Marines" Detachment.

Please see #2445 for further information.
