### ISSUE TITLE
Chaos - Death Guard: Curse of the Leper targeting

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2706]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Death Guard psychic power 6, "Curse of the Leper", has incorrect description:

Codex: If manifested, roll 7 dice. The closest visible enemy unit within 14" of the psyker suffers a mortal wound for each roll that exceeds its Toughness characteristic.
Battlescribe: If manifested, select a visible enemy unit within 14" of the psyker and roll 7 dice. For each roll which exceeds the unit's Toughness characteristic, that unit suffers a mortal wound

As written in codex, you do not get to select which enemy it manifests on.

**Comment by Mad-Spy** [comment]
Well, I have no idea where I got that wording from then. Fixed now. It'll be in the next release.
