### ISSUE TITLE
Chapter Approved 2017: Open Play Land Raiders

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#2708]
From /u/Mechoj_Nomreps_e via [reddit](https://www.reddit.com/r/BattleScribe/comments/86jfnj/land_raiders_chapter_approved/):
>Is it possible to add all the [land raider] options from chapter approved to [all] the space marine chapters?

---

I was actually toying around with this when Chapter Approved was first released, so I'm more than happy to implement it if other maintainers aren't keen.

Just wanted to get some other thoughts on it.

---

#### 2018-03-28 edit
Since this has been widely agreed upon, let's make it a proper issue with a check list:
 - [x] Chaos Space Marines
 - [x] Blood Angels
 - [ ] Dark Angels
 - [x] Deathwatch
 - [x] Grey Knights
 - [x] Space Marines
 - [x] Space Wolves

**Comment by Kohato** [comment]
I see no reason not to add it - it's usable in lists, and we're not matched play only.  Just set to 9999 points since not all catalogs have the "Matched play" game type selector.

**Comment by skonk** [comment]
Is it technically possible to have battlescribe support the ability to create the custom landraiders too? :)

**Comment by Kohato** [comment]
I don't see why not. Isn't it just weapon / hull options that increase PL? "Custom LR" entry. SEGs for Hull Type, Weapons, etc.

**Comment by skonk** [comment]
I think so yeh.

**Comment by GenWilhelm** [comment]
>set to 9999 points

I was thinking of having it be 0 so it doesn't mess up the totals for the rest of the army.

>not all catalogs have the "Matched play" game type selector

Isn't this in the GST root, ie. in all catalogues by default?

>Isn't it just weapon / hull options that increase PL?

It's a fixed 30 PL, regardless of wargear. The wargear options just affect abilities and transport capacity.

**Comment by GenWilhelm** [comment]
I've put my template for them on a branch in the above commit if anyone wants to take a quick looks and give any feedback. It should be pretty easy to copy it into other catalogues (and adjust the weapon options in the case of SW and CSM), which, again, I'm quite happy to do.

**Comment by tekton** [comment]
Logically GK should be able to take them, but after reading the section again I'm not so sure...

**Comment by GenWilhelm** [comment]
Yeah, Grey Knights explicitly can take them. Death Guard and Thousand Sons on the other hand...

**Comment by tekton** [comment]
I see it now; yay partially blind!

**Comment by WindstormSCR** [comment]
The matched play and narrative flags exist in root, just make it hidden if flag is not present (same as hiding by default with less bugs)

**Comment by SpaceJS** [comment]
Just want to thank you guys for the fast changes, the original request came from me. I will do some tests as soon as all variants are available for all chapters.

**Comment by WindstormSCR** [comment]
Blood Angels cat has the example case, but will need to be hand-copied for some cats due to issues with normal copy/paste in the editor

**Comment by WindstormSCR** [comment]
There is now a GST root entry that all cats can root link to.

**Comment by Mad-Spy** [comment]
@WindstormSCR, the GST version isn't correctly hiding PotMS and DMS correctly for some reason. As the author, you might want to take a look at it...

**Comment by SpaceJS** [comment]
I am not sure why this is closed, I do not see the addition in the dark Angels branch en points are not correctly calculated. can this be reopened till it is entirely correct?

**Comment by alphalas** [comment]
It is indeed added to the DA - just has not yet been released. 

ALSO; they don’t have points. So yes, it *is* done correctly.

**Comment by GenWilhelm** [comment]
>they don’t have points

More specifically, the base model doesn't have an official points cost (since they're only intended for open play) so the points cost listed in BattleScribe is only that of the wargear.

**Comment by SpaceJS** [comment]
The Terminus ultra is available for 450 points which made assume they had some kind of baseline of 300 points.

**Comment by alphalas** [comment]
You can assume that, yes; but the base model has no points cost according to GW. This means that we are not applying points cost to it.
