### ISSUE TITLE
Add disclaimer to Rule 0

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2709]
Our Implementation Guidelines have recently been updated to include rule 0:

> All choices, entries, upgrades etc. that are valid *or possibly* valid MUST be represented (implemented) and MUST NOT raise errors/warnings. This is **the single most important rule**. If there is a doubt if an option is legal, it MUST be included. *Motivation: we are not rules lawyers. Our effort targets all audiences, no matter their personal decisions, erratas or agreements. Our only source is Rules As Written (RAW), published by Games Workshop and their subsidiaries (Forge World etc.); that includes officially posted Erratas and FAQs (Facebook pages, emails and other unofficial channels excluded). If you feel we've missed a valid option (and you can provide reasonable argument supporting its legality) please raise an issue on GitHub.*

I propose to reformat it so that the "Motivation" is instead removed into site footer, but most importantly add the `Disclaimer` part, consisting mostly of the sentence starting with *Our only source is...`

The disclaimer would expand upon sources that we use, and add the following:

> **Disclaimer:** Datasheets included in physical box sets are an exception from our typical policy of inclusiveness, dictated simply by economical and practical means: we're not able to buy every single box and/or access every such datasheet by other means. If there's a request to include a specific datasheet, and the catalogue author has access to such datasheet, the catalogue maintainer can choose to include that specific box-sheet.

---

C&C and suggestions for enhancement/rewording are welcome.

**Comment by Mad-Spy** [comment]
Sounds good to me. The ones I added the OP had to supply the sheet.

**Comment by amis92** [comment]
Implemented in https://github.com/BSData/wh40k/wiki/Guidelines/_compare/e6b80dbe332dae004437706b8d091040b2c99d54...681aae1636b2709c87384e1e553c1b4a771e2243
