### ISSUE TITLE
Aeldari - Ynnari: Dire Avenger Cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2716]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Hello, I saw a different price for Dire Avenger unit (Troops) in Craftworlds dtch and Ynnari dtch. Can you check this or I need to write this information in difference place?

**Comment by FarseerVeraenthis** [comment]
Ynnari CAT has been pared back to the three characters. 
As such, Dire Avengers are only available by adding the Craftworlds CAT as a child force.
https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions
