### ISSUE TITLE
Imperium - Astra Militarum: Valkyrie Power Level incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2718]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Small problem with the power level cost of three valkyrie's, should be 23 (8+15) not 31 (8+8+15).

**Comment by alphalas** [comment]
![2044f625-cd4f-4f35-a1cb-74fe9b087216](https://user-images.githubusercontent.com/15703066/37873508-3cb69e68-2fec-11e8-8569-dc0ba38c440c.jpeg)

**Comment by GenWilhelm** [comment]
@alphalas that's exactly what anon is saying. A unit of Valkyries is 8 power, plus 15 for an additional 2 models, which adds up to 23. In the catalogue it gives 31.

![31 pl](https://user-images.githubusercontent.com/22036809/37874145-2ed4e072-3021-11e8-8b71-30eee1046512.png)

**Comment by alphalas** [comment]
closed by d2032b3
