### ISSUE TITLE
Imperium - FW Adeptus Astartes: Salis Alberec keywords issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2721]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.09

**Platform:** Mac

**Dropbox:** Yes

**Description:** captain salis alberec is listed as part of the Executioners chapter alone with his rites of battle. However in the FW book he is listed as part of the exorcist Chapter

**Comment by Crowbar90** [comment]
Probably it's an oversight from when I refactored some things. I'm going to
fix it as soon as possible (before the end of today anyway).

Il lun 26 mar 2018, 01:16 BSDataAnon <notifications@github.com> ha scritto:
