### ISSUE TITLE
Armiger Warglaive Point Vlaue

### ISSUE THREAD

**Issue by jgood3653** [BSData/wh40k#2726]
Imperial Knights

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Incorrect point value listed at 227, correct value should be 223

**Comment by skonk** [comment]
223 + 4 points for the Heavy Stubber = 227 points.

**Comment by jgood3653** [comment]
Oh wow thank you I'm being dumb
