### ISSUE TITLE
DKK Malcador Autocannon Costs incorrect

### ISSUE THREAD

**Issue by plaguedroneofblight** [BSData/wh40k#2727]
**File/Catalogue:**  Astra Militarum Death Korps of Krieg

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The Autocannons on the Malcadors should be 12pts each, not 15.

**Comment by skonk** [comment]
If it uses the standard "Autocanon" then it has indeed been changed to 12 points in Chapter Approved.

![image](https://user-images.githubusercontent.com/621514/37968494-326f7890-31c6-11e8-836b-2829d3c95191.png)

**Comment by plaguedroneofblight** [comment]
It uses the generic Forgeworld Astra Militarum points values from CA (not the DKK list one), but that is also 12pts, so yep!
