### ISSUE TITLE
Imperium - FW Adeptus Astartes: Relic Contemptor Dreadnought Melee Points

### ISSUE THREAD

**Issue by JPEGtheDev** [BSData/wh40k#2732]
**File/Catalogue:** Imperium - FW Adeptus Astartes: Relic Contemptor Dreadnought

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** When selecting two of the same melee weapons (combat weapon / chainfists), the points values are reduced for each of the weapons. I didn't see any special rules about this.

![image](https://user-images.githubusercontent.com/7024087/38027490-d3f8d534-325d-11e8-9815-cd0d23e2c2b6.png)

![image](https://user-images.githubusercontent.com/7024087/38027504-e1fa94ec-325d-11e8-8da3-c0dc28160043.png)

![image](https://user-images.githubusercontent.com/7024087/38027552-ff83ca2e-325d-11e8-8445-4bb5fdef1dc0.png)

**Comment by GenWilhelm** [comment]
It's from Chapter Approved 2017 (p120).

![ca2017](https://user-images.githubusercontent.com/22036809/38028558-2bef38d2-328b-11e8-8da1-0523d720271e.png)
