### ISSUE TITLE
Codex: Death Guard - Helbrute Explosion Radius Incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2741]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The explosion radius of the Helbrute should be 3 inches and not 6 inches :)

**Comment by Mad-Spy** [comment]
This was actually wrong in all of the Heretic Astartes catalogues! Now fixed.
