### ISSUE TITLE
Astra Militarum Codex: Earthshaker Battery Cost Wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2750]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Point cost for the Earthshaker Battery in Battlescribe does not match value in the official Imperial Armour book.

Point cost in Battlescribe for Earthshaker Battery is 3PL, 115 pts. Indicated value in Imperial Armour is 3PL, 80 pts.

**Comment by alphalas** [comment]
Please consult Chapter Approved 
![0e7cbcf3-ef4a-4893-ab5f-b6496d63fca7](https://user-images.githubusercontent.com/15703066/38173319-5f67167e-358a-11e8-8030-be285ea116fa.png)
