### ISSUE TITLE
Death Guard Codex: DG Daemon Prince can't take relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2754]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Daemon Prince can't be given relics in a death guard detachment even though he is not a named character and is the warlord with the death guard keyword.

**Comment by Mad-Spy** [comment]
Fixed in #2724
