### ISSUE TITLE
Astra Militarum Codex: Constript cost wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2756]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.01.30

**Platform:** Windows

**Dropbox:** No

**Description:** Conscript value should be 3 points per unit. Not 4.

**Comment by alphalas** [comment]
Consult Chapter Approved 
![e2da77fd-928d-43c8-bb0e-ad3b90e079cb](https://user-images.githubusercontent.com/15703066/38198238-f3bea4a2-3659-11e8-8eae-921f12a44d88.png)
