### ISSUE TITLE
Imperium Dark Angels Codex: Incorrection Options for Space Marine Scout Bike Sergeant

### ISSUE THREAD

**Issue by timbrown81** [BSData/wh40k#2757]
Imperium Dark Angels Codex

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**  The datafile for Scout Biker Sergeant allows for invalid wargear.   It is allowing combi weapons, but should only permit pistols and melee weapons.

From the codex: "The Scout Biker Sergeant may replace his bolt pistol with an item chosen from the Melee Weapons or Pistols lists."

**Comment by Kohato** [comment]
Per Index Imperium 1, Bike Sergeants can take an item from the Sergeant equipment list, which includes combi-weapons.  Per the Designer commentary, since the Biker Sergeant can use that equipment via the index datasheet even though the codex datasheet doesn't allow it, this is a valid combination.
