### ISSUE TITLE
Ynnari Corsair Reaver + Skyreaver Felarch weapon options show an extra nonremovable lasblaster

### ISSUE THREAD

**Issue by stwyde** [BSData/wh40k#2758]
**File/Catalogue:** Aeldari Ynnari

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Mac

**Dropbox:**No

**Description:** Corsair skyreavers and reaver band Felarchs can remove their lasblaster under the normal Corsair detachments but the Ynnari entries just start off with two lasblasters, with only one being replaceable with weapon options. 

You can't actually replace one lasblaster, meaning you can also end up having the Felarch with voidsaber, lasblaster, and shardcarbine without raising any issues, while paying double the points cost if you just wanted to field a felarch with lasblasters.

<img width="570" alt="screen shot 2018-04-02 at 9 28 44 am" src="https://user-images.githubusercontent.com/2429548/38199995-4a64d97c-3658-11e8-8fe1-169fe2fac4bd.png">

**Comment by FarseerVeraenthis** [comment]
This is deprecated because the data has been removed from the Ynnari CAT to make the CAT easier to maintain accurately.
https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions
