### ISSUE TITLE
Battlescribe: Selections cause choices to vanish

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2774]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** every time i try to choose a legion for any of my units(ie Slaanesh,Khorne,Nurgle,Tzeentch) the unit gets removed from my list.

**Comment by Kohato** [comment]
This is a known bug in 2.01.10 for desktop. We're bringing it to @Jonskichov 's attention.

**Comment by GenWilhelm** [comment]
This has been hotfixed. You'll probably have to manually update, as it's still 2.01.10.
