### ISSUE TITLE
New unit: Termite assault drill

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#2779]
New unit release by forgeworld.

Has 40k rules for heretic astartes and adeptus astartes  in pdf format, see « download » tab in link bellow

https://www.forgeworld.co.uk/en-WW/Terrax-Pattern-Termite-Assault-Drill-2018?utm_campaign=7f0730a293-FW_6th_April_Termite_Assault_Drill&utm_source=forgeworld.co.uk&utm_medium=email&utm_term=0_a6ef0a01da-7f0730a293-118376921

Progress tracker:

- [x] FW Heretic Astartes
- [x] FW Adeptus Astartes

**Comment by Mad-Spy** [comment]
Added in FWHA v18.
