### ISSUE TITLE
Hellforged Dreadclaw points value

### ISSUE THREAD

**Issue by Somefingguyidfk** [BSData/wh40k#2781]
**File/Catalogue:** Chaos - FW Heretic Astartes v17 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** The Hellforged Dreadclaw Drop Pod has it's cost listed as 130pts instead of 200pts.

**Comment by skonk** [comment]
It had it's points reduced in Chapter Approved (along with many many other units).
