### ISSUE TITLE
Aeldari - Drukhari: Warlord Traits in mixed detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2786]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When the Detatchment Attribute option is set to “None (Mixed Detachment”, the Warlord Trait options are ignoring the <Kabal>, <Wych Cult> and <Haemonculus Coven> Keywords, and as a result are showing all traits as selectable options.

As an example:
An Archon is a <Kabal> Unit, and should only see Warlord Traits from the Kabal Warlord Table, but BattleScribe is showing all warlord trait options.

**Comment by jasarien** [comment]
I made a mistake when reporting this by putting the keywords in < and > and they’ve not shown up in the description. It should have read:

> When the Detatchment Attribute option is set to “None (Mixed Detachment”, the Warlord Trait options are ignoring the ‘Kabal’, ‘Wych Cult’ and ‘Haemonculus Coven’ Keywords, and as a result are showing all traits as selectable options.
> 
> As an example:
> An Archon is a ‘Kabal’ Unit, and should only see Warlord Traits from the Kabal Warlord Table, but BattleScribe is showing all warlord trait options.
