### ISSUE TITLE
Aeldari - Drukhari: Misc Profile Updates

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2788]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Necrotoxin missiles type should be changed from Assault D6 to Assault 3D3.
- [x] Huskblade strength should be changed from User to +1.
- [x] Darklight Grenades should be renamed to Plasma Grenades.
- [x] Roster displays Ynnari rules when Ynnari is not selected as Detachment Attribute.

**Comment by AzhekAhriman** [comment]
To add a few more profile mistakes on to this.

* Glimmersteel Blades for Mandrakes need -1 AP
* All 2+ Poison weapons need the wording updated to reflect the new "Add 2 to wound" that those weapons use now in the codex
* Grisly Trophies and Chain Snares appear to have blank profiles currently

**Comment by Vailex** [comment]
Grotesques should be 4 wounds
