### ISSUE TITLE
Drukhari: Incorrect Ranged Weapon Choices on Archon

### ISSUE THREAD

**Issue by jasarien** [BSData/wh40k#2790]
File: Aeldari - Drukhari.catz

BattleScribe version: 2.01.14

Platform: iPhone / iPod / iPad

Dropbox: Yes

Description: The ranged weapon choices for Archon include a Blaster, but this is not a valid option in the codex.

**Comment by WindstormSCR** [comment]
It is as per the Designer Commentary, see #1414

**Comment by jasarien** [comment]
Ah, I see. Thanks
