### ISSUE TITLE
FW Tantalus missing

### ISSUE THREAD

**Issue by IdleMuse** [BSData/wh40k#2793]
**File/Catalogue:** Drukahri v1.1.31

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The Forge World super-heavy Tantalus seems to be missing (or hidden) in this initial release.

**Comment by GenWilhelm** [comment]
It's not a super-heavy, it's just a regular heavy support unit. I can see it there correctly, can you confirm this is where you're looking?

**Comment by IdleMuse** [comment]
For some reason I had memorised it as a Lord of War, to the extent I didn't bother to check... my apologies!

All good, major thanks to all contributors for getting the release out so fast.
