### ISSUE TITLE
Imperium - Astra Militarum: Unable to select Vostroyan relic

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2794]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi, playing Vostroyan Firstborn and it seems the Regiment relic is missing, in rosters that already have it equiped to a character it shows as a error and lists it as hidden.

**Comment by alphalas** [comment]
Did you select the Vost regiment from the regiment selector in the no force org slot selector?
