### ISSUE TITLE
REFERENCE: Drukhari - Units Not Showing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2796]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** I am attempting to use the latest edition of BattleScribe for the Drukhari army and it is not loading properly. I cannot see any unit choices when I load multiple detachments, the first detachment works fine but then the others show no unit entries at all.

**Comment by WindstormSCR** [comment]
Some logic adjustments have been made that will show units when detachment attributes are not selected
