### ISSUE TITLE
Drukhari- Prizes from the Dark City stratagem 

### ISSUE THREAD

**Issue by Deefurdee** [BSData/wh40k#2803]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Deefurdee** [comment]
The option to take multiple artifacts via the Prizes from the Dark City stratagem is not yet present in the ‘No Force Org Slot’ area.

**Comment by WindstormSCR** [comment]
Already Fixed in #2802 , Release pending
