### ISSUE TITLE
Drukhari - Roster not Valid if you add Warlord traits to Succubus / Heamonculus after Taking Archon

### ISSUE THREAD

**Issue by erbarratt** [BSData/wh40k#2805]
**File/Catalogue:**  v1.1.31

**BattleScribe version:** v2.01.10.101

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

When choosing an Archon, can there be an option to allow taking a Warlord Trait for up to 1 Haemonculus and 1 Succubus, as per the Alliance of Agony Strategem?

At the moment, you have to note both the Haem and Succ as Warlords to include it in the Roster output, which in turn makes the Roster not valid as there is then "Too many Warlords".

**Comment by WindstormSCR** [comment]
Already fixed in #2802 , release pending
