### ISSUE TITLE
BattleScribe: Duplicated units behave collectively

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2807]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Duplicating a Troops of Neophyte Hybrids makes the new Unit unchangeable for Shotgun/Lasgun/Special Weapon/Heavy Weapon/Weapon Team options. All Options will only apply on the first unit, independent of which one is selected.

**Comment by GenWilhelm** [comment]
Huh, looks like a weird bug in BattleScribe itself, as it's also happening in other catalogues (eg. IG Veterans, SM Scouts). Saving and reloading the roster appears to resolve the issue, so I would recommend doing that if you see this behaviour again before the next BScribe update.

**Comment by Kohato** [comment]
Hotfix is out.
