### ISSUE TITLE
Hellforged Contemptor's Chainclaws are priced incorrectly when paired

### ISSUE THREAD

**Issue by WarmasterWyatt** [BSData/wh40k#2815]
**File/Catalogue:** 
FW Heretic Astartes V16
**BattleScribe version:** 2.01.10

**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No

**Description:** Detailed issue description.
When equipping the Hellforged Contemptor Dreadnought with a Chainclaw on each arm, it drops each Chainclaw in cost from its base 45 to 27.5 points, making the pair only cost 55 points instead of 90.

**Comment by skonk** [comment]
![image](https://user-images.githubusercontent.com/621514/38510476-266bcb5a-3c1d-11e8-9340-28bd959d4ac5.png)

please consult your copy Chapter Approved for up to date points costs.
