### ISSUE TITLE
T'au - About Multi-tracker wording.

### ISSUE THREAD

**Issue by TKerrygan** [BSData/wh40k#2816]
**File/Catalogue:** Warhammer 40,000 v1.1.32

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** In the T'au army selection, the Multi Tracker wargear reads: "a model equiped with a multi-tracker can re-roll hit rolls of 1 if it is firing all of its weapons at the same target."

But that's the old description. In the new Multi-Tracker, to obtain the bonus the target unit must have 5 or more models.

The codex Multi-tracker: "Re-roll hit rolls of 1 in the SHooting phase for a model eqquiped with a multi-tracker if it fires all of its weapons at the same target and that target contains 5 or more models."

That's it.
Thank you for your work.

**Comment by amis92** [comment]
It's a low impact bug, I'll include it in FAQ update.
