### ISSUE TITLE
T'au - Ke'lshan Sept

### ISSUE THREAD

**Issue by BFT9000** [BSData/wh40k#2822]
File/Catalogue: Warhammer 40,000 v1.1.31

BattleScribe version: 2.01..16

Platform: Windows/iOS/Android/Mac/Linux

Dropbox: No

Description: I'm wondering if it's possible to add the ke'lshan sept to the sept choices? Shas'o R'alai is currently the only model that takes that sept automatically, but ke'lshan does not currently have any rules associated with it.

**Comment by amis92** [comment]
Yes, most certainly a nice improvement. I'll add this when doing the FAQ update, along with a more strict restriction system on SEPT-specific wargear, characters, rules etc.
