### ISSUE TITLE
Mechanicum: Taghmata missing Power Fist stats on Ursarax Cohort

### ISSUE THREAD

**Issue by eaxexe** [BSData/wh40k#2823]
**File/Catalogue:** Mechanicum: Taghmata Army List v65

**BattleScribe version:** 2.01.10

**Platform:** Mac

**Dropbox:** Yes

**Description:** When adding Power Fists to an Ursarax Cohort, in a Taghmata Omnissiah, Crusade, list, I am missing the stat-line for their Power Fists.

The Power Fists are also missing under "Weapon"

**Comment by Kohato** [comment]
This repo is for 40k - You'll want to repost this in the HH repo: https://github.com/BSData/horus-heresy
