### ISSUE TITLE
Drukhari - Haemonculus weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2826]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Haemonculus now comes with a stinger pistol equiped not a shard pistol, and has no option to take the shard pistol.

This means haemonculus can't take the parasite kiss relic

**Comment by Mad-Spy** [comment]
Index weapon options are still valid as per the Designer's Commentary, see #1414 .
