### ISSUE TITLE
Aeldari - Drukhari: Haemonculus is unable to select a Warlord Trait

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2829]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Haemonculus no longer can select their warlord trait

**Comment by OxidizedIron** [comment]
Issue occurs on the Windows Desktop platform as well, v23
