### ISSUE TITLE
Drukhari Combat Drugs Selector

### ISSUE THREAD

**Issue by AzhekAhriman** [BSData/wh40k#2834]
**File/Catalogue:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [ ] Wych Cult Units could use a clickable button for Combat Drugs if it isn't too difficult to add

**Comment by erbarratt** [comment]
This would be fantastic!

**Comment by WindstormSCR** [comment]
This is now implemented including the correct interaction with the Stimm Addict warlord trait, and will validate up to a maximum of 18 Selections.
