### ISSUE TITLE
Drukhari - Lilith/Urien as valid alliance of agony targets

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2835]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** When selecting the stratagem "Alliance of Agony" the rules state that Lelith Hesperax has the Succubus keyword, making her a valid target for one of the extra warlord traits. The data file in Battlescribe does not assign her the Succubus keyword and therefore does not allow you to select a warlord trait for her unless you actually select her as your warlord. The data file should be updated to include the Succubus keyword for Lelith and allow you to select Blood Dancer as a warlord trait when using the Alliance of Agony stratagem.

**Comment by WindstormSCR** [comment]
Not how the logic works on the backend, but I see your point. Will fix with next DE batch.
