### ISSUE TITLE
Chaos - Chaos Space Marines: Problems with Psychic Powers on DPs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2842]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** You cannot choose psychic powers for daemon princes until you have selected a "Warlord". Not sure if this is this an intentional interaction?

**Comment by Mad-Spy** [comment]
I am unable to replicate this issue. Psychic powers are selected by clicking on the chosen Allegiance after selecting one which allows psychic powers. There is no interaction with selecting a warlord in any way.
