### ISSUE TITLE
Ratlings Points Change

### ISSUE THREAD

**Issue by OmalleyAI9** [BSData/wh40k#2847]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** 
Due to chapter approved Ratlings are now 7pts per model not 9

**Comment by Mad-Spy** [comment]
You are correct. They are 7pts each, plus 2 for their sniper rifle. 9 pts in total as per the datafile.

**Comment by OmalleyAI9** [comment]
Haha i know. Ill keep you updated with anything else. You guys are doing an
awesome job with the datafiles. Thanks
