### ISSUE TITLE
Space Marines - Razorback wrong weapon choices and points

### ISSUE THREAD

**Issue by Emuyen** [BSData/wh40k#2855]
**File/Catalogue:** Warhammer 40,000 v.1.1.33 / Imperium - Space Marines v44

**BattleScribe version:** 2.01.10.101

**Platform:** Windows/Android/

**Dropbox:** Yes

**Description:** Detailed issue description.
The weapon choices and points are wrong (I think still 7th edition).

Correct values:
Base Model: 65 points (wrong in DB)

Armament:
A Razorback is a single model equipped with a twin heavy bolter.
- Hunter-Killer missile: 6 points (correct in DB)
- Storm bolter: 2 points (correct in BS)
- Twin assault cannon: 35 points (wrong in DB)
- Twin heavy bolter: 17 points (correct in DB)
- Twin lascannon: 50 points (correct in DB)

- delete Lascannon & Twin Plasma cannon
- delete Twin heavy flamer

Wargear option:

- This model may replace its twin heavy bolter with a twin lascannon or a twin assault cannon.
- This model may take a hunter-killer missile.
- This model may take a storm bolter.

Abilities:
correct in DB

**Comment by Kohato** [comment]
Please refer to the following items:

- Chapter Approved 2017
- Designer's Commentary

Points change yearly according to Chapter Approved and our data reflects that.
Wargear options not present in the codex, but still present in the index are retained as they are legal choices.

**Comment by Emuyen** [comment]
thank you very much!

2018-04-15 16:45 GMT+02:00 Earl Bishop <notifications@github.com>:
