### ISSUE TITLE
No Daemons for CSM armies

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#2861]
Chaos Space Marines list currently has no way of adding the CSM book daemons to the roster, since the Legion Trait selection seems to block anything non-LEGION, and there is no option for not picking a legion trait.

Three of the four Daemon units in the CSM codex are NOT the same as the ones in the CD codex (Horrors are due to bad GW errata but I assume that will be fixed soon), so need their own entries.

**Comment by Mad-Spy** [comment]
Please see #2445. We made the decision to remove them to help avoid confusion for users. Having them in the CSM catalogues made it too easy for users to mistakenly make invalid "Chaos Space Marine" detachments by including Daemons. 

You can still add Daemons to a CSM army by adding a child detachment.

**Comment by Mad-Spy** [comment]
I have read your feedback and given you the reason why we made the decision we took. I'm sorry that you don't agree with it. Everyone's feedback is welcome, and we have made changes based on your feedback previously (including #2858, which we have just been conversing on).

There is nothing to stop you making the army you want. As I have explained, you can add additional or child detachments to add Daemons to your roster and then build your army however you want.

Following GW's FAQs, there is no functional difference between the CSM and Daemon versions of the daemon units. All keywords and abilities are the same, and the clear intention is that they should be the same units. As such, there is no reason to duplicate them.

**Comment by BaconCatBug** [comment]
Sorry, but this is not true in the slightest. GW's FAQ explicitly makes the DAEMON Faction Keyword important. I can't use Daemon Stratagems on CSM Daemons. Their Keywords are NOT the same. The CSM Ones have the DAEMON Keyword, and the Chaos Daemons one have the Faction Keyword DAEMON.

**Comment by Mad-Spy** [comment]
The DAEMON keyword issue was fixed in version 1.2 of the CSM Codex FAQ on 22/01/18.

**Comment by Kohato** [comment]
@BaconCatBug - you can most definitely make the legal army you want.  It simply loses legion traits. For assistance in making multiple catalog detachments, please read through: https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions

You can continue to show up and insult the author base as much as you want, but like the child throwing a tantrum over candy he did not get, it won't make a difference.
