### ISSUE TITLE
Interim/big FAQ - T'au updates

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#2867]
Per the Official Update Version 1.0: https://whc-cdn.games-workshop.com/wp-content/uploads/2018/04/warhammer_40000_tau_empire_en.pdf

* [x] Remove Stimulant Injector option
* [x] Cyclic Ion Blaster ability change
* [x] Dal'yth Sept ability change
* [x] Add Knarloc Riders and Great Knarloc datasheets from IA: Index Xenos FAQ
* [x] Add constraint to Coldstar Weapons choice (MissilePod min 1 if HOBC taken)

**Comment by joarangoe** [comment]
Please add the ColdStar equipment changes. RAW you cant drop the Missile Pod without droping the HOBC. So you can equip 4 items from the ranged weapons/support sistems or HOBC+Missile Pod+2 items from the ranged weapons/support systems.
