### ISSUE TITLE
Astra Militarum -- Master of Ordnance Warlord Trait

### ISSUE THREAD

**Issue by Salrantol** [BSData/wh40k#2869]
**File/Catalogue:** Astra Militarum v109 

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Master of Ordnance is a \<Regiment> Character, so he should get access to Codex Warlord traits, not just BRB Warlord traits.

**Comment by Mad-Spy** [comment]
Looks like the Master of Ordnance is linked directly to the BRB Traits rather than the "Warlord Traits" SSEG.

**Comment by alphalas** [comment]
Yes - which is how the astropath is; I had forgotten the MoO *is* REGIMENT while Astropath and MoF are not; because you have to be REGIMENT to use guard WLTs. Will fix
