### ISSUE TITLE
Thousand Sons DP Incorrect Upgrade

### ISSUE THREAD

**Issue by Asuryun** [BSData/wh40k#2871]
**File/Catalogue:** Chaos - Thousand Sons

**BattleScribe version:** 2.01.14

**Platform:** iOS

**Dropbox:** No

**Description:** Thousand Sons data file lists Warp bolter as an option for a Daemon Prince of Tzeentch but codex does not provide bolter as an option for a Thousand Sons prince and no FAQs have changed this.

**Comment by Mad-Spy** [comment]
It is unclear as to whether a model which was previously being used as a Daemon Prince under the Index rules (which allowed a Warp Bolter), and is now being used as a Daemon Prince of Tzeentch under Codex rules is still allowed to take a Warp Bolter based on the Designer's Commentary.

As such, the option has been included until GW clear it up.
