### ISSUE TITLE
Imperium - Grey Knights: Issues with Brotherhood Ancient artefacts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2875]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The Grey Knight Brotherhood Ancient isn't able to add an artifact unless it is your warlord. This is incorrect as it is a character, it should be able to take an artifact. Also, when the Brotherhood Ancient is made your warlord, the warlord traits don't come up.

**Comment by Mad-Spy** [comment]
Unable to reproduce this in v18.

If I select any warlord, the Artefacts appear for the Brotherhood Ancient. I can also see the Warlord Traits when I select it as a Warlord.
