### ISSUE TITLE
Drukhari FAQ Changes

### ISSUE THREAD

**Issue by erbarratt** [BSData/wh40k#2876]
**Talos and Cronos, Keywords** 
Add ‘Fly’

**Kabal Obsessions, Slay From the Skies Change the penultimate sentence of rules text to read:** 
‘In addition, enemy units do not receive the benefit to their saving throws for being in cover against attacks made by models with this obsession that can Fly, or by models with this obsession that are embarked upon a Transport with this obsession that can Fly.’ 

**Alliance of Agony Add the following sentence:**
‘You can only use this Stratagem once per battle.’

**Labyrinthine Cunning Change the rules text to read:**
‘Whilst your Warlord is on the battlefield, roll a D6 each time you or your opponent spends a Command Point to use a Stratagem; you gain one Command Point for each roll of 6.’

**Comment by WindstormSCR** [comment]
Already Fixed in merged changes
