### ISSUE TITLE
Relic Leviathan Dreadnought incorrect points values

### ISSUE THREAD

**Issue by Navhank** [BSData/wh40k#2877]
**File/Catalogue:** Imperium - FW Adeptus Astartes v23

**BattleScribe version:** 2.01.10

**Platform:** Linux

**Dropbox:** No

**Description:** I'm not sure if this is the right place to put this, but I've found some erratas on the points values for the Relic Leviathan Dreadnought weapons:

-> Grav-Flux bombard 65 pts (should be 50)
-> Leviathan Siege Claw 55 pts when single one, 32.5 when pair (should be 55 pts always)
-> Leviathan Siege Drill 65 pts when single one, 37.5 when pair (should be 65 pts always)

Thanks in advance,
Navhank

**Comment by WindstormSCR** [comment]
Please see your copy of chapter approved where these were updated
