### ISSUE TITLE
Drukhari Bugs

### ISSUE THREAD

**Issue by superdefra** [BSData/wh40k#2887]
- [x] Talos 4 attacks instead of 5.
 - [x] Chain-flails label wrong, says re-roll wounds, it needs double attacks instead.
 - [x] Shardnet-Impaler missing label of rolling a D3 for the opponent.
I'll write if I find more

**Comment by GenWilhelm** [comment]
Drukhari v26 went out this morning, so some of this may have already been fixed.

**Comment by FearMyLazorFace** [comment]
not a bug per se, but for Lelith, if she is chosen as your warlord, she must take the blood dancer trait, similarly, Drazhar must have Hatred Eternal, and Urien zrakarth must have Diabolical Soothsayer
