### ISSUE TITLE
Inconsistent Squad Sergeant weapon behaviour (Plus Dark Angel bug)

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#2902]
Dark Angels v54, Blood Angels v42 and Space Marines v44

The behaviour of Squad Sergeants for the various Space Marine flavours (Cool Original, Dark Angels and Blood Angels) is inconsistent and different for each of them. This is despite each Tactical Squad entry having identical rules and the Sergeant Equipment lists having the same format of being split into a "Take 2" and "Take 1" section.

- [x] Vanilla Space Marines have no weapons equipped by default and must select them individually (incorrect from a rules standpoint and annoying)
- [x] Blood Angel Marines have the Default Wargear as a checkbox, followed by two lists of 1 Handed and 2 Handed Equipment
- [ ] Dark Angel Marines have each "armament" instead split into two sections, a Bolt Pistol Checkbox (with a redundant Bolt Pistol entry underneath it) and a Bolter Checkbox (with a redundant Bolter entry underneath it)
- [ ] Furthermore, the Dark Angels selection allows for the selection of two weapons from the "Take 1" list, with no validation error.

I would like to propose that all Space Marine Sergeant entries of this nature be standardised to the format used by the Blood Angels sergeants, as this is the format that most correctly fits the rules found in the codex and is the most user friendly format.

**Comment by Thairne** [comment]
The problem I see with this approach is that we have to abort our current principle of "maintainer has the right to implement as he sees fit". We'd create a precedence which then would cause a) inconsistencies in the behavior in the cat itself between sergeant and other units and b) we'd need to implement fixed guidlines on how things need to be done in detail from an UX perspective.
Objectively the better solution, but a load of work for every maintainer and nothing short of a rework for a lot of entries in a lot of cats.

**Comment by BaconCatBug** [comment]
I get this is a volunteer project, but that's not an excuse for sloppiness imho. There should be a standard for things like relic validation, identical units between armies, etc.

**Comment by Thairne** [comment]
There isn't and there hasn't been since the inception of this whole data thing.
Adding such standards simply is a non trivial task.

I'm not arguing against the change, I'm simply pointing out the consequences. And with consequences on this scale, everyone needs to be on board.

**Comment by OftKilted** [comment]
If all implementations allow you to select the associated weapons for the unit then all solutions are valid.

If all solutions are valid then we must, as a group, rely on the Wiki Guidelines [https://github.com/BSData/wh40k/wiki/Guidelines](https://github.com/BSData/wh40k/wiki/Guidelines ) (specifically number 11). 

As volunteer implementers, each implementer provides a solution to the question of 'How do we make the list work, and allow someone to create their list.' 

Individual implementations may be initial creations, and then eventually refined. Some other implementations may have been built on the prior work, and others may be home grown at the volunteers prerogative. 

If a solution works, then that will often be used. Unfortunately, we don't have staff to ensure an 'explicit' standard, and as we're all volunteers we all have different knowledge and experience levels.  With the large number of catalogs, a limited group of maintainers, and catalogs that are often completely different from a wording perspective to other catalogs. What can work for one situation. Won't for another. We would almost spend more time generating exceptions than providing you a solution that allows you to create that list.

Again, thanks for getting that this is a volunteer project. But remember to keep in mind Guideline number 11, and that a 'SHOULD' is not a 'MUST'.

Please do keep submitting issues for actual bugs. Just remember that implementations of a solution, if the end result in the listbuilder provides a valid result, are unique creations of each individual volunteer.

**Comment by amis92** [comment]
@flakpanda can you update the checklist in OP? I'm not sure how your commit changed these tasks.

**Comment by amis92** [comment]
@WindstormSCR closing without commit reference or resolution label? What's the status here? Checklist is not completed.

**Comment by WindstormSCR** [comment]
Flak fixed his cat without a commit reference, my understanding is that @thairne was in the "won'tfix" camp because his implementation is valid but slightly different
