### ISSUE TITLE
Kataphron Breachers Heavy Arc Rifle Wrong Cost

### ISSUE THREAD

**Issue by virl** [BSData/wh40k#2903]
**File/Catalogue:** Imperium v8

**BattleScribe version:** 2.01.10.102

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:**
Adeptus Mechanicus Kataphron Breachers have wrong cost for Heavy arc rifle: 6 pts instead of correct 8 pts.

**Comment by WindstormSCR** [comment]
Please acquire a copy of Chapter Approved 2017 where this was updated.
