### ISSUE TITLE
Astra Militarum: Platoon Commander weapon choice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2911]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Astra Militarum Platoon Commander validation says it must have a selection from the Chainsword group.
The datasheet says the chainsword or another melee item _may_ be taken.

The Platoon Commander should have an option to take no melee weapon if desired.

**Comment updated by @mad-spy for clarity.**

**Comment by Mad-Spy** [comment]
Although the OP is correct, given that a chainsword costs 0pts, I don't know why you'd ever choose not to take one.

**Comment by BaconCatBug** [comment]
That's not the point. It's not taken by default and it's not mandatory. The datafiles should reflect the rules, not what the contributors think the rules should be.
