### ISSUE TITLE
Space Marine Codex: Thunder Fire Cannon Display Bug

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k#2914]
The Thunder Fire Cannon Does not display as Bold Like the Land Raider or other units in the supplied picture does. See Pic for Reference.

![battlescribbug](https://user-images.githubusercontent.com/13488231/39005108-3a3c995e-43cd-11e8-9f04-351a36b0ded2.jpg)

**Comment by rsochia** [comment]
It makes it harder to find it in your Roster when you are scrolling.

**Comment by alphalas** [comment]
it's because it has no sub-options. The bold indicates there are further options. it's a BS thing, not a data thing.
