### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Incorrect cost for Commissar

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2915]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** The Death Korps Death Rider Commissar only costs 35pts after the recent FAQ. He still costs 50pts in Battlescribe. Please fix! Thanks in advance

**Comment by CrusherJoe** [comment]
The DKDR Commissar is 35 points in v54 of the datafile.

**Comment by steelysteve8** [comment]
Much appreciated
