### ISSUE TITLE
Imperium - Astra Militarum: Unable to select Vostroyan relic when Vostroyan regiment is selected.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2916]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** With the most recent update my imperial guard vostroyan company commander can't 
Take the heirloom armor specific to vistroyans

**Comment by CrusherJoe** [comment]
Same as #2973 which I closed earlier today.
