### ISSUE TITLE
Canoptek Wraiths options not right?

### ISSUE THREAD

**Issue by Mikle103** [BSData/wh40k#2918]
**File/Catalogue:** Necron.cat
**BattleScribe version:** 2.01.
**Platform:** Windows
**Dropbox:** No

**Description:** Canoptek Wraiths not sure if I am reading it right or wargear options are incorrect as was assembling my wraiths last night and they are armed with either claws or whips and either beamer or caster.

Hope this makes sense. 

That for every thing you guys do.

**Comment by Mikle103** [comment]
OK in the datafile you can only choose either whips, beamer, or caster all with claws or just claws?
But you can have 
- claws with beamer
- claws with caster
- whips with bearmer
- whips with caster 

CCWs are whips or claws
Missile Weapons are beamer or caster

Hope this clarifies

**Comment by Mikle103** [comment]
May need to wait for next FAQ as date card not very clear.

**Comment by Mad-Spy** [comment]
As you say, the data sheet isn't totally definitive of the options, but it would appear that Wraiths have claws by default and can then select _one_ of the additional options. Thus you cannot actually have whip coils and a ranged weapon, regardless of the actual way you can physically build the models.

It's possible to build many models with an invalid load out based on the box contents, so we can't take that as a indicator of their options.

**Comment by Mikle103** [comment]
I understand but cannot build with claws and whips it is either.

**Comment by amis92** [comment]
There's absolutely nothing unclear in the datasheet, sorry. Every Wraith has Vicious Claws and then:
![image](https://user-images.githubusercontent.com/2671396/39037963-6a7cac2a-4482-11e8-9e94-e91542553536.png)

The modelling options are in no way an indication of what a model can take, especially considering basic melee weapons.

As rules currently stand, Coils are simply the exact same weapon as Claws with an added special rule. My bet is they just didn't bother and took the easiest route for Wargear Options.

Closing as on our side everything is perfectly ok.

**Comment by Mikle103** [comment]
@amis92 thanks for clearing it up will have to wait for FAQ at this point as cannot physically build a wraith with both claws and whips.

Just my OCD as am a player from way way back and always try and do WYSIWYG.

Alas thems are the rules I will have to live with it.

Cheers and thanks again.
