### ISSUE TITLE
Warlord Traits not available for Space Marines

### ISSUE THREAD

**Issue by defconclown** [BSData/wh40k#2920]
**File/Catalogue:** 

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** Warlord traits do not display for Space Marines.

**Comment by WindstormSCR** [comment]
These display fine for me on v46. you have to select the sub-item that is added when you choose a character as warlord to select one (I'm guessing these were made a sub-option because there are so many)
