### ISSUE TITLE
Imperium: Astra Militarum Commissar and Lord Commissar points cost

### ISSUE THREAD

**Issue by steelysteve8** [BSData/wh40k#2924]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by steelysteve8** [comment]
Commissar and Lord Commissar are still at their old points cost of 30 and 50 respectively. FAQ updates them to 15 and 30 respectively.

**Comment by Mad-Spy** [comment]
Already fixed and will be in the next release.
