### ISSUE TITLE
New Shadowsword sponson options from FAQ.

### ISSUE THREAD

**Issue by Commisar** [BSData/wh40k#2929]
**File/Catalogue:** Astra Millitarum

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** There was a new FAQ added to [the most recent "Imperial amour index forces of the astra militarum"](https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/imperial_armour_index_forces_of_the_astra_militarum-1.pdf) as follows:

> Q: The classic Shadowsword model from Forge World has
two side sponsons, each with twin heavy bolters, but without
lascannons – is there a datasheet I should use for this unit?
A: Use the Shadowsword datasheet from Codex: Astra
Militarum. Replace the unit’s option for two or four
sponsons, each with a lascannon and twin heavy bolter
or twin heavy flamer, with ‘two sponsons, each with a
twin heavy bolter’.

As the owner of one of these venerable old tanks, it would be nice to have this option in battlescribe so I stop having to pay for invisible lascannons. Thanks!

**Comment by CrusherJoe** [comment]
Isn't this technically an "Arkurian Pattern Shadowsword"? I propose we add a datasheet named "Arkurian Pattern Shadowsword" and give it the options as specified in the FAQ. I own one as well (though I've upgraded the sponsons because MOAR LASCANNONS) and as far as I can tell, "Arkurian Pattern" is the correct name.

**Comment by CrusherJoe** [comment]
Okay -- after some offline discussion we decided to add another "datasheet" named "Arkurian Pattern Shadowsword" with the sponson options set forth in the FAQ. This will be in the next release of the datafile.
