### ISSUE TITLE
Orks: Meka-dread multiple updates required 

### ISSUE THREAD

**Issue by Dropfall** [BSData/wh40k#2932]
**File:** Ork.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Issue 1:** You should be able to take two Rippa Klaws without getting an error

**Issue 2:** Following things need to be changed in the unit entry to reflect changes in the FW IA Xenos Index FAQ.

> Change the first bullet point to read:
> ‘• The Meka-Dread may replace one of its rippa klaws
> with one of the following weapons: killkannon, big
> zzappa, shunta or ratler kannon.’
> 
> Change the second bullet point to read:
> ‘• The Meka-Dread must take one of the following:
> rokkit-bomms, two big shootas, the Mega Charga
> ability or a Kustom Force Field.’
> 

**Issue 3:** Rokkit-bomm [RAW Problematic] should have the points cost of 13 added so you can account for their cost when using them. FW aren't likey to  get around to fixing the RAW problem anytime soon.

**Comment by tag8833** [comment]
RE: issue 3
I think the RAW problems were that there was no way to legally take them.  Now that FW has made it a selectable piece of wargear I think the RAW problems are solved.
