### ISSUE TITLE
Supreme Command Detachment miss HQ and Elite slot.

### ISSUE THREAD

**Issue by MetalAdMech** [BSData/wh40k#2933]
BattleScribe v2.01.16
Warhammer 40000 v1.1.35
Imperial Knights v8

Supreme Command Detachment miss HQ and Elite slot. Can't choose them to add up the points, so list will remain unfinished...

**Comment by MetalAdMech** [comment]
Platform: Windows

**Comment by MetalAdMech** [comment]
Platform: Android

**Comment by radionausea** [comment]
Imperial Knights don't have HQ or Elites to put in those slots which is why they don't appear.
Add another faction to the shore command and those slots will appear

**Comment by Kohato** [comment]
As radion said, IK doesn't have Elite/HQ.  You will need to choose a cat that has those things.
