### ISSUE TITLE
Validation error with Ynnari

### ISSUE THREAD

**Issue by LordAmbiorix** [BSData/wh40k#2944]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Description:** Detailed issue description.
I don't understand that validation error I get, ¿can you explain it to me? 
![imagen](https://user-images.githubusercontent.com/38624044/39096603-882823d6-4652-11e8-99fb-8b28f0da09e9.png)
I followed the guide that you have explaining how to make multifaction armies, but it doesn't work.
I have an Ynnari warlord and I can't take that Detatchment type.

**Comment by WindstormSCR** [comment]
Ynnari must be the parent force for this validation to work. Still working on a workaround to make it so that it does not have to be.

**Comment by WindstormSCR** [comment]
@LordAmbiorix can you try this again, and set the harlequin detachment type to ynnari only AFTER setting your ynnari warlord? with the ynnari detachment as a child of the harlequin detachment.

it should function, its something to do with the order in which BS handles requirements updates.

**Comment by LordAmbiorix** [comment]
Okay, now it works fine, I think everything solved now :)
