### ISSUE TITLE
Chaos - Chaos Space Marines: Biker cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2946]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Hello! I noticed that the Chaos Space Marine Bikers are listed as 25 points per model, when in the FAQ 2017 their points have dropped to 23 points per model. Just thought I'd let you know! Thanks for your hard work, really love using battlescribe!

**Comment by Mad-Spy** [comment]
Bikers are 23 points per model. It sounds like you've forgotten to add the cost for their combi-bolter into your calculation,
