### ISSUE TITLE
Imperium - Astra Militarum - Arkurian Pattern Stormhammer Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2949]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.11

**Platform:** Windows

**Dropbox:** No

**Description:** ARKURIAN PATTERN STORMHAMMER
1) This vehicle has a lascannon in it's default loadout that is not reflected in the data.
2) The Co-Axial multi-laser weapon doesn't not appear in the list of weapons along with the admantium tracks, 6x multilasers/bolters/flamer/lascannon, stormhammer & twin battle cannon.

**Comment by CrusherJoe** [comment]
1. Fixed in v110 of data file.
2. I'm going to have to disagree with you on this one. It shows up as expected. 
![coax](https://user-images.githubusercontent.com/9998385/39398334-d0a0bde8-4ad1-11e8-92a6-21ab6de3392b.PNG)
