### ISSUE TITLE
Imperium - Blood Angels: Red Thirst

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2953]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** So there is no mention of red thirst anywhere. Codex says so long as you are battle forged infantry units get red thirst. I would think this would be included in "abilities" maybe and perhaps come with a description in every unit. Thanks for contributing. Cheers

**Comment by GenWilhelm** [comment]
It's in the rules section for every Blood Angels force, though it doesn't say which units benefit from it.

![rules](https://user-images.githubusercontent.com/22036809/39237694-1e2d8fe2-4874-11e8-963e-ad20b3da4b22.png)
