### ISSUE TITLE
Covenant of Chaos selectable with non-Warlord Renegade Commander

### ISSUE THREAD

**Issue by temporarrry** [BSData/wh40k#2954]
**File/Catalogue:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.11

**Platform:** Windows

**Dropbox:** No

**Description:** Currently you can select a Covenant of Chaos for any Renegades & Heretics detachment with a Renegade Commander as an HQ choice. This should only be possible if you both have a Renegade Command **and** that commander is your warlord as per this FAQ https://www.forgeworld.co.uk/resources/PDF/Downloads/40K_8th_ed_Update_Imperial_Armour_Index_Forces_of_the_Astra_Militarum_ver_1.0.pdf

**Comment by temporarrry** [comment]
Also I'm not sure how to properly report this type of issue so if this is incorrect my apologies.

**Comment by MountyChris** [comment]
I can't seem to get the warlord option to work for the renegade commander at all.

**Comment by Mad-Spy** [comment]
As there are no relics for R&H, there's no real need to actually denote which model is the warlord in a R&H detachment as there is no logic which requires it.

As with any list written in BS, it is up to the list builder to ensure their list is valid. Users are not forced to select a Covenant if they have a Renegade Commander.
