### ISSUE TITLE
Cyclic Ion Blaster Typo

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#2958]
**File/Catalogue:** T'au Empire v23

> If you roll one or more hit rolls of 1, **the bearer's unit suffers** a mortal wound after all of this weapon's shots have been resolved.

Should read

>If you roll one or more hit rolls of 1, **the bearer suffers** a mortal wound after all of this weapon’s shots have been resolved.

**Comment by amis92** [comment]
Unfortunately,
[![image](https://user-images.githubusercontent.com/2671396/39310626-2d45077e-496b-11e8-8a7d-949da096da83.png)](https://whc-cdn.games-workshop.com/wp-content/uploads/2018/04/warhammer_40000_tau_empire_en.pdf)

:shipit:

**Comment by BaconCatBug** [comment]
Yeah my bad, errata and all that.
