### ISSUE TITLE
Daemon Prince of Nurgle missing weapon option - Plague Spewer

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k#2959]
**File/Catalogue:** Death Guard v39

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** 

The most recent Codex Death Guard FAQ gives the Daemon Prince of Nurgle the option to take a Plague Spewer but this weapon option isn't currently available in the datafile.

**Comment by Mad-Spy** [comment]
This change was released last night. Please update your data files.
