### ISSUE TITLE
Imperium - FW Adeptus Astartes: Relic Unit Validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2961]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** elic dresdnoughts. I have a regular and a relic contemptor dreadnought in my list and it's telling me my list is invalid. The rules state I can have one reg and one relic. Relic: If your army is Battle-forged, no Detachment can contain more Relic units than it does non-Relic units of the same Battlefield. So why am I getting an error. It didn't do this till after the update

**Comment by GenWilhelm** [comment]
BattleScribe changed the way categories validate in the latest version, so the current implementation no longer works correctly.

**Comment by WindstormSCR** [comment]
This works fine on the current version (all platforms) as long as the FW detachment is the parent for a nested detachment?

**Comment by alphalas** [comment]
@WindstormSCR is correct, tested on PC and iOS.
