### ISSUE TITLE
Imperium - Space Wolves: Thunderwolf weapon choice issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2962]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** V35 of the Space Wolves. The Thunder Wolf cavalry entry does not have the option for dual Wolf Claws (or lightning claws) available. The whole unit has the option to take them.  To verify this go to the Index: Imperium 1 FAQ, on page 3, last entry in the right side column.

**Comment by CrusherJoe** [comment]
![twx](https://user-images.githubusercontent.com/9998385/39729452-8453a700-5221-11e8-9bb9-a99ed102d1e6.PNG)

...actually, yes, they do. You have to uncheck the bolt pistol and chainswords at the top of the option lists, but yes, you can take dual Wolf Claws with no issues.
