### ISSUE TITLE
Imperium - FW Elysians - Hellstrike Missiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2974]
**File:** Imperium - FW Elysians.catz

**BattleScribe version:** 2.01.11

**Platform:** Windows

**Dropbox:** No

**Description:** The 2x hellstrike missile is 60 pts and the 4x hellstrike missile is 120 pts. They should be 40 and 80 pts respectivelym as a single hellstrike missile is 20 pts on the valkyrie.

**Comment by CrusherJoe** [comment]
Unfortunately that's incorrect. Chapter Approved 2017, pg. 122 updated the cost of a Hellstrike Missile to 30 points each. The cost of "Hellstrike Missiles" on a Valkyrie remained (and remains) at 20 points.
