### ISSUE TITLE
Aeldari - Drukhari: Reaver Champion Can't Select Special Weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2987]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I can’t pick special weapons (e.g. blaster and grav-talon) to go on the Arena Champion instead of on regular reavers.

**Comment by FarseerVeraenthis** [comment]
![image](https://user-images.githubusercontent.com/23246922/39548688-493e19f6-4e53-11e8-9589-0d546417118a.png)

The Arena Champion can't take anything other than a Power Sword, or Agoniser, which is per the current setup of the CAT file.

**Comment by GenWilhelm** [comment]
The other options say "one model may...". Doesn't that mean anyone in the unit should be able to?

**Comment by FarseerVeraenthis** [comment]
Oh, good point... I'm not certain, is there precedence anywhere else?
