### ISSUE TITLE
pc issue

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k#2991]
**File/Catalogue:** 

**BattleScribe version:** 2.01.12

**Platform:** Windows
**Dropbox:** Yes/No

**Description:**Ive been recently remaking lists and one of the issues i ahve been having is when I go to make a list with two battallion detachments it always links them if they are the same faction on the pc version though it is still giving me the option of doing that or keeping them separate like I want on my tablet.

**Comment by Mad-Spy** [comment]
Make sure you re-select the "Roster" entry when adding forces, this will allow you to have them as separate detachments instead of child detachments.

![image](https://user-images.githubusercontent.com/29306451/39418494-a4e2f414-4c52-11e8-8af8-d2c91c970a4d.png)
