### ISSUE TITLE
Chaos - FW Heretic Astartes: Decimator points not updating correctly.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2995]
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Taking more than one weapon of the same type on a Chaos Decimator does not increase the points cost of the unit.

**Comment by Mad-Spy** [comment]
Looks like a recurrence of the Battlescribe bug where points for units in child detachments fail to get updated correctly. You will need to report this to Battlescribe, as it is not a problem with the data files.
