### ISSUE TITLE
Helbrute wargear 

### ISSUE THREAD

**Issue by WarmasterWyatt** [BSData/wh40k#3009]
![image](https://user-images.githubusercontent.com/38222500/39612190-2c8c41ba-4f2b-11e8-89e6-7d26cae887c6.png)

As per the new FAQ's and Erratas, Helbrutes can now have a power scourge on each arm, provided they have double fists. Im not sure how this factors in when points are calculated as there is the whole "No upgrading an upgrade" but ive heard that you just pay for the two scourges as it doesn't matter how you get to acquiring the final load out as long, you just pay for the final load out's options. I dont know. Any idea how this actually works?

**Comment by Mad-Spy** [comment]
This has already been implemented. My belief is that GW have just worded this badly and so you can just have any two melee weapons if desired, so that is how it has been implemented.

**Comment by WarmasterWyatt** [comment]
okay but currently there is no option for the second scourge. so i cant put it on my list. because each scourge adds +3 attacks, so a helbrute with 2 of them raises its attacks with those to 10, 11 for battering onslaught and 12 if it is a world eater and charges. So how would i do this in battle scribe when the second arm options are only Fist and all of its guns?

**Comment by alphalas** [comment]
It’ll be in the next release @warmasterwyatt

**Comment by WarmasterWyatt** [comment]
Excellent. Thanks for the timely response and sorry for the hassle

**Comment by Mad-Spy** [comment]
Oops, didn't realise the change hadn't gone out in a release yet! Sorry for the confusion.
