### ISSUE TITLE
Imperium - FW Death Korps of Krieg: List validation incorrectly requires multiple warlords

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3010]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** Hey fellas. Whenever I've got a list with multiple HQ slots taken up the program gives me a warning that I need to make them both warlords even after I've made one already.

**Comment by CrusherJoe** [comment]
Using v54 of the DKOK datafile I'm unable to reproduce this one.
