### ISSUE TITLE
Space Marine Named Characters have illegal Warlord Trait options

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#3016]
As per Page 199 of Codex Adeptus Astartes Space Marines, Named Characters must be given the Warlord Trait associated with their Chapter. Rowboat Girlyman is a named character, as per page 207 of Codex Adeptus Astartes Space Marines, and thus may only be given the Ultramarines Warlord Trait.

This bug also applies to all other Space Marine Named Characters.

Also note this also means they cannot take a Rulebook Warlord Trait, they MUST take the associated Chapter trait.

**Comment by Mad-Spy** [comment]
There are still issues with this, so I'm reopening it.
