### ISSUE TITLE
Imperium - Astra Militarum: Support Vehicle ability incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3017]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Trojan Support Vehicle - The description for the "Support Vehicle" rule is slightly different to what I've got in a digital copy of the index. The battlescribe rule says "may re-roll any failed rolls when making shooting attacks" while the IA Index says "may re-roll any failed hit rolls when making shooting attacks".
Which is it? I looked it up on google and it seems like perhaps GW bought out a digital version which isn't accurate to the printed version?

**Comment by CrusherJoe** [comment]
The rule reads: "During the Shooting phase, a single friendly <REGIMENT> VEHICLE within 6" may re-roll any failed hit rolls when making shooting attacks." according to my copy of IA:I:FotAM. I've updated the rule in the datafiles to represent this.
