### ISSUE TITLE
Deathwatch access to Anniversary Primaris Captain

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#3025]
**File/Catalogue:** Deathwatch

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** GW recently confirmed that the store anniversary marine (primaris cpt with power fist)  uses the Primaris Captain datasheet so is available to 'other' chapters - including Deathwatch. 

Please can you include this when you do codex upgrade.

Also Aggressor points are wrong in Deathwatch (right in space marine) when you do next update. .

Thanks in advance.

**Comment by MasterSlowPoke** [comment]
The Primaris Captain in the codex has access to the fist and pistol load outs, no worries.

**Comment by FarseerVeraenthis** [comment]
we'll get this included, like you say, with the Codex update :smile:
