### ISSUE TITLE
Necrons - Transcendent C'tan Random Personality

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#3027]
**File/Catalogue:** Necrons v24

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** Yes

**Description:**
If the random fractured personality option is selected for a transcendent c'tan, the list does not include a die roll table or the rules for each possible outcome.

**Comment by Kohato** [comment]
The checkbox for random personality simply allows you to select 2 at once in case you are using your list on a device rather than printed out.  In a proper setting, the correct way would be to use the reference table in "No Force Org" and roll at the start of the game.
