### ISSUE TITLE
CSM/DG/TS Daemon princes are eligible for Daemons Codex Relic

### ISSUE THREAD

**Issue by angelambrosio** [BSData/wh40k#3030]
**File/Catalogue:** Chaos Space Marine, Death Guard, Thousand Sons

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Having an army with a detachment of Chaos Daemons with the warlord inside and another detachment of CSM/DG/TS with one or more Daemon princes (all versions in those codexes). You can assign the free relic to one of those daemon princes because they meet the requirements of the Hellforged Artefacts assignment rules (pg. 130 Chaos Daemons Codex).

**Example 1:**
Batallion detachment (Daemons - Khorne) with Karanak as Warlord
Batallion detachment (Chaos Space Marines - World Eaters) with a World Eaters Daemon Prince (Khorne)
The Daemon Prince is a valid destination for Skullreaver, A'rgath or Armour of Scorn (for example) because he has the keywords (not faction mandatory) DAEMON, CHARACTER and KHORNE.

**Example 2:**
Batallion detachment (Daemons - Nurgle) with a GUO as Warlord
Batallion detachment (Death Guard) with a Daemon Prince of Nurgle with a hellforged sword
The Daemon Prince of Nurgle is a valid destination for Corruption because he has the keywords (not faction mandatory) DAEMON, CHARACTER and NURGLE and is equipped with a hellforged sword.

**Additional comments:**
This exception only occurs with the free relic for having the warlord with the DAEMON faction keyword. The extra relics can't be assigned to Legion Daemon Princes because there is the FAQ limiting the Chaos Daemon Stratagems by Faction Keywords.

**Comment by WindstormSCR** [comment]
Unfortunately Battlescribe's current data structures do not support such an implementation without catalog inheritance. additionally, there is a second problem: <allegiance> is considered fundamentally different from <mark of chaos> until GW faqs otherwise. this is because of the previous ones covering replaceable keywords, stating that two replacements with the same name but of a different type are not considered the same. 

From the designer commentary: http://puu.sh/Aipvo/091c7f5dcb.jpg

**Comment by angelambrosio** [comment]
@WindstormSCR I accept the problem related to the BS data structure. I'm developer too, and had a feeling about it would be a problem. But as a gamer I can't understand you explanation about the "second problem"... In the Hellforged Artefacts section of Chaos Daemon Codex (pg. 130) you can read:

If your army is led by a Warlord with the faction keyword **DAEMON**, you may give one of the following hellforged artefacts to a **DEMON CHARACTER** in your army.

I can't find the relation of this to <allegiance> o <mark of chaos> "keywords". Anyways, the problem I exposed only affects to the different Daemon Princes in the mentioned codexes (CSM, DG, TS and Chaos Index). Only the datasheets in CSM Codex and Chaos Index have the "Daemonic Allegiance" rule, and this replaceable keyword only affect to which relics the model can access, but not the fact that those datasheets are eligible as valid destinations for the free relic, which is the main problem I exposed.
