### ISSUE TITLE
Imperium - Grey Knights - Restore Missing Keywords

### ISSUE THREAD

**Issue by Remgrandt** [BSData/wh40k#3035]
**File/Catalogue:** Grey Knights

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS

**Dropbox:** Yes

**Description:** Several units are missing some keywords (categories). The Apothecary has extra keywords it should not have. See table below for complete list of discrepancies:

Unit      |Missing                 |Remove
-----------------------------------|---------------------|----------------
Lord Kaldor Draigo                  |Character            |
Grand Master Voldus                 |Imperium, Voldus     |
Grand Master                        |Imperium             |
Grand Master in Nemesis Dreadknight |Psyker               |
Castellan Crowe                     |Castellan Crowe      |
Brother-Captain Stern               |Imperium, Adeptus Astartes, Character, Infantry, Brother-Captain, Terminator, Psyker, Stern |
Brother-Captain                     |Imperium, Adeptus Astartes, Character, Infantry, Terminator, Psyker, Brother-Captain |
Techmarine                          |Character, Infantry, Techmarine |
Chaplain                            |Psyker               |
Brotherhood Champion                |Imperium, Character, Infantry |
Terminator Squad                    |Infantry, Terminator Squad |
Strike Squad                        |Strike Squad         |
Apothecary                          |Apothecary, Imperium |Ancient, Paladin
Brotherhood Ancient                 |Infantry |
Paladin Squad                       |Infantry, Paladin, Paladin Squad |
Paladin Ancient                     |Imperium |
Purifier Squad                      |Purifier Squad |
Venerable Dreadnought               |Venerable Dreadnought |
Purgation Squad                     |Psyker, Purgation Squad |
Nemesis Dreadknight                 |Psyker |
Razorback                           |Imperium |
Rhino                               |Rhino  |
Stormhawk Interceptor               |Vehicle |
Stormtalon Gunship                  |Vehicle |

**Comment by tekton** [comment]
These mostly got removed when a file got merged incorrectly a while ago, most of these were already fixed and we will get them back in with v19
