### ISSUE TITLE
T'au Empire: Warlord Trait ordering inverted when Narrative is selected?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3036]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** Warlord's traits in Narrative gametype (Stronghold assault) are inverted.

**Comment by Mad-Spy** [comment]
I think I've found the issue. The "Stronghold Assault Defender" trait group is misspelled (as *Stonghold*) so it appears before the Attacker group.
