### ISSUE TITLE
Warhammer 40,000 8th Edition: Error loading data files

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3040]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** At the start of the roster, an it said “problem loading data files”

Don’t know why. 
I tried to reload the data but the issue continue. 

Thanks for your work!

**Comment by alphalas** [comment]
Sounds like #1706.
