### ISSUE TITLE
Imperium - Astra Militarum: Company Commander always requires a Warlord Trait

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3041]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** ~~Astra militarum list with assasinorum attached.  Yarrick, company commander x2, inf squad x6, callidus assasin, commissar x2, armoured sent w/plasma x3, basilisk, heavy weapons squad w/mortars, heavy weapons weapons w/ auto cannon, and vulture gunships w/Gatling cannon.  Says list is invalid because each character needs a warlord trait, but only one can legally have one~~

Company Commander is requiring a Warlord Trait even if it is not the Warlord.

**Comment by Mad-Spy** [comment]
Root issue is that Company Commander is requiring a Warlord Trait even if it isn't the Warlord.

**Comment by CrusherJoe** [comment]
Not sure why this keeps getting reported, but using latest version of BattleScribe and latest released datafiles for AM, this is simply untrue.
![ccommander](https://user-images.githubusercontent.com/9998385/39895874-8f9b78f2-5471-11e8-915c-e73aa2065ae4.PNG)

**Comment by Mad-Spy** [comment]
@CrusherJoe, I swear I replicated this, or I wouldn't have updated it. Maybe my copy of BS at home is still the old one...

**Comment by alphalas** [comment]
It’s quite likely lol

**Comment by GenWilhelm** [comment]
it only happens when AM is the parent to a child force.

**Comment by alphalas** [comment]
Then that sounds more like a BS bug then anything else

**Comment by GenWilhelm** [comment]
Yeah, maybe, but it's solvable in the data. There's more than one min constraint, a variable 1 and a fixed 1, and BS doesnt consistently evaluate their priority.
