### ISSUE TITLE
Horrors points adding incorrectly

### ISSUE THREAD

**Issue by NecronLord3** [BSData/wh40k#3050]
**File/Catalogue:** 

**BattleScribe version:** 2.01.15

**Platform:** iOS
![4d0f290f-54dc-4a8f-aeb7-3bdc6e8da814](https://user-images.githubusercontent.com/29505805/39954157-0c9e2282-5580-11e8-8980-b3b12186d7db.png)

**Dropbox:** Yes/No

**Description:** I noticed when adding and subtracting a pink horror from a squad of 9 brimstone horrors the points get stuck at 27

**Comment by NecronLord3** [comment]
![eab49290-4b48-4d80-938a-5efa4ffa38d8](https://user-images.githubusercontent.com/29505805/39954197-b1b30030-5580-11e8-9784-000b6270a1e7.jpeg)

**Comment by GenWilhelm** [comment]
Is this in a child force?

**Comment by NecronLord3** [comment]
By child force do you mean a mixed detachment.  If so yes, I was making a keyword Tzeentch detachment with units from Daemons, CSM, and Thousand Sons.

**Comment by Mad-Spy** [comment]
In that case, it's a known Battlescribe bug with point calculations in child detachment, not a problem with the data files.. Please report it Battlescribe.

In the meantime, closing and reloading your roster will make the points recalculate.
