### ISSUE TITLE
Deathwatch intercessors error

### ISSUE THREAD

**Issue by kwilliamsfla** [BSData/wh40k#3053]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by kwilliamsfla** [comment]
You cant break up squad into different models

**Comment by FarseerVeraenthis** [comment]
The Codex update has not been released yet.
It should be available here shortly, but likely tomorrow.

**Comment by acebaur** [comment]
The codex was only released today, and the catalog is currently being revised. Please be patient as this takes time and we are all volunteers. Should have everything updated by the end of the weekend :smiley:

**Comment by kwilliamsfla** [comment]
No worries..I'm just messing

Sent from Yahoo Mail on Android 
 
  On Sat, May 12, 2018 at 4:32 PM, Alex Baur<notifications@github.com> wrote:   
The codex was only released today, and the catalog is currently being revised. Please be patient as this takes time and we are all volunteers. Should have everything updated by the end of the weekend 😃
