### ISSUE TITLE
Deathwatch Special issue ammunition

### ISSUE THREAD

**Issue by HarlequinOfDeath** [BSData/wh40k#3058]
File: Imperium - Deathwatch.cat

BattleScribe version: v2.01.12.105

Platform: Desktop

Dropbox: No

Description: All "bolts" shooting profiles have now access to Special issue ammunition if the units have the Special issue ammunition rule. So the Intercessors and other Primaris have these ammunitions as well if they use these weapons.

Thanks for the fast codex update over the last weekend!

And a question: Would it be possible to make a summary of all weapons profiles (with and without ammunition) at the end? With all the new options in Deathwatch it gets very confusing and the document/army sheet is very long.

**Comment by HarlequinOfDeath** [comment]
Any updates on the special issue ammunition? Can provide the weapons list if needed.

**Comment by WindstormSCR** [comment]
This was on the back-burner until all the other profiles got sorted, and needs to be done so that only the appropriate units are affected. currently most weapon profiles are entered once and linked to wherver they appear, so for weapons like storm bolters this needs adjustment

**Comment by WindstormSCR** [comment]
SO as things stand there are two real options:
1) List all the ammunition profiles for each affected weapon (and then those will display wherever the weapon appears)
2) List only basic profiles, but have the SIA rules appear by default at the base of the army roster.

No. 2 would shorten rosters considerably.

**Comment by WindstormSCR** [comment]
Option 2 chosen after discussion, file updated in v30

**Comment by HarlequinOfDeath** [comment]
Thanks for your response. I think option 2 would be nice but with small marker/sign at all weapons profiles like * which can use the special ammo.
________________________________

**Comment by HarlequinOfDeath** [comment]
@Hellgore1974 Better open a new thread and summarize all weapons that are missing to help them find the missing entries. I don't have the spare time at the moment to do it but I will check the data maybe next weekend.
