### ISSUE TITLE
Imperium - Deathwatch: Power fist and plasma pistol not automatically selected

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3059]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Primaris Watch Captain. I'm not really 100% sure but I think his Power Fist and Plasma Pistol should be costed at the accumulated points of each item e.g. Plasma Pistol + Power Fist, rather than it being free. Don't have the 'dex to hand so I can't say what the points cost should be though.

**Comment by acebaur** [comment]
I'll update this in the next release
