### ISSUE TITLE
Space Marines - Company Vets on Bike, Sgt, lacks Storm Shield Option

### ISSUE THREAD

**Issue by JasonMWelch** [BSData/wh40k#3070]
Catalogue: Imperium - Space Marines

BattleScribe version: 2.01.15

Platform: iOS

Dropbox: No

Description: Company Veterans on Bike Sgt can not properly take a Storm Shield like the rest of his unit can.

**Comment by GenWilhelm** [comment]
I can't see anything that allows a Company Veteran Biker Sergeant to take a storm shield.

They're not in the codex, they can't in the index, and they haven't had any errata; is there somewhere else that says otherwise?

**Comment by JasonMWelch** [comment]
I suppose not, I mistook any marine to mean him as well.  So weird that the sgt can take less than his unit.

**Comment by JasonMWelch** [comment]
I guess the one thing that really is iffy on this, is that in the new Deathwatch book, for a unit of say Aggressors, it states that "Any aggressor in the unit may swap out the boltstorm gauntlets for flamestorm gauntlets"  and they never specifically call out the Sgt, does that mean in those units the sgt does not have the option to switch?

**Comment by Mad-Spy** [comment]
Your quote is not correct. 

For Aggressors, the Codex says "Any model may replace its auto boltstorm gauntlets and fragstorm grenade launcher with flamestorm gauntlets." Thus the Sergeant is included in "any model".
