### ISSUE TITLE
Deathwatch - Interceptors are only paying for 1 of their two weapons.  Inceptor Fast choice selection Broken

### ISSUE THREAD

**Issue by JasonMWelch** [BSData/wh40k#3071]
**File/Catalogue:** Deathwatch

**BattleScribe version:** 2.01.15

**Platform:** iOS

**Dropbox:** No

**Description:** In both Primaris Killteams and just a Fast choice Inceptor unit, models are only paying for their weapon once, but they are equip with 2, unlike Aggressors who just pay for both "gauntlets" as one.  An assualt bolter Inceptor should total 45 points, and a plasma one should be 59 a piece.

Secondly, the Fast choice selection for the weapons should be a unit wide option.  Currently the Sgt can not change his weapon, and the troops have to do it one at a time.  In the Space Marine .cat they are just "equipment" choices at the top that tack on the gun prices.

**Comment by JasonMWelch** [comment]
Aggressors and Reivers also are like this 2nd part, but the sgt's can select gear.  I just can't remember if the deathwatch versions of these units can have mixed gear or not.

**Comment by acebaur** [comment]
All of these fixes have already been implemented. Please make sure you are using the most up to date version of the catalog. 

Secondly, each multiple model unit in the codex says "Any model may.." which means they can select individually.

**Comment by JasonMWelch** [comment]
Cool, that is a very subtle change over the SM Codex of it being a Unit wide selection.

**Comment by JasonMWelch** [comment]
I am on .cat V25 (the most recent) and still seeing all these issues.

**Comment by alphalas** [comment]
Delete and redownload - looks like @windstormSCR forgot to increment version

**Comment by JasonMWelch** [comment]
That still didn't change anything.

**Comment by WindstormSCR** [comment]
if you're pulling from appspot, these changes have not been released to there yet
