### ISSUE TITLE
[Anon] Bug report: Imperium - Adeptus Titanicus.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3072]
**File:** Imperium - Adeptus Titanicus.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Reaver Battle titan should cost 2,400
Warhound Scout titan should cost 1,500
There has been no errata point changes

**Comment by alphalas** [comment]
Yes there was. It’s called Chapter Approved.
