### ISSUE TITLE
Imperium - Deathwatch - Intercessors Point Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3074]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** Incepters are priced incorrectly they are only listed and priced with one gun when they come with two.

**Comment by FarseerVeraenthis** [comment]
what file version are you running??
on V25 they are listed with a bolt pistol and bolt rifle, and costed at 20 points (18 + 1 + 1) which is correct.
