### ISSUE TITLE
Aeldari - Harlequins: Codex point changes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3077]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** New codex point changes. Point Diffs:
- Troupe -2
- Troupe Master +11
- Shadow Seer -9
- Death Jester -15
- Solitaire -10
- Sky Weaver -5
- Starweaver No Change
- Voidweaver No Change -
- Harlequin's Blade -1 - Means a basic Troupe is 13 points now
- Caress No Change
- Embrace No Change
- Kiss -2
- Zypherglaive -5
- Fusion Pistol No Change
- Hallucinogenic Grenade Launcher No Change
- Haywire Cannon +1
- Neuro Disruptor No Change
- Prismatic Cannon No Change
- Shrieker Cannon No Change still 0
- Shuriken Pistol No Change still 0
- Star Bolas No Change still 0

**Comment by WindstormSCR** [comment]
These are already on branch, but thank you for the information. If you know how to use github/sync with github desktop you can check out the branch here: https://github.com/BSData/wh40k/tree/HarlequinsCodex

**Comment by FarseerVeraenthis** [comment]
closed by #3170
