### ISSUE TITLE
Imperium - Deathwatch: Hellfire flamer wounds on 2+, not 4+

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3078]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** Artemis' hellfire flamer is listed as wounding on 4+.  Codex shows it as wounding on 2+ like the hellfire ammo.  Thanks!

**Comment by acebaur** [comment]
will be updated in the next release
