### ISSUE TITLE
Deathwatch, Watch Captain Melee weapon error

### ISSUE THREAD

**Issue by Inquisitorbane0069** [BSData/wh40k#3079]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Deathwatch Watch Captain shows error when selecting alternative melee weapons. Also, Bolt Pistol should be removable? Uncertain if this second part is correct.

**Comment by WindstormSCR** [comment]
The watch captain datasheet is effectively a completely new one since the previous datasheet was simply a rename of the SM captain, so the codex entry takes precedence in its entirety, and is currently set up correctly.

**Comment by Inquisitorbane0069** [comment]
It's still flagging an error, limit 0, though when you switch from a chain
sword to any other melee option. This is the main error. It shouldn't flag
as an error if you select xenophase blade or relic blade.

**Comment by acebaur** [comment]
This will be fixed in the next release
