### ISSUE TITLE
Deathwatch, Inceptors missing second Assault Bolter

### ISSUE THREAD

**Issue by godaniel** [BSData/wh40k#3080]
**File/Catalogue:** Imperium : Deathwatch

**BattleScribe version:** 2.01.10

**Platform:** Mac

**Dropbox:** No

**Description:** Detailed issue description.
Inceptors are listed as having only one Assault Bolter and should have two. Current total point cost is 35 and should be 45 as a result of a second Assault Bolter.

**Comment by acebaur** [comment]
Inceptor costs are correct in the latest update, but the version number was not updated. Please delete and re-download.

**Comment by GenWilhelm** [comment]
Those particular fixes haven't been released yet, so it'll be a day or two before they're available while we round up all the other active issues.
