### ISSUE TITLE
Deathwatch point cost on pistols

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#3087]
**File/Catalogue:** deathwatch

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 1pt cost is added to Intercessors but bolt pistol and absolver bolt pustol show as 'no cost' on Primaris Chaplain, Libby and Apoth... is this built into unit cost or needs to add 1pt?

**Comment by MasterCrafty** [comment]
Oh ok. I have V25... but i only updated a few hours ago... must have missed
it. Let me go and see if V26 is available now...

**Comment by MasterCrafty** [comment]
Updated.

Chaplain is fixed.... Primaris libby still has a free pistol..

**Comment by GenWilhelm** [comment]
Just noticed the Primaris Watch Captain does as well.

**Comment by MasterCrafty** [comment]
Primaris watch captain has "master crafted bolt rifle & pistol" as
acwargear option (stalker or assault variants).

It looks like the pistol cost is included in that...

**Comment by GenWilhelm** [comment]
The points aren't correct though. Both variants of the master crafted bolt rifle should be 6pts, so those wargear options should be 7pts total.

**Comment by MasterCrafty** [comment]
Ah ok. Am still waiting on my (Collectors Edition) dex... so i'll take your
word for it :)

**Comment by MasterCrafty** [comment]
I have update all my army in BS now. I have all the primaris units so it
looks like most of the bugs are caught .... unless there are any wierd
wargear conflicts for builds i haven't made etc...

Thanks guys for a super quick turnaround on this - great work. I owe you'se
some beers.

M
