### ISSUE TITLE
Deathwatch captain in terminator armour

### ISSUE THREAD

**Issue by MasterCrafty** [BSData/wh40k#3090]
**File/Catalogue:** deathwatch

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Battlescribe throws up an error if you equip captain with mellee weapon and a storm shield. 

"2x May Pick One" 

It allows you to choose SS and a mellee weapon (giving up the SB) but flags an error in the list...

**Comment by GenWilhelm** [comment]
To clarify: these are index options - ie. not compatible with codex options.

**Comment by MasterCrafty** [comment]
So the codex will not let a termie captain have a Shield and a CC weapon?

I will go check...

**Comment by acebaur** [comment]
No it will not
