### ISSUE TITLE
Imperium - Grey Knights - Missing Relic and Warlord Trait options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3091]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** Yes

**Description:** 

- Many Grey Knights Characters are missing the ability to take artifacts, including Kaldor Draogo. 
- Paladin and Brotherhood Ancient are missing the ability to choose a warlord trait if designated as your warlord. 
- Force Org doesn't have the option to select the Grey knights chapter tactic brotherhood of psychers.

**Comment by Mad-Spy** [comment]
- Draigo cannot take relics as he is a named character, so nothing to do there. As far as I can tell, everyone who should be able to take relics can..
- The Paladin is missing a link to the Trait SSEG. Brotherhood Ancient looks fine.
- Brotherhood of Psykers should probably be a Root Rule. I don't think it can ever be displayed at present?

**Comment by legofiddl3** [comment]
Sorry about the relic thing. Draigo is the first named character I added to my grey knights and I wasn't thinking straight.

**Comment by Remgrandt** [comment]
Since Brotherhood of Psykers only applies to psykers, does it still make sense for it be a root rule? How are the troop/objective rules like Knights of Titan normally handled?

**Comment by legofiddl3** [comment]
You can add regimental doctrine to guard and Sept to Tau, maybe something like that with one choice? Then you could at least get the Brotherhood of Psykers Rule on the pdf.

Another odd thing I noticed just now. Making the Paladin ancient your warlord also removes the ability to take a relic on him. Kinda odd. I'd love to help fix stuff, if that's even possible. (I work in IT). Not sure how you get access to do that.

**Comment by tekton** [comment]
@legofiddl3 I'll get it done this weekend, thanks again :)

**Comment by amis92** [comment]
@legofiddl3 We could always use more volunteers, please read through https://github.com/BSData/bsdata/wiki#getting-started - if that doesn't scare you away, follow the steps described there :)

**Comment by legofiddl3** [comment]
I'I'll give it a read. Thanks :)

**Comment by tekton** [comment]
The Brotherhood of Psykers and GK flavour of Objective Secured are both added in there. FUnny story- both rules were already in the cat just not linked in any meaningful way (because sometimes I'm just plain dumb and useless).

I'm not the biggest fan of it since BS is more about helping build lists and a supplement to having the codex around, but I do understand the usefulness of having things there; if not just for you then to show your opponent at a glance what you're referencing.

**Comment by legofiddl3** [comment]
Thanks. I like it for printing the pdf, it can help games go quicker, but I agree anduse BS as a supplement to my codex.
