### ISSUE TITLE
Imperium - Deathwatch, Dreads and Venerable Dreads need the Index arms added.

### ISSUE THREAD

**Issue by JasonMWelch** [BSData/wh40k#3094]
**File/Catalogue:** Deathwatch 

**BattleScribe version:** 2.01.15

**Platform:** iOS

**Dropbox:** No

**Description:** Both the Dreadnought and Venerable Dreadnought need the arms that are only listed in the index added, such as twin auto-cannon arms and such.

**Comment by acebaur** [comment]
Those are not options for the Deathwatch Dreadnoughts in the index.

**Comment by alphalas** [comment]
Because the Dreadnought and vendread both just reference the Dreadnought HW list, which DW has its own instead of the SM list.
