### ISSUE TITLE
Imperium - Deathwatch - Kill Team unit name

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#3099]
**File/Catalogue:** Imperium - Deathwatch v19

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** Yes

**Description:**
This catalogue lists the name of the core troops unit as "Deathwatch Kill Team".  In the codex, they are simply "Veterans".

**Comment by WindstormSCR** [comment]
Codex release is file V26. update your data
