### ISSUE TITLE
Relic Leviathan Dreadnaught have 3 attacks instead of 4

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#3104]
**File/Catalogue:** FW Adeptus Astartes

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Relic Leviathan Dreadnaught have 3 attacks instead of 4

**Comment by WindstormSCR** [comment]
It has 4 by default as it is equipped with two melee weapons (giving it +1 A) by default. if you change the weapons this correctly drops to 3
