### ISSUE TITLE
Imperium - Astra Militarum: Missing profile for ripper guns

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3109]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.16

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ogryns missing ripper gun details in stats when new roster generated.

**Comment by Mad-Spy** [comment]
Looks like this may be a BS bug. Profiles are present in the cat, but I can't get them to display in the roster output.

**Comment by CrusherJoe** [comment]
Could it be related to them being (Collective) and having multiple profiles?

**Comment by CrusherJoe** [comment]
Okay I think I found the issue -- Ripper Guns aren't selected by default for Orgyn. When you add them, they show up.
![rippergun](https://user-images.githubusercontent.com/9998385/40285476-edbc5954-5c61-11e8-9c3d-48c20527386c.PNG)
