### ISSUE TITLE
Imperium - Dark Angels: Lion's Roar cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3116]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** Yes

**Description:** please check the lion's roar, it is costed at 15pts, where as it should be free cost : 0

**Comment by Mad-Spy** [comment]
This is the correct "cost" of the Lion's Roar as it replaces a combi-plasma (costing 15 pts). You still have to pay the cost of the combi-plasma before upgrading to the Lion's Roar.
