### ISSUE TITLE
Chaos - Thousand Sons: No warp bolter for Daemon Prince?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3117]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** No

**Description:** In codex: Thousand Sons - Daemon Prince of Tzeentch dont have option for Warp Bolter (nor in FAQ). Designers Commentary alows to take legacy options but in index : Chaos there is no DP of Tzeentch only (Basic) Daemon Prince. (Battlescribe Codex Death Guard have valid choice for Warp Bolter - 2 choices of DP: Index and Codex)

**Comment by Mad-Spy** [comment]
GW have not clarified whether the two datasheets ("Daemon Prince" and "Daemon Prince of Chaos") are intended to be equivalent. At present, if you want to take a Warp bolter on a Daemon Prince in a Thousand Sons army, you need to take an Index Prince.
