### ISSUE TITLE
Imperium - Astra Militarum - Malcador Heavy Tank Autocannon Miscosted

### ISSUE THREAD

**Issue by plaguedroneofblight** [BSData/wh40k#3119]
File: Imperium - Astra Militarum v114

Autocannons should cost 12 pts as per Chapter Approved 2017.

**Comment by plaguedroneofblight** [comment]
The catalogue added by Mad+Spy is incorrect. This issue is for the mainline AM cataglogue.

**Comment by Mad-Spy** [comment]
Oops, fixed.

**Comment by CrusherJoe** [comment]
Dupe of #3120

**Comment by plaguedroneofblight** [comment]
This is not a dupe of #3120. This one is a different catalogue, AND for a different weapon (autocannon vs battle cannon).

**Comment by CrusherJoe** [comment]
Oh, man...perhaps I should learn to read.

Or, maybe, pay closer attention...

Regardless, I'll fix this right now.
