### ISSUE TITLE
Chaos Decimator incorrectly calculates 2 of the same gun

### ISSUE THREAD

**Issue by FTgremlin** [BSData/wh40k#3122]
**File/Catalogue:** FW CSM v20

**BattleScribe version:** 2.01.

**Description:** You aren't charged past the first of the same gun for the Decimator. Eg attach two conversion beamers to it, you're only charged for one.

**Comment by Kohato** [comment]
Is this in a child detachment? If so, it's a known BS Bug - close and reload your roster and it will fix points. Nothing we can do here other than wait on Jon for this one.
