### ISSUE TITLE
Chaos Hellforged Termite incorrectly calculates 2 of the same gun

### ISSUE THREAD

**Issue by FTgremlin** [BSData/wh40k#3123]
**File/Catalogue:** FW CSM v20

**BattleScribe version:** 2.01.

**Description:** You aren't charged past the first of the same gun for the Termite. Eg attach two heavy flamers to it, you're only charged for one. Note this doesn't apply to the initial 2 combi bolter loadouts, but as soon as you change them, it breaks.

**Comment by Kohato** [comment]
See my comments on #3122
