### ISSUE TITLE
DKoK Gorgon not in BS (but is in the XML)

### ISSUE THREAD

**Issue by yeled** [BSData/wh40k#3124]
**File/Catalogue:** FW DKoK v56

**BattleScribe version:** 2.01.

**Description:** Gorgon not viewable (though it is in the XML)

I would expect the Gorgon to be in the Dedicated Transport. I see it referenced [here](https://github.com/BSData/wh40k/blob/master/Imperium%20-%20FW%20Death%20Korps%20of%20Krieg.cat#L427) and [here](https://github.com/BSData/wh40k/blob/master/Imperium%20-%20FW%20Death%20Korps%20of%20Krieg.cat#L1185) in the catalogue.

**Comment by yeled** [comment]
You know while I root around in the XML without_knowing_what_im_doing.jpg .. I see that everything with `targetId=c888f08a-6cea-4a01-8126-d374a9231554` is missing, also.

 - Minotaur Artillery Tank
 - Macharius*
 etc..

does that help?

**Comment by Kohato** [comment]
`targetId=c888f08a-6cea-4a01-8126-d374a9231554` is the Lord of War slot :)

**Comment by yeled** [comment]
Thanks @Kohato! If anyone else stumbles across my own stupidity, you need to add a Super-Heavy Aux Detachment to the list.

![image](https://user-images.githubusercontent.com/200421/40327477-029e0f46-5d3b-11e8-89a9-b5c7ed3ada32.png)
