### ISSUE TITLE
Imperium - FW Adeptus Astartes: Relic Units in Child Forces

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3126]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.18

**Platform:** Android

**Dropbox:** No

**Description:** It appears that when the FW Adeptus Astartes is sub to another list it will not count units in the parent list towards relic unlocks. Currently experiencing when space wolves are the parent list, selecting a relic elite (relic contemptor)  reports that I have to many relic elites despite having 4 elite choices in the parent list.

**Comment by el1l** [comment]
I know this says closed, but figured I chime in that it does the same thing in a Deathwatch Parent.

**Comment by GenWilhelm** [comment]
Yeah, the validation is done in the core game system, so it should behave the same regardless of parent.

Cheers for letting us know.
