### ISSUE TITLE
Chaos - Chaos Space Marines: Unable to select Kharn

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3127]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Kharn the Betrayer needs adding to HQ of Chaos Space Marines

**Comment by Mad-Spy** [comment]
As Kharn is only valid in a World Eaters (or unaligned) Army, you will need to select "World Eaters" or "No Legion Trait" from the Legion selector in order to add him to your army.
