### ISSUE TITLE
Chaos - Chaos Space Marines: Missing keywords on Chaos Cultists

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3135]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** v2.01.12.105

**Platform:** Windows

**Dropbox:** No

**Description:** The chaos cultists are missing the  "Faction: Legion" and "Mark of Chaos" categories. Have checked the latest FAQ to confirm, this is still true.

**Comment by Mad-Spy** [comment]
Cultists don't have a "Mark of Chaos" keyword, because it is replaced by the relevant God keyword after you select a Mark.

They were missing the "Legion" keyword though, so that's been added.
