### ISSUE TITLE
Imperium - Deathwatch: Problem with Veterans

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3138]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Deathwatch Killteam Veterans are bugged. They cannot take any equipment(Maximum Equipment :0)

**Comment by acebaur** [comment]
Please give an example, it is working fine for me.

**Comment by GenWilhelm** [comment]
It's probably because the two different "Boltgun" selections are behaving differently. Leaving the default one selected gives the error message that OP describes, even on valid wargear combinations.

**Comment by acebaur** [comment]
Well it was done that way to make it have a default gear selection. Also the codex reads "May swap Boltgun for two items from the DW equipment list" Even though boltgun is listed on the equipment list you technically have to swap it anyway. I'll look at it and see if I can make it so it is clearer on the naming of things
