### ISSUE TITLE
Imperium - Inquistion: Inquisitor Psykers

### ISSUE THREAD

**Issue by el1l** [BSData/wh40k#3147]
**File/Catalogue:** imperium - inquisition v17

**BattleScribe version:** 2.01.

**Platform:** /iOS/

**Dropbox:** Yes

**Description:** When making a generic inquisitor a psyker, it doesn’t allow selection of a Telethesia disipline power.

**Comment by Mad-Spy** [comment]
Once you've checked the Psyker box, you will need to select the new "Psyker" entry on the unit to select powers.
