### ISSUE TITLE
Imperium - Deathwatch - Primaris Watch Captain incorrect points cost.

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#3149]
**File/Catalogue:** Deathwatch v31

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Description:** Primaris Watch Captain has incorrect points cost for the "Master-crafted Auto bolt rifle & Bolt Pistol" and "Master-crafted stalker bolt rifle".

**Comment by Mad-Spy** [comment]
Specifically, the 1pt cost for the bolt pistol is missing.
