### ISSUE TITLE
Chaos - Chaos Space Marines: Helbrute weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3158]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** No

**Description:** When I add a Helbrute to my Chaos Space Marines Battalion there doesn't appear to be an option to change the Helbrute Fist for a Missile Launcher. Only the Power Scourge and Helbrute Hammer are available as replacement options.

**Comment by Mad-Spy** [comment]
You can take any two valid weapons from the Helbrute fist or multi-melta lists.

If you want missile launcher/fist, swap the multi-melta. If you want 2 ranged weapons, remove the default fist.
