### ISSUE TITLE
Deathwatch Intercessors no SIA

### ISSUE THREAD

**Issue by Hellgore1974** [BSData/wh40k#3159]
**File/Catalogue:** Deathwatch v31

**BattleScribe version:** 2.01.19.277

**Platform:** Android

The Intercessors in Deathwatchforces don't have Special Issue Ammunition but are listed to have them in the Codex.

**Comment by amis92** [comment]
Maybe look at #3058? I'm not sure, but it might be what you're looking for.

**Comment by Hellgore1974** [comment]
No I'm not looking for the SIA-profiles. It was just a note that the unit is missing the rule. It's more a matter of completeness.
