### ISSUE TITLE
Tau XV86 Coldstar Commander Loadout

### ISSUE THREAD

**Issue by rraapphhaaeell** [BSData/wh40k#3167]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Detailed issue description.

Tau XV86 Coldstar Commander Loadout:
This model may replace middle pod by other support systems/weapons

Error is thrown: must equip min of 1 middle pod.

**Comment by alphalas** [comment]
Because you have to replace both the high-yield burst cannon and the missile pod; if you don’t replace both it gives you an error.

**Comment by rraapphhaaeell** [comment]
Ok understood. But the codex says ```and/or```

**Comment by alphalas** [comment]
They FAQ’d it to be replace both with

**Comment by amis92** [comment]
Duplicate of #2936
