### ISSUE TITLE
Aeldari - Craftworlds: Named Characters stay hidden after adding craftworld trait

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3173]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Eldrad Ulthran has been removed and there is not a way to add him to a list.

**Comment by FarseerVeraenthis** [comment]
Looks like great fun to me

**Comment by Kohato** [comment]
Added you by mistake :p incorrect conditionals applied, already fixed.

**Comment by FarseerVeraenthis** [comment]
Fab, thanks for fixing it!

**Comment by daxiumx9** [comment]
It’s not fixed for me

**Comment by alphalas** [comment]
Because it’s only just been released to go live. Give appspot a few hours to update and try again
