### ISSUE TITLE
FW Elysians Drop Sentinel Costs

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#3180]
**File/Catalogue:** FW Elysians

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** FW Elysian Sentinel should be 40 points. Heavy Bolter, should be 8 points. Multi melta should also be 20 points. I don't see changes in FAQ, CA, Erratas but there's the possibility i've missed something.

**Comment by CrusherJoe** [comment]
Well I entered the wrong issue # but this is indeed fixed.
