### ISSUE TITLE
T'au XV84 Commander wrong cost (And has been for so long??!!!!!)

### ISSUE THREAD

**Issue by Bozac698** [BSData/wh40k#3183]
T'au Empire v24

BattleScribe v2.01.13.106

Platform: Windows/iOS/Android/Mac/Linux

Dropbox: No

Description: For the XV84 Commander from Forge World.  You keep adding the cost of the Target Lock to the overall cost of the Model.  It's an ''ABILITY''  not ''WARGEAR''  ...which, abilities, you don't pay for.  Would you please remove the 6 points from the total cost of this model.

**Comment by Mad-Spy** [comment]
I'm also pretty sure that this has been specifically addressed in one of the FAQs in as much as it stated that you pay for any item/ability that has an entry in the points table.

**Comment by amis92** [comment]
It was probably just that Facebook comment, but it's the best we've got to my knowledge. See #451
