### ISSUE TITLE
Orks Codex: Missing 'Ere we go on datasheets

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3184]
**File:** Orks.catz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Infantry missing 'ere we go rule/ability?  It's my understanding that many units have this ability but it's not displayed on character sheets. I have updated my database on 29/May at 11am this morning.

**Comment by WindstormSCR** [comment]
Its a collective army rule, and appears on the last page of the output, though if you have unit rules shown it will show up as listed: http://puu.sh/AzE1Y/43af262579.png
