### ISSUE TITLE
Imperium - Deathwatch: FAQ 1.0

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3186]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.17

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Deathwatch FAQ is up. If You guys could please hurry up and get this written out, as it’s quite literally only 4 changes to 3 units. Thank you

**Comment by acebaur** [comment]
It will get done as soon as is able. We are volunteers and do this on our own time. Please be patient

**Comment by tw6464** [comment]
I would love to help, but unfortuntely I’m at work.

**Comment by tw6464** [comment]
I find the idea of waiting this long for 3 rules changes when an entirely new version of the 9th age came out the 28th and everything was updated on the 29th

**Comment by Kohato** [comment]
@tw6464 Please feel free to dive into the freely available editor, make the modifications yourself, and submit a pull request.  We are not at your beck and call and it is childish and selfish to think otherwise.  The changes will be released as they are done.

**Comment by tw6464** [comment]
I apologize if I sounded childish. I admit I sounded like an impatient children. I appreciate that you responded to me, and I will now stop bothering you until the releases come
