### ISSUE TITLE
Bug report: Aeldari - Craftworlds.catz

### ISSUE THREAD

**Issue by joseale2310** [BSData/wh40k#3194]
**File/Catalogue:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.13

**Platform:** Mac

**Dropbox:** No

**Description:** Autarch on foot is automatically assigned with star glaive (6pts) and cannot be removed when using index options for wargear.

**Comment by WindstormSCR** [comment]
This is correct, the Designer commentary only adds the wargear options from the index, it does NOT adjust the standard equipment.

**Comment by joseale2310** [comment]
I do not believe so, in the example it is explained that you would equip with the index wargear options with the codexes point values if they exists.

**Comment by WindstormSCR** [comment]
"Use the **codex version** of your model's **datasheet**, but you can choose to use the index version for its **Wargear Options** (note that if the wargear has rules in the codex, these replace the index rules)"

emphasis mine. wargear options is a specific block within a datasheet.

**Comment by joseale2310** [comment]
The example is quite explicit. It is explained for the Commissar. You take the points for the commissar, the bolt pistol and the power axe. It doesnt make sense that you can field a Autarch with two avenger shuriken cannons and a star glaive.

**Comment by WindstormSCR** [comment]
Your example doesn't address standard wargear, which is in the top block of the datasheet and thus unchanged by the designer commentary. we work on Rules as Written unless there is an extreme problem, and in this case those are quite clear. While GW make care about "what makes sense" they have a very bad track record of writing rules to match it, and until the DC is adjusted the files will remain as they are.

**Comment by Kohato** [comment]
The issue is not that you're taking index with codex points.  In the index, Autarch Wargear options do not "Replace" existing weapons.  You can simply "take 2".  Codex Autarch has a Star Glaive.  There is no printed rule to replace that in any scenario.

**Comment by joseale2310** [comment]
Ok then. I will have to remove it manually. Thanks for the quick answer!

**Comment by Kohato** [comment]
I advise you to check with TOs with a list like that before using it in anything but casual games.  As shown in the 3 screens below - removing the Star Glaive would be invalid.  You can take 2 pieces of autarch wargear. In doing so, you do not replace the existing wargear.  This is not ambiguous, it is quite clear.

![1](https://user-images.githubusercontent.com/16939161/40786907-de37248e-64b1-11e8-8e73-9c525d30b43e.png)
![2](https://user-images.githubusercontent.com/16939161/40786908-de68fca2-64b1-11e8-90c1-2486e177b603.png)
![3](https://user-images.githubusercontent.com/16939161/40786909-dea7bce4-64b1-11e8-99bb-72dbf815d208.png)

**Comment by joseale2310** [comment]
I know, but I believe it is the intended way of using the DC. Everybody i have talked with agrees, but i will raise the question to the warhammer community.

**Comment by Kohato** [comment]
> The official model doesnt even have a start glaive, and it also has wings, so this whole thing doesnt make any sense.

Welcome to 40k :p

**Comment by joseale2310** [comment]
![image](https://user-images.githubusercontent.com/9451832/40832989-e93fa9ba-658c-11e8-9aa2-2e48e9490632.png)


I hope they fix it then for the next FAQ
