### ISSUE TITLE
Imperium - Grey Knights: Brotherhood of Psykers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3197]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Brotherhood of psykers army wide rule appears to be missing, the +1 to cast and deny and the not being affected by the new degrading smite.

**Comment by tekton** [comment]
The rule is listed in the Detachment Bonuses in "No Force Org Slot"
