### ISSUE TITLE
Deathwatch Veteran weapon selection issue

### ISSUE THREAD

**Issue by Inquisitorbane0069** [BSData/wh40k#3199]
**Deathwatch:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Error appears when only selecting one weapon change for any Deathwatch Veteran, states you must select two. I.E. Removed Boltgun to take stalker pattern bolter only. Codex states may take up to two, not must.

**Comment by acebaur** [comment]
You do in fact have to take 2 items. Codex states that veterans "may replace their boltgun with two items from the DW equipment list"
