### ISSUE TITLE
Draigo takes Relicspot away

### ISSUE THREAD

**Issue by Hellgore1974** [BSData/wh40k#3203]
**File/Catalogue: GK v20

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** 
When Draigo is selected as part of a (matched play) battle-forged army giving the first (free) relic to a character is marked as error. Named characters don't take away relic spots.

**Comment by GenWilhelm** [comment]
I can't reproduce this error, on either Android nor Desktop.
Can you provide steps to create the error?

**Comment by Hellgore1974** [comment]
I created a roster, chose battalion, took a scriptor and gave him a relic. When I then took Draigo the error sign lightened up saying too many relics taken.

**Comment by GenWilhelm** [comment]
Appears to work correctly for me.
Have you selected a Warlord? The free relic you get is for having a GREY KNIGHTS Warlord.

**Comment by Hellgore1974** [comment]
Ah. Okay. That did the trick. Thanx 😁
