### ISSUE TITLE
Imperium: Open Play Lander Raiders Power Overload

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3204]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Land Raider open play variants not displaying Power Overload rule with 3 twin lascannons and no lascannons selected. Not able to select twin helfrost cannons as hull weapon when Space Wolves are selected as the faction.

**Comment by WindstormSCR** [comment]
The space wolves might be a tricky fix, as their faction category is in their cat while the open landraiders are in the GST. power overload should be a simple conditional that got messed up somewhere.
