### ISSUE TITLE
Aeldari: Webway Gate Uncategorised

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#3205]
**File/Catalogue:** Craftworlds v45 / Drukhari v33

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Webway Gate is appearing under Uncategorised, instead of Fortifications.

**Comment by FarseerVeraenthis** [comment]
Whoops! I obviously didn't check thoroughly enough...
