### ISSUE TITLE
Imperium - Grey Knights: Warlord Category

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#3206]
**File/Catalogue:** Grey Knights v20

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Warlord selection is missing the Warlord category, causing it to not properly validate with other factions.

**Comment by tekton** [comment]
I've thought about fixing that at least a dozen times, then something comes up and I forget to write it down, lol. Thank you for the reminder :)
