### ISSUE TITLE
Twin Autocannon pts value and Capt TH pts in favourites

### ISSUE THREAD

**Issue by matthumpo** [BSData/wh40k#3208]
**File/Catalogue:** Space Marines v50

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Chapter approved has reduced FW Twin Autocannons from 33 to 30pts. 

Also... only a small one, but characters with thunder hammers displayed in favourites have points value of 16pts. Once added to the roster they return to the normal cost of 21pts.

Thanks

**Comment by matthumpo** [comment]
thats on the dreadnought and venerable dreadnought. not checked anything else

**Comment by GenWilhelm** [comment]
Dreadnought and Venerable Dreadnoughts aren't FW though, they're GW.

The favourites issue is a quirk of how BattleScribe resolves modifiers, which is used because the cost of a Thunder Hammer is different for a Character. I'll forward it on to the relevant repo.

**Comment by matthumpo** [comment]
Thanks for the response.
 
Ok, i'll ask on 40k website and get back to you, as lots of forums seem to say otherwise, as its not in the Codex but is in the index blah blah and the weapon is only available from FW but can still be run on a GW dread chasis under the index. Really need the points :P

**Comment by alphalas** [comment]
@genwhilhelm is correct; the points reduction was for the FW Twin Autocannon (which should be correct on the mortis and contemptors), not the SM Twin Autocannon which is an index only option and did not receive a points value in C:SM or ChapApp. Following the Designer’s Commentary the answer is pretty clear about this.

**Comment by matthumpo** [comment]
ok, cool, thanks for getting back to me
