### ISSUE TITLE
Blood Angels Chaplain issue

### ISSUE THREAD

**Issue by darkness24713** [BSData/wh40k#3223]
**File/Catalogue:** 
Imperium - Blood Angels
**BattleScribe version:** 2.01.
2.01.13
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
In Battlescribe, the Blood Angels Chaplain can select Combi-Weapons, however in the codex the rules state that they can only replace their bolt  pistol with an item from the pistol list. Also it gives the option to select a boltgun which again can't be used by the Blood Angels Chaplain

**Comment by GenWilhelm** [comment]
The Designers' Commentary allows a model to use the wargear options that were available on the Index version of that model's datasheet, which the boltgun and combi-weapons are in this case.

Designers' Commentary (final page): https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/warhammer_40000_designers_commentary_en-1.pdf
