### ISSUE TITLE
Imperium - Space Marines - Assault Squad Sergeant Missing INDEX Weapon Options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3231]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** Android

**Dropbox:** No

**Description:** The Update 'Index: Imperium 1' from the 16/04/2018 states the following:
Page 42 – Assault Squad, Wargear Options Change the first and second bullet points to read: ‘• The Space Marine Sergeant may replace his bolt pistol and chainsword with two items from the Melee Weapons and/or Pistols lists.’
Therefore selecting two plasmapistols for the Sergeant should be allowed.

(I hope that this is new, as I did not found that in my version)

**Comment by Kohato** [comment]
Verified - Pistols are set to max 1 in the group, Tactical Sergeant can get 2, but assault is unable to and should be able to.

**Comment by Mad-Spy** [comment]
Fixed. Also fixed Sergeant loadout, which was incorrectly set up as boltgun/chainsword instead of bolt **pistol**/chainsword.
