### ISSUE TITLE
FW Elysian Sergeant Plasma Pistol Cost

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#3232]
**File/Catalogue:** FW Elysian

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** FW Elysian Sergeant plasma pistol cost should be 5 not 7.

**Comment by Kohato** [comment]
Verified - Index cost is 5, BRB cost is 7, need to add modifier.
