### ISSUE TITLE
Inquisition: FW Model Inquisitor-Lord Hector Rex Points issue

### ISSUE THREAD

**Issue by ApolloBFC** [BSData/wh40k#3233]
**File/Catalogue:** Warhammer 40K 8th Edition V52

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Description:** Hector Rex has a points discrepancy which can confuse users which do not know which one to trust. The Model appears as 105 points in "Available Entires" but jumps to 115 points when selected. The model in "Available Entries" should either be 100 points (base model without storm shield) or 115 points (including storm shield). I would recommend having it as 115 points, as Hector Rex has a set wargear list and must take the Storm Shield, meaning he will always be 115 points in 8th Edition. (Unless he is changed if the Inquisition Codex ever drops).

**Comment by alphalas** [comment]
It’s not a discrepancy as much as the way BattleScribe handles it.

**Comment by ApolloBFC** [comment]
Could you shed this light on this? (you dont have to and im sorry for wasting your time in advance). Inquisitor Rex is never 105 points. His two values are 100 points or 115 points. Is there something else stopping the value being changed to 100 or 115? Again sorry, this will probably come across as ignorant.

**Comment by Kohato** [comment]
Rex is flagged as 100 points. Stormshield as 5. SS has a modifier to turn to 15 if equipped to a character. This modification doesn't take effect until the unit is added to the roster, not before.
