### ISSUE TITLE
Imperium - Adeptus Mechanicus - Points values for transuranic arquebus issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3236]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.17

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** “Change the points value of the transuranic arquebus to read ‘25’.” (It is 32 in BattleScribe adepts mechanicus v31)

Source: Forgebane FAQ v1.0 16/04/2018

**Comment by Thairne** [comment]
After what I know, the Forgebane FAQ is supposed to bring Forgebane costs that were pre-CA 17 back into line. That is the case for every AdMech entry except the Arquebus which did not get a points adjustment in CA.
However Forgebane is the newest publication of said wargear for this faction and therefore should be present in the cat.

**Comment by Kohato** [comment]
To clarify - the arquebus is already 25, but you still have to pay the 7 points for the guy holding it.
