### ISSUE TITLE
Aeldari - Drukhari - Reavers Missing from Patrol Detachment Selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3239]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** Yes

**Description:** Reavers cannot be added to a Patrol detachment. They don't show up in the fast attack options. They can be added to a batallion though.

**Comment by radionausea** [comment]
They are there. Check you've not chosen a Cabal or Coven as your force as that will hide them.

**Comment by Kohato** [comment]
Radion is correct - no issue here.
