### ISSUE TITLE
Imperial Knights warlord traits

### ISSUE THREAD

**Issue by DedusJovus** [BSData/wh40k#3241]
File/Catalogue: Imperium - Questor Imperialis.cat

BattleScribe version: 2.01.14

Platform: Windows

Dropbox: Yes

Description: When choosing warlord traits for IK models, besides traits from IK codex, BS offers those 3 from the rulebook, but in the IK codex (page 112) it says: "Note that Imperial Knights Warlords cannot take Warlord Traits from the Warhammer 40,000 rulebook."

**Comment by Kohato** [comment]
Good catch! Fixing now.
