### ISSUE TITLE
Moble knights houses 

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#3243]
**File/Catalogue:**  imperial knights 

**BattleScribe version:** 2.01.18

**Platform:** /iOS/Android/

**Dropbox:** Yes

**Description:** no force org slot house selection can’t change to other houses . Default to questor imperilas can’t change to Mechanicus houses

**Comment by Kohato** [comment]
Yes you can, you need to go one level deeper.  First radio button flips Imperialis/Mechanicus. Then you go one deeper to choose the house.

**Comment by williamcaw** [comment]
have done so as you have sated bug still persist on in ios and andrid systems . Household Choice cant be selected at all item keeps flowing to set preset of Questor Imperialis. as of june 10 2018 item was updated to be able to select Questor Mechanicus this cant be slected in the ios and andrid systems

**Comment by alphalas** [comment]
@williamcaw yes it does.
First, go into the house selection, and tap the radio button
![383607d6-35a4-4e08-baf1-21488311aa9d](https://user-images.githubusercontent.com/15703066/41238799-d682b2a6-6d64-11e8-809d-799dcb8356bd.jpeg)

You’ll see a list of 3 options, all with radio buttons; tap the buttons to change
![31959675-dac7-4d35-93a1-5df853fab19d](https://user-images.githubusercontent.com/15703066/41238869-0714ca08-6d65-11e8-823a-489992ac07f8.jpeg)

Then hit the check mark, and click on the orange box or the name of the alignment 
![e51e3c26-2d0d-4e61-b467-a9816eb71823](https://user-images.githubusercontent.com/15703066/41238923-286e8306-6d65-11e8-8e45-40fcf60ad35d.jpeg)

That brings up another radio button, click it
![27029585-511f-46d6-ab2d-b07f7b2e5211](https://user-images.githubusercontent.com/15703066/41238957-4640a42c-6d65-11e8-81b6-dd5117239bc9.jpeg)

Which then brings up all the houses aligned to that allegiance.
![05647fd0-2380-45dc-b968-84b2fb40b3c6](https://user-images.githubusercontent.com/15703066/41239014-6fc0ff18-6d65-11e8-9f06-d65e04e94714.jpeg)

It does indeed work.

**Comment by williamcaw** [comment]
then why cant i select in battle scribe on my apple device at all

**Comment by alphalas** [comment]
Update your app, delete and redownload data - I’m on iOS and it works just fine

**Comment by amis92** [comment]
@williamcaw did you try following the steps outlined by @alphalas ? You need to tap *exactly* on the dot. It's not really our fault, BattleScribe's interface works like that :)

**Comment by williamcaw** [comment]
i have done so it keeps flowing to the next screen cant select at all

**Comment by williamcaw** [comment]
i have click the eddit and it keeps going to the next screen with out allowing the change

**Comment by williamcaw** [comment]
i have dleated and redownload bs for apple divice and keeps saying  only Questor Imperialis

**Comment by amis92** [comment]
Okay, so what step exactly gives you a problem? Can you throw in some screenshots?

**Comment by williamcaw** [comment]
i do not know how to screen cap on my device

**Comment by Kohato** [comment]
You can press home+power to screencap, then attach those shots to the email reply for this thread (should be in  your inbox).  

I am looking to see how to improve the layout of the house choices while keeping the required validation.  No promises, but I am looking at what I can do to make it easier to use.

**Comment by alphalas** [comment]
https://flic.kr/p/2837uwh

**Comment by williamcaw** [comment]
a selection of none  to change over to other slections

**Comment by czer0** [comment]
This is definitely a user issue. Tested this with no issues on current version of android/iOS BS with latest data-files.
