### ISSUE TITLE
Codex: Imperial Knights forceorge slot lock to  Questor Imperialis  cant select Questor Mechanicus in /iOS/Android/

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#3246]
File/Catalogue: Codex: Imperial Knights

BattleScribe version: 2.01.18

Platform: /iOS/Android/

Dropbox: no

Description: no force org slot house selection can’t change  Default to Questor Imperialis can’t change to Mechanicus houses Area: selections   Cat: Imperium - Questor Imperialis  Type: bug  

 @Kohato
Contributor
Kohato commented 3 hours ago • 
Yes you can, you need to go one level deeper. First radio button flips Imperialis/Mechanicus. Then you go one deeper to choose the house. It's not the most amazing UX, but it's used this way to make relic validation cleaner (and FW knight validation too, since they can't be Questor Mechanicus)

have done so as you have sated bug still persist on in iOS and Android systems . Household Choice cant be selected at all item keeps flowing to set preset of Questor Imperialis. as of june 10 2018 item was updated to be able to select Questor Mechanicus this cant be selected in the IOS and Android systems

**Comment by alphalas** [comment]
Duplicate #3243

**Comment by Kohato** [comment]
@williamcaw - are you trying to assign Questor Mechanicus to a FW Knight? If so, that is not allowed.  They are hard written to be Questor Imperialis as a faction keyword.

**Comment by williamcaw** [comment]
selecting edit in only flows to the next level of choice of what houses to choose of default houses of cadmus griffith, hawkshroud , mortan and terryn this are the only house to be selected

**Comment by williamcaw** [comment]
this is not fw

**Comment by williamcaw** [comment]
read the path

**Comment by alphalas** [comment]
@williamcaw please see my response in #3243; this is not a bug and is functioning as expected
