### ISSUE TITLE
Chaos - Chaos Space Marines - Daemon Prince missing Dark Hereticus Discipline Options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3249]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 1.14.10

**Platform:** Windows

**Dropbox:** No

**Description:** Daemon Prince is allowed x1 option from the Dark Hereticus Discipline. The current version does not allow you to select a psychic power for him. He defaults with Smite and nothing else.

**Comment by Mad-Spy** [comment]
You need to select an eligible Mark of Chaos (not Khorne) and then select the Mark entry to select a power.
