### ISSUE TITLE
Imperium - Astra Militarum: Quad heavy stubber Sabre Platform missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3256]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Under the Heavy Support listing for Sabre Platforms there is no listing for the Quad Heavy Stubber version.

**Comment by alphalas** [comment]
@Mad-Spy is correct.
