### ISSUE TITLE
Adeptus Mechanicus FW new rules (Hoplites, Peltasts, Termite)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#3260]
Forge World published new rules for 40k:

https://www.warhammer-community.com/2018/06/15/15th-june-new-rules-by-popular-demandgw-homepage-post-2fw-homepage-post-1/

* [Terrax-pattern Termite Assault Drill](https://whc-cdn.games-workshop.com/wp-content/uploads/2018/06/warhammer_40000_termite_assault_drill_en-2.pdf)
* [Secutarii Hoplites](https://whc-cdn.games-workshop.com/wp-content/uploads/2018/06/warhammer_40000_secutarii_hoplites_en-1.pdf)
* [Secutarii Peltasts](https://whc-cdn.games-workshop.com/wp-content/uploads/2018/06/warhammer_40000_secutarii_peltasts_en-1.pdf)

**Comment by toadchild** [comment]
The Termite is also present in FW Adeptus Astartes and FW Heretic Astartes and needs to be updated there as well.
