### ISSUE TITLE
Drukhari - Triptych whip not displaying?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3262]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** Yes

**Description:** You forgot an artifact of cruelty, the triptych whip. Could you add it?

**Comment by FarseerVeraenthis** [comment]
The Triptych whip is available for Succubus with an agoniser.
If you select a succubus, and select an agoniser, the Whip will be shown and therefore can be selected.
