### ISSUE TITLE
Imperium - Adeptus Ministorum: Detachment validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3266]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** When selecting an outrider and a spearhead detachment in a roster together, fast attack gives an error when 3 units is selected (max 2), but when 2 is selected there is an error showing as minimum 3 units. And the same error is for heavy support.
No errors are showing when they are selected in a roster alone.

**Comment by Mad-Spy** [comment]
I'm unable to replicate this issue. Are you sure you have added your units to the correct detachment?
