### ISSUE TITLE
super-heavy auxiliary detachment ( Imperial knights) missing info 

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#3269]
**File/Catalogue:** 
Imperial knights
**BattleScribe version:** 2.01.14

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Detailed issue description.
Area: text/rule/profile missing information under force org- household choices . if a stranded super heavy detachment is add in to the mix it starts creating errors .

**Comment by Kohato** [comment]
Can you post a pic of the error?

**Comment by williamcaw** [comment]
![missinknights a](https://user-images.githubusercontent.com/22287376/41510583-3ccf0cec-721c-11e8-90d0-ed4dc24a4a4f.png)

**Comment by Kohato** [comment]
I don't see the issue?

Only Super Heavy Detachments gain the benefits of Household Traditions.

**Comment by williamcaw** [comment]
![missingkights b](https://user-images.githubusercontent.com/22287376/41510607-8b06622a-721c-11e8-823d-e5b9a0138aa4.png)

**Comment by williamcaw** [comment]
this is what happens if i upgrade one to a warlord and give him a heirloom

**Comment by Kohato** [comment]
Got it - thanks. I'll take a look
