### ISSUE TITLE
Imperium - Space Wolves: Wolf Guard in TA w/ Heavy weapon should be able to have 2 melee weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3270]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** In the space wolves roster. Wolf gaurd pack leaders in terminator armour should be able to take a cyclone missile launcher with a thunder hammer and storm shield.  However they cannot without a violation.  The same problem exists for wolf gaurd in terminator armor.

**Comment by Mad-Spy** [comment]
I can't find any data sheet that allows a Pack Leader to take a Cyclone Missile Launcher. Only standard Wolf Guard Terminators can do this. Please provide a citation for this, if you believe it is possible.

However, the Wolf Guard Terminator with Heavy Weapon _is_ incorrectly implemented as it should be able to take a second melee option.

**Comment by Mad-Spy** [comment]
This doesn't appear to be fixed. Either the Cyclone needs to be available to all models, or the Heavy Weapons guy needs to be able to take 2 melee weapons.
