### ISSUE TITLE
Termite Assault Drill in SM Cats

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k#3271]
Forge World published new rules for 40k:

https://www.warhammer-community.com/2018/06/15/15th-june-new-rules-by-popular-demandgw-homepage-post-2fw-homepage-post-1/

* [Terrax-pattern Termite Assault Drill](https://whc-cdn.games-workshop.com/wp-content/uploads/2018/06/warhammer_40000_termite_assault_drill_en-2.pdf)

Entry is present in the GST and needs to be added to the relevant cats:

- [x] Blood Angels
- [x] ~~Chaos Space Marines~~ FW Heretic Astartes
- [X] Dark Angels
- [x] ~~Space Marines~~ FW AA
- [x] Space Wolves
- [x] Deathwatch

**Comment by GenWilhelm** [comment]
If it's Forge World rules, shouldn't it be going in FW Adeptus Astartes, rather than being linked in each individual cat?

**Comment by Thairne** [comment]
AdMech also has access, therefore it kinda had to go in the GST. Of course one could copy it from the GST into FW astartes, but that creates duplicates again with AdMech...
I also dont know if FW astartes also covers CSM?

**Comment by GenWilhelm** [comment]
No need to copy anything, just link it in the root of FWAA like you've done for DA. 😄 
CSM have FW Heretic Astartes, so the same thing would happen in that file.

**Comment by amis92** [comment]
I'm wondering if there should be any checks for faction it's included in when linked in FWAA. The list of Chapters is restricted (ie no Grey Knights, no LotD).

**Comment by GenWilhelm** [comment]
Is there a clean way to do this without being able to check what catalogue a parent/child is drawn from?

I assumed we'd gone down the route of "user validation" until we can turn these catalogue into libraries.

**Comment by Kohato** [comment]
There would be no clean way of validation without library checks in 2.02 - since you can't put a conditional on FWAA that looks into another cat.  The only way to add while still validating is to add a link from the GST entry to the individual chapter cat files and not into FWAA, then hide as needed (IE: Set hidden true if force contains at least 1 instance of Legion of the Damned chapter)

**Comment by Thairne** [comment]
However we finally decide, I intentionally crafted the entry in a way it should be able to be cut&pasted into other cats without throwing (too many) errors.

**Comment by rsochia** [comment]
wondering when this will be updated for the space marines. I am using this in a event the end of august and was trying to have a single reference sheet for my army......

**Comment by Mad-Spy** [comment]
This has been added to the FW Adeptus Astartes catalogue, so it is now available for all SM armies.

**Comment by rsochia** [comment]
You say it has been added to the FW Adeptus Astartes catalogue. It was added when it was first released but this a data sheet update that has been linked in the start of this issue. It need to be updated in the FW Adeptus Astartes file. It still says it is PL6 when it is now 8. It does not have the new melta cutter profile, it does not have the termite drill weapon profile. It does not have the points changes for the drill and the melta cuter. Etc.......

Please reopen this ticket and update the drill profile in the FW AA Please. I have the new data file release that was released 3 hours ago on 7/29/18 (2 days after you say it was in the FW AA file.
