### ISSUE TITLE
Codex: Questor Imperialis - Freeblades should have access to allegience relics, but not house relics.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3272]
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** Regardless of the detachment Household choice a Freeblade knight can choose their own household allegiance Imperialis/Mechanicus, and thus get access to corresponding relics/stratagems but not household traditions.

**Comment by Kohato** [comment]
Well ... shit. They would get Allegiance relics, but not house limited relics.  These damned relics will be the death of me.  I'll get it fixed.
