### ISSUE TITLE
Thousand Sons Daemon Prince not allowed Warp Bolter

### ISSUE THREAD

**Issue by davidsavagejr** [BSData/wh40k#3273]
**File/Catalogue:** Chaos - Thousand Sons.cat

**BattleScribe version:** 2.01.14

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** I raised this a while ago but it was closed due to "Design Commentary" however, since it hasn't been updated I'm raising this again because it's at odds with how it has been ruled officially.  Thousand Sons DPs cannot take a Warp Bolter via Design commentary due to the fact that they changed the name of the data sheet in the codex.

Previous it was "Daemon Prince" and now it is "Daemon Prince of Tzeentch".  Since these are different data sheets, it counts as a completely different unit in the codex an therefore is not allowed via Design Commentary.

Also, I can confirm this is how it has been ruled in multiple tournaments I've participated in.

**Comment by GenWilhelm** [comment]
It doesn't matter that the datasheet changed name (or its unit has a different name, or however you want to spin it), as the Designers' Commentary asks whether or not the **model** has options that appear on its index datasheet.

>Use the following flowchart to determine which datasheet to use for your **models**. [...]

>Are there wargear options for your **model** that only appear in the index version of its datasheet?

>Use the codex version of your **model**’s datasheet, but you can choose to use the index version for its wargear options [...]

(emphasis mine)

&nbsp;

Before the codex, a THOUSAND SONS Daemon Prince would use `Daemon Prince` *(Index: Chaos p21)* as its datasheet. Therefore, that datasheet is the "index version" of that model's datasheet.

With the codex, that same model uses `Daemon Prince of Tzeentch` *(Codex: Thousand Sons p68)* as its datasheet. Therefore, that datasheet is the "codex version" of that model's datasheet.

The warp bolter is a wargear option that only appears on the index datasheet, therefore you may use the index version for its wargear options to take a warp bolter.

&nbsp;

Tournaments are free to impose whatever restrictions or rules changes they wish to, but the onus is on the players to adhere to that and on the organisers to enforce it. We can't support every variation of tournament rules, therefore we don't support any of them.

**Comment by Mad-Spy** [comment]
This issue can be interpreted both ways and indeed we have had tickets raised supporting both points of view. Until GW clarify the situation, we will support both interpretations.
