### ISSUE TITLE
Death Guard Noxious Blightbringer Incorrect Cost 

### ISSUE THREAD

**Issue by myatomicgard3n** [BSData/wh40k#3283]
File/Catalogue: Chaos - Death Guard.cat

BattleScribe version: v2.01.14.107

Platform: Windows

Dropbox: No

Description: Noxious Blightbringer is listed as 65 pts (58 + 7 plasma gun).  The updated points are now 70 (63 + 7 plasma gun) according to the codex.

**Comment by Mad-Spy** [comment]
Noxious Blightbringer is 58pts base as per Chapter Approved 2017.
