### ISSUE TITLE
Imperium - Astra Militarum: No crew stats for weapon batteries

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3287]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** The heavy support selection that are weapons battery types (earthshaker battery, saber platforms, ect.) Don't show the stats and unit count for the accompanying gun crews.

**Comment by Mad-Spy** [comment]
According to their datasheets, the units you have specifically called out do not have separate crews with their own stats. Thus, they are not included in the data files.

If you have an example where a unit which has a crew on its datasheet does not have details of the crew in the data file, please open a new ticket.
