### ISSUE TITLE
Imperium - Dark Angels: Incorrect cost for Hellblaster Squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3288]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** For Dark Angel, price of the Hellblaster squad is the same as the Intercessor. Nerf please!

**Comment by Thairne** [comment]
You need to give them a weapon of the 3 choices they have, then suddenly their price will be more to your liking.
