### ISSUE TITLE
Imperial Knights FW FAQ

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#3290]
**File/Catalogue:** Imperium - Questor Imperialis.cat

**Description:**

There was an FAQ from Forge World for at least one hour. Why is not yet implemented? I'm a not-paying customer of BattleScribe and I won't ever buy a subscription if these updates lag so badly!

I would provide you with a link, but I'm pissed at y'all and since you surely have internal access to all files GW has ever created, not to mention publicly published, I think you can handle that by your own lazy selves.

Also, the update doesn't give access to some relics, so if you could fill a change request to GW/FW on my behalf I'll be considering subscription again.

**Comment by Kohato** [comment]
My hate for you knows no bounds.
