### ISSUE TITLE
Imperial Knights Character inconsistency

### ISSUE THREAD

**Issue by HydraulicGold2** [BSData/wh40k#3292]
**File/Catalogue:**

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** Imperial Knights maximum number of Characters should equal # of Super Heavy detachments + selection of Exalted Court (0-2 depending on Selection) + selection of Heirlooms of the Household (0-2 depending on Selection).

I have a file with 2x Superheavy Detachments, and maximum selection of both Exalted Court and Heirlooms which should allow for 6 Characters

**Comment by Kohato** [comment]
Ok, this one is actually much trickier than it seems.  BS, as it is currently made, does not allow you to increment maximum of something based on the number of types of forces in a roster. Meaning, I can't just say, bump max characters by 1 for every super heavy detachments. I'd like if it would allow this in the future and i'll raise it to Jon.

I'm working on a workaround in the mean time that will validate.

**Comment by Kohato** [comment]
I cannot actually get a workaround working on this at this time.  I'll be poking around to try, but I think we'll need to wait on a fix for BS to allow this type of incremental conditional.

**Comment by Kohato** [comment]
OK, this is ... "Fixed" - It's messy internally and I will make it better when Jon fixes the bug I opened, but as of the next release, it will work as intended in all cases except when taking a Supreme Command of IK + something else (which isn't allowed in matched play beta rules anyway).
