### ISSUE TITLE
Renagade Knights

### ISSUE THREAD

**Issue by iamthesolo** [BSData/wh40k#3294]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Sorry if this a repeat but couldn't find an issue raised.

Renegade Knight Index dropped today.
And chance in getting it on battlescribe please.
When you get round to it at some point.
Thanks.

**Comment by Mad-Spy** [comment]
Already done. Will be in next release.
