### ISSUE TITLE
Chaos - Thousand Sons Hellbrute Reaper Autocannon point cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3296]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Reaper autocannon point cost incorrect. It should be 15 rather than 18.

**Comment by Mad-Spy** [comment]
Unfortunately, without knowing which unit you are referring to, I can't fix this.

**Comment by Kohato** [comment]
Reaper Autocannons are on Hellbrutes and Defilers.  Cat links to GST entry which is 18 points. TS Codex reduces it to 15.
