### ISSUE TITLE
Chaos: Index Renegade Knights Missing Items

### ISSUE THREAD

**Issue by Kohato** [BSData/wh40k#3297]
Found a couple of things missing:

1) GW Knights all have one of 3 new keywords: Renegade Knight, Renegade Knight Dominus, or Renegade Knight Armiger - these are missing.
1b) The FW Knights are also missing their respective keywords.
2) Renegade Knight's WS and A values should increase by 1 each if you have a Reaper Chainsword and Thunderstrike Gauntlet
3) Dominus missing Volcano Lance profile
4) There should be 1 forced character choice in a Questor Tratoris Superheavy Detachment

**Comment by Mad-Spy** [comment]
1. I've never included unit name keywords on any units; no one has ever complained.
2. Added missing Engine of Destruction rule.
3. Fixed.
4. Fixed.
