### ISSUE TITLE
Chaos - Death Guard: Unable to add Feculent Gnarlmaws to roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3300]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** Can't find a way to add Feculent Gnarlmaws to the army. Either as a separate Fortification or under Horticulus Slimux. Something I've missed?

**Comment by Mad-Spy** [comment]
Fortifications can only be taken in a Fortification detachment. You will need to include one if you want to take Feculent Gnarlmaws.
