### ISSUE TITLE
Imperium - Space Marines: Space Marine captain has no warlord trait options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3310]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** Issue with Captain in Space Marine option. When selecting him to be a warlord, it gives you the warlord but no ability to actually select any warlord ability, Iron Resolve for example. It works on other captains but not plan captain.

Also there appears a spelling mistake with Veteran Biker Sergeant as spelt Sergreant.

Regards
Paul

**Comment by Mad-Spy** [comment]
Couldn't reproduce Captain issue in v53.

Fixed typo in Vet Biker Sergeant.
