### ISSUE TITLE
T'au: Coldstar Commander weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3311]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I may be wrong about this, so if I am I apologize. But the Tau sourcebook came out after the index, right? The Commander in an XV86 Coldstar Battlesuit has a discrepancy between index and the sourcebook for Tau. The index said it can replace its high-output burst canon AND its missile pod, but the Sourcebook says and/or its missile pod. It’s a pretty significant difference for setup, because burst cannons can be a much tastier option than the missile pod, but not if you also have to give up the high-output. Can we get an update on this, or at least an index/codex option like I’ve seen on some other units?

**Comment by Mad-Spy** [comment]
The Index Coldstar had no weapon swap option at all. It could only take an additional two _Support Systems_.

The Codex Coldstar can take between two and four items in any combination from the _Ranged Weapons_ or _Support Systems_, one of which can be the high-output burst cannon.

There would appear to be no need to make a change to the implementation to cover an different Index option.

**Comment by ppenne** [comment]
Okay, I made an account so I can comment, since I apparently was less than clear. Currently, you get an error message on the Coldstar if you remove the missiles without removing the high-output burst cannon.

I also apologize for typos. I am banished to my phone at the moment, and that makes editing a challenge.

**Comment by amis92** [comment]
@ppenne please read the resolution/explanation in #2936 and if you're not satisfied, explain your point of view/interpretation :) (I'll close this for now, but you can comment anyway, and if I deem your future complaint valid, I'll reopen).

**Comment by ppenne** [comment]
Nope, I missed the errata. My bad!
