### ISSUE TITLE
Canis rex and freeblade

### ISSUE THREAD

**Issue by u02dah4** [BSData/wh40k#3324]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Description:** 

Takeing Canis Rex presently hides the qualties and burdens option on other freeblade knights.

This is not correct as due to the wording you cannot choose or not choose Canis rex to take them. It has qualities and burdens statically just by being included

So you may choose a freeblade in the detatchment to have qualities and burdens and have Canis Rex

(Note this is worded differently to warlord traits where it says if "Canis Rex is")

"If your army is battleforged, then before the battle you can give one freeblade model in each detatchment qualities and burdens. To do so, choose a single quality from the table below, or roll two d6 to randomly generate two qualities from the table (duplicate rolls have no effect). If your battle-forged army includes canis rex, both canis rex and sir hekhetur have the legendary hero and last of there line qualities."

**Comment by Kohato** [comment]
I likely have an incorrect force/roster flag. I'll take a look tonight.

**Comment by Kohato** [comment]
So this one was done on purpose.  Canis Rex is not allowed to not take burdens/qualities.

Since he has both qualities and burdens, this fulfills giving a single freeblade model Qualities/Burdens in the detachment.

![image](https://user-images.githubusercontent.com/16939161/42255563-f769b154-7f11-11e8-94a1-d7f7ce97b9fa.png)
![image](https://user-images.githubusercontent.com/16939161/42255566-fca53698-7f11-11e8-9719-75395d2a1f9a.png)

**Comment by u02dah4** [comment]
As It says- if your army is battleforged you can give one freeblade in your detatchment qualities and burdens.

So hypothetically i choose a warden and give it qualities and burdens.

The second part of that rule if your battle-forged army includes Canis Rex - both Canis rex and Sir Hekhtur have the last of your line qualities. Then grants Canis Rex qualities as a static bonus. Same for burdens.

So both the Warden and Canis Rex end up with qualities and burdens.

So below i'll explain why it works this way



Now while it is easy to quick read the rule as you may only have one freeblade with qualities and burdens in a detachment which would limit the detatchment to only one freeblade- it doesn't say that it says "you can give one freeblade in the detatchment" which is not the same thing as saying you are limited to only one in the detachment. 

The question therefore becomes do you choose to give Canis Rex qualities and burdens fullfilling the rule.

If you contrast the freeblade qualities and burdens wording with the Warlord trait wording you'll notice the warlord trait wording says "if Canis rex is your warlord"

The "if" is big 

Had the Canis Rex part of the rule been worded like warlord traits and written  "if Canis rex is your freeblade with qualities and burdens both Canis rex and Sir Hekhtur have the last of your line qualities."

Like warlord traits it would have meant Canis Rex was your choice and so you couldn't choose another - however it doesn't as this would give you the option of having a Canis Rex without them

The other way it could have been worded would be "if your army is battleforged and includes Canis Rex you must give Canis Rex qualities and burdens and both Canis rex and Sir Hekhtur have the last of your line qualities instead of generateing qualities.

This would have made Canis rex your choice and given him mandatory traits however it isn't worded this way.

So essentially Canis Rex is never given the qualities and burdens he just has them. He does not fullfill the first part of the rule as you never give him qualities and burdens and the first part of the rule does not prohibit two knights from having qualities and burdens it just gives you permission to give them to one knight.


I appreciate this is a wordy explanation

**Comment by Kohato** [comment]
![image](https://user-images.githubusercontent.com/16939161/42276639-23d9b1ec-7f5a-11e8-9f19-953ee3dfd63e.png)

**Comment by Kohato** [comment]
As there has been no response to what I assume is your follow-up on the thread (and I wouldn't expect there to be, WH community team rarely responds to child comments on the original for whatever reason ...). It will be kept as intended and shown by the response.  However, you can work around this for your own games if you and your opponent rule it otherwise.  If you select your burdens/qualities first on your freeblade, then add Canis Rex, Or load a favorite entry that has them already, you can have a list that has it all, though you wouldn't be able to clear the validation error ... just clear all the others and leave that one as is.

**Comment by u02dah4** [comment]
Thankyou for taking the time to review it. 

Hopefully GW will faq it or provide a more clear answer at some point as the one you posted above is subjective - following freeblade rules from your perspective means one thing and from the dakka rules threads means something different. 

However you have to go with what you think is right.

Wont be the first time dakka and BS have disagreed and probably wont be the last.

**Comment by alphalas** [comment]
TBH, more often then not the dakka threads do *not* follow the way GW intends rules and the way they FAQ things, for what it’s worth.
