### ISSUE TITLE
Necrons - Maynark Dynasty can't have Translocation Beams Dynasty Code (it should!)

### ISSUE THREAD

**Issue by vhp17099** [BSData/wh40k#3325]
**File/Catalogue:** Necrons.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows (Indifferent)

**Dropbox:** No

**Description:** When you select the Maynark Dynasty with Necrons, you should be able to select a Dynasty code from the other available dynasties for Maynark. However the Dynasty code for Nephrek named "Translocation Beams" is not available, and it shows the option "Relentless Advance" twice.
![issue](https://user-images.githubusercontent.com/7047900/42172746-d00bed32-7e14-11e8-9931-f27b16755d0c.png)

**Comment by Kohato** [comment]
Good catch - Just means I missed swapping a copied entry. I'll fix it tonight.
