### ISSUE TITLE
Imperium - Adeptus Mechanicus: Hoplites missing Canticles ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3326]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The secutarii hoplites, it’s under elites, they are also able to benefit from the canticles of the omnissiah too. The relatively recent rules on the warhammer community site do include canticles of the omnissiah. Thank you for all your effort :))

**Comment by Mad-Spy** [comment]
Correct according to https://www.forgeworld.co.uk/resources/PDF/Downloads//warhammer_40000_secutarii_hoplites_en.pdf
