### ISSUE TITLE
FW Adeptus Astartes - Can't select Venerable Chaplain Dreadnought as Warlord

### ISSUE THREAD

**Issue by Darkdefiler** [BSData/wh40k#3335]
**File/Catalogue:** Imperium - FW Adeptus Astartes v25
**BattleScribe version:** 2.01.14
**Platform:** Windows
**Dropbox:** /No
**Description:** Selected a Deathwatch Battalion, then added a FW Adeptus Astartes Battalion to the same detachment via add forces. Selected a Venerable Chaplain Dreadnought. The only options are for his ranged/melee weapon. I believe you should be able to choose him as your warlord as he's a Character?

**Comment by Mad-Spy** [comment]
Unfortunately, due to limitations of Battlescribe, it's not currently possible to implement Warlords properly in the FWAA catalogue. We are hopeful that this situation will be fixed in v2.02 of Battlescribe and will revisit this issue once it is released.
