### ISSUE TITLE
Imperium - Space Marines: Land Raider Excelsior should be able to be Warlord.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3340]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** Land Raider Excelsior does not allow Warlord selection. Whilst it is a vehicle it is also a character. Index entry.

**Comment by Mad-Spy** [comment]
Fixed. Also added Relics as it is eligible for the Armour Indomitus, Salamander's Mantle and Crusader's Helm.
