### ISSUE TITLE
Imperium - Deathwatch: Watch Captain weapon validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3341]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I try to add a relic blade or a xenophase sword to my Watch Captain for my Deathwatch, the list becomes invalid even though these are options give to us by the codex.

**Comment by acebaur** [comment]
Can you provide a screenshot? I'm not getting any validation errors.

**Comment by WindstormSCR** [comment]
triple checked all captain wargear logic on current version, working as intended
