### ISSUE TITLE
Imperium - Astra Militarum: Incorrect display of Regimental Doctrine

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3344]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Vostroyan doctrine pulls through the Valhallan one instead. To reproduce, select Vostroyan doctrine and then view roster (Valhallan doctrine is displayed instead).

**Comment by Mad-Spy** [comment]
Unable to replicate in AM v121.
