### ISSUE TITLE
Imperium - Space Marines: Unable to select Warlord Trait for Guilliman

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3350]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 1.11.54

**Platform:** Android

**Dropbox:** Yes

**Description:** Roubute Guilliman can be the Warlord however the trait option is missing

**Comment by radionausea** [comment]
If you make him your warlord he gains the Adept of the Codex warlord trait, which is the one he has to take as a named character.
