### ISSUE TITLE
Aeldari - Harlequins: Unable to select Curtainfall relic

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3352]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** In the Relic choice in Harlequin section I cannot choos "Curtain Fall" for my Death Jesters.
I am almost certain that it was available in prvious versions of the file but it is not right now.

**Comment by Mad-Spy** [comment]
Have you selected Dreaming Shadow as your Masque? If not, you won't be able to select Curtainfall, as it's only valid for that masque?

**Comment by FarseerVeraenthis** [comment]
per @Mad-Spy select Dreaming Shadow as your Masque and you're golden.
