### ISSUE TITLE
Chaos - Death Guard: Plague Champion weapon options missing

### ISSUE THREAD

**Issue by dhatcher** [BSData/wh40k#3354]
**File/Catalogue:** Chaos - Death Guard

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** The Plague Champion for a unit of Plague Marines can only have a bolt gun and plague knife.  He's missing options for plague sword, power fist, bolt pistol, plasma pistol and plasma gun.

**Comment by Mad-Spy** [comment]
Once you have selected whether you are taking Codex or Index weapon options, select the option you have chosen to make any weapon swaps needed.

**Comment by dhatcher** [comment]
Dang I was clicking on the radio button, needed to click on the main part of the entry (text or open area).  Thanks.
