### ISSUE TITLE
bsdata Repo is offline

### ISSUE THREAD

**Issue by bux** [BSData/wh40k#3366]
**File/Catalogue:** 

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:**

    Failed to download from one or more repositories
    
    1) net.battlescribe.model.config.Repository@2b71eac4: https://battlescribedata.appspot.com/repos/wh40k
    
    2) https://battlescribedata.appspot.com/repos/wh40k/index.bsi: https://battlescribedata.appspot.com/repos/wh40k/index.bsi

**Comment by Kohato** [comment]
Appspot has shit the bed again. This is nothing the BSData team can fix.  It will be back within the day.
