### ISSUE TITLE
Chaos FW - Renegades and Heretics on Mobile: chaos covenant does not allow selection of associated units

### ISSUE THREAD

**Issue by fattymacNz** [BSData/wh40k#3373]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by fattymacNz** [comment]
When trying to create an army on a tablet, the arch-demagogue allows for the selection of a chaos covenant, but selecting these covenants does not then allow for the selection of the associated units (i.e. blood slaughterers or blight drones and plague zombies) in the roster. I don't know if this is because it requires that the demagogue be selected as the warlord before allowing the units to be chosen. This could very well be the case, but as there isn't an option to select the demagogue as your warlord, but I don't know for certain.

I could find other reports talking about covenants and warlord selection, but none of them seemed to reference the units they are supposed to make available, and all have been closed out. Therefore I think that this is an unreported bug. Thanks to all the code writers who put all this together. You guys are awesome!

**Comment by Mad-Spy** [comment]
I'm not sure exactly what you're asking here. By Arch-Demagogue, I assume you mean Renegade Commander, as this is the only model that can select a Covenant?

However, unlike Chaos Marines, choosing a Covenant does not confer the actual Chaos God keyword (e.g. KHORNE), the keyword conferred is COVENANT OF KHORNE, as per p81.

Thus, you cannot make a valid Battleforged Detachment which includes both Renegades and Daemons (as CHAOS is no longer allowed as the common keyword per the Big FAQ).

Therefore, if you want to include Daemons in your army, you'll need to add a separate detachment of Daemons, or, if you are playing Unbound, a child detachment.

**Comment by MountyChris** [comment]
Looks like you're reading the 7th edition rules.  Those units aren't available for Renegades in 8th.
