### ISSUE TITLE
Imperium - Blood Angels - Gabriel Seth Missing Rules

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3387]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** First of all thank you for your hard work on this.
Gabriel Seth for Adeptus Astartes Blood Angles has no special rules listed for being a chapter master of Flesh Tearers. 

Thank you again!

**Comment by Mad-Spy** [comment]
In fact, Gabriel Seth has no entries for any of his Abilities.
