### ISSUE TITLE
??: Sergeant missing weapon options.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3389]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Space marine sgt, should be able to take combi weapons or storm bolter, also then a melee weapon. Currently unable to take any combi or storm bolter at all.

**Comment by Mad-Spy** [comment]
Which catalogue are you having problems with?

**Comment by Mad-Spy** [comment]
No update from OP, so closing.
