### ISSUE TITLE
WH40K Imperial knights - missing galvanic magnavent

### ISSUE THREAD

**Issue by spacem0ses** [BSData/wh40k#3392]
**File/Catalogue:** WH40K Imperial knights

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** no?

**Description:** I understand that the galvantic magnavent is just a piece of terrain, but it comes in an IK box set and has its own rules. Could we get it added to the repository?

**Comment by Kohato** [comment]
The Galvantic Magnavent is an odd beast.  Yes, it's included in the box - but as far as I'm aware, all rules published for it are for 7th edition.  There are no 8th ed rules present for it.  I didn't even think the instructions for the terrain was in the Renegades box.

Long and Short of it, no - we cannot add this to the repo, as it is not a valid Fortification for use in 8th ed.  It is simply a piece of terrain.  Yes, some terrain have special rules that are present in Chapter Approved, however if that terrain piece doesn't have a fortification datasheet, we do not include it in Battlescribe as it cannot legally be included in a list - which is what Battlescribe is for.
