### ISSUE TITLE
Chaos - Daemons: Belakor access to Psychic Powers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3395]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Belakor has access to all 6 dark heretics discipline but he should o KY have the first three I believe.

**Comment by Mad-Spy** [comment]
Some people believe as you do, some think he should have them all. If you don't want to use them, just don't include them in your list.
