### ISSUE TITLE
Imperium - Space Wolves: Missing keyword on Redemptor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3397]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Redemptor dreadnought needs "CHAPTER" keyword. Submitted a bit ago but wasn't logged in and html removed chapter from the post :(

**Comment by Mad-Spy** [comment]
Technically, it needs the SPACE WOLVES keyword, as you must replace `<CHAPTER>` with `SPACE WOLVES` in a Space Wolves army.

It also needs defaults set for the weapon options.
