### ISSUE TITLE
Necrons: Tomb Sentinel missing Living Metal

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3398]
**File:** Necrons.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** Canoptek Tomb Sentinel [9 PL, 180pts]
Should have the rule
Rules: Living Metal
But it does not.

Thanks, great stuff!

**Comment by Kohato** [comment]
Will add tonight :robot:
