### ISSUE TITLE
Tyranids: Biovore cost incorrect?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3401]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ay mate! So the biovores are 50 points instead of 36 (like they are in 8th edition) and when selecting the wings upgrade on the hive tyrant it still says you should pick at least 2 weapons when the wings take up 2 of the four weapon slots and you already have filled out the other 2 (in short the code says the flyrant should have 6 arms).

**Comment by Mad-Spy** [comment]
Not sure about Biovores (I can't find anywhere that would mean they are not 36 points as per the Codex), but the Hive Tyrant is RAW, because the datasheet doesn't require you to replace the arms with the wings.

**Comment by GenWilhelm** [comment]
It was changed to 50pts in the Big FAQ:
https://whc-cdn.games-workshop.com/wp-content/uploads/2017/12/warhammer_40000_chapter_approved_2017_en-1-1.pdf

**Comment by Mad-Spy** [comment]
Ah! The one place I forgot to check for point updates!
