### ISSUE TITLE
Imperium - Space Marines: Incorrect weapon choice for Intercessor Sgt.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3406]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Intecessor Sargent missing equipment for bolt rifle.  Each model is equipped with a bolt rifle,bolt pistol, and frag  grenades  and knack grenades. He may replace his bolt rifle with a power sword. When equipping the unit. The bolt rifle is not removed from the list of the unit when the  sergeant equip’s the power sword.

**Comment by williamcaw** [comment]
I have Just re-read the faq it’s also  in addition to he may Take a power sword  as well
