### ISSUE TITLE
Imperium - Dark Angels: Intercessor Sgt missing weapon validation

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#3409]
Intercessor Sergeants must have the same bolt rifle type as the rest of the squad. There is currently no validation to prevent them taking a different rifle.

**Comment by williamcaw** [comment]
same as Imperium - Space Marines - Intercessor Sergeant missing options #3408

**Comment by Mad-Spy** [comment]
@williamcaw, this not the same as #3408. I have explained on that ticket why Intercessors are implemented as they are.

However, in Dark Angels, the sgt is able to take a different weapon to the rest of his squad which is not allowed.

**Comment by williamcaw** [comment]
just add up the points the one in the file of the darkangles are the correct point values by hand  the only  different is the blood angles and that one can take a chainsword

**Comment by williamcaw** [comment]
All models - in this unit may replace ther bolt rifle with an auto rifle or stalker bolt rifle. This means that the Sargent may change his rifle to any selection of rifles

**Comment by alphalas** [comment]
@williamcaw yes - the rifle selection is at the squad level, not the individual level. So that means you only change it once - because the sgt can’t change it individually.

**Comment by alphalas** [comment]
Deleted my last comment because I misread. @williamcaw no, ALL means all members of the squad must have the same selection. For sgt to be able to change independently it would have to say ANY model, not ALL models.

**Comment by Mad-Spy** [comment]
Kill Team is an entirely different game with different rules, so comparisons with that game are unhelpful.

As per @alphalas comment, _Any_ and _All_ are not the same thing. Units where each model can have independent choices have the "Any model..." wording.

"Their" is both a singular and plural possessive, so it applies equally to either interpretation.

In any case, the general consensus is that __all__ models in an Intercessor uni  must have the same type of bolt rifle. We have, AFAIK, had no other tickets querying this.

If you feel this interpretation is incorrect, please email GW and ask them to clarify in an FAQ.

I am locking this thread.
