### ISSUE TITLE
T'au Empire: Unable to take Cyclic Ion Blaster on XV86?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3411]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** According to the codex there is nothing that states the XV86 Coldstsr Battlesuits Commander cannot use Cyclic ion blasters as one of its wargear selections. However in the app I am unable to select Cyclic ion blasters as a weapon option, if this could be changed I would appreciate it very much.

Thank you.

**Comment by Mad-Spy** [comment]
It's specifically forbidden on p89 of the Codex, in the asterisked section of the Ranged Weapons list.
