### ISSUE TITLE
Imperium - Adeptus Ministorum: Canoness weapon validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3412]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Adeptus Ministorum - Canoness may take an chain sword in addition to  having a second chainsword . validation, bug

**Comment by Mad-Spy** [comment]
I don't see this option on the datasheet? There doesn't appear to be any option for her to get two melee weapons.

**Comment by Viper666-Qc** [comment]
The Canoness a Chainsword and Bolt Pistol as basic. She can exchange her bolt pistol for a ranged or pistol weapon but not an melee weapon.

**Comment by Mad-Spy** [comment]
The Canoness can't take two chainswords on her datasheet, and it's not possible in the datafile. Closing ticket.
