### ISSUE TITLE
Necrons: Too Many Artefacts Error?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3423]
**File:** Necrons.catz

**BattleScribe version:** 1.01.56

**Platform:** Android

**Dropbox:** No

**Description:** During army creation.  You keep getting an error message over Artifacts of the Aeons.  It still has a limit of 1, even though you can spend command points to have additional options.

**Comment by GenWilhelm** [comment]
Have you selected a Warlord? The first artefact that you may take is for having a NECRONS Warlord.

**Comment by Mad-Spy** [comment]
Yep, all seems to be fine as far as I can see. Selecting a "Dynastic Heirlooms" choice allows selection of the correct number of Artifacts.
