### ISSUE TITLE
Harlequins Open-topped rule incorrect

### ISSUE THREAD

**Issue by BerkshireKnight** [BSData/wh40k#3425]
Final sentence of Harlequins Starweavers' Open-topped rule reads, "Note that the passengers cannot shoot if this model Falls Back, even though the vehicle itself can." The rule in the Codex states the exact opposite: "Note that, due to their Rising Crescendo ability, the passengers can shoot if this model falls back."

**Comment by FarseerVeraenthis** [comment]
that is the index wording that was obviouslt missed in the update to the Codex version.
Great spot!!
