### ISSUE TITLE
T'au Support System Point Values Incorrect for Imperial Armor units

### ISSUE THREAD

**Issue by JamesPoulsen86** [BSData/wh40k#3428]
File/Catalogue: Warhammer 40K / T'au Empire v26

BattleScribe version: 2.01.21.

Platform: Android

Dropbox: No

Description: I've reviewed the Imperial Armour Index: Xenos book, the T'au Empire codex, and the latest FAQ for them (plus the "BIG" FAQ and BRB FAQ) and I think the point values for the Support Systems for Imperial Armour units are supposed to be different. I've attached a screen capture of the Imperial Armour Index: Xenos book of the point values for the units in there. The unit datasheets for Imp Armour Index Xenos units say to reference the support systems listed in the Imp Armour Index Xenos, not the T'au Empire Codex (which was probably not out at that time). I think these different point values would need to be followed especially for Y'vahra's as the systems have a special value if equipped on a Y'vahra.
![capture](https://user-images.githubusercontent.com/2336982/44287579-906a1e80-a22a-11e8-8154-a13c1902ceed.PNG)

**Comment by JamesPoulsen86** [comment]
I also just noticed the point values for an MV84 Shielded Missile Drone is 50 points in BattleScribe. That should be 49 (25 for drone, 24 for missile pod).

**Comment by alphalas** [comment]
Actually drones include wargear in their price so one SMD should be 25pts period.

As to the Y’Vahra, the designers commentary say to use the newest points value printed for wargear; so until FW says otherwise I’d say all SupSystems *HAVE* to use the codex prices to be correct.

**Comment by JamesPoulsen86** [comment]
Alrighty. All looks good then.

**Comment by amis92** [comment]
As @alphalas said, wargear prices will stay until an FAQ comes out directly amending these costs.

Those that called out specifically `(Y'vahra)` were left as is, all other were updated to Codex points.


MV84 drones cost 25 per drone as they should. You've probably taken 2, or something else is wrong.
