### ISSUE TITLE
Termite assault drill duplicated

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k#3431]
The Space Marine Forgeworld file has the assault drill in the file twice.
once as the termite assault drill
and then as terrax-pattern termite assault drill.

The terrax-pattern is the correct entry with the correct rules.
The entry without the terrax-pattern needs to be removed.

**Comment by alphalas** [comment]
Since units go off the Actual Name™️of the data sheet, the fact that the old drill is just a termite drill, and the new drill is the Terrax Pattern means they are actually separate models. See also Arkurian pattern baneblade chassis vs non-arkurian pattern Baneblade chassis, the Ryza and Styges pattern Vanquishers, etc.

**Comment by rsochia** [comment]
The listing in the file without the terax-pattern in its name is the old data sheet with the old info. They updated the data sheet.

I have included the old and the new data sheet so you can see it was alway called the terax pattern assault drill.

Old
[warhammer_40000_termite_assault_drill_en.pdf](https://github.com/BSData/wh40k/files/2300964/warhammer_40000_termite_assault_drill_en.pdf)

New
[Terrax-pattern-Termite-Assault-Drill.pdf](https://github.com/BSData/wh40k/files/2300965/Terrax-pattern-Termite-Assault-Drill.pdf)

the old data file was added to the forgeworld file with out the terrax-pattern in its name. So therefore it needs to be removed from the file as it does not exist and has been updated.

**Comment by rsochia** [comment]
You have marked this as will not fix.

I have asked forgeworld about the old data sheet and the new data sheet. specifically if the new one replaces the old one and if the old one is still valid to use.

following is the response they sent me. In it they state the only rules are the ones that are currently on the website.


Forgeworld <forgeworld@gwplc.com> | Thu, Aug 23, 2018 at 10:20 AM
-- | --
To: Robert Sochia <rsochia2@gmail.com>
Hello,
Thanks for your email.
The latest rules for this model can be found on it's product page here, these rules are the ones that should be referred to for usage in games.
I hope I've been of assistance with this, but if there's anything else I can help with, please let me know. 
Kind Regards, 
Daniel 
How would you rate my reply?
Great    Okay    Not Good
--Daniel Scriver
forgeworld@gwplc.com
