### ISSUE TITLE
Imperium - FW Adeptus Astartes: Chaplain Venerable Dreadnought Warlord/Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3440]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Chaplin Venrable dreadnought cannot be made a Warlord or be given a relic. However it should be able to.

-----

 - [x] Codex: Space Marines
 - [x] Codex: Blood Angels
 - [x] Codex: Dark Angels
 - [x] Codex: Deathwatch
 - [x] Codex: Space Wolves

**Comment by GenWilhelm** [comment]
Closed by 31dd9c3665d3a0d2972252ad66b12ac6df6ec604.
