### ISSUE TITLE
Invalid Term Captain Wargear, Imperium - Deathwatch.catz

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k#3443]
**File/Catalogue:** Deathwatch.catz

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Battlescribe lists Power Lance and Auxiliary Grenade Launcher as valid wargear for a Watch Captain in Terminator Armor.

Per Designer's Commentary FAQ, if model had wargear available in the Index, it could be used with the Codex datasheet.

The INDEX version of the Terminator Captain said to use a standard Terminator captain datasheet, _however_, the only legal changes were from a Power Sword ->Relic blade.  As such, equiping a Power Lance, or having an auxiliary grenade launcher, is _not_ a valid Index wargear.

In the Deathwatch Codex and Deathwatch Codex FAQ, the Watch Captain in Terminator armor WAS given more wargear options, but neither the Codex nor the Codex FAQ allow for a Power Lance, or an Auxiliary Grenade launcher, to be taken.

As it was not a valid Index option, nor a valid Codex or Codex FAQ option, the Wrist Mounted Grenade Launcher should be removed as an option, and Power Lance should be removed from the valid melee weapon list.

**Comment by acebaur** [comment]
Will be fixed in the next update
