### ISSUE TITLE
Bug: Space Marines Scout Sergeant can take double primary weapons

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#3453]
**File/Catalogue:** Imperium - Space Marines v56

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Scout Squad Sergeant can take a Shotgun/Boltgun/Combat Knife/Sniper Rifle as 1 weapon option and then take a second boltgun/combi-weapon on top, even though he has to swap his initial boltgun for any of these options. Essentially, allows him to take double the amount of primary weapons that he should be able to equip.

**Comment by williamcaw** [comment]
Is ther any more information about this issue?
