### ISSUE TITLE
ForgeWold Knights data

### ISSUE THREAD

**Issue by DuelWield** [BSData/wh40k#3456]
**File/Catalogue:** 
![screenshot_20180828-002655](https://user-images.githubusercontent.com/42762093/44702438-1a9b5980-aa59-11e8-848f-32148d0a7ea1.png)
![screenshot_20180828-002651](https://user-images.githubusercontent.com/42762093/44702450-29820c00-aa59-11e8-817c-21320b83e9be.png)
![screenshot_20180828-002648](https://user-images.githubusercontent.com/42762093/44702456-30108380-aa59-11e8-8606-d00bdb432583.png)
![screenshot_20180828-002639](https://user-images.githubusercontent.com/42762093/44702467-369efb00-aa59-11e8-8942-fbd685b4fbb5.png)

**BattleScribe version:** 2.01.21.283

**Platform:** Android

**Dropbox:** No

**Description:** The FW knights no longer are able to be selected as Exalted Courts and cannot take Relics.

**Comment by CrusherJoe** [comment]
Exalted Court and Heirlooms of the Household strategems specifically call out QUESTORIS and DOMINUS class knights only. Thus the only FW knights that can take advantage of those strats are the Styrix and Magaera (as they are Questoris class).
