### ISSUE TITLE
Imperium - Space Marines: Unable to find Gravis Captain

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3458]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** According to GW the Primaris Captain from the DI box comes with a master-crafted power sword and a boltstorm gauntlet; neither of those can be selected.
Could be my limited 40k experience, could be bug, pls check and if necessary, add those options to the Primaris Captain. Thx!

**Comment by Mad-Spy** [comment]
You want the Captain in Gravis Armour, which is a separate entry.
