### ISSUE TITLE
Space Wolves codex omissions

### ISSUE THREAD

**Issue by knotdragon** [BSData/wh40k#3463]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

No land speeder storm
Lone Wolves still an option but aren't in the new codex

**Comment by knotdragon** [comment]
Also the helfrost destructor on the stormfang gunship now costs zero points instead of 50

**Comment by GenWilhelm** [comment]
Consolidated into #3462.
