### ISSUE TITLE
Imperium - Questor Imperialis: Data file crashes on Android

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3465]
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 1.08.08

**Platform:** Android

**Dropbox:** No

**Description:** No imperial knight data available. Causes app to crash... using latest version of app

**Comment by Mad-Spy** [comment]
Unable to replicate on v2.01.21.283 with IK v21.

**Comment by Kohato** [comment]
Current Version
2.01.21

BattleScribe version: 1.08.08

Please update your BS version.
