### ISSUE TITLE
Imperial Knight relics disappeared

### ISSUE THREAD

**Issue by DuelWield** [BSData/wh40k#3472]
**File/Catalogue:** 

**BattleScribe version:** 2.01.21.283

**Platform:** Android

**Dropbox:** No

**Description:** all forgeworld knight are not able to take Exalted court and cannot take Relics. Even when set as warlord.

**Comment by Mad-Spy** [comment]
Exalted Court and Heirlooms of the Household strategems specifically call out QUESTORIS and DOMINUS class knights only. Thus the only FW knights that can take advantage of those strats are the Styrix and Magaera (as they are Questoris class).

**Comment by DuelWield** [comment]
Thank you. I have misread there strat key words.

**Comment by DuelWield** [comment]
Now. If the FW model is the warlord. They should be allowed to take a relic. I seen nothing in the codex stating only dominus, questoris, or armiger class getting to take Relics (Heirlooms).
