### ISSUE TITLE
Imperial Knights: Armiger warlords have no access to Heirlooms

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3475]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When assigning a armiger as warlord or character cannot assign heirlooms to the character. Double checked rules but cannot see anything suggesting this cannot be done.

**Comment by williamcaw** [comment]
Sanctuary, armor of the sainted ion, helm of the nameless warrior , Mark of the Omnisaiah and any house can Heirloom may apply

**Comment by Kohato** [comment]
Yea ... I had a checkbox not checked.  Fixed :D

**Comment by Kohato** [comment]
Also - just to clarify - an armiger HAS to be the warlord to get relics. They don't get relics via strat.  I know it was broken in that case too, but just fyi.
