### ISSUE TITLE
Multiple warlord traits requested in Elysian force

### ISSUE THREAD

**Issue by Millambr** [BSData/wh40k#3477]
File: Warhammer 40,000 8th Edition.gstz
Imperium - FW Elysians

BattleScribe v2.01.15.114

Windows 10 64bit

Dropbox: No

Even when one model is selected as the warlord, there are errors for the other company and platoon commanders.

For example
"Elysian Platoon Commander must have 1 more selections from Warlord Traits (minimum 1)"

![image](https://user-images.githubusercontent.com/17701144/44765510-5f79da00-ab98-11e8-9ab4-76f616566296.png)

**Comment by Mad-Spy** [comment]
Do you have the latest version of the file (v28)? I'm not able to replicate this issue.

**Comment by Millambr** [comment]
Yes I do have v28.

I have just remade most of the list and the issue is still there. One commander is selected as the warlord and has a warlord trait selected, and now all the rest of the commanders show as needing a warlord trait.
It all works fine otherwise, just has that validation error.

I have attached the roster file.

[Elysian test.zip](https://github.com/BSData/wh40k/files/2331808/Elysian.test.zip)

**Comment by Mad-Spy** [comment]
Ok, looks like it's something to do with having the AM child detachments, which is why I couldn't replicate it. It works fine if you just have a straight Elysian detachment.

I'll try and track down the problem.

**Comment by Mad-Spy** [comment]
Looks like a weird interaction between the requirement to have a Warlord Trait and child detachments. Fixed by removing the requirement to have a Trait (as it's not mandatory at list building time) and tidying up the visibility conditions.

**Comment by Millambr** [comment]
Thanks very much for that. I really appreciate all the hard work you guys do.
