### ISSUE TITLE
FW Death Korps: Missing Infantry Weapons on Earthshaker Carriage Battery

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#3490]
**File/Catalogue:** FW Death Korps

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:**
All the Carriage Batteries have the Lasgun and Frag Grenades for the Crewman, except the Basilisk Carriage Battery.
But the Imperial Armour Index for Astra Militarum also lists those Weapons for this one.

**Comment by Mad-Spy** [comment]
The Infantry weapons on this crew don't have max1/min1 set, so they're not being assigned as defaults.
