### ISSUE TITLE
SW BattleScribe Issues

### ISSUE THREAD

**Issue by CrossEternal77** [BSData/wh40k#3492]
**Warhammer 40,000 8th Edition v57/Imperium - Space Wolves v41:** 

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** 
Items to Remove (No longer Codex options):
- Rune Priest on Bike
- Wolf Guard Battle Leader on Bike
- Wolf Priest on Bike
- Iron Priest on Bike
- Iron Priest on Thunderwolf
- Wolf Guard Bikers

Things Missing/Changes:
- Wolf Guard Battle Leader Jump Pack cost from 3 points to 18 points
- Stalker is missing from Heavy Support
- Fenrisian Great Axe profile is incorrect, it should be as below:
  Fenrisian Great Axe:When attacking with this weapon, choose one of the following profiles below.
  Cleave:Melee:Melee:+4:-3:D6:When attacking with this weapon, you must subtract 1 from the hit roll
  Scythe:Melee:Melee:User:-3:1:Make 2 hit rolls for each attack made with this weapon instead of 1
- Great Wolf Claw should be damage 3 instead of D6
- Lukas the Trickster's **Blood Claws Hero** has changed to the following:
   **Blood Claws Hero:** You can re-roll wound rolls of 1 for friendly **Blood Claws** units that are within 
   6" of this model._

**Comment by Kohato** [comment]
No worries, keep bug reports coming, the rest is valid.  Joe's one dude and can't be expected to catch it all :)

**Comment by CrossEternal77** [comment]
Wolf Guard Battle Leader has 3 attacks instead of 4 now. Forgot to add that one

**Comment by Soukypoof** [comment]
New relics need to be added

**Comment by coxey292** [comment]
The Wolf Guard Pack Leaders also have new costs.  16 for for the Grey Hunters and Blood Claws, etc...

**Comment by coxey292** [comment]
The Wulfen squad leaders are 1 point too expensive.  Should be 28 for the model and 14 for the claws for a total of 42 but they cost 43 for some reason.

**Comment by GenWilhelm** [comment]
Frost claws are 15 points, not 14, so 43pts is correct for the leader.

**Comment by coxey292** [comment]
You are right, I was looking at wolf claws. Sorry about that.

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 31, 2018 at 7:28 AM, Will Pattison<notifications@github.com> wrote:   
Frost claws are 15 points, not 14, so 43pts is correct for the leader.

**Comment by CrusherJoe** [comment]
All of these issues are fixed in v46 of the datafile.
