### ISSUE TITLE
Request: Option to take +1/+2 extra relics for Dark Angels

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#3496]
**File/Catalogue:** Imperium - Dark Angels v62

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Dark Angels can only take 1 Relic for free at the moment. If you try to take any more to represent purchasing more relics with Command Points, the roster throws an error saying you can only take 1 max.

**Comment by Mad-Spy** [comment]
If you select one of the "Relics of the Rock" item from the Uncategorised group in the Roster, you will be able to add additional Relics based on your selection.
