### ISSUE TITLE
Aeldari - Craftworlds: Force Shield should not have a cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3498]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Aeldari Autarch Force Shield is charges at 6pts. Since this is an ability, not an item of wargear (It's not an option on his data card) this should be free.

**Comment by Mad-Spy** [comment]
This was addressed in the Craftworlds FAQ. The Forceshield was added as an item of wargear and therefore has an associated cost.
