### ISSUE TITLE
Imperium - Space Wolves: Fury of the Wolf Spirits Description

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3501]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The new spell Fury of the Wolf Spirits (Tempestas discipline) shows the description for Murderous Hurricane.

**Comment by CrusherJoe** [comment]
Fixed in v46 of the datafile.
