### ISSUE TITLE
Death Guard - Rhino options error

### ISSUE THREAD

**Issue by 7ede** [BSData/wh40k#3509]
**File/Catalogue:** 
Chaos - Death Guard.cat

**BattleScribe version:** 2.01.

**Platform:** All

**Dropbox:** No

**Description:** Death Guard Rhino can't take combiweapons (combiflamer-melta-plasma). As you can see in Codex (and errata/FAQ) the DG Rhino has only Havoc Missles and the standard bolter

**Comment by GenWilhelm** [comment]
The Chaos Rhino datasheet has the wargear option to do so:
> • This model may take one item from the *Combi-weapons* list.

**Comment by 7ede** [comment]
Yes, CHAOS Rhino in Chaos Codex say that. But in DG Codex there are different rules...If I’m going to play a DG army I’ll use the DG specific rules written in DG Codex, not the Chaos rules from an other Codex! Otherwise why in the TS Codex there are still different armament options? If it were a bug in the book GW would correct it in the "errata", but they don’t...
