### ISSUE TITLE
Iron Priests can't change their gear

### ISSUE THREAD

**Issue by Luminoth** [BSData/wh40k#3514]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** For whatever reason, the codex removed the ability to change any of the Iron Priests gear, but it's still changeable in BS

**Comment by GenWilhelm** [comment]
Index wargear options are still legal, as per the Designers' Commentary:
https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/warhammer_40000_designers_commentary_en-1.pdf
