### ISSUE TITLE
Imperium - Blood Angels: Captain in Cataphractii Armour Weapon Validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3517]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Blood Angels

Captain in Cataphractii Armour displays a validation error when melee weapons are chosen from anything other than the top 3 melee options along with any range weapons 

"Captain in Cataphractii Armour has 1 too many selections from Ranged/melee weapon (maximum 1)

**Comment by williamcaw** [comment]
recreated issue validation
