### ISSUE TITLE
Imperium - Space Wolves: Fury of the Wolf Spirits Description

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3522]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Space Wolves Psychic powers, Fury of WOlf Spirits has the same description as Murderous Hurricane.  Also, not clear on why you can choose the same power multiple times for Living Lightning, Murderous Hurricane, and Fury o fthe WOlf Spiritys.

**Comment by CrusherJoe** [comment]
Please update your datafiles -- this was fixed in the latest release.

**Comment by GenWilhelm** [comment]
This was still an issue when I check on Njal.
