### ISSUE TITLE
Imperium - Dark Angels: Relic Visibility

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3525]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** A librarian cannot take a relic anymore. This used to work and should work according to the Codex.

**Comment by williamcaw** [comment]
Type bug. Recreated. won’t show up untell librarian updated to be a alloed to selection after being selected as warlord and  selecting relic

**Comment by GenWilhelm** [comment]
This is working as intended. The only way for a Dark Angels character to take a relic is to have a Dark Angels Warlord, or use the "Relics of the Rock" stratagem.
