### ISSUE TITLE
Blood angels devastator unit issue

### ISSUE THREAD

**Issue by michaelsmitzel** [BSData/wh40k#3529]
**File/Catalogue:** current

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** no

**Description:** Detailed issue description.

When I add the devastator squad to my detachment, it didn't give me the units characteristics when I view the roster. No M, BS, WS, S etc..

**Comment by williamcaw** [comment]
recreated
