### ISSUE TITLE
Imperium - Space Wolves: Wolf Lord and Reiver issues.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3534]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Incorrect entries in 
Wolf Lord:
Should be able to equip a Storm Shield - currently no such option.

Reivers:
The Reiver Sergeant should be able to exchange either his Bolt Carbine or a Heavy Bolt Pistol for a Combat Knife

**Comment by GenWilhelm** [comment]
The storm shield is a replacement for his chainsword.

![lord shield](https://user-images.githubusercontent.com/22036809/44982207-0a114480-af6d-11e8-98b1-92c19467c63e.png)
