### ISSUE TITLE
Imperium - FW Adeptus Astartes: Error with Relic model validation in SHAD

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3536]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** When I use a Relic Model in a Super-Heavy Axillary Detachment, it doesnt warn me, that Relic Models should be 0.

**Comment by GenWilhelm** [comment]
Using just one Relic unit, it shouldn't. As per the FAQ, you can use one Relic Lord of War in an army even if it contains no other Lord of War.
https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/imperial_armour_index_forces_of_the_adeptus_astartes-1.pdf

>Page 4 – Additional Rules, Relic
Change the first paragraph to read:
‘If your army is Battle-forged, no Detachment can contain more Relic units than it does non-Relic units of the same Battlefield Role. You can, however, include a single Relic Lord of War unit in your army even if it contains no non-Relic Lord of War units (you cannot include second and subsequent Relic Lord of War units unless they are taken in a Detachment that contains at least as many non-Relic Lord of War units).’

This is extremely difficult for BattleScribe to accurately validate, and the current implementation is pretty close the best we can do, with it only failing in some edge cases.

**Comment by Mad-Spy** [comment]
As per previous comment, validating this perfectly is not possible in the current version of BS. We hope it will be possible in a future version.
