### ISSUE TITLE
Imperium - FW Death Korps: Tank Commander stats incorrect

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#3545]
**File/Catalogue:** FW Death Korps

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:**
I can't find the Tank Commander in the forgeworld Index Astra militarum.
But in battlescribe it's possible to choose it as HQ. Where does this Option come from?
And shouldn't it have a BS3 instead of BS4?

**Comment by Mad-Spy** [comment]
The Tank Commander is inherited from Codex: Astra Militarum, which has superseded the instructions on p55 to take the sheet from Index: Imperium 2.

![image](https://user-images.githubusercontent.com/29306451/45123899-51abf200-b160-11e8-8636-b96da9bb69d0.png)

You are correct that the model's BS is wrong.
