### ISSUE TITLE
Imperium - Space Wolves: Sky Claw Pack Leader should have default bolt pistol

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3556]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Select skyclaws You are required to give the skyclaws pack leader a special weapon, although he cannot take this as an option in the codex

**Comment by Mad-Spy** [comment]
The implementation is technically correct because the Pack Leader is able to take a special weapon, as per the first bulletpoint on the datasheet. However, the Leader should be defaulting to a bolt pistol, which does need fixing.
