### ISSUE TITLE
Imperium - Space Wolves: Incorrect cost for Blizzard Shield

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3557]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.21.28

**Platform:** Android

**Dropbox:** No

**Description:** The points for the Blizzard Shield are wrong. It should be 15 instead of 0 and 17 with storm bolter.

**Comment by williamcaw** [comment]
Relax it’s being fixed we are only human

**Comment by CrusherJoe** [comment]
This was fixed back in v47 or 48 of the datafile -- please update your data.
