### ISSUE TITLE
Imperium - Space Wolves: Skyclaw special weapon validation

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#3558]
Only two models in a Skyclaw unit should be able to take a special weapon, currently there is no restriction.

**Comment by CrusherJoe** [comment]
Actually the restriction is there, it throws validation errors, see attached screenshot.
![skyclaws](https://user-images.githubusercontent.com/9998385/45234593-d2233d80-b29b-11e8-9e1e-bf8f5db53be6.PNG)
