### ISSUE TITLE
Imperium - FW Adeptus Astartes: Contemptor Mortis should not have access to missile launchers?

### ISSUE THREAD

**Issue by MountyChris** [BSData/wh40k#3561]
FW ~~Heretic~~ Adeptus Astartes Catalogue. 

The contemptor mortis has the option to take missile launcher arms, but do not believe this is a valid selection.

**Comment by Mad-Spy** [comment]
Have you referenced the correct catalogue? There is no Contemptor Mortis in the FW Heretic Astartes catalog.
