### ISSUE TITLE
Repositories are not available for download

### ISSUE THREAD

**Issue by SpaceJS** [BSData/wh40k#3562]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Repositories are not available for download

URL's are not reachable

**Comment by Mad-Spy** [comment]
Hi, I'm afraid we don't really have any control over the appspot page. It looks like it's having some technical difficulties right now, but I'm sure it will be back as soon as possible.

**Comment by SpaceJS** [comment]
would it be a idea to put a status view on the main website to prevent questions about it?

**Comment by GenWilhelm** [comment]
We don't have any say over what happens on appspot, other than publishing data files to it.

It's all handled by the BSData/BSData repo, where it appears there is already an issue open: https://github.com/BSData/bsdata/issues/204

**Comment by alphalas** [comment]
There use to be an open reference issue about it so that people could see as they’re signing in to point it out to us; but it was closed.
