### ISSUE TITLE
Chaos - Chaos Space Marines: Plague Marines w/ Melee Don't Count Towards Power

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3566]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Using Plague Marines as an elite choice for CSM detachment and adding bolter marines increases Power Level like normal, however adding additional melee marines adds the points cost, but not the Power Level increase.

**Comment by Mad-Spy** [comment]
Well, just goes to show how few people play with PL!
