### ISSUE TITLE
Chaos - Death Guard: Unable to select wargear for Plague Champion

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3579]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Unable to choose items from the champions wargear for the plague marine champion.

**Comment by Mad-Spy** [comment]
First, select whether you are using Index or Codex wargear, then tap on the Codex/Index entry to get to the wargear options. You need to tap at the left hand side of the entry, not on the radio button, which us used to choose between the two modes.
