### ISSUE TITLE
Inconsistent relic/warlord behaviour

### ISSUE THREAD

**Issue by someguyss** [BSData/wh40k#3585]
**File/Catalogue:**

**BattleScribe version:** 2.01.15.114

**Platform:** Linux

**Dropbox:** No

**Description:**  Current relic and warlord behaviour over different forces varies heavily. For example Chaos Marine detachments can't take relics at all until they select a warlord and then have to take the No Force Org Slot _Gift of Chaos_ selection (1 or 2 relic options) to take more or Battlescribe will throw a verification error. Astra Militarum detachments on the other hand can take relics without a warlord/stratagem selection at all and can take any number of them at once as long as they don't have duplicates.

If possible consistent behaviour across all files would be better.

**Comment by Kohato** [comment]
All catalogs should have relics hidden unless a warlord of the proper faction is selected OR the relevant stratagem is chosen.

They should be limited to 1 per roster (or 2 or 3 pending stratagem)

Relics should also be hidden from the list of models that are not valid choices

Any deviation from this behavior needs to be listed as an issue/bug for that catalog.

Catalogs are not all maintained by the same people, you've pointed out AM and CSM - which we can assign issues to those maintainers, are they any others you have noticed?

**Comment by Kohato** [comment]
You've made issues for Sisters and IG - Tagging this one for our CSM maintainer.

**Comment by Mad-Spy** [comment]
Untagged CSM because it is correct.

**Comment by someguyss** [comment]
>Catalogs are not all maintained by the same people, you've pointed out AM and CSM - which we can assign issues to those maintainers, are they any others you have noticed?

CSM is actually correct, I only pointed it out as an example of how it should function. However it also applies to the following armies in addition to the Imperial Guard:

'''1.''' Space Marines (haven't checked the sub-types)
'''2.''' FW Elysians (sub-type of IG)
'''3.''' FW Death Korps of Krieg (sub-type of IG)

Orks as of now work fine, their relic only appears when a character is selected as a warlord. However it appears in the normal wargear section instead of in a separate relic section as with everyone else and it might be more consistent to have it show up in its own section instead (it's also something that will have to be done if/when they get a codex).

> You've made issues for Sisters and IG - Tagging this one for our CSM maintainer.
Actually the separate Sister and IG issues are a bit different, those are validation issues with specific relics (e.g. picking a bolt pistol relic without having a bolt pistol) not with how relic assignment works overall.

**Comment by someguyss** [comment]
> Any deviation from this behavior needs to be listed as an issue/bug for that catalog.

I can always split them up into four separate issues (one IG, one SM, one Elysian and one Death Korps) if that's easier for everyone. Orks is more of an 'it works now but might not in future' so I'm not sure that's a bug strictly speaking.

**Comment by someguyss** [comment]
> Relics should also be hidden from the list of models that are not valid choices

Also worth noting that the Grey Knights are set up properly with the exception that their relic selection is always available (i.e. it isn't hidden when you don't have a Warlord or pick the Stratagems). Battlescribe **will** throw an error if you pick a relic anyway so the validation is working but the relic wargear section should probably not appear at all if you can't pick one.


I've checked all the remaining armies and they all look to be fine. it's only those four (Guard, the two FW Guard spin-offs and vanilla Marines) and then minor consistency issues with Grey Knights and Orks. Would you like them re-submitted as separate issues?

**Comment by Kohato** [comment]
That would help I think - that way the maintainers for each can commit and close them as they are fixed.

**Comment by someguyss** [comment]
Right, I'll get on that now.

**Comment by someguyss** [comment]
Done, added an Ork and a Grey Knight issue as well. I've also noticed some specific relic issues for the Space Marines which I'll add in a few minutes once I've double checked them all.

**Comment by Kohato** [comment]
Thanks! This is a labor of love for us done when we have time to address issues so listing out helps a lot.

**Comment by someguyss** [comment]
No problem, I'll try and add anything else if/when I find it.
