### ISSUE TITLE
Imperium - Astra Militarum Specific Relic Validation Issues

### ISSUE THREAD

**Issue by someguyss** [BSData/wh40k#3586]
**File/Catalogue:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.15.114

**Platform:** Linux

**Dropbox:** No

**Description:** The weapon based relics can be picked without their underlying weapons (skipping the cost of purchasing them). The easiest way to solve this might be to simply bake the cost of the weapon into the relic (e.g. Pietrov's Mk 45 needs a bolt pistol so the relic itself could cost 1pt to take) and have them conflict with the base weapon (so a Lord Commisar would have to drop his power sword for -4 points to take the Power Sword relic at +4 points), alternatively don't have it show up unless the model already has a bolt pistol similar to how e.g. Corruption works as a relic for Nurgle Daemons.

Please note that the regiment verification is working fine (that is the VALLHALLAN-only relic is correctly only usable when picking that doctrine)

**1** Pietrov's Mk 45: can be given to models without a bolt pistol but says bolt pistol only
**2** The Blade of Conquest: should be equipable on models with power swords only
**3** Claw of the Desert Tigers: should be equipable on models with power swords only
**4** Mamorth Tuskblade: should be equipable on models with power swords only
**5** The Emperor's Benediction: replaces any Commisar or Lord Commisar's bolt pistol (which they come with by default), however they can swap the bolt pistol to a boltgun or plasma pistol and still equip the relic 

**Note:** See also #3587 for a more general AM issue with Relics and Warlords.

**Comment by amis92** [comment]
@alphalas any comment? These are legitimate bugs, as far as I can see.

**Comment by alphalas** [comment]
@amis92 from what I recall the last time this topic came up on the gitter the conclusion was that while relic validation is a nicety, there is as much argument for not validating and saving the line count, meaning in the end the choice to include is still up to the maintainer. I personally don’t see the need, especially since we already include the restriction verbiage in the profiles.

**Comment by amis92** [comment]
That's fine. Just, you know, closing without any comment about the reason == bad. Gitter chat doesn't count.

**Comment by alphalas** [comment]
Fair enough.
