### ISSUE TITLE
Imperium - Space Marines Inconsistent Relic/Warlord Behaviour

### ISSUE THREAD

**Issue by someguyss** [BSData/wh40k#3590]
**File/Catalogue:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15.114

**Platform:** Linux

**Dropbox:** No

**Description:** Relics selection should be hidden unless there's either a Space Marine Warlord picked or the relevant stratagem is chosen. This means the following changes are needed

- Two new options under No Force Org Slot: 'Relics of the Chapter (1 Relic)' and 'Relics of the Chapter (2  Relics)'

- The 'Relics' wargear selection menu for characters should be hidden by default and shown only when either a Warlord is picked or one of the two new stratagems above is selected

- Relics should be limited to either 0, 1, 2 or 3 total (depending on combination of Warlord and Stratagems) otherwise throwing a validation error

**Comment by williamcaw** [comment]
Is ther any status to be updated?
