### ISSUE TITLE
Orks - Inconsistent Relic Behaviour

### ISSUE THREAD

**Issue by someguyss** [BSData/wh40k#3593]
**File/Catalogue:** Orks.catz

**BattleScribe version:** 2.01.15.114

**Platform:** Linux

**Dropbox:** No

**Description:** Currently Orks only have one relic available and this is (correctly) hidden unless a warlord is picked. However when it **is** available it simply appears as another wargear item instead of in a separate menu as with every other army currently in battlescribe. It would be more consistent to have it sectioned off into a separate relic menu that is hidden until a warlord is picked (Orks have no Stratagems for picking extra relics so that's not a concern).***

If it is separated it should be limited to one per army (of course) and also should only be selectable by a character armed with a big choppa which it replaces (they must spend 7 points on the big choppa first). Currently both of these are validated correctly.

**Comment by Mad-Spy** [comment]
Given that Codex: Orks will be out in the next couple of weeks and the Relics will need reworking at that point, I'm going to close this for now.
