### ISSUE TITLE
Imperium - Space Marines Specific Relic Validation Issues

### ISSUE THREAD

**Issue by someguyss** [BSData/wh40k#3595]
**File/Catalogue:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15.114

**Platform:** Linux

**Dropbox:** No

**Description:** Some weapon based relics can be picked without their underlying weapons (skipping the cost of purchasing them).

**1** The Axe of Medusa: should be equipable on models with power axes only
**2** The Fist of Vengance: should be equipable on models with power fists only
**3** The Sparteam: should be equipable on models with bolt pistols only
**4** Raven's Fury: should be equipable on models with jump packs only

**Note:** See also #3590 for a more general Space Marine issue with Relics and Warlords.

**Comment by williamcaw** [comment]
Has there been any progress in status of requests?
