### ISSUE TITLE
W40k Space Wolves Wolf Lord

### ISSUE THREAD

**Issue by Darikson** [BSData/wh40k#3596]
**File/Catalogue: Space Wolves V48** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:**No

**Description:** Hi, I see one bug with the wolf lord, When I select any melee weapon it counts as range weapons, and show a error message, thanks. How can I help to solve this errors on battlscribe?

**Comment by Mad-Spy** [comment]
If you are swapping the Lord's master-crafted boltgun for a melee weapon, you will need to unselect his boltgun to avoid a validation error. Changing just the melee weapon (in the Wolf Lord Melee Weapon option) gives no error.
