### ISSUE TITLE
Imperium - Space Wolves: Wolf Priest power fist validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3597]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Wolf priest can take combi weapons, when in codex there is only the option to replace the bolt pistol with a plasma pistol. In addition if you take a power fist fir the wolf priest, it shows an error saying the max ammount of powerfists is 0. In codex the wolf priest can take a power fist.

**Comment by Mad-Spy** [comment]
The combi-weapons are allowed as he had access to them in the Index.

Power fist issue needs to be fixed.

**Comment by CrusherJoe** [comment]
This problem was fixed in v50 of the data file.
