### ISSUE TITLE
Chaos - Death Guard: Lord of Contagion Points Cost Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3599]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Value of Lord of contagion is 120 points without armour or weapons

**Comment by FarseerVeraenthis** [comment]
Please read Chapter Approved 2017.
Lord of Contagion is listed there at 100 points on page 118.
