### ISSUE TITLE
Adeptus Mechanicus - Missing Warlord Traits and <Forge World> Relics

### ISSUE THREAD

**Issue by Relentless967** [BSData/wh40k#3608]
File/Catalogue: Imperium -  Adeptus Mechanicus.catz

BattleScribe version: 2.01.21

Platform: Android

Dropbox: No

Description: (First time reporting something, if this is the wrong place please let me know) When designating an ADMECH character as a warlord it currently does not enable a dropdown for warlord traits. Additionally, when the FORGE WORLD is selected, it does not enable the associated relics (IE, The Red Axe for a MARS detachment).

**Comment by Mad-Spy** [comment]
You need to click on the "Warlord" entry after selecting your Warlord to find the traits.
