### ISSUE TITLE
Tyranids - Miasma Cannon does not replace Venom Cannon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3613]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting Artifact, the Miasma Canon should replace the Heavy Venom Canon on the sheet (still pay the points for it), but it is just being added instead making it seem like you can be using both.

**Comment by Mad-Spy** [comment]
This is a deliberate design choice, and there is an entry added to the unit's abilities which states that the Miasma Cannon replaces the Venom Cannon.
