### ISSUE TITLE
Imperium - Astra Militarum: Commissars unable to take chainsword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3620]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Commisars seem to be missing Chainswords in the Melee Weapon list, yet according to the Codex they should be able to use them.

**Comment by williamcaw** [comment]
confirmed recreated.

**Comment by Mad-Spy** [comment]
This is not correct. Commissars have no option to take a chainsword. The Astra Militarum Melee Weapons list has never contained a chainsword, either in the Index or Codex.
