### ISSUE TITLE
Aeldari - Ynnari: Unable to create list

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3622]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Roster only has options for HQ available. No options are available for troop choices, elite choices heavy choices or any other choise.
As a result It is not possible to build a list using the app that contains all the correct rules for a Ynnari detachment

**Comment by williamcaw** [comment]
person is referring to the closed item Aeldari - Ynnari: No WL Traits for Ynnari HQs? #3607

**Comment by FarseerVeraenthis** [comment]
I think the response from @KalChoedan answers the question succinctly enough :smile:
