### ISSUE TITLE
Imperium - Space Wolves: No cost for Primaris Wolf Lord weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3628]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Primaris Wolf Lord can take weapons for free. It's mistake because weapons have a price.

**Comment by Mad-Spy** [comment]
@CrusherJoe, the problem here is that the sub-selections in the weapon choices don't have min1/max1, so they're not getting selected.
