### ISSUE TITLE
Chaos - Chaos Space Marines: Unable to create multi-Legion detachment without validation errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3634]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** When attempting to create a detachment(any detachment) you should be able to pick a Legion trait per unit instead of assigning the Legion Trait to the detachment as a whole. This would allow you to field Abaddon the Despoiler and Kharn the Betrayer in the same detachment for example. Currently, this is not possible. The usual workaround for generating multi-army detachments(i.e adding a detachment to a detachment to make "sub-detachments" does not work in this case as even though it does allow the selection of a second legion trait it does not make the specific HQs available in the detachment. For example, there is currently no way to add Abaddon the Despoiler to the same detachment as Kharn the Betrayer even though that should be able to function by the rules. The fix would either involve allowing detachments to have no "global" legion trait and also allow them to assign Legions per unit if they did not select a global one or at the very least have the multi-legion selection enable the correct choices for the mixed detachment.

**Comment by SpartenSoldier** [comment]
Sorry if this is a misunderstanding, but this bug isn't about Legion traits not applying its about the Legion Keywords not being able to be assigned per unit. In Battlescribe right now it is currently not possible for a mixed detachment of say Abaddon and Kharn the Betrayer to be created. As this was mentioned above and not in the closing message it seems incorrect to close this with that comment.

**Comment by cartag** [comment]
Select "No Legion Trait" and it will do a mixed detachment.

**Comment by SpartenSoldier** [comment]
Selecting "No Legion Trait" does let you select everyone but yields the following Roster Errors: "1 too many selections of Kharn the Betrayer(maximum 0)" and "1 too many selections of Abaddon the Despoiler(maximum 0)"

**Comment by cartag** [comment]
That, is a valid bug.

**Comment by SpartenSoldier** [comment]
The other point to this bug is that according to the codex in a mixed Legion Detachment you can actually assign individual units separate Legion tags.  So if I had 3 cultist squads I should be able to assign them Alpha Legion, Black Legion, and World Eaters for example. Perhaps this issue attempted to tackle to many problems at once. Would you suggest I open new separate issues for this?

**Comment by SpartenSoldier** [comment]
I think you are misunderstanding that sentence. "Includes units with one of these keywords" is not the same as includes units with ONLY one of these keywords. This is where mixed detachments come in. If you reread pg 116 in the codex you find the process for replacing the <Legion> tag. Note that it specifies you do this on a per unit basis. In the example they give in the third paragraph this is made relatively clear. Now you can elect to have all of the units from the same legion in a detachment and that is where Legion Traits come in. However, it is perfectly valid to build a detachment with all of the units replacing their respective <Legion> tags with different Legions.
