### ISSUE TITLE
Death Guard:  missing movement buff for Noxious Blightbringer.

### ISSUE THREAD

**Issue by SPEC4** [BSData/wh40k#3635]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by SPEC4** [comment]
I hope that I’m just being blind and can’t find were it has gone.  But we haven’t seen in any FAQ’s or errata that the movement buff was removed.

**Comment by Mad-Spy** [comment]
Sorry, what's the actual issue here? Is there something missing/incorrect on the profile.

**Comment by SPEC4** [comment]
Sorry I was not seeing things that were right in front of my face again.  I see now the the two dice roll for advancing was listed under Tocsin of Misery ability and just merged together.  I need to stop reading this at 4 am before work.
