### ISSUE TITLE
Chaos - Titanicus Traitoris: Problems with adding Knights to Titan detachments?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3644]
**File:** Chaos - Titanicus Traitoris.catz

**BattleScribe version:** 2.01.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** cant take Questor Traitors  by combining the "Questor traitoris super-heavy Detachment " this also locks away the the +6 command points and warlord and Character settings. 
Area: validation Type: request Type: bug cat: Chaos-Questor traitoris  cat: Chaos-Titanicus traitoris

**Comment by Mad-Spy** [comment]
Maybe you could explain exactly what you are trying to do?

Only QUESTOR TRAITORIS detachments (that is, detachments which ONLY have QT units in) can get the +6 command points and give models the CHARACTER keyword.

You can't put Knights and Titans in the same detachment and have access to the command points and traits.

**Comment by williamcaw** [comment]
i bleave the person is refering to the wording on the index INDEX: RENEGADE KNIGHTS that was releaced on  22/6/2018 it does state Titanicus "Questor Traitoris Super-heavy Detachment is
changed to ‘None’ if it does not contain at least one
Questor Traitoris Titanic"

**Comment by Mad-Spy** [comment]
@williamcaw, there's nothing in there about Titans?

A QUESTOR TRAITORIS TITANIC model is one which has both the QUESTOR TRAITORIS and TITANIC keywords, namely any except Armigers.

**Comment by Mad-Spy** [comment]
Without further clarification, I'm not able to resolve this. Closing.
