### ISSUE TITLE
Mortis Dreadnought change

### ISSUE THREAD

**Issue by DragoLord19D** [BSData/wh40k#3664]
**File/Catalogue:** 
FW Space Marines
**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux
iOS 
**Dropbox:** Yes/No
Yes
**Description:** Detailed issue description.
May I ask why you took the cyclone launcher from the Mortis dreadnought? Because last I checked the index they could take one.
![792deaee-4dcf-4b25-9fba-572e101b8437](https://user-images.githubusercontent.com/36297332/45935392-99a88280-bf70-11e8-9581-b5c72aefde9d.jpeg)

**Comment by Mad-Spy** [comment]
That's weird. The copy of IA:Forces of the Adeptus Astartes which I am working from does not have that option for the standard Mortis, based on the latest FAQ.

They did add it in in one of the early FAQs, but then took it away again in later versions.

**Comment by alphalas** [comment]
Can confirm, my ePub of IAI:FotAA indeed does not have an option for cyclones on mortis

**Comment by DragoLord19D** [comment]
Weird because mine does, when did you get your’s?

**Comment by DragoLord19D** [comment]
> That's weird. The copy of IA:Forces of the Adeptus Astartes which I am working from does not have that option for the standard Mortis, based on the latest FAQ.
> 
> They did add it in in one of the early FAQs, but then took it away again in later versions.

...Where? Because I cannot find it.

**Comment by Mad-Spy** [comment]
This is from FAQ 1.1

Pages 24 and 26 – Mortis Dreadnought and Contemptor
Mortis Dreadnought, Wargear Options
Add the following to both models’ wargear options:
‘• This model may take a cyclone missile launcher.’

FAQ 1.3 has:

Pages 26 and 28 – Contemptor Mortis Dreadnought and
Relic Contemptor Dreadnought, Wargear Options
Add the following to both models’ wargear options:
‘• This model may take a cyclone missile launcher.’

**Comment by DragoLord19D** [comment]
> This is from FAQ 1.1
> 
> Pages 24 and 26 – Mortis Dreadnought and Contemptor
> Mortis Dreadnought, Wargear Options
> Add the following to both models’ wargear options:
> ‘• This model may take a cyclone missile launcher.’
> 
> FAQs 1.2 and 1.3 have:
> 
> Pages 26 and 28 – Contemptor Mortis Dreadnought and
> Relic Contemptor Dreadnought, Wargear Options
> Add the following to both models’ wargear options:
> ‘• This model may take a cyclone missile launcher.’

Oh...
Damnit, at least I didn’t glue them on...

**Comment by Mad-Spy** [comment]
I'd suggest you make GW aware of the discrepancy if you're seeing something different in your iBooks copy and can't update it.
