### ISSUE TITLE
Bug: Craftworlds - Autarch's Mandiblasters rules incorrect

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#3671]
**File/Catalogue:** Craftworlds v45

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Mandiblasters are ruled as

> At the beginning of each Fight phase, you can pick a single enemy INFANTRY unit within 1" of this unit. Roll a D6 for each model in this unit; for each roll of a 6, the enemy unit suffers a mortal wound.

but should read as:

> At the beginning of each Fight phase, you can pick a single enemy INFANTRY unit within 1" of this model and roll a D6. On a roll of 6, that unit suffers a mortal wound.

**Comment by Mad-Spy** [comment]
Autarch is using the Scorpion squad wording. The effect is the same (as there's only one model in the Autarch's unit), but it probably should be amended.
