### ISSUE TITLE
Ork battalion CP 

### ISSUE THREAD

**Issue by Piemur1** [BSData/wh40k#3680]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** Warhammer 40k 8th Ed. Ork battalion states +5 CP.  Rulebook says +3.

**Comment by GenWilhelm** [comment]
This was changed in the spring "Big FAQ":
https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/warhammer_40000_rulebook_en-1.pdf

>Page 243 – Battalion Detachment, Command Benefits
Change this Detachment’s command benefits to read ‘+5 Command Points.’

>Page 243 – Brigade Detachment, Command Benefits
Change this Detachment’s command benefits to read ‘+12 Command Points.’

**Comment by Piemur1** [comment]
Thanks! Did not see the errata.
