### ISSUE TITLE
Imperium - Space Wolves: Ven Dread weapon cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3682]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** 8th ed v58
on the Venerable Dreadnought the total cost of Fenrisian Great Axe and Blizzard shield's total point cost is 70points and in the codex the price is 50 for axe 15 for shield with a grand total of 65 points i am not sure if this is

**Comment by Mad-Spy** [comment]
Please check you have the latest Wolves datafile (v52) as the cost is correct in that file.
