### ISSUE TITLE
Imperium - Space Wolves: Unable to take 15 Skyclaws as per datasheet

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3683]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** In battlescribe skyclaws have a limit of paxk leader + 9 skyclaws, but in the codex (on the datasheet) it says "This unit contains 1 Skyclaw Pack Leader and 4 Skyclaws. It can include up to 5 additional Skyclaws (PowerRating+4), or up to 10 additional Skyclaws (PowerRating+8)."

Under the points values table it says 5-10 skyclaws, but until the errata arrives confirming one or the other, (i personally think datasheet is more relevant) it would be wise to raise the limit to 15 in battlescribe, seeing as how lots of units dont have any caps in the battlescribe at all.

**Comment by CrusherJoe** [comment]
This was addressed in v53 of the datafile -- the most current version.
