### ISSUE TITLE
 Imperial Knights does not add 3 extra CP for 3 Titanic units

### ISSUE THREAD

**Issue by tmorton42** [BSData/wh40k#3685]
**File/Catalogue:** Imperial knights
Warhammer 40,000 v 1.1.66

**BattleScribe version:** v2.01.15.114

**Platform:** Windows and Android

**Description:** When creating an Imperial Knight Super Heavy attachment with 2 Paladins and 1 Warden, shouldn't the +3 CP in the header be +6 CP? 
I very well could have missed something and this could be correct, but I couldn't see it.

"Super-Heavy Detachment +3CP (Imperium - Imperial Knights) [69 PL, 1245pts]"

"Knight Lance: If your army is Battle-forged, select one model in each IMPERIAL KNIGHTS Super-heavy Detachment in your army. Each model you selected gains the CHARACTER keyword. The Command Benefit of each Imperial Knights Super-heavy Detachment is changed to 'None' if it does not contain at least 1 IMPERIAL KNIGHTS TITANIC unit, and is changed to '+6 Command Points' if it contains at least three IMPERIAL KNIGHTS TITANIC units. (Codex: Imperial Knights)"

**Comment by Mad-Spy** [comment]
Unfortunately, it is not possible to do this in the current version of Battlescribe without making a separate detachment type just for Imperial Knights, which could potentially cause confusion.

We are expecting that this will be possible in v2.02 of Battlescribe once it is released.
