### ISSUE TITLE
Imperium - Space Marines: Dreadnought missing Explodes rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3695]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Explode  rule  is missing from Space Marine dreadnoughts.

**Comment by williamcaw** [comment]
What Dreadnoughts are you referring to?

**Comment by williamcaw** [comment]
Selection fw is indeed missing the the rules but don’t count me on this.

**Comment by williamcaw** [comment]
Multiple issues blood angels,gray knights,and space wolves

**Comment by Mad-Spy** [comment]
I think you're looking in the wrong place. The various versions of the Explodes rule have been implemented in the catalogues as "Rules", which means they only have a reference in the unit entry, and then are displayed at the bottom of the Roster output (as long as you have the "Include rules?" option set to "Inline and Summary").

I think what you are expecting is for them to be implemented as "Profiles", which do display inline.

![image](https://user-images.githubusercontent.com/29306451/46353080-3810a400-c653-11e8-88ae-950f18906e51.png)
