### ISSUE TITLE
Incorrect Points Cost - Hellforged Contemptor Dreadnought "Soulburner"

### ISSUE THREAD

**Issue by Archon-Zailyar** [BSData/wh40k#3696]
**File/Catalogue:** wh40k/Chaos - FW Heretic Astartes.cat

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** For the Hellforged Contemptor Dreadnought's ranged weapon entry "Soulburner," it is currently listed in Battlescribe as costing 30 points. According to the Chaos Imperial Armor Index, it should cost 23 points.

**Comment by Mad-Spy** [comment]
The cost was increased in Chapter Approved.
