### ISSUE TITLE
Imperium - Space Marines: Can't find Inceptors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3697]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** Cannot find any reference to Primaris Inceptors. Looked through the entire space marine brigade list and couldn't find them.

**Comment by Mad-Spy** [comment]
The entry in the Marine catalogue is named "Inceptor Squad" and appears in the Fast Attack category.
