### ISSUE TITLE
Imperium - Blood Angels: Sanguinary Priest on Bike is missing bike's boltguns

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3698]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 1.11.54

**Platform:** Android

**Dropbox:** No

**Description:** Sanguinary priest on bike is missing default requirements to equipped his bike with twin boltgun

**Comment by williamcaw** [comment]
Reviewed  selection of default equipment  for bike template is missing .
