### ISSUE TITLE
[suggestion] Kustom Force Field description

### ISSUE THREAD

**Issue by Piemur1** [BSData/wh40k#3702]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** Description on Kustom Force Field includes Phrase "If the Big Mek is embarked..." but this description is on all units that can equip KFF including Wazbom Blastajet and Morkanaut. Suggest change description to say something along the lines of "If this unit is INFANTRY equipped with KFF and is embarked..." or something like that. If description is taken directly from rules and must include verbatim then ignore this. I feel like the phrasing could be improved. It isn't JUST a Big Mek that can equip KFF.

**Comment by amis92** [comment]
There should be separate profiles for all units that have differing wording (that's the strictly correct solution). As OP suggested, the alternative is to "generalize" the rules, but that should be done very carefully, since it means that the rule differs from the original.
