### ISSUE TITLE
[Necrons] Can't see Nanoscarab Casket

### ISSUE THREAD

**Issue by vhp17099** [BSData/wh40k#3704]
**File/Catalogue:** Necrons.cat

**BattleScribe version:** 2.01.

**Platform:** Windows/Irrelevant

**Description:** I don't see Nanoscarab Casket as an artifact option anymore.

See screenshot for reference:
![image](https://user-images.githubusercontent.com/7047900/46347007-f75c5f00-c641-11e8-91ae-980933b76f46.png)

**Comment by GenWilhelm** [comment]
You need to have phylactery on the model first.
