### ISSUE TITLE
Imperium and Chaos dreadnaughts missing Explosion profile/rules

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3705]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Request for validation and review pass of  explosion rules for forge world chaos and standard ,blood angels,gray knights, space wolfs . Have read Entries and they are lacking  this data for  dreadknots .

**Comment by Mad-Spy** [comment]
I have been unable to find any examples where a Dreadnought does not have the Explodes rule or its equivalent in some form, whether that is as an Ability, Rule entry or profile table.

If you have a specific issue, please raise a ticket with full details. Please see also #3695.
