### ISSUE TITLE
Warhammer 40,000 8th Edition.gstz

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#3710]
**File/Catalogue:** 
Warhammer 40,000 8th Edition.gstz
**BattleScribe version:** 2.01.15

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:**/No

**Description:** Detailed issue description.
item is missing from appspot

**Comment by Mad-Spy** [comment]
@williamcaw, we do not have any control over appspot, I'm afraid. This is just for reporting issues about the data in the files.
