### ISSUE TITLE
Imperium - Adeptus Mechanicus: No Knights in catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3713]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** In adeptus mechanicus super heavy detachment super-heavy axillary and in Supreme Commander there is no Lord of War options so none of the knights are showing and are able to be put in to detachment

**Comment by Mad-Spy** [comment]
To add Knights, use a child detachment of the Imperial Knights catalogue.

Instructions on how to add child detachments are here: https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions
