### ISSUE TITLE
Sabre Weapons Battery with Defensive Searchlight bug

### ISSUE THREAD

**Issue by OSP123** [BSData/wh40k#3717]
**File/Catalogue:** Imperium - Astra Militarum.cat

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** Sabre Weapons Battery with Defensive Searchlight comes out to 40 points instead of the correct 20 points. Imperial Armour Index mentions that the Sabre Weapons Battery is 20 points base and that the Defensive searchlight costs 0 points.

**Comment by Mad-Spy** [comment]
The cost of the Defense Searchlight was increased to 20pts in Chapter Approved 2017.
