### ISSUE TITLE
Aeldari - Drukhari: "Vanguard of the Dark City" rule is missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3724]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** VANGUARD OF THE DARK CITY MISSING - heading

Good afternoon Mr. WindstormSCR, 

First of all, I'd like to apologize for any mistake on this report as English is not my native language and sometimes i might make an error or two.

Second, I'd like to thank you for your amazing work and congratulate you for it, I find it sublime and can't start to imagine the amount of work and dedication you must have poured into it.

Lastly however, I've noticed I'm unable to find the "Vanguard of the Dark City" rule to apply to my roster (the faction specific rule for objective secured which can be found on page 114 of the Drukhari Codex). I don't know if it can be found somewhere where I couldn't find it or if you judged it was unnecessary to add, but i thought it might be a nice addition. I would try to add it myself but I have no idea how to do it, also i didn't think it would be nice to go over the author's head and do it. So I'm asking you to please add it if you feel it is a good idea to put it. 

Thank you for your attention.

Sincerely,

Marcel Esquius (marcel.esquiusdiez@gmail.com)

**Comment by WindstormSCR** [comment]
Well, thank you for the polite bug report, I'm actually surprised that got missed and hasn't been bug reported until now, a fix should be out as soon as possible for it.
