### ISSUE TITLE
Imperium - Space Wolves: Wulfen Dread Blizzard Shield issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3725]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** The Point value of the Blizzardshield from the Wulfen Dreadnought is listed as 2 Points but it should be 15 Points.

**Comment by Mad-Spy** [comment]
The actual problem is the the Blizzard Shield itself is not a default selection in the Blizzard Shield option (which also includes the storm bolter/flamer).

In addition, I'm pretty sure that the dread can only take 1 Blizzard Shield based on the datasheet, but it is possible to equip two.

**Comment by tekton** [comment]
I would love a video of a Wulfen Dread running in to battle with two shields, ejecting enemies from battle and shield bashing all at the same time with either shield...it would be glorious!
