### ISSUE TITLE
T'au Forgeworld units update (BIG FAQ 2 2018)

### ISSUE THREAD

**Issue by joarangoe** [BSData/wh40k#3726]
**File/Catalogue:** 
**BattleScribe version:** 2.01.
**Platform:** Windows/iOS/Android/Mac/Linux
**Dropbox:** Yes/No
**Description:** Tiger Shark Fighter-Bomber and TX7 Fire Support Hammerhead Gunship got their Heavy burstcannon renamed, so they no longer benefit from the updated profile on the codex for this weapon. They are reverted to their original weapon profile and cost as shown in the IAI:Xenos book. 

Thanks!

**Comment by amis92** [comment]
I do not know when I'll find time to fix this, so if anyone's up to it/has free cycles, feel free to take it on. Just please comment here it's in progress, so we won't duplicate the effort.
