### ISSUE TITLE
Lone wolf no longer in space wolves repository, still legal unit 

### ISSUE THREAD

**Issue by alleyblackmane** [BSData/wh40k#3731]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by GenWilhelm** [comment]
Lone Wolves are no longer a valid datasheet, as per the T'au Empire FAQ regarding index options that were replaced by stratagems:
https://whc-cdn.games-workshop.com/wp-content/uploads/2018/04/warhammer_40000_tau_empire_en-1.pdf

>Q: In Index: Xenos 2, the Stimulant Injector was a piece of wargear that I could purchase for certain T’au Empire units. In Codex: T’au Empire, the Stimulant Injector is no longer a wargear option, but instead there is a Stimulant Injector Stratagem. Can I continue to use the Index: Xenos 2 datasheets in order to purchase Stimulant Injectors for my units, as per the ‘What datasheet rules should I use?’ flowchart?
>
>A: No. You cannot purchase Stimulant Injectors anymore and the rules for Stimulant Injectors as presented in Codex: T’au Empire (i.e. the Stratagem) take precedence.

**Comment by amis92** [comment]
I'll just flag it as such for reference, since that issue is almost obvious (it should no longer be valid), but RAW there's nothing explicitly saying so. Which means it's ambiguous (we have already a precedent), and needs FAQ to resolve the ambiguity.

Separately, I'd advise to leave the entry if it's still there somewhere. If it's not, and reviving it will take considerable effort, mark it as low impact/request, not a bug, and leave as Pending until we get the FAQ (or were SW after-release-FAQ included in Big FAQ 2 wave?).

**Comment by alleyblackmane** [comment]
The SW after release FAQ was included in Big FAQ 2 and unfortunately did
not clear this issue up in its ambiguous glory

**Comment by IronWulfen88** [comment]
I got a reply from warhammer saying that the Lonewolf from the index is still a valid unit. I got the reply within the last hour.

**Comment by amis92** [comment]
@BSData/data-admins-wh40k how do we proceed? The case here is not *really* ambiguous per Designer's Commentary. It might get non-obvious when you count in the cited T'au FAQ about Stim Injectors, but overall it's a pretty clear situation.

I think: Lone Wolf unit is still legal and should be reinstated.

Do we drop "ambiguous" label and mark it as a bug, or do we fix it and leave issue open as "needs FAQ"?

We're not bound by correspondence "rulings", but it's just a confirmation of what we've mostly already established.

**Comment by GenWilhelm** [comment]
With regard to the Designers' Commentary, what is it about a lone wolf model that means it can't be used with any of the datasheets in the codex, such as as a Wolf Guard Battle Leader or a Wolf Guard Pack Leader?

**Comment by Kohato** [comment]
I've made my point in agreement with Amis. This is in no way similar to Stim Injectors.  One is an upgrade, the other is an entire model.  The datasheet is in Index but not Codex. It is legal as a choice.  Leave it in, mark the issue as Needs FAQ if you want, but it doesn't really need to stay open either.

**Comment by IronWulfen88** [comment]
Agreed  I say we put it back in. If he and their official Facebook page says it's legal then it is. Also the unit is a viable one while the stratagem gives you the ability to make one from a depleted unit so it is still very sound in play.

**Comment by Morkath** [comment]
It's not in the codex, and has been replaced by a stratagem with the same name.  The Tau FAQ makes it pretty clear this overrides the index version as they have the same name.

**Comment by IronWulfen88** [comment]
I talked to be just last week and they say the lone wolf entry in the index is still valid

**Comment by Morkath** [comment]
> 
> 
> I talked to gw just last week and they say the lone wolf entry in the index is still valid

Got a link to this ruling?

**Comment by IronWulfen88** [comment]
ill check. not sure if they took it down or not. the rulings go through the facebook page according to gw customer services till the faqs are updated. but ive sent in that question to just to be sure

**Comment by IronWulfen88** [comment]
> > I talked to gw just last week and they say the lone wolf entry in the index is still valid
> 
> Got a link to this ruling?

looks like they took it down. i will get reconfirmation then post the link here.
