### ISSUE TITLE
Imperium - Space Wolves: Error when giving Great Company Ancient a Relic

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3738]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Space wolves great company ancient gets an error when taking a relic.

**Comment by CrusherJoe** [comment]
@Mad-Spy is right. Cannot reproduce.
