### ISSUE TITLE
Tyranids: Validation error on Hive Tyrant when taking Wings

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3747]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** You are forced to take a second weapon selection on the hive tyrant when using wings

**Comment by Mad-Spy** [comment]
Yes, because the datasheet states that wings are an additional option to the two weapons which the Hive Tyrant is allowed. They are not a swap for a weapon choice.
