### ISSUE TITLE
Imperium - Dark Angels: Incorrect cost for Dark Talon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3751]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Dark Angel's Dark Talon is labeled at 200 points and should be 160. 140 points for Dark Talon and 20 points for two hurricane bolters. Rift cannon is free which totals at 160. Thanks for the help!

**Comment by Mad-Spy** [comment]
Cost has not been updated to Codex.

**Comment by SpaceJS** [comment]
The issue is incorrect, in the first big faq cost was changed from 160 to 180 excluding wargear. Rift cannon is 0 points and hurricane bolters are 10 each so total is 200

**Comment by Mad-Spy** [comment]
I knew there was somewhere else I should have checked!
