### ISSUE TITLE
Imperium - Space Wolves: WG Terminator weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3762]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Wolf guard terminators with cyclone missle launchers and storm bolter can upgrade their storm bolters. Currently in BS they cannot.

**Comment by Mad-Spy** [comment]
Are you using v53 of the Wolves catalogue? I can give a WG Terminator any combination of weapons and a Cyclone in that version.

**Comment by WindstormSCR** [comment]
There is precedent that this is not correct, specifically the prohibition in the deathwatch FAQ of doing exactly this with deathwatch terminators.

**Comment by WindstormSCR** [comment]
jeebus christo. GW right hand doesn’t know what the left one is doing anymore...

**Comment by Mad-Spy** [comment]
As above, you can do this by adding a Cyclone launcher to a normal WG Terminator, rather than a Heavy Weapons one in version 53 of the Wolves datafile.
