### ISSUE TITLE
T'au Empire: Riptide Burst Cannon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3766]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Tau Riptide Battlesuit has incorrect weapons.  It should have the Heavy Burst Cannon not the Swiftstrike Burst Cannon.

**Comment by Mad-Spy** [comment]
I think I broke this. I missed that the Heavy Burst was linked to the Riptide as well as all the FW models.

**Comment by amis92** [comment]
For the sake of user convenience it's probably good idea to have Swiftstrike be renamed back to HBC, and create a new Swiftstrike entry, so that riptides taken previously have the correct cost and weapon name.

**Comment by samtayler** [comment]
Would it be a good stopgap solution while this is being worked on to just revert the swiftstrike change and allow people to create correct lists with the riptide again. 
I don't think many people would be using the units with the swiftstike cannon.
