### ISSUE TITLE
Imperium - Inquisition: Unable to select Psychic powers for Inquisitor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3781]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Inquisitor Psyker powers not appearing. 

The option to select specific psychic powers from the Inquisition psychic discipline does not appear when the "Psyker" checkbox is selected for the Inquisitor.

**Comment by Mad-Spy** [comment]
You need to drill-down into the Psyker selection in order to select your powers.

![image](https://user-images.githubusercontent.com/29306451/47637860-e3c6ea00-db54-11e8-813c-195b1123e2d7.png)
