### ISSUE TITLE
Tyranids - Genestealer Cults: Genestealers should have same wargear options as Codex.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3782]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The genestealer of genestealer cult have accès same option than genestealer of tyranide codex since the box "tooth and claw"

Thanks

**Comment by GenWilhelm** [comment]
I'm unable to find anything that supports this. As far as I can tell, the Purestrain Genestealers datasheet in Tooth and Claw is the same as the one from Index: Xenos 2.
