### ISSUE TITLE
Chaos Death Guard plague marine champion no wargear options

### ISSUE THREAD

**Issue by knotdragon** [BSData/wh40k#3784]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Plague marines squad champion has only 1 available loadout - boltgun and plague knife - no option for power fist, plague sword, plasma gun or anything else is available

**Comment by Mad-Spy** [comment]
Select whether you are using Index or Codex weapons, then drill down to find the actual weapon options.

**Comment by knotdragon** [comment]
That doesn't work.  I select codex option, then tap the weapons options and
it leads me to screen where I can go Index, or tap the codex weapons again,
but no alternative options come up when I tap this, just remains boltgun
and plague knife.  I feel like I'm getting it wrong but I've used
battlescribe a lot and I don't see any other tap option I'm missing to give
me the other loadouts.

**Comment by knotdragon** [comment]
Ha brilliant, scratch that, found it.  I knew I was missing something.
Thank you for taking the time to reply to me.
