### ISSUE TITLE
Imperium - Space Wolves: Skyclaw Unit Size

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3788]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Unit size for Skyclaws in incorrect.
FAQ allows max size of 15 not 10 as per V53.
Might be worth checking swiftclaws too.
Keep up the good work.
Andrew

**Comment by CrusherJoe** [comment]
I beg to differ -- note the lack of validation errors for the Swiftclaws -- and this is from v53.
![swiftclaws](https://user-images.githubusercontent.com/9998385/47734221-f6661f80-dc37-11e8-8cfa-a6daf75ae1e7.PNG)
