### ISSUE TITLE
Astra Militarum: Wrong cost Primaris psyker and Tempestus command rod and other weapons

### ISSUE THREAD

**Issue by Pyromadness** [BSData/wh40k#3802]
Cat: Astra Militarum

BattleScribe version: 2.01.15

Platform: Windows

Dropbox: No

Description: Primaris psyker, Force stave and Tempestus command rop seems to have wrong costs.
Codex say 
Primaris psyker 28p
Force stave 12p
Tempestus command rod 0p

BS say

Primaris psyker 38p
Force stave 8p
Tempestus command rod 5p

It also seems like a lot of other weapons have wrong prices, Hot-shot volly gun is 6p in codex, but 7p in BS. Meltagun is 12p in codex as 17 in BS.

Did i miss something or have the weapons prices just not been updated?

**Comment by Mad-Spy** [comment]
Yes, I'm afraid you have missed something. All of these costs were changed in Chapter Approved 2017.

**Comment by Pyromadness** [comment]
okey? so sorry then, just got back in to 40k an no one told me i needed yet one more book

But thanks for the help
________________________________
Fra: Iain Launchbury <notifications@github.com>
Sendt: 1. november 2018 17:24
Til: BSData/wh40k
Cc: Pyromadness; Author
Emne: Re: [BSData/wh40k] Astra Militarum: Wrong cost Primaris psyker and Tempestus command rod and other weapons (#3802)


Yes, I'm afraid you have missed something. All of these costs were changed in Chapter Approved 2017.

**Comment by Kohato** [comment]
Don't bother buying CA 2017. CA 2018 will be coming out in a month or so :) Which will then have more point changes which will likely overwrite stuff from CA 2017. Unfortunately 8e will be a living ruleset, Yearly books to buy.

**Comment by Pyromadness** [comment]
Okey, thanks for the info 😊

________________________________
Fra: Earl Bishop <notifications@github.com>
Sendt: 1. november 2018 19:42
Til: BSData/wh40k
Cc: Pyromadness; Author
Emne: Re: [BSData/wh40k] Astra Militarum: Wrong cost Primaris psyker and Tempestus command rod and other weapons (#3802)


Don't bother buying CA 2017. CA 2018 will be coming out in a month or so :) Which will then have more point changes which will likely overwrite stuff from CA 2017. Unfortunately 8e will be a living ruleset, Yearly books to buy.

**Comment by Pyromadness** [comment]
Hey sorry to bother but was hoping you could help me agian, i cant finde the profile for the Leman Russ
 where I can change the main gun? did they remove all those options or?


________________________________
Fra: Earl Bishop <notifications@github.com>
Sendt: 1. november 2018 19:42
Til: BSData/wh40k
Cc: Pyromadness; Author
Emne: Re: [BSData/wh40k] Astra Militarum: Wrong cost Primaris psyker and Tempestus command rod and other weapons (#3802)


Don't bother buying CA 2017. CA 2018 will be coming out in a month or so :) Which will then have more point changes which will likely overwrite stuff from CA 2017. Unfortunately 8e will be a living ruleset, Yearly books to buy.
