### ISSUE TITLE
Imperium - Space Marines: Relic validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3806]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Relics don't unlock for characters unless the warlord is in the same detachment at those characters.

**Comment by Mad-Spy** [comment]
Relic visibility was set to trigger on Force rather than Roster. Fixed.
