### ISSUE TITLE
Orks: Traktor cannon points incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3821]
**File:** Orks.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Mek guns traktor cannon points costs are incorrect. Listed as 15, but should be 30.

**Comment by cmonger** [comment]
Ork scrapjet should be 120 also.

**Comment by tag8833** [comment]
These are both fixed, and ready to release.
