### ISSUE TITLE
Orks: Megatrakk Scrapjet cost incorrect.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3822]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** Points cost for Ork Megatrakk Scrap Jet. Should be 110, not 140. Rokkit kannon 0 Pts, wing missiles 0Pts, Nose Drill 0Pts, not 10pts each. Only the big shoota's cost points at 10. Therefore 90+10+10 = 110Pts Total. 
Thank you for the amazing work so far and the speed this has been done!

**Comment by tag8833** [comment]
Fixed and ready to release.
