### ISSUE TITLE
Orks: Deffkilla Wartrike, Illegal Relic options

### ISSUE THREAD

**Issue by DDelvin** [BSData/wh40k#3823]
**File/Catalogue:**  Orks.catz

**BattleScribe version:** 2.01.21

**Platform:** Windows

**Dropbox:** No

**Description:** Deffkilla wartrike has access to "Da Ded Shiny Shoota", "Gitstoppa Shells" and "Da Gobshot Thunderbuss" (Bad Moons) despite it lacking the prerequisite Kustom Shoota/Kombi shoota weapon.

Similarly It has access to "Da Ded Killy Klaw", despite it lacking the prequisite Power klaw.

**Comment by tag8833** [comment]
I didn't add wargear constraints to relics.  I thought about it.  I'll see how hard it is as I clean up the other typo errors today.
