### ISSUE TITLE
Orks: Megatrakk Scrapjet profile issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3824]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** Megatrakk Scrapjet rules for Mortal wounds on the charge not in the text at all. The same as what is entered for the Kustom Boosta Blasta.

**Comment by tag8833** [comment]
They are there.  They are showing up for me.  Check again please.
