### ISSUE TITLE
Ork Warbikes 

### ISSUE THREAD

**Issue by blackflow** [BSData/wh40k#3838]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** Correct me if I am wrong but in the codex it is specified that each warbike model has 2 dakkaguns?  Maybe it's a misprint but still, it should be 2/model.

**Comment by tag8833** [comment]
They do have 2 dakkaguns both in the codex and in battlescribe.  

It looks right to me.
