### ISSUE TITLE
Chaos - FW Heretic Astartes: Can't make SHAD its own child.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3850]
**File:** Chaos - FW Heretic Astartes.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** I'm not sure this is a bug, it just seems like a limitation.  I'm trying to add a Spartan Assault Tank to my Iron Warriors army, with is a Lord of War, so it needs a Super-Heavy Auxillary Detachment.  The FW Heretic Astartes list doesn't let me choose a Legion, and I can't create a nested list of Chaos Space Marines-FW Heretic Astartes with the Super-Heavy Auxillary Detachment like I can a Battalion Detachment.  So there's no way to tell my list what Legion my Spartan is from.

**Comment by Mad-Spy** [comment]
You're right, it's a limitation. We made the decision not to allow nesting in SHADs back in the mists of time, as they can only have a single unit in them. 

In 99% of cases, the model you add to your SHAD is going to be the same <LEGION>, <CHAPTER>, <CRAFTWORLD> or whatever as your main army, so it's not a huge problem and you can just note it manually on your list if you need to.

Once 2.02 is released, it will be much easier for us to put the FW models into the individual catalogs without needing to duplicate them, so this problem should go away.
