### ISSUE TITLE
Imperium - Elucidian Starstriders: Sanistasia Minst missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3853]
**File:** Imperium - Elucidian Starstriders.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Missing "Sanistasia Minst" from the elites choices.

**Comment by Mad-Spy** [comment]
She shows up for me the the latest release. Can you give some more details?

**Comment by GenWilhelm** [comment]
It's likely due to the fact that she doesn't take up a slot when she's in the same detachment as Elucia Vhane, in which case she moves to "No Force Org. Slot".

**Comment by Mad-Spy** [comment]
Ah, that's probably it! Forgot that she had that rule.

OP, see @GenWilhelm's comment. If you have Elucia in your Detachment, Sanistasia moves to "no Force Org" as she doesn't take up a slot.
