### ISSUE TITLE
Imperium - Dark Angels - Various issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3854]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** 1. Relics seem to be either missing or are messed up in the recent versions.
2. Scout Bike Squad shouldn't have TROOPS keyword and their Sergeant should also have a Bolt Pistol and Shotgun as default Ranged Weapons. The Pistol can be replaced by an item from the Pistols or Melee Weapons list.

**Comment by Mad-Spy** [comment]
There have been some validation updates on Relics so that you are now required to take either a DA warlord or one of the "Relics of the Rock" options in order to quality. Perhaps this is why you cannot find them?
