### ISSUE TITLE
Command Points Incorrect

### ISSUE THREAD

**Issue by Dawson1985** [BSData/wh40k#3856]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The command points are incorrect in the warhammer 40k list. Example- I loaded the ork list and chose my detachment and it says I have 5 CP. However, a battalion detachment only gives you +3 cp. 

Thank you though for getting the list maker up there so quickly for the orks. You folks make playing the game a much easier process for someone who dosent have much time to devote to this hobby. ;)

**Comment by Kohato** [comment]
This was changed in the BIG FAQ back in April. https://www.warhammer-community.com/2018/04/16/warhammer-40000-big-faq-1-the-low-downgw-homepage-post-1fw-homepage-post-2/
