### ISSUE TITLE
Orks: Missing HQ options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3862]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Boss Zagstrukk and Boss Snikrot are not in the HQ choices for Orks.  Zagstrukk was in an option in the outrider detachment for a little while, but he's gone now.

Great app though!  Thanks.  Michael.

**Comment by Mad-Spy** [comment]
You need to select the correct Clan Kultur for them to appear as valid choices.
