### ISSUE TITLE
Orks: Warbikers Power Level is incorrect

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#3868]
**File/Catalogue:** Orks v32

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** When a unit of Warbikers has more than 3 models in it, the power level is incorrect and is calculated at 4 PL per 3 models. However, the Codex suggests that the increases are actually 3.5 PL per 3 models:
3 models = 4 PL
6 models = 7 PL
9 models = 11 PL
12 models = 14 PL

**Comment by tag8833** [comment]
Well done spotting these errors.  I'll get them resolved and fixed in the next day or two.
