### ISSUE TITLE
Problem with detachment requirements

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3873]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.00

**Platform:** Windows

**Dropbox:** No

**Description:** What is broken:
-the requirement for different detachments are wrong in that it demands troops and characters not stated in the rulebook
What it should be:
- Battalion detatchment should have a requirement of two (2) characters and three (3) troops only
- Vanguard detatchment should have a requirement of one (1) characters and three (3) Elites only
- Spearhead detatchment should have a requirement of one (1) characters and three (3) Heavy support only
- Outrider detatchment should have a requirement of one (1) characters and three (3) Fast attack only

**Comment by Mad-Spy** [comment]
Not sure what the problem is here. Each of the detachments you have listed above require the minimum requirements you have listed.

What requirements are you seeing over and above those listed?

**Comment by Kohato** [comment]
There is no issue - The requirement is HQ, not Character.
