### ISSUE TITLE
Orks: Incorrect text for "Roar of Mork"

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3882]
**File:** Orks.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Weirdboys Power of Waaagh „Roar of Mork“ doesnt work. If i look at my weirdboy the Power „Da Krunch“ is shown instead.

**Comment by Mad-Spy** [comment]
The power text is (mostly) correct, but the Profile entry is named incorrectly.
