### ISSUE TITLE
Imperium - Dark Angels: Incorrect unit count limits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3892]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The number of Deathwing Ancient models allotted to field, and the number of Deathwing Champion (1 per army) should be reversed. Codex Page 96.  Thanks!

**Comment by Mad-Spy** [comment]
For clarity, Deathwing Champions should be max 1 in Roster, and Deathwing Ancients should have no limit.
