### ISSUE TITLE
Orks: Units added in IA:Xenos errata missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3900]
**File:** Orks.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The following units from the “Imperial armour - update Xenos” Errata are missing:
- Grot bomm Launcha (fast attack)
- Dethrolla Battle Fortress (lord of war)
- Kill Krusha (lord of war)

**Comment by tag8833** [comment]
You've got to set the "Gametype" to "Open", and they will show up.
