### ISSUE TITLE
Imperium - Questor Imperialis: Exalted Court Characters should be able to take Heirlooms

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3902]
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Should allow selection of heirloom artefacts even if only choosing the knight as an exalted court member from the exalted court stratagem. 
I.e. a character is chosen in the unit as the warlord and a second knight is given the exalted court warlord trait stratagem. If I don’t want to choose the warlord as the bearer of the heirloom, I should still be able to choose the exalted court member as he is also a character after playing the stategem. Cannot currently choose an heirloom for the exalted court guy.

**Comment by Mad-Spy** [comment]
OP is correct, any CHARACTER should be able to take Heirlooms, regardless of how they gain the keyword.

**Comment by Kohato** [comment]
![image](https://user-images.githubusercontent.com/16939161/48705583-25303f80-ebbf-11e8-8ec3-3f5b3bc3b81d.png)

Yep, OP's Correct. OP needs to select the correct option in the list. Choose the Heirlooms strat from No Force Org, then use the "Character (Heirloom of the House)" option.  It was implemented this way because nesting validation for IK relics with so many character combinations was a nightmare.  This is far cleaner and easier.

**Comment by GenWilhelm** [comment]
OP is using the Exalted Court stratagem, not Heirlooms of the House.

**Comment by Kohato** [comment]
Whoops. Point stands. Select character (exalted court)

**Comment by GenWilhelm** [comment]
But they can't take the free Warlord relic in that setup.

![court](https://user-images.githubusercontent.com/22036809/48707624-f08caa00-ebf7-11e8-8320-1f47dc7613e9.png)

**Comment by Kohato** [comment]
*sigh* IK Characters strike again.  I'll fix that tonight.

**Comment by Kohato** [comment]
As an aside, I never thought people would need it this way ... because if you're using Exalted Court to give a WT and a relic ... just make that knight the warlord.  But yes, it can technically be allowed, so I need to fix it.

**Comment by Kohato** [comment]
Closed via 16ccb26
