### ISSUE TITLE
FW - Elysian Lord Commissar Weapon Options

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#3907]
**File/Catalogue:** FW - Elysian

**BattleScribe version:** 2.01.

**Platform:** Mac
**Dropbox:** No

**Description:** Elysian Lord Commissar can take a boltgun for free, which shouldn't be the case. The wargear options are a little chaotic for this character on the menu, it could do a with tidy up as there are duplicate options for the same weapon. I assume this came about when the index was updated to include more options to the ranged weapon list and what's happened is whoever did the change added the whole list to the commissar selections without realising (or ignoring) that both the bolt pistol and boltgun were already standard options. Perhaps consider removing the 2 bolt options and just leaving the ranged weapon list selection and an error if none are selected. But idk how this works so for all I know i'm talking out my arse. Thanks anyway! <3

**Comment by alphalas** [comment]
I fixed the one boltgun being free; unfortunately because how we write the cats minor duplication like that is inevitable.
