### ISSUE TITLE
Problems adding FW units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3908]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Maybe I'm doing something wrong, but I do not appear to see forgeworld units in the drop down menus. Is FW not supported in this file, or am I doing it wrong?  Thanks!

**Comment by Mad-Spy** [comment]
Which army are you trying to add Forgeworld options for? Some catalogues have them integrated, but Marines and Heretic Astartes have separate files which you'll have to add as Child Detachments.
