### ISSUE TITLE
Add Eisenhorn's Demonhost

### ISSUE THREAD

**Issue by Mikle103** [BSData/wh40k#3909]
**File/Catalogue:**  Imperium - Inquisition v19

**BattleScribe version:** 2.01.15.114

**Platform:** Windows

**Dropbox:** No

**Description:** Enhancement 
Would it be possible to add Eisenhorn's demonhost with modified stat-line but make only visible to take  if matched play is selected and Eisenhorn is also added to the roster.
or just if Eisenhorn is added to the roster which ever you think would be best?

**Comment by alphalas** [comment]
Not really, because you summon cheruibael midway through the game, you don't select him at the start of the game. Also, the description of the Malus Codicium ability is already on Eisenhorn.

**Comment by Mikle103** [comment]
I know that it is summoned by it has a different stat line than a normal host and in Matched play you still need to factor in the cost of it.

**Comment by alphalas** [comment]
Yup, so either have your list down by the appropriate points (the way GW says to do it) or just put a regular host in if you have to have your list be pointed perfectly. This is a standard across all “summoned” thing on BS.

**Comment by Mikle103** [comment]
I understand that but it has a different stat line that the standard one.

**Comment by alphalas** [comment]
It doesn’t have a separate data sheet though; that’s the issue. If they actually made a separate datasheet for it, I’ll be right there with you and I’d be doing it in a heartbeat. But they didn’t .
