### ISSUE TITLE
Imperium - Adeptus Ministorum: Blackstone Fortress

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3938]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** There missing Thaddeus the Purifier and Pious Vorne in Adeptus Ministorum Data File - datasheets here: https://vk.com/doc454540467_482708122?hash=a9babdbc87130b95a4&dl=c5c9b1110be08120ae

**Comment by GenWilhelm** [comment]
Units from Blackstone Fortress are still being worked on. Hopefully, we'll have them ready to be available within the next few days.

**Comment by Mad-Spy** [comment]
They're done. They'll be in the next release.
