### ISSUE TITLE
Imperium - Space Wolves: Warlord Traits missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3944]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** There are no Warlord traits in the Space Wolves list after you pick a Warlord. Please fix this. It was working before and I am not sure why it was removed.

**Comment by Mad-Spy** [comment]
Can you let us know which model you're looking at specifically, as I can see the Traits on all the ones I've tried.

**Comment by habelson** [comment]
Sadly, because of how the anon bug reporter works, I’m not sure the reporter will ever see your follow up question. Personally I have not run into an issue with warlord traits yet.

**Comment by CrusherJoe** [comment]
Me either -- could possibly be using an outdated version of the datafile. Closing.
