### ISSUE TITLE
Necron HQ units (and others) missing

### ISSUE THREAD

**Issue by houkdaddy** [BSData/wh40k#3949]
**File/Catalogue:** Necrons V37

**BattleScribe version:** 2.01.283

**Platform:** Android

**Dropbox:** No

**Description:** Missing several HQ units like Imotekh and Orikan. Also missing some individual units like Canoptek Spyder. Some warlord traits missing as well

**Comment by Kohato** [comment]
You need to select the correct Dynasty for them to appear (Sautekh). Though the spyder should be there regardless, under Heavy Support. Is it not?

**Comment by houkdaddy** [comment]
Understood. Spyder actually is there. Sorry for the confusion

**Comment by Kohato** [comment]
No worries :D - "Mixed/No Dynasty" will show them as well fyi - I made it so if you want a mixed detachment you can.
