### ISSUE TITLE
Imperium - Astra Militarum: Add Relic stratagems and validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3977]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** There is no option for the “Imperial Commanders Armoury” stratagem to allow multiple relics to be taken.

**Comment by Mad-Spy** [comment]
There's currently no validation on the Relics in the AM catalogue, so the Stratagem isn't needed. However, it might be nice to add them (and validation) for consistency with other catalogues.
