### ISSUE TITLE
Necrons: Tesseract Vault missing Tesla spheres?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3985]
**File:** Necrons.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** While in the roster selections list the Tesseract Vault shows it has four Tesla Spheres, but in the view roster list there is no indication that it has more than one.

**Comment by Mad-Spy** [comment]
Are you outputting in minimal output mode? BS does not show default equipment in this mode. Using "Full Output" mode displays that the model has 4x Tesla spheres.

![image](https://user-images.githubusercontent.com/29306451/49720949-fe62a780-fc58-11e8-9ee4-467f4e9a600e.png)
