### ISSUE TITLE
Grey Knights - Twin Psycannon and Techmarine points values

### ISSUE THREAD

**Issue by Pukwudji** [BSData/wh40k#3998]
Imperium - Grey Knights

**BattleScribe version:** 2.01.15

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Twin Psycannon and Techmarine points values

The Twin Psycannon on the Vortimer pattern vehicles is listed as costing 50pts, in the index it lists it as 28pts and I can't see anywhere that the points have been altered.

GK Techmarines are costed differently from normal Adeptus Astartes, we pay for 2*Servo Arms, a Plasma cutter, a Flamer, a Bolter and a Power Axe, all seperately.  We do not take a Servo Harness, this should drop our costs (and even more so after CA2018).

Cheers Steve

**Comment by tekton** [comment]
This will be updated next week for CA18
