### ISSUE TITLE
Space marines points not updated properly

### ISSUE THREAD

**Issue by DedusJovus** [BSData/wh40k#4007]
**File/Catalogue:** Space Marines

**BattleScribe version:** 2.01.15

**Platform:** Windows/

**Dropbox:** Yes

**Description:** Hi. Unless I'm doing/reading something wrong, there seems to be a whole bunch of points that are not properly updated for space marines. I haven't checked all the entries but for example captain on a bike is still 98 instead of 88, power fist is 12 not 9, terminators are 26 not 23, assault squad w JP is still 16 not 15 etc... For reference I checked the same values for space wolves and they are as they should be.

**Comment by Mad-Spy** [comment]
The current release does not include the CA 2018 points updates, as the book is not yet released. Please wait until the weekend after we release the update.
