### ISSUE TITLE
T'au FW unit prices update CA18

### ISSUE THREAD

**Issue by joarangoe** [BSData/wh40k#4019]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Hi there. I can see that the codex units have already been updated and and are awaiting to be published, but the forgeworld units remain unchanged in the last updated file. Here are the changes on CA18:

Blacklight Marker Drones - 7pts
TX7 Fire support hammerhead gunship - 100pts
Xv9 Hazzard support team - 40pts
TX7 Heavy bombardment hammerhead gunship - 100pts
Manta Super heavy dropship - 2000pts
DX4 Remora stealth drone squadron - 30pts
Taunar supremacy Armor - 750pts

Hope you can slip these before realease on the weekend

**Comment by amis92** [comment]
For reference, the actual changes made:
* TX7 Fire Support HH: 117 -> 100
* TX7 Heavy Bombardment HH 117 -> 100
* XV9 Hazard 61 -> 40
* DX6 Remora 57 -> 30
* Ta'unar 1500 -> 750
