### ISSUE TITLE
Space Marine Ironclad Dreadnaught

### ISSUE THREAD

**Issue by Zachary-Newman** [BSData/wh40k#4023]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes/No

**Description:** I think the Marine Ironclad Dreadnaught has an issue. It looks like the Dreadnaught Melee Weapon cost is built in to the base cost with the Stormbolter and Heavy Flamer points as options at 2 and 17 points, but then the Hurricane Bolter is listed at 10 points when it actually replaces the Dreadnaught Melee weapon. I'm pretty sure they should be 32, 47, and 10 (until Saturday anyway) with the base model 30 points cheaper.

**Comment by Mad-Spy** [comment]
The Ironclad Dread is priced as per the Codex and CA 2017 (until we release CA 2018 updates). 

The Ironclad's CCW is free, and it costs 80pts base.
