### ISSUE TITLE
Chaos - Chaos Space Marines: Terminators in CA18

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4032]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** Terminators of chaos cost base its 28 no 31. Chainfist its 11 no 14. And autocanon its 10 no 15. Thanks for your work.

**Comment by Kohato** [comment]
Consolidated in #4078
