### ISSUE TITLE
T'au Empire: CA2018 Changes - Consolidated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4035]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** 

- [x] Ghostkeel cost is at 72 points. It should be 70.
- [x] The Eight entirely absent from Lord of War choices
- [x] ~~Advanced Targeting System should be 6pts~~ (eligible units have it for 6, Codex-excluded - 18, as Codex instructs)

**Comment by cwright71** [comment]
Imperial Armor Xenos does not have Shas'o R'alai's drones listed as Dal'Yth

**Comment by amis92** [comment]
@OP I did not find any unit that was supposed to have ATS for 5 and had for 18. All other than those with special cost of 18 (Ghostkeel, Riptide, Stormsurge) have the cost right.

**Comment by cwright71** [comment]
Blacklight marker drones are 7 points each down from 10.

**Comment by amis92** [comment]
@cwright71 they were 10 with Markerlights (which are 3), and now are 7 without wargear + 3 with MLs.

**Comment by cwright71** [comment]
Gotcha, thanks !
