### ISSUE TITLE
Elysian OotF and Valkyrie

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#4037]
**File/Catalogue:** FW Elysian

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** No

**Description:** Officer of the fleet points cost has not been updated for chapter approved. 

Valkyrie bass cost needs to drop 10 points. 
Hellstrike missiles need dropping as well. 

Standard AM OotF doesn't include the condition of your units needing the fly keyword for the strafing coordinates ability.

**Comment by GenWilhelm** [comment]
Not sure what you mean by the OotF ability not needing the keyword. Here is the current version, from Codex: Astra Militarum:

![image](https://user-images.githubusercontent.com/22036809/50043578-8c31fe80-006e-11e9-8808-e713fbc71502.png)

BattleScribe matches that exactly, except for swapping out AERONAUTICA IMPERIALIS for ELYSIAN DROP TROOPS, as per the Elysian Drop Troops army list.

**Comment by Millambr** [comment]
It coming up correctly on mine.

![image](https://user-images.githubusercontent.com/17701144/50060196-7f331d80-01dc-11e9-8cf9-56af9225d433.png)

But the cost of the OoF does need changing to 20 from 25 pts, as well as the other 2 changes.
