### ISSUE TITLE
Imperium - Space Wolves: Intercessor Power Weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4042]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** Hi,

was very grateful to see the CA changes flowing into the datasource. Thanks for your work!

But i noticed that for Space Wolves:
- The Intercessor Pack Leader is missing the Power Sword and Power Fist options

Thanks

Florian

**Comment by timbrown81** [comment]
The fix addresses the Power Fist but doesn't appear to address the Power Sword option.
