### ISSUE TITLE
Chaos - Chaos Space Marines: Spawns in CA18

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4045]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.16

**Platform:** Mac

**Dropbox:** No

**Description:** Points cost for chaos spawn are 25 points, not 33 points. (as per Chapter Approved 2018)

**Comment by Kohato** [comment]
Consolidated in #4078
