### ISSUE TITLE
Chaos - Daemons: Lord of Change with Baleful Sword in CA18

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4053]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Lord of change with Baleful Sword comes to 280 points when it should be 275. It should be 270 without the Sword. Please change the Baleful Sword point cost to 5.

**Comment by Kohato** [comment]
Consolidated in #4079
