### ISSUE TITLE
Chaos - Chaos Space Marines: Various Costs in CA18

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4054]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Probably some points cost haven't been updated after CA2018 (following the photos of points cost changes around the web). Up to now I found this:
- Chaos Terminators are still 31 instead of 28
- Chaos Spawns are still 33 instead of 25
- Chaos Land Rider Twin Lascannons are still 50 each instead of 40.

I hope it can help. Thank you very much for your job!

**Comment by Kohato** [comment]
Consolidated in #4078
