### ISSUE TITLE
Adepta Sororitas Warlord Traits + Blackstone Character bugs

### ISSUE THREAD

**Issue by Commisar** [BSData/wh40k#4055]
**File/Catalogue:** 
Imperium - Adeptus Ministorum v40
**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** 
1) The new Adepta Sororitas Warlord Traits don't show up to be selected for non unique warlords. Celestine and Uriah have Warlord Traits correctly, but not so for the ones were its selectable.

2) Taddeus the Purifier (Blackstone Fortress) insists on having a warlord trait even when he is not the warlord.

3) Pious Vorne becomes a 'No Force Org Slot' choice when you include a priest. Which is a cool idea, but I can't find any rules to support it anywhere.

**Comment by alphalas** [comment]
@crusherjoe the way Celestine's WLT is implemented is consistent with all other named characters due to BS limitations. But you should know this ;)
