### ISSUE TITLE
Chaos - Chaos Space Marines: Maulerfiend in CA18

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4060]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Maulerfiend base price is 120 per Chapter Approved 2018, current data still has previous price of 140.

**Comment by Kohato** [comment]
Consolidated in #4078
