### ISSUE TITLE
Land Raider Twin Lascannnon cost wrong

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4066]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Item twin-lascannon in land raider wargear should be 40 not 50 ponit

Thank you so much for this amazing app

**Comment by GenWilhelm** [comment]
Which catalogue? There are a lot that use land raiders.

**Comment by Kohato** [comment]
This has been fixed in the GST already
