### ISSUE TITLE
Blood Angels - Inferno Pistols Cost 9, should be 7

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4072]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Imperium Blood Ángels - Inferno pistols still cost 9 points, should be 7.

**Comment by Kohato** [comment]
Consolidated to #4077
