### ISSUE TITLE
Space wolves - Thunderwolf Cavalry Cost

### ISSUE THREAD

**Issue by Illarvan** [BSData/wh40k#4083]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Storm shields should cost 10 on thunderwolf cavalry, they didn't drop down to 2.

**Comment by Kohato** [comment]
They did actually, take a look at your CA book:

![image](https://user-images.githubusercontent.com/16939161/50050184-a1804a80-00b9-11e9-9809-01616552ffe9.png)

**Comment by Illarvan** [comment]
This is incorrect, if you check the codex there is an entry for Storm shield (thunderwolf cavalry) 10. As there is no entry for this in CA then the codex takes precident

**Comment by alphalas** [comment]
How does an older publication take precedent over a newer publication entry that specifically says “other models”?

**Comment by Illarvan** [comment]
If you read the codex It has 3 entries. Characters, Cavalry, and other models. CA addressed Characters and Other models but not cavalry.

Maybe if you actually read what I wrote instead of just closing it again.

Picture for clarity as it keeps getting closed with no-one checking the codex.

![swss](https://user-images.githubusercontent.com/13433600/50053831-aa196500-013b-11e9-8757-4f0b1fe29095.PNG)

**Comment by amis92** [comment]
@CrusherJoe @Kohato @alphalas  I have to agree with @Illarvan.

There's a separate row for TWC in Codex, and it did not get updated. There's a couple other wargears that had their points selectively updated.

* Grey Knights: Psilencer (Terminator)
* Space Marines: Dreadnought combat weapon (other models)
* Tau Empire: Advanced targeting system (all other models)
* Tyranids: Massive scything talons (two or more pairs) (Trygon and Trygon Prime)

**Comment by Kohato** [comment]
All indications from gw show it is as written. "all other" means what it
says

**Comment by CrusherJoe** [comment]
I understand your point of view. I consider the issue settled, however, as multiple reputable/reliable sources have specifically stated the TWC storm shield is included in the (other models) wargear points update. Cost of 2 points will remain until GW says otherwise.

**Comment by amis92** [comment]
@CrusherJoe I think this should stay open until FAQ comes.

**Comment by Kohato** [comment]
Mentioning the other lines - I can see now Amis. I'm honestly not sure anymore. A FAQ should come soon though I think.  Issue probably should stay open until then.

**Comment by Illarvan** [comment]
![48403875_2227868210824929_2158999911314489344_n](https://user-images.githubusercontent.com/13433600/50088373-21fe9280-0203-11e9-97f0-f5b0cd7a8064.jpg)

**Comment by amis92** [comment]
@Illarvan see #4196 - temporarily "fixed"

**Comment by scotticus2** [comment]
Space wolf file doesn't have the option for lone wolf in terminator armour via the index book

**Comment by Kohato** [comment]
Per CA2018 FAQ/Errata, TWC SS is 10 points per model.
