### ISSUE TITLE
CA2018 Narrative/Open Play Updates

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4095]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Custom Characters abilities from Chapter Approved 2018 don't appear to be in the dataset as of yet.

**Comment by Kohato** [comment]
Battlescribe is primarily a Matched Play tool.  We will need to discuss how to best implement things like Looted items and the Custom Characters into the dataset.

**Comment by WindstormSCR** [comment]
Ultimately it will be up to catalog owners to determine the amount of effort required to integrate things like custom characters and battle honors, but I plan to add these to the GST using a SSEG in order to minimize memory load, so they can simply be linked to the appropriate units

**Comment by WindstormSCR** [comment]
Unfortunately battle honors will not be implemented due to causing unacceptable slowdowns on unit entry loading on the mobile variants... It sucks but it's a program limitation and the primary goal of the catalogs are as a matched play tool.
