### ISSUE TITLE
Space Marines: Terminators and Cataphractii Captain CA2018 Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4115]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Captain in cataphracti armour not updated to CA points. Terminator points not corre t, base and power fist (I think)

Dreadnought combat weapon incorrect.

**Comment by JasonMWelch** [comment]
Yea the Power fist Price is 12 not 9 on tactical marines and Sternguard vets.  So I assume all units.

**Comment by flakpanda** [comment]
Fixed in v68
