### ISSUE TITLE
Space Marines: Stalker Twin Icarus Stormcannon CA2018 Update

### ISSUE THREAD

**Issue by SHEKOLDA** [BSData/wh40k#4116]
Icarus stormcannon is currently 17 points, should be dropped to 10 (Chapter Approved 2018, page 132)

**Comment by SHEKOLDA** [comment]
@Kohato v67 Space Marines, doesn't seem to be fixed for Stalkers. Maybe it, s because their option is listed as "Two Icarus Stormcannons" and is separate? They still cost 34 instead of 20

**Comment by Kohato** [comment]
*Sigh* Yep, separate wargear. Good catch
