### ISSUE TITLE
Imperium - Deathwatch storshield for characters CA2018 cost

### ISSUE THREAD

**Issue by SHEKOLDA** [BSData/wh40k#4118]
Stormshield cost for characters is at 15 points now, should be dropped to 10 (Chapter Approved 2018, page 130)

**Comment by acebaur** [comment]
Showing as 10 points for me. Make sure you are on v46

**Comment by SHEKOLDA** [comment]
@acebaur right, v43 for me on Android, doesn't refresh for now for some reason
