### ISSUE TITLE
Adeptus Ministorum: Missing Warlord Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4121]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Celestine can't take either of the Gemini. Warlord Traits are unavailable for basically all of the characters, beyond the BRB ones.

**Comment by Kohato** [comment]
Germina Supria are in No Force Org while Celestine is in your list - WTs however are not yet finished.

**Comment by Kohato** [comment]
Duplicate of #4055
