### ISSUE TITLE
SM Intercessors Auxilary Grenade Launcher CA2018 Update

### ISSUE THREAD

**Issue by JasonMWelch** [BSData/wh40k#4126]
**File/Catalogue:** SM

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** The Auxiliary Grenade Launcher on Intercessors are back to costing 0 points as of CA 2018, still cost 1 atm.

**Comment by Kohato** [comment]
Duplicate - Fixed in latest release
