### ISSUE TITLE
Grey Knights: Dreadnought Missile Launchers/Incinerator CA2018 Points Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4129]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Points cost on greyknight dreadnought middle launchers is listed at 25 when it was reduced to 20 with CA.  Also doomglaive dreadnought incinerator should be 13 pts not 9.

**Comment by Kohato** [comment]
Duplicate - Fixed in latest release
