### ISSUE TITLE
Adeptus Custodes: Storm Shield CA2018 Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4144]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** Points not updated on Storm Shields for characters. Should be 10, is at the moment 15.
Points not updated for wardens. Base points should be 43, is at the moment 45.

**Comment by Kohato** [comment]
SS is a unique Shared Entry in Custodes. Hasn't been updated to match GST.
