### ISSUE TITLE
Space Marines - Captain on Bike CA2018 Points Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4154]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Space Marine Captain on Bike still without CA18 points. Don't know if reported.

Regards

**Comment by DedusJovus** [comment]
It's 88 in the latest file I downloaded from here
![capture](https://user-images.githubusercontent.com/26274301/50056360-646c9480-015b-11e9-8f14-2b43dfb50962.PNG)

**Comment by Kohato** [comment]
Derp, you're right, I was looking at Chaplain on bike when confirming the issue!
