### ISSUE TITLE
Aeldari - Craftworlds: Missing CA 2018 point changes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4157]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Craftworld Eldar point costs still need updated for a few things post CA 2018. Two death spinners should be 12 as they are now 6 each. Dire avenger Exarch taking two avenger catapults also needs updated. It’s like the double weapon entries didn’t get updated. Also the DA Exarch shimmershield needs updated.

**Comment by WindstormSCR** [comment]
Duplicate of #4030
