### ISSUE TITLE
Chaos - Chaos Space Marines - Missing Chapter Approved Changes

### ISSUE THREAD

**Issue by funguykharn** [BSData/wh40k#4159]
**File/Catalogue:** Chaos - Chaos Space Marines.cat

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Two missed point changes:
Maulerfiends are 120pts (old 140)
Havoc Autocannons are 10pts (old 15)

**Comment by GenWilhelm** [comment]
Duplicate of #4078
