### ISSUE TITLE
Imperium - Adeptus Custodes: Vexillus Praetor Storm shield cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4161]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.02.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** The storm shield (character) for a Vexillus Praetor should be 10 points following Chapter Approved 2018, but is currently 15 points.

**Comment by Mad-Spy** [comment]
Duplicate of #4144
