### ISSUE TITLE
Imperium - Adeptus Mechanicus: Datasmith should be able to select Warlord Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4162]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The Cybernetica Datasmith is capable of taking the Field Commander rule to take Specialist Detachment Warlord Traits but no such option exists for this Unit at this time.

**Comment by TurielD** [comment]
This bug (or something similar) appears to have returned - the Cybernetica Datasmith can select Warlord, and can select a Relic, but gets no Warlord Trait options.

**Battlescribe Version:** v2.03.01.128

**Platform:** Windows

**Dropbox:** No
