### ISSUE TITLE
Imperum - Blood Angels.catz

### ISSUE THREAD

**Issue by Olius90** [BSData/wh40k#4171]
**File/Catalogue:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** Updated points values and Intercessors data sheet from Chapter Approved 2018
[Imperium - Blood Angels.zip](https://github.com/BSData/wh40k/files/2683987/Imperium.-.Blood.Angels.zip)

**Comment by Kohato** [comment]
Hi, Thanks for the work - this update is in progress and will hopefully go out with our next release today/tonight.

**Comment by Olius90** [comment]
Ok, no problem. In case you plan to use my file, there is a minor bug with Intercessors' grenade auxiliary launcher, minimum value is set to 0 instead of 1
