### ISSUE TITLE
BA Redemptor Dreadnought not correct post CA2018

### ISSUE THREAD

**Issue by BillBarnes3** [BSData/wh40k#4180]
File: Imperium - Blood Angels.catz

BattleScribe version: 2.01.19

Platform: PC

Dropbox: No

Description: Imperium Blood Ángels - Redemptor Dreadnought points not adjusted yet.  Currently still 140, should be 105.

**Comment by Kohato** [comment]
Fixed about 5 minutes ago :D Will be in next release.
