### ISSUE TITLE
Not really an issue, but

### ISSUE THREAD

**Issue by DedusJovus** [BSData/wh40k#4185]
Actually, not an issue at all. I just wanted to thank all of you hard working people for doing this for us all and putting up with all of our annoying duplicate issues and non-issues (I know, irony). I wish you all happy holidays and whatever you celebrate (or not) this month. Thank you and keep up the good work =)

**Comment by Kohato** [comment]
<3

**Comment by flakpanda** [comment]
❤️

**Comment by amis92** [comment]
I think we can close it after a month of self-admiration 😎
