### ISSUE TITLE
adeptus ministorium aka adepta sororitas beta codex

### ISSUE THREAD

**Issue by CaptainStern** [BSData/wh40k#4186]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android

Hello guys, 
my reported bug is about the missing elite options according to the chapter approved 2018.
I am missing geminae superia, crusaders, death cult assassins, arco-flaggelants.
please add them to the elites section.
best regards.

**Comment by Mad-Spy** [comment]
Not sure what you mean? All of these units are in the Elites section of Adeptus Ministorum v41.

![image](https://user-images.githubusercontent.com/29306451/50076221-054d6500-01d9-11e9-9dbb-88bc52a8c5be.png)

**Comment by CaptainStern** [comment]
my bad ,
you are right it's already fixed. I used a version that was 2 days old. my apologies

**Comment by alphalas** [comment]
Also remember if you have Celestine or a Missionary/Uriah in your list, all those units move to No Force Org slot due to rules in the beta codex.
