### ISSUE TITLE
FW adeptus astartes, version 2.01, platform iOS, NO dropbox. Have an issue with the Leviathan Dreadnought, in its rules i cant find the option for Hunter-Killer missiles, but they are able to be chosen on the battlescribe file. Just a minor issue! 

### ISSUE THREAD

**Issue by ATR3US** [BSData/wh40k#4188]
**File/Catalogue:** FW adeptus astartes

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** Have an issue with the Leviathan Dreadnought, in its rules i cant find the option for Hunter-Killer missiles, but they are able to be chosen on the battlescribe file. Just a minor issue!

**Comment by GenWilhelm** [comment]
It was added in an erratum:
https://whc-cdn.games-workshop.com/wp-content/uploads/2018/04/imperial_armour_index_forces_of_the_adeptus_astartes.pdf

>**Page 30** – Relic Leviathan Dreadnought,
Wargear Options
Add the following bullet point:
‘• This model may take up to three hunter-killer missiles.’

**Comment by ATR3US** [comment]
Sorry, my bad, and alao sorry 4 long tittle, first post here :/

**Comment by GenWilhelm** [comment]
No worries. 😄
