### ISSUE TITLE
Imperium - Space Marines: Victrix Typos

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4189]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** Yes

**Description:** Spotted several typos of "Victrtix" instead of Victrix Honour Guard in the latest update whilst I was checking to see if they'd been added.

**Comment by battlebrother** [comment]
Don't know why this was anon since I was logged in when I submitted it but nevermind, I'm new to these things I'm afraid!
