### ISSUE TITLE
Chaos - Death Guard: Lord's power fist incorrect cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4191]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Lord have a 12 pt power fist, however Chapter approved 2018 reduced it to 9 pt.

**Comment by Mad-Spy** [comment]
Apparently, I'm crap at this and managed to miss removing all of the power fist modifiers.
