### ISSUE TITLE
Imperium - Space Wolves: TWC Storm Shield Points Correction from GW

### ISSUE THREAD

**Issue by timbrown81** [BSData/wh40k#4196]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Storm shield points for TWC were not adjusted in the CA 2018.  The SW Codex has 3 entries for stormshield, 2 were adjusted in CA.  The third one is specific to TWC at 10pts.  Per Simon Grant, the rules team will be reviewing this with the playtestors for possible adjustment in the future.  In the meantime, RAW has them at 10pts. 

![image](https://user-images.githubusercontent.com/6496672/50091917-aee12600-01da-11e9-8b20-d2e0d3679dd1.png)

**Comment by CrusherJoe** [comment]
Yes indeed, saw that this morning. It is a sadness.

**Comment by amis92** [comment]
Original thread: #4083
