### ISSUE TITLE
Imperium - Blood Angels: Intercessor points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4202]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Intercessors point cost should be 17 with Chapter Approved, it is currently still 18.

**Comment by john-hostetter** [comment]
Agreed - all of Blood Angels need updated still.

**Comment by Mad-Spy** [comment]
These should all be fixed in today's release.
