### ISSUE TITLE
Chaos - Chaos Space Marines: Land Raider lascannon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4205]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** 2x Twin lascannon on the Land Raider is 100 points (50 each) / should be 80 (40 each)

**Comment by Mad-Spy** [comment]
Fixed in today's release.
