### ISSUE TITLE
Imperium - Astra Militarum: Macharius Vulcan sponson costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4211]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 9.99.99

**Platform:** Android

**Dropbox:** Yes

**Description:** The macharius Vulcan (fw)has options to equip sponsons with a single heavy stubber each. The points cost needs to be updated

**Comment by Mad-Spy** [comment]
It looks like all of the options for this hardpoint are local and thus haven't been updated.
