### ISSUE TITLE
Chaos - Chaos Space Marines: Reaper autocannon costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4214]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Point cost for Reaper Autocannon for Helbrute and Chaos Terminators is still listed at 15 after latest update, should be 10.

Thanks for all your hard work!

**Comment by Mad-Spy** [comment]
Fixed in CSM v62.
