### ISSUE TITLE
Imperium - Astra Militarum: Unable to equip Pietrov's Mk45 on Company Commander

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4215]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Pietrov's Mk-45 pistol is no longer available for company commander.

**Comment by Mad-Spy** [comment]
You must select the Valhallan Regimental Doctrine, and equip the Company Commander with a bolt pistol which can be upgraded to the Mk45 and then it will be available in the Relic list.
