### ISSUE TITLE
Imperium - Blood Angels: Intercessor Sergeant should be able to equip power fist

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4218]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Intercessor sgt should have a power fist as a weapon option.

**Comment by Mad-Spy** [comment]
Fixed in Blood Angels v51.
