### ISSUE TITLE
Imperium - Space Wolves: Intercessor weapon costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4220]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 1.02.02

**Platform:** Android

**Dropbox:** No

**Description:** Intercessors Points Bug
Stalker Bolt Rifles = 0 pts
Auto Bolt Rifles = 1 pts

**Comment by Mad-Spy** [comment]
Fixed in Space Wolves v61.
