### ISSUE TITLE
Imperium - Grey Knights: Various point costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4223]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Warhammer 40k Chapter Approved 2018 was recently released,  it points values changes do not appear to be reflected for the unit: Imperium - Grey Knights. 

Unit type Troops - Terminators squad. Points are still showing 205 pts (41 per model); The new points value should be 195 pts (39 per model).

Unit type Heavy Support - all the various Land Raiders have reduction in points. If you need me to report line by line, will have to wait when I’m back at my desk.

**Comment by Mad-Spy** [comment]
Should all be fixed in Grey Knights v27.
