### ISSUE TITLE
Imperium - Astra Militarum: Rein and Raus require a Warlord Trait when selected

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4226]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Rein and Raus trigger a warlord trait required validation error. Might need a review for full keyword tags (i.e. are they characters?)

**Comment by Mad-Spy** [comment]
They are definitely Characters and can therefore be the Warlord. 

@alphalas, Warlord Traits are not mandatory. A model MAY take a Warlord Trait. Maybe consider just hiding the entire Warlord Traits SSEG, rather than setting min1 to 0?

**Comment by alphalas** [comment]
@mad-spy it’s weirdly a bug all the blackstone models seem to have been developing; I’ll get on it
