### ISSUE TITLE
Chaos - Chaos Space Marines: Chaos Terminators cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4227]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Chaos terminators point costs are incorrect, the new chapter approved base cost of 28 points INCLUDES a combi-bolter and a power axe. Currently these weapons are additional points making the terminators 35 points instead of 28. Thank you for your hard work!

**Comment by Mad-Spy** [comment]
This is incorrect. The base cost does not include wargear.

![image](https://user-images.githubusercontent.com/29306451/50142056-f92cda80-02a0-11e9-9c7e-b5923cfa8658.png)
