### ISSUE TITLE
FW Adeptus Astartes v33 Volkite Charger wrong cost

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k#4230]
**File/Catalogue:** FW Adeptus Astartes v33

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** The point cost for the volkite charger is wrong. Its 8, should be 3 for blood angels (only).

**Comment by Mad-Spy** [comment]
Which model is this on? I can't find a model in FW Adeptus Astartes which has a volkite charger?

**Comment by alphalas** [comment]
Only thing I can think of are cata terms.

**Comment by DedusJovus** [comment]
all chapters' tartaros terminators

**Comment by alphalas** [comment]
Those aren’t in FWAA though, which I think is where the confusion stems from. Those are in the individual cats. (Remember, they’re plastic and produced by GW so they’re actually in codecies).

**Comment by p5freak** [comment]
The terrax pattern termite assault drill has the option for twin volkite chargers. As a BA player i can pick this model. So terminators get them for 3 pts. but the drill has to pay 8 for one ?

**Comment by WindstormSCR** [comment]
Unfortunately yes at present, because FW is still using separated cost sections, and has not issued any rules or official errata linking its costs to GW points updates, simply followed them mostly in step
