### ISSUE TITLE
Indomitus Crusaders specialist detachment

### ISSUE THREAD

**Issue by rtho782** [BSData/wh40k#4252]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.01.15

**Platform:** Windows/

**Dropbox:** No

**Description:** The indomitus crusaders formation states that it is for use with any "Space Marine" detachment. This is not printed in bold implying it is not a keyword (indeed no units have "Space Marine" as a keyword.) Further, page 139 of Codex: Space Marines clearly states that a "Space Marine" unit is any unit with the "Adeptus Astartes" keyword, which Dark Angel units do have.

This may get FAQ'd in the future but RAW Dark Angels CAN use this, in addition to the Ravenwing Attack Squadron formation. Yes, there is a clear difference between the way the two formations are worded, as there are between this formation and the "Ultramarines Vitrix Guard" formation, but there has been no suggestion that Ultramarines cannot use the indomitus crusaders formation.

**Comment by Mad-Spy** [comment]
A Space Marines detachment is defined in Codex: Space Marines, p. 194

In the rules described in this section we often refer to ‘Space Marines units’. This is shorthand for any ADEPTUS ASTARTES unit that has one of the following Faction keywords: <CHAPTER>, ULTRAMARINES, IMPERIAL FISTS, SALAMANDERS, WHITE SCARS, RAVEN GUARD, IRON HANDS, CRIMSON FISTS or BLACK TEMPLARS. A __Space Marines Detachment__ is therefore one which only includes units with one of these keywords. (bold added by me)

Therefore, DARK ANGELS models cannot be a member of a Space Marines Detachment.
