### ISSUE TITLE
Imperium - Adeptus Ministorum: Incorrect points for Twin multi-melta

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4253]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The Twin Multamelta is listing at 54 points and should be 40.
The elite Geminae are not listed.

Thank you.

**Comment by Mad-Spy** [comment]
Geminae are listed, but move to No Force Org, when you take Celestine. This might be why you can't find them.
