### ISSUE TITLE
Imperium - Space Wolves: Wolf Lord is missing its default bolt pistol

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4259]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Got some points updates and info to pass on. Hope that's ok?
Wolf Lord can take bolt pistol in addition to bolter etc.
~~Venerable dreadnought is 10 points over priced and so is his dreadnought close combat weapon.~~

**Comment by Mad-Spy** [comment]
Dreadnought is fixed in Wolves v67.
