### ISSUE TITLE
Imperium - Grey Knights: Incorrect Points Values (Post-CA)

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k#4266]
**File/Catalogue:** Imperium - Grey Knights v27

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:**

Servitors — Something is whacky with all their base & wargear point costs. Servo Arms are now free, and each servitor is 2 points, making a full unit be 8 points (not 68!). Likewise, Plasma Cannon should be 16 points. Multi-Melta should be 22 points.

Knight of the Flame (Purifier Squad) — currently 28 points. Chapter approved changed to 21 points. 

Missile Launcher (Dreadnought, Venerable Dreadnought, etc.) — currently 25 points. Chapter approved changed to 20 points.

**Comment by Kohato** [comment]
Issues have been resolved in previous updates.
