### ISSUE TITLE
Imperium - Blood Angels - Intercessor Stalker Bolt Rifle

### ISSUE THREAD

**Issue by orlan89** [BSData/wh40k#4272]
File/Catalogue: Imperium - Blood Angels

BattleScribe version: 2.01.21.283

Platform:Android

Description: Stalker Bolt Rifles were changed to cost zero points in CA2018, but they are still listed at 2pts a piece for Intercessor units.

**Comment by Kohato** [comment]
This has already been fixed in the most recent data.
