### ISSUE TITLE
Space Marines: Blood Ravens Gabriel Angelos Missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4277]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** there is no listing in HQ units for Space Marines for the Forgeworld Released Chapter Master Gabriel Angelos of the Blood Ravens
if I knew how to add a unit I would get my Forgeworld .pdf card out and enter it into the data file so I can then have access to my Blood Ravens Chapter Master

thank you in advance
John Crouch
lupus_malus_magnus@yahoo.com

**Comment by Kohato** [comment]
He has been added to Codex SM - Only when you have Mixed/No Chapter or Blood Ravens chapter selected.

**Comment by Kohato** [comment]
Yea, I'm wrong - he's in FWAA already. I should look at that first hah.
