### ISSUE TITLE
Bug: Blood Angels Company Veterans with Jump Packs have incorrect cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#4278]
**File/Catalogue:** Blood Angels v50

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Blood Angels Company Veterans can take Jump Packs for 3 points per model, but should be 5 points per model. CA2018 made vanilla Company Veterans 14 points (down from 16), but Company Veterans with Jump Packs should still be 19 points per model, as per Index Imperium 1.

**Comment by Kohato** [comment]
Probably gonna piss some people off, but you're not wrong. The file was implemented with jump packs as wargear (because it's far easier that way) but the cost was not adjusted when the base model cost was lowered per CA.  Fixed in latest build.
