### ISSUE TITLE
Imperium - FW Adeptus Astartes: Dreadnought chainfist cost

### ISSUE THREAD

**Issue by lordasterionmoloc** [BSData/wh40k#4291]
ORGEWORLD adeptus Astartes
Dreadnought chain fists cost 38/48
Current points show them at 56

**Comment by lordasterionmoloc** [comment]
Well that didn’t work. 
FORGEWORLD adeptus Astartes 
Dreadnought chain fists cost 38/48
Current points show them at 56

**Comment by WindstormSCR** [comment]
this was already fixed in v34
