### ISSUE TITLE
Imperium - Astra Militarum: All Command Squad models should cost 5 points.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4293]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Astra Militarum Command Squads - veterans here are 6 points - they should now be 5 - including special weapons veterans and veteran heavy weapon teams etc. Thanks!

**Comment by Mad-Spy** [comment]
There has been no points change to the Command Squad, which is a separate unit to normal Veterans and has its own cost, which was not updated in CA2018.

**Comment by xamsham** [comment]
Veterans are the same models in both units.

**Comment by Mad-Spy** [comment]
That is not correct. They are models which happen to have the same name. The datasheet is for a Command Squad, which has its own cost in the Points table. This cost was not updated in Chapter Approved.

**Comment by alphalas** [comment]
![9AB48A1A-2AB6-4B0E-B618-CC5041369AC7](https://user-images.githubusercontent.com/15703066/60810153-69764d00-a15a-11e9-94fe-1744aa009dd2.png)
![5E654D09-5658-43D7-97DA-E424B9866716](https://user-images.githubusercontent.com/15703066/60810154-69764d00-a15a-11e9-8427-b2ff7edd1913.png)
![D9838181-10F4-4FBB-96CC-46CCB691BDCF](https://user-images.githubusercontent.com/15703066/60810155-69764d00-a15a-11e9-8c01-70f7d04aaf5c.png)
The absence of a command squad entry confirms @Mad-Spy
