### ISSUE TITLE
Chaos - Chaos Space Marines: Maulerfiend cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4299]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Maulerfiends in Chaos Space Marines are not updated with CA points values - still showing 140 points base (excluding wargear) instead of the new 120 points base. Data version for CSM that I’m using is v60 in Warhammer 40,000 v1.2.04 .

**Comment by Mad-Spy** [comment]
Fixed in v65.
