### ISSUE TITLE
Imperium - Space Wolves.cat - ThunderWolves StormShield Cost Inc

### ISSUE THREAD

**Issue by DessaiImrane** [BSData/wh40k#4308]
**File/Catalogue:** Imperium - Space Wolves.cat

**BattleScribe version:** 2.01.15.114

**Platform:** Mac

**Dropbox:** No

**Description:** Detailed issue description.

As seen in the attached screenshoot, TW StormShield cost should be 2 and not 10. 

My file is up-to-date

I guess it is related (the opposite way) to   : #4120  

![image](https://user-images.githubusercontent.com/1715606/50380919-8ac98d00-0691-11e9-8a57-a0ad2b9726f1.png)

**Comment by alphalas** [comment]
https://user-images.githubusercontent.com/13433600/50088373-21fe9280-0203-11e9-97f0-f5b0cd7a8064.jpg
