### ISSUE TITLE
Space Wolves:  Sergeant unable to select weapon when squad does

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4318]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** INTERCESSOR SQUAD
why you are wrong and the use of may is that every one has a choice 

if it was that only the people can only take the same gun why can the sargent take a diffrent wepons then chaper aproved 2018. 
i know that english is hard on a lot of people me includsed me.
but i do know what may is and that is a posablity of somthing not i can only take one thing and that is that 

may vs can only in other language may simply does not exist even when speaking to a ton of diffrent people and a language professor, and a speech pathologist.

what i segust is how scouts are set up to be how we slect the people in side of the unit.

"All modles in the unit may replace ther bolt rifle with a auto bolt rifle or a stalker bolt rifle" 
"All modles in the unit possibly  replace ther bolt rifle with a auto bolt rifle or a stalker bolt rifle"
"All modles in the unit can only replace ther bolt rifle with a auto bolt rifle or a stalker bolt rifle"
"All modles in the unit can replace ther bolt rifle with a auto bolt rifle or a stalker bolt rifle"
v1 as the one that is written gives caveats that any wepon can be taken or changed out
v2 is how it shood be read
v3 is how people understand it
v4 what most people under stand it to be

1.
expressing possibility.
"that may be true"
used when admitting that something is so before making another, more important point.
"they may have been old-fashioned, but they were excellent teachers"
2.
expressing permission.
"you may use a sling if you wish"

**Comment by WindstormSCR** [comment]
"all models in the unit" < the specified actor in the sentence
"may" < specifies optional thing that can be done but is not required
"replace XXX" < action that the specified actor has the option to do.

the sergeant options are a separate line, and give him specific exemption to ditch the rifle and use only a bolt pistol and close combat weapon option.

Yes the current space wolf files have an issue of the sergeant being unable to correctly select an auto or stalker bolt rifle when his squad do, but the lecture on language (with ironic terrible spelling) was unnecessary and rude.

**Comment by williamcaw** [comment]
by your reasoning the Sargent cant take his melee weapons sir or mam.
