### ISSUE TITLE
Chaos Daemons: Add Wrath and Ruin Models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4323]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Missing the infernal enchantress from characters. Please update

**Comment by Kohato** [comment]
@Mad-Spy Since you're gone on holiday - I've added The Enrapturess - I copied the format of your other entries so it should match up. Please feel free to go over it and change though!
