### ISSUE TITLE
Discussion: Option to hide FW-sourced units from view in roster construction.

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#4334]
There is simply so much FW bloat it actually becomes a detriment to list building. I think that if Space Marines are considered viable enough to be isolated in their own file because of all the bloat, the Astra Militarum ones should also be shuffled off into their own file for the same reason.

**Comment by alphalas** [comment]
The reason FW was offloaded to a separate cat for astartes is because they have to be shared across 6 cats; AM unfortunately doesn’t suffer from that issue since both DKoK and EDT are designed to be self-sufficient

**Comment by BaconCatBug** [comment]
Fair enough. My point still stands that the amount of FW entries for AM is large enough to offload to their own file IMHO since I assume some sort of hiding isn't possible (ala Regiments and Characters).

**Comment by WindstormSCR** [comment]
Hiding might be possible, but such a thing would set a precedent and would need to be discussed. To that end, I'm going to label this for discussion, 
Options:
A) Retain current implementation. 
B) Use a NFO entry in the GST file labeled "Hide FW Entries". This retains current implementation if nothing is done, and would require minimal work for most catalogs. (FW-only cats can ignore it entirely)
C) other suggestion????

**Comment by CrusherJoe** [comment]
Maybe we should table this until BattleScribe v2.unicorn is released?

**Comment by WindstormSCR** [comment]
After some discussion overnight, decision has been taken to retain current implementation. Issue closed
