### ISSUE TITLE
Blood Angels: Veteran Bolter Collective Error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4347]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** As per the codex, any Space Marine Veteran may replace their chainsword with a Boltgun. However the app forces you to put Bolters on the whole squad (if you tick the Bolter on a veteran, it automatically appears on the rest).

**Comment by Kohato** [comment]
Mmm, Collective bugs.
