### ISSUE TITLE
Imperium - Dark Angels: Primaris Master Power Sword and Keyword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4354]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Data entry for Dark Angels Primaris Master is missing the option to give him a Power Sword on top of his rifle/pistol loadout. 

Also: the same Primaris Master is wrongly allocated the „faction: Deathwing“ keyword.

**Comment by WindstormSCR** [comment]
The power sword option is there, it's simply a step down inside the weapon loadout.
