### ISSUE TITLE
Death Guard: Mortarion Degredation Profile Typo

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4360]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Mortarian's Wound profile shows Mortarian 3 as being 9-18+ which is also shown as the wound profile for Mortarian 1.

**Comment by Mad-Spy** [comment]
Fixed in v52.
