### ISSUE TITLE
Chaos Space Marines - Helbrute needs Missile Launcher

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4363]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Helbrute has wrong weapon option set up. Missile launcher should be a option for Helbrute Fist replacement not Multi Melta. ie there should be an all shooting version.

**Comment by Mad-Spy** [comment]
Remove the default equipped fist (by selecting it and then pressing Delete), and then you'll be able to add 2 ranged weapons.

![image](https://user-images.githubusercontent.com/29306451/50563271-4aae7e00-0d13-11e9-9046-2e0a136709c3.png)
