### ISSUE TITLE
Daemons: Blue Scribes Sorcerous Barrage Text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4364]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Blue scribes Xirat'p's Sorcerous Barrage was changed in the codex

"Though not a PSYKER, the Blue Scribes automatically manifest one randomly selected psychic power from the Tzeentch discipline each Psychic phase. "

This sentence was changed to "......from the Tzeentch discipline (pg.132) in your Psychic phase. "

**Comment by Mad-Spy** [comment]
Fixed in v47.
