### ISSUE TITLE
FW Renegade and Heretics: Points for Grenade Launcher

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4366]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Grenade launchers are still 5 points.  Should be 3 points with the new FAQ.  

Great work as always guys. Much appreciated.

**Comment by Mad-Spy** [comment]
Fixed in v30.
