### ISSUE TITLE
Renegade and Heretics: Points Error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4367]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Missile Launcher is still showing as 20pts.  Should be 15 as per the new FAQ.

Flamer is showing as 7pts, but should be 6.

Meltagun is showing as 12pts, but should be 10.

Cheers matey

**Comment by Mad-Spy** [comment]
Fixed in v30
