### ISSUE TITLE
[Anon] Bug report: Chaos - Titanicus Traitoris.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4370]
**File:** Chaos - Titanicus Traitoris.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Their are a lot of things wrong with the thousands sons point values. Too many to list. Was fine until the update.

**Comment by Kohato** [comment]
Once again, raising an issue like this does not help. Take a look at CA2018, make sure you're referencing correct data, and please provide examples of incorrect data.
