### ISSUE TITLE
Codex Supplement: Crimson Fists (New Publication)

### ISSUE THREAD

**Issue by Davey-Jone-s** [BSData/wh40k#4376]
**File/Catalogue:** 

**BattleScribe version:** 2.01.15

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** New Crimson Fist Chapter Tactic, Warlord Traits and Relic added in WD Jan 19.

**Comment by Kohato** [comment]
You are correct. Once we either get a copy early or get the copy of WD, our SM maintainer will be able to add it. Even so - it will not be released until the mag officially releases, same as our other releases for new publications.

**Comment by WindstormSCR** [comment]
Unfortunately as far as I know, most of us in the maintainers team do not have an active WD sub, so it may take slightly longer to get them implemented. I'll keep an eye out for any online leaks until then.

if you care to, you could PM me just the relevant pages via reddit: /u/WindstormSCR
