### ISSUE TITLE
Imperium - Astra Militarum: Lord Commissar Cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4379]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Lord Commissars are 30 points now instead of 35 points

**Comment by WindstormSCR** [comment]
the 35 includes the default wargear for the model. base is 30 plus the pistol and sword.
