### ISSUE TITLE
Space Wolves: Intercessors should not have combat squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4383]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 1.02.06

**Platform:** Android

**Dropbox:** No

**Description:** 
~~The intercessor pack is coming up with the combat squads rule when viewing the army list, but this rule doesn't apply to space wolves.~~

Also the long fang pack leader T value is blank

**Comment by benbutters** [comment]
Sorry I got the version number wrong should be 2.01.21

**Comment by williamcaw** [comment]
refer to chapter approved 2018

**Comment by Mad-Spy** [comment]
As per williamcaw's comment, the Intercessor datasheet was updated in Chapter Approved 2018, and all Intercessor squads do now have the Combat Squad rule.

**Comment by benbutters** [comment]
Chapter approved states to remove this rule for the space wolves.

Pg140 "it also replaces the intercessors datasheet in codex:space wolves (change the datasheet title to intercessors, replace intercessor sergeant with intercessor pack leader throughout, remove the combat squads ability, replace the <chapter> keyword with space wolves and replace intercessor squad keyword with intercessors)"

**Comment by Mad-Spy** [comment]
Oops! Missed that part.
