### ISSUE TITLE
Shadowsun weapon profile adjustment

### ISSUE THREAD

**Issue by Shadowsunismybigtiddytaugf** [BSData/wh40k#4386]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by tekton** [comment]
![image](https://user-images.githubusercontent.com/137810/50728116-c4f74d80-10d9-11e9-83b6-e62dd2c0d3cd.png)

The "view roster" output will only show a single weapon, but the selections does say 2x
