### ISSUE TITLE
Imperium - Space Marines: Implement Vigilus special detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4388]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Not a bug but a question. Is there any way to add the special detachments for space marines or am I just dumb and don't know how to put it in my list ?

**Comment by Mad-Spy** [comment]
They haven't been implemented yet in the main Space Marines catalogue.
