### ISSUE TITLE
Imperium - Adepta Sororitas missing Geminae Superia

### ISSUE THREAD

**Issue by Caboose816** [BSData/wh40k#4389]
**File/Catalogue:** Imperium - Adepta Sororitas

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** Saint Celestine has no Geminae Superia in her entire, and there are no Geminae Superia entries in the Elites section.

**Comment by Kohato** [comment]
You are correct! Check the codex. When you select Celestine, the Geminae do not take up a Force Org Slot, so they are in the No Force Org Slot section.
