### ISSUE TITLE
Elysian Officer of the Fleet unable to select Warlord Trait & Missing Sergeant Aux Grenades

### ISSUE THREAD

**Issue by neonionus** [BSData/wh40k#4394]
**File/Catalogue:** FW - Elysian

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** When ticking the checkbox for "Warlord" for the Officer of the Fleet in a FW/Elysian detachment, the list for selecting Warlord Traits does not come up. The Officer of the Fleet is also missing the "OFFICER" keyword, which in turn means they should have Kurov's Aquila available in their heirlooms of conquest list. 

~~The sergeant for Elysian Drop Trooper Squads is also missing the option to replace their Laspistol with a Lasgun with Auxiliary Grenade Launcher which is an option as per the IA Index Astra Militarum FAQ.~~

**Comment by alphalas** [comment]
I so wish drop troop squad sgts could take aux launchers but @genwilhelm is correct

**Comment by alphalas** [comment]
Also the bug is a copy-pasta error, from importing from C:AM to EDT. Will fix, thanks!
