### ISSUE TITLE
Chaos - FW Renegade and Heretics: Militia stubber should be 2pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4395]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Thanks for the fixes so far, but noticed that the Heavy Stubber for renegade militia is still 4 points (should be 2).  

Cheers again
Stu

**Comment by Mad-Spy** [comment]
Fixed in v32
