### ISSUE TITLE
Chaos - Death Guard: Reaper autocannon cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4398]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Reaper autocannon has had a points reduction in Chapter Approved 2018, and is now at 10 points. Please rectify this before I lose my mind :)

**Comment by Mad-Spy** [comment]
I apologise. I am a terrible useless person who should stop doing this job for free.

Fixed in v54.
