### ISSUE TITLE
Chaos - Renegades and  Heretics - Baneblade

### ISSUE THREAD

**Issue by gitbrabbin** [BSData/wh40k#4403]
The wording for the Steel behemoth rule for the Baneblade in renegades does not match that for the Astra militarum Baneblade (and maybe other lords of war?) Specifically the moving and firing heavy weapons line.

As the two are meant to be identical can the renegade and heretic entry be updated to new one?

Cheers for all your hard work :)

**Comment by Mad-Spy** [comment]
Don't you just love it when GW use the same name for a slightly different rule so it's really hard to maintain! Fixed in v33.

**Comment by gitbrabbin** [comment]
Cheers for the work :)
