### ISSUE TITLE
Orks - Runtherds Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4404]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Orks runtherds missing in the elites section. They do not count against avilible elites slots,

**Comment by Mad-Spy** [comment]
They can be found in the "No Force Org Slot" section, as they never actually count towards the Elites, and this is the only way we can represent this.
