### ISSUE TITLE
Imperium - Space Marines: Devastator Sergeant wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4405]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** In the codex Space Marines the Space marine sergeant for the devastator squad has the option of swapping his bolt pistol for another type of pistol, however on the datafile this is not possible as it does not allow you to deselect the bolt pistol. 

This causes an error to show for the army list when you try to give the sergeant the pistol you want instead of the bolt pistol.

**Comment by Mad-Spy** [comment]
A Devastator Sergeant may _not_ swap his bolt pistol at all. He can only swap his boltgun.

![image](https://user-images.githubusercontent.com/29306451/50765035-9067cb00-126c-11e9-960f-d213ba22f004.png)
