### ISSUE TITLE
Chaos - Chaos Space Marines: Add Obsidius Mallex to main CSM catalogue.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4410]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Obsidius Mallex is missing under Black Legion detachments. Since you can use him in both Servents of the Abyss and Black Legion detachments.

**Comment by Mad-Spy** [comment]
Added in v70.
