### ISSUE TITLE
Chaos - Death Guard: Deathshroud missing Gauntlets?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4431]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Deathshroud terminators all have a plaguespurt gauntlet, champion has option for 2. In BattleScribe only the champion has them equipped, not the other ones.

**Comment by Mad-Spy** [comment]
It sounds like you're outputting in minimal mode. Battlescribe doesn't output free default gear when you do that. The entry for the normal Deathshroud definitely has the Gauntlets equipped.
