### ISSUE TITLE
Craftworlds Eldrad hidden if Ynnari is picked

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k#4435]
**File/Catalogue:** Aeldari - Craftworlds v57 

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Maybe nothing but if I select Ynnari as my craftworld attribute Eldrad becomes hidden.  As far as I can tell looking at FAQs the only banned model from the Craftworlds faction is the Avatar of Khaine (which hides correctly).

Please let me know if I'm wrong and just missing the info somewhere.

**Comment by WindstormSCR** [comment]
This is an artifdact of some recent logic changes, will fix.
