### ISSUE TITLE
Incorrect weapon selection for skyclaw pack leader

### ISSUE THREAD

**Issue by Garvlok** [BSData/wh40k#4436]
**File/Catalogue:** Imperium - Space Wolves  v66

**BattleScribe version:** 2.01.21.283

**Platform:** Android

**Dropbox:** No

**Description:** In battlescribe it looks like skyclaw pack leader may take any weapon from the melee list however in the codex they can only take chainsword, power axe, power fist and power sword.

**Comment by Mad-Spy** [comment]
The options from the Index are still valid, as per the Designer's Commentary flowchart.
