### ISSUE TITLE
Chaos - FW Renegade and Heretics: Missed CA2018 points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4448]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Hi dude. 
Just noticed that multilasers on the sentinels is 10pts.  Should be 5pts. 
Also, on the Leman Russ tank, as lascannon sponson is showing as 25pts.  It should be 20pts.

Cheers as always for all of your great work

**Comment by Mad-Spy** [comment]
Fixed in v34.
