### ISSUE TITLE
T'au Empire: Detachment validation errors

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4449]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** Windows

**Dropbox:** No

**Description:** T'au Empire v38.  Vanguard Detachment requires 1 HQ selection, 3 or more selections from Elites AND 3 or more selections from Heavy Support.  Page 244 Vanguard Detachment diagram shows the requirement as 1-2 HQ selections and 3-6 Elites.  There is no requirement for Heavy Support.  Note that the Vanguard and Spearhead detachments both require the same units in BattleScribe but not in the rulebook. 2.02.00.111.BETA is my version showing in "About" in BattleScribe.

**Comment by Mad-Spy** [comment]
Not sure what is going on here as the minimum requirements are fine in the current version of the datafiles. If you can provide further information on your force structure, please let us know.
