### ISSUE TITLE
T'au Empire: Vanguard validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4450]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** Windows

**Dropbox:** No

**Description:** Vanguard T'au Empire Force requires 3-6 Elite units, but if I put in 3 it says I have 1 too many, and if I delete one it then says I am short an Elite unit and have to have a minimum of 3.

**Comment by Mad-Spy** [comment]
As per #4449 , there are no problems with the validation in the current version of the data files. Please check your Roster structure to ensure you have not accidentally nested some detachments.
