### ISSUE TITLE
T'au Empire: Spearhead validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4451]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** Windows

**Dropbox:** No

**Description:** Spearhead detachments page 244 of the 8th edition rule book requires a minimum of 1 HQ unit and 3 Heavy Weapon units.  My T'au Spearhead force on Battlescribe requires a minimum of 1 HQ unit, 3 Heavy Weapon units, and 3 Elite Units.  There should be no requirement for Elites.

**Comment by Mad-Spy** [comment]
As per #4449 , there are no problems with the validation in the current version of the data files. Please check your Roster structure to ensure you have not accidentally nested some detachments.
