### ISSUE TITLE
T'au Empire: Spearhead validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4452]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** Windows

**Dropbox:** No

**Description:** T'au Spearhead Detachment page 244.  When I choose a HQ unit and 3 Heavy Weapon units the program says I have too many Heavy Weapon units.  If I delete 1 Heavy Weapon unit it says I now require 3 minimum.  3 should be the minimum with 6 the maximum.  Note it also requires 3 Elite units although the 8th Edition rule book doesn't.

**Comment by Mad-Spy** [comment]
As per #4449 , there are no problems with the validation in the current version of the data files. Please check your Roster structure to ensure you have not accidentally nested some detachments.
