### ISSUE TITLE
Chaos - Chaos Space Marines: Helbrute weapon options issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4456]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hellbrute is missing equipment from items that it can take from the index.

**Comment by Mad-Spy** [comment]
The wargear options block is identical between the Index and Codex, so I'm not sure how this could be the case? Can you give a specific example of what you believe is missing.

**Comment by Mad-Spy** [comment]
Closing as implementation appears to be correct and OP has not clarified.
