### ISSUE TITLE
Aeldari - Harlequins - Solitaire Missing Warlord Option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4457]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Solitaire and Death Jester (both characters) are missing the option to be the Warlord and subsequently assign a warlord trait.

**Comment by WindstormSCR** [comment]
The solitaire is forbidden from ever having a warlord trait. however you are correct that there currently is no ability to select them as a warlord. Will fix for next release

**Comment by FarseerVeraenthis** [comment]
Death Jester already has the option to be chosen as a Warlord in v17.
