### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Trojan Support Vehicle and Transports

### ISSUE THREAD

**Issue by Cultiststeve** [BSData/wh40k#4461]
**File/Catalogue:** v93

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
* In the Death Korps catalogue, the Trojan Support Vehicle has the profile called Chimera, and stat Damage called Chimera *.
* It has no transport profile
* The storm chimera and centaur have ability profiles for their transport capability, not transport profiles.

Also in the AM cat, the Trojan's transport rule is an ability, not a transport profile like a chimera's.

**Comment by alphalas** [comment]
the stat damage profile is chimera simply because the trojan uses the chimera stat group due to having the same statline and for simplification.
