### ISSUE TITLE
Imperium- adeptus mechanics points

### ISSUE THREAD

**Issue by CharredCaptain** [BSData/wh40k#4471]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** the chapter approved points changes haven't been implemented for this faction (I do not know about the others)

**Comment by Thairne** [comment]
I am pretty much sure they are in, as I am the one that did them and use them to this day ;)
Check your data, you might be out of date.
