### ISSUE TITLE
Imperium - Dark Angels: Intercessor Sergeant loadout error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4472]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** For some reason there is an error then i try to arm my intercessor sergeant both with stalker bolt rifle and power sword but he can do that. To prove my words remember limited intercessor sergeant that GW released last year. He has wargear that i describe earlier. And the second problem is that i can't give indomitus crusader specialist detachment to dark angel primaris marines. Fix these problems please.

**Comment by Thairne** [comment]
>and the second problem is that i can't give indomitus crusader specialist detachment to dark angel primaris >marines. Fix these

DARK ANGELS are not SPACE MARINES, as stated by the recent FAQ.
