### ISSUE TITLE
Chaos - Chaos Space Marines: Sorcerer in Terminator Armour Psychic Power Limit

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4486]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.02.07

**Platform:** Android

**Dropbox:** No

**Description:** Chaos sorcerer lord in terminator armour: codex allows this unit to take smite and two other psychic powers, however currently the database only allows one other power

**Comment by williamcaw** [comment]
in chaos space marines Chaos sorcerer lord in terminator Armour. verified only 1 section of powers while chaos death guard can do so and select 2.

**Comment by GenWilhelm** [comment]
Working correctly on my end. Could you be more specific about how the error occurs?

![image](https://user-images.githubusercontent.com/22036809/51444357-642d5f00-1cee-11e9-8a09-46792848d0e5.png)

**Comment by Mad-Spy** [comment]
I think you're probably trying to select a Mark-specific power when you don't have the relevant mark. 

Tbh, now I look at it, it could almost certainly be improved by hiding the powers rather than just making them give an error.
