### ISSUE TITLE
Tyranids: Incorrect Points and Wargear Options?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4489]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The tyranid list seems to be the 7th edition list. All of the points values are incorrect and many of the weapon options aren't valid for the 8th editions rules.

**Comment by GenWilhelm** [comment]
Could you be more specific about what exactly is incorrect?

Please cross-reference the Codex with the Index for wargear options, and the Codex with Chapter Approved 2018 for points values.
