### ISSUE TITLE
Imperium - Space Marines: Unable to select Victrix Guard relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4499]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Ultramarines Victrix Guard special detachment is missing Standard of Macragge Inviolate on Ancients of all kinds

**Comment by WindstormSCR** [comment]
Fixed for next release along with calgar and roboute CP additions
