### ISSUE TITLE
Chaos - Death Guard: Chaos Lord should have blight grenades/Plagueburst Explodes rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4506]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos Lord have blight grenade and krak grenades on codex, but frag and krak on battlescribe
Plagueburst crawler explodes on 5+ (codex), not 6+ (battlescribe)

Amazing work nonetheless!!! Thanks for the updates :)

**Comment by Mad-Spy** [comment]
Well, both of those have been there since I did the Codex updates! Good spot.
