### ISSUE TITLE
Aeldari - Drukhari: Court of the Archon model costs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4519]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Points value for the 4 members of court if the archon (drukhari)
Are not in line with chapter approved 2017

**Comment by Mad-Spy** [comment]
They shouldn't be, because Codex Drukhari came out after CA 2017 and therefore the costs from that book take precedence.
