### ISSUE TITLE
Imperium - Adeptus Custodes: Telemon Dreadnought Caestus Fixes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4522]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Telemon Dreadnought Caestus needs some changes. 

- [x] Damage is now flat 4 (Not flat 3)
- [x] no  longer re-rolls wound rolls. 
- [x] Also taking a pair of Caestus gives +1 attack.

**Comment by WindstormSCR** [comment]
Good catch, will fix for next release

**Comment by natecross1990** [comment]
No problem. Everything else looks spot on. Thanks for all the hard work :)
