### ISSUE TITLE
Deathwatch venerable dreadnought missing index weapon options

### ISSUE THREAD

**Issue by THusky1** [BSData/wh40k#4524]
see title. Index DW references index SM for venerable dreadnought, therefore DW venerable dreadnought is entitled to select index weapons. Note that twin auto cannon on venerable dreadnought is not entitled to CA2018 points reduction as index points costs were not changed and twin auto cannon does not have entry in DW codex.

**Comment by GenWilhelm** [comment]
Index Deathwatch use modified version of the Space Marines datasheet, as specified in their army list on page 171. One of the modifications is their Dreadnoughts can't replace their CCW arm with a twin autocannon.

![image](https://user-images.githubusercontent.com/22036809/51909693-2357d900-23c5-11e9-8905-95bea2a0f0e6.png)
