### ISSUE TITLE
Land raider point cost changed in chapter approved

### ISSUE THREAD

**Issue by demonhammer** [BSData/wh40k#4526]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Hi not sure how this works but when looking up where to bring up user issues on the subject of Land raider point cost change in chapter approved i found a link to hear so i want to bring up the fact that the current cost is 297 points on the battle scribe app on both PC and IOS but it has been a while since chapter approved where it was reduced to 200 points for both the land raider and crusader and 180 for the redeemer, so could someone please update the cost listed on the app

**Comment by acebaur** [comment]
Those points have been updated but the changes in CA are to the cost of the vehicle without any weapons. So the cost of those weapons is added when you see the price in Battlescribe
