### ISSUE TITLE
Blank Roster View on Android Devices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4541]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Lastest 40k 8th edition update allows me to build list but when I click on the eye icon to view the data sheets it is just a blank screen . Have tried uninstalling and redownload data file in case it was corrupted but no joy cheers jim

**Comment by WindstormSCR** [comment]
We're trying to reproduce this behavior on our end, but no luck so far. Device Type and Android build information would help if the app creator decides to drop in and investigate.

**Comment by CadianSon** [comment]
Im having the same issue. If i go to setting and set it to plain text or bbc code ill get a roster i can see but the normal html setting shows up blank. I have a samsung galaxy 7.

**Comment by WindstormSCR** [comment]
Definitely something to do with the battlescribe app itself and html handling on android after the recent android system updates, will require the app developer to fix, nothing we can do from the data side

**Comment by CadianSon** [comment]
Thank you guys. Its working normal now again on my phone. Appreciate  it.
