### ISSUE TITLE
[Tau Empire] Crisis suits/bodyguards minimum equipment

### ISSUE THREAD

**Issue by Cartesian214** [BSData/wh40k#4545]
**File/Catalogue:** Tau Empire v40

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** A minor issue, but the codex states that _"Any model may replace its burst cannon with **up to** three items from the Ranged Weapons and/or Support Systems list."_

"up to 3" includes the number 0, therefore Crisis suits and Crisis Bodyguards can be fielded with no Wargear, however Battlescribe is throwing an alert claiming they require at least 1 Wargear option.

**Comment by tekton** [comment]
You do have to replace it with something from either of those lists, otherwise it has it's trusty burst cannon to fall back on. Sorry for the confusion and thank you kindly for the report!

**Comment by Cartesian214** [comment]
Perhaps this is something to ask GW then.  But I would maintain that RAW replacing the burst cannon with nothing does satisfy the "replace with up to three items" condition and is a valid build.

**Comment by DrTobogganMD** [comment]
Replace 1 with 0 is not a valid option in any book ever printed for 8e. Flat No. Feel free to submit it to GW for Errata and should it be posted as such, it will change here.

Saying "Well it doesn't say I can't, so I must be able to" is a very backwards way of looking at this. It also doesn't say I can't toss all of your models in the bin and declare you tabled, so I guess that's a rule yea?
