### ISSUE TITLE
Imperium - Adeptus Mechanicus - Tech Priest Manipulus 

### ISSUE THREAD

**Issue by Armond-Hammer** [BSData/wh40k#4556]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Points cost is still off. Base point cost should be 85. The 90pt cost should be including the Magnarail lance weapon. In addition. Text for Galvanic Field should be Units within 6" and not Models within 6" for both Bolster Warriors and Bolster Weapons.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/52167890-719d0d00-2722-11e9-981b-0e7240b1c361.png)
Base 85.
Comes with Magnarail standard as per datasheet -> 90 pts in list selection.

Ability description also mentions UNITS and not MODELS.

![grafik](https://user-images.githubusercontent.com/8590840/52167900-a14c1500-2722-11e9-91d3-d2b5b0d87c8e.png)
