### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Exterminator Autocannon cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4563]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Death Korps Leman Russ Mars-Alpha Battle Tank - Exterminator Autocannon is the wrong points.
The listed points for the Exterminator Autocannon is 25pts. It should be 17pts as per CA2018.

**Comment by Mad-Spy** [comment]
Merged into #4561
