### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Executioner plasma cannon incorrect points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4564]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Leman Russ Mars-Alpha Executioner gun is the wrong points.
The Executioner Plasma Cannons is listed as 20pts, it should be 15pts as per CA2018.

**Comment by Mad-Spy** [comment]
Duplicate of #4561
