### ISSUE TITLE
Imperium - Dark Angels: Problems adding Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4576]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 1.22.28

**Platform:** Android

**Dropbox:** No

**Description:** Unable to give any character's the std 1 extra relic unless I select them as warlord even if I already have a warlord

**Comment by Mad-Spy** [comment]
There is no "standard extra relic". You get a free relic if your warlord is from your faction, i.e. if you mark a Dark Angels character as our Warlord, you can then add a Relic to any DA character. 

You can pay for additional relics by selecting the "Relics of the Rock" stratagem from the "No Force Org Slot" section in the Roster. This will allow 1 or 2 relics depending on which option you choose.
