### ISSUE TITLE
Heavy Mining Laser Stat issue

### ISSUE THREAD

**Issue by Ghost4225** [BSData/wh40k#4578]
**File/Catalogue:8th Edition 40k Tyranids: Genestealer Cults v29

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Heavy Mining Laser was confirmed to be Heavy D3, but is still listed as Heavy 1. Both Ridgerunner and Rockgrinder display them the same.

**Comment by GenWilhelm** [comment]
Thanks!

I haven't gotten a good look at the armoury yet, so any changes to weapon profiles probably won't have been made yet (with a couple of exceptions). I'll give the whole catalogue a once-over before I release (either tonight, or tomorrow morning), just as soon as I get my hands on the book

**Comment by GenWilhelm** [comment]
Fixed by 78987c84207ab9b5cec3b27b156551bb3bac641c.
