### ISSUE TITLE
Aeldari - Ynnari: Error when selecting Ynnari "craftworld"

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4581]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** when selecting ynnari with craftworld, using craftworld attribute ynnari - says too many have been selected max 0.  Doesn’t matter if I put craftworld nested in ynnari or viva versa!   Also don’t know whether this is a data issue or app issue so attempting to report here. I have Mac and iPhone editions and this is the same in both.

**Comment by Mad-Spy** [comment]
Related to #4435?

**Comment by DrTobogganMD** [comment]
You have to select a Ynarri Warlord to have a Ynarri force. Select one of the 3 as your warlord and the Ynnari attribute is now valid.

**Comment by WindstormSCR** [comment]
Per the big FAQs, current implementation is correct.
