### ISSUE TITLE
Tyranids - Genestealer Cults: Abominant warlord max error.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4585]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Genestealer Cult’s - Abominant 
Selecting the abominant as warlord give the error ‘too many selections of warlord. Maximum 0’

**Comment by GenWilhelm** [comment]
Do you have a Patriarch in your army? If so, an Abominant can't be your Warlord in a matched play game.

![image](https://user-images.githubusercontent.com/22036809/52534528-97d23680-2d3a-11e9-8308-4574f2ecbd17.png)
*Codex: Genestealer Cults p108*
