### ISSUE TITLE
Imperium - Astra Militarum: Brood Brothers

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#4586]
![image](https://user-images.githubusercontent.com/22036809/52535388-c570ad00-2d45-11e9-9764-beabebd0a7d7.png)
*Codex: Genestealer Cults p108*

The gist of it is:
- [x] No named characters.
- [x] No ObSec.
- [x] No regiment-specific items.
- [x] All infantry gain +1 Ld and Unquestioning Loyalty ability (this ability should already be present due to having GSC in the army).
- [x] No Warlord.
- [x] No Relics.
- [x] Half CP from detachments.

**Comment by WindstormSCR** [comment]
detachment CP modifier will have to be done in GST. I recommend just adding a brood brothers category to the gst and adding it to that entry in the regiment selector, then having the GST work off that
