### ISSUE TITLE
Tyranids - Genestealer Cults: Goliath Rockgrinder Drilldozer blade cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4587]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 1.02.13

**Platform:** Mac

**Dropbox:** No

**Description:** The base cost for Goliath Rockginders is 5 pts too low. It looks like the 5 pts for the drilldozer blade were omitted.

**Comment by GenWilhelm** [comment]
The drilldozer blade doesn't cost 5pts.

![image](https://user-images.githubusercontent.com/22036809/52558588-b42dac00-2dea-11e9-84f3-286a349badc3.png)
*Codex: Genestealer Cults p118*
