### ISSUE TITLE
Imperium - Space Wolves: Storm Wolf lascannons cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4589]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Twin las cannons on storm wolf should be 40pts as per chapter approved but are stil showing as 50 on BS
😀

**Comment by lble** [comment]
Don't think this change is correct. Spent a while trying to figure out why my list got cheaper. The stormfang has two lascannons at 25 pts each, not the twin lascannon that was reduced in CA18

**Comment by budd86** [comment]
Hmm that will suck if it’s the case considering its litrally thensame weapon.

**Comment by budd86** [comment]
On top of that twin lass cannons was 25x2, hope this is just a oversight on gw
