### ISSUE TITLE
Imperium - Astra Militarum: Crusader cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4591]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 1.22.28

**Platform:** Android

**Dropbox:** No

**Description:** Stormshield are 0 points therefore crusaders should be 13 points each with their equipment

**Comment by Mad-Spy** [comment]
If you want to use the costs from the Beta Adeptus Sororitas Codex, you will need to select the "Use Beta Rules" option from the No Force Org Slot section.

The new costs are not applicable unless you are using those rules.
