### ISSUE TITLE
Astra Militarum - Ministorum Priest Zealot display issue

### ISSUE THREAD

**Issue by Cultiststeve** [BSData/wh40k#4595]
**File/Catalogue:** Astra Militarum v199

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

The Ministorum Priest's zealot ability shows up under "selection rules", while other abilities in the catalogue show up as an "ability".

**Comment by DrTobogganMD** [comment]
The only place this is true was on Taddeus, the rest are via a shared rule.

**Comment by Cultiststeve** [comment]
@DrTobogganMD Hi, I think this got mislabeled. My report is about the Ministorum Priest within Imperium - Astra Militarum (Imperial Guard) v200.
![](https://i.imgur.com/fWEaqMx.png)
Zealot links to a shared rule, where other abilities (like War Hymns) are a "Abilities" profile.

**Comment by DrTobogganMD** [comment]
Nope, not mislabled. I just can't read. Funnily enough, there was an instance of it in Ministorum as well hahaha. Fixed and released. You should see it on the next appspot update.
