### ISSUE TITLE
Chaos - Chaos Space Marines: Abaddon missing Warmaster ability

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4598]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** Hi there everything is accurate as far as I can tell except abbadon is missing his war master ability

**Comment by Mad-Spy** [comment]
That ability only applies if he is the Warlord of your army, so it only appears if you select him as your Warlord.
