### ISSUE TITLE
Tyranids: Sporocyst ability incorrect text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4599]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** Please, my sporocyst, he is very sick. I've submitted this bug a few times over the last few months and it's been combined with other bug reports, but then declared done when the other bugs are fixed instead. As of the latest big FAQ the sporocyst had its bombardment organism ability changed to something completely different. For your convenience I've copied the exact new ability text below:

"When you set up this unit during deployment, it can be set up anywhere on the battlefield that is more than 9" from the enemy deployment zone and any enemy models."

Please, help the most playable fortification in the game reclaim its rightful place on the throne

**Comment by GenWilhelm** [comment]
You're quoting a beta rule:

![beta_1](https://user-images.githubusercontent.com/22036809/52746027-8017de00-2fd8-11e9-93fd-c2478778a64c.png)


So it shows up when you have selected that you're using beta rules:

![beta_2](https://user-images.githubusercontent.com/22036809/52746030-80b07480-2fd8-11e9-9f52-7019c899d739.png)
