### ISSUE TITLE
Imperium - Dark Angels: Scout camo cloaks

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4600]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** It should be possible to equip individual scouts with camo cloaks rather than the entire squad.

**Comment by Mad-Spy** [comment]
If you don't equip the whole squad, they don't get the cover bonus, so there's reason to make it a per model choice.

![image](https://user-images.githubusercontent.com/29306451/52745312-9cb31680-2fd6-11e9-9790-6267fe1cc2dc.png)

**Comment by Ginjitzu** [comment]
It may be an unusual case, but what if all of the other squad members are
removed from battle, leaving only the camo cloak equipped model remaining?

**Comment by Mad-Spy** [comment]
Good point, or if you Combat Squad them and only want one of those squads to have cloaks.
