### ISSUE TITLE
Imperium - Dark Angels: Relic Validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4601]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** When using the stratagem "Relics of the Rock," two characters must not be able to take the same relic.

**Comment by Mad-Spy** [comment]
Also, selecting Relics of the Rock allows one more Relic than it should; I can select 2 for -1CP or 3 for -3CP. 
I can also give all of them to the same character which shouldn't be allowed.

**Comment by Thairne** [comment]
One free base relic + 1 for -1 CP = 2 total relics
One free base relic + 2 for -3 CP = 3 total relics
heck,
One free base relic + 1 for -1 CP  +2 relics for - 3 CP= 4 total relics!

That's how I understood this to work... for like... ever?

**Comment by alphalas** [comment]
But if your warlord is not a dark angel, you don’t get the initial one free.  So it’s a one free if your warlord is dark angels, one CP for one extra, meaning one if no DA warlord, 2 if DA warlord, etc.

**Comment by Thairne** [comment]
YES:
