### ISSUE TITLE
Death Guard Index Daemon Prince

### ISSUE THREAD

**Issue by iamthesolo** [BSData/wh40k#4604]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Sorry how come there is still a profile for the Index Daemon Prince for Death Guard?
The designers commentary flowchart is pretty clear there should only be one datasheet for the Daemon Prince. I've heard arguments about name and different model but both official model's are represented by the codex profile and the flowchart is pretty clear in that there should only be one datasheet to use.

**Comment by Mad-Spy** [comment]
That's your opinion, and as you're aware from the arguments you mention, there is contention over this. So, rather than constantly go back and forth and without clear guidance from GW, it's easier to just include both and you can ignore the one you don't agree with.
