### ISSUE TITLE
Imperium - Space Wolves: Icarus Stormcannon cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4605]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Hello there,

First, i wanted to thank you for the amazing job you are doing. 
There is a mistake in the point value of the "stalker" since the price of the icarus stormcanon dropped in last chapter approved. It s not 109 but 95 points

**Comment by williamcaw** [comment]
other catz do have the change to 95 points as per ca2018

**Comment by budd86** [comment]
Any of the space wolves errors going to be fixed?
