### ISSUE TITLE
Imperium - FW Adeptus Astartes: Add Chapter selector

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4607]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** can we get a chapter selection for the file so that we can remove chapters when making a  section

**Comment by williamcaw** [comment]
this is just a hide option so that when selecting red scoripons it hides astral claws and vice versa
