### ISSUE TITLE
Support for understrength units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4611]
**File:** Tyranids.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** The bug is this: When i choose Auxiliary Support Detachment to include an incomplete unit, the number of models in unit remains the same minimum with the same minimum cost.
For example: I need to put in my roster only one Venomthrope, but the minimum models in unit must be 3. With the last wh40k faqs, i can put only one model and pay the cost for only one model, not like before who i payed the full unit minimum cost, also if i included only one model.
I hope you can resolve this bugs. Thanks!

**Comment by DrTobogganMD** [comment]
We have yet to implement this asinine FAQ ruling as doing so would require a modifier on every single multiple model entry in every single catalog.

**Comment by WindstormSCR** [comment]
you can end-run this with most units simply by removing the sub-element via context menu, then re-adding only the number of models you have.

**Comment by DrTobogganMD** [comment]
I've added a text rule to lists containing an Aux detachment explaining how to manually remove models and that we cannot mitigate the error that follows.  That is as much as we can really feasibly do for this request.
