### ISSUE TITLE
Necron gauss pylon wrong cost

### ISSUE THREAD

**Issue by shassino** [BSData/wh40k#4612]
Teleportation matrix is a mandatory upgrade, in the catalogue its price is set but the total cost is still 475 instead of 485.

**Comment by DrTobogganMD** [comment]
Huh, interesting.

The datasheet doesn't say it is a bit of equipped wargear, yet it has the ability.  But the points table has it as wargear.

Good catch. I'll revise tonight after work.

**Comment by DrTobogganMD** [comment]
Fixed, It'll be in the next release.
