### ISSUE TITLE
Imperium - Death Korps of Krieg - (Feature Request) Engineer Breaching Drill

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#4616]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes

**Description:** This is more of a feature request (sorry I don't know how to tag it properly), but as many DKoK players know, Forge World goofed and did not allow for Engineers to deploy alongside their Hades Breaching Drill.

Scores of us have emailed them regarding this, and their solution thus far has been to respond by saying "Just replace the veterans in the Hades Breaching Team with Engineers and pay the appropriate points cost." While it's possible to do this in Battlescribe, it's a bit squirrely and causes a bunch of validation errors (drills without veterans, too many Elites selections, etc...) and makes it difficult to track what actually needs to be addressed in the roster.

I'd like to request an option within the Engineer profile marked "Open Play Only - Hades Breaching Drill" or something which adds 65 points (the cost of the Hades drill) to the unit, thereby earmarking those points so that we can still use Battlescribe to build rosters for casual games, and play this unit as intended without the massive headache it currently causes.

I understand if, because this has been passed out to players via emails and is not an official rule, you guys decide against its inclusion, but I don't see the harm in requesting it as a quality of life improvement for casual players, as long as it is CLEARLY labeled "NOT FOR COMPETITIVE PLAY" or "NARRATIVE ONLY" in the roster. In the meantime, my fingers will be crossed for the next FAQ...

**Comment by DrTobogganMD** [comment]
Sorry for the delay in response. Our DKOK maintainer has been a bit busy outside of BS - I hesitate to answer on his behalf, but as you said we normally do not implement changes based on emails directly to users. Published rules changes are our preferred form of source.  I'll leave this up to @alphalas to decide on but I wanted to let you know we did not forget about this request.

**Comment by DrTobogganMD** [comment]
I spoke with the DKOK Maintainer, we're going to mark this as closed for the time being. Once FW publishes a FAQ stating the change, we will be able to implement it. Until then, to keep consistent in our practices, we won't be changing things until official publication is put forth.

**Comment by GenericCola** [comment]
Sad panda. Was worth a shot. Hopefully they'll actually address the litany of issues that have been present in our rules since publication rather than continuing to ignore them, but I wont hold my breath. Thanks, guys.
