### ISSUE TITLE
Imperium - Officio Assassinorum: Please implement new rules before they're released

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4617]
**File:** Imperium - Officio Assassinorum.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** https://imgur.com/a/kgH6ycq#wsD7kdH this has been leeked the modified detachment now gives one cp

**Comment by Thairne** [comment]
Are you done yet?
Are you done yet?
Are you done yet?
Are you done yet?

**Comment by tekton** [comment]
Why isn't this done and live yet?

**Comment by WindstormSCR** [comment]
I WILL THROW YOU ALL INTO THE SUN

**Comment by DrTobogganMD** [comment]
Hey. That's my territory.

**Comment by Thairne** [comment]
I see you still aren't done yet.
