### ISSUE TITLE
Grey Knights: Typo in Relic name

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#4619]
**File/Catalogue:** Imperium - Grey Knights

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The Relic "Desroyer of Crys'yllx" should read as "Destroyer of Crys'yllx" (missing letter T in first word).

**Comment by DrTobogganMD** [comment]
What, you don't know of the tale of the great Crys'yllx Desroyer?!

**Comment by tekton** [comment]
Sure, pick on the lysdexic kid!

And thank you :-D how did you know I was working on these things tomorrow?!
