### ISSUE TITLE
Imperium - Astra Militarum - Units Missing??

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#462]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Can you please add the enginseer, priest, primaris psyker, astropath, and wyrdvane back in since they also have the astra militarum keyword?

**Comment by alphalas** [comment]
No. They are in their root factions according to the index. See #77 if you don't know how to make soup detachments.
