### ISSUE TITLE
Tech-Priest Manipulus Data Errors

### ISSUE THREAD

**Issue by JCRobertson** [BSData/wh40k#4620]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS

**Dropbox:** Yes

**Description:** The Manipulus point cost is correct, but the Magnarail lance should be 5 points instead of 0. In addition, the two Galvanic Field rules need to say 'friendly (FORGE WORLD) units" instead of just "friendly units"
![img_9114](https://user-images.githubusercontent.com/2532074/52916527-a8d8f580-32ae-11e9-8451-80daa1d97ccd.jpg)

**Comment by Mad-Spy** [comment]
The cost of the Manipulus itself _includes_ wargear, so no matter which weapon he takes, his cost is 90, even though GW provided points for the lance.

**Comment by JCRobertson** [comment]
Oh wow didn't notice that thanks, weird how they did that. I guess just the <FORGE WORLD> thing then
