### ISSUE TITLE
Imperium - Astra Militarum: Add more things that aren't released yet

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4621]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** https://spikeybits.com/wp-content/uploads/2019/02/Screenshot_133-1.jpg  Severina Raine hq 36p

**Comment by DrTobogganMD** [comment]
Guess what doesn't actually release until next week!

**Comment by alphalas** [comment]
https://whc-cdn.games-workshop.com/wp-content/uploads/2019/02/40K_AM_Severina_Raine_Datasheet_ENG.pdf

He’s actually not wrong; just might leave it a week for linking spikeybits instead of the actual thing on WHC

**Comment by DrTobogganMD** [comment]
True, You could always use the old model with the new sheet.  The new sculpt isn't out until next week with that boxed set.

**Comment by derekburgess** [comment]
Waiting patiently for this data :)
