### ISSUE TITLE
Imperium - Space Marines Primaris Captain Wargear Options Missing

### ISSUE THREAD

**Issue by jajames87** [BSData/wh40k#4622]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** iOS & Mac

**Dropbox:** Yes

**Description:** Primaris Captain should have: Page 141 – Primaris Captain, Wargear Options Change the second bullet point to read: ‘This model may take a power sword, or replace its master-crafted auto bolt rifle and bolt pistol with a power fist and a plasma pistol.’ As per the Space Marine Codex Official Update 1.4 19/11/18. At 78pts + 5pts + 9pts = 92pts (CA18)

**Comment by Mad-Spy** [comment]
You just need to pick the "Primaris Captain w/Power Fist instead?

![image](https://user-images.githubusercontent.com/29306451/52919034-e01ec500-32f5-11e9-962c-3b012277baf5.png)
