### ISSUE TITLE
Imperium - Grey Knights: Terminator with Psycannon cost

### ISSUE THREAD

**Issue by creature124** [BSData/wh40k#4623]
**File/Catalogue:** Imperium - Grey Knights.cat

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** When adding a Terminator (Psycannon) to a Terminator Squad, the model comes out at 91 points. The correct costing is showing on the header line for the model (50pts). I believe the old cost (41) is being added to the new cost (50), resulting in 91pts for the model.

This was observed in a Battalion detachment, but is not present in an Unbound Army detachment.

**Comment by Mad-Spy** [comment]
Are you remembering to remove a non-heavy weapon Terminator from your squad, because you've **added** the Psycannon?

**Comment by creature124** [comment]
Yes.
[Screenshot](https://www.dropbox.com/s/66nzrnvh5qarde4/Screenshot_20190218-100411.jpg?dl=0)

**Comment by creature124** [comment]
Aha. I spotted the issue, seems like to bundled two terminators in there? I delete the model and re-added it, and the issue went away. All good now, not a data issue.

**Comment by alphalas** [comment]
Yeah that’s a strange one.

**Comment by tekton** [comment]
If you try it with editing an old list after update it does that a lot. Additionally on new lists on Android (and only android) I've seen it a few times- even one guy at LVO we had to remove/add an HQ a few times before it calculated right.

Thanks for the updates!
