### ISSUE TITLE
Deathwing Tartaros SS+TH option?

### ISSUE THREAD

**Issue by paxmiles** [BSData/wh40k#4628]
Deathwing Tartaros Terminators are given the option for Storm Shield and Thunderhammer, but I can't figure out where the rules support this.

Not sure if this is a problem with the 40k data, might just be me being unable to figure out where the option comes from. Not an option in the codex. Dark Angels don't have access to Tartaros Terminators at all in the Index. 

Any clue where the rules are for this?

**Comment by WindstormSCR** [comment]
The index gave them the option, likely in error, and the current designer commentary keeps it as a legal option.

**Comment by paxmiles** [comment]
Dark Angels can't select the index version of the Tartaros terminators. It's not on the list of units they have access to. So it doesn't matter if it's a legal index option, they lack access to the index version of the Tartaros Terminators.
