### ISSUE TITLE
Deathwing Tartaros Terminators Shouldn't have TH+SS access

### ISSUE THREAD

**Issue by paxmiles** [BSData/wh40k#4629]
Dark Angels can't select the index version of the Tartaros terminators. It's not on the list of units they have access to (in the index). Also the DA codex entry is not the same as the Index Entry. They are "Deathwing Tartaros Terminators" not "Tartaros Terminators." Even with access to the index, they are two entirely separate unit entries.

Designer's Commentary regarding choice of index version vs codex version does not apply here because they are different unit entries.

Unless this is FAQed somewhere else?

_Originally posted by @paxmiles in https://github.com/BSData/wh40k/issues/4628#issuecomment-464943627_

**Comment by DrTobogganMD** [comment]
DA can indeed select Index Tartaros. Why wouldn't they be able to?  Tartaros Terminators have <Chapter> Which is replaced with Dark Angels in a Dark Angels detachment.  You're right that they are separate though. 

DA Cat should have Deathwing Terminators and Tartaros Terminators, not "Deathwing Tartaros Terminators"

**Comment by DrTobogganMD** [comment]
Ok, more time reading and less time spitting word vomit.

Index Tartaros were replaced in the codex with "Deathwing Tartaros" ... They are exactly the same with a few DA rules added.  You are correct they shouldn't be able to have SS/TH because index did not.

**Comment by paxmiles** [comment]
In the index, under the "Dark Angels" section, there's a list of units from the main list that can be fielded in a DA army using the index. Tartaros Terminators are not on the list. 

In the DA codex, we gained a unit entry called "Deathwing Tartaros Terminators"

It doesn't replace the index version because there isn't an index version for them to replace.

**Comment by Thairne** [comment]
I should start remembering the #closes....
