### ISSUE TITLE
Tyranids - Genestealer Cults: Hybrid Hand flamer cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4630]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** Yes

**Description:** Acolyte Hybrids hand flamers cost 8pts. They should only be 1pt now.

**Comment by GenWilhelm** [comment]
They're all 1pt as far as I can see.

![hand flamer](https://user-images.githubusercontent.com/22036809/53171626-36805200-35db-11e9-952d-37dbb6ff86ce.png)
