### ISSUE TITLE
Imperium - Space Marines: Twin Autocannon cost confusion

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#4633]
**File/Catalogue:** Imperium - Space Marines v83

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:**
The Dreadnought twin autocannon weapon is only present in the Index, where it costs 33 points.  It's also used on some of the weapon options in the FW Adeptus Astartes catalog.  In Chapter Approved 2018, under the Forge World point changes, Twin Autocannon was dropped to 30 points. It is currently inconsistent, with the main SM catalog having the weapon as 33, but all others listing it as 30.

A quick survey:

 * Space Marines - 33
 * FW Adeptus Astartes - 30
 * Grey Knights - 30
 * Blood Angels - 30
 * Dark Angels - 30
 * Space Wolves - 30

**Comment by WindstormSCR** [comment]
The values in GK, DA, BA, and SW need adjustment, the SM and FW values are correct.

This is because the FW catalog uses its own costing, while SM, etc get thiers from index 1, which has not changed.

**Comment by tekton** [comment]
./sigh, I'll change it back...again.

**Comment by tekton** [comment]
This needs a gst change technically
