### ISSUE TITLE
Warhammer 40,000 8th Edition: Add Ambull

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4640]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Unaligned .cat or update to all army’s for next week bun release for black stone upgrade box 1

**Comment by WindstormSCR** [comment]
guessing this is related to the ambull release?

**Comment by Mad-Spy** [comment]
Mine should be arriving on Monday, so I'll add it then.
