### ISSUE TITLE
Aeldari - Harlequins: Great Harlequin Should Cost CP

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4642]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Fusion Pistol cost for Player and Troupe Master, is listed as 7 pts. Codex says 9 pts and the only errata so far to that codex, is in regards to wording on flip belt.

Warlord traits are also weird. Selecting masque warlord trait should not be possible without the warlord already being that masque, but it is. But selecting it first, and then selecting a masque, now gives error that it can't have that trait, and I have to deselect it, upon which reselection of it is now possible. Seems there is duplicate versions of the same traits, one set which is selectable without actually being the right masque.

Great Harlequin selection is listed as no cost, but that selection comes from using a stratagem, which costs 2 CP. Enigmas of the Black Library is the same in that that's a stratagem that costs CP during force build, but is listed under "No Force Org Slot", with the cost.

- [ ] Great Harlequin selection cost

**Comment by Ether009** [comment]
7 Points comes from Chapter Approved. So that's actually correct. Only an issue with how GW sorts things for erratas.

**Comment by WindstormSCR** [comment]
The WLTs is mostly a show/hide issue, that comes from needing to support mixed-masque detachments and is a quirk of BS's function rather than the way the datafiles are structured.'

Great Harlequin trait needs CP cost added as the CP costs were a thing after that was originally implemented.
