### ISSUE TITLE
Space Marines Heavy Plasma Cannon cost incorrect

### ISSUE THREAD

**Issue by ManDrow** [BSData/wh40k#4643]
**File/Catalogue:** 
v 1.2.16

**BattleScribe version:** 
2.01.

**Platform:** 
Android

**Dropbox:**
No

**Description:**
According to Chapter Approved the price for the Heavy Plasma Cannon is 16 for all Chapters. It is still listed at the old price of 17.

**Comment by WindstormSCR** [comment]
reads as 16 for me on v83

**Comment by ManDrow** [comment]
Terribly sorry for my inaccurate report. It appears the price is only incorrect for Dark Angels now. When I first noticed the issue a while back it was all Chapters and I just noticed it still being wrong for DA when I made a list for them yesterday. I did not think to double check the other chapters thinking they would likely pull the same data as DA. 

Sorry for wasting your time, but the price for HPC is wrong for DA as of imperium - Dark Angels v82
