### ISSUE TITLE
Imperium - Space Marines: Primaris Captain wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4649]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The primaris captain.i have been equiping him  manually  With a power fist and bolt pistol as what it says on top of all data sheets. I’m  treating data sheets as a upgrade or a patch like a computer program . The unit is called primaris captain it’s not separate in any way as a model..” for the full rules for the unit see the codex or index book relevant to your army.” This sounds   Programmeding language .

**Comment by Mad-Spy** [comment]
Which datasheet are you referring to? There is no datasheet which allows a Primaris Captain to take a Power Fist and bolt pistol.

A standard "Primaris Captain" from Codex: Space Marines has the equipment below, and has no option to take a power fist.

![image](https://user-images.githubusercontent.com/29306451/53347958-1077ec00-3912-11e9-846a-f1ccaf4263e6.png)

The only Primaris Captain which can take a Powerfist is the Store Birthday version, which has a separate datasheet called "Primaris Captain with Power Fist". This model does not have an option for a bolt pistol.

![image](https://user-images.githubusercontent.com/29306451/53348171-7795a080-3912-11e9-8f3e-8b1086c37a97.png)

You are trying to put in a wargear combination which is not valid.

**Comment by williamcaw** [comment]
then the unit does not have any equipment at all the unit can take a power fist and a bolt pistol as per the top black line of the sheet
