### ISSUE TITLE
Imperium - Dark Angels: Unable to give all Scouts a camo cloak.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4653]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** If you give every member of a scout squad (Including the Sergeant) a camo cloak, the program gives you an error message that reads as follows: "Scout Squad has too many selections of Camo cloak (maximum X)", where X is the number of squad members (Including the sergeant) minus 1. The options list in the codex does says "Any model may take a camo cloak"

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/53439391-37155000-3a02-11e9-927e-81c18bd29487.png)
6x Camo cloak is one to many.

![grafik](https://user-images.githubusercontent.com/8590840/53439419-45636c00-3a02-11e9-8b58-60ca28733a8c.png)

5 is just right.

![grafik](https://user-images.githubusercontent.com/8590840/53439436-4c8a7a00-3a02-11e9-9d8d-331ff4ba2088.png)

and 4 are possible now, despite it being a waste of points.

**Comment by Mad-Spy** [comment]
@Thairne, it's having a Heavy Weapon Scout that causes the problem. If you include one, you can't give him a cloak without an error.
