### ISSUE TITLE
Imperium - Space Marines: Primaris Captain issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4658]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Thanks to a person on Facebook asking the same question as myself. That  the Primaris captain with Powerfist  the same as the regular Primaris captain in regards to equipment and not a separate model or unit. Response by warhammer 40,000 Indeed - refer to the Codex for all rules except his loadout :)

**Comment by Mad-Spy** [comment]
I managed to find the post you refer to, but it doesn't make any real difference to the implementation. Adding a single wargear option of "Power fist and plasma pistol" to the standard Primaris Captain doesn't really solve your issue, in that it's still a single option and you appear to want it to be separate upgrades so you can take a Power fist without also paying for a plasma pistol. Please correct me if this is not the case.

I've updated the post to ask the actual question I believe you want answered which is whether power fist and/or plasma pistol are individual upgrades or whether always they need to be taken together.

**Comment by DrTobogganMD** [comment]
I'm still confused as to what you are actually wanting to do OP. 

Are you requesting it be merged into the normal Primaris captain for ease of selection? Are you trying to take one of those weapons separately? What is your end goal of a list entry here?

**Comment by williamcaw** [comment]
#4652

**Comment by WindstormSCR** [comment]
Until an actual rules release and not a facebook comment that could be an uninformed opinion from the community team, the datasheets will remain separate.
