### ISSUE TITLE
Imperium - Blood Angels: Intercessor Sgt should be able to *not* take a rifle.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4659]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi there

In regards to the options for Intercessor Sergeant for all Marine forces, there is a missing option. In CA2018 it does state that ‘The Intercessor Sergeant may either replace their bolt rifle with a chainsword, power sword or power fist, or take a chainsword, power sword or power fist in addition to their other options’.
So I’m reading that as a Sergeant can have a pistol, bolt rifle (any variant) and melee weapon as well.

Hope this helps 

Chris Bowes

**Comment by Mad-Spy** [comment]
Yes, you're correct and that's how the implementation currently works in Space Marines, Dark Angels and Space Wolves. By default, the Intercessor Sgt has its rifle, and then you can select a melee weapon on top. You can then select the "melee weapon replaces rifle" option to deduct the cost of the rifle from the squad if you want.

![image](https://user-images.githubusercontent.com/29306451/53488896-7e91ef80-3a87-11e9-909b-d0b025c8e71d.png)

It does appear to be incorrect in Blood Angels.

**Comment by williamcaw** [comment]
you can read it both ways that he can take 2 weapons as well; And is crude language to other people that do not understand English.

**Comment by williamcaw** [comment]
#4516 , #4511

**Comment by DrTobogganMD** [comment]
@williamcaw Please stop tagging issues that have nothing to do with this one.

**Comment by williamcaw** [comment]
tread carefully sir or madam. i must remind you that you are on github.
