### ISSUE TITLE
Unaligned: Create new catalog file to contain unaligned units

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k#4668]
Same reasoning as not including Daemons in Heretic Astartes detachments

**Comment by williamcaw** [comment]
this was initially requested by the anon . there is other conflicts as well in with the Ambull. "Buildings". they may have to be moved and separated cat.

**Comment by williamcaw** [comment]
#

> this was initially requested by the anon . there is other conflicts as well in with the Ambull. "Buildings". they may have to be removed to the separated cat.

on topic of the data breach

**Comment by alphalas** [comment]
@williamcaw while your statement is technically correct, it genuinely has little to do with why we’re making the changes now.

**Comment by fuckingenglish** [comment]
buildings are part of the unlined faction witch the Ambull is.

**Comment by DrTobogganMD** [comment]
@fuckingenglish We don't need to move buildings, they only show up in a fortification detachment and can stay linked as is in the GST

**Comment by WindstormSCR** [comment]
Also, fortifications are unique in that in no cases do they cause relevant breaks in faction keywords, unlike ambulls, borewyrms, and spindle drones
