### ISSUE TITLE
Is anyone updating to Chapter Approve 2018?

### ISSUE THREAD

**Issue by mykyl69** [BSData/wh40k#4671]
**File/Catalogue:** The 3 points changes to Imperial Knight (Porphyrion, Lancer and Magera)

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by DrTobogganMD** [comment]
How long has it been since you updated your data? These changes have been in since CA2018 dropped.
