### ISSUE TITLE
Space Marines: Do the thing, phobos style

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4674]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** https://puu.sh/CTWVv/41585fd834.jpg add more things that are not released yet. until 16 Days from now.

**Comment by DrTobogganMD** [comment]
I love you.

**Comment by Thairne** [comment]
I have failed to not notice....

**Comment by WindstormSCR** [comment]
It'll be on a branch soon, and merged whenever shadowspear actually releases

**Comment by Thairne** [comment]
You're aware we're just joking, emulating anons that want shit done 2 seconds after it is announced/leaked?
Either that or you're metatrolling me... Hm. Well played, good sir.

**Comment by DrTobogganMD** [comment]
I have failed to not notice the whoosh over your head

**Comment by Thairne** [comment]
Mine? Or his?
Does this make it a double-woosh?
Woosh-Woosh.

**Comment by alphalas** [comment]
is live on master for BA

**Comment by Thairne** [comment]
I guess we are done here...
