### ISSUE TITLE
FW Heretic Astartes - Points Update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4675]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** No

**Description:** Chaos - FW Heretic Astartes List file:
1. Ferrum Infernus Dreadnought no longer exists in the forces of Chaos Imperial Armour book. 
2. The Hellforged Contemptor Dreadnought has wrong points values.
     Points for base dreadnought without upgrades is currently 88 points , should be 116. 
     Points for deathclaw and chainclaw should be 40 and 45 points respectively, currently are different. 
     Points for the other heavy ranged weapons also appear to be incorrect.

**Comment by DrTobogganMD** [comment]
1) If you look closely - it uses the same things as the helbrute, as per the FAQ.
2) Check CA2018
