### ISSUE TITLE
Aeldari Craftworlds v64 - Field Commander not granting extra Warlord trait allowance in validity checking

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k#4682]
**File/Catalogue:** 
Aeldari - Craftworlds v64

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** 
Wraith Host HQ with the "Field Commander" option and "Revered by the Dead Warlord" trait selected, alongside a standard Warlord+trait also in list results in list counting as invalid due to too many Warlord traits.

Steps to reproduce:
1, New Roster, Craftworlds Battalion
2. Select Craftworld
3. Add Specialist Detachment, Wraith Host
4. Add an HQ, mark as Warlord, select Warlord trait
5. Add 2nd HQ, mark as Field Commander, selet Revered By The Dead

Result: 1 too many selections from Warlord Trait (maximum 1)

**Comment by DrTobogganMD** [comment]
Mmm, I love me reproduction steps. Thanks!

**Comment by FarseerVeraenthis** [comment]
Yup, that's confirmed, I'll see what I can do :smile:
