### ISSUE TITLE
Imperium - Space Marines: Rename Inceptor weapon options to make it clearer that models are equipped with a pair.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4685]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Inceptor Squad  showing 1 weapon being equipped when there is 2

**Comment by fuckingenglish** [comment]
default equipment is shown as one. instead of being equipped with two. this also applies to the Plasma Exterminator.
