### ISSUE TITLE
There is no option for chosing crusaders in Inqusition army 

### ISSUE THREAD

**Issue by Cray97w** [BSData/wh40k#4692]
**File/Catalogue:** warhammer 40,000 v1.2.20

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** when i chose Inqusition as army there is no option to select crusaders or Arco-flagellants so is something wrong or i just can't find if this is stupid exuse me for that but i like my inqusition army :)

**Comment by Mad-Spy** [comment]
You'll need to create a multi-faction detachment, https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions and include the Adeptus Sororitas if you want to do this, as both of those units are Adeptus Ministorum, not Inquisition.
