### ISSUE TITLE
Imperium - Space Marines: Scout Sergeant Weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4700]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** I think I found a problem with the loadout options of the Scout Squad. According to the codex you can only exchange your Boltgun for a shotgun, sniper rifle or knife. Battlescribe lets me choose the shotgun AND the Boltgun by unchecking the Box for the pistol, though. So according to Battlescribe a Scout can be equipped with a Boltgun and a Shotgun by leaving his pistol at home, I'm pretty sure this isn't intented.

**Comment by williamcaw** [comment]
This is a holdover from index

**Comment by Mad-Spy** [comment]
@williamcaw, no it's not. The weapon options haven't changed for Scouts between the Index and the Codex.

**Comment by Mad-Spy** [comment]
There are several ways to interpret this and GW are inconsistent on it. Please see #3783. Technically, a Scout Sgt can swap his default boltgun for a sniper rifle, and then swap his pistol for a boltgun from the Sgt Equipment list, so the implementation is fine.
