### ISSUE TITLE
Codex: Deathwatch - Psychic Enhancements for "standard" Librarians as Custom Heroes Missing

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#4702]
File Version 56.
The Psychic Enhancements table is only visible for the Primaris Librarian, not the "Standard" Librarians (of all flavours).
Please update the file to include this table for all Librarians.

**Comment by Mad-Spy** [comment]
Model doesn't have the PSYKER keyword, which would explain it.
