### ISSUE TITLE
Grey Knights - Finally Finish The Damn Pre-Game Selection Toggle Already

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4712]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.23

**Platform:** Android

**Dropbox:** Yes

**Description:** The application reads there is a roster error as every Grey Knights character requires a warlord trait.

**Comment by williamcaw** [comment]
Cannot  re-create error. You may need to update your data .

**Comment by tekton** [comment]
It's legit, it's due to the newer battlescribe- a fix is coming this weekend
