### ISSUE TITLE
Questor Traitoris - Character required where it shouldn't be

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4714]
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.01.23

**Platform:** Android

**Dropbox:** No

**Description:** Chaos - renegade knights super-heavy auxiliary detachment has an error requiring a selected character option, as if it is falling under the renegade knight lance rules, which the auxiliary doesnt benefit from.

**Comment by DrTobogganMD** [comment]
New BS no longer ignores constraints when hidden.  Character Min 1 needs to be set to 0 if force no instance of Renegade Knights SHD.

**Comment by Mad-Spy** [comment]
This is a Battlescribe bug. It should be fixed in 2.01.17.
