### ISSUE TITLE
Tyranids - Genestealer Cult special detachment bug

### ISSUE THREAD

**Issue by BertjanWanders** [BSData/wh40k#4720]
**File/Catalogue:** Tyranids - Genestealer Cult

**BattleScribe version:** 2.01.16

**Platform:** Windows

**Dropbox:** No

**Description:** when adding one of the 2 special detachments to a detachment, ticking the Stratagem: Field Commander box for the relevant character (Iconward for Broodsurge or Abominant for Throng) throws up a validation error for BOTH special detachment warlord traits needing to be picked, rather then only the relevant selected detachment.

**Comment by GenWilhelm** [comment]
It appears this was caused by a bug in BattleScribe v2.01.16 and is now fixed in v2.01.17 (as of an hour ago).

https://github.com/BattleScribe/Release/issues/36
