### ISSUE TITLE
Chaos - Chaos Space Marines: No statline for Greater Possessed

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4724]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The new Greater Possessed units datasheet don't show the stat line for the units, only for their weapon.

**Comment by williamcaw** [comment]
This is still being reviewed
