### ISSUE TITLE
Imperium - Adeptus Mechanicus - No options to select warlord traits

### ISSUE THREAD

**Issue by felldian** [BSData/wh40k#4726]
**File/Catalogue:** Imperium - Adeptus Mechanicus v52

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** No

**Description:** No warlord traits able to be picked regardless of character chosen as warlord.

**Comment by Thairne** [comment]
Look under the warlord entry, it's down there.

![grafik](https://user-images.githubusercontent.com/8590840/54491756-2cdbc880-48c1-11e9-9dc4-984490861eea.png)

**Comment by felldian** [comment]
You can assign warlord, you cannot assign a warlord trait, you have misread the big report.

You cannot pick any specific warlord trait on battlescribe.

**Comment by Thairne** [comment]
Tap on Warlord.
Tap on Warlord trait.

Behold and despair before the beauty which you will see unfold in front of your very own eyes!
