### ISSUE TITLE
Imperium - Adeptus Sororitas: Geminae are missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4728]
**File:** Imperium - Adeptus Sororitas.cat

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** ~~The space wolves data file needs to have the Units from the Shadowspear box set added to it.~~ 

The Adeptus Sororitas data file is missing the Sisters Gemenia from the elites choices.

**Comment by Mad-Spy** [comment]
Geminae do not take up a slot when you include Celestine, so they appear in the "No Force Org Slot" group.
