### ISSUE TITLE
Chaos - Chaos Space Marines: Venomcrawler missing Attack stats

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4734]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** Hey there, 
just wanted to let you know that the Venomcrawler is lacking the number of attacks it has in its decreasing profile. 
Thank you for updating everything so fast though :)
Best wishes

**Comment by Mad-Spy** [comment]
The leaked data didn't have the stat in, so I couldn't add it. As soon as we find out what it is, it'll be added.
