### ISSUE TITLE
Orks Errata Index War buggies points reduction in Chapter approved

### ISSUE THREAD

**Issue by Spankadelic** [BSData/wh40k#4740]
File: Orks.catz

BattleScribe version: 2.01.16

Platform: Windows

Dropbox: No

Description: Errata Index Skorchas, Warbuggies and Wartrakks were given a points reduction in the last chapter approved
Page 131 – Updated Points Values: December 2018
Add the following: 
Skorchas 37pts 
Warbuggies 33pts
Wartrakks 37pts

**Comment by Spankadelic** [comment]
You brain boyz are awesome. Your doing Gork (or possibly Morks) work!

**Comment by Mad-Spy** [comment]
All of these points are correct in the current version of the files (v41). Are you forgetting that they are the points _excluding_ wargear?

**Comment by Spankadelic** [comment]
My bad! totally didn't notice the wargear (derp). I'm a simple slugga boy - not too good at finkin'.
