### ISSUE TITLE
Imperium - Space Marines: Infiltrator PL cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4747]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The infiltrators under the space Marines troop choice have the power level display incorrectly when using a smaller size squad. A squad of 4 infiltrators and a infiltator sergeant should be 5 power level not 11

**Comment by Mad-Spy** [comment]
This is not the case in the released version of the files (v86), see the screenshot below.

![image](https://user-images.githubusercontent.com/29306451/54533765-dc2ca400-4982-11e9-8fc2-5457d315c4d2.png)
