### ISSUE TITLE
Imperium - Space Marines: Phobos and Tome of Malcador

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#4749]
**File/Catalogue:** Space Marines v87

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** A Librarian in Phobos Armour with the Tome of Malcador should select an additional power from Librarius, rather than Obscuration.

**Comment by Mad-Spy** [comment]
I suspect that this is not the case and this will be FAQed so that the additional power must be taken from a discipline which the psyker knows. However, current RAW is that he gets access to Librarius, so I'll reimplement it that way.
