### ISSUE TITLE
Grey Knights - Missing Techmarine Relic?

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k#4755]
**File/Catalogue:** Grey Knights v33

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Since Techmarine has index option of taking a Storm Bolter, shouldn't he be allowed to take the Fury of Deimos relic? Honestly I'm not sure how relic replacements work with index wargear...

**Comment by Mad-Spy** [comment]
Agreed, I can't see any reason why they wouldn't be allowed it.

**Comment by tekton** [comment]
I thought I fixed that...it got messed up when some other things got moved around post CA18; I swear that unit is going to be the death of something.

**Comment by tekton** [comment]
This is such an old issue, someone should really fix it! ...oh, right. Well I'm home finally ;)
