### ISSUE TITLE
Imperium - Grey Knights: Vortimer Redeemer cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4763]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Under Grey Knight entry for the Vortimer Pattern Land Raider Redeemer I believe the points haven’t been updated from chapter approved 2018. The base cost of the vehicle should now be 215. It is currently showing as 255 points.

**Comment by tekton** [comment]
Nope, I was wrong, it's the "help" I had to revert on points costs that's going to be the death of things...
