### ISSUE TITLE
Grey knight points values

### ISSUE THREAD

**Issue by kyuubi08** [BSData/wh40k#4764]
Several unit point values are incorrect. For several models it looks as if they are paying for storm bolter when that should be included in the point cost. 

Terminators should be 39 points per model base
Brother captain should be110
Gm should be 130
Venerable dreadnaughts should be 85per unit

**Comment by Mad-Spy** [comment]
All the listed model points in the Codex (and subsequent updates) are not including wargear. You must pay for any weapons the unit/model has, hence the displayed point values, all of which are correct to the latest updates in Chapter Approved 2018.

**Comment by kyuubi08** [comment]
Per grey knight war gear, they don't have a pt value for storm bolters

**Comment by Mad-Spy** [comment]
Yes they do. It's in their Codex as below. Chapter Approved only lists _updated_ costs, not all costs.

![image](https://user-images.githubusercontent.com/29306451/54754380-46d81c80-4bdb-11e9-9321-9ff001c038b6.png)
