### ISSUE TITLE
Necrons warlord trait 

### ISSUE THREAD

**Issue by kyuubi08** [BSData/wh40k#4765]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description: unable to select warlord trait for necrons. You can display all the traits, but cannot select for wl

**Comment by Mad-Spy** [comment]
You must click the "Warlord" selection after making an eligible model your Warlord in order to select Traits.

![image](https://user-images.githubusercontent.com/29306451/54712422-227d3100-4b44-11e9-977d-b7d37ab75e90.png)
