### ISSUE TITLE
T'au Empire: Keywords for Shas'o R'alai need to be updated to latest FAQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4766]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** Latest Imperial Armour Index Xenos FAQ has updated Keywords for HQ Commander Shas'o R'alai and his drones.
https://whc-cdn.games-workshop.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Imperial_Armour_Index_Xenos_ver_1.0.pdf

Change this datasheet’s keywords to read:
‘Keywords (Shas’o R’alai): Battlesuit, Commander, Character, Jet Pack, Fly, Shas’o R’alai

Keywords (Blacklight Marker Drone): Drone, Fly, Blacklight Marker Drone’

**Comment by amis92** [comment]
The "Profile" format was deprecated long time ago, if you were referring to that. For reference I've updated https://github.com/BSData/wh40k/wiki/Guidelines#15 to be more specific.

Otherwise, the file is correct right now.
