### ISSUE TITLE
Imperium - Blood Angels: Intercessor Sgt weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4767]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Concerning Intercessor Squads, the Intercessor Sergeant is missing a weapon. The sergeant should recieve the same bolt weapon as the rest of the squad by default, and he may either take a melee weapon, or have his melee weapon replace his rifle. When the melee weapon replaces rifle box is checked, the unit is correct, but when the same box is unchecked, he should have a rifle added to his list. The rifle does not get added when the box is unchecked.

**Comment by Mad-Spy** [comment]
No Intercessor has a "personal" weapon. Their weapons are chosen at the squad level. It would be more complicated for us and for users if we had to implement validation to make sure the Sgt always has the same weapon as his squad (as is required by the rules). You can see that the cost of his rifle is included in the squad cost if you choose the Auto Bolt Rifle (which costs 1pt). Checking the "Melee weapon replaces rifle" option deducts 1pt from the weapon total.
