### ISSUE TITLE
Imperium - Space Wolves: Primaris Battle Leader missing default wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4777]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Battlescribe mobile android v2.01.24.288
Warhammer 40k v92 - Space wolves v72
The space wolves primaries battle leaders hq should have a bolt pistol, frag and krak grenades in addition to the optional primary weapons choice, but only has the choose piece of wargear.

**Comment by williamcaw** [comment]
Yep no equipment showed
