### ISSUE TITLE
Imperium - Space Marines: Biker Veteran can't take storm shields?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4780]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 1.02.25

**Platform:** Android

**Dropbox:** No

**Description:** Page 26  – Company Veterans, Wargear Options Change the second bullet point to read: ‘•    Any model may replace their bolt pistol with a storm shield or an item from the  Melee  Weapons  or Pistols  lists.’         
Why can't the Company Veterans on Bike use storm shields if the FAQ says any model?

**Comment by acebaur** [comment]
They can take a storm shield, can you provide a screenshot of where it's not allowing you?

**Comment by JasonMWelch** [comment]
@acebaur I he is referring to the Sgt that can not.  As that is a weird wording issue in the index that prevents them from taking it, yet the normal members can.

**Comment by Mad-Spy** [comment]
"Company Veterans on Bikes" do not use the same datasheet as "Company Veterans", and as such, the Bike Sgt cannot take a Storm shield because it is not in the Sgt Equipment list.
