### ISSUE TITLE
Imperium - Adeptus Ministorum: Celestine's Beacon of Faith has incorrect text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4796]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.20

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Adepta Sororitas, Celestine HQ entry: if taken as a warlord, she is restricted to Beacon of Faith, as already described (Chapter Approved 2018 p.98 under Named Characters).  So my tweet that this was incorrect was wrong. 

  But the description for the Beacon of Faith warlord power is incorrect here.  It looks like the description is restating Saintly Blessings, which she has regardless.  Beacon of Faith description needs to match the power, per the Warlord Traits table on p.98 of Chapter Approved 2018.  “At the start of your turn, roll a D6 if this Warlord is on the battlefield; on a 4+ you gain 1 Faith Point.”

**Comment by Mad-Spy** [comment]
Celestine still has an entry for the Index version of "Beacon of Faith" which is overriding the Codex version (because they have the same name). The Index version needs to be removed.

**Comment by DrTobogganMD** [comment]
In case anon comes back: Just so you're aware - we have no visibility on your tweets about data correctness (Assuming you're tweeting to BSData's Twitter). You'll want to make issues here (as you've correctly done :D )
