### ISSUE TITLE
Codex Drukhari weapons should say they are Poisoned

### ISSUE THREAD

**Issue by lostgrail** [BSData/wh40k#4799]
**File/Catalogue:** Aeldari / Drukhari

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** Yes

**Description:** The following weapons should have “Poisoned Weapon (p87)” as their Abilities description, instead of text describing how Poisoned Weapon works:
 * Haemonculus Tools
 * Shardcarbine
 * Agonizer
 * Electrocorrosive Whip
 
Additionally, the following weapons should have “Poisoned Weapon (p87). Add 2 to wound rolls made for this weapon, unless it is targeting a *vehicle*.” (same as description for Necrotoxin Missile) as their Abilities description:
 * Venom Blade
 * Stinger Pistol

The Scissorhand weapon’s Abilities should read “Poisoned Weapon (p87). Each time the bearer fights, it can make 1 additional attack with this weapon.”

Finally, the relic The Parasite’s Kiss should have the following Abilities description: “Poisoned Weapon (p87). Add 2 to wound rolls made for this weapon, unless it is targeting a *Vehicle*. Each time this weapon kills an enemy model, the bearer regains 1 lost wound.”

**Comment by lostgrail** [comment]
Updated description to include electrocorrosive whip and scissorhand.

**Comment by WindstormSCR** [comment]
Thanks for the detailed report, sorry this took so long to get to!

**Comment by lostgrail** [comment]
Is it too late to say I missed one?

Splinter Pods should also be Poisoned Weapon (p87)

I can file a new bug, and it's less of an issue because I'm not aware of any rules interactions for Wyches
