### ISSUE TITLE
Imperium - Questor Imperialis: Hide weapons when Relics are selected

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4800]
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Plasma Decimator to be hidden when Cawl's Wrath  heirloom is selected?

**Comment by Mad-Spy** [comment]
This is not something we can do in the current version of Battlescribe. We hope it will be a feature in the future.
