### ISSUE TITLE
Imperium - Deathwatch: Terminator Libby should not have access to Storm shield

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4801]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch Librarian in Terminator Armor invalid wargear, Storm Shield:

Per Index Imperium 1, a DW Librarian in Terminator Armor is not permitted to take a Storm Shield (it is a bullet point in the "changes from normal datasheets" section).

In the Deathwatch 8th edition codex, Storm Shields are not explictly granted to a Librarian in Terminator Armor, and the Librarian in Terminator Armor may only swap a Force Weapon for one from a different type, or swap it's Stormbolter for a Terminator Combi-weapon, neither of which permit a Storm Shield.

However, Battlescribe Sneaky Wolves update still lists it as a valid Index wargear option for a Deathwatch Librarian.  This is likely a copy/paste issue that occurred by using the regular Space Marine Libby in Terminator Armor information.

**Comment by corrinavatan** [comment]
For clarity, why was this issue closed?  Has it been corrected for the next commit?
