### ISSUE TITLE
Imperium - Adeptus Astartes, Leviathan Dreadnought is missing his explosive rule 

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#4804]
**File/Catalogue:** Imperium - Adeptus Astartes

**BattleScribe version:** 2.01.21

**Platform:** Windows and IOS

**Dropbox:** /No

**Description:** Detailed issue description.
Relic Leviathan Dreadnought dosn’t have it’s explosive rule. 

Should be:

Atomantic Conflagration: If this model is reduced to 0 wounds, roll a D6 before removing it from the battlefield;
on a 5 or 6 it explodes and each unit within 9" suffers D3 mortal wounds.

**Comment by fuckingenglish** [comment]
Contemptor Mortis Dreadnought  is  missing explosion rules.  as of April first  release   item was updated and has explosion rules restored.
