### ISSUE TITLE
Imperium - Space Wolves: Terminator Wolf Lord Thunder hammer cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4805]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Greetings! just a small point issue I came across. The Wolf Lord in Terminator Armor still has equipping the Thunder Hammer points cost to be 21 points as opposed to the now 16 points across the rest of the army. I appreciate everything you do and thank you for maintaining this data!

**Comment by CrusherJoe** [comment]
Unfortunately thunder hammers for characters (which the Wolf Lord definitely is) are 21 points.
