### ISSUE TITLE
Questor Traitoris Super-heavy Detachment - No CP given

### ISSUE THREAD

**Issue by Charlesfox9999** [BSData/wh40k#4806]
**File/Catalogue:**  Detachment CP

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux Android

**Dropbox:** Yes/No

**Description:** Detailed issue description. When I select a Questor Traitoris Super-heavy Detachment, i have to choose a character which is correct. The detachment cp should be 3 cp is the detachment has at least one Titanic keyworded knight in the list and 6 cp is there is 3 Titanic keyworded knights in the list.  This used to happen before we started needing to choose detachment cp in every detachment, Currently it gives no cp at all if you choose this detachment.  If you choose a normal super heave detachment, it just gives  you 3, does not make you take a character, and will not give you more than 3 cp, like is was before the renegade knight codex come out in chapter approved.  Thank you

**Comment by Mad-Spy** [comment]
The Questor Traitoris Super-Heavy Detachment has been removed and using a standard Super-Heavy Detachment will calculate the CP correctly.

**Comment by Charlesfox9999** [comment]
I am using an android device,and just refreshed my data files, under chaos
renegade knights, when you choose the standard superheavy detachment, it
does not allow you to make one a character, and it only give out 3 cp, and
it should be 6 when you select 3 of the big knights

**Comment by Mad-Spy** [comment]
The change hasn't been released yet. It is in v15 of the files.

**Comment by Charlesfox9999** [comment]
Thanks
