### ISSUE TITLE
Vigilus Ablaze Specialized detachments correction

### ISSUE THREAD

**Issue by jtarbox** [BSData/wh40k#4807]
**File/Catalogue:** Chaos Space Marines v93 - Chaos-Vigilus-Ablaze branch (just pulled)

**BattleScribe version:** 2.01.17

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** The specialized detachments in the Warhammer Community legion reviews are not tied to the legions they were previewed with, except for the Black Legion "Bringers of Despair" detachment.  This one technically doesn't have requirement of a legion, but only effects Black Legion terminators so there is no point taking it without Black Legion.

**Comment by Mad-Spy** [comment]
You may be right, and once the book is available, I'll update everything appropriately.
