### ISSUE TITLE
Chaos - Chaos Space Marines: Obliterator cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4816]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.10.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Obliterators incorrect points value are 115 actually 60

**Comment by radionausea** [comment]
65 actually, and I guarantee that the FAQ/errata updates the new codex to something higher even if it's not the Shadowspear price.

**Comment by daveslayerv1** [comment]
I’d say that GW will probably give fleshmetal guns a price about 25-30pts

**Comment by Mad-Spy** [comment]
This will be updated when I release the new Codex/Vigilus Ablaze work, #4802.
