### ISSUE TITLE
Tyranids - Genestealer Cults: Specialist detachment relics

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#4826]
The implementation of Specialist Detachment Relics is incorrect. The requirement for taking a Specialist Detachment relic is only that you have the relevant Detachment, _not_ that there is a Warlord (either from that Detachment or not). See the below:

![image](https://user-images.githubusercontent.com/29306451/55316019-6c7be600-5465-11e9-908b-f6b269cd6695.png)

**Comment by GenWilhelm** [comment]
![image](https://user-images.githubusercontent.com/22036809/55351311-e2a83900-54b5-11e9-90ba-d33f7f2a0741.png)

I thought we took this to mean that you have to be able to take one in the first place, either by Warlord or Stratagem, and that they count towards the maximum number that you can take?

**Comment by Mad-Spy** [comment]
Apologies - misunderstood how this works. Closing.
