### ISSUE TITLE
Tyranids - Genestealer Cults: Relics should not be available by default

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#4827]
Relics should only be available for selection if there is a Warlord, or if CP are paid for the relevant Stratagem. Currently, you can select a Relic in GSC regardless of whether these conditions are met.

**Comment by GenWilhelm** [comment]
They should have a Max 0 constraint, which increments with Warlord/Stratagem, so you should be seeing an error if you select a relic incorrectly.

Or do you mean they're not hidden by default?

**Comment by Mad-Spy** [comment]
Yes, in (almost) every other catalogue, they are hidden by default.

**Comment by GenWilhelm** [comment]
I dislike having relics hidden by default, partly for the "discoverability", but mostly because I've seen people be very confused about how to get relics onto their characters (and a warning about having too many is easier to workaround than something being missing).
