### ISSUE TITLE
Imperium - Imperial Knights v33 (household trait rules do not show)

### ISSUE THREAD

**Issue by mynameisvu** [BSData/wh40k#4832]
Imperium - Imperial Knights v33

**BattleScribe version:** 2.01.24.288

**Platform:** Android

**Dropbox:** Yes/No

**Description:** When viewing rules under Household Choice, the rules for the different Household traits no longer show.  It only shows (as example):

House Raven
    Selections: Household Tradition: Relentless Advance

**Comment by DrTobogganMD** [comment]
This is a known issue that is caused by a BS bug. Jonski has fixed it, so whenever he releases the new version it'll be fixed.

**Comment by mynameisvu** [comment]
Thanks for the heads up.  You're doing the Emperah's work.  =)
