### ISSUE TITLE
Aeldari - Craftworlds: Keyword issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4833]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** Yes

**Description:** Support weapon platform should have "guardian" keyword
Wave Serpent should not have "falcon" keyword
Illic Nightspear should have  "ranger" keyword

**Comment by Mad-Spy** [comment]
Guardian Defenders are also missing the "Guardian" keyword, not just the platform
