### ISSUE TITLE
Chaos - Chaos Space Marines Weapon list and terminators.

### ISSUE THREAD

**Issue by Gallahorn** [BSData/wh40k#4834]
**File/Catalogue:** 
Chaos - Chaos Space Marines v83
**BattleScribe version:** 2.01.
2.01.17
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.

**Chaos Space Marines Wargear lists need following updates:**

Melee Weapons need Thunder Hammer

Terminator Melee Weapons need Chainaxes

Image with updated list for reference. 
CSM 2.0 page 119
https://gyazo.com/0fb665f98814dd32fbb775fc644fd5a3

**Terminators need point changes and standard gear update:**
Terminators are now 26 points without wargear. 

CSM 2.0 page 174
https://gyazo.com/25bbb3b9db48bff2c305eda781208e0d

Standard gear is now Chainaxe and combi-bolter.

CSM 2.0 page 137
https://gyazo.com/771739a82cdcddf991e70e7c0431a838

**Comment by Mad-Spy** [comment]
Fixed in v84

- I think this was just missing from Chaos Lords? Now added
- Terminator Melee list updated
- Terminator points adjusted
- Default wargear adjusted

**Comment by Gallahorn** [comment]
Looks like Exalted Champion are missing Thunder hammers too in v 83

**Comment by Mad-Spy** [comment]
The Champion uses the same list as the Lords, so they should both be sorted now.

**Comment by Gallahorn** [comment]
And I found an other issue. Abaddons weapons need update

Drach'nyen does flat 3 dmg now not d3
Talon of Horus have -4 AP now.

Want me to make new threads if i find more issues or keep puting them in here?

**Comment by Mad-Spy** [comment]
@Gallahorn, new issues are better so I remember where I am with fixes. I'll pick up Abaddon's weapons from here though.
