### ISSUE TITLE
Chaos - Chaos Space Marines: Havocs Unit Size

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4836]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 1.17.11

**Platform:** Windows

**Dropbox:** No

**Description:** On Chaos Space Marines V83 (which is still a manual import i think) Havocs can have an additional 5 Havocs. This was removed in the Rev2 codex and the max squad size is now 5.

(while im here. Couldn't submit proper bscribe version as 1.17.117 doesnt fit the x.yy.zz format? or did i fuck this up)

**Comment by GenWilhelm** [comment]
We don't need the last 3 numbers, so it should just be `v2.01.17`.

**Comment by Mad-Spy** [comment]
Fixed in v86. Also reworked weapon options and added proper Champion options.
