### ISSUE TITLE
Chaos -  Chaos Space Marines Havocs

### ISSUE THREAD

**Issue by Gallahorn** [BSData/wh40k#4841]
**File/Catalogue:** 
V88
**BattleScribe version:** 2.01.
2.01.17
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
no
**Description:** Detailed issue description.
Havocs cost 14 points in battlescribe with missilelaunchers. They should cost 34 points.

**Comment by Mad-Spy** [comment]
Forgot to make the launcher mandatory. Fixed in v89.
