### ISSUE TITLE
Chaos - Chaos Space Marines: Chaos Mark Prayers / Council of Traitors Stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4843]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** Yes

**Description:** Dark Apostle - if marked they get their corresponding prayer in addition to the one they chose from the Dark Gods. see under Mark of Chaos Prayers, Vigilus Ablaze page 169.
No option for taking the Council of Traitors stratagem (Vigilus Ablaze page 190), allows additional Sorcerer and Dark Apostle to take Warlord traits.
Other than that excellent work sir. Much apprecated.

**Comment by Mad-Spy** [comment]
Corrected in v89
