### ISSUE TITLE
Imperium - Space Wolves: Add Terrax Termite to Space Wolves

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4851]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** Can the Terrax Termite get added to the Space Wolf section please?  Here is the text straight from the Termite's data sheet concerning Space Wolves - "It can be from any other Chapter, including Blood Angels, Dark Angels, Space
Wolves and Deathwatch."   Thank you!

**Comment by Mad-Spy** [comment]
The Termite is a Forgeworld unit and, as such, is found in the FWAA catalogue. See here https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions for details of how to do this.
