### ISSUE TITLE
Chaos - Chaos Space Marines: Dark Disciples

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4853]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** An error appears when selecting a second Combi-bolter on a chaos rhino. 

Dark disciples aren't loading as an actual unit.

**Comment by Mad-Spy** [comment]
Combi-bolter issue is known already and will be fixed soon.

Dark Disciples move to the "No Force Org Slot" section if you include a Dark Apostle and the Elites entry should change name to tell you this?

**Comment by Mad-Spy** [comment]
Fixed in v90
