### ISSUE TITLE
Fallen: Unable to select Specialist Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4854]
**File:** Fallen.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** There's no option to add any type of chaos sorcerer or rhino. 

You can't select the fallen detachment in this file or as a CSM vanguard detachment.

**Comment by williamcaw** [comment]
This is a combination file.

**Comment by Mad-Spy** [comment]
The Fallen detachment should be available as long as you make your Fallen detachment a Vanguard. It's not valid otherwise.

**Comment by Mad-Spy** [comment]
Just checked this and it is working as intended. As long as your Fallen Detachment is a Vanguard, the option for the Fallen Angels Specialist Detachment will appear.
