### ISSUE TITLE
Imperium - Deathwatch: Infernum Halo Launcher description incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4856]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Corvus Blackstar upgrade Inferium Halo Launcher has incorrect description. File states "‘If an enemy unit that can FLY targets a supersonic model with an infernum halo-launcher in the Shooting phase, your opponent must subtract 1 from the subsequent hit rolls." Actual effect "Infernum Halo-launcher: You can re-roll save rolls of 1 for this model if it is equipped with an infernum halo-launcher and it has the Supersonic ability." P. 87 codex deathwatch

**Comment by Mad-Spy** [comment]
This ability was changed in the Codex: Deathwatch FAQ. It is correct as per that FAQ.
