### ISSUE TITLE
Khorne demon prince relics

### ISSUE THREAD

**Issue by Charlesfox9999** [BSData/wh40k#4862]
**File/Catalogue:**  Chaos Demons V54

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux Android

**Dropbox:** Yes/No

**Description:** Detailed issue description. In the latest update, the option to give a demon prince in a demon detachment that is a khorne demon prince with the demonic ax the relic skullreiver.  I have done so in the past, so when opening those older list, it gave an error code and when i looked at it, the option has been given away.  I am not sure what changed but i have researched the rules and there have been no changes to the chaos demon codex that warrants this change.

**Comment by Mad-Spy** [comment]
This option is definitely still available as long as the Daemon Prince has the Khorne Daemonic Allegiance and is equipped with a Daemonic Axe.

![image](https://user-images.githubusercontent.com/29306451/55491959-5705e800-562e-11e9-915f-735784631367.png)

![image](https://user-images.githubusercontent.com/29306451/55491981-5f5e2300-562e-11e9-9907-ab1ead66e0f3.png)

**Comment by Charlesfox9999** [comment]
Not on android.

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/55493396-c67cd700-5630-11e9-92f4-75d90b25940a.png)

It's working fine for me.

**Comment by Charlesfox9999** [comment]
Try it without making him the warlord. I took relic of chaos to give him
the relic without being the warlord.  When i clicked to make him the
warlord, it gave me the options in android, but doesn't give the options
when he is not the warlord.

**Comment by Mad-Spy** [comment]
Ah, I see! That was the missing information I needed. It's fixed in v90.

**Comment by Charlesfox9999** [comment]
Thank you sir.
