### ISSUE TITLE
Chaos Points and War Gear issues

### ISSUE THREAD

**Issue by WarmasterWyatt** [BSData/wh40k#4866]
So ive noticed that Obliterators are still listed in battlescribe as 65 points each, this is incorrect as in shadowspear they are listed at 115 a piece and come in a squad of 1-3. In the new codex, their entry says they come in a squad of 1-3. In the back of said codex it lists them still as a group of 3 for 65 each. This is clearly a copy paste error/ carryover from the last codex. Secondly ive noticed that per the codex a chaos biker champion can take a combi bolter as his ranged weapon. Selecting this however creates an error saying he has too many selections of Combi Bolter as his bike has one stock that cannot be removed.

**Comment by Mad-Spy** [comment]
As per my comment on Reddit, the current valid point value for Obliterators is 65pts, as per Codex CSM 2019. When it gets an Erratum, I'll fix it.

The Biker champion issue is fixed in v90, which will release soon.
