### ISSUE TITLE
Chaos - Daemons: Khorne Artefacts Without a Warlord

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#4869]
**File/Catalogue:** Chaos - Daemons v54

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** Yes

**Description:** Khorne Characters are unable to select any Hellforged Artefacts when only the Rewards of Chaos stratagem has been selected (i.e. the Warlord is not a Chaos Daemon).

**Comment by Mad-Spy** [comment]
Well, this has been broken for ages...
