### ISSUE TITLE
FW Index Heretic Astartes - Sonic dreadnought too avaliable

### ISSUE THREAD

**Issue by Stevrak** [BSData/wh40k#4873]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Sonic dreadnought was included in the Chaos FW FAQ and specifies you can take a modified helbrute from Chaos Codex with additional options. If I am not mistaken this is the only place it is avaliable in 8th ed. for the time being. The FAQ states the LEGION keyword must be Emperor’s Children. In the BS files it appears avaliable to likely all CSM forces.

**Comment by Mad-Spy** [comment]
You're right, there are no Legion restrictions in the FWHA file. We assume that people will use their common sense, read the rules and not take the units in armies for which they are not valid given the lower incidence of using FW models. Once we have catalogue inheritance in Battlescribe, we'll be able to move the units into the "correct" catalogue and then we'll put in restrictions.
