### ISSUE TITLE
Detachments aren't working properly.

### ISSUE THREAD

**Issue by AsterixCodix** [BSData/wh40k#4874]
Select a Vanguard and a Spearhead detachment, e.g. one Fallen, one CSM. Roster issues say the Vanguard needs 3 Heavy Support, Spearhead needs 3 Elites, Vanguard says limited to 2 Elites, Spearhead says limited to 2 Heavy Support.

**Comment by Mad-Spy** [comment]
Can you provide a screenshot of the problem? Please include a capture of how you have your Forces set up.

**Comment by DrTobogganMD** [comment]
Are you using the beta client?
