### ISSUE TITLE
Chaos Space Marines - Warlord Traits

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k#4876]
**File/Catalogue:** CSM v90

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** 
I have selected Council of Traitors which works fine. I then add a specialist detachment (in this case Soulforged Pack) and Field Commander.
I then get a validation error saying I have one too many CoT warlord traits (maximum 3)

**Comment by Mad-Spy** [comment]
Can you give some more details on your Force composition and which models you have selected?

**Comment by radionausea** [comment]
Battalion (red Corsairs)
Battalion (black Legion)
Chaos Lord on steed of Slaanesh (warlord)
Sorcerer (CoT warlord)
Dark Apostle (CoT warlord)

Spearhead (Black Legion)
Lord Discordant with the field commander WL trait of Master of the Soulforges

**Comment by rakelley** [comment]
Even without CoT this always occurs when trying to take a specialist warlord trait via Field Commander.

I haven't found any combination of legion, units, or single-vs-multiple detachments that this doesn't occur with, you just need a specialist detachment with field commander and an eligible non-warlord HQ to take the specialist warlord trait.  The warlord and field commander can take traits in isolation, but having both always produces `has too many selections from CoT Warlord Traits (maximum 1)`.

**Comment by radionausea** [comment]
I don't get that error with Field Commander without also having Council of Traitors.

I've just tried a lot of variations and I've not received that error from having only a warlord and Field Commander

**Comment by Mad-Spy** [comment]
There's some weird interaction going on with the constraints. I'm working on it.
