### ISSUE TITLE
Grey Knights - Grand Master in Nemesis Dreadknight Relic

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k#4883]
**File/Catalogue:** Grey Knights v34

**BattleScribe version:** 2.01.17

**Platform:** Windows/

**Dropbox:** No

**Description:** Grand Master in Nemesis Dreadknight should not have the option to take the Fury of Deimos relic, as he does not have a Storm Bolter.

**Comment by tekton** [comment]
you missed the apothecary being able to take it as well :P
