### ISSUE TITLE
Khorne - Warlord Traits (Specialist)

### ISSUE THREAD

**Issue by zhangxianzhong** [BSData/wh40k#4885]
**File/Catalogue:** Chaos - Daemons.cat

**BattleScribe version:** 2.01.24.288

**Platform:** Android

**Dropbox:** Yes

**Description:** 
Khone Specialist Detachment : "Legion of Skulls".
"Blood Throne", "BloodMaster", "Skullmaster", "Skulltaker" all have BLOODLETTER keyword, but only X can choose "Warlord Traits (Specialist)".
![Screenshot_2019-04-05-22-27-34-059_net battlescri](https://user-images.githubusercontent.com/10415368/55635896-5b7bfd80-57f4-11e9-8787-27d144febae8.png)
![Screenshot_2019-04-05-22-43-23-979_net battlescri](https://user-images.githubusercontent.com/10415368/55635897-5c149400-57f4-11e9-825c-48b60d989fa2.png)
![Screenshot_2019-04-05-22-43-32-715_net battlescri](https://user-images.githubusercontent.com/10415368/55635899-5cad2a80-57f4-11e9-91a4-f395bd1e7567.png)
![Screenshot_2019-04-05-22-29-31-256_net battlescri](https://user-images.githubusercontent.com/10415368/55635912-62a30b80-57f4-11e9-9f2d-889fa35d29b4.png)
![Screenshot_2019-04-05-22-30-16-262_net battlescri](https://user-images.githubusercontent.com/10415368/55635915-633ba200-57f4-11e9-86bc-f6fcce50ca28.png)
![Screenshot_2019-04-05-22-31-01-149_net battlescri](https://user-images.githubusercontent.com/10415368/55635916-633ba200-57f4-11e9-8279-26fb23f72f1f.png)
![Screenshot_2019-04-05-22-31-32-270_net battlescri](https://user-images.githubusercontent.com/10415368/55635917-63d43880-57f4-11e9-91f0-f2fc3a131032.png)

**Comment by Mad-Spy** [comment]
Skulltaker can't take a choice of Warlord Trait because he's a named character; he must take Devastating Blow.

I had forgotten that the Blood Throne has BLOODLETTER, so I've added that in.
