### ISSUE TITLE
Imperium - FW Astra Militarum/Death Korps: Centaur Points Values

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#4888]
**File/Catalogue:** FW - Astra Militarum

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** The Centaur Artillery Tractor (the one listed as being available to all Imperial Guard regiments) is listed as being 54 points on BS in the Krieg files (didn't check regular AM files)-- 46 points for the vehicle, plus 4 points for each Stubber. As of Chapter Approved 2018, Heavy Stubbers were reduced to 2 points each. As such, the vehicle should be 50 points even.

**Comment by alphalas** [comment]
update your data. is correct in v100

**Comment by GenericCola** [comment]
I've tried updating my data several times, and for some reason Battlescribe will not update my data past v99. This is... odd, to be sure.

**Comment by GenericCola** [comment]
Okay, I've tried deleting all of my data files and re-downloading all of my data from the repository... Krieg is still only updating to v99

**Comment by alphalas** [comment]
Probably hasn’t been released yet - have patience

**Comment by GenericCola** [comment]
I'd manually update if I knew how :(

**Comment by alphalas** [comment]
@windstormscr just pushed a release so you should be able to update soon
