### ISSUE TITLE
Imperium - Deathwatch: Terminator Libby should not have access to Storm shield

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k#4892]
**File/Catalogue:**  Imperium-deathwatch.cat

**BattleScribe version:** 2.01.24

**Platform:**Android

**Dropbox:** Yes/No

**Description:** 
NOTE:  This issue was submitted in issue 4801.and was assigned to Acebaur.  However, it was closed by WindstormSCR with absolutely no explanation, despite a comment requesting rationale for it.  I have checked the DW FAQ, and the issue still seems valid to me: it looks like the Librarian in Terminator Armor was copy/pasted from a regular Space Marines datasheet, and given identical wargear choices, when we do not have them.  I am unsure why the previous issue was closed, it doesn't look like it was set to be corrected in the next update or whatever, and for all I know someone just closed it just because.  Re-opening a new case to try to get this addressed.  As the "Cry Havok and let slip..." update has come out and the issue persists, I am still unsure why 4801 was closed.

Per Index Imperium 1, a DW Librarian in Terminator Armor is not permitted to take a Storm Shield (it is a bullet point in the "changes from normal datasheets" section).

In the Deathwatch 8th edition codex, Storm Shields are not explictly granted to a Librarian in Terminator Armor, and the Librarian in Terminator Armor may only swap a Force Weapon for one from a different type, or swap it's Stormbolter for a Terminator Combi-weapon, neither of which permit a Storm Shield.

Per the Designer's Commentary flowchart, a Codex datasheet can have access to wargear it had in the index.  However, a storm shield was not Index wargear.  As well, a Librarian in Terminator armor did not have access to a storm shield in 7th edition.

However, Battlescribe Sneaky Wolves update still lists it as a valid Index wargear option for a Deathwatch Librarian. This is likely a copy/paste issue that occurred by using the regular Space Marine Libby in Terminator Armor information.

**Comment by WindstormSCR** [comment]
The lack of comment was because of personal events taking place between time of closing and when I would be able to post. Recovery has taken a couple weeks.

On further investigation the stormshield issue is accurate, and the original logic used to keep it was flawed. Further cleanup of index options across DW is pending another detailed look at each.
