### ISSUE TITLE
Chaos - Chaos Space Marines: Error with Obliterator stats?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4895]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The points and possibly stats for the obliterators are incorrect

**Comment by Mad-Spy** [comment]
Stats and points are correct as per Codex Chaos Space Marines 2019.

**Comment by Meister-Haufen** [comment]
They are not correct. The Datasheet states that a unit of Obliterators consists of one Model and up to two models can be added. The point value table in the end of the Codex states that Obliterators always come in units of three. So the two entries don't match. Please remove the Obliterators point costs entirely from the catalogue as per the Codex Chaos Space Marine 2019 2nd edition you can't play them in matched play right now. Sounds ridiculous? Well, it's the same logic used to the end for you to say 65 Points is right.

**Comment by DrTobogganMD** [comment]
Calm down and explain this a bit slower. What do you feel is incorrect exactly?
