### ISSUE TITLE
Deamon Prince Can't choose Psychic ???

### ISSUE THREAD

**Issue by zhangxianzhong** [BSData/wh40k#4896]
**File/Catalogue:** Chaos - Daemons.cat

**BattleScribe version:** 2.01.24.288

**Platform:** Android

**Dropbox:** Yes

**Description:** 👇👇👇
![Screenshot_2019-04-08-11-01-03-999_net battlescribe mobile rostereditor](https://user-images.githubusercontent.com/10415368/55696071-f986e800-59ed-11e9-8fc0-793d4646c541.png)

**Comment by Mad-Spy** [comment]
Click on the Daemonic Allegiance you have selected to choose your powers. See how it is coloured orange? That means there are sub-selections available.
