### ISSUE TITLE
Chaos - Chaos Space Marines: Relics with Reaver Lord WLT

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4898]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** Yes

**Description:** Red Corsairs extra relic issue:

When selecting a Red Corsairs Detachment, and choosing Huron Blackheart as Warlord, this allows for the Warlord Trait: "Reaver Lord".

"Your army can have one extra relic, chosen from the Artefacts of Chaos, which must be given to a RED CORSAIRS CHARACTER from your army that does not already have a relic. This relic must be different to any relics already included in your army. In addition... "

When I attempt to give any Red Corsairs (not Huron) character this extra relic, be it Murder Sword or Intoxicating Elixir etc., I recieve the error: "...has too many selections from Artefacts of Chaos (Maximum)". The original relic is on a character in another detachment from another Legion, it is not a duplicate of the extra one I am selecting. 

This may be to do with the fact that units are not identified as the Legion from the detachment that they are in, at least on the viewable list. Or simply a line of code that is missing when Reaver Lord is chosen as the Warlord Trait.

**Comment by MainerZ** [comment]
This was my submission if you need any more details.

**Comment by Mad-Spy** [comment]
Fixed in v92
