### ISSUE TITLE
Heretic Astartes - Hellforged Rapier Battery keywords

### ISSUE THREAD

**Issue by radionausea** [BSData/wh40k#4906]
**File/Catalogue: Heretic Astartes v29

**Platform:**Android

**Dropbox:** No

**Description:** 
Hellforged Rapier Batteries have the CHAOS SPACE MARINES keyword so they should contribute towards the three units for Red Corsairs to get 3CP rather than 1CP.

**Comment by Mad-Spy** [comment]
Fixed, but updating the CP value of the Trait in the CSM detachment may require users to make a change in their Roster - this is a limitation of the BS validation process.
