### ISSUE TITLE
Chaos - Daemons: Relic validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4910]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** Error in Rewards of Chaos stratagem, even when I pay the CP for the stratagem, my characters can't take relics.

**Comment by Mad-Spy** [comment]
Can you give some more details? There was a problem with Khorne relics which I've already fixed, but if it's with another god I'll need to check again.

**Comment by Mad-Spy** [comment]
Closing due to not getting clarification on the issue.
