### ISSUE TITLE
Imperium - Dark Angels: Relic validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4911]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** So, the bug is that the current version flags relics as illegal u less they are equipped to the warlord. Page 139 of the latest codex, Relics of Caliban, states and I quote:
"If your army is led by a Dark Angels Warlord, then before the battle you may give any one of the following items to an Dark Angels Character." 
This means that the relic does Not need to be equipped to the warlord, and the only requirement be that the warlord is from the Dark Angels chapter. If someone could fix this when they have the time, that would be wonderful.

**Comment by Mad-Spy** [comment]
I'm unable to reproduce this issue in Dark Angels v87. I am able to give a relic to any eligible character as long as I have a Warlord in my Roster and get no errors.

Please provide more details of your issue so we can investigate.

**Comment by Thairne** [comment]
Relics even cannot be chosen because they are hidden if you do not have a Warlord or the stratagems.
Therefore, the issue probably only appears if you select a warlord, take a relic and then deselect the warlord, in which case the error is totally justified.
