### ISSUE TITLE
Requesting Tyberos

### ISSUE THREAD

**Issue by talen2004** [BSData/wh40k#4914]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

I'm new to this but I would like to see Tyberos the Red Wake added to the Battlescribe Warhammer 40k as a HW option.

**Comment by WindstormSCR** [comment]
select the correct chapter, he's been in for months

**Comment by talen2004** [comment]
What Chapter does he fall under, there is no Carcharodon selection

**Comment by Waldmenschen** [comment]
You need to select FW adeptus astartes

**Comment by talen2004** [comment]
Awesome, thank you
