### ISSUE TITLE
Chaos - Daemons: Skarbrand cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4915]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Skarbrand is 360pts not 330! Thanks for all you do!<3

**Comment by Mad-Spy** [comment]
Cost is correct as per Chapter Approved 2018.
