### ISSUE TITLE
Space Marine Scout Sarges can take double-primary weapons

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#4918]
**File/Catalogue:** 
All Space Marine factions

**Description:** 
Note this might be the same issue as  #3453
The scout sergeant validation allows it to equip two copies of primary weapons: eg. it can carry a boltgun AND a sniper rifle -- whereas it's not allowed to do this. It follows normal sergeant protocol, so it replaces **both** its boltgun + bolt pistol for two weapons, one melee/pistol and one melee/pistol/primary

**Comment by gitGremlin** [comment]
This is also repeated in #4700 -- but this is a mistake. the rule is:
`The Scout Sergeant may replace his bolt pistol and boltgun with items from the Sergeant Equipment list.`
That says **and**, not **and/or**, meaning both the boltgun + bolt pistol are traded in for 2 choices, only one of which can be a primary.

**Comment by Mad-Spy** [comment]
As per the comments on #4700, GW have been inconsistent in how they apply the rules for "double-swapping" of items. The current implementation allows both interpretations and will be left as such until GW clarify the situation; hopefully by making the datasheet for Scouts in Codex SM match the ones in Dark Angels and Blood Angels which do not have this ambiguity.
