### ISSUE TITLE
Chaos - Chaos Space Marines - Chosen Champion

### ISSUE THREAD

**Issue by Gallahorn** [BSData/wh40k#4919]
**File/Catalogue:** 
v90
**BattleScribe version:** 2.01.
2.01.17
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
no
**Description:** Detailed issue description.
Chosen Champions are missing thunder hammers in melee weapon selection.

**Comment by Mad-Spy** [comment]
Fixed in next release.
