### ISSUE TITLE
Imperium - Dark Angels: Weapon option issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4923]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Hello, Im a Dark Angels player and I think there is something missing in Company Veteran, Ravenwing Apothecary/Ancient units. As Designer Complementary said that we can use Unit with abilites/stats in Codex, but still can use wargear options in Index. So there is a things
- Ravenwing Apothecary and Ravenwing Ancient still can get their Covus Hammer
- Company Veteran in Index said "any models can swap their bolt pistol with stormshield, or items in Pistol Lists or Melee Weapon list". So I believe that Veteran Sergent can swap his bolt pistol for a storm shield too.
Thankyou for your listening

**Comment by Mad-Spy** [comment]
1. This is probably correct. They should have the hammer as an option still. Precedent was set by the Craftworlds Autarch who no longer comes equipped with a shuriken pistol, but has it as an option.
2. This is not correct. The Index states that any _Company Veteran_ may take a storm shield, not any _model_. A Veteran Sergeant is not a Company Veteran.
![image](https://user-images.githubusercontent.com/29306451/56099444-10a16a80-5f05-11e9-8d22-eb74832430b9.png)
