### ISSUE TITLE
BIG FAQ ... 3? Or BIG FAQ 1, Year 2, Electric Boogaloo?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4932]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.21

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The  calm before the storm faq this is only a place holder for everyone. Easter weekend.

**Comment by DrTobogganMD** [comment]
I'm not sure how to feel about this ... It lacks a certain solar shotput threat.

**Comment by DrTobogganMD** [comment]
Who knows when this'll actually come out.

**Comment by DrTobogganMD** [comment]
It's out ... Using this as the oldest issue to link dupes to.
