### ISSUE TITLE
Request: Option to reserve points for Eisenhorn's Malus Codicium

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#4936]
**File/Catalogue:** Inquisition v23

**BattleScribe version:** 2.01.14

**Platform:** Windows

**Dropbox:** No

**Description:** It'd be nice to add the ability to "save" 25 points on Inquisitor Eisenhorn for the Daemonhost that the Malus Codicium ability summons, without using an actual Daemonhost selection, which takes up an Elite slot choice in a detachment.

**Comment by alphalas** [comment]
Add a reinforcements detachment at initial list building.
