### ISSUE TITLE
Bug report - Imperium - Custodes.catz

### ISSUE THREAD

**Issue by Antyface** [BSData/wh40k#4950]
There is a points and rules issue with the Telemon Dreadnought in comparison to the Custodes beta rules released by GW.

The rules and name of the Arachnus Storm cannon is incorrect in comparison to the beta rules, as is the starting wargear

**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by WindstormSCR** [comment]
https://whc-cdn.games-workshop.com/wp-content/uploads/2019/01/Forgeworld_Custodes_Datasheets-1.pdf

The telemon is very much accurate for the current version of the rules packet.

**Comment by Antyface** [comment]
The mobile version of the rules packet is still showing incorrect rules, profiles and points values.

**Comment by Revilo26** [comment]
WindstormSCR good job with the Custodes data drop. But there is an error with the points for the Telemon. I am specifically referring to the Telemon Caestus - the points value for 1 should be 30pts + 15pts for the Twin Plasma Projector. For a pair, the points cost should be 40pts (total for the pair) + 30pts for 2 Twin Plasma Projectors.
