### ISSUE TITLE
Validation Problems when adding/removing detachments

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k#4957]
**File/Catalogue:**
any/all cats

**BattleScribe version:** 2.02

**Platform:** Windows

**Dropbox:** No

**Description:** When removing then adding detachments to a roster the validation on the roster gets corrupted.

(Updated repro steps after further testing as mentioned below.)

Repro:
1. New Roster
2. Add detachment 1 (e.g. Spearhead), Ok out of the forces editor.
3. Edit Roster, Add detachment 2 (e.g. Batallion)
4. Delete detachment 1
5. Add detachment 3 (e.g. Vanguard)

Result:
![BS202validation_problems3](https://user-images.githubusercontent.com/1786901/56595290-479f0c80-65e6-11e9-85fe-01bda332e8b4.jpg)

Note, this works with any cat, not just Craftworlds - same repro steps with CSM cat:
![BS202validation_problems4](https://user-images.githubusercontent.com/1786901/56595469-9d73b480-65e6-11e9-81d3-a6ff00e16838.jpg)

**Comment by WindstormSCR** [comment]
When I try these repro steps I get correct validation. Can you try updating your files from the current master branch stuff and see what happens? you might need to download the cat files and remove the same-named .catz's

**Comment by KalChoedan** [comment]
Yep, confirmed correct validation after manual update to current master branch.

**Comment by KalChoedan** [comment]
However, a bit of further testing shows there are still validation problems - I don't have exact repro steps yet but will post as soon as I do. Playing around with all the current updates (latest master branch and 2.02.01) at the moment and if I delete a spearhead and then add a vanguard, the vanguard gets the validation for the spearhead as well as itself i.e. I have a Vanguard that requires 3 Heavy, as well as 3 Elites and an HQ.
![BS202validation_problems2](https://user-images.githubusercontent.com/1786901/56594876-8385a200-65e5-11e9-858e-2d1acef5c07b.jpg)

**Comment by KalChoedan** [comment]
Repro:
1. New Roster
2. Add detachment 1 (e.g. Spearhead), Ok.
3. Edit Roster, Add detachment 2 (e.g. Batallion)
4. Delete detachment 1
5. Add detachment 3 (e.g. Vanguard)

Result:
![BS202validation_problems3](https://user-images.githubusercontent.com/1786901/56595290-479f0c80-65e6-11e9-85fe-01bda332e8b4.jpg)

**Comment by Dunamis55** [comment]
I had this problem, but was able to fix it by using the "delete existing data" option when updating my data files.

**Comment by KalChoedan** [comment]
I can't confirm that @Dunamis55 - I've just tested completely deleting all data and redownloading the current master branch manually, and following the repro steps above I get exactly the same result.

**Comment by Dunamis55** [comment]
I believe I've been able to reliably replicate this problem now.

1. Create a New Roster and add a single detachment of any type.
1. Press Ok to begin editing the roster.
1. Click the Edit Forces button and then add 3 new detachments of differing types so that all 4 detachments are unique detachment types (e.g. 1 Vanguard, 1 Unbound, 1 Super Heavy & 1 Supreme Command).
1. Press Ok.
1. Everything should now be broken in the requirements.

**Comment by amis92** [comment]
@Dunamis55 can you repro this with the newest BS? (2.02.03 on desktop)?

If you can please raise it as an issue in https://github.com/BattleScribe/Release/issues with repro steps and reference this issue to have a link. Thanks!

**Comment by Dunamis55** [comment]
Yep, still having the problems and can reproduce them using the same steps as above. Will post in the link provided.

**Comment by amis92** [comment]
The issue on the app side was fixed.
