### ISSUE TITLE
T'au: XV25 Stealthsuits Fusion blaster limit broken

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4958]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Tau stealth suit fusion blaster allowance has been broken. Should allow 1 blaster per 3 models. Will only allow first fusion blaster at 6 models.

**Comment by amis92** [comment]
Confirmed with current master bf27944b9 and Desktop BS v2.02.00


The data was not changed. It seems that it's a problem with the app itself.

**Comment by amis92** [comment]
Reported under https://github.com/BattleScribe/Release/issues/43

This issue should be closed when app is fixed.

**Comment by amis92** [comment]
After fixing should be marked as `Res: external`.

**Comment by amis92** [comment]
Fixed via BattleScribe/Release#43
