### ISSUE TITLE
Battlescribe 2.02.0/1/2 Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4959]
Commandeering oldest issue.

There are currently a few known bugs for the new BS version with 40k data.

**PC** - Current Latest Version - 2.02.01.122: No Major issues.
**Android** - Current Latest Version - 2.02.01.297: No Major issues. ~~No rosters will load. This will be fixed by the next version, which has already been submitted~~
**iOS** - Current Latest Version - 2.02.01.Something: Go get the new version. All good! ~~No catalogs will show when making a new roster (or just Chaos Knights will show).~~ 

**Catalogs in General** - There are some validation issues cropping up for individual catalogs.  Please continue to submit issues separately for those.

**File:** Warhammer 40,000 8th Edition.gstz
**BattleScribe version:** 2.02.00
**Platform:** iPhone / iPod / iPad
**Dropbox:** No
**Description:** iOS only loads  chaos knights when starting a new roster or modifications to saved roster 
Before 2.02.00

**Comment by williamcaw** [comment]
I have the same problem for what I use to validate claims for iOS. Thanks anon.

**Comment by DrTobogganMD** [comment]
I've commandeered the original comment to show status of these bugs.

**Comment by williamcaw** [comment]
#4970 As well

**Comment by Casselcrunk** [comment]
BattleScribe is still only loading Chaos Knights on iOS, hoping the problem is fixed soon. Currently using hammer and chisel method to do my list...

**Comment by DrTobogganMD** [comment]
@Casselcrunk That is correct. The fixed ios version is still being reviewed by Apple. It's out of Jonski's hands at the moment. Once they approve it'll be released on itunes.

**Comment by DrTobogganMD** [comment]
IOS has been updated and the issue has been fixed.
