### ISSUE TITLE
Chaos - Chaos Space Marines: Reaver Lord relic selection not working.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4992]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Roster does not allow for the free relic provided by the "Reaver Lord" Warlord trait

**Comment by Mad-Spy** [comment]
You need to select the "Reaver Lord Artefact" selection on the model which will be carrying the additional relic.
