### ISSUE TITLE
Chaos - Thousand Sons: Helbrute fist cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5005]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Thousand Sons Helbrute fist option is incorrectly listed as 20 pts. Under Helbrute fist options screen fist is listed as 30 pts but as soon as you select it the points oddly adjust to 20.

**Comment by Dunamis55** [comment]
To expand on this, upon taking the Helbrute unit, it has a Helbrute fist costing 20 points (it should be 30 for a single one). If you then take the other arm as a second Helbrute fist, it adds it at 30 points (it should be 40 points total for a pair).
However, if you then change the first arm to any other option, and then switch it back to a Helbrute Fist, both arms now cost 30 points each, totalling 60 points.

**Comment by gitGremlin** [comment]
I have a feeling #5039 is the same issue.

**Comment by Mad-Spy** [comment]
@gitGremlin, it's related, but not the same issue.

**Comment by Mad-Spy** [comment]
This was fixed in v50 of the TSons file.
