### ISSUE TITLE
Bug: Hemlock Wraithfighter is unable to take Twilight Gloom psychic power

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5010]
**File/Catalogue:** Craftworlds v68

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** Hemlock Wraithfighters in a Wraith Host Specialist Detachment are unable to take the Twilight Gloom psychic power, despite meeting the criteria for it (they have the Psyker and Wraith Construct keywords).

**Comment by WindstormSCR** [comment]
fixed for next release
