### ISSUE TITLE
Imperium - Deathwatch: Veteran wargear selection error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5011]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.00

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch veterans select options not working properly. For example unable to select both a power sword and a boltgun without getting a roster error.

**Comment by WindstormSCR** [comment]
Should be fixed in next release, leaving this up until I can confirm it works on current master.
