### ISSUE TITLE
Bug: XV8 Crisis Battlesuits aren't counting Iridium battlesuit wargear correctly

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5012]
**File/Catalogue:** T'au Empire v43

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** The XV8 Crisis Battlesuits unit isn't counting the XV8-02 Crisis Iridium Battlesuit wargear choice correctly.
A unit of 3 models expects a maximum of 0 upgrades, when it should be 1; a unit of 6 models expects 1 upgrade, when it should be 2; and a unit of 9 models also expects 1 upgrade, when it should be 3.

**Comment by WindstormSCR** [comment]
we've seen a few of these, I fixed one in Deathwatch that seems to have been the result of 2.02 fixing a long-standing bug with the shared field.

**Comment by WindstormSCR** [comment]
Ref for the above is #4960

**Comment by amis92** [comment]
Probably another instance of https://github.com/BattleScribe/Release/issues/43 - waiting for resolution there.

**Comment by amis92** [comment]
Fixed via BattleScribe/Release#43
