### ISSUE TITLE
Bug: Super-Heavy and Super-Heavy Auxiliary have wrong required amount of units

### ISSUE THREAD

**Issue by robinmtb** [BSData/wh40k#5023]
**File/Catalogue:** Imperium - Imperial Knights v35

**BattleScribe version:** 2.02.01.122

**Platform:** Windows

**Dropbox:** No

**Description:** 

- When having a Super-Heavy Auxiliary Detachment with 1 Knight in it, I get a warning saying "(Super-Heavy Auxiliary Detachment) must have 2 more selections from Lord of War (minimum 3).

- When having a Super-Heavy Detachment with 3 Knights in it, I get a warning saying "(Super-Heavy Detachment) has 2  too many selections from Lord of War (maximum 1).

These should be the other way around. Super-Heavy is 3-5 and Super-Heavy Aux is max 1.

![Capture](https://user-images.githubusercontent.com/19304676/56826971-cb166300-685d-11e9-8d15-8b6a852a4e70.PNG)

**Comment by DrTobogganMD** [comment]
Are you sure you don't have the forces mixed up, or nested?  Just tested on fresh copy of data and it behaves as properly expected.

**Comment by robinmtb** [comment]
Hi, it was a new list. I have removed and added a couple of times now and got it to work. I got some wierd behavior some times though. I had an admech battalion detachment in the list as well and it gave me error regarding forgeworlds etc for the knight super heavy detachment. Could there be a timing bug or similar here? Are there any logs I can send?

**Comment by williamcaw** [comment]
Or it could be apart of #4957 issues.

**Comment by robinmtb** [comment]
It is behaving just like https://github.com/BSData/wh40k/issues/4957, might be that I encountered that but on Windows.

**Comment by Mad-Spy** [comment]
Pretty sure this has been resolved in the latest version of BS.
