### ISSUE TITLE
Aeldari - Craftworlds: Autarch wargear profile incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5026]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi =D

Autarch with Swooping Hawk Wings, Banshee Mask	Enemy units cannot fire Overwatch at this unit, is incorrect description.

In the index Xenos that’s different.

And the other bug is wend you remove the Mandiblasters for used Banshee mask in reports errors is wrong.

Best regards!

**Comment by WindstormSCR** [comment]
the wargear/ability was updated for all units with the release of the codex per the designer commentary. Will check validation

**Comment by Dunamis55** [comment]
This was specifically called out in the Designer's Commentary as now using the Codex rules:
![image](https://user-images.githubusercontent.com/36267768/56853884-cf0db800-6925-11e9-8991-79cca9b4e7eb.png)
The Banshee Mask Codex rules stop enemy Overwatch, and are used by both Howling Banshees and Jain Zar, so I'd assume the Autarch's version would operate with the same rules.

On the second point, there is indeed a duplicate Mandiblasters option (which also uses the Striking Scorpions' rule wording, not the Autarch's) and incorrectly accepts an Autarch with double Mandiblasters:
![image](https://user-images.githubusercontent.com/36267768/56853959-ef8a4200-6926-11e9-96db-65aef1b507a9.png)

**Comment by WindstormSCR** [comment]
fixed mandiblaster stuff for next release
