### ISSUE TITLE
Imperium - Dark Angels: DA Rules not showing on output

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5028]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Hello. After the latest update, when creating a Dark Angels list, I am now required to select Dark Angels Chapter tactics. However, after doing so, the chapter tactics and rules (Grim Resolve, Defenders of Humanity, Inner Circle) do not  do not show up when viewing the completed list.

**Comment by WindstormSCR** [comment]
Fixed in app on most recent version
