### ISSUE TITLE
Bug/Request: Astra Militarum - Title text for Ministorum Priest's wargear options should be updated

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5032]
**File/Catalogue:** Astra Militarum v210

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** The title for the Ministorum Priest's wargear options is "Just Take Whatever, I Give Up". My sympathies to the editor for the complexity of this unit, but recommend changing the title to "Weapon Options", as the options are now all correct at the time of writing.

**Comment by alphalas** [comment]
Naw is fine as is.
