### ISSUE TITLE
Bug: Astra Militarum - Specialist Detachments don't get automatically applied

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5034]
**File/Catalogue:** Astra Militarium v210

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** After giving a detachment a Specialist Detachment, every unit in the detachment then has to be manually enabled to be a part of the chosen Specialist Detachment.
Specialist Detachments can only be applied once to a single detachment and the relevant units correctly get the option to be included, so this option should just be done in the background and automatically, as in other lists.

In addition, the initial Specialist Detachment option in the No Force Org Slot section is listed as "Vigilus Defiant". Recommend renaming this to "Specialist Detachment" like in other army lists.

**Comment by alphalas** [comment]
TECHNICALLY, the guard implimentation is more correct because it adds the relevant keywords, which the other styles actually don't. unfortunately that does mean more clicks, but I prefer the more exact granularity for clarity. 

However, I will rename it as suggested. thanks!
