### ISSUE TITLE
T'au Empire: Selection rules not showing on output

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5038]
**File:** T'au Empire.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Not sure if this is broken or a feature that has been removed, but my new Tau Empire entry lists do not contain the “Selection Rules” at the bottom of the list, similar to my other armies (SM & CSM!

**Comment by amis92** [comment]
Sounds like an instance of https://github.com/BattleScribe/Release/issues/47

Will close when dependency is done.

**Comment by amis92** [comment]
Fixed via BattleScribe/Release#47
