### ISSUE TITLE
Hellforged Contemptor double-fist points calculation doesn't work

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5039]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Contemptors give double chainfist or double claws cost the single form of the weapon, not the dual.

**Comment by gitGremlin** [comment]
This is happening to all other types, including leviathan dreads. I suspect this is the same across both chaos and imperium rosters.

**Comment by Mad-Spy** [comment]
Fixed in v32 of FW Heretic Astartes, #5008
