### ISSUE TITLE
Inquisitor Hector Rex has the incorrect points

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5040]
Inquisition

Hector Rex should be 100pts, not 110.

**Comment by Dunamis55** [comment]
Hector Rex is 100 points without wargear costs. However, there's no listed points cost for a Storm Shield in any Inquisition list, of which he is equipped with.
All costs for Storm Shield (Characters) in other codices have been standardised to 10 points each though, which would raise his points cost to 110 points.

**Comment by gitGremlin** [comment]
Without a wargear cost, and as a named character, he probably shouldn't have it costing any points. The Forgeworld book in question is strange in that it lists no cost for storm shields... but that means they have no cost for inquisition.

**Comment by Dunamis55** [comment]
Yea, I can see the logic both ways. If it's not listed in any Inquisition list though, I'd personally lean on the side of him just being 100 points, especially considering he is a named character.

**Comment by WindstormSCR** [comment]
Unfortunately this is an issue with FW, and thier choice to make character costs include wargear, and then set the majority of that wargear to zero, except standard gear.

as a result, hector rex is indeed 110 points:

https://puu.sh/DlIlX/5c587ddd14.png

**Comment by gitGremlin** [comment]
FW has issued no cost for the Storm Shield, and extrapolating from other data sources isn't how any other costs are calculated. The wargear 'Storm Shield' does not have a price in Inquisitor lists (not in Imperium 2, nor in subsequent FAQ, nor in Chapter Approved). A player using an Inquisition force has no way of knowing that Storm Shields are a uniform 10 points (they're not: sometimes they're 2 points) across other armies. Ergo, he needs to be 100.
This is the same with Imperial Guard plasma weapons costing different to Space Marines, and Inquisitor Combi-Plas costing differently to Space Marines.
