### ISSUE TITLE
Chaos: Helbrute weapon validation issues in 2.02

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5041]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** Started creating a battalion. First unit added is the hellbrute. Replaced fist with missle launcher. Getting issue stating the missiles are hidden. Added fist back and swapped the multimelta for the missle launcher and got the same error. Tried in three different formations with the same error.

**Comment by Mad-Spy** [comment]
This has been caused by a change to constraint validation in 2.02. Working on a fix.

**Comment by Mad-Spy** [comment]
This is now working in all affected catalogues.
