### ISSUE TITLE
Orks Warbikers

### ISSUE THREAD

**Issue by xerusjoe** [BSData/wh40k#5048]
This would be on all current versions of the app for the Orkz.catz file. Platform is not relevant.

Nobs on Warbikes (as well as the boss nob) have a checkbox for Slugga when they already have a selection for Arm1 and Arm2. Checking the box for Slugga causes an error because the model cannot have 3 weapons.

Warbikers don't automatically have Choppa and Slugga as their weapons, but instead a checkbox for each. Normal Warbikers can only come in one way, and that is with 2x Dakkagun, 1x Stickbomb, 1x Choppa, and 1x Slugga. The checkbox for Choppa and Slugga is an unnecessary thing to have there.

Attached is an image showing how the code would look in the data editor currently (red) and how it would look to solve the issue (blue). In the case of the Nobs on Warbikes on the bottom left, simply removing the Slugga selection entry from solves this. The normal Warbikers would need a Min+Max 1 for both Slugga and Choppa to remove the need for a checkbox.
![ork bike changes](https://user-images.githubusercontent.com/30806706/56932447-bbcf2980-6a98-11e9-8933-568547a667ff.png)

**Comment by DrTobogganMD** [comment]
Mmm. I love when someone knows the value of collective :)  I'll assign to the Ork maintainer :)

**Comment by tag8833** [comment]
Good solution.  I'll put it in place for the next release.
