### ISSUE TITLE
No canticles of the Omnissiah show at the end of the rooster

### ISSUE THREAD

**Issue by dumdrak** [BSData/wh40k#5053]
**File/Catalogue:** Adeptus Mechanicus

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** No canticles of the Omnissiah show at the end of the roster

When printing no canticles of the Omnissiah show at the end of the roster

**Comment by Mad-Spy** [comment]
This is a known issue with the new version of the BS app. Please report it to the Battlescribe developer. We cannot fix it in the datafiles.
