### ISSUE TITLE
Various catalogues: Astraeus and Thunderhawks missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5055]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** Yes

**Description:** Space wolves, Dark angels, and blood angels are all missing astreus super heavy tank and both thunderhawk varients.

**Comment by Thairne** [comment]
Seems I forgot to link these things.. at least I am consistent in my upfuckery :P
