### ISSUE TITLE
Imperium - Blood Angels: Dreadnought issues

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#5057]
1. The Contemptor Dreadnought entry is misspelled as "Dreadought"
2. The Relic Contemptor Dreadnought has not been linked from the FWAA library.
3. Mortis Dreadnought has not been linked from the FWAA library.

**Comment by onlyamonth** [comment]
Item 2: The Relic Contemptor Dreadnought has not been linked from the FWAA library.
This does not appear to be fixed by https://github.com/BSData/wh40k/commit/1e8ed9425c185bbf6e27a9e6027b073636221153
