### ISSUE TITLE
Imperium - Space Marines: LR Variant appearing when Open Play is not selected

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5065]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Land Raider Variant (Open Play) is appearing with out the tag open play selected and is in the wrong location of selection Lord of war

**Comment by Mad-Spy** [comment]
You're correct that it shouldn't be appearing, but they are Lords of War, as per p24 of Chapter Approved 2017, under 7. List Profile
