### ISSUE TITLE
Aeldari - Craftworlds: Song of Ynnead missing text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5074]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** Ynnari Updates. 
Relic ; 'Song of Ynnead' is missing part of its 'Abilities' full entry below,
'Each time you make a wound roll of 6+ for this weapon, that attack is resolved with an AP of -3. Each time an attack made with this wapon slays an enemy model the target unit subtracts 1 from its Leadership characteristic until the end of the turn'

**Comment by natecross1990** [comment]
Also noticed that 'Favoured of Ynnead' selection doesn't allow you to select 2nd warlord trait without flagging validation issues
