### ISSUE TITLE
Aeldari - Craftworlds: Exalted of Ynnead should allow additional WLT

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5075]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** 'Exalted of Ynnead' selection in the 'No Force Org' area does not allow valid allocation of a second warlord trait. This should work in a similar way to the Imperial Knights 'Exalted Court' Stratagem

**Comment by WindstormSCR** [comment]
duplicate of #5052
