### ISSUE TITLE
Adeptus Custodes - Godstrike Teleportarium Typo

### ISSUE THREAD

**Issue by MechaWorg** [BSData/wh40k#5080]
File/Catalogue: Imperium - Adeptus Custodes v28

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Units that have the 'From Golden Light' ability (Shield-Captain in Allarus Terminator Armor, Vexillus Praetor in Allarus Terminator Armor, Allarus Custodians) have the following typo: 'During deployment, you can set up this model in a Goldstrike-pattern teleportarium array instead of...'

This should read:

'During deployment, you can set up this model in a Godstrike-pattern teleportarium array instead of...'

Custodes love gold but not everything is named after it ;)

**Comment by WindstormSCR** [comment]
Fixed for next release
