### ISSUE TITLE
Chaos - Chaos Space Marines - Daemon Prince can't pick the psychic power from dark hereticus discipline

### ISSUE THREAD

**Issue by angelambrosio** [BSData/wh40k#5083]
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.

**Platform:** iOS/Mac

**Dropbox:** Yes

**Description:** When you add a daemon prince (with or without wings) and choose a proper daemonic allegiance, you can't pick the second psychic power from the Dark Hereticus discipline or the specific chaos mark power.

**Comment by Mad-Spy** [comment]
The method of selection has changed. Powers are now in the root of the DP entry, instead of nested within the Daemonic Allegiance.
