### ISSUE TITLE
Chaos - Servants of the Abyss: Missing units and profiles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5086]
**File:** Chaos - Servants of the Abyss.catz

**BattleScribe version:** 2.02.01

**Platform:** Android

**Dropbox:** No

**Description:** The faction data is missing for most of the units, there's no listing for chaos beastmen nor rogue psykers and the unit data that is there is incomplete.

**Comment by Mad-Spy** [comment]
As per the Servants rules, if you include Obsidius Mallex in your army, the Chaos Beastmen, Rogue Psykers and Black Legionnaires do not take up a slot and therefore are moved to the "No Force Org Slot" section.

I cannot see anything wrong with any of the unit profiles, so if you can provide specific examples of what is missing that would be great.
