### ISSUE TITLE
Ynnari detachment Rules

### ISSUE THREAD

**Issue by MnG-SeventySix** [BSData/wh40k#5090]
**File/Catalogue:** Ynnari

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:**No

**Description:** It's about the new Ynnari rules they no longer lose Rising Crescendo/Battle Focus/Strenght form Pain when they become an Ynnari Detachment.
They Just lose detachment attribute from Theyr craftworld,kabal, ecc...
The rule say: If Yvraine, the Visarch or the Ycarne is included in a Craftworld, Harlequins or drukkhari Detachment, you can choose for that Detachment to remain a Ccraftworld, Harlequins or Drukkhari Detacchmennt, or for that detachment to become an Ynnari Detachment.
If u cchoose for the Detachment to remainn as a Craftworld, Harlewuins or Drukhari Detachmennt, then Yvraine, the Visarch or the Yncarne can be included in that detachment without preventing other units from Gaining the following Detachment Ability: The Path of War, Craftworld Attributes, Vanguard of the Dar CCity, Raiding Forces, Drukkhari obsessions, Defenders of the black library, masque form. ( there is no more mention about ancient doom, Battle focus, Rising crescendo or strenght form pain)

**Comment by WindstormSCR** [comment]
Update your data
