### ISSUE TITLE
Chaos - Daemons: Add new Slaanesh models and rules.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5091]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.02.21

**Platform:** Android

**Dropbox:** No

**Description:** Keeper of secrets out of date. Missing new units from slaanesh release

**Comment by Mad-Spy** [comment]
These models came out _today_ and we don't magically get access to datasheets any more than anyone else does. When we can find full details of the datasheets and points costs, then they'll get added.

**Comment by paulwinters** [comment]
Spikey Bits had the new Slaanesh datasheets on their website https://spikeybits.com/2019/04/slaanesh-daemons-full-40k-rules-datasheets-revealed.html it looks like GW forgot to include points value for the Contorted Epitome. I didn't see it the booklet that came with the kit.

**Comment by Mad-Spy** [comment]
Units added. I'll have to add the Epitome's points when GW update them.
