### ISSUE TITLE
Imperium - Adeptus Titanicus: Error with rules output?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5092]
**File:** Imperium - Adeptus Titanicus.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Super-Heavy Auxiliary Detachment  various  Titans. Macro not generated as rules every thing is selected to show rules

**Comment by williamcaw** [comment]
Have problems repeating that error. If it’s just the auxiliary detachment but if you have another detachment it’s not there at the end of the list. If you select just the Titans it shows up.

**Comment by Mad-Spy** [comment]
This should be fixed in the latest version of the Battlescribe app.
