### ISSUE TITLE
Terrax Drill Visibility

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5094]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Terrax-pattern drill entree from forge world is missing space marines can take this option it says it in the description, the only chapters that can not take it, is Legion of the damned and Grey knights. The option is missing from all the other chapters like space wolves, blood angels etc. the drill can be used for chaos and Adeptus mechanicus and space marines

**Comment by WindstormSCR** [comment]
Needs the appropriate primary category applied to the root entry, since it's a shared GST link for use by multiple factions.
