### ISSUE TITLE
Bug: Fallen - Fallen Champion cannot replace bolt pistol for a combi-weapon

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5097]
**File/Catalogue:** Fallen v5

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** The Fallen Champion has the wargear option "The Fallen Champion may replace his boltgun and/or bolt pistol with one item from the Champion Equipment list.", but is unable to replace his bolt pistol with a combi-weapon and also keep his boltgun.

**Comment by Mad-Spy** [comment]
The constraint from the Champion Equipment list which allows 1 selection from the "rifle" weapons list prevents this from being a valid wargear choice.
