### ISSUE TITLE
Salamanders FW Characters missing 

### ISSUE THREAD

**Issue by battlescribeuser** [BSData/wh40k#5098]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox:** N/A

**Description:** Detailed issue description.

With the merge of FW Adeptus Astartes and Space Marines the Salamanders special characters are not in the HQ section.

Specifically missing is Bray’arth Ashmantle and Harath Shen.

**Comment by WindstormSCR** [comment]
You need to select the salamanders chapter in chapter selection for them to appear.
