### ISSUE TITLE
[Anon] Bug report: Chaos - Servants of the Abyss.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5099]
**File:** Chaos - Servants of the Abyss.catz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** The stat block for Black Legionnaires(Servants of the Abyss) is missing, from both Killteam and full 40k lists

**Comment by fuckingenglish** [comment]
Killteam is not in this file please refer to wh40k-killteam
