### ISSUE TITLE
Error with Telemon points on BattleScribe 

### ISSUE THREAD

**Issue by Revilo26** [BSData/wh40k#5110]
@WindstormSCR good job with the Custodes data drop. But there is an error with the points for the Telemon. I am specifically referring to the Telemon Caestus - the points value for 1 should be 30pts + 15pts for the Twin Plasma Projector. For a pair, the points cost should be 40pts (total for the pair) + 30pts for 2 Twin Plasma Projectors.

**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by WindstormSCR** [comment]
This looks like a 2.02 issue, will check it tonight. other dreads with double fist options also seem to be having similar errors
