### ISSUE TITLE
Elysian Lightning Strike Fighter 

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#5114]
**File/Catalogue:** Elysian 

**BattleScribe version:** 2.02.

**Platform:** Windows

**Dropbox:** No

**Description:** Elysian Lightning Strike Fighter is incorrect cost base (should be 185 points inclusive of standard weapons). In addition it is missing the new option of removing the long barrelled autocannon when selecting 6 hellstrikes. 

It should be noted that this option as written in the errata (at least in my interpretation) means you CANNOT choose to have an autocannon AND 6 hellstrikes. It's either 4 and the cannon or just 6. 

Edit: AM Catalogue is now correct. Just requires Elysian update.

**Comment by lewis0460** [comment]
Page 48 – Lightning Strike Fighter, Wargear Options
Add the following additional bullet point to this
datasheet’s Wargear Options:
‘• If this model is equipped with four hellstrike missiles,
it may replace its long-barrelled autocannon with two
additional hellstrike missiles.’

**Comment by Mad-Spy** [comment]
The base points appear to be correct, at least in v213 of the AM file, which also added the 6 hellstrike option.

**Comment by lewis0460** [comment]
Yeah the AM file is ok. The Elysian file however is incorrect.

**Comment by Mad-Spy** [comment]
Oops, sorry. Reopened so it can be fixed.
