### ISSUE TITLE
No Warload Traits in Super-Heavy Auxiliary Detachment

### ISSUE THREAD

**Issue by gre370** [BSData/wh40k#5116]
File/Catalogue: Imperium - Space Marines v97, Chaos - Death Guard v62

BattleScribe version: 2.02.02

Platform: iOS

Dropbox:No

Description: When warlord option is selected in Super-Heavy Auxiliary Detachment, no warlord trait options appear. I have tried on Mortarion and Roboute Guilliman. 

However, when a model is selected as warlord from my Battalion, warlord traits appear as expected.

**Comment by Mad-Spy** [comment]
As named characters, neither Mortarion nor Roboute are allowed to select a Warlord Trait; they both must take a specific Trait which is included in their profile if you make them the Warlord.

![image](https://user-images.githubusercontent.com/29306451/57483466-d4acbb80-729e-11e9-8222-b9d734b4e5e9.png)

**Comment by gre370** [comment]
Thank you! Embarrassing....

Sent from my iPhone

On May 9, 2019, at 3:10 PM, Iain Launchbury <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #5116<https://github.com/BSData/wh40k/issues/5116>.
