### ISSUE TITLE
Imperium - Astra Militarum: Hydra Heavy stubber cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5119]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** Astra Militarum Hydra Heavy Stubber upgrade wrong cost. Currently 4 points, should be 2. I checked all the other Astra Militarum vehicles (even the Super Heavies) and Hydra was the only one I found that was not 2 points for a Heavy Stubber.

**Comment by Mad-Spy** [comment]
This is fixed in v213 of the AM catalogue.
