### ISSUE TITLE
Imperium: FW Venerable Chaplain Dreadnought can't take new Crimson Fist warlord traits

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5120]
Venerable Dreadnought Chaplain can only take (CF) Tenacious Opponent from the CF list. There are two more WL traits it's legal for the model to take, though.

**Comment by Mad-Spy** [comment]
I'm not sure what the problem is here? The Chaplain Dread appears to have access to all WLTs.
Can you elaborate?

**Comment by gitGremlin** [comment]
The Chaplain should have access to the full selection of three Crimson Fist Warlord Traits.
He currently only has access to CF Tenacious Opponent.
![screenshot_20190510-132146](https://user-images.githubusercontent.com/12858421/57527088-023d4780-7327-11e9-9a9b-7978f218867f.png)

They should have:
Refuse to Die
Stoic Defender

https://spikeybits.com/2019/01/do-crimson-fists-have-what-it-takes-for-the-meta.html

**Comment by Mad-Spy** [comment]
Oh, I forgot about the White Dwarf minidex! Those traits need to be added to the FW Adeptus Astartes library.
