### ISSUE TITLE
Chaos - Chaos Space Marines: Non-Khorne units visible when selecting Brazen Beasts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5129]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.02.03

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Brazen Beasts addition of the  keyword Khorne only .
from FAQ VIGILUS ABLAZE : 1.0
All Brazen Beast units must have the Khorne
keyword if they are able to do so. If a unit has the
Tzeentch, Nurgle or Slaanesh keyword, it cannot
be from the Brazen Beasts. In addition, Psykers
cannot be from the Brazen Beasts.’

**Comment by Mad-Spy** [comment]
If you choose Brazen Beasts, you *are* forced to choose Khorne for your Mark of Chaos, else you get a validation error.

Is there a particular unit on which you're not seeing this behaviour?

**Comment by fuckingenglish** [comment]
chaos lord on Palanquin of Nurgle, disk and Steed of Slaanesh should not be selectable or shown nor should any other chaos god be chosen

**Comment by Mad-Spy** [comment]
Thanks for clarifying the issue.

**Comment by fuckingenglish** [comment]
missed one Rubric Marines
