### ISSUE TITLE
Imperium - Space Marines - Dev SGT Improper Warning

### ISSUE THREAD

**Issue by tksolway** [BSData/wh40k#5132]
**File/Catalogue:** Warhammer 40k V 1.3.04

**BattleScribe version:** 2.02.03

**Platform:** iOS

**Dropbox:** No

**Description:** 

The Devastator SGT gets the warning: "Space Marine Sergeant has 1 too many selections from SGT Equipment (Maximum 1)" when more than one sgt equipment selected.  

Likely the maximum is set incorrectly for this unit.  SM Codex PG 173:

"The Space Marine Sergeant may replace his boltgun with **_items_** from the sergeant equipment list"

**Comment by Mad-Spy** [comment]
No. He gets to swap 1-for-1. You cannot give him 3 weapons. We've had this argument before and our stance has not changed.

**Comment by williamcaw** [comment]
Default is the bolt gun
