### ISSUE TITLE
Imperium - Dark angels: Missing IMPERIUM keyword, no option to take Assassins

### ISSUE THREAD

**Issue by theonetruejedi** [BSData/wh40k#5133]
**File/Catalogue:** Dark Angels. 40k 1.3.04.

**BattleScribe version:** 2.01.02.098

**Platform:** Windows/iOS/Android

**Dropbox:** No

**Description:** 
Edited for clarity:

1. There are a number of Dark Angels models which are missing the IMPERIUM keyword.
2. There is no option to use the "Operative Requisition Sanctioned" stratagem in the Dark Angels catalogue.

**Comment by williamcaw** [comment]
This is  in conjunction  With the fallen keyword

**Comment by Thairne** [comment]
I did a major pass over the key words. Should be fixed now.

**Comment by Mad-Spy** [comment]
@Thairne, the Stormraven is showing up as Uncategorised; looks like it lost its Primary keyword.

Also, the "Operative Requisition Sanctioned" strat still needs to be added as an RSE.

**Comment by Thairne** [comment]
Whoopsiedaisies!
