### ISSUE TITLE
Imperium - Dark Angels: Vet Sgt Storm shield?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5138]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.03

**Platform:** Windows

**Dropbox:** No

**Description:** Hello, it about Dark Angels Veteran Units
In the new FAQ of GW this months, A unit data sheet have versions in both Index and Codex, then it must use the Codex's Abilities.
But with the war gears, they can using Codex or Index of player choice.
So about the Dark Angels Veteran Units, the Veteran Sergent can swap his bolt pistol or bolt gun to get the Storm Shield (Index's version)
Thanks for reading.

**Comment by Mad-Spy** [comment]
Not sure where you're getting that from? Assuming you're talking about the Company Veterans datasheet, the Veteran Sergeant was never able to take a Storm shield, as it does not appear in the _Sergeant Equipment_ list. He is not a "Space Marine Veteran", so he does not have the option to take the shield.
