### ISSUE TITLE
Imperium - Deathwatch: Watch Captain wargear options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5139]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.02.02

**Platform:** Android

**Dropbox:** No

**Description:** In the last FAQ, the Watch Captain was allowed to use a relic blade, xenophase blade and all other chainsword substitutes while also using a weapon from the Deathwatch equipment list. This is not implemented in the battlescribe file yet, since it says there's an error in the equipment if you do that

**Comment by williamcaw** [comment]
This is the same thing as the Sargent wording
