### ISSUE TITLE
Aeldari - Drukhari: SpearHead Detachment compo issue

### ISSUE THREAD

**Issue by Vaster42** [BSData/wh40k#5140]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The spearhead detachment ask for 3 Elites and allows only 2 Heavy Support. (Restriction of the Vanguard detachment)

**Comment by Mad-Spy** [comment]
This is a Battlescribe bug. See #4957. We're waiting on a fix from the developer.
