### ISSUE TITLE
Imperium - Dark Angels: Grim Resolve missing from output

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5141]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.03

**Platform:** Mac

**Dropbox:** No

**Description:** The Dark Angels Chapter Tactic/Special Rule "Grim Resolve" does not show up in army lists.

All units in in the army can re-roll 1's to hit as long as they didnt move.
No more than 1 model can be lost as a result of a single failed morale roll
https://www.warhammer-community.com/2017/12/04/chapter-focus-dark-angels/

**Comment by Mad-Spy** [comment]
This is a weird one as it's definitely there as a root rule in the cat. Maybe put it there directly rather than as a link?

**Comment by Thairne** [comment]
Probably a BS issue, Grim Resolve is shown fine on PC Desktop and my Android Handy.
If I remember correctly, there was an issue with the BS App that did not show root rules...
Checking 2.02.04 updates right now - 
Fixed root Rules linked from imported data files not showing up when viewing a Roster.

Might be the issue persists on Mac.

**Comment by Mad-Spy** [comment]
Should be fixed in BS 2.02.04.
