### ISSUE TITLE
Chaos - Chaos Space Marines: Unable to select Relics for Red Corsairs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5145]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.02.02

**Platform:** Android

**Dropbox:** No

**Description:** Hi. For renegade (red corsairs) chapter, i am unable to select any artefact.

**Comment by Mad-Spy** [comment]
Do you have either a Warlord or one of the Gifts of Chaos options in your Roster?

**Comment by fuckingenglish** [comment]
crimson slaughter , red corsairs, renegade chapters,world bearers. does not Generate artifacts when selected for warlord or be given  2.02.04 pc  and 2.02.03 ipod/others

**Comment by Mad-Spy** [comment]
All of those seem to work as expected for me. If the model is eligible for a particular Relic then it can be chosen.

Can you give a specific example of what you're having trouble with?

**Comment by fuckingenglish** [comment]
i just did general chaos lord to check

**Comment by Mad-Spy** [comment]
Have you given him any wargear that allows a Relic? If you don't then they won't appear. His default wargear doesn't allow any.

**Comment by williamcaw** [comment]
Yes

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/58002080-407bf900-7ad5-11e9-99dd-de117815634d.png)
See above a Red Corsairs Chaos Lord with Power sword and Combi-melta and a Mark of Nurgle. He is eligible for 3 Relics, which appear correctly as options for him.
