### ISSUE TITLE
Land Raider Excelsior Warlord Traits

### ISSUE THREAD

**Issue by rtho782** [BSData/wh40k#5146]
**File/Catalogue:** Imperium - Dark Angels v93

**BattleScribe version:** 2.02.03

**Platform:** Windows

**Dropbox:** No

**Description:** Land Raider Excelsior can be selected as Warlord but cannot be given any warlord traits.

This was previously fixed in issue #3734 but appears to have come back.

**Comment by WindstormSCR** [comment]
Which catalog are you seeing affected by this? Working on SM v97 and DA v96

**Comment by rtho782** [comment]
DA v96. I can select the Land Raider Excelsior as the warlord, but I can't give it any warlord traits.

![image](https://user-images.githubusercontent.com/25555587/58234711-145fb280-7d37-11e9-8a85-829c1fddf30a.png)

![image](https://user-images.githubusercontent.com/25555587/58234726-1e81b100-7d37-11e9-9a9e-9a53ec223ef8.png)
