### ISSUE TITLE
Imperium - Astra Militarum: Add Defenders of Humanity as a root rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5152]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.02.03

**Platform:** Windows

**Dropbox:** No

**Description:** The general Astra Militarum ability "Defenders of Humanity" (Astra Militarum Codex p. 132) is not shown in BattleScribe. Please include that as an ability indicated at the end of the roster.

**Comment by williamcaw** [comment]
This has been happening more sense the updated to the new format. Just relax.

**Comment by Mad-Spy** [comment]
It's not in the file at all, so it would need to be added.
