### ISSUE TITLE
Imperium - Space Marines: Sgt Chronus Sponson selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5155]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** I just noticed if you want to take Sergeant Chronus from the Ultramarines HQ slot in a Predator, you are not able to choose the sponson weapsons. So you can just configure the main weapon and that's it. 
But if you take a normal Predator from the heavy support list, you have both options to choose the main and sponson weapons. Basically it is not possible, to configure Sgt. Chronus in a fully equipped Predator.
Please add the sponson weapon options to Chronus Predator.

**Comment by Mad-Spy** [comment]
Yes, you can. If you click into the Predator after selecting it, you can see the weapon and sponson options.
![image](https://user-images.githubusercontent.com/29306451/58114456-b07ea200-7bef-11e9-96d0-a85e83c97ee2.png)
