### ISSUE TITLE
Imperial knights household traditions issue

### ISSUE THREAD

**Issue by SeanT135** [BSData/wh40k#5157]
**File/Catalogue:**  Imperium - Imperial Knights v36

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Apart from house mortan (under the questor imperialis allegiance) none of the other imperial knights household choices have their household traditions, under both the questor imperialis and questor mechanicus allegiances

**Comment by fuckingenglish** [comment]
i have it generating in roster view and that it working as intended

**Comment by Mad-Spy** [comment]
I am unable to replicate this at all. Can you provide screenshots of the problem?

**Comment by SeanT135** [comment]
Here are a few images of me trying to access it in different ways. Just
hovering, viewing selection, and viewing roster

**Comment by williamcaw** [comment]
Hay if it’s the aux detachment then no .it will never  benefit of having a household tradition .

**Comment by SeanT135** [comment]
It does this in any type of detachment

**Comment by williamcaw** [comment]
Have you checked the roster vie advance settings?

**Comment by Mad-Spy** [comment]
Your screenshots didn't come through, I'm afraid.

**Comment by SeanT135** [comment]
I don't know how to access advanced settings. And yeah, those screenshots
were mangled

**Comment by williamcaw** [comment]
Click on the roster view then click advance

**Comment by DrTobogganMD** [comment]
I can also not replicate this. Please upload your SS to the issue or imgur if you're still having this issue.

**Comment by SeanT135** [comment]
Better versions of all three screenshots

**Comment by DrTobogganMD** [comment]
You are not uploading screenshots.

**Comment by SeanT135** [comment]
I presumed that is what you meant by SS, but here is an imgur instead
https://imgur.com/a/CBIGMR2

**Comment by DrTobogganMD** [comment]
You're using Unbound.  Household Traits are only allowed in Super Heavy Detachments, per codex.
