### ISSUE TITLE
Imperium - Space Marines: Something is missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5160]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** I can not find the (unit) script (with psi-ace) so I think he was forgotten

**Comment by Mad-Spy** [comment]
I'm not sure what you're asking for here. Can you give some more details? 
Which unit? What is a "psi-ace"?

**Comment by Mad-Spy** [comment]
Unable to resolve this as it's not clear what the problem is.
