### ISSUE TITLE
Imperium - Space Marines: Selecting Field Commander unlocks Traits for all Characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5165]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** I chose Space Marines with the Ultramarine Chapter Selection
Battalion Detachment
Specialist Detachment - Indomintus Crusaders -1CP
HQ - Marneus Calgar is the Warlord
HQ - Primaris Lieutenant is given Stratagem "Field Commander -1CP"
however
ELITES - Company Ancient can now take a Warlord Trait (ie: Storm of Fire) with no error

**Comment by Mad-Spy** [comment]
@WindstormSCR, the hide condition for Warlord Traits is being triggered off a selection of Field Commander in "Force", rather than "Parent".
