### ISSUE TITLE
Space Wolves: Points Incorrect for Wolfguard with Jumpack

### ISSUE THREAD

**Issue by timbrown81** [BSData/wh40k#5168]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux PC

**Dropbox:** Yes/No YES

**Description:** Detailed issue description.
Currently no points are reflected when selecting jumpacks for a unit of Wolfguard.  Per the codex the points per model should go up from 15 to 19 points when selected.

**Comment by Mad-Spy** [comment]
Working fine in the released version of the Wolves catalogue. Each model is correctly incremented by 4 points when selecting Jump Packs.
