### ISSUE TITLE
Imperium - Adeptus Mechanicus: Cawl and Knights missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5169]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** In the HQ Bellisarius Crawl is missing, and I can't select lord of war in order to use a questor mechanicus Imperial Knight

**Comment by Mad-Spy** [comment]
1. Belisarius Cawl can only be chosen if you select Mars as your Forgeworld.
2. All Knights are in the Imperial Knights catalogue; you can select a Mechanicus aligned House once you've added your Super Heavy detachment.
