### ISSUE TITLE
Imperium - Space Marines: Librarian in Terminator Armor should not equip Storm Bolter with Storm Shield

### ISSUE THREAD

**Issue by Remgrandt** [BSData/wh40k#5171]
**File/Catalogue:** Space Marines v97

**BattleScribe version:** 2.02.04.125

**Platform:** Windows

**Description:** The Librarian in the Space Marines catalogue can take a Storm Shield with a Storm Bolter. I believe the Librarian gets its access to the Storm Shield from the Index: Imperium 1 page 15, which says the Storm Shield replaces the Storm Bolter.

**Comment by Mad-Spy** [comment]
This is not the case. If you equip both a storm shield and a storm bolter on the Librarian in Terminator Armour, you get a validation error.

![image](https://user-images.githubusercontent.com/29306451/58536029-52e9e700-81e7-11e9-8301-906acb5277c3.png)

![image](https://user-images.githubusercontent.com/29306451/58536045-5c734f00-81e7-11e9-8662-70a475815b07.png)
