### ISSUE TITLE
Thousand Sons psykers with access to Dark Hereticus spells needs Weaver of Fates

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5175]
![Screenshot_20190529-181300](https://user-images.githubusercontent.com/12858421/58577056-9707d680-823d-11e9-9bea-854b7ed0df5c.png)

**Comment by gitGremlin** [comment]
All thousons psykers should have access to this version of Weaver of Fate, which affects Tzeentch Heretic Astartes instead of Thousand Sons.

**Comment by Mad-Spy** [comment]
P100 of Codex: Thousand Sons states that Dark Hereticus powers can be selected from "the table below". The relevant table on p101 does not include Weaver of Fates. There has not been an erratum to update this, therefore, RAW, they do not have access to that power.
