### ISSUE TITLE
Imperium - Space Marines: Captain on Bike cannot select 2 bolt pistols without error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5178]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.02

**Platform:** Android

**Dropbox:** No

**Description:** Captain on Bike creates roster error (Limit 1) when selecting bolt pistol from the Pistols list when replacing Master Crafted Boltgun. 
Codex allows replacing Mastercrafted Boltgun for item from Pistols list  no mention of Cap.

**Comment by fuckingenglish** [comment]
this comes from index
