### ISSUE TITLE
Chaos - Thousand Sons: DP should not have access to Warp Bolter

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#5185]
File: Chaos - Thousand Sons.catz

BattleScribe version: 2.02.04

Platform: Windows

Description: Thousand Sons Daemon Prince of Tzeentch has access to a Warp Bolter. It should not have access to this as per the BRB flowchart. 

Please reference Chaos - Death Guard.catz for how Daemon Princes are supposed to work.

**Comment by Mad-Spy** [comment]
Given the updated guidance on p5 of the [Designer's Commentary](https://www.warhammer-community.com/wp-content/uploads/2019/04/warhammer_40000_update_April_2019_en.pdf) for the April 2019 Update which states that all Daemon Princes are to be considered as the same datasheet, and, applying the BRB Designer's Commentary flowchart, the Index Daemon Prince and the Codex Daemon Prince of Tzeentch are the same. Therefore, it _should_ have access to a warp bolter.

**Comment by BaconCatBug** [comment]
Totally incorrect. You can't just ignore the first half of the answer.

"No. For the purposes of these guidelines, all these datasheets are considered to be the same."

"These Guidelines" are the Matched Play "Rule of 3" guideline, and NOTHING ELSE. In fact, that FAQ proves they aren't the same and thus should not have access to the warp bolter.

**Comment by Mad-Spy** [comment]
I still believe that TSons should have access to a Daemon Prince that can take a Warp Bolter, given that this was possible for them pre-Codex. You mention that you prefer the Death Guard version where there is a separate Index DP entry. Is that an acceptable solution for TSons?

**Comment by BaconCatBug** [comment]
That is literally how the rule works. The Daemon Prince of Tzeentch cannot take a warp bolter, but if you take the Index Daemon Prince with the Thousand Sons keyword, it can.

**Comment by Mad-Spy** [comment]
OK, I'll work on that. I can't promise it will be soon, as I'm currently rebuilding the structure of all Chaos files to take advantage of new BS functionality, but it will be part of that work.

**Comment by BaconCatBug** [comment]
I appreciate the quick reply! I wish you the best of luck. Re-doing stuff from scratch is never fun!

**Comment by KalChoedan** [comment]
For what it's worth, the counter-argument is that the flowchart actually asks you to refer to the datasheet that was in play for the model, not the unit, and if you had a tzeentch DP model pre-codex you would indeed have used the index DP of chaos with Mark of Tzeentch datasheet, so the flowchart does apply and the warp bolter is a valid choice. It's also been ruled this way in tournaments (e.g. dallas just a few weeks back.)

It's impossible for anyone to say with certainty which is correct until GW answer the actual question here with a solid FAQ.
