### ISSUE TITLE
Imperium - Adeptus Ministorum: Preacher can take infinite chainswords

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5186]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The preacher in the elite slot can select infinite chainswords all in game formats .

**Comment by fuckingenglish** [comment]
i think you mean not take

**Comment by fuckingenglish** [comment]
can confirm that there is no limit to cap of chain sword section
![image](https://user-images.githubusercontent.com/47985304/58888035-90dd8400-869b-11e9-8819-9e733fddc39f.png)
