### ISSUE TITLE
Imperium - Adeptus Mechanicus: Unable to select warlord traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5194]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Re open #5193 warlord abilities are not selectable in any way . Current build is a blank space for selection . Have confirmed and  verified  that it’s not ther on iOS and on the pc build. DrTobogganMD Please review the links of warlord.

**Comment by Thairne** [comment]
Works fine on desktop and android. Cannot confirm/deny for iOS devices.
Either bug with BS on iOS or user error.

**Comment by williamcaw** [comment]
I have reviewed this it’s not clickable.

**Comment by cartag** [comment]
Works fine for me on IOS.

**Comment by DrTobogganMD** [comment]
As said in the other issue. Works fine on Android and desktop.

**Comment by Thairne** [comment]
Well since we cannot reproduce and you can - provide some screenshots so we can narrow down the problem?

**Comment by williamcaw** [comment]
What I mean by I can reproduce the click is that other cats. Have the select ability is the main selection box after the warlord is selected by a new user. Take a look at space  Marines, imperial  knights,  and many other cats. This is ease of use for end user.

**Comment by DrTobogganMD** [comment]
IK is a unique case.  I had to implement it that way in order to validate their extra Warlord Trait strat.

So in short, there is no bug.

**Comment by Thairne** [comment]
While I totally agree that this is not a bug in the first place, I dont feel to strongly either way. So, for the sake of consistency, I can move the traits to the highest level,
