### ISSUE TITLE
Warhammer 40,000 8th Edition: Incorrect point values for scout weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5196]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.99

**Platform:** Android

**Dropbox:** No

**Description:** The space marine scout point cost for sniper and shotgun if incorrect, they should only be 2 and 0 points respectively

**Comment by Mad-Spy** [comment]
Costs look fine in release version of Space Marines catalogue. Scout w/ shotgun is 11pts, Scout w/ Sniper rifle is 13pts.
