### ISSUE TITLE
Blackstone Fortress Detachment

### ISSUE THREAD

**Issue by vossler117** [BSData/wh40k#5197]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

Battle scribe let's me make a detachment using Blackstone Fortress models in a battleforged army in matched play but surely they can't do that because of the battle brothers rule? 

![Screenshot_20190609-231903](https://user-images.githubusercontent.com/51544499/59165055-85f87880-8b0d-11e9-8f97-f342d6d740b3.jpg)

**Comment by Mad-Spy** [comment]
We do not validate Battle Brothers. You can make an army containing Space Marines and Tyranids using the data and you won't get any errors because they can't be in an army.

It's up to the user to validate these rules.
