### ISSUE TITLE
Chaos - FW Renegade and Heretics: Incorrect statline for Militia Champion

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5200]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** The values for BS/WS on the Renegade Militia Champion are wrong. They are 5+ each whereas they should be 4+ I think.

**Comment by Mad-Spy** [comment]
Duplicate of #5117. Fixed in current release, please update your data.
