### ISSUE TITLE
Tau Crisis Suits should have access to Iridium Armor at 1 per 3 per unit.

### ISSUE THREAD

**Issue by LockeWatts** [BSData/wh40k#5201]
**File/Catalogue:** 1.3.06

**BattleScribe version:** 2.02.01

**Platform:** Android

**Description:** Creating a 3 man XV8 Crisis unit and giving one of them "XV8-02 Crisis Iridium Battlesuit" results in the error: XV8 Crisis Battlesuits has 1 too many selections of XV8-02 Crisis Iridium Battlesuit (maximum 0)

**Comment by Mad-Spy** [comment]
The only way I can replicate this error message is to give the XV8-02 upgrade to the Shas'vre AND a Shas'ui at the same time. I'm unable to get that exact message to appear in any other way.

**Comment by amis92** [comment]
@LockeWatts it was a bug in one of BattleScribe releases. Please make sure you have the latest and confirm it still happens.

**Comment by amis92** [comment]
Most probably duplicate of #5012

**Comment by LockeWatts** [comment]
@amis92 I have v1.3.06 published Jun 7th 2019. Screenshot attached displaying the error. 

![image](https://user-images.githubusercontent.com/1290805/59558656-1ed33c00-8fc5-11e9-950e-1cb00b819a11.png)

**Comment by amis92** [comment]
That's data release. I'm talking about the app itself. You have v2.02.01. Please update to latest. 😊

**Comment by LockeWatts** [comment]
@amis92 fixed indeed, thanks!
