### ISSUE TITLE
Chaos Space Marines - Reaver Lord extra relic option only functions if character you want to give the relic to is in the same detachment as the Warlord.

### ISSUE THREAD

**Issue by TophatKiyaki** [BSData/wh40k#5203]
**File/Catalog:** Chaos Space Marines.catz/Chaos - Chaos Space Marines v98

**BattleScribe version:** 2.02.04.125.

**Platform:** Windows 10

**Dropbox:** Yes

**Description:** The current iteration of the Chaos Space Marine catalog does not properly allow you to gain your additional relic if you are utilizing the Reaver Lord warlord trait available to the Renegade Legion: Red Corsairs. If you choose the Reaver Lord trait, the option to select "Reaver Lord Artefact (no cost)" only appears if the character you are attempting to apply it to is also in the same detachment as your Warlord who has the trait, as opposed to any Red Corsairs character in your army, which is how it is supposed to function. Characters in other detachments can still be given your army's baseline free relic, but can not benefit from the one that is gained from Reaver Lord.

![Battlescribe Reaver Lord Bug 1](https://user-images.githubusercontent.com/31428938/59323608-5e3e1780-8ca9-11e9-841b-37ee2ad5eaac.png)
![Battlescribe Reaver Lord Bug 2](https://user-images.githubusercontent.com/31428938/59323611-61390800-8ca9-11e9-9c1a-3d26dfd27060.png)

**Comment by Mad-Spy** [comment]
Fixed in v99. "Reaver Lord Artefact" will be available to characters in Red Corsairs Detachments which are not the one containing the Warlord Trait.
