### ISSUE TITLE
CSM - Faction Marines and Renegade Chapters.

### ISSUE THREAD

**Issue by Gallahorn** [BSData/wh40k#5206]
**File/Catalogue:** 
 V98
**BattleScribe version:** 2.01.
2.02.04
**Platform:** Windows/iOS/Android/Mac/Linux
Windows
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.

Im pretty sure that Plague/Rubic/Noise/Berzerkers cant be of certain renegade chapters according to the last faq of Vigilus Ablaze.

For example:
 All Purge units must have the Nurgle keyword if they
are able to do so. If a unit has the Khorne, Tzeentch
or Slaanesh keyword, it cannot be from the Purge.

So maybe need a error message added to that or even hide them for detachments of the renegade chapters.

The chapters that are affected are:
Purge - Nurgle keyword
Scourged - Tzeentch keyword
Flawless Host - Slaanesh keyword
Brazen Beast - Khorne keyword

Link to the faq for reference
https://www.warhammer-community.com/wp-content/uploads/2019/04/warhammer_40000_imperium_nihilus_vigilus_ablaze_en.pdf

**Comment by Mad-Spy** [comment]
This is a problem caused by a problematic merge we had a few weeks back. It'll be fixed in the next release.

**Comment by amis92** [comment]
@Mad-Spy can we not re-apply fixes manually until #5204 is done? Adding more duplication won't help with fixing the situation.
