### ISSUE TITLE
CSM - Terrax Pattern Termite Assault Drill cannot be selected as dedicated transport

### ISSUE THREAD

**Issue by DoBene29** [BSData/wh40k#5207]
**File/Catalogue:** 
Chaos Space Marines

[warhammer_40000_termite_assault_drill_en.pdf](https://github.com/BSData/wh40k/files/3284640/warhammer_40000_termite_assault_drill_en.pdf

**Platform:** Android

**Description:** The Terrax Pattern Termite Assault Drill cannot be selected as CSM dedicated transport. The rules are attached to this message.

Thanks in advance for looking into it.

**Comment by Mad-Spy** [comment]
It's a Forgeworld model, so you will need to add a FW Heretic Astartes hold detachment to use it.

**Comment by DoBene29** [comment]
thank you for the quick reaponse
