### ISSUE TITLE
AM Lightning Strike Fighter Missiles

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#5209]
**File/Catalogue:** Astra Militarum 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** As referenced in #5114 the Lightning Strike Fighter was given the option to swap its autocannon for an additional 2 hellstrike missiles when already selecting 4. HOWEVER this was already fixed and pushed before because I remember checking it so there's a strong possibility that this has been removed to due the merger issue #5204

**Comment by Mad-Spy** [comment]
Yes, it's definitely been broken by #5204, because I know I did the work once.

**Comment by Mad-Spy** [comment]
Refixed via #5214
