### ISSUE TITLE
Unable to apply Warlord/Relics to Land Raider Excelsior

### ISSUE THREAD

**Issue by MrFluckoff** [BSData/wh40k#5211]
**File/Catalogue:** Space Wolves

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** Unable to select Land Raider Excelsior as Warlord or apply Chapter Relics to it.

**Comment by williamcaw** [comment]
Re-created iOS 2.02.04 unable access  attach warlord when selected.

**Comment by Mad-Spy** [comment]
Working as expected in Space Wolves v84 in the current release.
