### ISSUE TITLE
Bug Report: Imperium - Space Marines

### ISSUE THREAD

**Issue by GalacticPoutine** [BSData/wh40k#5218]
**File/Catalogue:** Adeptus Astartes.cat

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Inceptor Squad does not take into account Sargeant's weapon options. Only lists points for base model.

**Comment by Mad-Spy** [comment]
Assault bolters are 10pts each as of Chapter Approved 2018. Cost of "Assault bolters x 2" for a default Inceptor Squad = 60pts which is 6 bolters, two for each of the standard Inceptors and two for the Sergeant.

![image](https://user-images.githubusercontent.com/29306451/59569044-e0e51f00-907b-11e9-856c-f50dab431918.png)
