### ISSUE TITLE
Base Cost Astra Militarum

### ISSUE THREAD

**Issue by GuillaumeDuezOfficiel** [BSData/wh40k#5226]
File/Catalogue: Astra Militarium v210

BattleScribe version: 2.02.01

Platform: Mobile

Dropbox: No

Description: The cost point of these units are not in accordance with the codex Astra Militarium :
Baneblade: wrong Base cost  -> 390
Banehammer: wrong Base cost -> 390
shadowsword: wrong Base cost -> 390
autocanon :  wrong Base cost -> 15
servitor  :  wrong Base cost -> 2

**Comment by alphalas** [comment]
Please consult chapter approved 2018 before making points cost bug reports; these were all changed and are correct according to that.
