### ISSUE TITLE
Imperium - Space Marines: Deathstorm Drop Pod is using incorrect "Drop Pod Assault" text

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5227]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Deathstorm Drop Pod has the Drop Pod Assault ability.  It currently reads:
During deployment, you can set up this model, along with any unit embarked within it, in orbit instead of placing it on the battlefield. At the end of any of your Movement phases, this model can perform a drop pod assault - set it up anywhere on the battlefield that is more than 9" away from any enemy models. Any model embarked inside must immediately disembark, but they must be set up more than 9" away from any enemy models. Any model that cannot be set up because there is not enough room is slain.

it should read:
During deployment, you can set up this model, along with any unit embarked within it, in orbit instead of placing it on the battlefield. At the end of any of your Movement phases, this model can perform a drop pod assault - set it up anywhere on the battlefield that is more than 9" away from any enemy models.

The unit is not a transport and cannot embark other units, so the Drop Pod Assault text is modified in the FW Index.

**Comment by DrTobogganMD** [comment]
Technically, the ability is still valid ... Any models embarked inside (of which there are none ...) must disembark lol.
