### ISSUE TITLE
Imperium - Astra Militarum: Hammer of Sunderance incorrectly only available to Warlords

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5228]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Good day,

Hammer of Sunderance, the new Vigilus relic for Tank Commanders, should not be limited to Warlords.  (A Tank Commander that is not a Warlord should be able to take the relic).

Thanks,
Doug W.

**Comment by Mad-Spy** [comment]
They can. You must specifically mark them as belonging to the Emperor's Fist (after selecting the Specialist Detachment) and then it will become available to them as long as there is a Warlord in your list.
