### ISSUE TITLE
Imperium - Adeptus Ministorum: Repressor text not updated from FAQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5231]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Hello! There is inconsistancies with the "Sororitas Repressor" rule which says this:

Firing Ports
Up to six models being transported by the Sororitas Repressor can shoot in thier Shooting phase, measuring and drawing line of sight from any point on the vehicle. Units that shoot in this manner count as having moved if they or the Sororitas Repressor moved in the preceding Movement phase

Where as in the official update of 1.6 (https://www.warhammer-community.com/wp-content/uploads/2018/09/imperial_armour_index_forces_of_the_adeptus_astartes.pdf) it says:

Page 54 – Sororitas Repressor
Change the Firing Ports ability to read:
‘Up to 6 models embarked on this model can attack in their Shooting phase. Measure the range and draw line of sight from any point on this model. When they do so, any restrictions or modifiers that apply to this model also apply to its passengers; for example, the passengers cannot shoot if this model has Fallen Back in the same turn, cannot shoot (except with Pistols) if this model is within 1” of an enemy unit, and so on.’

**Comment by fuckingenglish** [comment]
index tab need
