### ISSUE TITLE
Chaos - Daemons: Something is broken, maybe?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5234]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Ther are wired artifacts of code found  of hq selection os that refers to other games supported by app

**Comment by Mad-Spy** [comment]
I don't understand the problem. Can you provide screenshots or some further details?

**Comment by williamcaw** [comment]
Found one  references to specialist within some demons selection after being marked as your warlord for abilities

**Comment by Mad-Spy** [comment]
@williamcaw, I think you're perhaps referring to the Warlord Traits from Specialist Detachments? It's hard to tell without proper details or a screenshot.

**Comment by williamcaw** [comment]
Nope found where selection during a selection of a selection of battalion.

**Comment by Mad-Spy** [comment]
This is still no clearer as to what you think the problem is. If English is not your first language, please feel free to post in your native language and I can run it through Google Translate if it's easier for you. Or maybe upload a screenshot?

**Comment by fuckingenglish** [comment]
i have also found Specialist selection when not activated in force org slot on multiple hq's

**Comment by alphalas** [comment]
Like Iain said, please provide screenshots so we understand what you’re talking about.

**Comment by Mad-Spy** [comment]
Closing as there has been no clear explanation of what the issue is.
