### ISSUE TITLE
CSM Havocs - Unit size & wargear errors

### ISSUE THREAD

**Issue by undividedusa** [BSData/wh40k#5238]
**File/Catalogue:** Chaos - Chaos Space Marines v98

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Multiple errors with the current Heavy Support - Havocs. From Codex, "This unit contains 1 Aspiring Champion and 4 Havocs. It can include up to 5 additional Havocs (Power Rating +3). Each model is armed with a boltgun, a bolt pistol, frag grenades and krak grenades. Any model may replace its boltgun with a chainsword. Up to four Havocs may replace their boltgun with one item from the Heavy Weapons or Special Weapons lists." 
 > Issues: Presently, the only options are to choose 4 Havocs with one of the five Heavy Weapons options, and the Aspiring Champion's wargear. There are no options to add or configure any Havocs with: 
-boltguns, 
-chainswords, or
-Special Weapons. 
- In addition, the Aspiring Champion's profile defaults to a flamer, rather than a boltgun. 
- Finally, Havocs should have a base cost of 13pts per model, not 14pts per model. 

![Error](https://user-images.githubusercontent.com/52113764/59969315-6430c580-94ff-11e9-9803-820600e94021.JPG)

**Comment by Mad-Spy** [comment]
It sounds like you are using the old Codex. Those are no longer the rules for Havocs since the new Codex was released.
