### ISSUE TITLE
Imperium - Space Marines: Rosters will not load

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5241]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** No rosters load; after selecting and the ad pops up, locks up at loading the roster. Every time. Tried usual fixes (refresh files, restart app+phone, try various lists etc) Other things such a Killteam Data loads just fine.

**Comment by Mad-Spy** [comment]
This sounds like an app issue, rather than a data issue, as opening Space Marine Rosters works fine for me on all platforms. You will need to report this to the app developer.
