### ISSUE TITLE
Imperium - Dark Angels: Company Veteran Lightning Claw validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5246]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** Yes

**Description:** Giving a Company Veteran two lightning claws throws up the following error: "Space Marine Veteran has 1 too many selections from Melee Weapons (maximum 1)."

**Comment by Mad-Spy** [comment]
Unable to replicate in v101 of the Dark Angels catalogue. Please ensure you have the latest version of the data files.
