### ISSUE TITLE
Imperium - Blood Angels: Relic validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5247]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Full version number is v2.02.04.125
Since the June 23rd 2019 data update, Blood Angels armies have a limit of 0 Relics, rather than 1 Relic, without having to pay the CP cost to take extra relics.
This means that all Blood Angels lists are flagged as "invalid" in Battlescribe at the moment.

**Comment by Mad-Spy** [comment]
To clarify, setting a model as Warlord is not granting the allowed relic.
