### ISSUE TITLE
Chaos - Daemons: Rotigus Warlord issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5248]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** In the Chaos Daemons codex, selecting the Warlord option with Rotigus defaults the Warlord selection tables to the GUO entry.  If you include both in a roster, make Rotigus your Warlord, then check the GUO entry, you'll see the issue.  Thanks!!

**Comment by Mad-Spy** [comment]
Nope, I'm afraid I don't see a problem. Can you be more specific?

**Comment by williamcaw** [comment]
It’s the same issue that has been reported in the last week that the hq are not showing or allow for input from users to make selection of warlord ability’s

**Comment by Mad-Spy** [comment]
Rotigus doesn't get to choose a Trait (or a Relic), because he is a named character. He must take a specific one, as per p129 of the Daemons Codex. This Trait is added to his profile if you mark him as the Warlord.
