### ISSUE TITLE
Imperium - Adeptus Custodes: Telemon Caestus not updating cost when paired

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5250]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** There is a mistake in Adeptus custodes Beta rules for the Telemon Heavy Dreadnought.
When you chose a pair of Telemon Caestus they should drop from 45 to 35.
In older versions it was right, but now, both Telemon Caestus apears at 45 points.

**Comment by Mad-Spy** [comment]
@WindstormSCR, the cost modifiers are using the link IDs rather than the ID of the Caestus itself, so they will never trigger (as you won't get two instances of the individual links).

**Comment by WindstormSCR** [comment]
They used to be the static IDs, I think this might have been an artifact from the 2.02 conversion
