### ISSUE TITLE
Orks: "Follow Me, Ladz" doesn't grant its CP

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5253]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.03

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting "Follow Me Ladz" as the Warlord trait of my Weirdboy, the additional 1CP that it provides does not get added to any totals.

**Comment by williamcaw** [comment]
Orks , not recreated

**Comment by Mad-Spy** [comment]
CP boost added to the Trait in v52 of Orks catalogue; also fixed wording of the Trait.
