### ISSUE TITLE
Imperium - Space Wolves: Incorrect cost for Fenrisian Wolves

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5263]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The point value of Fenrisian Wolves is updated from 8 to 6 per model in Chapter Approval 2017

**Comment by Mad-Spy** [comment]
Yes, the cost of these models from the _Index_ was decreased in CA2017, but when Codex Space Wolves was released in 2018, it changed the costs to the current values. Codex SW + CA2018 are the current points values in force for Space Wolves.
