### ISSUE TITLE
Imperium: Adeptus Mechanicus - Skorpius Disintigrator

### ISSUE THREAD

**Issue by Armond-Hammer** [BSData/wh40k#5268]
Unit is missing a Broadspectrum datatether as per unit profile. Also middle bracker movement profile should be 9" instead of 6" and middle bracket attacks should be D3 instead of 1.

![65421687_374151529821667_9027156150994337792_n](https://user-images.githubusercontent.com/16469179/60471211-b83f5680-9c31-11e9-8eab-9ce9869b39f8.jpg)

**Comment by williamcaw** [comment]
relax it’s being Processed soon.

**Comment by Armond-Hammer** [comment]
Just informing.

**Comment by tekton** [comment]
I was already working on it while working on Cawl ;)
