### ISSUE TITLE
Sororitas Repressor Firing Ports incorrect text

### ISSUE THREAD

**Issue by kovacor** [BSData/wh40k#5270]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Sororitas Repressor in Adepta Sororitas file has the open top firing rules rather than the Firing Ports rules from forge world. They are distinctly different in that Repressors can fall back and the units inside are able to fire.

**Comment by Mad-Spy** [comment]
The text was updated to match the latest FAQ in the most recent release, see #5231.
