### ISSUE TITLE
Imperium - Dark Angels: Repulsor Executioner missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5275]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.04

**Platform:** Android

**Dropbox:** No

**Description:** The Repulsor Executioner is missing from the roster.

**Comment by Thairne** [comment]
As of now, only <CHAPTER> has access to the executioner.
Without a real datasheet in hand which allows BA, DA and SW to use it, this is correct.

**Comment by SpaceJS** [comment]
the following lines are from the Dark Angels Codex. as they are a chapter they should have access to th executioner.

KEYWORDS
Throughout this section you will come across
datasheets with the DARK ANGELS keyword.
This indicates that the unit is drawn from the
Dark Angels Chapter, but the keyword can
also be changed to represent that the unit
is drawn from a successor Chapter of your
choosing, as described below.

**Comment by alphalas** [comment]
Except the marine codex says this:
![D4AEF927-D172-4B50-8AA1-791EC0002B83](https://user-images.githubusercontent.com/15703066/62012106-e68c5500-b14f-11e9-9911-b870f72885dc.jpeg)

Rules as written, without an expressed permission for the units to be BA/DA/SW/Deathwatch they cannot be if they have <CHAPTER>.

**Comment by SpaceJS** [comment]
the executioner datasheet says adeptus astartees chapter, not space marines
or space marines detachment

Op zo 28 jul. 2019 om 21:54 schreef Jon Kissinger <notifications@github.com

**Comment by alphalas** [comment]
You’re missing the point about chapter; BA/DA/SW/DW are not acceptable replacements for <CHAPTER>.  It needs an FAQ or an addendum to be able to legally be BA/DA/SW/DW. In the meantime, if you insist on using it in those armies, you can include a child detachment of space Marines.

**Comment by SpaceJS** [comment]
they are, they are not space marines but they are adeptus astartes

**Comment by DrTobogganMD** [comment]
![image](https://user-images.githubusercontent.com/16939161/62012457-19cce500-b14c-11e9-80e6-cd297d6cd306.png)

![image](https://user-images.githubusercontent.com/16939161/62012508-d030ca00-b14c-11e9-8873-cf7666a492c2.png)

You noted yourself that 

"Throughout this section you will come across
datasheets with the DARK ANGELS keyword.
This indicates that the unit is drawn from the
Dark Angels Chapter"

Above is 2 examples of the Land Raider sheet.  The one in the DA Codex has "DA" specifically on it. Repulsor Executioner does not, and therefore cannot be drawn from the Dark Angels Chapter.

**Comment by SpaceJS** [comment]
there are index choices available which do not have the DA keyword anywere so why not do the same for the executioner. you really think they will allow only the normal repulsor and not the executioner?

**Comment by DrTobogganMD** [comment]
https://www.games-workshop.com/en-US/Space-Marines-Primaris-Repulsor-Executioner-2019 - note that it doesn't say it can be taken by the other chapters. (whereas the regular repulsor page specifically calls it out).

**Comment by alphalas** [comment]
So yes, yes we do.

**Comment by NonEuclideanLlama** [comment]
https://www.belloflostsouls.net/2019/07/40k-the-repulsor-is-now-available-for-non-codex-marines.html
There's rules now

**Comment by alphalas** [comment]
And we’ve already released it it’s in the file. But thank you !
