### ISSUE TITLE
Imperium - Space Marines: Repulsor Executioner has incorrect transport capacity

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5276]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Android

**Dropbox:** No

**Description:** The transport capacity of the Repulsor Executioner is incorrectly stated as 10 instead of 6.

**Comment by DrTobogganMD** [comment]
Closed via #86eb026
