### ISSUE TITLE
Chaos - Chaos Space Marines: Host Raptorial WLT missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5278]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Host raptoral specialist detachment doesn’t show its warlord trait.

**Comment by Mad-Spy** [comment]
The Trait will only appear for models with a Jump Pack, because only Jump Pack models are eligible to be members of that Specialist Detachment.

I've updated the file so that the Chiropteran Wings also only appear for Jump Pack models, as they were mistakenly appearing for all models.
