### ISSUE TITLE
Astra Militarum points for Veterans were updated to 5 per model - Update Command Squads

### ISSUE THREAD

**Issue by xamsham** [BSData/wh40k#5279]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
The cost for Command Squads was not updated. Command Squads have a separate cost line in the Codex, which was not updated by Chapter Approved.
