### ISSUE TITLE
T'au Empire xv25 stealth battlesuits // target lock ruleis absent

### ISSUE THREAD

**Issue by Bredian** [BSData/wh40k#5285]
**File/Catalogue:** 
T'au Empire v47
**BattleScribe version:** 2.02.03.229

**Platform:** Android
**Dropbox:**No

**Description:**
In XV25 Stealth Battlesuit profile, in Selected Rules section Target Lock rule is absent, however this rule is present in Codex: T'au Empire for this unit. Errata from 29/05/19 does not remove this rule.

**Comment by Mad-Spy** [comment]
If you give a model a Target Lock (which is optional in all cases), then the rule appears as expected.
