### ISSUE TITLE
Imperium - Deathwatch: Add Repulsor Executioner

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5289]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Deathwatch does not have access to the Repulsor executioner, even though it’s been added to the other space marine lists.

**Comment by Mad-Spy** [comment]
It's currently only been added to Space Marines, because we haven't seen full rules to see whether it's actually available to anyone else.

**Comment by Thairne** [comment]
essentially duplicate of #5275
