### ISSUE TITLE
Imperium - Blood Angels: Add Repulsor Executioner

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5291]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.29

**Platform:** Android

**Dropbox:** No

**Description:** The. Replsour excutioner data sheet is missing from the heavy support slot for blood angels

**Comment by Mad-Spy** [comment]
It's currently only been added to Space Marines, because we haven't seen full rules to see whether it's actually available to anyone else.

**Comment by Thairne** [comment]
essentially duplicate of #5275

**Comment by chainw0** [comment]
Still isn't available in battlescribe...
