### ISSUE TITLE
RAM issues 

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k#5292]
**File/Catalogue:** 

**BattleScribe version:** 2.02.03.299

**Platform:** Android

**Dropbox:** Yes

**Description:** I have battlescribe on my old Samsung TabE. I believe it is the previous generation one. a couple days ago it began saying it the device is running low on RAM when I was trying to make multi detachment lists. Even after I did a full factory restart its still doing it. And low RAM mode doesnt work either. Is this a normal problem or is there something I am doing wrong when putting the lists together?

**Comment by Mad-Spy** [comment]
We know about it; it's a Battlescribe bug. The developer is working on it.

**Comment by IronWulfen88** [comment]
thankyou. I was getting worried I had somehow messed it up
