### ISSUE TITLE
Chaos - FW Renegade and Heretics: Validation error with multiple Marauder squads

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5296]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Put in a Renegade Marauder Squad. Set to stalkers, 4 autoguns and 2 special weapon units (both set to sniper). Set Marauder Chief to autogun, no melee and plasma pistol. Duplicated. After duplicating, bug started occurring. Get error 'Marauder Chief has 1 too many selections from weapon options (maximum 1)'. Tried adding melee weapon, result was the same but with (maximum 2). Tried removing weapons. Error changed to 'Marauder Chief must have 1 more selections from Weapon options (minimum 2)'

**Comment by Mad-Spy** [comment]
You cannot equip your Marauder Chief with an autogun and  plasma pistol. You must swap the autogun to get a plasma pistol, as per the third bullet point on the datasheet.
