### ISSUE TITLE
Imperium - Dark Angels: Primaris Master missing power sword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5297]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Under Primaris Master there is no option for adding a power sword. Page 87 states "This model may take a power sword, or replace it's master-created auto bolt rifle and bolt pistol with a power fist and a plasma pistol."

**Comment by Mad-Spy** [comment]
You need to tap on the bolt rifle option (not the radio button, the option itself) and you'll be given the power sword option.

Battlescribe shows options which have sub-options by marking them with an orange square on the left, rather than a grey one.
