### ISSUE TITLE
Chaos Knights (and so it begins)

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5307]
I appreciate that this is first version, so there's gonna be a lot of these little niggles;

Chaos Knight Despoiler should cost +20pts if it's equipped with two melee weapons. Book states without wargear it's 285, or 305 if it's equipped with the chainsword and fist.

**Comment by Mad-Spy** [comment]
Already fixed, will be in the next release.

**Comment by gitGremlin** [comment]
I see you cast _prescience_ today.
