### ISSUE TITLE
Chaos Knights - Relics & Warlords

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5308]
If you take corrupted heirlooms strategem, war dogs can't take relics. They should be able to.

Also, while fw knights can't benefit from heirlooms or council strategem (I imagine this will be FAQ'd as they're probably Abhorrent class), they should still be able to be made Warlords and thus get relics and traits that way.

**Comment by Mad-Spy** [comment]
RAW they are currently unusable as they do not have the CHAOS KNIGHT keyword, which is required in all cases to qualify for Traitoris Lance, Relics and Traits.

**Comment by Mad-Spy** [comment]
Corrupted Heirlooms only applies to KNIGHT DESPOILER, KNIGHT TYRANT and ABHORRENT class, so no, War Dogs can't take Relics using it.

**Comment by gitGremlin** [comment]
Jeez, I need to buy the book or something. Everything I know is from YouTube videos.

**Comment by Mad-Spy** [comment]
Same! Guess I just saw better quality videos :)
