### ISSUE TITLE
Chaos - Questor Traitoris: Dreadblades, Pacts, and Damnations

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5317]
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** Any number of knights in your detachment can have the DREADBLADE keyword, however only 1 may select pacts and damnations. Currently you get an error if more than one knight is listed as a dreadblade, that error should only populate if multiple knights select damnations or pacts.

**Comment by gitGremlin** [comment]
On top of this, you shouldn't throw an error if said dreadblade doesn't have any pacts or damnations. This is an optional pregame step.
