### ISSUE TITLE
Chaos - Questor Traitoris: Knights in a SHAD should not get Ambitions

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5322]
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Auxiliary detachment can never  benefit from ability granted from having main super  heavy detachment .

**Comment by Mad-Spy** [comment]
I'm assuming you mean that you believe Super-Heavy Auxiliary Detachments do not get Traitoris Ambitions? This is incorrect. The criteria to qualify for Traitoris Ambitions is that the Detachment is a CHAOS KNIGHTS Detachment and all units have the same `<QUESTOR TRAITORIS>` keyword. In a SHAD, both of these are true.

**Comment by DrTobogganMD** [comment]
He's right @Mad-Spy page 62. They only get ambitions in SHD

**Comment by Mad-Spy** [comment]
Turns out I should read the whole page, and also that GW should be consistent in the way they write rules! I'll sort it out.
