### ISSUE TITLE
Imperium - Space Marines: Performance Issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5324]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Whenever I attempt to load a detachment or faction the app crashes to dash board

**Comment by williamcaw** [comment]
This is being worked upon the app developers. If there’s any more  problems please speak to them .

**Comment by williamcaw** [comment]
There is a workaround for some of this issue. And that’s to turn off the screen lock and just let this load.

**Comment by DrTobogganMD** [comment]
Latest BS update functionally resolves this. SM is still slow to load, but I think this is the best we'll get with the size.  Once the Supplements drop, we may visit splitting SM into its own chapter cats to help a bit.
