### ISSUE TITLE
Dark Angels Primaris Master can't take a power sword

### ISSUE THREAD

**Issue by LionDaJohnson** [BSData/wh40k#5325]
**File/Catalogue: Imperium - Dark Angels `v101**` 

**BattleScribe version:** v2.02.03.299.

**Platform:** Android

**Dropbox:** No

**Description:** Dark Angels Primaris Master cannot be given a power sword.

**Comment by Thairne** [comment]
He can, but it is inconveniently hidden in the auto bolter entry.

**Comment by LionDaJohnson** [comment]
Thanks
