### ISSUE TITLE
Wrong Knight Despolire Points cost with melee weapons

### ISSUE THREAD

**Issue by MnG-SeventySix** [BSData/wh40k#5326]
**File/Catalogue:** Warhammer 40,000 v1.3.14 / Khaos Knights v22

**BattleScribe version:** 2.02.04

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** no

**Description:** Hi, On the last Knights Codex (page 71) there are 2 different Knight Despoilers prices one for your customizable Despoiler with no gear 285pts. and another one for the Knight with 1 reaper chainsword and 1 thunderstrike gauntlet 305(+2pts mandatory Heavy Stubber) pts but on the app if you try to make this weapon setup the model cost it's 372 (285+30+35+"2 mandatory Heavy Stubber") instead of the specif cost for this kind of model/weapons set up

**Comment by mykyl69** [comment]
Also Forgeworld models can not choose Iconoclast / Infernal / Dread blade options. Also, even though "Tyranical Court" and "corrupr

**Comment by mykyl69** [comment]
"Corrupted Heirlooms" are not allowed to be taken by FW Knights. A FW Knight Warlord should be able to take.one other than restricted ones

**Comment by Mad-Spy** [comment]
Despoiler cost was fixed in the last release; please update your data.
FW Knights do not have the CHAOS KNIGHTS keyword which is required for them to qualify for all of the rules you mention. Until they get an FAQ, you can't use them.

**Comment by mykyl69** [comment]
Dear Mad-Spy. As per page 52 of chaos knight. Questoris Traitoris keyword gives iconoclast/infernal/dread blade keywords. All FW Knights have Questoris Traitoris

**Comment by MnG-SeventySix** [comment]
All my data files/application versions should be updated correctly if you can please check the link below 
in the image as well as being able to check the version of the files, I highlighted the part of the codex interested in my report and compared to the current data on the app file.
https://ibb.co/rsVPVzJ 

Thanks for your time =)

**Comment by Mad-Spy** [comment]
Thanks, but I have a copy of the Codex.

The cost for a Despoiler with Thunderstrike and Reaper is 372 points in v22 of the Chaos Knights data file which is the latest release.

@mykyl69, that is incorrect. Codex Knights have the `<QUESTOR TRAITORIS>` keyword which is replaced by either ICONOCLAST HOUSEHOLD or INFERNAL HOUSEHOLD when adding them to your army.

FW Knights have the `QUESTOR TRAITORIS` keyword which is not a placeholder (denoted by angle brackets) and therefore cannot be replaced. This disqualifies them from using any of the special rules in the Codex.
