### ISSUE TITLE
Chaos Knights - Dreadblade & Rune clash

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5330]
Chaos Knight detachments with a dreadblade with Pacts & Damnations are also able to take the Rune of Unpronounceable on another knight and get Pacts & Damnations without an error.

**Comment by Mad-Spy** [comment]
I'm not sure how you've done this. You should be getting a validation error for having More than one Pacts and Damnations?

Can you screenshot your list?

**Comment by gitGremlin** [comment]
I am getting a validation error for having more than one Pacts & Damnations, thats the bug.
What you can do is:
- Give two separate Knights Dreadblade
- Give one Knight Pacts & Damnations, as per normal
- Give the second Knight the Rune of Nak'T'Graa, giving him a 5++ and a Pact & Damnation

Battlescribe doesn't allow the rune to give P&D without throwing a validation error.

**Comment by gitGremlin** [comment]
What should happen is that you should now have two Dreadblade Knights:
- One with 1 Pact & 2 Damnations (assuming you picked all results)
- One with a 5++ relic and 1 Pact & 1 Damnation

You should also be able to give your normal Dreadblade that relic to allow just one model to have up to 3 Pacts and 3 Damnations, but I haven't tested this.

**Comment by Mad-Spy** [comment]
Right, I see. It wasn't clear from your original post that this was the issue. Giving one Dreadblade 3 Pacts/Damnations does work currently as that was my understanding of how the Rune works.

The two Dreadblades thing doesn't, but it makes sense. I'll sort it out.

**Comment by Mad-Spy** [comment]
Fixed in next release. The only way I could get it to validate correctly was to have a model with the Rune have an explicit check box to add the extra pact/damnation.
