### ISSUE TITLE
Chaos Knights - BRB Warlord Traits missing

### ISSUE THREAD

**Issue by spaceyjdjames** [BSData/wh40k#5331]
**File/Catalogue:** Chaos - Chaos Knights v22

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** When adding a character as a Warlord, Codex: Chaos Knights warlord traits are generated to select from, but not BRB generic traits.

**Comment by GenWilhelm** [comment]
Chaos Knights can't take warlord traits from the main rulebook:

![image](https://user-images.githubusercontent.com/22036809/61734713-672b0a00-ad7a-11e9-8d19-cdcb7406a98f.png)
~Codex: Chaos Knights p70

**Comment by spaceyjdjames** [comment]
Touche. Thanks!
