### ISSUE TITLE
Imperium - Questor Imperialis: New Forgeworld models and update

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5334]
**File:** Imperium - Questor Imperialis.catz

**BattleScribe version:** 2.02.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** new publication,  update to forge world models 
Armiger Moirax

Acastus Knight Asterius

review of datasheets
  
https://www.warhammer-community.com/wp-content/uploads/2019/07/Imperial_Knights_FW_Army_List.pdf

**Comment by williamcaw** [comment]
Knights have lost Flanking speed, and repair.

**Comment by DrTobogganMD** [comment]
Yep. I'll get things done.
