### ISSUE TITLE
Imperium - Astra Militarum: Tank Commander Turret Weapon Validation

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#5338]
**File/Catalogue:** Imperium - Astra Militarum v217

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Tank Commanders (including Pask) currently require one of each turret weapon, and come pre-selected with them.

**Comment by alphalas** [comment]
Closed by commit 65382af
