### ISSUE TITLE
Imperium - Imperial Knights: Armiger Moirax Weapon Validation

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#5339]
**File/Catalogue:** Imperium - Imperial Knights v38

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Armiger Moirax incorrectly give a validation error when selecting two of the same weapon.

**Comment by DrTobogganMD** [comment]
Yea. I know why. I'll fix it
