### ISSUE TITLE
DeathGuard: Not-Codex units Missing

### ISSUE THREAD

**Issue by LuXSmeck** [BSData/wh40k#5358]
**File/Catalogue:** 

Chaos - Death Guard v64

**BattleScribe version:** 

2.02.04  (Warhammer 40K 8th Ed v102)

**Platform:** 

Windows

**Dropbox:** 

No

**Description:** 

I have read the rules now again and again from the "new" Codexes and came to the point that you CAN give CSM that are NOT listed in the Main Codex the Keyword "DeathGuad" as Legion.

Why am I so sure? : 
- In the CSM Codex page 116: "The Death Guard, Thousand Sons and Fallen deviate significantly in terms of organisation and fighting styles. As a result, you cannot choose one of these keywords when determining which Legion a unit **in this codex is from**."

- This means that this rule is only valid for units from the Codex itself (and all units from the Index i think because they are nearly all in the codex).
BUT that rule is not valid for units outside of the codex!
As example we can have a look at the Index of Chaos ForgeWorld: the Hellforged Predator CAN get the Legin KeyWord replaced with DeathGuard as the newest Errata of the DG prooves. 
In the Errata they sais that you can use the Stratagem Killshot from the DG Codex only with an normal Predator and not a Hellforged one. This prooves that the Hellforged one has to had the DG Keyword otherwise he would have no access to the stratagems of the DG!

- What does this means? All of the Models that were released after the Codex: Lord Discordant; the ShadowSpear-models and the ForgeWorld-models are playable in a DeathGuad-Detachment.

Best Regards
LuX

Sources:
- CSM-Codex (vers. 2) page 116 p. 3 alignement 4
- DG-Errata from the official homepage (latest update 19/4/2019: 
https://www.warhammer-community.com/wp-content/uploads/2018/09/warhammer_40000_death_guard_en.pdf

**Comment by Mad-Spy** [comment]
The FW Index specifically lists the units which can replace `<LEGION>` with the `Death Guard` keyword in its update; it is not inferred from a tangential ruling in the Death Guard update.

However, the Shadowspear units and Lord Discordant are specifically Chaos Space Marine units, and as such follow the Codex rules unless otherwise ruled by GW.

**Comment by Mad-Spy** [comment]
Additionally, as someone has pointed out to me, those models *are* in the 2019 CSM Codex, so I think you may still be using the old Codex.
