### ISSUE TITLE
Imperium - Dark Angels: Mortis Dread missing Cyclone option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5364]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** The Mortis Dreadnought does not have an option to take a Cyclone Missile Launcher as per FW Index.

Cheers
HPM

**Comment by Mad-Spy** [comment]
Standard Mortis Dreadnoughts do not have an option for a Cyclone Missile Launcher. Only FW Contemptors get that option.

**Comment by HowardPierceMorgan** [comment]
Hi Mad-Spy … I'm looking at the Mortis Dread in the FW Index (2 pages before the Contemptor Mortis). Last option beneath all the weapons....I realise the kit ships with a Contemptor Head but you can take it on a Mk IV or V. I'm looking at the iBooks version which usually gets updated for errata.
