### ISSUE TITLE
Hq choice missing : mortarion

### ISSUE THREAD

**Issue by Burningfist123** [BSData/wh40k#5366]
**File/Catalogue:** Death Guard v64

**BattleScribe version:** 2.02.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 

hq choice daemon primarch mortarion missing

**Comment by alphalas** [comment]
Because Mortarion in isn’t an HQ, he’s a Lord of war
