### ISSUE TITLE
Chaos Knights -  Chaos Desecrator missing War Dog reroll ability

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5369]
The Knight that no one uses is missing his '6" War Dogs reroll 1s to hit' ability in his description.

**Comment by Mad-Spy** [comment]
You need to select an Allegiance for the ability to appear so that the correct keyword can be applied.
![image](https://user-images.githubusercontent.com/29306451/62499065-47173400-b7d9-11e9-9bc8-e0c839ef0953.png)
