### ISSUE TITLE
Blood Angels Repulsor Executioner

### ISSUE THREAD

**Issue by wmwhillman** [BSData/wh40k#5372]
**File/Catalogue:** 
Imperial - Blood Angels 
**BattleScribe version:** 2.02.
2.02.04
**Platform:** Windows/iOS/Android/Mac/Linux
IOS
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
Please add Repulsor Executioner to the Blood Angels Heavy support section. Thank you.

**Comment by Mad-Spy** [comment]
Duplicate of #5291

**Comment by wmwhillman** [comment]
Does closing it mean the vehicle is being added to the heavy support section? BA are eligible now. The Executioner has been already been added to DA/SW/DW/GK.

**Comment by chainw0** [comment]
Still missing in the battlescribe...
