### ISSUE TITLE
SM 2019 update

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k#5380]
8/20 - Update pushed, Issue Kept Open as reference catch and remaining to-dos

- [x] Combat doctrines validation???
- [x] Sort out Honor Guard
- [x] QA Testing

**Comment by williamcaw** [comment]
Quote Of the day. You got this.

**Comment by williamcaw** [comment]
Quote Of the day. Never bless a demon, it will only gain power from you if you   acknowledge it.

**Comment by fuckingenglish** [comment]
update psy powers

**Comment by williamcaw** [comment]
Quote Of the day. When all else Fails, take a break and relax with no internet connection.

**Comment by NiklasLeide** [comment]
Add Litanies?

**Comment by Davey-Jone-s** [comment]
Amazing work - thanks

**Comment by SpaceJS** [comment]
some of the existing datasheets also got new options. https://www.warhammer-community.com/wp-content/uploads/2019/08/warhammer_40000_space_marines_summer_update_en.pdf

**Comment by radionausea** [comment]
I don't know if this is an issue with the SM file or a Battlescribe issue. I'm not able to make a space marine list with more than two detachments. It gets stuck adding them forever. I waited 5 minutes and it still didn't add the third detachment.

**Comment by commnagrom** [comment]
Oculus Bolt Carbines on Incursors should be 0 points making the unit 19 ppm not 23, only the master crafted ones are 4 points, additional the eliminator sergeants have a prerequisite of bolt sniper rifles which is no longer required and infiltrators need to have max of 1 for helix adeptus or comms guys regardless of squad size, not 0 at 5man

**Comment by frohawk8337** [comment]
Looking good guys keep up the good work.
Did notice a few things.
-chaplain litanies are available for all chaplains (eg: terminator chaplain)

- special issue wargear not available (I assume new feature incoming since it's a new option)
