### ISSUE TITLE
Imperium - Space Marines: "Every"?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5383]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** #5233 #5380

https://www.merriam-webster.com/dictionary/every?utm_campaign=sd&utm_medium=serp&utm_source=jsonld

**Comment by GenWilhelm** [comment]
Not sure how the definition of the word "every" relates to publication references and the new Space Marines codex. Could you please be more specific?

**Comment by williamcaw** [comment]
I think this is part of the new release

**Comment by GenWilhelm** [comment]
That can't be it - the link they gave has the opposite definition:

>Definition of every
1a : being each individual or part of a group without exception
