### ISSUE TITLE
Beast of Nurgle wrong keywords

### ISSUE THREAD

**Issue by elodingens** [BSData/wh40k#5391]
**File/Catalogue:**  Warhammer 40,000 v1.3.17 Chaos - Daemons

**BattleScribe version:** v2.02.04.125

**Platform:** Windows

**Dropbox:** No

**Description:** Beast of Nurgle has in Battlescribe the following keywords: Beast, Faction: Daemon, **Flesh Hound**, **Faction: Khorne**, Elites, Faction: Chaos

It should have: Beast, Faction: Daemon, **Beast of Nurgle**, **Faction: Nurgle**, Elites, Faction: Chaos

**Comment by Guy-Markman** [comment]
Closes #5391
