### ISSUE TITLE
Space Marines Weapon Option points changes

### ISSUE THREAD

**Issue by aamck** [BSData/wh40k#5397]
**File/Catalogue:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.

**Platform:** All

**Dropbox:** No

**Description:** 

- Assault Bolters are now 8 points each, catalogue has them as 10 each.
- Dreadnaught Combat Weapon is now 20 points, catalogue has it at 30.
- Skyhammer Missle Launcher is now 20 points, catalogue has it at 24.

**Comment by JasonMWelch** [comment]
Along with the Assault Bolters, the base Inceptor cost changed to 31 points, currently at 25.

**Comment by WindstormSCR** [comment]
> 
> 
> Along with the Assault Bolters, the base Inceptor cost changed to 31 points, currently at 25.

https://puu.sh/E7zqJ/80df55b09a.png Please check before reporting, false information makes for more work.
