### ISSUE TITLE
Space Marines - Chaper Master Stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5398]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Android

**Dropbox:** No

**Description:** Chapter Master (2cp) strategem missing. Makes a captain a chapter master giving the appropriate keywords/abiliites (good rerolls). Provided there is not a chapter master in the army already

**Comment by WindstormSCR** [comment]
Will be added on release of Battlescribe 2.03 to stable.

**Comment by CORE461** [comment]
Noticed this was partially addressed in 2.03. However Captains in (various armors) do not have access yet.

(thank you for all the hard work)
