### ISSUE TITLE
Space Marines - Incursor Fixes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5403]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Android

**Dropbox:** No

**Description:** Space Marine Incursor squad are listed as 115 for five (23 points each).
The right cost is 95 (19 points each).

**Comment by Rasputinprime** [comment]
I'm going to guess the error is adding the cost of a Master Crafted Occulus bolt rifle (4 pts) to each model instead of the regular Occulus (0 pts)
