### ISSUE TITLE
Space Marines - Invictor Costing?

### ISSUE THREAD

**Issue by HBGryffin** [BSData/wh40k#5404]
**Imperium - Space Matines.catz:** 

**BattleScribe version:** 2.02.

**Platform:** Android

**Dropbox:** No

**Description:** Twin Ironhail Autocannon point cost listed as 0. Should be 20 points (Invictor Tactical Warsuit)

**Comment by JasonMWelch** [comment]
The Base cost of the Invictor is also off, it should be 90 +16 for the 3 weapons that can't be changed for a total of 106 not 116.

**Comment by HBGryffin** [comment]
I think the base is right. Or can the heavy bolter be exchanged?
90 
4 for fragstorm
10 for heavy bolter 
6 for each heavy stuber (12)
116

**Comment by JasonMWelch** [comment]
No, your correct, I kept leaving out the HB every time I calculated it.  My Bad.
