### ISSUE TITLE
[Bug] Space Marines - Ultramarines - Chief Librarian Tigurius unable to take correct amount of psychic powers

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5407]
**File/Catalogue:** Imperium - Space Marines v108

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Ultramarines Chief Librarian Tigurius should be able to take 3 psychic powers, but an error is thrown saying only a maximum of 2 can be taken:
![image](https://user-images.githubusercontent.com/36267768/63365372-7009fe00-c36f-11e9-967e-e358846f4539.png)

**Comment by WindstormSCR** [comment]
Duplicate of #5399
