### ISSUE TITLE
Space Marines - Eliminator Weapon Options on Sgt

### ISSUE THREAD

**Issue by STCTbone** [BSData/wh40k#5417]
**File/Catalogue:**  Imperium - Space Marines

**BattleScribe version:** 2.02.

**Platform:** Mac

**Dropbox:** Yes

**Description:** If the Instigator Bolt Carbine or Las Fusil is selected for an Eliminator Sergeant, you receive an `Eliminator Sergeant must have  1 more selections of Bolt sniper rifle (minimum 1 each)`, despite the other options being valid in the Codex.

**Comment by WindstormSCR** [comment]
Duplicate of #5400
