### ISSUE TITLE
Space Marines - Hero of the Chapter Strategem Missing

### ISSUE THREAD

**Issue by STCTbone** [BSData/wh40k#5418]
**File/Catalogue:** Imperium - Space Marines

**BattleScribe version:** 2.02.

**Platform:** Mac

**Dropbox:** Yes

**Description:** The Hero of the Chapter Strategem (1CP to give another character a warlord trait) is missing.

**Comment by WindstormSCR** [comment]
It's there, update your data.

**Comment by STCTbone** [comment]
Oops I was looking in the wrong place... sorry about that.
