### ISSUE TITLE
Space Marines - Chronus vehicle options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5433]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Sergeant Chronus lacks options to take non-Codex Space Marines vehicles. Namely, rules as stated that the list of vehicles he can use are listed as keywords:

RHINO
WHIRLWIND
RAZORBACK
PREDATOR
VINDICATOR
HUNTER
STALKER
LAND RAIDER

Codex Supplement: Ultramarines does NOT name any book restrictions for what he can take through this rule, so vehicles such as the Land Raider Achilles, Relic Whirlwind Scorpius, Deimos Pattern Relic Predator and the Deimos Pattern Vindicator Laser Destroyer are all available, as are the likes of the Land Raider Excelsior and the Rhino Primaris.

**Comment by WindstormSCR** [comment]
So, while this is a valid report, it may take some time to fix as it involves library files and cross-linking
