### ISSUE TITLE
Tyranids - Battlescribe crashes when attempting duplication

### ISSUE THREAD

**Issue by Jayton95** [BSData/wh40k#5456]
**File/Catalogue:** Tyranids

**BattleScribe version:** 2.02.04

**Platform:** Linux

**Dropbox:** No

**Description:** When adding a "Ripper Swarm" unit, double clicking to expand to "3x Ripper Swarm" and then clicking the "Duplicate selection (Ctrl + D)" button at the top the application freezes and I can no longer make changes to the roster (but thankfully can still save). A cursory look at the cmd line I run BS from shows a java exception, so it looks like this is undefined behaviour and the application has crashed.

**Comment by WindstormSCR** [comment]
please bug report here for the app itself: https://github.com/BattleScribe/Release/issues
