### ISSUE TITLE
Lieutenant in Phobos Armor - Error wargear options

### ISSUE THREAD

**Issue by nalcon** [BSData/wh40k#5473]
**File/Catalogue:** wh40k

**BattleScribe version:** v2.02.04.301

**Platform:** Android

**Dropbox:** No

**Description:** Grav-Chute throws error when Heavy Bolt Pistol and Combat Knife is selected as Weapon Option. When selecting this option Grav-Chute is replaced with Smoke Grenades plus associated effects, and gains keyword Reiver and effect Terror Troops.

Source is pg 115 Codex: Space Marines 2019

**Comment by nalcon** [comment]
Also missing paired combat blades when master-crafted occulus bolt rifle and bolt pistol is selected.

**Comment by WindstormSCR** [comment]
Duplicate Report
