### ISSUE TITLE
Imperium - Space Marines - Power Levels

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5477]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Power Levels are incorrect across a large number of units.  This seems to be something the community as a whole missed with the new Codex Space Marines Release.  Below are the non-named character PL changes that I can find:

Captain in Terminator Armor - Down to 6 PL from 7 PL
Captain in Cataphractii Armor - Down to 6 PL from 8 PL
Primaris Captain - Down to 5 PL from 6 PL
Captain in Phobos Armor - Down to 5 PL from 6 PL
Captain in Gravis Armour - Down to 6 PL from 7 PL
Lieutenants - Up to 5 PL from 4 PL
Primaris Lieutenants - Down to 4 PL from 5 PL
Librarian - Down to 5 PL from 6 PL
Librarian in Terminator Armor - Down to 6 PL from 9 PL
Primaris Librarian  - Down to 5 PL from 7 PL
Librarian in Phobos Armour - Down to 5 PL from 6 PL
Chaplain - Down to 4 PL from 5 PL
Chaplain in Terminator Armor - Down to 5 PL from 7 PL
Primaris Chaplain - Down to 4 PL from 6 PL
Tactical Squad - Down to 4 PL for the first 5, 3 PL for up to additional 5 from 5 PL for first five and 4 PL for up to additional 5.
Scout Squad  -  Down to 4 PL for the first 5, 3 PL for up to additional 5 from 6 PL for the first 5 and 4 PL for up tn an additional 5.
Primaris Apothecary - Down to 3 PL from 4 PL
Primaris Ancient  - Down to 4 PL from 5 PL
Ancient in Terminator Armour - 5PL, missing in update
Terminator Squad - Down to 9 PL from 12 PL, +9 PL for an additional 5, down from +12 PL for an additional 5
Terminator Assault Squad - Same changes as normal terminators
Cataphractii Terminator Squad - Down to 10 PL from 12 PL, +10 PL for additional 5, down from +12 PL for additional 5
Tartaros Terminators - Down to 9 PL from 13 PL, +9 PL for additional 5, down from 13 PL for additional 5
Vanguard Veterans  -  Down to 6 PL from 7 PL, +6 for additional 5, down from +7 for additional 5.
Sternguard Veterans - Same changes as Vanguard Veterans
Dreadnought - Down to 5 PL from 7 PL
Ironclad Dreadnought - Down to 7 PL from 8 PL
Venerable Dreadnought - Down to 6 PL from 8 PL
Contemptor Dreadnought - Down to 6 PL from 8 PL
Redemptor Dreadnought - Down to 7 PL from 10 PL
Reiver Squad - Down to 4 PL from 5 PL, +4 PL for additional 5, down from +5 PL for additional 5.
Aggressor Squad - Down to 5 PL from 6 PL, +5 PL for additional 3, down from +6 PL for additional 3.
Centurion Assault Squad - Down to 8 PL from 12 PL, +8 PL for additional 3, down from +12 PL for additional 3.
Bike Squad - Down to 4 PL from 5 PL, + 3 PL for three more bikes or plus +5 for 5 additional bikes.  +2 PL for attack bike.
Assault Squad - Down to 4 PL from 5 PL, +3 PL for additional 5 down from +4 PL for additional 5.
Inceptor Squad - Down to 7 PL from 10 PL, +7 PL for additional 3 from +10 PL for additional 3
Supressor Squad - Down to 4 PL from 5 PL
Scout Bike Squad - Down to 3 PL from 4 PL, +3 PL for 3 additional bikers or +6 PL for 6 additional bikers
Land Speeders - Down to 4 PL from 6 PL, +4 PL for each additonal speeder down from 6 PL per additional speeder
Attack bike squadron - Down to 2 PL from 3 PL, +2 for each additional attack bike
Devastator Squad - Down to 6 PL from 8 PL, additional devastators still +3 PL
Centurion Devastator Squad - Down to 12 PL from 19 PL, +12 for additional 3 from +19 for additional 3
Hellblaster Squad - Down to 6 PL from 8 PL, +6 PL for additional 5, down from +8 PL for additional 5
Eliminator Squad - Up to 4 PL from 3 PL
Thunderfire Cannon - Down to 4 PL from 6 PL
Hunter - Down to 4 PL from 5 PL
Stalker - Down to 5 PL from 4 PL
Whirlwind - Down to 4 PL from 5 PL
Predator - Down to 8 PL from 9 PL
Vindicator - Down to 6 PL from 7 PL
Land Raider - Down to 15 PL from 19 PL
Land Raider Crusader - Down to 14 PL from 16 PL
Land Raider Redeemer - Down to 14 PL from 18 PL
Rhino - Down to 3 PL from 4 PL
Drop Pod - Down to 3 PL from 5 PL
Land Speeder Storm - Down to 3 PL from 5 PL
Repulsor - Down to 15 PL from 16 PL
Stormhawk Interceptor - Down to 9 PL from 10 PL
Stormtalon Gunship - Down to 8 PL from 9 PL

**Comment by Zaanzabar** [comment]
This issue is still not fixed.
Verified units:  Chaplain, Land Speeder, and Predator still wrong.  Did not check others yet.

**Comment by amis92** [comment]
@Zaanzabar please raise this in a separate issue.
