### ISSUE TITLE
Space Marine - Primaris Chaplain doesn't have Litanies of Battle option

### ISSUE THREAD

**Issue by gungagreg** [BSData/wh40k#5479]
**File/Catalogue:** Warhammer 40K v1.3.19

**BattleScribe version:** 2.02.04125 (windows) and 2.02.05 (iOS)

**Platform:** Windows/iOS

**Description:** The Primaris Chaplain battlescribe entry lacks the option to choose a Litany of Battle like the other Chaplains have had added.  
![Primaris Chaplain Rules](https://user-images.githubusercontent.com/18035407/63544708-9ef0b300-c4da-11e9-81ab-562d24cb6881.jpg)

**Comment by WindstormSCR** [comment]
Duplicate Report
