### ISSUE TITLE
Imperium - Blood Angels: Incorrect Strength for Bolt-sniper rifles

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5480]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** Strength values for Eliminator Bolt-Sniper Rifles are incorrect in Blood Angels data file v1.3.19 dated Aug 21 2019.
Data has it as 4 strength, but the FAQ update for Blood Angels has it as 5 strength

**Comment by Dimitri1282** [comment]
Also aggressors need +1 to their attacks
