### ISSUE TITLE
Space Marines - Terminator Assault Squad has incorrect Power Level costs

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5483]
**File/Catalogue:** Imperium - Space Marines v110

**BattleScribe version:** 2.03.00

**Platform:** Windows

**Dropbox:** No

**Description:** Terminator Assault Squad has the following incorrect power levels:

- 5 models - Currently 12 Power Level; should be 9 Power Level.
- 6-10 models - Currently 24 Power Level; should be 18 Power Level.

**Comment by WindstormSCR** [comment]
Duplicate of #5477
