### ISSUE TITLE
Unorganized units in CSM

### ISSUE THREAD

**Issue by urbankuriboh** [BSData/wh40k#5494]
**File/Catalogue:** CSM

**BattleScribe version:** 2.02.

**Platform:** Android (though may Appear on all)

**Dropbox:** No

**Description:** In the CSM catalogue the units Rubric Marines and Lord Arkos are not in their respective categories but in a separate one called unorganized (This occurred regardless of which legion was chosen obviously excluding ones where those units are not available to the legion e.g. world eaters and emps children)
![Screenshot_20190823-102850](https://user-images.githubusercontent.com/54436662/63582344-d4f06e80-c590-11e9-93a1-37b6b2514332.jpg)
![Screenshot_20190823-103100](https://user-images.githubusercontent.com/54436662/63582511-200a8180-c591-11e9-818e-80d088817803.jpg)

**Comment by Mad-Spy** [comment]
Covered by #5496
