### ISSUE TITLE
Imperium - Space Marines: Inceptor Sgt wargear options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5503]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Inceptor Sergeant has no weapons options available to select resulting in incorrect points cost for unit.

**Comment by WindstormSCR** [comment]
You need to double check your math
