### ISSUE TITLE
Beasts of Nurgle - Wrong Keyword

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#5505]
**File/Catalogue:** Chaos - Demons

**BattleScribe version:** 2.02.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:**
Beasts of Nurgle have the Faction: Khorne and Flesh Hounds keywords

**Comment by Mad-Spy** [comment]
Duplicate of #5391. Already fixed.
