### ISSUE TITLE
Orks: Da Souped Up Shokka is available to the Index Big Mek (who cannot take a Shokk Attack Gun)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5529]
**File:** Orks.catz

**BattleScribe version:** 2.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Orks - HQ - Big Mek - what used to be (a week ago) “Big Mek with Shock attack gun (SAG)”  with the relic Da souped up Shokka (selected hq in the roaster) is now simple “Big Mek” with the relic Da souped up Shokka but withou shock attack gun - ordinary Big Mek does not have a SAG option, the BM with SAG have to be chosen. So it means, my HQ is 25 points cheaper, but againts the rules, because the ordinary sag is missing, big mek has “just” the upgrade

**Comment by Mad-Spy** [comment]
Mad-Spy: For clarity, the issue here is that an Index Big Mek, who cannot select a Shokk Attack Gun, is incorrectly able to select "Da Souped-Up Shokka" relic without a validation error.
