### ISSUE TITLE
Chaos - Chaos Space Marines: Marine Heavy/Special weapon validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5546]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** No

**Description:** Issue:
I have an error 'Chaos Space Marines has 1 too many selections of Marine w/Heavy or Special Weapon (maximum 1)', while datasheet says that 'If the unit numbers ten or more models, an additional Chaos Space Marine may take one item from the Special Weapons or Heavy Weapons lists.'

My squad has Aspiring Champion, 6 Marines/Chainsword, 1 Marine/Plasma pistorl, 1 Marine/Heavy bolter, 1 Marine/Plasma gun (10 total)
Adding more normal marines doesn't help.

Fix:
Allow 2 Heavy/Special marines when model number is >9

Data version:
Chaos-Chaos Space Marines v106

**Comment by Mad-Spy** [comment]
You've missed the previous bullet point which says that you can either have a Heavy/Special OR a plasma pistol.

Thus you cannot have both a plasma pistol AND two Heavy/Special Weapons even in a 10 man squad.

![image](https://user-images.githubusercontent.com/29306451/63757953-e8fadf80-c8b2-11e9-8176-2b73b9064cf1.png)
