### ISSUE TITLE
Imperium - Space Marines: Validation error when giving Primaris Captain a power sword

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5565]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** Select "Primaris Captain" as HQ selection for a Space Marine detachment. Equip him with power sword (first checkbox). 
Error will be "Primaris Captain has 1 too many selections of Power sword (maximum 0)"

The default model from GW has equiped bolter and power sword - this is not possible in the current data repository.

Data is Warhammer 40K 1.3.21 (26th of august)

**Comment by Mad-Spy** [comment]
Unable to reproduce in Marines v115. This will be in the next release.
