### ISSUE TITLE
Tyranids - Genestealer Cults: Webber cost is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5574]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.03.01

**Platform:** Mac

**Dropbox:** No

**Description:** Neophyte Hybrid Weapon options shows Webber is listed at 6 points each but should be 1 point

**Comment by Mad-Spy** [comment]
You are paying for both the Hybrid AND his Webber.
