### ISSUE TITLE
Imperium - Space Marines: Captain Sicarius adjustments

### ISSUE THREAD

**Issue by jfries85** [BSData/wh40k#5577]
**File/Catalogue:** Imperium/Space Marines v113

**BattleScribe version:** 2.03.00

**Platform:** iOS

**Description:**
-Captain Sicarius' cost needs to be adjusted down from 110 > 100. Power level down from 7 > 5  
-His plasma pistol needs to be changed to "_Artisan plasma pistol_" with a profile of [Range-12", Pistol 1, S8/AP-3/D2 (no supercharge profile, no 'gets hot' )
-His abilities changed _Battle-forged Heroes_ to "_At the start of the battle-round, you can select one friendly ULTRAMARINES unit within 6" of this model. Until the end of the battle round, that unit has the Defenders of Humanity ability._" 
-Other adjustments needed: Currently Warlord is selectable, but no Warlord traits are. He also needs to access Relics.

**Comment by Mad-Spy** [comment]
He doesn't get to pick a Trait or take a Relic because he's a named character. Your other points are valid though.

**Comment by jfries85** [comment]
Oh. Thanks for clearing up the traits and relic. Not sure how I missed that.
