### ISSUE TITLE
Daedalosus Missing from Ad-Mech

### ISSUE THREAD

**Issue by noobzilla99** [BSData/wh40k#5579]
**File/Catalogue:** AdeptusMechanicusv60

**BattleScribe version:** 2.03.01

**Platform:** iOS

**Dropbox:** No

**Description:** When trying to add Daedalosus to an Ad-Mech list, he cannot be added / seen in the HQ section (or any section).  His entry / code is in the data file, but he isn't visible.

![IMG_4459](https://user-images.githubusercontent.com/16530180/63949665-59833700-ca40-11e9-90b9-80340c06aeed.JPG)

Example of Ad-Mech v.60 catalogue where he does not show up as an HQ Choice.

**Comment by Mad-Spy** [comment]
None of the Escalation characters have been added to any catalogues yet. I've raised #5580 to cover adding them once someone has the datasheets.

**Comment by noobzilla99** [comment]
> None of the Escalation characters have been added to any catalogues yet. I've raised #5580 to cover adding them once someone has the datasheets.

That's not true, X-101 was added, and Daedalosus is already in the datafile.  I read through it and saw it.

X-101 is an option in V60
![IMG_4460](https://user-images.githubusercontent.com/16530180/63954809-52acf200-ca49-11e9-8c5e-eb9dca1ec5e4.JPG)

Daedalosus is in the file:
![IMG_4461](https://user-images.githubusercontent.com/16530180/63955024-acadb780-ca49-11e9-942e-4056790c0750.JPG)

Daedalosus profile is added.
![IMG_4462](https://user-images.githubusercontent.com/16530180/63955025-acadb780-ca49-11e9-9da3-3701afbdbf19.JPG)

Which indicates there is a different problem with the file... e.g. he is not showing when he should be.

**Comment by Thairne** [comment]
That is simply because I started implementing them, added a link to check if they validate and forgot to delete the rootlink for X-101 again.
However, with the next release Daedalosus and X-101 will be there with the correct rules.
