### ISSUE TITLE
Add Characters from BSF: Escalation

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#5580]
Need to find data sheets and add units.

**Comment by Mad-Spy** [comment]
Found all except Firebrand: https://imgur.com/a/Wcz8clo

**Comment by noobzilla99** [comment]
I don't know if you will see my reply on the closed topic, so I'm putting it here for redundancy just so its seen.

> None of the Escalation characters have been added to any catalogues yet. I've raised #5580 to cover adding them once someone has the datasheets.

X-101 was added, and Daedalosus is already in the datafile.  I looked through it and saw it.

X-101 is an option in V60
![IMG_4460](https://user-images.githubusercontent.com/16530180/63954809-52acf200-ca49-11e9-8c5e-eb9dca1ec5e4.JPG)

Daedalosus is in the file:
![IMG_4461](https://user-images.githubusercontent.com/16530180/63955024-acadb780-ca49-11e9-942e-4056790c0750.JPG)

Daedalosus profile is added.
![IMG_4462](https://user-images.githubusercontent.com/16530180/63955025-acadb780-ca49-11e9-9da3-3701afbdbf19.JPG)

Which indicates there is a different problem with the file... e.g. he is not showing when he should be.

**Comment by Mad-Spy** [comment]
Those two were added from leaks, and shouldn't have been made visible. The proper versions will be in the next release.

**Comment by Thairne** [comment]
That is simply because I started implementing them, added a link to check if they validate and forgot to delete the rootlink for X-101 again.
Neither X-101 nor Daedalosus were supposed to be selectable in a list at that point.
However, with the next release Daedalosus and X-101 will be there with the correct rules.

**Comment by Mad-Spy** [comment]
All added except Firebrand as I can't find the datasheet anywhere.
