### ISSUE TITLE
Imperium - Adeptus Custodes: FW Datasheets Update

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#5582]
https://www.forgeworld.co.uk/resources/PDF/fw_warscrolls/40K_Adeptus_Custodes_FW_Datasheets_Ares.pdf

NB - no longer beta.

**Comment by WindstormSCR** [comment]
Update complete in Custodes v35

**Comment by natecross1990** [comment]
So how long after this being updated should it take for Battlescribe to have v35? Just curious... and itching to rewrite my lists with Sagitarrum as Troops choices :D

**Comment by GenWilhelm** [comment]
Anywhere from a couple of hours to a couple of days, depending on how cooperative appspot is feeling.

**Comment by natecross1990** [comment]
Aha fair play, you guys are spot on with how quickly you update/fix things, thanks for being awesome
