### ISSUE TITLE
Imperium - Adeptus Custodes: Validation error with Custodes Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5585]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** after creating a list for a friend and using the open the vaults stratagems to recreate the list . it no longer allows me to give 1 relic for free and is saying it needs to have relic of terra. but when i do so it produced  you have to many selections of relic of terra (maximum 0)

have reset and logged bat file might be from app it self .

**Comment by WindstormSCR** [comment]
You only get a free relic if the warlord is from that faction.
