### ISSUE TITLE
Imperium - Space Wolves: Various issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5591]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** -Intercessor pack leader missing thunder hammer option
-Incursor squad paired combat blades, has a completely different abil written in, it doesnt ignore cover saves lol (melle weapon)
-Inceptor assault bolters are now 8pts down from 10 pts please fix.
-invictorTactical warsuit has it wound track profile mixed up. 9minor but still anoying no the less
-All characters still have thunder hammers as 21pts instead of 40pts.
thank you and the community keep up the good work!

**Comment by TheGreatSquark** [comment]
The Thunder hammer and Assault Bolter changes are not part of the Space Wolves codex until GW errata's them in. Until such time, they are only for Codex: Space Marines.
