### ISSUE TITLE
Orks: Ruckatrukk Squigbuggy missing profiles for Squig Launcha

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5596]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** No

**Description:** In tbe orks roster the rukktruck squiggbuggy only lists the weapons for the heavy squig launcher, is missing thebregular squig pauncher thats also on it. Only reference to the regular squig launcher is in the weapons list, but I believe it gets less shots.

**Comment by Mad-Spy** [comment]
Looks like both weapons are using the same profiles, but they should be different.

**Comment by Guy-Markman** [comment]
Fixed in #5603
