### ISSUE TITLE
Chaos (Chaos Space Marines & FW Heretic Astartes)

### ISSUE THREAD

**Issue by anticitizen013** [BSData/wh40k#560]
**File/Catalogue:** Chaos - Chaos Space Marines.catz & Chaos - FW Heretic Astartes.catz (Catalogue version 1.0.19)

**BattleScribe version:** v2.01.03.90

**Platform:** Windows & Android

**Dropbox:** Yes

**Description:** 
- [x] Chaos Space Marines: Maulerfiends incorrectly given the ability: Teleport strike. 
- [x] FW Heretic Astartes: Chaos Decimator incorrect base point value. Also, adding two of the same weapon doesn't add the price twice (eg a Chaos Decimator with 2 Soulburner Petards shows as 102 points when in fact it should be 150).

**Comment by cartag** [comment]
Sub-detachments are currently not calculating points properly, it's a BS bug.
