### ISSUE TITLE
Imperium - Space Marines: A few missing options for relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5607]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** Company Champion Doesn't have the Shield Relic as an option but should
Lieutenant in Phobos Armour can't take Purgatorus Relic if Heavy Bolt Pistol & Combat Knife weapon set is selected.  Purgatorus can replace either a regular or Heavy Bolt Pistol.
Librarian in Terminator Armor should be spelled Armour (Missing U).  Maybe shouldn't have access to Storm Shield post-FAQ?

**Comment by frohawk8337** [comment]
Terminator ancient also does not have access to the banner of the emperor ascendant
