### ISSUE TITLE
Imperium - Blood Angels: Bolt sniper round profiles not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5614]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** The profile of each of the eliminators bolt sniper rifle rounds has not been updated to match the changes in the space marine summer update

**Comment by Mad-Spy** [comment]
Duplicate of #5480
