### ISSUE TITLE
Imperium - Space Marines: Captain in Gravis Armor PL incorrect

### ISSUE THREAD

**Issue by abust005** [BSData/wh40k#5618]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** PL for Space Marine Captain in Gravis Armor listed as 6, datasheet says 8.

**Comment by Mad-Spy** [comment]
It was reduced in the new Codex.
