### ISSUE TITLE
Imperium - Space Wolves: Psychic powers for Phobos Librarian

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5622]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** File version 92.
Librarian in Phobos Armour - is showing the Obscuration Discipline details from the Shadowspear supplement, but the Space Marines Summer Update, under the Space Wolves entry states - 'Change the final sentence of its Psyker ability to read: ‘It knows Smite and two psychic powers from the Obscuration discipline (see Codex: Space Marines) or two psychic powers from the Tempestas discipline (see Codex: Space Wolves) .'  There are several differences between the two lists.

**Comment by Mad-Spy** [comment]
This is fixed in the current release version.
