### ISSUE TITLE
Ynnari - Hungering Blade incorrectly available for Succubus HQ

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k#5629]
**File/Catalogue:** Drukhari v52

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Description:** The "Hungering Blade" Ynnari relic is available as a choice to Succubus HQ models, this is invalid as the Hungering Blade can only replace a "power sword, star glaive or huskblade" - none of which the Succubus has.

**Comment by Mad-Spy** [comment]
There is no Relic called "The Hungering Blade", and Succubi do not appear to have access to any Relics they should not have.
