### ISSUE TITLE
Fallen - Cypher as Warlord

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#5639]
Cypher, while he cannot be given a WARLORD TRAIT, can be selected as the WARLORD, but doing so should lock you out of getting relics when spending CP.
Currently, Cypher cannot be made into the Warlord.

**Comment by Mad-Spy** [comment]
Closing due to lack of response.

**Comment by gitGremlin** [comment]
Sorry, I have been on holiday.
@Mad-Spy -- the bug is that you should be able to set Cypher as your Warlord (but you can't).
The relics thing was me predicting a future bug.
