### ISSUE TITLE
Imperium - Space Marines: Exemplar of the Chapter should cost 1CP

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5645]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** Hi. The stratagem "Exemplar of the Chapter" is set for "(no cost)" but it as a cost di -1 CP.

**Comment by WindstormSCR** [comment]
duplicate of #5594
