### ISSUE TITLE
Typhoon Missile Launcher Cost

### ISSUE THREAD

**Issue by Whiteraven15** [BSData/wh40k#5646]
**File/Catalogue:* Space Marine.catz

**BattleScribe version:** 2.03.01.128

**Platform:** Windows

**Dropbox:** No

**Description:** The typhoon missile launcher is incorrectly costed in the Windows version of the files (38pts should be 32pts). Correctly costed in the Mobile version though.

**Comment by Mad-Spy** [comment]
It's the same data, so make sure they are both on the same version.
