### ISSUE TITLE
Imperium - Space Marines: Captain should be able to take Relic blade and Storm shield

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5649]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** In the Captain entry it's not possible to select both a Relic Blade AND a Strom Shield even though this combination is allowed by the codex do to this FAQ:
Q: Can a Captain replace his master-crafted boltgun with a
chainsword, then replace that chainsword with a storm shield?
A: Yes, because these wargear options are two
separate bullet points (you cannot choose the same
bullet-pointed wargear option for a unit more than
once, however).

So:  master-crafted boltgun ---> chainsword ---> storm shield
AND
chainsword ---> relic blade

**Comment by WindstormSCR** [comment]
this is considerably more difficult to fix than it may at first appear. and may take some experimentation.
