### ISSUE TITLE
Imperium - Space Marines: Thunderfire Cannon not in bold

### ISSUE THREAD

**Issue by liftedlimo** [BSData/wh40k#5652]
Thunderfire Cannon entry is not in bold as well as the Gunner sub selections.

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by BaconCatBug** [comment]
Same for Suppressors

**Comment by WindstormSCR** [comment]
Entries are only bolded if they have relevant sub-selections. suppressors are fixed wargear and fixed squad number, so there is no sub-selection to change.
