### ISSUE TITLE
Imperium - Dark Angels: Ravenwing Land Speeders cause Fast Attack validation to fail

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5660]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When using Fast Attack choices in a battalion when you select the third fast attack choice it brings up a warning saying you can’t select more than three fast attack choices

**Comment by Mad-Spy** [comment]
Both the unit and the models have the Fast Attack keyword, so the validation gets tripped incorrectly.
