### ISSUE TITLE
Imperium - Space Marines: Victrix Honour Guard missing Angels of Death rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5664]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** Victrix honour guard do not show Angel's of death. And adding Sergeant Chronus to a terminus ultra for matched play is a bit tricky.

**Comment by Mad-Spy** [comment]
The Land Raider Terminus Ultra is not valid for Matched Play; you can only take one in Open Play.
