### ISSUE TITLE
Imperium - Space Marines: Relics of the Chapter not working

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k#5665]
**BattleScribe version:** 2.03.03

**Platform:** Android

**Description:** 
After update to Space Marines v116, Relics of the Chapter do not increase the number of relics allowed for the detachment (ie batallion with 3 HQ, one warlord, one relic for everyone and with two 'Relics of the Chapter' selected shows 'has 2 too many selections for Chapter Relics (maximum 1)'

**Comment by Mad-Spy** [comment]
This sounds correct; unless one of your Models is the Warlord you can only take 2 Relics in the situation you have described above?

**Comment by gluck3d** [comment]
> This sounds correct; unless one of your Models is the Warlord you are only permitted to take 2 Relics in the situation you have described above?

Yeah, I mean one is warlord as well, so I expect 3 relics to be allowed. Even  if not, it shows max number of relics=1 (instead of 2 if stratagems would be applied)

**Comment by gluck3d** [comment]
Exact steps:
1) Create new batalion
2) Assign it to Ultramarines
3) Add 3 Captains
4) Add 2 Relics of the Chapter stratagems to the detachment
5) Mark first one as Warlord and give him for ex Purgatorous
6) Give second Captain Reliquary
7) Give third one Armoour Indomites
Check alerts - it still has 'too many relics 3 instead of max 1'

**Comment by GenWilhelm** [comment]
There's an additional selection under Relics of the Chapter for how many extra relics you want. It currently defaults to 0, which is why it still thinks you have too many relics.

Perhaps it should default to 1 instead?

**Comment by gluck3d** [comment]
Ah, that is what has changed, right. Yep, probably should be set to default 1 and may be removed an option to add multiple ones as it is confusing?
Can't check how it behave in previous version, but I'm sure I never clicked on it,, so it was adding one relic by default and removing 1 CP
