### ISSUE TITLE
Imperium - Space Marines: Chronus should be able to ride in a Land Raider Variant in Open Play

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#5666]
As per summary, Chronus should be able to ride in a Variant Land Raider if you are playing under Open Play.

**Comment by Mad-Spy** [comment]
Also, should he still be able to go in a "Terminus Ultra" in his list of options? I didn't think it was a Matched Play model any more.

**Comment by MrRWJP** [comment]
> Also, should he still be able to go in a "Terminus Ultra" in his list of options for Matched Play? I didn't think it was a Matched Play model any more.

The Terminus Ultra still has a datasheet from Index: Imperium 1 so should still be available for Matched Play unless GW have specifically said otherwise.

**Comment by Mad-Spy** [comment]
@MrRWJP, I think that sheet has been superseded by the Open Play only sheet from Chapter Approved 2017, which is possibly where the oversight of still having it in Chronus' list has come from.

There's no longer a separate Terminus Ultra LoW option in the catalogue, which is why I'm pretty sure it's an oversight.
