### ISSUE TITLE
Orks: Tank Hunters ability text incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5669]
**File:** Orks.catz

**BattleScribe version:** 2.03.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Tank Hunters ability on the Tankbustas should be “reroll hit rolls” not “reroll failed hit rolls”.

**Comment by Guy-Markman** [comment]
Fixed in #5683
