### ISSUE TITLE
Chaos - Questor Traitoris: Missing relic

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5670]
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** Relic within the Chaos Knights codex is missing from the battlescribe list. 
Relic Name: The Blasphemous Engine
Description: Infernal Household model only (other than a Dreadblade model). A model with this Relic is considered to have double the number of wounds remaining for the purposes of determining what row to use on it's damage table.

Knight in list is listed as being Infernal household allegiance but this relic does not show as an available relic, even though the corrupted heirlooms trait has been selected on the force org section.

**Comment by Mad-Spy** [comment]
Are you missing the entire Relic selection, or just that one Relic? 

I am unable to replicate this as long as the model is marked as INFERNAL HOUSEHOLD and has the "Corrupted Heirloom" option checked on the model itself.

There _is_ an issue that the FW Knights currently can't be selected to be the recipient of a Corrupted Heirloom which I will fix.

**Comment by Mad-Spy** [comment]
Closing as I am unable to replicate this issue without more details.
