### ISSUE TITLE
Imperium - Blood Angels: Malakim Phoros should be in the BA catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5671]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** When FW units were incorporated into the main file it looks like FW entry for malakim phoros was removed and moved to the codex compliant file instead.

**Comment by Mad-Spy** [comment]
@WindstormSCR , Phoros/Lamenters should probably come out of the SM catalogue entirely as they are very definitely a BA successor.
