### ISSUE TITLE
Blood Angels  Relic Leviathan Dreadnought, Chest weapon options missing

### ISSUE THREAD

**Issue by Chikara72** [BSData/wh40k#5674]
Warhammer 40,000 v1.3.23

**BattleScribe version:** 2.03.01

**Platform:** Windows 10

**Dropbox:** yes

Leviathan Dreadnought only has the heavy flamer chest option, should also have Volkite Calivers and Autocannons.

**Comment by Mad-Spy** [comment]
None of those things are options on the datasheet for this model (p30 of Imperial Armour - Index - Forces of the Adeptus Astartes). What is your source for this?

**Comment by Chikara72** [comment]
The Forge World website states:” The Leviathan pattern Siege Dreadnought is a multi-part resin kit. It includes optional torso mounted heavy flamers and volkite calivers”
Also for the Blood Angels version it states:”  including - unique to the Blood Angels Leviathan Dreadnought - chest-mounted assault cannons”

https://www.forgeworld.co.uk/en-AU/Blood-Angels-Leviathan-Dreadnought-2018
https://www.forgeworld.co.uk/en-AU/Leviathan-Pattern-Siege-Dreadnought-Body
Cheers.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by alphalas** [comment]
Those options are options for the 30k version only; unless you can show me a data sheet that includes those as options they will not be added. 

And as an additional point to drive this home; the listing for the leviathan Dreadnought says it includes a volkite discharger; the sheet for the leviathan Dreadnought in the index does not include a volkite discharger, instead having the option for hunter killer missiles instead.
