### ISSUE TITLE
Chaos - Death Guard: Plague Marine Champion has no weapon options from Codex

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k#5677]
**BattleScribe version:** 2.03.03

**Platform:** Android

**Description:** 
Death Guard v67 pack doesn't have Plague Marine Champion options from codex:
To change his boltgun to bolt pistol/plasma pistol/plasma gun
To take power fist.
To replace plague knife with plaguesword

*I was able to spot that prior to refreshing, my champion had powerfist/plasma gun selected. So it seems this options are now lost.

**Comment by Mad-Spy** [comment]
Yes it does. You need to drill down into the Codex/Index option after selecting it. Items with sub-selections are denoted by orange colouring on the little tab on the left side.

It's been like this for a long while, so your roster must be quite old.

**Comment by gluck3d** [comment]
Sorry, I was quite sure I've clicked everywhere on this options and suddenly it started to work.
Apologies, not sure what it was.
