### ISSUE TITLE
Marksman's Honours has not been updated to new version

### ISSUE THREAD

**Issue by dode74** [BSData/wh40k#5684]
**File/Catalogue:Space Marines 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes

**Description:** Marksmans' Honours has changed in the new codex and now reads:
"Add 1 to the Damage characteristic of ranged weapons this
Warlord is equipped with. This does not apply to Grenades
or Relics."

Source: Codex: Space Marines page 178

**Comment by Mad-Spy** [comment]
Duplicate of #5632

**Comment by dode74** [comment]
This is not a duplicate of #5632 - that one references a typo in the old version, this references the changed version in SM19.
