### ISSUE TITLE
Lieutenant in Phobos armour - Two issues 

### ISSUE THREAD

**Issue by TJ-paints-and-games** [BSData/wh40k#5691]
Warhammer 40,000 v 1.3.23

For Imperium - Space marines, if you select the Primaris Lieutenant with Phobos armour, and wargear option of Heavy Bolt Pistol, Combat Knife and Smoke Grenades, it does not produce the Terror Troops rule. 

Also tested in Blood Angels, same result.

~~In addition, there is no option for the above wargear in Wolf Guard battle leader in Phobos armour, for Space wolves.~~

~~(Apologies in advance if it should have been two posts)~~
Moved to #5695 

Thanks for all your hard work!

**Comment by TJ-paints-and-games** [comment]
Thanks for splitting this.
Should have mentioned that I haven't tested this for Dark Angels,

**Comment by Mad-Spy** [comment]
Not fixed in v119. Needs looking at again.
