### ISSUE TITLE
Dark Angels Jump Packs do not confer fly.

### ISSUE THREAD

**Issue by TonyPeterLong** [BSData/wh40k#5693]
**File/Catalogue:** Imperium - Dark Angels v106

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes/No

**Description:** Equipping an _Assault Squad_ with _Jump Pack_ does not confer the **fly** keyword on that unit.

**Comment by Mad-Spy** [comment]
The current release version of DA is v110 and it is fine in that version. Please update your data.
