### ISSUE TITLE
Supletemnto Raven Guard

### ISSUE THREAD

**Issue by javito55** [BSData/wh40k#5701]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

En la app para android . no aparece aun las opciones  de la reven guard y valores del señor del capituloa

In the app for android, the options of the reven guard and values of the lord of the chapter do not appear yet.

excuse me english use google translator

**Comment by Mad-Spy** [comment]
They were released today, so please make sure you've updated your data to v1.3.24.

Se lanzaron hoy, así que asegúrese de haber actualizado sus datos a v1.3.24.

**Comment by javito55** [comment]
Thank you! it works OK
