### ISSUE TITLE
Space Marines: Iron Hands - Stratagems "March of the Ancients" would be useful

### ISSUE THREAD

**Issue by onlyamonth** [BSData/wh40k#5702]
**File/Catalogue:** Space Marines: Iron Hands

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** The Iron Hands stratagem "March of the Ancients" allows you to select a <Dreadnought> unit to become a character, which then allows it to gain a warlord trait via Hero of the Chapter, and paragon lets it then have an additional warlord trait from the IH trait list. I cannot see a way to enable this stratagem on, for example, Elites -> Dreadnought.

It would be very helpful, but I understand it's a bit of a complex rule!

**Comment by WindstormSCR** [comment]
It's not the complexity that is the problem, more so that duplicating the warlord traits tables to another 8+ units would definitely cause issues on low memory devices. The entire SM file is being reworked to reduce impacts, and once complete March will be in there.

**Comment by onlyamonth** [comment]
> It's not the complexity that is the problem...

Massively appreciate the reply and all the work that is going into the data :) Thank you!

**Comment by toadchild** [comment]
I'd also like to use this functionality, and look forward to the future updates.

I just wanted to note that you can't nominate the dreadnought you select for March of the Ancients as your warlord - the stratagem says that it is used "before the battle, after nominating a model to be your Warlord".

You can still use the generic SM stratagem "hero of the chapter" to give it a warlord trait, though.

**Comment by toadchild** [comment]
The FAQ contradicts me - I forgot that you're allowed to nominate _any_ unit as warlord, not just a character.

Q: If I nominate an Iron Hands Dreadnought to be my Warlord and I then use the March of the Ancients Stratagem for that Dreadnought to gain the Character keyword, can it now have a Warlord Trait?
A: Yes.

**Comment by Shiney1965** [comment]
A related bug is that Battlescribe does not allow you to nominate any unit as your Warlord, only a character.  I think this is a general issue with Space Marines (at least), but I only noticed this with Iron Hands because the Dreadnought stratagem caused me to want to nominate a non-character.  Perhaps this will be fixed in the upcoming overhaul?  Thanks to all for their work on this!
