### ISSUE TITLE
Space Marines - Chaplain Venerable Dreadnought cannot use stratagems to take a second Warlord trait

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5704]
**File/Catalogue:** Space Marines v117

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** If a Chaplain Venerable Dreadnought is taken as your Warlord, it cannot use the following supplements stratagems to take a second Warlord trait:
- Tempered by Wisdom (White Scars)
- Exemplar of the Chapter (Ultramarines)
- Master of the Trifold Path (Raven Guard)
- Paragon of Iron (Iron Hands)

**Comment by Mad-Spy** [comment]
Partially fixed by #5718, for UM and IH.
