### ISSUE TITLE
Imperium - Space Marines: Phobos Librarian shouldn't have Librarius

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#5706]
**File/Catalogue:** Imperium - Space Marines

**BattleScribe version:** 2.03.01

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**
The Phobos Librarian should only have access to the Obscuration discipline, and possibly a chapter-specific discipline.  Battlescribe additionally shows the Librarius list, which is incorrect.

**Comment by williamcaw** [comment]
Release 2 states yes for access to the Disciplines. This also includes chapter selected powers when chapter is selected.

**Comment by toadchild** [comment]
William, unless there is an update I missed, a "normal" librarian can't access Obscuration, and a vanguard/phobos librarian can't access Librarius.  Both can use the subfaction discipline if you have one.

**Comment by toadchild** [comment]
![phobos](https://user-images.githubusercontent.com/1512358/66154867-4af5e580-e5d3-11e9-8947-ca6ec322c8c0.png)
