### ISSUE TITLE
Imperium - Space Marines: Master of the Trifold Path not implemented

### ISSUE THREAD

**Issue by ResidentScribe101** [BSData/wh40k#5712]
**Space Marines** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS

**Description:** Raven guard Stratagem "Master of the Trifold Path" *give warlord 2 traits* Is missing from the options when selecting warlord from the roster, all other stratagems are working and Implemented

**Comment by Balthazar100** [comment]
Please reopen. Chaplain is missing the ability to take this strategem in the app.
