### ISSUE TITLE
Imperium - FW Adeptus Astartes: Chaplain Dread not unlocking Relics for all catalogues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5716]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** This is still an issue and keeps being closed without resolution or explanation. When you take a chaplain venerable dreadnought and make it your warlord, OTHER characters do not have access to relics. A warlord in a faction should grant the army access to relics regardless of whether the warlord is eligible for the relic. This appears to function correctly in codex marines but BA, DA, and SW are all experiencing the bug. Interestingly the Librarian Dreadnought does not experience the issue either. It is only with Chaplain dreadnoughts. To recreate: create a space wolf battalion (or BA or DA), add chaplain dreadnought, add iron priest, make chaplain dreadnought a warlord, observe nor relics available to iron priest. This does not occur if a similar action is taken in codex marines.

Thank you, jbickb

**Comment by WindstormSCR** [comment]
this was closed with a merged fix in #5584 , not "without reason" in future please UPDATE your data to the newest revision before filing bug reports.

**Comment by jbickb** [comment]
Well my data is up to date and it is still an existing bug. So the fix must not have taken. Apologies for the terse tone in the initial report but it is still unresolved in the current available data.
