### ISSUE TITLE
Lib - FW Astartes: Update characters to use local links instead of duplication

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k#5719]
remove FW warlord and WLTs, adjust SM/BA as needed

**Comment by amis92** [comment]
@WindstormSCR @acebaur do you think this issue is still valid, taking into account the Lib SM work already done?

Asking since I don't track all the SM work.

**Comment by DrTobogganMD** [comment]
I think the lib SM change for new-dex has pretty much eliminated the need for this.

**Comment by DrTobogganMD** [comment]
We are currently discussing a revamp of SW/FW libraries to ease conjestion. This issue can be closed - a new one for the redo will be opened when it is settled on.
