### ISSUE TITLE
Astra Militarum / Death Korps: Demolisher Cannon now D6

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#5720]
**File/Catalogue:** Astra Militarum / Death Korps of Krieg

**BattleScribe version:** 2.03.01

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Demolisher Cannons are now D6 for Leman Russes instead of D3 - Source is the newest FAQ:

Astra Militarum / Death Korps:
Tank Commander,
Knight Commander Pask, Leman Russ Battle Tanks,
Baneblade, Hellhammer and Armoury of the Imperium,
demolisher cannon
Change Type characteristic to Heavy D6 and Abilities
to ‘-’.

Forgeworld Index / Death Korps:
Malcador Annihilator,
Malcador Defender, Stygies Thunderer Siege Tank,
Death Korps Leman Russ Mars-Alpha Battle Tanks,
Astra Militarum Wargear and Death Korps of Krieg
Wargear, demolisher cannon
Change Type characteristic to Heavy D6 and Abilities
to ‘-’

**Comment by lewis0460** [comment]
This technically isn't correct. Imperial Armour Index: Forces of the Astra Militarum has not been updated to reflect this. It might be a case of RAW vs RAI but until it's updated, units from the book do not get this change. In the meantime, email 40kfaq@gwplc.com voicing your frustration.

**Comment by Mad-Spy** [comment]
OP is correct. This was changed in today's Errata update.. However,  he is a little premature, given we have only had around 6 hours since the FAQ was updated, and GW haven't actually announced it in any way, and we haven't done a release since the change was made.

**Comment by Waldmenschen** [comment]
Apologies If I sounded rude or it seemed Like I was demanding a fix immediately^^
I Just thought it might easier fit you to keep track of everything If there's a Ticket.

(I Work in Software development and want a Ticket für everything before i even think about doing Something ;) )

**Comment by Waldmenschen** [comment]
Hi :)
thank you for the quick fix on Astra Militarum!
However the Death Korps Catalogue Demolisher Cannon is still D3 on the following Units:

- Death Korps Tank Commander
- Death Korps Leman Russ Mars-Alpha Battle Tank
- Death Korps Malcador Annihilator
- Death Korps Malcador Defender
- Death Korps Stygies Thunderer Siege Tank
- Death Korps Baneblade

**Comment by Mad-Spy** [comment]
The fix was only released this morning. So it's likely you haven't got the version which actually contains the fix.

**Comment by Waldmenschen** [comment]
I've got the 1.3.25 Version, and the Astra Militarum Demolisher Cannons got the fix, the Death Korps one don't

**Comment by alphalas** [comment]
Because DK had been manually fixed before the GST fix
