### ISSUE TITLE
Chaos - Chaos Knights: Knight Tyrant Relics Access Incorrect

### ISSUE THREAD

**Issue by Typhus** [BSData/wh40k#5724]
**Chaos Knights**

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** Currently, the Knight Tyrant is unable to select either the Veil of Medrengard or The Blasphemous Engine relics, although it should have access to both/either. Additionally, the Knight Tyrant is able to select both the Tyrant's Banner and Helm of Warpsight relics, although both should be unavailable to Tyrants, and War Dogs.

**Comment by Typhus** [comment]
Upon further investigation, seems to be an issue with the Dreadblade. No Dreadblade can purchase either the Veil of Medrengard or The Blasphemous Engine, although they should be able to.

**Comment by Mad-Spy** [comment]
Dreadblades should not be able to take the Veil or Engine; they are specifically denied access in the text for those Relics.

I'll sort the issue with the Banner and Helm.
