### ISSUE TITLE
Imperium - Space Marines: Chronus missing vehicle options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5729]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** No vehicle options available for HQ choice Sergeant Chronus. Normally can be placed in many Space Marine tank variants.

**Comment by WindstormSCR** [comment]
This was intentionally removed as chronus alone was responsible for a massive chunk of memory bloat because of the way vehicle options had to be linked. different validation is being worked on to check the roster for a valid vehicle keyword instead
