### ISSUE TITLE
Orks: Missing or outdated references to Ork Codex

### ISSUE THREAD

**Issue by MechMK1** [BSData/wh40k#5730]
**File/Catalogue:**
Orks.cat

**BattleScribe version:** 2.03.01

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:**
Most abilities or pieces of gear are missing references to the Ork Codex, or still reference the Xenos Index, even though it is now considered obsolete.

**Comment by amis92** [comment]
Linking #5233

**Comment by MechMK1** [comment]
@Guy-Markman If I can support you in updating the references, please let me know.
