### ISSUE TITLE
Imperium - Space Marines: Hero of the Chapter does not work on Chronus

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5736]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** Trying to use Hero of the chapter dont work on sgt Chronus. There are no list to select from. Also he no longer has any vehicle to select.

**Comment by Mad-Spy** [comment]
1. This will be looked in to.
2. Vehicles were deliberately removed from his entry as it was a contributing factor to the loading time issues we have been seeing. Work is on-going to add validation for him.

**Comment by Mad-Spy** [comment]
Chronus is not being granted the "Calm Under Fire" trait when he is selected as Warlord or when he is chosen to be the target of "Hero of the Chapter". This is the only option he should have in either case.

**Comment by Shiney1965** [comment]
None of the named characters have their designated warlord trait popping up on the ios version when they are given hero of the chapter.  On the PC version Chronus has free selection of WLT, based I assume on the Codex Supplement before the Errata correction.  The PC version allows selection of his vehicle, ios version does not.

**Comment by Mad-Spy** [comment]
The data set is the same, so it sounds like you just haven't updated the data on the PC.

**Comment by Shiney1965** [comment]
yes you were right .. after update ios and PC have the same Chronus issue.

**Comment by Shiney1965** [comment]
also relics cannot be selected for chronus, whether or not he is the warlord, although he is a character model and therefore is eligible for a relic

**Comment by WindstormSCR** [comment]
He is a vehicle, and therefore can never receive a relic under any circumstances

**Comment by Shiney1965** [comment]
This issue should not be closed — it is still
not possible to give chronus a warlord trait after you give him Hero of the Chapter.  I am working in ios with just updated data. Thanks
