### ISSUE TITLE
Lieutenant in Phobos Armour - Still no Terror Troops or Reiver keyword

### ISSUE THREAD

**Issue by TJ-paints-and-games** [BSData/wh40k#5742]
See previous issue: 5691

Unfortunatly the Terror Troops ability, and as i've now noticed the Reiver keyword is still not applying when the combat blade and heavy bolt pistol weapon option is selected.

I suspect this is for all versions of the Lt in Phobos armour, not just in "Space Marines".

If this hasn't made it into the current release but is due, thank you, ignore me, and close this with my apologies :)

**Comment by Mad-Spy** [comment]
I have reopened the previous ticket.
