### ISSUE TITLE
Orks: Nob weapon options need rework following FAQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5747]
**File:** Orks.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** When selecting Ork wargear on a Nob it does not flag up as not allowed when selecting a kombi scorcha or kombi rokkit (you can only take one of these and nothing else) then try and add a choppa etc as well as the kombi weapon this isnt allowed under the new faq.
Many thanks

**Comment by Mad-Spy** [comment]
It's not clear what you mean here. The text says each Nob "may replace its slugga and choppa for items from the _Nob Weapons_ list". That means it loses 2 items and can select two replacements from the list. The restriction in the list says that you can only take 1 kombi-weapon _per model_. That is all. There is nothing to stop you taking a kombi-weapon as one of your replacements and something else as the other.

I'm not sure what you're referring to when you mention the FAQ, as there are no relevant updates in the Ork Update 1.2

**Comment by CurtDaOrk** [comment]
Sorry about this it may just be the terrible wording but the faq said this so assumed it is this.

Q: When a Nob replaces their slugga and choppa with items from the Nob Weapons list, can they take two weapons from the first list and one weapon from the second list, for a total of three weapons (e.g. a big choppa, killsaw and a kombi-weapon with skorcha)?
A: No. They can take two weapons from the first list or only one if it is taken from the second list.

**Comment by Mad-Spy** [comment]
Ah, now I see. You're right, they have changed how this should be implemented. It'll need to be looked at.

**Comment by Guy-Markman** [comment]
Working on it
