### ISSUE TITLE
Sisters of Silence - Null-Maiden Rhino points updated in White Dwarf

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5751]
**File/Catalogue:** Imperium - Sisters of Silence v6

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** The Null-Maiden Rhino has a base cost of 70 points, but should be 65 points (as of White Dwarf Index Imperalis).

**Comment by Mad-Spy** [comment]
Is this from the Index that doesn't officially get released until next week?

**Comment by Dunamis55** [comment]
One benefit of being a subscriber, I guess!

**Comment by Mad-Spy** [comment]
My point being, most of us aren't subscribers and the new rules aren't officially released until Saturday. Raising issues before official release, _and_ before there's been a release of the data which could possibly have included the changes, comes across badly. We are aware that there are changes in White Dwarf this month, and those changes will get made as soon as we can, _after_ the rules are officially released.

If you want to help get the changes made, then post screenshots of all the pages of the Index, so we have something to work with!

**Comment by Dunamis55** [comment]
Yea, that's a good point, my bad. I'll get a photo uploaded tonight when I'm home from work.

**Comment by Dunamis55** [comment]
Index datasheet and points images:
https://imgur.com/a/Cg8JvhG
