### ISSUE TITLE
Servants of the Abyss missing Firebrand

### ISSUE THREAD

**Issue by franravi** [BSData/wh40k#5752]
**File/Catalogue:** Chaos - Servants of the Abyss.cat

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** Missing Cultist Firebrand in Servants of the Abyss.

**Comment by Mad-Spy** [comment]
If you have the datasheet, I'll add it.

**Comment by franravi** [comment]
There is an online version in wahapedia.
[http://wahapedia.ru/wh40k8ed/factions/chaos-space-marines/Cultist-Firebrand](http://wahapedia.ru/wh40k8ed/factions/chaos-space-marines/Cultist-Firebrand)
