### ISSUE TITLE
Magnus's Lord of Forbidden Lore ability

### ISSUE THREAD

**Issue by Robin0001** [BSData/wh40k#5784]
**File/Catalogue:** Thousand Sons v55 by BSData Developers 

**BattleScribe version:**  v2.03.02.130

**Platform:** Windows10

**Dropbox:** No

**Description:** Magnus as warlord dont apply  'Lord of Forbidden Lore' ability to spell selection maximum.
--

**Comment by Mad-Spy** [comment]
This is not a data issue, it's an issue with the latest version of the app. It will be fixed when the app developer releases a new version.
