### ISSUE TITLE
      Imperium - Space Marines: Infiltrator Squad Comms array should be allowed

### ISSUE THREAD

**Issue by d-isla** [BSData/wh40k#5792]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:**  iOS

**Dropbox:** No

**Description:** infiltrator squad should have a maximum number of comms array of 1 if a Helix adept is added to the unit, right now, it way the maximum is 0 no matter what you do.

**Comment by Mad-Spy** [comment]
This was due to a bug in the last release of the Battlescribe app. The developer has just rolled back those changes, so it will start working properly again after the next update to the app. Please keep checking the app store for an update to 2.03.05.
