### ISSUE TITLE
Astra Militarum - Sabre Weapons Battery - Incorrect point cost for wargear

### ISSUE THREAD

**Issue by dwtadlock** [BSData/wh40k#5795]
**File/Catalogue:** 

**BattleScribe version:** 2.03.05

**Platform:** Windows/Android

**Dropbox:** Yes/No

**Description:** Point cost for Twin Autocannon (20 ->25)and 2xTwin Heavy Stubbers(8 ->2x7=14) is incorrect. Verified with Imperial Armour-  Index: Forces of the Astra Militarum and Newest FAQ 1.2

**Comment by Mad-Spy** [comment]
I think you've missed the point changes from Chapter Approved in your calculation. That publication has the latest points costs.

**Comment by dwtadlock** [comment]
The Twin Autocannon and Twin Heavy Stubbers are not listed in 2018 Chapter Approved or Chapter Approved FAQ 1.1. and the single Stubber and single Autocannon are considered different weapons for rules purposes as far as I am aware. Rules as Worded vs Rules as Intended.

**Comment by Mad-Spy** [comment]
Apologies, I didn't have the book to hand. Most people who raise issues about points have overlooked Chapter Approved, and as you didn't mention it in your original comment, I assumed (incorrectly) the same applied.
