### ISSUE TITLE
Imperium - Space Marines: White Scars missing "Devastating Charge" rule.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5798]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.03

**Platform:** Windows

**Dropbox:** No

**Description:** The Chapter selection does not add all Chapter special rules.

Example: The chapter 'White Scars' adds the special rule 'Lightning assault', but not 'Devastating charge'.

**Comment by WindstormSCR** [comment]
Because the supplement rule is contingent on having all units in the army be from a specific chapter, which is currently impossible to validate correctly
