### ISSUE TITLE
Chaos - Chaos Space Marines: World Eaters Kytan Ravager & Blood Slaughterer

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#5799]
**File/Catalogue:** Chaos - Chaos Space Marines v111

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** Yes

**Description:** World Eaters should have access to the Kytan Ravager and Blood Slaughterer of Khorne.

**Comment by Mad-Spy** [comment]
Forge World units can currently be found in the FW Heretic Astartes catalogue. You'll need to add that one as a child detachment.

However, all the units will be merged into the main Heretic Astartes catalogues in the next release of the 40k data.

**Comment by Mad-Spy** [comment]
Fixed
