### ISSUE TITLE
Aeldari - Craftworld Autarch Skyrunner Laser Lance option missing

### ISSUE THREAD

**Issue by Lazerius** [BSData/wh40k#580]
Just signed up on Github and wasn't sure how to search, so please excuse me if this has already been reported.

Autarch Skyrunner can take either 2 weapons from the Autarch Weapons list or a Laser Lance and 1 weapon from the Autarch Weapons list.

No Laser Lance option in Data File.

Thanks.

**Comment by GenWilhelm** [comment]
I can see the option on my end. Can double-check, and if it's definitely not there, it would be useful to know which version of the file you have, what version of BattleScribe you are using, and on which platform.

**Comment by FarseerVeraenthis** [comment]
Laser Lance option is present on Android, file version 7 (latest released version)

**Comment by FarseerVeraenthis** [comment]
Laser Lance option is also available on Windows.

**Comment by Lazerius** [comment]
Sorry I never got back on this.  It's been a very busy week and I never got a chance to double check 
 and reply.

Data File is WH40k 8th Mobile v34 on Windows.


![skyrunner](https://user-images.githubusercontent.com/29804332/27925492-868d4336-624a-11e7-9bc2-f5ff936b40b6.png)

It appears to be in the 8th Edition v14 normally, so I'll probably just stick with that one.

Thanks!

**Comment by FarseerVeraenthis** [comment]
Ah right, yeah, this is not the issues list for the mobile files... That's, (oh bother where's the link...) anyway, it is present in "our" file:smile:

**Comment by Lazerius** [comment]
Ah ha!  Ok, sorry about that!  

Thanks for all you do!

**Comment by FarseerVeraenthis** [comment]
No worries, thanks for the appreciation!

**Comment by FarseerVeraenthis** [comment]
https://github.com/BSData/wh40k-mobile-format/issues

Here is the link to report issues with the mobile format files... They are all created and maintained by one dude though so, don't expect an instant response!
