### ISSUE TITLE
Addition of PA1: Blood of the Phoenix: Custom Faction Traits

### ISSUE THREAD

**Issue by Davey-Jone-s** [BSData/wh40k#5804]
**File/Catalogue:** Craftworlds / Drukhari / Ynarri

**Description:** Addition of Aeldari Custom Faction Traits for Craftworlds and Drukhari from Psycic Awakening Book 1: Blood of the Phoenix.

**Comment by Mad-Spy** [comment]
This is already being worked on and will be in the next release.
