### ISSUE TITLE
Incorrect maximum relics number value for Grey Knights force

### ISSUE THREAD

**Issue by corias** [BSData/wh40k#5806]
**File/Catalogue:** Imperium - Grey Knights.cat

**BattleScribe version:** 2.03.05

**Platform:** Android

**Dropbox:** No

**Description:** When selecting a relic for a unit in Grey Knights force, BattleScribe shows validation error, which states that roster has too many selections from GK relics (maximum 0). When Armory of Titan is selected, the maximum relics number is 1 and 2 for 1 and 2 additional relics respectively.

**Comment by Mad-Spy** [comment]
Have you selected either a Grey Knights Warlord or one of the Armoury of Titan options? If not, then the validation error is correct because you cannot take a Relic otherwise.
