### ISSUE TITLE
Imperium - Grey Knights incorrect wargear for Librarian

### ISSUE THREAD

**Issue by corias** [BSData/wh40k#5807]
**File/Catalogue:** Imperium - Grey Knights.cat

**BattleScribe version:** 2.03.05

**Platform:** Android
**Dropbox:** No
**Description:** It is possible to select Stormshield wargear option, while it's actually not availiable (Codex: Grey Knights, pg. 70)

**Comment by Mad-Spy** [comment]
It's a holdover option from the Index, allowed as per the Designer's Commentary flowchart.
