### ISSUE TITLE
Triumvirate of Ynnead has not got the phoenix rising updated points values

### ISSUE THREAD

**Issue by rrhyx** [BSData/wh40k#5810]
**File/Catalogue:** 
Aeldari - Craftworlds v80
**BattleScribe version:** 2.03.
2.03.05
**Platform:** Windows/iOS/Android/Mac/Linux
Android
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
The triumvirate of ynnead has the wrong points values, as they have been updated in phoenix rising

**Comment by Mad-Spy** [comment]
We haven't done a release since Psychic Awakening book came out. The changes will be in the next release.
