### ISSUE TITLE
Lib - FW Adeptus Astartes: Atomantic Pavaise text needs updating

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5812]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** Yes

**Description:** Under Space Marine Codex, Relic Deredeo Dreadnought, Atomantic Pavaise, first sentence should be read: "If equipped with an atomantic pavaise, all friendly <CHAPTER> units wholly within 6" of this model gain a 5+ invulnerable save." 

The word "wholly" before "within 6" of this model" was added in a FAQ to Imperial Armour Index Forces of the Adeptus Astartes,

**Comment by gitGremlin** [comment]
Please also remember that it's friendly `<CHAPTER>` units for the SM version. Chaos get the the friendly CHAOS units bubble.
