### ISSUE TITLE
The bonesinger needs runes of fortune

### ISSUE THREAD

**Issue by Ithyrrinaz** [BSData/wh40k#5823]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows
**Dropbox:** 

**Description:** The Bonesinger is a Psyker and can therefore replace smite with Runes of fortune. It does not have that option at the time

**Comment by Mad-Spy** [comment]
It didn't have Smite linked in previously, which is how I missed it! It'll be in the next release.
