### ISSUE TITLE
Imperium - Deathwatch: Veterans are allowed to equip 3 items.

### ISSUE THREAD

**Issue by derekburgess** [BSData/wh40k#5833]
**File/Catalogue:** Imperium - Deathwatch

**BattleScribe version:** 2.03.03

**Platform:** iOS

**Dropbox:**

**Description:**

According to the Codex, Veterans can replace their Boltguns with 2 items from the Deathwatch Equipment List. Which includes 2 sub-lists, one allowing 2 selections and one allowing only 1 selection. It has been considered legal to also equip them with 1 item from either list.

i.e. The classic Storm Bolter(1 item list) and Storm Shield(2 item list) load out.

Battlescribe throws errors unless you pick 2 items from the "2 item list". Battlescribe than still allows a selection from the "1 item list", resulting in a total of 3 items being equipped.

Tested using Storm Bolter and Storm Shield vets and adding a Chainsword, which resolved the errors.

**Comment by Mad-Spy** [comment]
This is a bug in the app, rather than the data. We are awaiting a fix from the developer.
