### ISSUE TITLE
[Aeldari] Bug Report: Hemlock Fighter incorrect cost for Craftworld and Ynnari

### ISSUE THREAD

**Issue by inEQUALITY94** [BSData/wh40k#584]
**File:** Aeldari - Ynnari.catz | Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Hemlock Wraithfighter costs 221, but it's supposed to be 211. Issue is identical with both Ynnari and Craftworlds.

**Comment:** When I loaded a roster made from a previous (June 27th) version of the catz files with the latest (June 29th), it had a checkbox for Spirit Stones (10 pts) that disappeared once it was clicked. I would assume it's treating Spirit Stones as a wargear upgrade, since they do cost 10 pts when used that way, but the Hemlock is supposed to come with these by default at 211 pts.

**Comment by FarseerVeraenthis** [comment]
I'm sorry, but you're wrong. Spirit stones are listed under "other wargear" and have a cost. As such, in the same way as the Autarch has to pay for his Forceshield, the Hemlock has to pay for its spirit stones.

**Comment by inEQUALITY94** [comment]
Previous data files had the cost at 211 and the 2nd place list from GT Boise lists the Hemlocks at 211 as well. "Spirit Stones" is listed as an ability for Hemlocks, not as Wargear it can take. I seem to not be understanding how this works, then, which could well be a failing on my part (I'm fairly spoiled by Battlescribe). But if Wargear can also be listed under abilities in the codices, rather than only under a section titled Wargear (which it is for other units) that is absolutely obtuse. Especially if the wargear is required but not calculated into the base cost of the unit...

**Comment by FarseerVeraenthis** [comment]
Hehehe! The wonders of GW... further ref, #451
It is interesting to hear about the GT list though!

**Comment by inEQUALITY94** [comment]
That certainly helps, though it's a bit disappointing. Darn GW and their ways. Thanks!

**Comment by FarseerVeraenthis** [comment]
If it was easy, it would be boring... Right...?!
