### ISSUE TITLE
Drukhari - Court of the Archon Error

### ISSUE THREAD

**Issue by crackedgear** [BSData/wh40k#5865]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** When selecting court of the archon, I receive the error “No Force Org slot has one too many selections of Court of the Archon (maximum 0)”

**Comment by Mad-Spy** [comment]
Fixed in v57 of the Drukhari catalogue.
