### ISSUE TITLE
Necron Characters (that are allowed to select a relic) cannot select a relic, Rosters with relics selected throw errors

### ISSUE THREAD

**Issue by Veziik** [BSData/wh40k#5868]
**File/Catalogue:** Necrons.cat

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Characters in a necron army cannot select an artefact of aeons (aka a relic), the field is hidden. Rosters created before 2.03 update throw errors for too many relics on a per character basis (for example, if two characters have a relic each, two errors are thrown). Rosters made and viewed in BScribe version # < 2.03 are unaffacted.

**Comment by Mad-Spy** [comment]
v
