### ISSUE TITLE
Craftworld: Runes of Fortune for Hemlock

### ISSUE THREAD

**Issue by Phoenix8472** [BSData/wh40k#5884]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes

**Description:** Request: Hemlock Wraithfighter in Craftworld Eldar should be able to swap Smite for Runes of Fortune Psychic powers.

**Comment by Mad-Spy** [comment]
Already fixed in v85 of the Craftworlds file. Will be in the next release.
