### ISSUE TITLE
Officio Assassinorum detachment not giving CP

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k#5888]
Officio Assassinorum v10

**BattleScribe version:** 2.03.06

**Platform:** Windows/Android

**Dropbox:** No

**Description:**

When you select the vanguard detachment without CP you dont get +1CP when you have 1 of each assassin.

Execution Force: So long as your Warlord is from the IMPERIUM, you can include this unit in a Vanguard Detachment even if that Detachment contains no HQ units. However, if you do so, that Detachment's Command Benefits are changed to 'None' unless that Detachment contains exactly 1 of each assassin.

**Comment by Mad-Spy** [comment]
You should use the standard Vanguard (not the 0CP version). Then, if you add one of each Assassin, an HQ option of "Execution Force" will appear to allow you to validate the Detachment.

**Comment by p5freak** [comment]
Ok, thanks.
