### ISSUE TITLE
Aeldari - Drukhari: Relics not working across Detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5889]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.08

**Platform:** Android

**Dropbox:** No

**Description:** Problem: Artefacts of Cruelty are only available to the selected warlord.

Correction: The choice of Artefact should be available to any non-named DRUKHARI CHARACTER.

**Comment by Mad-Spy** [comment]
This was working within a Detachment, but not across multiple Detachments.
Fixed in v57 of the Drukhari catalogue.
