### ISSUE TITLE
Chaos - Death Guard: Helbrute Fist cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5891]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.09

**Platform:** Android

**Dropbox:** No

**Description:** Hellbrute pts incorrect. Fist displaying as 20pts should be 30?

**Comment by Mad-Spy** [comment]
Looks like the validation has changed in the new version of Battlescribe. Fixed in the next release.
