### ISSUE TITLE
Drukhari - Can’t give relic to Haemonculus unless he’s Warlord

### ISSUE THREAD

**Issue by crackedgear** [BSData/wh40k#5896]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes/No

**Description:** When selecting a Haemonculus unit, the option for relics doesn’t appear unless I designate this unit as my Warlord.

**Comment by Mad-Spy** [comment]
Fixed in the next release.
