### ISSUE TITLE
Operative requisition sanctioned disappeared

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k#5897]
All Imperium catalogues

**BattleScribe version:** 2.03.06 Windows, 2.03.09 Android

**Dropbox:** No

**Description:**

The option to select operative requisition sanctioned -2CP 85 pts. under no force org slot has disappeared from all Imperium catalogues.

**Comment by Mad-Spy** [comment]
Looks like it's an app bug. I've reported it to the developer.

**Comment by Mad-Spy** [comment]
This should be resolved now. We've reworked it to get around the app bug.
