### ISSUE TITLE
Imperium - Sisters of Silence: Include WD updates

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5901]
**File:** Imperium - Sisters of Silence.catz

**BattleScribe version:** 2.03.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Request for updates to point value and to power levels as of  recent release of October white dwarf

**Comment by Mad-Spy** [comment]
All these changes should have been done already. Can you give specifics of what is missing?

**Comment by williamcaw** [comment]
This is a  attempted save of index units it does change a lot of rules and interactions and changing of point values

**Comment by Mad-Spy** [comment]
@williamcaw, the point of your comment is not clear. All of the changes made in October's White Dwarf should have been implemented already (by me, as per #5751). If something has been missed, please provide details.

**Comment by jvogtherr** [comment]
I just noticed that Adeptus Astra Telepatica is missing the 3 Sisters of Silence units and the rhino as choices. Sisters have the Astra Telepatica keyword (even since before the WD i think).

**Comment by Mad-Spy** [comment]
@jvogtherr, there's a separate Sisters of Silence catalogue which is why they are not in that one.

I'm closing this as it doesn't appear that anyone can point to any specific issues.

**Comment by jvogtherr** [comment]
@Mad-Spy yes they have their own catalogue, but they can also be included in an Astra Telepatica detachment (SoS doesnt have/News HQ choices, but AT does, so there are reasons to play both). Currently it is not possible to create such a detachment (AT Vanguard, 2x HQ + 3x Sisters for example). Should i open another issue?

**Comment by Mad-Spy** [comment]
Yes, you can, like this: https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions

**Comment by jvogtherr** [comment]
Thank you very much
