### ISSUE TITLE
Imperium - Dark Angels: Several issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5911]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.09

**Platform:** Android

**Dropbox:** No

**Description:** Auxillary Grenade Launcher on intercessors points cost should be 1pt and options for the ravenwing attack squadron vigilus detachment are not available. Also the eliminator segeants abilities do not show on his data sheet, guided aim and covering fire.

**Comment by Thairne** [comment]
Specialist Detachment is available on desktop version. Might be a problem with the app (although there are no hide modifiers on that one).
