### ISSUE TITLE
Imperium - Space Marines: Cassius cannot take the correct number of Litanies

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5912]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.06

**Platform:** Windows

**Dropbox:** No

**Description:** Chaplain Cassius is allowed 2 Litanies is addition to Litanies of Hate. Litanies of Hate is currently being counted as one of the 2 extra litanies he is allowed, meaning selecting 2 throws up an error.

**Comment by Mad-Spy** [comment]
None of the modifiers which should give him access to the extra Litany and modify the naming are firing. Looks like a BS bug.
