### ISSUE TITLE
Imperium - Space Marines: Relic validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5913]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When making a Patrol Detachment and selecting a Relic, it shows that you have selected more Relics than allowed (maximum 0)

**Comment by preatoria** [comment]
After creating this issue I found take this error disappeared after I selected a Warlord.
It looks like the wrong error is being reported.

**Comment by preatoria** [comment]
Below I added the list that give the Relic error:

[b]++ Patrol Detachment (Imperium - Space Marines) [28 PL, 500pts, 2CP] ++[/b]

[b]+ No Force Org Slot +[/b]

[b]**Chapter Selection**:[/b] Raven Guard

[b]Battle-forged CP [3CP][/b]

[b]Detachment CP[/b]

[b]Gametype:[/b] Matched

[b]+ HQ +[/b]

[b]Kayvaan Shrike [8 PL, 130pts][/b]

[b]Librarian in Phobos Armour [5 PL, 101pts, -1CP]:[/b] 4) Shadowstep, 4. Stealth Adept, 5) The Abyss, Camo cloak, Force sword, Shadowmaster Cloak, Stratagem: Hero of the Chapter

[b]+ Troops +[/b]

[b]Scout Squad [4 PL, 80pts]:[/b] 5x Camo cloak
. Scout Sergeant: Bolt pistol, Sniper rifle
. 4x Scout w/Sniper Rifle: 4x Sniper rifle

[b]Scout Squad [4 PL, 65pts][/b]
. Scout Sergeant: Bolt pistol, Boltgun
. 3x Scout w/Boltgun
. Scout w/Heavy Weapon: Heavy bolter

[b]+ Elites +[/b]

[b]Ironclad Dreadnought [7 PL, 124pts]:[/b] Hurricane bolter, Meltagun, Seismic hammer

[b]++ Total: [28 PL, 500pts, 2CP] ++[/b]

**Comment by Mad-Spy** [comment]
Sounds like this is working as expected. You _shouldn't_ be able to take any Relics without either having an appropriate Warlord or choosing the Relic unlock stratagem.

I can't even find a way of adding a Relic without doing so, but maybe it was possible in an earlier version of the data.
