### ISSUE TITLE
Imperial Fist Updates needed!!!

### ISSUE THREAD

**Issue by martinpa91** [BSData/wh40k#5914]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
The 40k data is maintained by a team of volunteers from the community. As such, updates are provided when they are done. Rudeness is not acceptable.

**Comment by martinpa91** [comment]
Imperial Fist Updates greatly appreciated.
