### ISSUE TITLE
FW Death Korps - Watch Master only able to equip 1 Weapon

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#5915]
**File/Catalogue:** ForgeWorld Death Korps

**BattleScribe version:** 2.03.06.134 (PC) / 2.03.09.317 (Android)

**Platform:** Windows / Android

**Dropbox:** No

**Description:**
The Watch Master in the Infantry Squads can currently only equip 1 Weapon.
But the Index allows 1 Melee + 1 Ranged Weapon, and I didn't find anything in the FAQs to change this.
I'm not sure if this is a Data Issue or BattleScribe Issue or a bit of both, as it was ok before the "performance updates" but hasn't changed in the last Fixes.

**Comment by Mad-Spy** [comment]
I'm unable to cause an error in the current dataset with a valid loadout.

If I remove his lasgun, I can give him either one single item from the Melee list and one single item from the Ranged list, **or** one of the "2 x" options from the Ranged list without getting an error.

What is the exact combination you are adding?

**Comment by Waldmenschen** [comment]
I can't equip a Lasgun + Chainsword.
Every other Combo works as intended it seems (2 Pistols -> 0 Melee / 1 Pistol or Gun + 1 Melee)

**Comment by Waldmenschen** [comment]
You're right, I was probably just used to the way it was before... xD
Seems like I have to sort through my Rosters and correct it...
Thank you!
