### ISSUE TITLE
FW: Elysian Vulture Weapon Options

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#5919]
**File/Catalogue:** FW:Elysian

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** When you equip the Vulture with twin punisher cannons and select the other weapon options as "none", it still shows an error saying you must select a minimum of 1.

**Comment by Mad-Spy** [comment]
This is an app bug. Please ensure you have the latest version of the Battlescribe app (2.03.04). If there is still an issue, please report to the app developer via Uservoice, as per the Battlescribe website.
