### ISSUE TITLE
FW: Elysian Officer Heirlooms

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#5920]
**File/Catalogue:** FW: Elysian

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Unable to select heirlooms on Elysian Officers (Company, Platoon, Commissar, OotF). No option is given, even if selected as warlord.

**Comment by Mad-Spy** [comment]
This is an app bug. Please ensure you have the latest version of the Battlescribe app (2.03.04). If there is still an issue, please report to the app developer via Uservoice, as per the Battlescribe website.
