### ISSUE TITLE
"Killsaw" for Ork Painboy is missing (Index)

### ISSUE THREAD

**Issue by MechMK1** [BSData/wh40k#5922]
**File/Catalogue:** Orks

**BattleScribe version:** 2.03.06

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Wargear options that are only available in the Index, but not in the Codex, usually have `(Index)` appended to them. The Killsaw as an option for the Ork Painboy was present in Index: Xenos 2, but is missing from Codex: Orks. It should therefore be noted that this is a wargear option from the Index.

The image below shows the issue:

![Painboy missing Index](https://user-images.githubusercontent.com/979843/68084197-bf21e400-fe32-11e9-8cc7-ee0c7f6a6462.png)

**Comment by Mad-Spy** [comment]
Technically, anything which has an (Index) marker is incorrect, as the current style is not to mark these as any different.
