### ISSUE TITLE
Imperium - Space Marines, missing new characters

### ISSUE THREAD

**Issue by zapruder327** [BSData/wh40k#5923]
**File/Catalogue:** Imperium - Space Marines.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** Special characters from the new supplements aren't showing up in BS. Adrax Agatone for Salamanders and Tor Garadon for Imperial Fists.

**Comment by Mad-Spy** [comment]
We have not yet done a release which includes these characters.
