### ISSUE TITLE
T'au: XV25 Stealthsuits Fusion blaster limit broken

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5924]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When taking 3 Stealth suits, the Codex allows one of them to change out their Burst cannon for a Fusion Blaster. When selecting this option in BS it error and shows the Max allowed is 0.

**Comment by amis92** [comment]
Again...? :(

**Comment by amis92** [comment]
Duplicate of #4958

**Comment by amis92** [comment]
This was fixed in an app update, marked in the issue referenced above.
