### ISSUE TITLE
T'au: XV8-02 Crisis Iridium limit broken

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5926]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.06

**Platform:** Mac

**Dropbox:** Yes

**Description:** XV8 Crisis Battlesuits Iridum armour wargear is configured incorrectly and can only be given to a Shas'vre when it should be possible to give to a Shas'ui.

If given to a Shas'ui it gives the error "XV8 Crisis Battlesuits has 1 too many selections of XV802 Crisis Iridium battlesuit (maximum 0)".

The codex entry for this wargear states that "For every three models in the unit, one model may take an XV8-02 Crisis Iridium Battlesuit, increasing that model’s Save characteristic to 2+." (T'au Empire Codex page 103) It is not specific to the Shas'vre.

**Comment by amis92** [comment]
Unfortunately that's broken thanks to new app version. See #5924.

This is due to https://github.com/BattleScribe/Release/issues/97 as well.

**Comment by amis92** [comment]
This was fixed in an app update, marked in the issue referenced above.
