### ISSUE TITLE
Imperium - Space Marines: Fist of Vengeance not restricted to 1 per model

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5932]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.10

**Platform:** Android

**Dropbox:** No

**Description:** The Crimson Fists relic Fist of Vengeance has a numerical picker instead of being a checkbox like all the other relics. 
This is true in version 119 of imperium space marines. It's minor but if like to see it get fixed.

**Comment by Mad-Spy** [comment]
This will almost certainly change when the IF supplement is implemented.
