### ISSUE TITLE
Some chaos red corsairs detachments dont get +1CP for three or more units

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k#5939]
Chaos v111

**BattleScribe version:** 2.03.06 PC / 2.03.10 Android

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** When i select an air wing detachment the command benefits are not increased by +1CP when i have three or more units. With a spearhead detachment its only increased for a few units, like hellforged deredeo, hellforged leviathan, or havocs.

**Comment by Mad-Spy** [comment]
Yes, this is correct. As the rule says:
> If you choose to use this supplement, and your army is Battle-forged, all Daemon Prince, INFANTRY , BIKER and HELBRUTE units in a Chaos Space Marine Detachment gain a Renegade Trait, so long as every unit in that Detachment is from the same Renegade Chapter.

Air Wings can only contain flyers, so they can never qualify. Spearheads can, but not if you only include vehicles.

**Comment by p5freak** [comment]
Ok, i misunderstood the rule, sorry.

**Comment by Mad-Spy** [comment]
No worries
