### ISSUE TITLE
Aeldari - Drukhari: Urien Rakarth points inaccurate

### ISSUE THREAD

**Issue by Enavia** [BSData/wh40k#5944]
**File/Catalogue:** Aeldari - Drukhari.cat

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Urien Rakarth is listed in Codex at 90 points (includes wargear). In the app, displays as 95 points (90 base + 5 for Ichor Injector).

**Comment by Mad-Spy** [comment]
Already fixed for the next version, as per #5908
