### ISSUE TITLE
Imperium - Space Marines: Relic Leviathan melee weapon costs incorrect

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k#5945]
**BattleScribe version:** 2.03.10

**Platform:** Android

**Description:** data file - Space Marines v119

Leviathan Siege Drills costs are 40/50 single/pair. Plus 14 for each melta gun.
But If I create a Dread with a pair of Siege Drills, each drill costs 54 (instead of 50/2+14=39).

Same happens for Siege Claws which should be 30/40 (44 each when paired, instead of 40/2+14=34).

Seems like the logic for single/paired is reversed, because if I select different hands for dread, drill hand costs 39 and claw hand costs 34

**Comment by Mad-Spy** [comment]
Another casualty of the BS app bug affecting conditions using links.

**Comment by amis92** [comment]
I guess those are the modifiers that don't trigger:

![image](https://user-images.githubusercontent.com/2671396/68533944-4f7a9000-032f-11ea-985f-c6e22a25602f.png)


My workaround suggestion is: change the condition to trigger when not-a-link Claw/Drill is selected 2 times in RLD entry.

**Comment by gluck3d** [comment]
Seems like with latest fix of BS for the ticket above ( 2.03.12.320 ) this has been resolved, claws have correct price.
Instead all the 'Hero of the Chapter'/'Exemplar of the Chapter' are no more visible (and there is an alert on number of warlord traits)...

**Comment by WindstormSCR** [comment]
fixed in v122 / BS 2.03.07
