### ISSUE TITLE
Imperial Fists and Salamanders missing Relics / Characters / Warlord Traits

### ISSUE THREAD

**Issue by teun135** [BSData/wh40k#5947]
**File/Catalogue:** Imperium - Space Marines.cat

**BattleScribe version:** 2.03.06.134

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:**  Missing new characters, Relics, and Warlord traits released in new supplements that were released 10/26

**Comment by Mad-Spy** [comment]
This content has not yet been released. It will be released as soon as it is ready.
