### ISSUE TITLE
T'au Empire: Breacher and Strike Team drones should cost 1PL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5949]
**File:** T'au Empire.catz

**BattleScribe version:** 1.03.26

**Platform:** Android

**Dropbox:** No

**Description:** Tau fire warrior not reporting extra 1 PL for attached drones

**Comment by amis92** [comment]
I've triaged this on PC v2.03.07.135

On first sight it looked to be a simple bug - I haven't checked "Include all child selections" on appropriate conditions. But after fixing that oversight, it still didn't work.

Raising as an app bug.

**Comment by amis92** [comment]
Also what's more interesting is that it activates for the MV36 Guardian Drone, but doesn't for all the other drones.

**Comment by amis92** [comment]
Repro: 
[Drone PL issue repro.zip](https://github.com/BSData/wh40k/files/3851839/Drone.PL.issue.repro.zip)

**Comment by amis92** [comment]
It's fixed in BattleScribe 2.03.08+, I confirm.
