### ISSUE TITLE
Validation errors when adding second signature system and using Emergency Dispensation stratagem

### ISSUE THREAD

**Issue by TedSanne** [BSData/wh40k#5955]
**File/Catalogue: T'au Empire.catz** 

**BattleScribe version:** v2.03.06.134.

**Platform:** Windows

**Dropbox:** No

**Description:** 
When adding the Emergency Dispensation stratagem to the roster, and selecting a different signature system for another character, BattleScribe spews out lots and lots of the same validation message:
"New Roster (Warthammer 40,00 8th Edition v110) has 1 too many selections of Signature System (maximum 1)"

By adding the Emergency dispensation stratagem, I should be able to select 2.

See attached test roster with Cadre Fireblade with Puretide engram and Commander in Coldstar with Supernova launcher

[TestRoster.zip](https://github.com/BSData/wh40k/files/3832558/TestRoster.zip)

**Comment by amis92** [comment]
This was reported as BattleScribe/Release#96 - fixed by app update.
