### ISSUE TITLE
Sergeant Chronus in UM still cannot get warlord traits with Hero of the Chapter, 

### ISSUE THREAD

**Issue by Shiney1965** [BSData/wh40k#5958]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Shiney1965** [comment]
Hello: this issue was previously closed but it is still there. When giving Chronus (in Ultramarines) Hero of the Chapter he should be able to select a Warlord trait.  The mandatory warlord trait rule applies only if he is selected as a Warlord (as states in the supplement), not with Hero of the Chapter.  I am working in ios with the just updated data.  Thanks

**Comment by Mad-Spy** [comment]
That sounds incorrect to me. The Stratagem says to determine a Warlord Trait for him and that he is treated as the Warlord for the purposes of the Trait. If you are treating him as the Warlord, he must take Calm Under Fire.

**Comment by Shiney1965** [comment]
Thanks for pointing that out — I was aware of the rule but did not read it as you do.  You are probably right about the intent and its fine for Battlescribe purposes, but there is ambiguity.  “For the purposes of the Warlord Trait” could mean for the purposes of applying the Warlord Trait not choosing the Warlord Trait.  I searched and found a few discussions in DakkaDakka and Redditt about this so I am not the only one who sees this as ambiguous, although most seem to agree the trait always follows the character.  According to one post,  GW has said in response to an email inquiry that they are “aware of the issue” - suggesting that they don’t have a position on it yet. 
 I guess there is nothing to be done for the data set and it can remain as is, but the rule does require some clarification.
Thanks for your help.

**Comment by Mad-Spy** [comment]
I guess we'll wait for an FAQ response then.
