### ISSUE TITLE
Imperium - Space Marines: Drake-smiter not available

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5961]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.10

**Platform:** Android

**Dropbox:** No

**Description:** The Salamanders Relic "Drake Smiter" is not available for selection, even when the model is selected as a warlord and equipped with the thunder hammer it replaces.

**Comment by Mad-Spy** [comment]
@WindstormSCR, the condition is pointing at the GST copy, but the SM models use a local copy.
