### ISSUE TITLE
Inquisition - Forge World Inquisitors cannot take Index Inquisition Warlord traits

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5962]
**File/Catalogue:** Inquisition v29

**BattleScribe version:** 2.03.06

**Platform:** Windows

**Dropbox:** No

**Description:** Inquisitor-Lord Hector Rex and Inquisitor-Lord Solomon Lok are unable to select Warlord traits from the Index Inquisition options.

**Comment by Mad-Spy** [comment]
The new content from White Dwarf has not yet been implemented. Please hold off raising issues until it has been done
