### ISSUE TITLE
Inquisition - Inquisitor Greyfax is unable to take a Warlord trait

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5963]
**File/Catalogue:** Inquisition v29

**BattleScribe version:** 2.03.06

**Platform:** Windows

**Dropbox:** No

**Description:** If Inquisitor Greyfax is selected to be a Warlord, she is not automatically granted the No Escape Warlord trait and no option appears for her to take this trait either.

**Comment by Mad-Spy** [comment]
The new content from White Dwarf has not yet been implemented. Please hold off raising issues until it has been done.
