### ISSUE TITLE
Imperium - Dark Angels: Aux grenade launcher cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5968]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.10

**Platform:** Android

**Dropbox:** No

**Description:** Item "Auxiliary Grenade Launcher" is 1 point it should be 0 point.

**Comment by Thairne** [comment]
Points were updated in CA 18 if I remember correctly.

**Comment by Mad-Spy** [comment]
Ca2018 lists the DA aux grenade launcher at 0 pts.

**Comment by Thairne** [comment]
I could've sword I changed the aux a few weeks back... but obviously I'm old and crap!

**Comment by jambo0r** [comment]
Hi Thairne, you did change this to 1pt a couple weeks ago. 1pt is the correct value for a DA aux launcher, if nothing else then CA19 resolves this where it is definitely listed as 1pt for DA (and all other chapters). Cheers! - James
