### ISSUE TITLE
Chaos - Additional Relic stratagems do not unlock Relics

### ISSUE THREAD

**Issue by peterduff** [BSData/wh40k#5969]
**File/Catalogue:** 

**BattleScribe version:** 2.03.06

**Platform:** Mac

**Dropbox:** No

**Description:** Detailed issue description.

Create Chaos Space Marine Supreme Command Detachment, add a HQ, make it the warlord. Create a second Thousand Sons Supreme Command Detachment, add a HQ, include additional relic rule: Relics of the Thousand Sons (1 Relic) (-1CP). You are unable to give the Thousand Sons HQ a relic.

Also occurs with other detachments, also occurs with other relic rule, also occurs with other armies (CSM & Death Guard tested). Does NOT occur with Imperium armies (tested with Space Marines and Astra Militarum).

This used to work, assuming bug?
<img width="1676" alt="Screenshot 2019-11-14 at 01 00 57" src="https://user-images.githubusercontent.com/6538469/68817710-77912880-067a-11ea-98e7-919702a9b8f1.png">

**Comment by Mad-Spy** [comment]
This is not a soup problem, it's a problem with the TS Relic strats no longer unlocking the Relic selectors.
