### ISSUE TITLE
Imperium - Adeptus Custodes: Selecting Warlord does not unhide WLTs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5975]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** v2.03.12.320
Since updating my data last night, my custodes warlord can no longer take warlord traits. I get an error saying that they have too many choices with a max of 0

**Comment by Mad-Spy** [comment]
The WLT SSEG is hidden based on a link, rather than the real entry so it's being stuck by the BS bug. 

Works fine on Windows.

**Comment by williamcaw** [comment]
Can’t be   Selected  Under the warlord drop down.

**Comment by DrStalker** [comment]
I  had the same problem with version 1.3.29 of the datafiles but it's fixed with today's update to 1.3.30.
