### ISSUE TITLE
Imperium - Space Marines: Relics show as max 0 after selecting a Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5978]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** Created Space Marines roster, made a battalion detachment of Imperial Fists. Set a chaplain as Warlord. BattleScribe will allow me to select a warlord trait, but when selecting a relic it states that the maximum number of relics is 0. Was selecting Benediction of Fury, but it also prevented me from using any of relic I selected either.

**Comment by WindstormSCR** [comment]
fixed in v122
