### ISSUE TITLE
Death Korps

### ISSUE THREAD

**Issue by DeathKorps** [BSData/wh40k#598]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
I see that most of the factions from the new IA:Astra Militarum have been added to battlescribe, but the Death Korps of Krieg have not?

**Comment by alphalas** [comment]
They are still in progress; see #375

**Comment by alphalas** [comment]
Ack, #379
