### ISSUE TITLE
Imperium - Space Marines: Salamanders Relics and Strats are available to all Chapters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5981]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** When i creating roster for imperial fists, battle scribe offers salamanders stratagems such as Master artisans and trust of Prometheus. Also there is special issue wargear for salamanders. I remind you. I making an imperial fists list. Fix this please. Thank you.

**Comment by gitGremlin** [comment]
This is not specific to FW Adeptus Astartes. This happens in all SM rosters.

**Comment by Mad-Spy** [comment]
Battlescribe link bug

**Comment by WindstormSCR** [comment]
Fixed in V122 via better implementation
