### ISSUE TITLE
Aeldari - Harlequins: Masque-specific selections not appearing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5986]
**File:** Aeldari - Harlequins.catz

**BattleScribe version:** 2.03.07

**Platform:** Windows

**Dropbox:** No

**Description:** Masque specific Enigmas and warlord trait options don't work anymore and are not displayed as an option. When loading previous edition rosters the traits that are on the old rosters generate errors. One example: Soaring Spite masque and related Faolchu's Talon enigma and Skystrider warlord trait.

**Comment by WindstormSCR** [comment]
This is due to a current BS bug, no eta on fix, if it persists too long will be introducing a possible work around.

**Comment by Mad-Spy** [comment]
I've done the workaround as this seems like it's taking a while to get sorted.
