### ISSUE TITLE
Imperium - Inquisition: missing Ordo specific psychic powers

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#5991]
**File/Catalogue:** Inquisition 

**BattleScribe version:** 2.03.

**Platform:** Android

**Description:** 
Ordo specific psychic powers are not showing. I'd love to choose "Psychic Veil" for Eisenhorn, but I cannot :frowning_face:

**Comment by WindstormSCR** [comment]
Specific issue for named characters
