### ISSUE TITLE
Death Korps can't use heirlooms of conquest anymore

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#5993]
**File/Catalogue:**  ForgeWorld Death Korps of Krieg

**BattleScribe version:** 2.03.12.320

**Platform:** Android

**Dropbox:** No

**Description:**
Although it's a Character with Regiment Keyword, neither Marshall nor field officer can use a heirloom of conquest If Chosen as Warlord.

**Comment by Mad-Spy** [comment]
Battlescribe Link bug

**Comment by alphalas** [comment]
Rolled into #6315
