### ISSUE TITLE
Dark Angels: Primaris Lieutenant Plasma pistol option 

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#5994]
File: Imperium - Dark Angels.catz

BattleScribe version: 2.03.06

Platform: Windows

Dropbox: No

Description: Primaris Lieutenant should be allowed to have bolt pistol and plasma pistol, but it's not currently possible in the catalogue.

"- any model may either replace its bolt pistol with a plasma pistol, or take a plasma pistol in addition to its other weapons."

and FAQ's hasn't said anything about it. and it is RAI and not miss type.

**Comment by Mad-Spy** [comment]
Primaris Lieutenants definitely have this option in the current release.
