### ISSUE TITLE
Imperium - Space Marines: Can't take a relic after selecting a Warlord

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5998]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.12

**Platform:** Android

**Dropbox:** No

**Description:** When creating a space marine list with one relic selected, the app gives an error saying a maximum of zero relics are allowed. When I select the stratagem to have an extra relic, it then allows me to have two relics without giving an error message.

**Comment by williamcaw** [comment]
When selecting a chapter the relics are set to  minimum  1.  but can’t be selected for it generates multiple chapters relics to be selected from other chapters.

**Comment by WindstormSCR** [comment]
This is due to a current BS bug, a workaround might be implemented, but does not work properly either, so release of the workaround was postponed while the app developer works on a fix.

**Comment by acebaur** [comment]
Appears to be working properly for me now
