### ISSUE TITLE
Chaos - Chaos Knights: Selection of Traitoris Lance not recognized and does not meet validation requirements

### ISSUE THREAD

**Issue by cqvo** [BSData/wh40k#6000]
**File/Catalogue:** Chaos - Chaos Knights v27

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** 
Validation checker does not recognize any number of selections of Character (Traitoris Lance). Additionally, the message requesting "must have 1 more selections of Character (Traitoris Lance)" appears 13 times in a row.

**Comment by Mad-Spy** [comment]
The repeated message is fixed in the latest version of BS (2.03.08 on Windows). However, there still appears to be a app bug causing it to not get validated properly. As it's not a data issue, I am closing this ticket.
