### ISSUE TITLE
Faith and Fury updates?

### ISSUE THREAD

**Issue by sassmcsass** [BSData/wh40k#6001]
**File/Catalogue:** Chaos Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Is anyone volunteering to update for the Psychic Awakening Faith and Fury for Saturday? All of the stuff has leaked, so it could get done early and be ready to go if anyone had time on their hands.

**Comment by Mad-Spy** [comment]
I will be handling it when I have time as per the usual process.
