### ISSUE TITLE
Chaos - Chaos Space Marines: Unable to select missile launcher and second ranged weapon for Helbrute

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6008]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.13

**Platform:** Android

**Dropbox:** Yes

**Description:** The replace with missile launcher option is missing for Hellbrute fist. Choosing one under the Multi-melta in addition to another ranged weapon causes an error.

**Comment by Mad-Spy** [comment]
Not missing, just not validating correctly due to an app bug. Fixed in the next release.
