### ISSUE TITLE
Imperium - Inquisition: Plasma pistol cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6013]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.14

**Platform:** Android

**Dropbox:** No

**Description:** Inquisition Acolytes can now take Incinerators for 20pts and plasma pistols are 5pts not 7

**Comment by Dunamis55** [comment]
Incinerators are only for Inquisitors.
