### ISSUE TITLE
Imperium - Inquisition: Ordo Relics not appearing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6014]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.13

**Platform:** Android

**Dropbox:** No

**Description:** Hi, the Hereticus & Malleus relics are not listed.

**Comment by Mad-Spy** [comment]
Hereticus relic appears correctly if you select Hereticus and an Inferno pistol.
Malleus relic appears correctly if you select Malleus and a power sword.

Tested with Inquisition v31 and BS 2.03.15 on Android and BS 2.03.09 on Windows.
