### ISSUE TITLE
Hellfoeged Rapier Canon, chaos space marines, missing abilities 

### ISSUE THREAD

**Issue by Type-40** [BSData/wh40k#6018]
**File/Catalogue:** 
Chaos - Chaos Space Marines.cat
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 

Hellforged rapier canon from forge world, chaos space marines, heavy,  is missing these abilities

Daemon Unleashed: A Hellforged Rapier gains this ability if all Chaos Space Marine Crewmen in the same unit are slain. While a Hellforged Rapier has this ability,it must move as far as possible directly towards the nearest visible enemy unit during the Movement phase(it does not have to Advance, but may do so if the controlling player wishes) ,it  may fire normally in the Shooting phase, even if no friendly Chaos Space Marine Crewmen are within 6" and must declarea Charge in the Charge phase if there are any enemy units within 12" at the beginning of that phase.

and 

Artillery:A Hellforged Rapier can only fire its ranged weapon if a friendly LEGION Chaos Space Marine Crewman model from the same unit is  within 3". A single Chaos Space Marine Crewman can not operate multiple Hellforged Rapiers in this way in a single turn. If  all of the Chaos Space Marine Crewmen from the same unit within 6" of a Hellforged  Rapier are slain,it  loses the Artillery ability and gains the Daemon Unleashed ability, and operates under the rules of that ability instead.

**Comment by Mad-Spy** [comment]
Both of these abilities _are_ listed in the output, although Daemon Unleashed is named incorrectly. I've fixed the name.
