### ISSUE TITLE
Chaos Space Marines Helbrute and Sonic Dread weapon options

### ISSUE THREAD

**Issue by Blacknar** [BSData/wh40k#6027]
**File/Catalogue:** Chaos - Chaos Space Marines v112 

**BattleScribe version:** 2.03.09.137

**Platform:** Windows and iOS

**Dropbox:** Yes

**Description:** When attempting to add weapon options onto the Hellbrute or the Sonic Dreadnaught, it wrongly identifies the missile launcher as a muli-melta option when it can be used to replace the cc weapon arm only.

**Comment by Mad-Spy** [comment]
This is just how it's been implemented. You can replace either arm with a missile launcher and the validation was easier to implement if the ML is in that group.

I've now fixed the invalid error message which appears if you try to select an ML and another ranged weapon.
