### ISSUE TITLE
Imperium - Space Marines: Tor Garadon cannot be selected as Warlord

### ISSUE THREAD

**Issue by Melmarkian** [BSData/wh40k#6037]
**File/Catalogue:** Imperium Space Marines - Imperial Fists

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The Imperial Fists character Tor Garadon doesn´t have the option Warlord when added to your list.

**Comment by acebaur** [comment]
Will be fixed by this weekend
