### ISSUE TITLE
Imperium - Deathwatch: Armoury of the Watch Fortress doesn't correctly allow Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6040]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.10

**Platform:** Android

**Dropbox:** No

**Description:** When hq is not warlord, giving charactor relic creates alerts, even if i selected additional relic (armory of watch fortress).

**Comment by Mad-Spy** [comment]
Modifier is using link instead of actual item

**Comment by corrinavatan** [comment]
May have already been identified, but using Armory of the Watch Fortress for 1 cp, and giving 2 relics (1 for the Watchmaster selected as Warlord, another for the Primaris Captain via the Armory Strat) getting an error too many are selected.

**Comment by Mad-Spy** [comment]
Fixed in Deathwatch v82
