### ISSUE TITLE
Imperium - Space Marines: Incorrect text for Marksman's Honours

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6042]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Vanguard Warlord Trait description of marksman's honours is wrong. As of the new Codex the trait adds only 1 dmg to the range weapon characteristics ( except for grenades) and no more rerolls.

**Comment by acebaur** [comment]
Will be fixed by this weekend
