### ISSUE TITLE
Ork Boyz Stratagem upgrades add CP instead of deducting it

### ISSUE THREAD

**Issue by MechMK1** [BSData/wh40k#6043]
**File/Catalogue:** Orks.cat

**Description:** "'Ard Boyz" and "Scar Boyz" add 2 CP and 1 CP respectively, instead of deducting it. The internal description sets cost at a positive value, while it should be a negative value.

**Comment by Guy-Markman** [comment]
Fixed it in #6048

**Comment by MechMK1** [comment]
@Guy-Markman Hey, I already created PR #6044 that fixes the issue. I dunno if it'd be duplicate work
