### ISSUE TITLE
Space Marines - Captain in Cataphractii Armour has incorrect points cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6045]
**File/Catalogue:** Space Marines v121

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Captain in Cataphractii Armour costs 93 points, but should cost 95 points.

**Comment by Mad-Spy** [comment]
Actually it should cost 99pts (93 base + 2 for bolter + 4 for power sword). It correctly shows this cost after being added to a Roster in 2.03.10 on Windows.
