### ISSUE TITLE
Imperium - Dark Angels, Eliminators

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/wh40k#6047]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

Eliminators or Dark Angels should use the new datasheet found in Codex Space Marines (ie should have access to Las-Fusils and other new abilities), as per the Space Marines Summer Update found here:

https://www.warhammer-community.com/2019/08/16/space-marines-new-rules-for-non-codex-chaptersgw-homepage-post-3/

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/69920887-91f63f00-148d-11ea-958e-60c063a01dc5.png)
