### ISSUE TITLE
Imperium - Space Marines: Blood Ravens should no longer have Relentless Seeker

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6052]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.06

**Platform:** Mac

**Dropbox:** No

**Description:** Imperium; Space Marines; Blood Ravens: The Chapter lost its tactics(Relentless seeker) that it gained from the White Dwarf July 2019 issue during the summer update/FAQ/Errata, but it kept everything else(Stratagem, relic, and Gabriel Angelos). It's currently stacking chapter tactics.

**Comment by acebaur** [comment]
Will be fixed by this weekend

**Comment by Haddix239** [comment]
Not sure what FAQ this was in. Summer FAQ doesn't mention Relentless Seekers.
