### ISSUE TITLE
Chapter Approved 2019 Edition (+ Munitorum Field Manual)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6054]
A new GW book, released on 2019-12-07.

It's sold as a two-book bundle:
* Chapter Approved 2019 Edition
* Munitorum Field Manual 2019 Edition (see #6086 for progress)

https://www.games-workshop.com/en-PL/Chapter-Approved-2019-EN

---

Please do not unnecessarily comment. This is a reference issue. Any discussions or comments should go into new issues. Also, we do have access to the source material, no need for posting book contents.

**Comment by buckeyede06** [comment]
Craftworld Changes: Units cost ( without gear )

Autarch with swoopin hawk wings - 80
crimson hunter - 128
crimson hunter exarch - 150
dark reaper - 9
falcon - 100
fire dragon - 8
fire prism - 140
howling banshee - 7
shining spears - 20
spiritseer - 55
striking scorpion - 8
vyper - 35

war walker - 35
warlock - 45
warlock conclaive - 35
warlock skyrunner - 60
warlock skyrunner conclaive - 48
warp spiders - 9
wraithknight - 285
wraithlord - 80
Characters cost
asurmen - 150
eldrad - 145
feugan - 125
illic - 65
bonesinger - 55


Ranged weapon cost

D-cannon - 35
D-scythe - 14
twin aml - 35
twin brightlance - 35
vibro cannon - 10
wraith cannon - 10

Melee weapon costs

biting blade - 2
ghostaxe - 4
forceshield - 2
scattershield - 15
shimmershield - 5

**Comment by buckeyede06** [comment]
Harlequins

Troupe master 60 (-10)
Shadowseer 110 (-15)
Troupe 11 (-2)
Skyweavers, zephyrglaive, haywire blaster 46 (-5)
Star weavers 80 (-19)
Voidreaver 90 (-13)
Nuerodisruptor 5 (-5)
