### ISSUE TITLE
Imperium - Space Marines: Company Champ should have "Superlative Duellist" and 4 Attacks

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6055]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** the space marine compagny champion is missing the "superlative duellist " rule

**Comment by Dunamis55** [comment]
In addition, the Company Champion also currently has an Attacks characteristic of 3, but should have an Attacks characteristic of 4.

**Comment by acebaur** [comment]
Will be fixed by this weekend
