### ISSUE TITLE
Imperium - FW Adeptus Astartes: Ivanus Enkomi Litanies need updating per FAQ

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6056]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Minotaurs Chaplain Ivanus Enkomi has incorrect Litanies. 
Currently he knows Litany of Hate, Litany of Hate (Minotaurs) and has access to one Litany of Battle. 

As per recent FAQ by GW Enkomi should know the Litany of Hate and two Litanies of Battle.

**Comment by WindstormSCR** [comment]
Needs fixing on root and in Codex SM, will remove base ability in Lib FW
