### ISSUE TITLE
Da Killa Klaw does not replace Power Klaw in wargear

### ISSUE THREAD

**Issue by MechMK1** [BSData/wh40k#6065]
**File/Catalogue:** Orks.cat

**Description:** According to the Ork Codex, "Da Killa Klaw" replaces the Power Claw. Upon selecting Da Killa Klaw, the Power Claw is not replaced and the roster still displays both weapons.

**Comment by Mad-Spy** [comment]
It is not possible to do this in the data files in any easily implementable way. No Relics actually replace the weapon in the output because of this limitation.
