### ISSUE TITLE
Psychic Awakening: Faith and Fury

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k#6067]
Released on 2019-11-29

Book 2 of Psychic Awakening "Faith and Fury" was released on 11/29/19
This has multiple updates for space marine and chaos space marine

(I see no entry started to track the updates being added)

**Comment by Mad-Spy** [comment]
Work is in progress.

**Comment by amis92** [comment]
@Mad-Spy if it's in progress, why not mark it as such, and keep it open? See #6054 as an example.

**Comment by acebaur** [comment]
The aim is to have this done by Friday in at least a functionable state

**Comment by DrTobogganMD** [comment]
Released today.
