### ISSUE TITLE
Chaos - Questor Traitoris: Tyrannical Court not working correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6070]
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** tyrannical court is not allowing for -3cp for slection of two models to take the  tyrannical court stratagem

**Comment by Mad-Spy** [comment]
This is due to a Battlescribe bug; raised as https://github.com/BattleScribe/Release/issues/106

**Comment by Mad-Spy** [comment]
Fixed in latest release of Battlescribe.
