### ISSUE TITLE
Imperium: Adeptus ministorum - new sista codex

### ISSUE THREAD

**Issue by TristanBlg** [BSData/wh40k#6073]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Hi, 
This is my first issue here sorry if i do some mistakes 

It seems that the sista's codex isn't up to date
I will work on soon

**Comment by CrusherJoe** [comment]
Tag team effort between me and @alphalas but it's done and will be in next release. I'm sure there's something we missed or got wrong -- just let us know and we'll fix it.
