### ISSUE TITLE
Imperium - Adeptus Mechanicus: Specialist Detachment WLTs not being made visible correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6074]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Mechanics rosters have access to the field commander stratagem but when selected no additional warlord trait from that specialist detachment can be given to a non named character, even though it should.

To fix the error the stratagem field commander should give the option to make a non named character in a specialist detachment use that detachments special warlord trait again

**Comment by Mad-Spy** [comment]
Problem is caused by a Battlescribe bug which causes the WLT selector to fail to appear due to being triggered from a link.
