### ISSUE TITLE
Necrons: Can't find Imotekh

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6077]
**File:** Necrons.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** In necron v55 there are still missing units including immotehk

**Comment by Mad-Spy** [comment]
OP: In general, you need to select the correct Dynasty to make Dynasty-specific characters like Imotekh appear. However, there are a number of Dynasty specific characters which do not appear when selecting a "Mixed" Dynasty and that needs fixing.
