### ISSUE TITLE
Warhammer Legends

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#6079]
Covers implementation of Legends content for all catalogues.

__Implementation Guidelines__

- For units whose entire datasheet is in the Legends PDF, affix [Legends] to the unit name.
- For units who have Legends-only wargear options, Either trigger a automatic suffix of [Legends] to units that have legends content in them or, in necessary, create duplicate units with the [Legends] suffix

__Imperium__

- [x] Adeptus Astartes
- [ ] Space Wolf
- [x] Deathwatch
- [x] Inquisition
- [x] Blood Angels
- [ ] Legion of the Damned
- [x] Astra Militarum
- [x] Grey Knights
- [x] Dark Angels
- [x] Adepta Sororitas

__Chaos__

- [x] Chaos Space Marines
- [x] Thousand Sons
- [x] Death Guard
- [x] Chaos Daemons

__Xenos__

- [x] Craftworlds
- [x] Drukhari
- [x] Tyranids
- [x] Orks

**Comment by TJ-paints-and-games** [comment]
Could you have it as an option in the No Force Org section? So they are hidden by default?

**Comment by MrRWJP** [comment]
I'd echo @TJ-paints-and-games's suggestion. Similar to the "Show Primaris only" in the Space Marine catalogue, have it as a No Force Org choice to show or hide them.

**Comment by miku2020** [comment]
you can use legends in any match. it just means that they do not get updates anymore

**Comment by alphalas** [comment]
Because legends are discouraged from play in competitive 40k

**Comment by amis92** [comment]
I'd like to say that *if* there will be any kind of switch for Legends, I'd only agree to an opt-in Hide Legends.

 The [Guideline #17](https://github.com/BSData/wh40k/wiki/Guidelines#17) still is in force. No hiding by default.

**Comment by p5freak** [comment]
> Because legends are discouraged from play in competitive 40k

I didnt know battlescribe was only for competitive 40k. Seriously, legends are still legal for open, narrative, and matched play.

**Comment by miku2020** [comment]
our GW also stated legends are allowed in tournaments

**Comment by alphalas** [comment]
@p5freak i think you and @miku2020 are confused exactly what we’re actually doing; please take this discussion to discord for further information.

**Comment by rtho782** [comment]
The Space Marines Legends PDF update increases the points for the Twin Plasma Gun (previously Index Imperium 1) from 20 to 22.

This impacts the Space Marine Razorback Index-Only weapon option of Lascannon+Twin Plasma Gun.

**Comment by amis92** [comment]
@Thairne @CrusherJoe @alphalas how's progress? Your catalogues still are unchecked.

**Comment by Thairne** [comment]
Ah yes yes... I think I had done everything except the Techmarine (fuck that one).
I think I'll just copy him over from SM...

**Comment by alphalas** [comment]
my cats should all be done?
