### ISSUE TITLE
Refresh data error - a file has already been added

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6087]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Tried to refresh data for 40K 8th edition file, and got error code. Says a file has already been added. Just never seen this before, so I thought it was worth reporting. Thanks much!

**Comment by amis92** [comment]
I can't reproduce it, and investigating json index from appspot confirms that everything is okay.

I can only guess: maybe you have a repository cloned? In that case you should not use app's update data, but only git sync. Or delete repository and keep using app update manager.
