### ISSUE TITLE
imperium - dark angels

### ISSUE THREAD

**Issue by evilodmin** [BSData/wh40k#6091]
**File/Catalogue:** imperium - dark angels

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Tactical and other old space marines costs 12pts, not 13, in CA2019

**Comment by miku2020** [comment]
just mere fellow community member. be patient they are doing all ca19. and as fellow DA player why report Marines only when azzy is 150 :D also devastators are 13 not 12.

**Comment by amis92** [comment]
Duplicate of #6086
