### ISSUE TITLE
Adepta Sororitas batch bug report

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6093]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Bugrep for Adepta Sororitas

Requirements for Canoness to hold Rod of Office is Boltgun and Powersword, not Bolt Pistol and Power Sword.
Priests (Missionaries and Preachers) can only take the Book of St Lucius relic.
Imagifiers can carry relics
Imagifiers should have the -1CP option to use the Venerated Saint stratagem allowing them to tell two tales (I guess it would function like Heroine in the Making currently does?)
Repentia Superior's can take a Bolt Pistol
Exorcists and Immolators can theoretically be equipped without Heavy Bolters by using the index wargear loadout. It wasn't Legend-ed out and looks like Legends stuff has been left in anyway (you've let Superiors continue to take Storm Bolters). There are the following loadout combinations:
-     Exorcist w/Missile Launcher (Index)
      -     Exorcist w/Missile Launcher & Storm Bolter (Index)
      -     Exorcist w/Missile Launcher & Heavy Bolter (Codex)
-     Exorcist w/Conflagration Rockets & Heavy Bolter (Codex)
For Immolators it's just the same as the Index loadout options but you can either take a Storm Bolter or a Heavy Bolter

Haven't found anything else so far, but I'll let you know if I do.

**Comment by UraharaKisuke88** [comment]
Junith has disappeared
Preachers have the same loadout options as missionaries

**Comment by UraharaKisuke88** [comment]
I'm just going to go ahead and fix these for you.

**Comment by natecross1990** [comment]
Sorry to add to your woes but as I am aware the canoness data sheets equipment wording is a little confusing, I feel I should point out that the canoness with Rod of office mini from the army set actually has a plasma pistol modelled on her back (under her Cape!). So I think that means you Can change the boltgun for a different pistol/ranged weapon if you wanted to. At the moment if you select a different weapon other than boltgun it throws up validation errors.

**Comment by UraharaKisuke88** [comment]
Ah hilarious story, the model in the Army Box can’t actually be fielded as per the rules in the Codex. The Canoness can only take a Rod of Office if she has a Boltgun and Power Sword.

Expect this to get fixed in the FAQ though.

**Comment by natecross1990** [comment]
Its a silly thing really as she clearly hasn't got a boltgun but has got a plasma pistol hidden under her habit. Probably won't be an FAQ for a while yet though. Did you spot the mistake on unit size for Mortifiers in the unit points summaries?

Also arco flaggelants can be 2+1 endurant. Right now it wil only allow 3 flaggelants minimum and an endurant on top to avoid validation. 
Mortifiers are the same, you can take an anchorite instead of a Mortifiers if you like. At the moment you need to have 1xMortifier And 1xAnchorite to avoid invalid warnings

Canoness rod of office 'ability' doesn't seem to display either.

**Comment by UraharaKisuke88** [comment]
> Also arco flaggelants and Mortifiers can be 2+1 endurant. Right now it wil only allow 3 flaggelants minimum and an endurant on top to avoid validation.

> Canoness rod of office 'ability' doesn't seem to display either.

Awesome we’ll add them to the list for next patch. Let me know if you find anything else.

**Comment by natecross1990** [comment]
Just spotted the description for relic 'Iron Surplice of Saint Istaela' doesn't specify that unmodified WOUND rolls of 1, 2 or 3 always fail.
