### ISSUE TITLE
Bug Report: Cannot select relics for Dark Angel warlord

### ISSUE THREAD

**Issue by MechaLenin** [BSData/wh40k#6102]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes/No

**Description: Relic selection windows doesnt appear after selecting warlord.

**Comment by Thairne** [comment]
A fix for this was released 10 days ago... Did you update your data?

**Comment by MechaLenin** [comment]
> A fix for this was released 10 days ago... Did you update your data?
"Dark angels get updates too". Yeah, it was updated version. I used android. Need to go to bed. In couple hours i can provide more details if it will help.

**Comment by Mad-Spy** [comment]
Relic selection definitely appears for both the Warlord and other characters using Android 2.03.16 and DA v119.
