### ISSUE TITLE
Adepta Sororitas v74 Bugrep

### ISSUE THREAD

**Issue by UraharaKisuke88** [BSData/wh40k#6119]
- [x] Mortifiers missing a ‘Decrement If’ rule to allow Anchorite in MSU.
- [x] Ability description missing for rod of office.
- [x] Order lock Junith
- [x] Make Repentia Superior Bolt Pistol optional
- [x] Acts of Faith typos
- [x] Change name of Missionary weapon choice from ‘Either’ and add min 1
- [x] Exorcist Missile Launcher typo shots typo
- [x] Hand flamers need to have points changed to 1 per

**Comment by alphalas** [comment]
![AE99E69F-F2D7-4EC7-9933-4AF94DBC31A1](https://user-images.githubusercontent.com/15703066/70522563-556eb700-1b0f-11ea-832a-4f1f9433c2c2.png)
Arcos work correctly so just morts need changed.

**Comment by UraharaKisuke88** [comment]
- Combine Arco-Flagellants
- Order lock Junith
- Make Repentia Superior Bolt Pistol optional
- Acts of Faith typos

**Comment by CreepingDementia** [comment]
Hand flamers need to have points changed to 1 per

**Comment by Kal451** [comment]
For Desktop version

Canoness
 im not seeing rod of office at all
"may have" options disappear if canoness isnt armed with a chainsword

**Comment by amsouthey** [comment]
The  "Ranged Weapons" options for Sisters Superior wrongly includes a storm bolter. Barring an FAQ, this is sadly a Special Weapon and they don't get access to it.

**Comment by Ravien** [comment]
Seems repentia superior has some artifacts from the old list. Before the update, when you added a unit of sisters repentia, mistress of repentence would vanish from the elites list. The same is still happening, instead of it not counting for a detachment slot like it should now. 

It is still counting as an elite slot as well as throwing an error for elites cannot have any selections of Repentia Superior (hidden)

**Comment by alphalas** [comment]
@Ravien that’s because you then have to select the repentia Super from the NFO area instead of elites

**Comment by alphalas** [comment]
@amsouthey please consult the flow chart of index options from the designer commentary; it is still a thing unfortunately.

**Comment by alphalas** [comment]
@Kal451 The May take options disappear when you don’t have a chainsword, because you are required to have a chainsword to take them.

**Comment by CrusherJoe** [comment]
@alphalas you mean Rod of Office is required if you take boltgun and power sword. It's not optional, if you have a power sword and boltgun you ALSO have a Rod of Office. 😃

**Comment by daveg92** [comment]
Canoness with a Boltgun and Power sword should be able to take the rod of office.

"If this model is equipped with 1 boltgun and 1 power sword, it additionally has a rod of office"
pg 77
