### ISSUE TITLE
Astra Militarum point values not updated

### ISSUE THREAD

**Issue by DaManWilo** [BSData/wh40k#6120]
The recent update 1.4.0 has not included the points changes for the Astra Militarum for CA2019.
Lascannons, Astropath, Mortars, Punishers have all remained unchanged

**Comment by amis92** [comment]
#6086 - indeed it seems it was marked as done but not actually done.

**Comment by Mad-Spy** [comment]
@amis92, looks like they got reverted because we were going to do an earlier release which we cancelled, and then not added back in again!

**Comment by miku2020** [comment]
same with DA. but i guess it is all? ideas how long until fix?

**Comment by alphalas** [comment]
Rolled into #6135
