### ISSUE TITLE
Blood Angels Missing Options

### ISSUE THREAD

**Issue by sfPanzer-BnC** [BSData/wh40k#6121]
**File/Catalogue:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** /No

**Description:** 
Intercessors of any kind are missing options: Thunderhammer, Hand flamer.

"Honoured of Baal" option missing for successor chapters.

**Comment by alphalas** [comment]
Rolled into #6131
