### ISSUE TITLE
Dark angels CA19 Update missing some point changes

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6122]
**File/Catalogue:** 

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** None of the pts has been updated in Dark angels Data.

**Comment by Mad-Spy** [comment]
Dark Angels v119 definitely has point changes from MFM2019 in it. Please give specific examples of where there are errors.

**Comment by miku2020** [comment]
this is just few i know out of my head. 
asmodai 110
azrael 150
belial 125
primaris lieutenant 65 (base)
sammael in sableclaw 200
sammael in corvex 140
of my 4,5k list nothing changed. compared to pre CA19

![image](https://user-images.githubusercontent.com/2915330/70519778-270bce80-1b45-11ea-88a0-2dd5736dfc0a.png)

**Comment by SpaceJS** [comment]
it seems like the standard marine changes did not come through

**Comment by Thairne** [comment]
You're using V117. Latest Release is v119.

**Comment by Thairne** [comment]
![grafik](https://user-images.githubusercontent.com/8590840/70521706-f9705680-1b3f-11ea-86ca-b028914bb7ac.png)

**Comment by miku2020** [comment]
how to change to it if update did not change that? do i have to redo whole list

**Comment by miku2020** [comment]
okay i had to reopen the file. weird.

**Comment by jambo0r** [comment]
Hi,

There are some points updates missing for DA in today's release. Not many though. 

Typhoon missile launcher from 38pts to 32pts

Auxillary Grenade Launcher for intercessors from 0 to 1pt

Deathwing Knights from 35pts to 33pts

Everything else is right, at least for my list :)

Thanks for the hard work updating these!
