### ISSUE TITLE
Chaos - Death Guard: Foetid Bloat Drone Plague Probe points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6123]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Plague Probe for Foetid Bloat Drone is 5pts now according to CHA2019

**Comment by Borovil-cz** [comment]
Plague Probe for Forge World Greater Blight Drone still 25 pts, so only FoetidBloatDrone  Plague Probe Changed

**Comment by Mad-Spy** [comment]
Fixed in Death Guard v76
