### ISSUE TITLE
Blood Angels Wrong Points

### ISSUE THREAD

**Issue by sfPanzer-BnC** [BSData/wh40k#6124]
**File/Catalogue:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:**
Assault bolters still at 10p instead of 8p

Boltstorm gauntlet still at 22p instead of 12p

Flamestorm cannon still at 30p instead of 25p

Grav-cannon and grav-amp still at 28p instead of 20p

Grav-gun still at 12p instead of 10p

Inferno pistol still at 7p instead of 9p

Special issue boltgun still at 2p instead of 0p

Typhoon missile launcher still at 38p instead of 32p

Dreadnought combat weapon still at 30p instead of 20p

Lightning Claw still at 8p instead of 6p (check the paired variant too)

Combat shield still at 4p instead of 1p

**Comment by alphalas** [comment]
Rolled into #6131
