### ISSUE TITLE
Chaos Knights - Weapons points not updated

### ISSUE THREAD

**Issue by PedroDeOro** [BSData/wh40k#6125]
**File/Catalogue:** Chaos - Chaos Knights

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** 

- Avenger Gatling cannon: 99 points ->85 points (page 30)
- Rapid-fire battle cannon: 92 points ->90 points (page 30)

Chapter approved 2019. Monitorum field manual.

**Comment by Mad-Spy** [comment]
You can only buy those weapons with attached co-axials.

Avenger (85pts) + Heavy Flamer (14pts) = 99pts
Cannon (90pts) + Heavy Stubber (2pts) = 92pts.

Costs are correct.

**Comment by PedroDeOro** [comment]
True, sorry for my mistake.
