### ISSUE TITLE
Imperial Knight points not updated

### ISSUE THREAD

**Issue by exet1530** [BSData/wh40k#6126]
**File/Catalogue:** Questor Imperialis

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Looks like the Imperial Knights missed out on the update for CA19. I think the only changes are Armigers going down and Gallants going up.

**Comment by Mad-Spy** [comment]
Looks like the same issue as #6120. Changes were reverted and then not merged again before release.

**Comment by DrTobogganMD** [comment]
Yea ... I kind of committed a file that had no changes. Fixed! Gonna be another release today.
