### ISSUE TITLE
Necrons points not updated

### ISSUE THREAD

**Issue by furka** [BSData/wh40k#6132]
**File/Catalogue:** Necrons

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Looks like Necrons points haven't been updated.

It looks like the changes were reverted but not merged back in. Even thought he version changed from 55 to 56

**Comment by furka** [comment]
appears to be similar to #6126 and #6120

**Comment by DrTobogganMD** [comment]
Yea ... I kind of committed a file that had no changes.  Fixed! Gonna be another release today.
