### ISSUE TITLE
Definitely Missing Dark Angels CA19 Changes 

### ISSUE THREAD

**Issue by jambo0r** [BSData/wh40k#6133]
**File/Catalogue:** Warhammer 40,000 v.1.4.0 - Imperium - Dark Angels v119

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** 

Hi,

Confirmed that there are some CA19 points updates missing for Dark Angels in today's release. Not many though.

- Typhoon missile launcher for ravenwing land speeder from 38pts to 32pts

- Auxillary Grenade Launcher for intercessors from 0 to 1pt

Everything else is right, at least for my list :)

Would also be nice if Ravenwing Black Knights could be updated so that each model in the unit is not listed individually on the data sheet. 

Thanks for the hard work updating these.

**Comment by miku2020** [comment]
DW knights are correct because stormshield is counted in it

**Comment by Mad-Spy** [comment]
Tactical squad: model - 13 -> 12
Venerable Dreadnought: model - 77 -> 80
Dreadnought & Venerable: Dreadnought combat weapon - 30 -> 20
Dreadnought & Venerable: Heavy plasma cannon - 17-> 16

**Comment by jambo0r** [comment]
> DW knights are correct because stormshield is counted in it

Hrm, guessing you are right but then we're they costed wrong in battle scribe previously? 

Base model definitely got 2pt reduction in CA19 but then overall unit cost in battle scribe is the same as it was before the CA19 update.

**Comment by Mad-Spy** [comment]
@jambo0r,  Black Knights are (currently) individual because each one can choose whether it has a Corvus Hammer or not.

**Comment by Thairne** [comment]
Typhoon/Dread CCW will be changed in GST.
Ven Dread already was 80.

RW Knights have, I think, the old index option of not being equipped with a Corvus (for whatever reason anyone would do that however). I think we can get rid of that option since it is broken anyway... I presume noone ever did choose that option.
