### ISSUE TITLE
Dark angels few incorrect pts

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6134]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** I am listing few pts change from CA19 that have been missed in previous update

Intercessors: auxiliary grenade launcher - 0 -> 1 (sorry thairne. now it is changed in ca19)
Tactical squad: model - 13 -> 12
Venerable Dreadnought: model - 77 -> 80
Dreadnought & Venerable: Dreadnought combat weapon - 30 -> 20
Dreadnought & Venerable: Heavy plasma cannon - 17-> 16

**Comment by Mad-Spy** [comment]
Merged with #6133
