### ISSUE TITLE
Death Guard wargear Plague probe points cost is wrong

### ISSUE THREAD

**Issue by Jeva92** [BSData/wh40k#6137]
**File/Catalogue:** Chaos - Death Guard v75

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Points cost for Foetid Bloat drones Plague probe weapon has not been changed.

The price should have changed from 25 -> 20

**Comment by Mad-Spy** [comment]
Already fixed in #6123
