### ISSUE TITLE
Cyclone ML cost incorrect in several Marine catalogues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6138]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** Space wolves, Deatwatch and Blood angels Cyclone missile launcher is still 38 (or 40 with storm bolter), should be 32 (or 34 with SB). Typhoon missile launcher also 38, should be 32.

**Comment by Mad-Spy** [comment]
All moved to catch-all tickets.

BA #6131 
DA #6140 
SW #6141
