### ISSUE TITLE
DG Plague Probe incorrectly pointed

### ISSUE THREAD

**Issue by Redmoon45634** [BSData/wh40k#6139]
**File/Catalogue: Warhammer 40k Death Guard** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Death Guard Foetid Bloatdrone Plague Probe is 25pts when should be 5pts. Other points values appear to be correct for the rest of the units. Appears to have been missed in the review.

**Comment by Mad-Spy** [comment]
Already fixed in #6123
