### ISSUE TITLE
Imperium - Deathwatch: Missing Deathwatch point changes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6140]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.13.06

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch Primaris Bolt weapons are at pre-CA2019 costs for all Primaris units

Bolt Rifles/Stalker Bolt rifles should now be 0 (shows as 1)
Auto BR should now be 1 (shows as 2)
Master-crafted variants should be 5 (show as 6)
Twin bolt gun (bikes) currently costs 4pts, should have been reduced to 2pts with CA2019.
Cyclone ML cost not updated (should be 32)
All combi-weapons need reducing

**Comment by corrinavatan** [comment]
In addition, have found the following points missed as well:

All Combi-Weapons (Combi-Melta, -Flamer, Plas, Grav) are 1 point more than they should be, with the exception of the Stormbolter being changed to the correct points cost.

Corvus Blackstar base cost still coming out to old CA 2018 cost (should be down 10)

Cyclone Missile Launcher for a Heavy Weapons Terminator coming at old costs (Cyclone ML on a Mortis Contemptor or Relic Contemptor showing correct cost)

**Comment by LaryPL** [comment]
Hej,
Artemis should cost 100 points (now it's 115).
