### ISSUE TITLE
Space Wolves missed CA19 pts.

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6141]
**File/Catalogue:** Imperium - Space Wolves v99 

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:**
few pts that i found to be incorrect

Helfrost cannon: 25 -> 17
Frost Axe - 10 -> 6
Frost Sword - 7 -> 5
Great frost axe - 17 -> 9
Great wolf claw - 45 -> 20
Dreadnought combat weapon - 32 -> 20
Wolf claw - single is 7 pair is 11
Wolf guard Battle leader on Thunderwolf: model 104 -> 86
Cyclone Missile Launcher 38 -> 32
Assault bolter 10 -> 8
Iron priest TH should be 40pts
Frost sword is 7, should be 5.
Great frost axe is 17, should be 9.
Landraider redeemer flamestorm cannon needs reducing from 30 to 25 (60 to 50).
Intercessor auxiliary grenade launcher needs to be 1 point.

And one incorrect Loadout option 
Long Fang Pack leader may replace it's chainsword with power sword, axe, fist only. no frost weapons ect.

**Comment by miku2020** [comment]
![image](https://user-images.githubusercontent.com/2915330/70529486-56c4d180-1b59-11ea-838b-e98ebe085729.png)
![image](https://user-images.githubusercontent.com/2915330/70529516-69d7a180-1b59-11ea-9f82-6ceeb279b694.png)

**Comment by Mad-Spy** [comment]
@miku2020, what exactly are you trying to report in your comment?

**Comment by miku2020** [comment]
single wolf claw in battle leader options is 11 it should be 7. pair is 11 like it is. 
TWC has 2x7 wolf claws it should be just 11 there's no option to take pair instead
