### ISSUE TITLE
Adeptus Custodes Storm Shield point costs swapped (already fixed)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6143]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Adeptus Custodes troop Storm Shield is 10 points, should be 5 points (it is only 10 points on characters).

**Comment by tekton** [comment]
Duplicate of #6118
