### ISSUE TITLE
AM changes were not added due to - Revert "Astra Militarum MFM 2019 Points Update" 8 days ago. 

### ISSUE THREAD

**Issue by AlexGardner94** [BSData/wh40k#6144]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

hey  @CrusherJoe  looks like you made the change but commited the revert.

**Comment by alphalas** [comment]
Duplicate #6135
