### ISSUE TITLE
 Chaos- Chaos Space Marines.catz

### ISSUE THREAD

**Issue by Nighthawke211** [BSData/wh40k#6153]
**File/Catalogue:** 
Chaos- Chaos Space Marines.catz
**BattleScribe version:** 2.03.
2.03.10
**Platform:** Windows/iOS/Android/Mac/Linux
window
**Dropbox:** Yes/No
no
**Description:** Detailed issue description.
heldrake claws went from 17p to 0p in CA2019. these have not been changed.

**Comment by Mad-Spy** [comment]
Already fixed.
