### ISSUE TITLE
Death Guard missing Point Change

### ISSUE THREAD

**Issue by Nomada86** [BSData/wh40k#6155]
**File/Catalogue:** Death Guard

**BattleScribe version:** 2.03.

**Platform:** Windows/

**Dropbox:** Yes/No

**Description:** For the Foetid Bloat Drones, the Plague Probe that comes automatically with, has had a point reduction from 25 points to 5. Making the drone by default 20 points cheaper. This is not represented yet.

**Comment by Mad-Spy** [comment]
Already fixed, as per the several other issues which have been closed today. Please check recent issues before logging.

**Comment by Nomada86** [comment]
well excusez moi,
Have read through all the open articles, couldn't find it (stupid me), and although i've tried to update several times still same error. Thats why I created the log. Sorry for the inconvenience though and thx 4 the feedback.
