### ISSUE TITLE
Imperium Blood Angels - issues

### ISSUE THREAD

**Issue by jmkk11** [BSData/wh40k#6156]
No Hero of the chapter to assign warlord trait to non warlord character.
Intercessors require veteran intercessor option.
Auxhillary grenade launchers should be 1 pt.
Death Company Intercessors allow too many instances of Thunder Hammers (should be 1 per squad, currently allows 1 per model)
Death Company Intercessors missing option to take second Chainsword
Death COmpany Intercessors missing Auto-bolt rifles

**Comment by sfPanzer-BnC** [comment]
@jmkk11 update your file and check your selections
veteran intercessor option is there
auxillary grenade launchers cost 1p
DC Intercessors can take only one Thunderhammer (are you looking at regular DC perhaps)
DC Intercessors can't take a second Chainsword
DC Intercessors can take Auto Bolt rifles

**Comment by Mad-Spy** [comment]
Apparently all of these are non-issues.
