### ISSUE TITLE
Imperium Blood Angels - Astorath should be able to take 3 litanies

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#6159]
**File/Catalogue:**  Imperium Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Astorath can only take 2 litanies. Should be able to take 3.

**Comment by Mad-Spy** [comment]
Merged into #6131
