### ISSUE TITLE
Imperium Blood Angels - wording of Savage Echoes is hilariously wrong

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#6160]
**File/Catalogue:** Imperium Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** The Savage Echos wording contains "... performs at her work intervention...". It should be "...performs a Heroic Intervention...".

**Comment by Mad-Spy** [comment]
Merged into #6141
