### ISSUE TITLE
Imperium Blood Angels - Death Company Intercessor Issues

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#6162]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** Intercessor with CCW does not have the option for Thunder Hammer (only Chainsword, Power fist and Power sword). Also doesn't have the option to replace bolt rifle with hand flamer or chainsword.

**Comment by Mad-Spy** [comment]
Already raised into #6131
