### ISSUE TITLE
Plague probe Incorrect points - Chaos - Death Guard.cat

### ISSUE THREAD

**Issue by pabloarturot** [BSData/wh40k#6170]
File/Catalogue: Chaos - Death Guard.cat 

BattleScribe version: 2.03.06 

Platform: IOS

Dropbox: No

Description: Plague probe Incorrect points cost should be 5 pts not 25 pts. Affects  Foetid Bloat-drone profile.

**Comment by Mad-Spy** [comment]
Already fixed.
