### ISSUE TITLE
Skarbrand, Bloodthirster variants points unchanged

### ISSUE THREAD

**Issue by buzzdady** [BSData/wh40k#6173]
Skarbrand and the three Bloodthirster variants haven’t had their points reduced. Thanks!

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
These changes are definitely in the released version (Daemons v70). Please ensure that you have updated your data set to v1.4.0.

**Comment by buzzdady** [comment]
It’s at v1.4.0 and I’ve duplicated my roster, is there an additional step I’ve missed?
