### ISSUE TITLE
Imperium - Space Wolves: Impulsor entry missing some abilities and default selections

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6179]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** Impulsor entry is missing Assault Vehicle, Hover Tank and Repulsor Field abilities.  Default of weaponry of 2 Storm Bolters is not selected, and an option to take no Side Weapons is available, this is not correct, it must be either Storm Bolters or Fragstorm Grenade Launchers.  The Impulsor entry for Space Marines is correct.

**Comment by CrusherJoe** [comment]
Fixed -- good catch!
