### ISSUE TITLE
Chaos - Thousand Sons - Tzaangor Enlightened

### ISSUE THREAD

**Issue by roperklacks** [BSData/wh40k#6183]
**File/Catalogue:** Chaos - Thousand Sons

**BattleScribe version:** 2.03.10/2.03.16

**Platform:** Windows/Android

**Dropbox:** No

**Description:** Thousand Sons Tzaangor Enlightened weapon option point labels are showing the old values. It appears the actual values are correct it's just the label.

**Comment by Mad-Spy** [comment]
There's no "label" for the costs; BS just displays them. I think there's a display issue where the main list doesn't update immediately. Change something on the unit and it'll update the costs.
