### ISSUE TITLE
Heldrake claws points value incorrect

### ISSUE THREAD

**Issue by cqvo** [BSData/wh40k#6184]
**File/Catalogue:** Chaos Space Marines

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Heldrake claws should be zero pts as of CA 2019.

**Comment by Mad-Spy** [comment]
Already fixed, as per the 4 other issues raised for this today. Please check closed issues before posting if you're doing it direct on Github.
