### ISSUE TITLE
Chaos - Chaos Space Marines: Sonic Dread validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6187]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Displays error when a sonic dreadnought equips a multi melta arm weapon and a missile launcher, despite it being allowed.

**Comment by Mad-Spy** [comment]
Fixed this and Ferrum Infernus validation
