### ISSUE TITLE
Imperium - Adeptus Mechanicus: Battle-forged CP Maximum is at 0 instead of 1

### ISSUE THREAD

**Issue by JCRobertson** [BSData/wh40k#6205]
**File/Catalogue:** Imperium - Adeptus Mechanicus 

**BattleScribe version:** 2.03.06

**Platform:** iOS

**Dropbox:** Yes

**Description:** @Thairne Under No Force Org Slot, Adding Battle-forged CP always makes the list invalid because the maximum is set to 0. It should be set (as I understand it) to 1. Again thanks for all the hard work.

**Comment by Thairne** [comment]
Works for me.
You actually need to be Battle Forged, having an unbound detachment disallows that selection.

**Comment by JCRobertson** [comment]
That was it, have an unbound detachment for an inquisitor. Thanks!
