### ISSUE TITLE
Imperium - Astra Militarum

### ISSUE THREAD

**Issue by Wraith0** [BSData/wh40k#6206]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Tempestus Scions have incorrect cost, CA2019 dropped points from 9ppm to 7ppm.
edit: Astropath points incorrect 15pts base instead of 26pts.
Edit: Tempestor Prime 35pts base instead of 40pts
Mortar 9pts instead of 5pts

**Comment by AbsoluteManiac** [comment]
Identical problems to original poster, in addition it seems that none of the points have been updated from CA19 for the astra militarum roster
