### ISSUE TITLE
Imperium - Imperial Knights.catz

### ISSUE THREAD

**Issue by Wraith0** [BSData/wh40k#6209]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Knight Gallant incorrect points cost - 305 instead of 285 base points cost

**Comment by Mad-Spy** [comment]
Fixed in v1.4.1 (IK v46).
