### ISSUE TITLE
Chaos - Chaos Space Marines: Daemon prince cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6215]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Demon Prince wings were dropped to 9 points in Chapter Approved 2019. They are still showing as 24 points in BS

**Comment by Mad-Spy** [comment]
Already fixed.
