### ISSUE TITLE
Aeldari - Vibro Cannons wrong points cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6217]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Eldar Vibro Cannons points not been updated. Showing as 15 points but they dropped to 10 points in Chapter Approved 2019.

**Comment by KalChoedan** [comment]
Duplicate of #6192
