### ISSUE TITLE
Inquisition Issues - Hector Rex with CA 2019 & WD

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#6218]
**POINTS**
I know this one has been raised before (by me!), but I think now is the time to revisit it.

CA19 has no entry for Storm Shields for Inquisitors, so this should not cost 10pts. It has been raised that 'Storm shields cost 10pts, so Hector's should cost 10pts', but several factions don't have a Storm Shield cost. From CA19, the following:
Space Marine/Custodes Characters: 10
Space Wolf Cavalry: 5
Space Marine: 2
Sisters of Battle: 0
Imperial Guard: 0

If there's no clear points cost, it's worse if you just arbitrarily attribute the SM/Custodes Character cost to Hector Rex as he's neither a Space Marine nor a Custodes. FW didn't include the Storm Shield cost in CA19, and they also didn't include his weapon (Arias) - that defaults to 0 points.

**PSYCHIC POWERS**
Rexy is missing his Malleus power selection, Power through Knowledge, for the 5++ spell he should get access to as ORDO Malleus.

**WARLORD TRAITS**
He has no clear warlord trait and FW should probably have forced him to have one in Index Inquisition, but can we give him the current Inquisition selection (including the Malleus one) for the time being?

**Comment by Phuzzyhead** [comment]
"If there's no clear points cost" ... There is. It is 0 and would be 0 even if Inquisition had an entry for storm shields since he is a named character. Therefore his point cost includes wargear.

**Comment by alphalas** [comment]
@Phuzzyhead incorrect
![84C23AE2-DB75-450D-803F-5D823361389F](https://user-images.githubusercontent.com/15703066/70563583-7dd0d280-1b5c-11ea-916e-4eda5acbaf2c.png)

Notice the column very specifically says EXCLUDING wargear.

**Comment by Phuzzyhead** [comment]
@alphalas 
Lol,  my bad. Thx for the info mate.
Is this from 2019 CA? If it is, this really made it through 3 CA's now and tons of minor updates without getting fixed or even FAQ'd?! FW you drunk?!

**Comment by gitGremlin** [comment]
alphalas is right - they haven't included Wargear Costs with any of the name characters in Imperial Armour. They've also not included any costs for Hector's equipment, though, which leads me to assume it's all supposed to be free.
