### ISSUE TITLE
Grey Knights: Stormraven - Stormstrike

### ISSUE THREAD

**Issue by Phuzzyhead** [BSData/wh40k#6223]
Version 1.4.0
Stormstrike launchers have a check-box in latest data, but are not optional in the rules.
Selecting them adds 3x21=63 Points and entry reads 1 launcher and 2 launchers below that.

For reference, the Space Marines Stormraven's stormstrikes are fine.

**Comment by Phuzzyhead** [comment]
That was quick!
Thank you sir! :-)

**Comment by tekton** [comment]
@Phuzzyhead it's going to be live in the next push after the one that was this afternoon/evening- merge got weird :(
