### ISSUE TITLE
Blood Angels - Mephiston validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6224]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** It is telling me I can’t use Mephiston (Primaris) and the special BA litany.

**Comment by Mad-Spy** [comment]
Fixed in v1.4.1 (BA v107)
