### ISSUE TITLE
Elysian Drop Troops MFM Some Updates Missing

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#6225]
**File/Catalogue:** FW: Elysian

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Couldn't quite tell from the other reported issues whether these were highlighted so thought i'd throw a new one up, just incase!

Here's what i've found that is missing so far.

- Avenger Strike Fighter - Hellstrike Missile, Missile Launcher
- Valkyrie Sky Talon - Hellstrike Missile
- Lightning Strike Fighter - Hellstrike Missile
- Elysian Heavy Weapon Squad - Missile Launcher, Mortar
- Elysian Veteran and Command Squad Heavy Weapons - Missile Launcher, Mortar
- Operative Requisition Sanctioned

Apologies if they have already been fixed. Thanks for your work so far!

**Comment by CrusherJoe** [comment]
Operative Requisition Sanctioned is there, it's under "No Force Org Slot". I'll handle the other things right now -- thanks for the feedback!

**Comment by CrusherJoe** [comment]
Also -- in a rare event, the Elysian mortar remained 5 points, the missile launcher dropped to 10. So...yay, for once? Everything else is done. Thank you again!
