### ISSUE TITLE
Tyranids - Genestealers have incorrect points cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6229]
**File/Catalogue:** Tyranids v56

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** The Hive Fleet variant of Genestealers currently cost 12 points each, but should cost 10 points each.

**Comment by GenWilhelm** [comment]
Is that with or without their rending claws?

**Comment by Dunamis55** [comment]
Yea, just noticed it. Please ignore this.
