### ISSUE TITLE
Aeldari - Craftworlds: Relics should not cost points if model cannot lose its wargear

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6233]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Autarch with swooping hawk wings ,non legends version, pays 4 points for power sword and is being charged another 4 points for the shard of anaris. The shard of anaris should be a zero point upgrade because its a relic and the power sword has already been paid for.

**Comment by Mad-Spy** [comment]
tbh, I don't think we have relics costing points in any other catalogue?
