### ISSUE TITLE
Imperium - Space Wolves: Missed point changes

### ISSUE THREAD

**Issue by brandnewstereo** [BSData/wh40k#6236]
File: Imperium - Space Wolves.catz

BattleScribe version: 2.03.10

Platform: Windows
**Dropbox:** Yes/No

Some points errors showing for me

dreadnought combat weapons w/heavy flamer is 44pts I believe it should now be 34 as the combat weapon has dropped to 20pts, similar issue with dreadnought combat weapons w/storm bolter being 32pts instead of 20pts

also front axes showing up as 10pts for me on thunderwolf cavalry instead of 6 pts

thanks

**Comment by Mad-Spy** [comment]
Fixed in v1.4.1 (SW v100).
