### ISSUE TITLE
Wulfen Great Frost Axe point cost

### ISSUE THREAD

**Issue by Shoxaju** [BSData/wh40k#6238]
**File/Catalogue:** 

**BattleScribe version:** 2.03.16.325

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Wulfen wargear option "Great Frost Axe" listed at 17 points when it should be 9 according to new Chapter Approved

**Comment by CrusherJoe** [comment]
Fixed in next release.
