### ISSUE TITLE
Imperium - Space Marines: Champion of Blades not unlocking correct Relics?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6241]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 3.16.32

**Platform:** Android

**Dropbox:** Yes

**Description:** Imperial Fist Successor Chapters stratagem "Champion of Blades" must unlock all the relics of the Imperial Fists and the Crimson Fists.

**Comment by Captain-Aramus** [comment]
![2019-12-12](https://user-images.githubusercontent.com/58768636/70710256-0ecfb700-1cdf-11ea-8c3f-59465f65fe63.png)
![2019-12-12 (1)](https://user-images.githubusercontent.com/58768636/70710637-e6948800-1cdf-11ea-85a3-f00bf55ba038.png)
