### ISSUE TITLE
[Join Request] 

### ISSUE THREAD

**Issue by script-driver** [BSData/wh40k#6242]
I've joined the discord, my name is Eos#5691. I'd like to help with data development if I can, particularly the Eldar categories (which are my main army in 40k.) I've made some custom catalogues before, so I know generally how the structuring is done and what I should do. I'd also like to do some refactoring of existing data to make it more uniform across the whole game system and clean up unnecessary fluff a bit. I have done bug testing and bug fixing as well, (on the custom catalogues I've made) if you need help with that.

**Comment by amis92** [comment]
Starting with https://github.com/BSData/catalogue-development/wiki/Getting-Started#existing-game-system

As this falls into "busy repo" category, we're not inviting people to have write access. You can start off asking appropriate codeowners how you can help, raising bugs, helping us triage those that are already raised, etc.

Data development needs to be coordinated with the codeowner, and the best place for that will be issues and/or discord.

Refactoring of any size will also need to be discussed, so I encourage you to post a more detailed request/suggestion issue and we can start from there.
