### ISSUE TITLE
Chaos - Death Guard: plague probe points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6244]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** According to ca2019, plague probe is now 5pts.
Thanks for the update of database.
Hope you fix this error soon.
And all the best to your guys.

**Comment by Mad-Spy** [comment]
Already fixed.
