### ISSUE TITLE
Imperium - Blood Angels: unable to pick any WLTs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6246]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Generic blood angels characters (ie not special characters  do not have the option to select blood angels warlord traits)

**Comment by alphalas** [comment]
It’s fixed in the latest version of the files on master
