### ISSUE TITLE
Tyranids: Scythed Hierodule points not updated

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6249]
**File:** Tyranids.catz

**BattleScribe version:** 3.16.32

**Platform:** Android

**Dropbox:** No

**Description:** Tyranid Lord of war, "Scythed Heirodule" needs points value updated. Currently at 410 needs reduced to 350.

**Comment by GenWilhelm** [comment]
350pts is **excluding** wargear - it has to pay an additional 60pts for its two pairs of massive scything talons, which brings the total up to 410.
