### ISSUE TITLE
Officio Assassinorum Points Issue

### ISSUE THREAD

**Issue by Baskett55** [BSData/wh40k#6253]
**File/Catalogue:** 
Imperium - Officio Assassinorum.cat
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Detailed issue description.
Assassins are 85, wargear included. Listed as 95 on newest version

**Comment by Mad-Spy** [comment]
You may have heard of this thing called Chapter Approved that GW have been going on about for a few weeks? The points got changed.
