### ISSUE TITLE
Blood Angels Intercessor 'melee weapon replace rifle' error

### ISSUE THREAD

**Issue by sfPanzer-BnC** [BSData/wh40k#6255]
**File/Catalogue:** Imperium - Blood Angels.catz v107

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:**
"Melee weapon replaces rifle" on Intercessor Sergeants and DC Intercessor with CCW throws a maximum 0 error

Veteran Intercessor Sergeants don't lose their rifle when selecting the replacing option. It still lists 5 Bolt rifles in a unit of 5 and if Auto bolt rifles (1p) are selected it adds 5 points instead of just 4.

DC Intercessor with CCW never get their rifle even when the replacing option is not selected. It only lists 4 Bolt rifles in a unit of 5 and if Auto bolt rifles (1p) are selected it adds 4 points instead of 5.

**Comment by alphalas** [comment]
It should be fixed in the latest version of the file on master
