### ISSUE TITLE
Imperium - Astra Militarum: Valkyrie lascannons not showing new point value

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6256]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Lascanons on Valkyrie should be 15 points not 20.
Lascanon+twin heavy Bolter sponson on baneblade variants should be 29pts not 34.
Lascanon+twin heavy flamer Sponson on baneblade variants should be 43pts not 48pts.

(Possibly other missing discounts from the 5pt lascanon drop)

**Comment by Mad-Spy** [comment]
Baneblade Sponsons are fixed in AM v231.

Valkyrie issue still outstanding.
