### ISSUE TITLE
Adeptus Ministorum - Sisters Repentia hides Repentia Superior

### ISSUE THREAD

**Issue by mjingham** [BSData/wh40k#6258]
File/Catalogue: Imperium - Adeptus Ministorum.cat

BattleScribe version: 2.03.06

Platform: iOS

Dropbox: No

Description: Adding a Sisters Repentia unit hides the Repentia Superior in the list of available units. If the Repentia Superior is already added and then Sisters Repentia are added, you get an error saying the Repentia Superior is invalid.

**Comment by Mad-Spy** [comment]
Yes, it should because the Repentia Superior does not take up a slot if you take the Sisters. You'll find her under "No Force Org Slot" after adding the Sisters.

**Comment by mjingham** [comment]
Oh that makes sense. Thanks for responding!
