### ISSUE TITLE
Renegades and Heretics Tank Points need updating 

### ISSUE THREAD

**Issue by Brassclaw** [BSData/wh40k#6259]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description: I think during the update, someone forgot to update the tank point profiles for the Renegades and Heretics. I could see why it was overlooked seeing that none of the infantry models got modify during this cycle.

**Comment by Mad-Spy** [comment]
Fixed in R&H v46, hopefully.
