### ISSUE TITLE
Chaos Daemons - missing Herald of Slaanesh on Hellflayer

### ISSUE THREAD

**Issue by crackedgear** [BSData/wh40k#6261]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Missing HQ unit from Chapter Approved 2019

**Comment by Mad-Spy** [comment]
Added this one and updated all the others which were in CA2019. Fixed in Daemons v71.
