### ISSUE TITLE
Imperium - Astra Militarum: Heavy Weapon squad ML needs updated points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6264]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Missile Launcher option in infantry heavy weapons is listed as 15 points. MFM19 lists it as 10 points.

**Comment by CrusherJoe** [comment]
Fixed, will be in next release.
