### ISSUE TITLE
Chaos - Chaos Space Marines: Raiment Repulsive missing description

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6266]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Chaos space marines/ Legion: Emperors Children/ Relikt: "Raiment repulsive"is buggy in the View Screen

**Comment by Mad-Spy** [comment]
Unhelpful bug report is buggy in Github.

**Comment by Mad-Spy** [comment]
Fixed in CSM v120.
