### ISSUE TITLE
Blood Angels - Impulsor Issues

### ISSUE THREAD

**Issue by KishinAres** [BSData/wh40k#6267]
**File/Catalogue:** Imperium - Blood Angels.catz v107

**BattleScribe version:** 2.03.10

**Platform:** Android

**Dropbox:** No

**Description:** Impulsor missing the Assault Vehicle ability & Angels of Death rules
Wargear:
2x Storm Bolters listed currently at 2pts this should be 4, 2 per Storm Bolter
Ironhail Skytalon Array should be 5 pts, currently listed as 0

**Comment by alphalas** [comment]
merged into #6254
