### ISSUE TITLE
Imperium - Grey Knights: Paladin w/ Daemon Hammer not getting hammer by default

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6268]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Paladins with Daemon Hammers arent adding the points for the hammer. E.g 45 ppm compared to 46 ppm with a sword.

**Comment by Mad-Spy** [comment]
Nemesis Daemon Hammer is missing its min 1 in Parent constraint, so it's not being added by default for Paladins.
