### ISSUE TITLE
Imperium - Adeptus Ministorum: Blessed Blade missing profile

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6272]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Canoness data sheet does not show stats for the Blessed Blade if this is selected. Other melee options work fine (eviscerate, power sword etc)
This is with data set v1.4.1

**Comment by alphalas** [comment]
It’s fixed in whatever version is on master
