### ISSUE TITLE
Cost of AM wargear

### ISSUE THREAD

**Issue by zanilmeojk** [BSData/wh40k#6278]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android/

**Dropbox:** No

**Description:** Missile launchers in Guard HWT must cost 10pts, lascannon on Baneblade sponsons must cost 15pts

**Comment by zanilmeojk** [comment]
so sponson with lascannon and twin heawy bolters must cost 29pts, with lascannon and twin heavy flamers must cost 43pts

**Comment by Mad-Spy** [comment]
Duplicate of #6264 

Baneblade sponsons fixed in AM v231.
