### ISSUE TITLE
Aeldari - Craftworlds: Scattershield cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6281]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** The Wraithknight Ghostglaive and scattershield should cost 45 points as scattershield dropped from 30 to 15

**Comment by KalChoedan** [comment]
Duplicate of #6130
