### ISSUE TITLE
Imperium - Blood Angels: Librarian Dreadnought as warlord does not list blood angels traits, only BRB.

### ISSUE THREAD

**Issue by onlyamonth** [BSData/wh40k#6284]
**File/Catalogue:** Blood Angels - imperium v116/ba v107

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** Selecting a librarian dreadnought HQ choice as warlord gives access to the BRB warlord traits but not the BA traits.

**Comment by Mad-Spy** [comment]
This is a general issue in the BA file in the released version. No BA Warlord can take BA Warlord Traits.
