### ISSUE TITLE
Imperium - Blood Angels: Sanguinary Priest should not have any weapon choices

### ISSUE THREAD

**Issue by onlyamonth** [BSData/wh40k#6285]
**File/Catalogue:** Blood Angels - imperium v116/ba v107

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** The BA codex and blood of baal both list the sanguinary priest as being equipped with bolt pistol, chainsword, frag and krak grenades, with no options other than adding a jump pack. Data gives many choices.

**Comment by Mad-Spy** [comment]
At present, the Designer's Commentary flowchart is still in effect, so these Index options are still valid for the Priest.
