### ISSUE TITLE
Imperium - Blood Angels: Unable to select BA Warlord Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6286]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Unable to choose a Warlord Trait from the Blood Angels Codex. Only the three Traits from the Basic Rule Set are available. The same problem appears while using Android/the BattleScribe App.

**Comment by Mad-Spy** [comment]
Fixed for next release. Working correctly in BA v114
