### ISSUE TITLE
Dire Avenger point cost error

### ISSUE THREAD

**Issue by hieronymouse** [BSData/wh40k#629]
**File/Catalogue:** Aeldari Craftworlds v7

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** Point cost for adding more Dire Avengers does not include the 7pts for the Avenger catapult. I.e. adding one more DA costs 10pts instead of 17.

**Comment by FarseerVeraenthis** [comment]
Is this in a child detachment? 
They are bugged atm...

**Comment by amis92** [comment]
Yeah sounds like BattleScribe/Desktop-Alphas#166 again.

**Comment by hieronymouse** [comment]
Yep that's right, sorry didn't realise other similar issues were raised

**Comment by FarseerVeraenthis** [comment]
the points should update if you save and reload the roster. Although, if you change the number of models in the unit again it will not update until you close and re-open...
Since this is a known Battlescribe bug I'm going to close the issue and wait for BS to be upgraded.
