### ISSUE TITLE
Imperium - Astra Militarum: Tempestus Relic not available to Tempestus models.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6290]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** For the Tempestor Prime, the Militarum Tempestus relic "Tactical Auto-Reliquary of Tiberius" isn't showing up as an option to select once chosen as a warlord.

**Comment by Mad-Spy** [comment]
This relic can actually never be unlocked for a Militarum Tempestus model because none of them have "Faction: <Regiment>" and it is hidden for models which don't have that keyword.
