### ISSUE TITLE
Necrons - Tomb Blades CA 2019 pts Update - 28 to 21 pts

### ISSUE THREAD

**Issue by quentin41500** [BSData/wh40k#6294]
**File/Catalogue:** Necrons.cat

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** I believe the base points of tomb blades have been updated from 28 to 21 in the new Chapter Approved 2019. I still see them as 28 currently. Can you confirm the pts update is missing? Thanks for the hardwork getting everything in for this CA.

**Comment by quentin41500** [comment]
Unless I'm missing to count the weapons points in the 28pts, which means the base points are 14 pts and the count of "Two Gauss Blasters" at 14 pts push them at 28pts.

If it's only the base points changing, then should the model point be updating from 14 -> 7 ?

**Comment by DrTobogganMD** [comment]
I don't have access to stuff where I am, I'll take a gander tonight. I probably just missed it in my update. Thanks for the heads up

**Comment by quentin41500** [comment]
I'm still of v57! I don't have access to v58 as of just yet, but as soon as I do and see the update, I will close the ticket, otherwise just assumed this is still an issue.

**Comment by quentin41500** [comment]
When looking at the commit for v58, I'm not seeing anything in terms of points update so my guess is that the update is not in for tomb blades, unless I just can't read a CA and there is actually no points update!

**Comment by DrTobogganMD** [comment]
Huh, I could've sworn 58 was in the same release as 57.  Oh well.  If you're on 57 and seeing it, then it'd be a valid bugrep. I'll take a gander tonight!

It'd be easier if GW put out points changes along with the blanket list in MFM ... but hey, at least we got MFM.

**Comment by quentin41500** [comment]
https://github.com/BSData/wh40k/blob/e95a7093d18b2a154993d87a685ce1ffffc708a9/Necrons.cat#L1337

For reference, here is where the base points of the model is for a tomb blade.

**Comment by quentin41500** [comment]
I made a PR for the issue. Please confirm the point change before merging 🙈

**Comment by DrTobogganMD** [comment]
Please update the PR to bump version # as well. If that number isn't bumped, BS doesn't know that the file needs to be updated, so unless someone purges and re-dl's the files, they won't get the update.

I'll verify points and likely accept it tonight when I get to my desktop 👍

**Comment by quentin41500** [comment]
Ok, updating version as well.

**Comment by quentin41500** [comment]
Updated.

**Comment by Zanetsuken** [comment]
There is no point change here?

The base cost of a tomb blade is 14 pts.
Two Tesla Carbines or Gauss Blasters is 14 pts making 28.

**Comment by DrTobogganMD** [comment]
@Zanetsuken is correct. MFM points are 14 + 2x7
