### ISSUE TITLE
Aeldari - Craftworlds - Incorrect points costs

### ISSUE THREAD

**Issue by Bhazakhain** [BSData/wh40k#6295]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes

**Description:** Wraithcannons should be 10pts. Vibrocannons should be 10pts. Support platforms should be 25pts. Distort cannons should be 35pts.

**Comment by Mad-Spy** [comment]
Fixed in Craftworlds v89.
