### ISSUE TITLE
Blood angels Eliminator squad ammunition types are outdated

### ISSUE THREAD

**Issue by Carlsonsten** [BSData/wh40k#6299]
**File/Catalogue:** 
Blood Angels v107
**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
The Data of the ammunition types "Mortis Round" and "Executione Round for the Eliminator Squad are switched.

Mortis Round should be:
S5 AP-2 DW3    
This weapon can target a CHARACTER unit even if it is not the closest enemy unit. When resolving an attack made with this weapon, a wound roll of 6+ inflicts 1 mortal wound on the target in addition to any other damage.

Executioner Round should be:
S5 AP-1 D1
This weapon can target units that are not visible to the bearer, and can target a CHARACTER unit even if it is not the closest enemy unit. When resolving an attack made with this weapon, add 2 to the hit roll, and the target does not receive the benefit of cover to its saving throw.

The curent BS data seems to be based on a leaked picture of a datasheet which has since been updated in the current codex: space marines and psychic awakening: blood of baal

**Comment by alphalas** [comment]
merged into #6254
