### ISSUE TITLE
adeptus mechanicus and space wolves don't work

### ISSUE THREAD

**Issue by pjklan** [BSData/wh40k#6306]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**can't load or create rosters for swolves and ad mech

**Comment by CrusherJoe** [comment]
Space Wolves works just fine for me.

**Comment by CrusherJoe** [comment]
Unable to reproduce. Closing.
