### ISSUE TITLE
Deathwatch V81 Incorrect costs

### ISSUE THREAD

**Issue by BlackKnightSrc** [BSData/wh40k#6315]
Deathwatch V81 costs are not correct after I updated a few minutes ago. I swear some have reverted from earlier as I remember them being altered.

Primaris Librarian is 93, should be 90.
Librarian with jumpacks is 112, should be 108.
Librarian in Terminator armour is 102, should be 100.
Reivers(elites) are 18, should be 16.
Landraider(Normal) is 200, should be 180.
Repulsor is 185, should be 215.
Rhino is 70, should be 65.

A lot of the equipment and weapons costs are also not up-to-date.

**Comment by acebaur** [comment]
Try deleting the data as you update. That usually fixes it

**Comment by BlackKnightSrc** [comment]
It won't update via the normal update, it updates to v80. When I add it separately it won't let me delete first.

**Comment by BlackKnightSrc** [comment]
Concerning the Bolter Rifle, I just noticed in the editor that there is a set Pts to 1 rule in there.

**Comment by williamcaw** [comment]
chapter approved 2019

**Comment by corrinavatan** [comment]
> Concerning the Bolter Rifle, I just noticed in the editor that there is a set Pts to 1 rule in there.

Which, for the regular Bolt Rifle, is incorrect.

Bolt Rifle and Stalker Bolt Rifle should be 0 points, Auto BR should be 1.

I can confirm all the mistakes in what BlackKnight has mentioned, as well as Heavy Thunderhammers also still being 30 points, rather than correct 18.
