### ISSUE TITLE
Elysian Valkyrie Lascannon 

### ISSUE THREAD

**Issue by lewis0460** [BSData/wh40k#6321]
**File/Catalogue:** FW Elysian

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** To supplement #6225 I forgot about the valkyrie lascannon. @CrusherJoe Thanks for fixing those other bits, seen you've sorted this for regular AM but I guess not Elysian?

**Comment by CrusherJoe** [comment]
Eh...nuts. I'll fix that right now.
