### ISSUE TITLE
Imperium - Blood Angels - Warlord Traits

### ISSUE THREAD

**Issue by TomWija** [BSData/wh40k#6322]
**BattleScribe version:** 2.03.

**Platform:** Mac

**Description:** Having picked any HQ or unnamed character and making them a Warlord or giving them Hero of the Chapter. None of the Warlord Traits seem to appear, except for the BRB ones.

In addition, BRB warlord traits are appearing even if a character has not been made a warlord or hero of the chapter.

<img width="378" alt="Screenshot 2019-12-12 at 00 41 42" src="https://user-images.githubusercontent.com/7304281/70672854-65ee7100-1c78-11ea-97eb-19b416fa2df3.png">

**Comment by alphalas** [comment]
Fixed in next release
