### ISSUE TITLE
Astra Militarum forgeworld point costs

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k#6323]
**File/Catalogue:**  wh40k

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:**

Updated to latest version deleting data first.
Astra Militarum forgeworld units still show lascannons at 20 points, it should be down to 15 points

**Comment by CrusherJoe** [comment]
Yup, fixed in next release.
