### ISSUE TITLE
Imperium - Inquisition: Terminator Inquisitor missing Inquisitorial Mandate

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6326]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Ordo Malleus Inquisitor in Terminator Armour did not have Inquisitorial Mandate option.

**Comment by williamcaw** [comment]
missing from v116
