### ISSUE TITLE
Aeldari - Craftworlds - Shimmershield & Power Glaive points error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6329]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Shimmershield & power glaive points seem off. They are currently listed at 14 for the pair, but are 5 and 4 points respectively.

**Comment by FarseerVeraenthis** [comment]
this is correct in V89
