### ISSUE TITLE
Inquisition rules and stratagems not working correctly

### ISSUE THREAD

**Issue by NZStarlord** [BSData/wh40k#6336]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Authority of the Inquisition has a bullet point that states If you Army does not include any **INQUISITION** Detachments, one **INQUISITOR** model can be included in any other Detachment without taking up a slot, so long as every unit in your army (with the exception of **UNALIGNED** has the **IMPERIUM** keyword (and does not have the **FALLEN** keyword) etc. 
This SHOULD mean that I can have a full three HQ in a Battalion and Still add an Inquisitor into the same detachment, yet I get an error that I have too many HQ units.

In addition to this the Inquisitorial Mandate Stratagem that allows me to give a Warlord trait to my Inquisitor produces an error when I give my Inquisitor said Warlord Trait that I have 1 too many Warlords

**Comment by williamcaw** [comment]
the work a round is to take a unbound  detachment faction of Inquisition to take a inquisitor model

**Comment by Mad-Spy** [comment]
The first functionality has not yet been implemented; you can use @williamcaw's workaround for now.

I'm unable to replicate the second error. Can you provide some further details on your list setup?

**Comment by NZStarlord** [comment]
Oops, I figured out what I was doing wrong for the second error, my List is using Eisenhorn, and I was selecting him as a Warlord as well. My mistake
