### ISSUE TITLE
BR: Astra Militarium Rocket Launcher wrong cost

### ISSUE THREAD

**Issue by Sawaki1** [BSData/wh40k#6338]
**File/Catalogue:** 

**BattleScribe version:** 2.03. Release 1.4.1 

**Platform:** Android

**Description:** Rocket launcher shows wrong point cost (15) on infantry units (HWT, Infantry, Veterans). Shown correctly on vehicles though(10).

**Comment by Mad-Spy** [comment]
Fixed in SM v234
