### ISSUE TITLE
Imperium Blood Angels Relic Stratagem Costs

### ISSUE THREAD

**Issue by jmkk11** [BSData/wh40k#6340]
Relic costs in BA Version 103 is 1 cp per relic, BA still has the old 1/3cp relic stratagem

**Comment by Mad-Spy** [comment]
Didn't it get changed in Blood and Baal? Don't have the book handy.

**Comment by jmkk11** [comment]
No, the relic strat wasn't changed or updated at all (super annoying considering how many good relics there are now)

**Comment by alphalas** [comment]
merged into #6254
