### ISSUE TITLE
(Re)Add Primus Redoubt to Fortifications list

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6342]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Primus Redoubt fortification is missing from the fortifications list for both loyalist and chaos factions. Have not tried any Xenos factions. It is an unaligned unit in Imperial Armour Index: Forces of the Astra Militarum. In that book, it is erroneously called the Primaris Redoubt, page 53.

**Comment by Mad-Spy** [comment]
Fixed in GST v119
