### ISSUE TITLE
BattleScribe error: Directory '/Users/myname/Battlescribe/data/<gamesystem>" could not be created

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6356]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.10

**Platform:** Mac

**Dropbox:** No

**Description:** After several tries to uninstall, restart, and re-aquire the necessary repositories... everytime the program says it can't find the game system to open the army files.  This has been for both 40k and AoS.  It wont even let me pick a game system, that box is greyed out and will not drop down at all.

I'm running Catalina, 10.15.1, on an iMac.

**Comment by amis92** [comment]
Have you downloaded any datafiles? That sounds like you haven't.

> re-aquire the necessary repositories

Well maybe you have. Are you doing it manually (using git for example), or via app's Manage Data?

When you use Manage Data-> Add data ->(select one)->Done, what happens? Is data downloaded to the path you see in "Data location" on the bottom? Do the selected systems show on the Manage Data list?

**Comment by 40kChris** [comment]
Made an account... Hi!

When you use Manage Data-> Add data ->(select one)->Done, what happens? It goes through the motion of downloading the repositories, takes longer than it has normally, and then I get the "An Error Has Occurred" window with... net.battlescribe.model.cinfig.RepositoryFile@18f4ab6f: Directory '/Users/myname/Battlescribe/data/Warhammer 40,000 8th Edition" could noit be created

Is data downloaded to the path you see in "Data location" on the bottom? I believe so, there's Battlescribe and the tools folder with the Editor and Indexer, but nothing else.

Do the selected systems show on the Manage Data list? They do, but everything is locked up until I click Ok on the error window and done for the management window.  If I go to create a new roster I can't select a game system, and a greyed out page icon titled "root' is in the Forces box.

**Comment by amis92** [comment]
Hi.

Well the error that `the directory could not be created` is I think the actual issue. I don't know why, though.

Datafiles are downloaded to that path (`...BattleScribe/data/xxx`), so if there is no such directory, datafiles weren't downloaded.

Can you try creating that directory manually? My guess would be that there's some permission issue on a folder in the path.

**Comment by amis92** [comment]
Also, can you try any other gamesystem? Kings of War for example? The name doesn't have a coma.

**Comment by 40kChris** [comment]
I ran Disk Utility before doing anything else... I migrated computers not too long ago and thought there might be some permissions that needed repaired.  Same type of error message with Frostgrave, Gaslands, and 40k... I also attempted Necromunda, Kill Team, AoS, Kings of War, and Inifinity which did not give that error BUT I still couldn't make a roster just like above.

Would I put the new directory file in the Tools folder? I apologize if that's an obvious answer, I'm incredibly computer language deficient.

**Comment by 40kChris** [comment]
So it seems the Repair Disk, unistall, move Tools folder to trash, reinstall.. I moved the Tools folder first then Battlescribe, launch, update data seems to have worked.  I can see the game systems, the drop downs work for Forces, and I've been able to start a list.

**Comment by amis92** [comment]
I hope we can mark this as resolved, although I'm still not sure what was wrong. Happy you got it working, anyway. :)

**Comment by 40kChris** [comment]
Yeah, it was weird, but also thank you for all the suggestions.  You guys rock and thanks for doing all this for all the games systems in Battlescribe.
