### ISSUE TITLE
Imperium - Astra Militarum Astropath Points Cost

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#6361]
**File/Catalogue:** Astra Militarum

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Astropath has been reduced to 15 points in Chapter Approved, but is still listed as 21 points in Battlescribe.

**Comment by alphalas** [comment]
The telepathica stave costs 6ppm
