### ISSUE TITLE
Chaos - Daemons still missing Herald of Slaanesh on Hellflayer

### ISSUE THREAD

**Issue by crackedgear** [BSData/wh40k#6362]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** HQ unit from chapter approved 2019 still missing as of version 71.

**Comment by Mad-Spy** [comment]
Some idiot built it and forgot to link it into the selection list. Fixed in v72.
