### ISSUE TITLE
Blood Angels (DC) Intercessor replace rifle with melee weapon error

### ISSUE THREAD

**Issue by sfPanzer-BnC** [BSData/wh40k#6367]
**File/Catalogue:** Imperium - Blood Angels.catz v104

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** Detailed issue description.
DC Intercessors with CCW and Intercessor Sergeants still throw a maximum 0 error when replacing the rifle with a melee weapon

**Comment by Mad-Spy** [comment]
I think the actual issue is that hand-flamer + melee weapon is a valid load out, but is not permitted by the validation.

**Comment by sfPanzer-BnC** [comment]
Yes for the Intercessor Sergeant that's right. He can take only one melee weapon whatsoever. However for the DC Intercessor with CCW it should be possible to equipp two melee weapons as long as it isn't two Chainswords RAW.
