### ISSUE TITLE
Blood Angels Inceptor Squad Assault bolters wrong points

### ISSUE THREAD

**Issue by sfPanzer-BnC** [BSData/wh40k#6368]
**File/Catalogue:** Imperium - Blood Angels.catz v104

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:**
The points are still only adjusted for the Sergeant of the unit.

Correct for a unit of 3: 3x25+3x(8+8) = 123
Currently for a unit of 3: 3x25+1x(8+8)+2x(10+10) = 131

**Comment by Mad-Spy** [comment]
The base cost has been changed, but the increment in the unit entry hasn't been updated.
