### ISSUE TITLE
Necron CCB can use Voltaic Staff with no staff of light

### ISSUE THREAD

**Issue by miek770** [BSData/wh40k#6369]
**File/Catalogue:** Necrons v58

**BattleScribe version:** 2.03.16.325

**Platform:** Android

**Dropbox:** ?

**Description:** The Voltaic Staff (VS) description states that it replaces the staff of light (SoL, 10 pts). With the Catacomb Command Barge (CCB, haven't tested on other units), the VS can be selected even if the unit is not equipped with a SoL. Using the hyperphase sword at 3 pts, for example, frees up 7 pts.

The correct behavior should either be (depending on the dev's philosophy):

1. Prevent selection of the VS when the unit is not equipped with a SoL;
2. Autoselect the SoL when the VS is selected;
3. Raise a warning that this rule was broken.

I think item 2 is the ideal behavior, but I don't know the full context (i.e.: what can be done from the BSData vs in BS itself).

Thanks.

**Comment by DrTobogganMD** [comment]
Did you select it then move off of the SOL? 

Currently it works as intended. If you select it then change from SOL you get a validation error as expected. If you don’t have a SOL it doesn’t appear as below. 
![C9A5D390-A017-4833-8A77-185B77AC69AF](https://user-images.githubusercontent.com/16939161/70836431-b58e8300-1dc5-11ea-9a6f-00b700b7b0a3.png)

**Comment by miek770** [comment]
Ah, sorry, didn't notice the validation error was there. Thanks.

**Comment by DrTobogganMD** [comment]
No worries.  Your suggestion 2 would be grand, if BS was capable of that :(  In fact I'd love to take it one step further and hide the SOL profile entirely if you have the artefact selected.  Sadly I cannot.

**Comment by miek770** [comment]
Maybe someday :)

Thanks again!
