### ISSUE TITLE
Various Astra Militarum Lascannon fixes still to be made

### ISSUE THREAD

**Issue by DuneManta** [BSData/wh40k#6372]
**File/Catalogue:** Imperium - Astra Militarum v234

**BattleScribe version:** 2.03.16.325

**Platform:** Windows/Android

**Dropbox:** ?

**Description:** There are various units that have still yet to have the Lascannon points value updated to the new 15 point value instead of the 20 point value. I've gone through and tried to find all of them and have created a list of all that I have found.

**Carnodon:** Two multi-laser replacements
**Malcador Annihilator:** Two heavy stubber replacements, demolisher cannon replacement
**Malcador Defender:** Two heavy bolter replacements
**Malcador Heavy Tank:** Two heavy stubber replacements, heavy bolter replacement
**Malcador Infernus:** Two heavy stubber replacements
**Arkurian Pattern Stormhammer:** Hull mounted lascannon, multi-laser sponson replacements
**Crassus Armored Assault Vehicle:** Heavy bolter replacements
**Dominus Armoured Siege Bombard:** Heavy bolter replacements
**Praetor Armored Assault Launcher:** Heavy bolter replacements
**Valdor Tank Hunter:** Heavy stubber replacement

That's all the units I was able to find that still needed their lascannon points updated. I might have missed one or two but I think I got them all.

**Comment by alphalas** [comment]
@DuneManta what rev of the guard file are you on?

**Comment by DuneManta** [comment]
@alphalas v234 of the guard files. I've deleted and updated data a few times just to make sure I'm on the most up to date version.

**Comment by alphalas** [comment]
kk just wanted to verify, I cocked up BA a bit and rolled back the revs to earlier then the latest released revs - so fixes actually haven't been going live unless you delete and redownload. wanted to make sure I didn't do the same for am.

**Comment by CrusherJoe** [comment]
Carnodon -- sorry, this is a "twin lascannon" which is specified in the MFM as being 40 points. Otherwise all good catches -- thank you!

**Comment by DuneManta** [comment]
@CrusherJoe Right, I know the main gun is a twin lascannon option. But it can take two single lascannons on the sponson weapons, and those are showing at 20 points each still.

**Comment by CrusherJoe** [comment]
Ah, dang it...I own a Carnodon and didn't catch that bit -- thank you!
