### ISSUE TITLE
Slaanesh Herald on Hellflayer not listed

### ISSUE THREAD

**Issue by 40kChris** [BSData/wh40k#6374]
**File/Catalogue:** 

**BattleScribe version:** 2.03.10

**Platform:** Mac

**Dropbox:** No

**Description:** Slaanesh Herald on Hellflayer is not listed in the HQ section for Chaos: Demons, and this was after I had updated repositories, always deleting the old info, this morning.

**Comment by Mad-Spy** [comment]
Already fixed for next release.
