### ISSUE TITLE
Imperium - Adeptus Mechanicus: A few point cost issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6379]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** No

**Description:** Arc Rifle from Skitarii Rangers and Vanguards is 9 pts/ 10 pts, should be 2 pts
Plasma caliver from Skitarii Rangers an Vanguards is 18 pts /19 pts, should be 11 pts
Transuranic Arquebuse from Skitarii Rangers and Vanguards is 19pts / 20 pts, should be 12 pts

**Comment by tekton** [comment]
The cost seen is the Wargear plus the base cost for the body- these all seem like the right prices.
