### ISSUE TITLE
Chaos - Chaos Space Marines: Getting a "free" relic

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6381]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Chaos Marine data gives me access to a free relic. If I ask for +1 relic, it makes no difference. I can still have only 1 relic. I can pay 3 CP for 2 relics and not get a free one.

**Comment by Mad-Spy** [comment]
Please give some details of how you have your list set up. There shouldn't be any way to unlock the relic pick lists without either taking a CSM Warlord or adding one of the Relic stratagems to your list.

**Comment by Mad-Spy** [comment]
No update from OP on the problem. Closing.
