### ISSUE TITLE
Imperium - Codex Supplement Imperial Fists: Legacy of Dorn ability missing

### ISSUE THREAD

**Issue by pwtdo** [BSData/wh40k#6387]
File/Catalogue: Imperium - Space Marines v124

BattleScribe version: 2.03.10.

Platform: Windows

Dropbox: No

Description: Army is Battle-forged and every detachment has chapter selection **Imperial Fists**, but the roster doesn't receive **Legacy of Dorn** as Selection Rules.

**Comment by acebaur** [comment]
None of the chapters have their doctrine bonus as a selection rule. I have no plans to add them at this time either, as the SM cat is already so big it's causing load issues. When we refractor and break out the supplements I will revisit
