### ISSUE TITLE
Dark Angels - some marines have wrong pts

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6390]
**File/Catalogue:**  Imperium - Dark Angels v120

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
Tactical Squad: **Heavy weapon marine** is 13 it should be 12
Tactical Squad: **Special weapon marine** is 13 it should be 12
Devastator Squad: **Space marine sergeant** is 12 it should be 13

**Comment by williamcaw** [comment]
chapter approved 2019

**Comment by Calamulus** [comment]
Devastator Marines (non heavy weapons) should also be 13 instead of 12 (#6357)
