### ISSUE TITLE
Deathwatch inappropriate equipment points cost

### ISSUE THREAD

**Issue by Kongield** [BSData/wh40k#6397]
**File/Catalogue:** Deathwatch.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** Master-crafted boltgun is still 5pts, should be 3pts. Auxiliary Grenade Launcher is free, should be 1pts. Bolt Rifle is 1pts, should be 0pts.

**Comment by Mad-Spy** [comment]
Already fixed for next release as per #6313 and other closed tickets.
