### ISSUE TITLE
Deathwatch Terminators Cyclone/TH/SS and Twin Claws/Cyclone loadouts missing.

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k#6399]
**File/Catalogue:** Deathwatch.cat

**BattleScribe version:** 2.03.16

**Platform:** Windows/iOS/Android/Mac/Linux / All

**Dropbox:** Yes/No

**Description:** Detailed issue description:

The Deathwatch FAQ clarifies that wargear you gain via trading in previous wargear, can be traded AGAIN to meet the qualifications of a different bullet point, with the following example:

_Q: Can a Watch Captain replace his chainsword and mastercrafted boltgun with a storm bolter and another chainsword, and then replace his ‘new’ chainsword with either a relic blade or xenophase blade? A: Yes, because these wargear options are two separate bullet points (you cannot choose the same bullet-pointed wargear option for a unit more than once, however)._

Note that this does NOT conflict with other Faq, stating that you can't trade for a Cyclone Missile Launcher+Stormbolter, then trade the Stormbolter AGAIN for an Assault Cannon: both of these are in the same bullet point, and per above answer can only be selected once.

This means the following can be done in both the Terminators Datasheet, as well as Terminators that are taken as part of a Veterans unit:

1.  Start with Stormbolter+Powerfist/Power Sword
2.  Trade up to 3 terminators Stormbolter for a Heavy Weapon, and take Cyclone Missile+Stormbolter.
3.  Trade Stormbolter+Power Fist/Power Sword for Thunder Hammer+Storm Shield (or 2 Lightning Claws)

Final result is up to 3 Terminators with Thunder Hammers, Storm Shields, and Cyclone Missile Launchers, or up to 3 Terminators with twin Lightning Claws+Cyclone Missile Launchers.

While this is a niche loadout, it WAS a legal loadout in 7th edition, and was still a legal loadout in 8th edition, but many people misconstrued a previous FAQ answer to mean "you cannot trade a weapon you traded to get" when it actually said "you can't use the same bullet point on a datasheet multiple times"

**Comment by Mad-Spy** [comment]
Resolved by adding "Cyclone Missile Launcher" as an option to standard Terminators to avoid breaking existing lists.

**Comment by corrinavatan** [comment]
Just as a sanity check:

Having a Cyclone ML should count against your "max 3 Terminators can have heavy weapons."

Just checking that the validation will count such a Term as a HW term.

**Comment by Mad-Spy** [comment]
Yes.
