### ISSUE TITLE
CSM Death Guard

### ISSUE THREAD

**Issue by skonk** [BSData/wh40k#640]
- [ ] Not sure if this applies to the other Chaos cats but the Lord with Jump Pack in the DG cat is throwing a "1 too many from chain sword options" when changing the chain sword to a melee weapon and selecting a pistol (bolt or plasma) for the pistol options.

**Comment by cartag** [comment]
Are you unselecting the initial chainsword or bolt pistol?

**Comment by skonk** [comment]
Specifically it seems to be when using the Pistol radio button options, but doesn't throw the error when the pistol is coming from the numeric input box.

Doesn't seem to matter which "arm" has the melee weapon or pistol; if the pistol is selected from one of the radio groups (bolt or plasma) and a melee weapon (even the basic chain sword) is selected in the other slot it shows the error.

**Comment by cartag** [comment]
Found it after I posted
