### ISSUE TITLE
Chaos - Daemons: Prince cannot select psychic power

### ISSUE THREAD

**Issue by regentcid434** [BSData/wh40k#6400]
** File:** Chaos - Daemons.cat 

**BattleScribe version:** 2.03.07

**Platform:** iOS

**Dropbox:** No

**Description:** Daemon Prince of Chaos does not have the ability to select psychic powers, even with a Daemonic Allegiance selected. When you 'View' the datasheet, it does display Smite, however.

**Comment by Mad-Spy** [comment]
Yes, they can. It's a sub-list under the Allegiance selection, as shown by the orange (rather than grey) tab on the Allegiance selection after you make it. Any selection which has sub-options shows in this way in the BS mobile UI.

**Comment by regentcid434** [comment]
Thanks. I never even noticed the tiny tab.

**Comment by Mad-Spy** [comment]
No worries; you're not the first and you'll not be the last.
