### ISSUE TITLE
Deathwatch HQ costs are wrong

### ISSUE THREAD

**Issue by GuillermoDiazGarcia** [BSData/wh40k#6406]
**File/Catalogue:** wh40k

**BattleScribe version:** 2.03.16

**Platform:** Android

**Dropbox:** Yes

**Description:**
Some Deathwatch HQ costs are wrong, such as Artemis bring costed at 115 for some reason (he changed straight from 130 to 100), or all librarians being overcosted (I think with their pre-CA cost)

Edit: okay, seems like Artemis was already corrected. However, I just noticed that master crafted boltgun is 5pts (should be 3) and master crafted auto bolt rifle is also 5 (should be 4)

**Comment by Mad-Spy** [comment]
All already fixed for next release.
