### ISSUE TITLE
Minor Problem with Sisters of Battle rules

### ISSUE THREAD

**Issue by mage98** [BSData/wh40k#6408]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:**No

**Description:** Detailed issue description.
Sisters of battle rules for two things are incorrect. First a null rod doesn't require a cannonness to have a chainsword. (Though A brazier of holy fire does). Second hospitallers (and I presume other minor characters) should have access to the "wrath of the emperor" relic pistol. They are characters who have a bolt pistol, and as such can take the relic.

**Comment by CrusherJoe** [comment]
As of v84 of the datafile the Rod of Office validation is correct...though I notice the power sword option is a spinner and not a checkbox, so I'll have to fix that as well. Thanks for the report!
