### ISSUE TITLE
Blood Angels - Price for 2 x Lightning Claws is wrong

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k#6409]
**File/Catalogue:** Imperium - Blood Angels v104

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Lightning claws are 6 pts each, or 10 for a pair. If you take 2 currently you are still getting charged 6 for each - the second should be reduced to 4pts. This affects both characters (where the two melee options are separate options) and units like Vanguard Vets (where there is one entry for lightning claws with a quantity against it).

**Comment by Mad-Spy** [comment]
Still a problem in BA v104, the local copy of Lightning Claws hasn't been updated.

**Comment by alphalas** [comment]
It’s fixed in the latest version, will be in next release (v121
