### ISSUE TITLE
Chaos - Chaos Space Marines: Scorpion of Khorne missing for World Eaters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6411]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Greater brass scorpion of khorne appears to be missing entirely

**Comment by Mad-Spy** [comment]
It's a Lord of War so you must include a Detachment which allows them.

![image](https://user-images.githubusercontent.com/29306451/71008016-d44f8b00-20df-11ea-9a1d-d0ff41f50a2a.png)

**Comment by papastacy** [comment]
I would like to comment that the GBS does not show up in a World Eaters detachment for super heavy. Not sure if intentional.
