### ISSUE TITLE
Couple Dark Angels issues I noticed today

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6414]
**File/Catalogue:** Imperium - Dark Angels v120

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

Relic Whirlwind Scorpius: isn't suppose to have Whirlwind keyword <-- 30/09/2019 IMPERIAL ARMOUR errata
Whirlwind Hyperios: isn't suppose to have Whirlwind keyword <-- 30/09/2019 IMPERIAL ARMOUR errata

And when having special detachment you can choose special detachment relics without having warlord.

**Comment by Ginjitzu** [comment]
Also, Tactical Squad Special Weapon Marine still costs 13 points instead of 12.

**Comment by miku2020** [comment]
@Ginjitzu that is already fixed into next update. would you read closed issues too.
