### ISSUE TITLE
Blood Angels Issues

### ISSUE THREAD

**Issue by mdmagnusson** [BSData/wh40k#6415]
**File/Catalogue:** Blood Angels v107

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
1. Captain in Phobos Armor - Master-crafted instigator bolt carbine incorrectly marked as *Damage 2*, Should be *Damage 3* as per "[space marine summer update](https://www.warhammer-community.com/wp-content/uploads/2019/08/warhammer_40000_space_marines_summer_update_en.pdf)" and subsequent publications.
2. ~~Additional Relics of Baal - Only allows 1 additional relic for 1 command point but should have an option for *another additional relic for a total of 3 command points* as per the Codex Blood Angels Stratagem.~~

**Comment by Mad-Spy** [comment]
2. This option is there; you just need to click/tap on the Armoury of Baal entry after adding it. It's displayed as **Bold** in the Windows Roster Editor, and has an orange tab on the left in the app version, to show this.

**Comment by mdmagnusson** [comment]
> 2. This option is there; you just need to click/tap on the Armoury of Baal entry after adding it.

Right you are. After deleting existing data and downloading again it now shows up correctly for me. Sorry about that.
