### ISSUE TITLE
No points for orbital comms array on Rhino Primaris

### ISSUE THREAD

**Issue by rtho782** [BSData/wh40k#6418]
**File/Catalogue:** Dark Angels v121

**BattleScribe version:** 2.03.07

**Platform:** Windows

**Description:** Rhino Primaris has an orbital comms array as per the Dark Angel Legends PDF. This seems to be the same wargear as on the impulsor, as it has the same name and the same ability. As such I believe it should pay 18 points for this as per CA19 MFM.

**Comment by Dunamis55** [comment]
This also applies to the standard Space Marines and the Blood Angels data too.

**Comment by alphalas** [comment]
fixed in ba

**Comment by acebaur** [comment]
Fixed in SM

**Comment by CrusherJoe** [comment]
Fixed in Wolves
