### ISSUE TITLE
Imperium - Adeptus Ministorum: Repentia Superior should be NFO if there is at least one Repentia unit, not exactly 1.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6419]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** When trying to add both my Sisters Repentia and Repentia Superior, battlescribe doesn't let me. When i have no or two selections of Sisters Repentia, i can choose to add a Repentia Superior, yet when i have only 1 unit of Sisters Repentia, the option to add a Repentia Superior dissapears in terms of adding it as an Elite. I can choose to add it under the "No force org slot", but that makes my Vanguard detachment illegal. When adding a Repentia Superior first, and the adding just 1 unit of Sisters Repentia, Battlescribe gives me the error of "Elites can not have any selections of Repentia Superior (Hidden)". This error dissapears if i simply add 1 more unit of Sisters Repentia, but i do not own 1 more unit.

**Comment by Mad-Spy** [comment]
If you take the Sisters, the Repentia Superior doesn't take up a Force Org Slot, so the Detachment shouldn't validate (as you don't meet the necessary requirements).

I'm afraid we can't help you with not owning enough models to make a valid Detachment.

**Comment by Mad-Spy** [comment]
There is a bug however as the Superior should always be No Force Org if there are any Repentia units in the list, not just if there is exactly 1.

**Comment by CrusherJoe** [comment]
Okay I think it's fixed now. Will be in next release.
