### ISSUE TITLE
Imperium - Adeptus Ministorum: Mortifier unit limit should be 6 models

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6420]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.03.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Mortifiers are listed in BattleScribe as having a max unit size of 4, including Anchorite. Codex Adepta Sororitas says that maximum unit size for Mortifiers is 6.

**Comment by CrusherJoe** [comment]
There is a discrepancy between the number allowed in the unit on the datasheet and on the "Points Values" section of the Codex. The lesser value has been used until this one is FAQ'd. Closing for now, will change in the event of a FAQ.
