### ISSUE TITLE
Imperium - Adeptus Ministorum: Battalion validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6421]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.03.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Having 3 fast attack squads in a Battalion Detachment list throws an error that there is one too many squads, while also saying that the max is 3. Error should not be thrown for having 3 squads.

**Comment by Mad-Spy** [comment]
Unable to replicate this issue. Please can you give some more information on your list and force composition.

**Comment by dXQuarionXb** [comment]
Fast attack is comprised of 3 squads of 5 Seraphims. There aren’t any fast attack units in my list that qualify for a NFO categorization.

**Comment by dXQuarionXb** [comment]
Outside of fast attack, my list is composed of:
NFO: 2 geminae superia, 2 separate Repentia Superior
HQs: 1 cannoness, Celestine
Troops: 3 battle sisters squads
Elites: 2 squads of Repentias, 1 squad of zephyrims
Heavy: 2 Exorcists, 1 squad of Mortifiers 
Transports: 3 sororitas rhino

**Comment by dXQuarionXb** [comment]
I removed the zephyrims from my list and the error cleared. Apparently zephyrims are classified as both elite and fast attack

**Comment by radionausea** [comment]
Confirming that the above is the case. I created an outrider detachment with 2 seraphim and 1 zephyrim squad and it was valid so Zephyrim are counting towards fast attack.

**Comment by CrusherJoe** [comment]
Yes Zephyrim erronously had the Fast Attack role as well as Elite. This has been fixed in the next release of the datafile.
1
