### ISSUE TITLE
Aeldari - Craftworlds: Vibrocannon points issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6428]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The cost of the Craftworld Eldar Vibro Cannons for the Support Weapon unit are wrong.  They show the cost to be 15 points, when Chapter Approved 2019 reduced the cost to 10 points.

**Comment by FarseerVeraenthis** [comment]
Please update your data. This is correct in v89 of the CAT.
