### ISSUE TITLE
Land Raider Excelsior no longer has CHARACTER keyword

### ISSUE THREAD

**Issue by rtho782** [BSData/wh40k#6432]
**File/Catalogue:** Dark Angels v120

**Description:** This will likely apply to other catalogues but I'm not sure if they have all been updated for legends. Land Raider Excelsior lost the character keyword in the Legends update, and so can no longer take warlord traits or relics. Sad times :(

**Comment by alphalas** [comment]
fixed in BA

**Comment by acebaur** [comment]
Will be fixed in SM in the next release

**Comment by CrusherJoe** [comment]
Fixed in Wolves.
