### ISSUE TITLE
Adepta Sororitas-Kyrinov, Preacher and Zepheryim

### ISSUE THREAD

**Issue by gungagreg** [BSData/wh40k#6433]
**File/Catalogue:** 1.4.2

**BattleScribe version:** 2.03.07

**Platform:** iOS

**Dropbox:** no

**Description:** Detailed issue description.

Preacher is marked as Legend incorrectly
Zeryphim appear as elites selection, but are being counted against the fast attack as well
Arch Confessor Kyrinov is not marked as legend

thanks!

**Comment by alphalas** [comment]
In regards to the preacher; because he normally only has a chainsword and laspistol, if you have anything other than those two pieces of wargear on him he is a legends model.

**Comment by gungagreg** [comment]
Ah, didnt see that for preacher, there was no flag that i needed to assign wargear.

**Comment by alphalas** [comment]
That is a definite improvement that can be made, yes.
