### ISSUE TITLE
Invulnerable saves are not consistenlty shown on Unit Profiles

### ISSUE THREAD

**Issue by gimmethedatafiles** [BSData/wh40k#6437]
**File/Catalogue:** Astra Militarum

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Invulnerable saves are not consistenlty shown on Unit Profiles.
E.g. the unit profile for a Company Commander shows "Save: 5+/5++" clearly indicating a 5+ save and a 5++ invulnerabilty save.
However for a Ministorum Priest, the profile (view roster) only shows Save: 5+, whilst it should be 5+/4++

-Similar issue for several other units:
- Commissar Yarrick: is 4+ => should be 4+/4++
- Colonel 'Iron Hand' Straken is 3+ => should be 3+/5++
- Lord Commissar is 4+ => should be 4+/5++

**Comment by Mad-Spy** [comment]
Invulnerable saves should not be shown on unit profiles as they do not appear as such on data sheets. The "++" format is a community convention not a rule.
