### ISSUE TITLE
FW Death Korps of Krieg - CA 2019 cost updates for Mortars and Missle Lauchners

### ISSUE THREAD

**Issue by Rafal3920** [BSData/wh40k#6439]
**File/Catalogue:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.03.16

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** CA 2019 updated costs of Heavy Weapons for Astra Militarum and also for Death Korps:
Missile Lauchner - 15 -> 10
Mortar 5 -> 9

**Comment by CrusherJoe** [comment]
This has been addressed and will be in the next release.
