### ISSUE TITLE
Necron Doomsday ark Damage table does not show correct titles

### ISSUE THREAD

**Issue by Alijens** [BSData/wh40k#644]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
```
            <characteristic name="Characteristic 1" characteristicTypeId="bf41-c860-50bc-2a7e" value="12&quot;"/>
            <characteristic name="Characteristic 2" characteristicTypeId="dc18-e51f-309b-8efa" value="3+"/>
            <characteristic name="Characteristic 3" characteristicTypeId="df06-8eca-150f-90ba" value="3"/>
          </characteristics>
```

Characteristic # should be replaced with abriviation: M, BS,  D

**Comment by GenWilhelm** [comment]
Edited the OP to fix formatting.

**Comment by Kohato** [comment]
This is not an issue with Necrons. Those are set at the GST level. We don't pre-determine them because they differ for every model with a damage table.

**Comment by amis92** [comment]
@Kohato actually you might reconsider it, many catalogues have done it. I know I did in Tau. Create a new profile type for each stat combination and mark them appropriately.

**Comment by Kohato** [comment]
If we're doing that as the standard, I'll swap it over. Can eventually take out the shared one from GST then.

**Comment by amis92** [comment]
Yeah it was shortly discussed on Gitter and never made it into Guidelines. As a matter of fact, we could probably raise the most common combinations into GST, but that's for some future effort.

I should probably add it to GLs along with #4 and other little things.
