### ISSUE TITLE
FW Death Korps of Krieg - Missing Militarum Tempestus and Advisors and Auxillia rules

### ISSUE THREAD

**Issue by Rafal3920** [BSData/wh40k#6440]
**File/Catalogue:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.03.16

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Battlescribe's Death Korps of Krieg list don't including units described in Militarum Tempestus and Advisors and Auxillia (Codex: Astra Militarum page 132). They are don't receiving Cult of Sacrifise and DKoK Keyword, but they are still can be attached to DKoK Detachments without other penalties. This units are (found so far):
- Militarum Tempestus units:
   - Tempestor Prime
   - Militarum Tempestus Scions
   - Militarum Tempestus Command Squad
- Tech-Priest Engineseer
- Servitors
- Ministorum priests 
- Crushaders
- Aeronautica Imperialis units:
   - Officer of the fleet
   - Valkyries
   - Marauder Bomber/Destroyer
   - Aquila Lander
   - Arvus Lighter
   - Avenger Strike Fighter
   - Lightning Strike Fighter
   - Thunderblot Heavy Fighter
   - Vendetta Gunship
   - Vulture Gunship
- Militarum Auxilla units:
   - Ogryn bodyguard
   - Ogryns
   - Bullgryns
   - Nork Deddog
   - Ratlings
- Officio Prefectus units (DKoK have their own Commisars but "just Forgeworld")
   - Commissar Yarick
   - Lord Commissar
   - Commissar
- Scholastica Psykana units
   - Primaris Psyker
   - Wyrdwane Psykers
   - Astropath

**Comment by alphalas** [comment]
Include a child detachment as per here: https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions
