### ISSUE TITLE
T'au Empire: XV9 can take too many support systems

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6447]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** The XV9 Hazard Battlesuit is able to take 0 to 3 Support Systems despite being limited to a maximum of 1 per model, as per the datasheet.

This in Warhammer 40,000 8th Edition v120, T'au Empire v51.

**Comment by amis92** [comment]
Yeah so the data hasn't changed. I confirm it works correctly on 2.03.10 and doesn't on 2.03.11 (PC).

App bug. Raised: https://github.com/BattleScribe/Release/issues/107

**Comment by Shiney1965** [comment]
So far as I can see there are no wargear limit validation errors for any battlesuits.  You can tale any nunber of weapons and support systems for the Coldstar battlesuit without a validation warning, for example .. and every other battlesuit that I have tried.

**Comment by alphalas** [comment]
@Shiney1965 like @amis92 said, it’s a BS APP bug, not a data issue.

**Comment by amis92** [comment]
Tracking now in #6672.
