### ISSUE TITLE
Imperium - Inquisition: Hector Rex should be able to take 3 powers when taking Psychic Mastery

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6454]
**File:** Imperium - Inquisition.catz

**BattleScribe version:** 2.03.08

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Inquisitor Lord Hector Rex can‘t choose an additional psychic power, when choosing the warlord trait „Malleus-Psychic Mastery“. When choosing the additional power the red „!“ shows up stating „too many selections from Thelethesia Discipline (maximum) 2“ but with the warlord trait it should be maximum 3. (Inquisitor Coteaz who has to take Psychic Mastery as his warlord trait does not have this issue!)

**Comment by williamcaw** [comment]
this also applies to Inquisitor Coteaz
