### ISSUE TITLE
CSM - Greater Brass Scorpion not in Lord of War 

### ISSUE THREAD

**Issue by morenn1** [BSData/wh40k#6463]
File/Catalogue:

BattleScribe version: 2.03.

Platform: Android

Dropbox: Yes/No

Description: Lord of War category in Super-Heavy Auxillary Detachment doesn't feature Greater Brass Scorpion of Khorne

**Comment by Mad-Spy** [comment]
Assuming you are using World Eaters as there was an issue that was preventing it from appearing for them (although it does appear for other valid Legions). Already fixed as per #6411.
