### ISSUE TITLE
CSM we are alpharius stratagem limited to alpha legion warlord traits

### ISSUE THREAD

**Issue by p5freak** [BSData/wh40k#6471]
**Catalogue** CSM v120

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** The alpha legion stratagem we are alpharius lets you select a warlord trait for another character, besides your warlord. Battlescribe only lists the alpha legion warlord traits. But the stratagem doesnt say its limited to alpha legion warlord traits only, so all warlord traits should be available, alpha legion, codex CSM, shadowspear, and the BRB.

WE ARE ALPHARIUS
 
Use this Stratagem before the battle, after nominating your Warlord. Select one ALPHA LEGION CHARACTER model from your army that is not your Warlord and determine one Warlord Trait for it; it is regarded as your Warlord for the purposes of that Warlord Trait. Each Warlord Trait in your army must be unique (if randomly generated, re-roll duplicate results). You can only use this Stratagem once per battle.

**Comment by Mad-Spy** [comment]
Fixed in v122
