### ISSUE TITLE
Aeldari - Drukhari - Tantalus Points issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6473]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** Yes

**Description:** Tantalus points are 350,not 400. The new points are in the codex of forge world

**Comment by fuckingenglish** [comment]
Ther are early updates to point in chapter approved and was updated in 2018 chapter approved form 350 to 400

**Comment by FarseerVeraenthis** [comment]
Tantalus is listed at 400 points including wargear in the Munitorum Field Manual that was released alongside Chapter Approved 2019.
