### ISSUE TITLE
Rhino Primaris and LR Excelsior wrong points in SM

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6474]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Both the Landraider Excelsior and Primaris Rhino are incorrect there was a new update on FAQs for Warhammer legend models I provided a screenshot but the document is also available on Warhammer community page. Using here because I've tried submit file update for the last month and it hasn't worked.

**Comment by onlos** [comment]
![Screenshot_2019-12-09-11-58-48-324_com google android apps docs](https://user-images.githubusercontent.com/59221420/71439067-b4126400-26bd-11ea-8bb9-f534723d5dc5.jpg)

**Comment by acebaur** [comment]
fixed in the latest release
