### ISSUE TITLE
No Option For making Astra Militarum Roster

### ISSUE THREAD

**Issue by dheck175** [BSData/wh40k#6475]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
When I open the options to create a roster there is no option for the Astra Militarum. The screenshot will perhaps better explain the situation.
![Screenshot_20191225-144504](https://user-images.githubusercontent.com/59234920/71450032-9548b780-2727-11ea-8bf9-8d3f15b40f15.jpg)

**Comment by fuckingenglish** [comment]
Have you deleted the full bin file then re-download the file/updated?

**Comment by alphalas** [comment]
what @fuckingenglish English said. delete and redownload data.

**Comment by dheck175** [comment]
Hi there, no I haven't. I have two questions though. 1st, Will deleting the full bin also delete my rosters? 2nd, how do you delete the bin? Thank you guys for the quick responses!

**Comment by amis92** [comment]
Resolved via #6480
