### ISSUE TITLE
Chaos Daemons - Herald of Slaanesh on Hellflayer Missing

### ISSUE THREAD

**Issue by paulwinters** [BSData/wh40k#6478]
**File/Catalogue:** Chaos Daemons v71

**BattleScribe version:** 2.03.17.326

**Platform:** Android

**Dropbox:** No

**Description:** Chapter Approved 2019 added a new chaos daemon unit, "Herald of Slaanesh on Hellflayer" found on page 87. It was overlooked in the Chapter Approved 2019 update.

**Comment by Mad-Spy** [comment]
Fixed in #6362 and released in v72 of the Daemons catalogue.
