### ISSUE TITLE
[Dark Angels] Librarian in Phobos armour disciplines

### ISSUE THREAD

**Issue by MechaLenin** [BSData/wh40k#6483]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes/No

**Description:**  Librarian in Phobos armour should have access to both Obscuration and Interromancy disciplines.  ATM it has just Obscuration.

**Comment by MechaLenin** [comment]
https://www.warhammer-community.com/wp-content/uploads/2019/08/warhammer_40000_space_marines_summer_update_en.pdf

**Comment by alphalas** [comment]
it seems like this will be changed back in PA - the BA PhLib lost access to Sanguinary

**Comment by Thairne** [comment]
RoD allows Interromancy as well and was updated accordingly.
