### ISSUE TITLE
Crimson Fists incorrect warlord traits

### ISSUE THREAD

**Issue by TJ-paints-and-games** [BSData/wh40k#6486]
**File/Catalogue:** 
Imperium - Space marines V124
**Description:** Detailed issue description.
Crimson fists warlord selected but no error if a warlord trait isnt selected, or if an Imperial Fists trait is selected (without strategem).

If Vigilus Detachment selected, other chapter traits incorrectly become available as an option.

**Comment by acebaur** [comment]
Crimson Fists can select Imperial Fists WLT as they are a successor. The second part was a BS linking issue and It'll be corrected in the next release

**Comment by GenWilhelm** [comment]
Crimson Fists don't have access to Imperial Fists Warlord Traits (other than using the Sentinel of Terra stratagem):

![image](https://user-images.githubusercontent.com/22036809/72220276-edb0ef00-3546-11ea-8264-67e7e87e0e99.png)
~Codex Supplement: Imperial Fists, p56
