### ISSUE TITLE
Adepta Sororitas: Possible to equip 1 Special & 1 Heavy Weapon simultaneously

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#6488]
**File/Catalogue:** Adepta Sororitas v84

**BattleScribe version:** 2.03.11.140

**Platform:** Windows

**Dropbox:** No

**Description:** In Battle Sister Squad and Celestian Squad you can add a Sister with Special or Heavy Weapon.
It is possible to equip both a Heavy AND a Special Weapon, but only one Heavy OR Special should be allowed.

**Comment by alphalas** [comment]
this is actually a BS bug ironically
