### ISSUE TITLE
Word Bearers "Apostle of the Dark Council" stratagem doesn't deduct 1cp

### ISSUE THREAD

**Issue by mazik765** [BSData/wh40k#6492]
**File/Catalogue:** 
Chaos - Chaos Space Marines v120

**Description:** Detailed issue description.
For a Word Bearers Chaos Space Marines detachment it allows you select the "Apostle of the Dark Council" stratagem to upgrade a Dark Apostle but it doesn't deduct a CP as it does for field commander or bonus relics.

**Comment by Mad-Spy** [comment]
Fixed in v122
