### ISSUE TITLE
Chaos Knights - Knight Desecrator missing Taskmaster ability

### ISSUE THREAD

**Issue by crackedgear** [BSData/wh40k#6495]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Knight Desecrator is missing ability to reroll 1s for nearby War Dogs

**Comment by Mad-Spy** [comment]
The ability shows once you select a Household type so it knows which keyword to put into the ability. Please ensure you clear validation errors (as much as possible) before raising issues.
