### ISSUE TITLE
Aeldari: Ynnari - Known Validation Issues

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#6498]
- [x] Ynnari special characters will not cause validation errors when they are selected as a warlord without their specific trait being selected.
- [ ] Stratagem: Exalted of Ynnead does not allow a second warlord trait to be selected.
- [ ] Relic validation has not been checked.
- [ ] Ynnari keyword updates have not been QA'd.
- [ ] The Visarch does not generate Ynnari detachment rules for Craftworld Aeldari when taken as an HQ. (Posted by MarshalLaeroth)
- [ ] Solitaire should not be available in Ynnari detachments. (Posted by MarshalLaeroth)

**Comment by MarshalLaeroth** [comment]
In addition to the above issues listed, I also have noticed the following:

1) The Visarch does not generate Ynnari detachment rules for Craftworld Aeldari when taken as an HQ.  The other two Ynnari characters function normally.

2) Psychic Awakening: Phoenix Awakening specifically bars the Solitaire from being taken in a Harlequin Ynnari detachment, but the option is still available even after selecting the Ynnari "Masque".

**Comment by FarseerVeraenthis** [comment]
Thanks, I'm hoping to have a good look at the state of the whole cat, including legends, the whole general integration of ynnari, and any areas where it could be brought into line with other cats.

**Comment by Haileyadams** [comment]
Yncarne is currently not generating the Craftworld attribute of Ynnari after selected as HQ.

Yvraine's Warlord trait must be Favored of Ynnead as described in White Dwarf May 2019, which is default on her page even when not a Warlord. But if you set Yvraine as Warlord the Warden Of Souls option is available and should not be.

**Comment by DrTobogganMD** [comment]
Combined the above with other issues for the rewrite: Combined into #8056
