### ISSUE TITLE
Knarloc Riders have no points cost

### ISSUE THREAD

**Issue by OmniTau** [BSData/wh40k#6499]
**File/Catalogue:** 40k 8th edition/Tau

**BattleScribe version:** 2.03.017

**Platform:** Android

Knarloc Riders only cost 5 power level, no points cost associated.

**Comment by GenWilhelm** [comment]
Their rules were published without a points cost:
https://www.warhammer-community.com/wp-content/uploads/2019/09/imperial_armour_index_xenos-1.pdf

>Q: What datasheets should I use for Grot Bomb Launchas, Attack Fightas, Fighta-Bommers, Dethrolla Battle Fortresses, Kill Krushas, Raven Strike Fighters, **Knarloc Riders**, Great Knarlocs and Firestorms?
A: It is an unfortunate truth that we can’t continue indefinitely to sell and support every model we’ve ever made. As we make new models, and new books to explore their background and rules, we have to stop producing and featuring some older models. But just like many of you, we still treasure our collections of older miniatures, and we still want to be able to use them in games and forge glorious narratives on the tabletop! As such, the datasheets for these classic models can be found below, but they are intended for use in open play or narrative play games; they are not designed or approved for use in matched play games (**as they won’t, for example, have any points values**).

(emphasis is mine)
