### ISSUE TITLE
Coldstar Commander has wrong wargear limits

### ISSUE THREAD

**Issue by OmniTau** [BSData/wh40k#6500]
**File/Catalogue:** 40k 8th edition/Tau

**BattleScribe version:** 2.03.017

**Platform** Android

Coldstar command can have up to 7 wargear options, instead of the 2-4 it should be limited to.

**Comment by DrTobogganMD** [comment]
![image](https://user-images.githubusercontent.com/16939161/71551456-c20e0080-29ad-11ea-9a87-5173a0fc5717.png)

While yes, you can physically select all 7, you get a validation error. We cannot control if someone wants to ignore the error messages for validation.

**Comment by amis92** [comment]
Actually, I can confirm the problem is that there are no warnings using Android BS v2.03.17.326

Again, the app ignores constraints.

**Comment by amis92** [comment]
Another instance of https://github.com/BattleScribe/Release/issues/107

**Comment by Shiney1965** [comment]
I have the same issue for all commander battlesuits, working on iOS with updated data.  You can take any number of weapons and support systems without getting a validation warning.

**Comment by amis92** [comment]
Tracking now in #6672.
