### ISSUE TITLE
Heretic Astartes - Hellforged Deredeo Dreadnought can take invalid wargear options

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6519]
**File/Catalogue:** Chaos Space Marines v121

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** The Hellforged Deredeo Dreadnought can currently take both a greater havoc launcher and a hellfire veil, but these are mutually exclusive wargear options and the unit should be only able to take one or the other.

**Comment by Mad-Spy** [comment]
This is an app bug. It worked correctly in previous versions.
