### ISSUE TITLE
orks Deff dread base points wrong

### ISSUE THREAD

**Issue by ChaOsRul3z** [BSData/wh40k#6524]
**File/Catalogue:** Orks v67

**BattleScribe version:** 2.03.17.326

**Platform:** Android

**Dropbox:** Yes/No

**Description:** Detailed issue description.

According to the codex Deff dread points per model (does not include wargear) is 55
But in the app the base cost is 45

**Comment by Mad-Spy** [comment]
Correct as per CA2019. Please ensure you are referencing the latest publication before raising tickets.
