### ISSUE TITLE
Bug report: Imperium - Space Marines ( unit factions )

### ISSUE THREAD

**Issue by sgorii** [BSData/wh40k#6526]
**File/Catalogue:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.09

**Platform:** iOS

**Dropbox:** Yes

**Description:** The Emperor's Champion unit factions in categories seem to not appear ( only HQ )

**Comment by acebaur** [comment]
I don't understand what you mean. The Emperor's Champion is a BT only HQ. He appears in the HQ section.

**Comment by fuckingenglish** [comment]
The unit has also disappeared from my iPad when selecting black Templar.

**Comment by MrRWJP** [comment]
To clarify: The Emperors Champion does not show any keywords in the "Categories" section other than "HQ" when viewing the roster in a printable view. He should include "Black Templars", "Infantry", "Character" etc.
![Screenshot_22](https://user-images.githubusercontent.com/25469606/71646233-d4a17600-2cdc-11ea-91d6-718eb7b8e630.png)
