### ISSUE TITLE
Aeldari - Craftworlds: Dark reaper exarch is missing Rain of Death option

### ISSUE THREAD

**Issue by StefanDinges** [BSData/wh40k#6535]
**File/Catalogue:** Aeldari - Craftworlds.cat

**BattleScribe version:** 2.03.11.140

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

Only five of the Exarch powers, from Phoenix Rising, are listed for the Dark Reaper Exarch. The "Rain of Death" ability is missing as an option.

**Comment by Mad-Spy** [comment]
You'll need to equip him with the correct weapon for it to appear. It's only allowed if he has a Tempest Launcher.
