### ISSUE TITLE
Warhammer 40,000 Rulebook FAQ v1.6 (reupload)

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6536]
So over the Christmas break GW has reuploaded v1.6 of the BRB FAQ with no revision number change (1.6) and no announcement or note.

Seemingly the only difference is the removal of the old Index Wargear chart, AKA chart-of-f***ery or Designer's Commentary Chart or That Chart or whatever you came up with.

[![Chart: What datasheet rules should I use?](https://user-images.githubusercontent.com/2671396/71767803-7d83e700-2f10-11ea-9e3c-675ff3484e24.png)](https://www.warhammer-community.com/wp-content/uploads/2019/05/warhammer_40000_rulebook_en.pdf)

With that chart removed, Index Wargear options for Codex datasheets are no longer legal, and since Legends datasheets are newer publications than Indexes, Index datasheets are no longer valid as well*.

> \* - this excludes units that have had no updated datasheets since their Index came out, e.g. Tyranid Shrikes.

**Comment by Mad-Spy** [comment]
Will no longer be relevant in 9th edition. Closing.
