### ISSUE TITLE
Chaos - Chaos Space Marines: Battering Onslaught doesn't appear when selecting two melee on Helbrute

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6537]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 3.17.32

**Platform:** Android

**Dropbox:** No

**Description:** Version: BattleScribe v2.03.17.326

Helbrutes do not show their "battering onslaught" ability. When equipped with 2 melee weapons, Helbrute attacks should increase by 1 (from base 4 to 5 per the codex) OR Helbrute datacard should state "Battering Onslaught: Add 1 to this model's Attacks characteristic if it is equipped with two melee weapons." 
This ability is listed on Pg. 139 of the Chaos Marine Codex. I have found no FAQ that removes it.

**Comment by williamcaw** [comment]
which Chaos Marine Codex codex
