### ISSUE TITLE
Imperium - Adeptus Mechanicus: Ranger/Vanguard max unit size not checked

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#6541]
**File/Catalogue:** Imperium - Adeptus Mechanicus v65

**BattleScribe version:** 2.03.11

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:**

When adding models to a unit of rangers/vanguards, it does not throw an error if the total number of models exceeds 10.  For example, an Alpha, 9 standard troops and 3 special weapon troops is considered valid, when it should throw an error for having more than 10 models in the unit.

**Comment by Thairne** [comment]
Ah christ.

**Comment by Thairne** [comment]
Once "shared" is selected in a constraint, it doesnt seem to work on anymore, at least when used in SEGs...
