### ISSUE TITLE
Imperium - Space Marines: Dreadnought twin autocannon should be 20pts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6552]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Legends points for Dreadnaughts twin autocannons states 33 points should be 20 points

**Comment by Mad-Spy** [comment]
Both are incorrect in v126, and only one got changed to the correct costs in v127.
