### ISSUE TITLE
[Legends] Honour Guard

### ISSUE THREAD

**Issue by IdleMuse** [BSData/wh40k#6555]
**File/Catalogue:** 40k 1.4.3 space marines v126

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** Legends Honour Guard have no points costs for their weapons where I think they should pull them from the codex? Also their ability seems to be hardcoded to ULTRAMARINES whereas it's CHAPTER in the Legends pdf

**Comment by Dunamis55** [comment]
If using Honour Guard in a non-Ultramarines list, it would be a Legends choice, have the <CHAPTER> keyword, and wargear options would cost extra points.
In an Ultramarines list, Honour Guard would be non-Legends, have the ULTRAMARINES keyword, and wargear options are all included in the cost.

**Comment by IdleMuse** [comment]
That makes sense, explains why this is slighty wonky currently! It's effectively correct as is for the Ultramarines-supplement version, but not for the Legends version.
