### ISSUE TITLE
Orks: Deff Dread power cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6566]
**File:** Orks.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** Dread Mob of one or two Deff Dreads power is 1 higher than it ought to be.

i.e. Single Deff Dread is 5 power, but the unit shows 6 power. Two Deff Dreads are 5 power each, but the unit shows 11 power.

**Comment by Mad-Spy** [comment]
I was unable to replicate the original issue (as far as I could tell this situation could never happen in the current implementation.

However, I have reworked it so that you'll always get the correct value now, and additionally, correctly limited the number of Dreads in a Mob.
