### ISSUE TITLE
Imperium - Dark Angels: RW Grenade Launcher is unavailable

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6570]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Ravenwing Apothecary and Ravenwing Ancient don't have the option to take a Ravenwing Grenade Launcher in place of their Plasma Talons, despite the codex saying they have that option and there doesn't seem to have been an FAQ to prevent that.

**Comment by Mad-Spy** [comment]
The RW Grenade Launcher entry is hidden with no way for it to become visible on Black Knight bikes.
