### ISSUE TITLE
Imperium - Space Marines - Chaplain Venerable Dreadnought

### ISSUE THREAD

**Issue by liftedlimo** [BSData/wh40k#6571]
**File/Catalogue:** 

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** SM Chaplain Venerable Dreadnought Abilities: Litanies of Battle is now incorrect. It now reads "Litanies of Battle (Chaplain Ivanus Enkomi)" and the description is incorrect (thought the rules are better *sigh*).
--

**Comment by Mad-Spy** [comment]
Fixed in #6516.
