### ISSUE TITLE
Wrong PL for DW Terminator Squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6578]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** There is no power level for Deathwing Terminators. I believe it should be 11, but as of writing this, it is listed as 'no cost.

**Comment by Thairne** [comment]
DW Terminator Squads are listed at 13 PL in the codex.
CA doesnt update power levels and I'm not aware of any other change to 11 points.
Also, they do have the correct pts cost in desktop.
![grafik](https://user-images.githubusercontent.com/8590840/72244023-a893c800-35ed-11ea-823a-1a3134432ace.png)
