### ISSUE TITLE
Imperium - Space Marines: Scout Sgt weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6584]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Hello,

It is possible to choose Astartes shotgun, Bolt pistol, Boltgun, Combat knife, Thunder hammer, Combi-melta for Scout Sergeant at the same time without any error message.

Thanks
Balazs

**Comment by acebaur** [comment]
This is an App bug and unfortunately there is no way that I can see to fix it. It is replicated on other sgt's as well.

**Comment by amis92** [comment]
Tracking now in #6672.
