### ISSUE TITLE
Imperium - Grey Knights - Purgation Squad model costs do not update after the first instance.

### ISSUE THREAD

**Issue by TophatKiyaki** [BSData/wh40k#6585]
**File/Catalogue:** Imperium - Grey Knights.catz (Imperium - Grey Knights v49)

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** The Points Values for the Purgation Squad Unit will only update if the first instance of any model variant option is added or removed. Additional instances of the same model will not be counted, unless the first instance of a different model is added, at which point the cost will update correctly. Attached images demonstrate the issue.

![Purgation Squad 01](https://user-images.githubusercontent.com/31428938/72383643-e2e28f80-36e9-11ea-9629-fee885366296.png)
![Purgation Squad 02](https://user-images.githubusercontent.com/31428938/72383652-e5dd8000-36e9-11ea-9497-865e47a90a1e.png)
![Purgation Squad 03](https://user-images.githubusercontent.com/31428938/72383659-e7a74380-36e9-11ea-92f8-792d8743d91f.png)
![Purgation Squad 04](https://user-images.githubusercontent.com/31428938/72383663-ea099d80-36e9-11ea-8cd5-02b7b61673a6.png)
![Purgation Squad 05](https://user-images.githubusercontent.com/31428938/72383715-03aae500-36ea-11ea-9b27-cbd57625e06b.png)
![Purgation Squad 06](https://user-images.githubusercontent.com/31428938/72383716-0574a880-36ea-11ea-9b27-ca7b0ba2f510.png)

**Comment by Mad-Spy** [comment]
This is a Battlescribe bug, not a data issue. It's already been reported to the app developer, but please feel free to report it again.

**Comment by TophatKiyaki** [comment]
> This is a Battlescribe bug, not a data issue. It's already been reported to the app developer, but please feel free to report it again.

Interesting. Is there a reason why it only applies to this particular entry in the data? The rest of the Grey Knights catalogue seems to be working fine, and I'm yet to run into this anywhere else in the other Battlescribe datas I utilize.

**Comment by Mad-Spy** [comment]
It will be something to do with how the unit is constructed in the back end. Regardless, it _should_ correctly calculate regardless of how the data is structured so we're waiting on the dev to fix it.
