### ISSUE TITLE
Imperium - Adeptus Ministorum: Something about Canoness weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6586]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Cannoness melee options” chainsword “ overriding  selections in  Ranged weapons.

**Comment by Mad-Spy** [comment]
This is insufficient detail for us to determine what the problem might be or fix it. Please provide additional information or this issue will be closed.

**Comment by alphalas** [comment]
probably someone complaining about her wonky logic because of specific wargear requirements for upgrades.
