### ISSUE TITLE
Blood Angels can have 155 man Vanguard Veteran Squads with no error.

### ISSUE THREAD

**Issue by corrinavatan** [BSData/wh40k#6588]
**File/Catalogue:** Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** as per issue description.  There is no validation flag that occurs when adding more than 9 Space Marine Veteran models to a Vanguard Veteran squad.  Was able to get the unit to a size of 155 while still not getting a list error.

**Comment by corrinavatan** [comment]
Same occurs for regular SM Van Vets, as well.

Deathwatch Vanguard Vets DOES throw an error if squad size goes above 10, so doesn't need corrected.

Space Wolves/Dark Angels do not have Van Vets as available units.

**Comment by alphalas** [comment]
It’s a battlescribe bug not a data bug - DW vets are implemented differently so aren’t affected by it.

**Comment by corrinavatan** [comment]
So I guess I am not sure how this can be stated as simultaneously a BS issue, but since Deathwatch are implemented differently, it doesn't occur.

That would suggest if the BA Data is changed... The error would be fixed.

**Comment by alphalas** [comment]
Because there’s no actual need to change the data - the app will eventually be fixed so that the data functions as it should
