### ISSUE TITLE
Psychic Awakening: Ritual of the Damned

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6594]
This new campaign book was announced for release on 2020-01-25.

Webstore listing:
https://www.games-workshop.com/Psychic-Awakening-Ritual-Of-The-Damned-EN-2020

- [x] Dark Angels
- [x] Grey Knights
- [x] Thousand Sons

**Comment by tekton** [comment]
I somehow missed this one; but the GK stuff is already done/merged.

**Comment by Mad-Spy** [comment]
Closing as we've all done the work.
