### ISSUE TITLE
Chaos - Chaos Space Marines: Red Butchers should be available for Terminator Characters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6596]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Faith & Fury
CSM World Eaters "Red Butchers" Stratagem can be used on terminator characters as well as "Chaos Terminator" units (ie "Chaos Lord in Terminator Armour") according to the official Faith and Furry Errata

**Comment by Mad-Spy** [comment]
Fixed in v126
