### ISSUE TITLE
Imperium - Blood Angels: A few issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6598]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** 
- Company Veterans with Jump Packs are 5 points too high
- Inferno Pistols should be 9 points, 
- Dreadnoughts should still be able to take two Twin Autocannons. 

Cheers and thanks for the work.

**Comment by alphalas** [comment]
![Screen Shot 2020-01-20 at 8 15 42 PM](https://user-images.githubusercontent.com/15703066/72767401-b8994200-3bc1-11ea-950f-7c1370f499fc.png)
 also specifically which inferno pistol is not 9pts? what version of the data are you using?

**Comment by zeoevil** [comment]
I posted this last night. The Jump Pack entry on the Veterans was 5 points with 5 points per model so it came up 5 points too high, he Inferno Pistol entry was on my HQs (where it says it is 7 points), and the Dreadnought entry said two autocannons were invalid. Said it was limited to one twin autocannon per model.
