### ISSUE TITLE
Aeldari - Ynnari: Ynnari HQ WLTs were changed in Phoenix Rising

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6604]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** In Phoenix Rising they changed what Warlord traits the three characters get.
they are now
Yvraine - Warden of Souls
Yncarne- Fear the Grave

**Comment by dalamar666** [comment]
Oops I thought I was logged in.  GW changed only the 2 characters.

**Comment by FarseerVeraenthis** [comment]
This is part of #6498 
When I was doing the update I just could not get the correct warlord powers to auto select, it is very possibly a BS bug but when I have some time I'll have another go and see if it's something obvious!
