### ISSUE TITLE
Cataphractii Termie weapons

### ISSUE THREAD

**Issue by Junkman4** [BSData/wh40k#6607]
The weapon options are still showing that they need 2 after selecting the pair of Lightning Claws.

**Comment by Mad-Spy** [comment]
Which catalogue is this in?

**Comment by Mad-Spy** [comment]
@Junkman4, which catalogue is this in?

**Comment by Junkman4** [comment]
Normal Space Marines, It was fine before the codex update, I don't know what changed.

**Comment by Mad-Spy** [comment]
It's more than likely an app bug, but it needs checking.

**Comment by acebaur** [comment]
It was the app bug, working now.
