### ISSUE TITLE
Psychic Awakening: Engine War

### ISSUE THREAD

**Issue by Thairne** [BSData/wh40k#6615]
This issue is a reference, anything associated should be done in separate issues with a mention of this one.

Set for release in April.

**Comment by amis92** [comment]
Please update the https://github.com/BSData/wh40k/wiki/Publications with release date and mark as in-use, when ready :)

Was it actually released already, or corona-delayed?

**Comment by DrTobogganMD** [comment]
Hah, released. You're a funny one. I've updated the month to XX

**Comment by fuckingenglish** [comment]
adding cat: Imperium - Imperial Knights  to lords of war to  cat: Imperium- Adeptus Mechanicus 
no longer a separate entity 
![image](https://user-images.githubusercontent.com/47985304/82929292-44d4c080-9f38-11ea-8a38-c385690280d9.png)

**Comment by DrTobogganMD** [comment]
What?

**Comment by Mad-Spy** [comment]
All catalogues updated.

**Comment by amis92** [comment]
Someone update wiki as "in-use" please?

**Comment by DrTobogganMD** [comment]
Done
