### ISSUE TITLE
Thousand Sons - [LEGENDS] units

### ISSUE THREAD

**Issue by Quixus** [BSData/wh40k#6617]
**File/Catalogue:** Thousand Sons v61

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

There are several HQ units in the catalogue that have a regular version and a [LEGENDS] version. It appears that the latter is the version from the index but somehow changed. That is not how the Index rules are supposed to be grandfathered in. You are not supposed to use the old rules for the entire unit but just add the discontinued wargear with the most recent rules (see [Warhammer 40,000 Designers' Commentary](https://whc-cdn.games-workshop.com/wp-content/uploads/2017/11/warhammer_40000_designers_commentary_en-1.pdf)).

For example there should not be two Sorcerers in Terminator Armour but the combi-weapon options should be added to the Codex Version. The Daemon Prince is a special case as there is actually a new Data Sheet.  Daemon Prince is not the same as Daemon Prince of Tzeentch.

**Comment by alphalas** [comment]
While I do agree with the thrust of your main point about no duplicate units, I do have one thing to point out to you - you are linking to a depreciated version of the Designer’s commentary, see #6536

**Comment by Quixus** [comment]
Interesting. Where can I find the Legends data sheets mentioned in #6536?

**Comment by Mad-Spy** [comment]
https://www.warhammer-community.com/legends/

I suggest you keep an eye on that page. It's where GW announce all their new content.

However, I will not be changing the implementation.
