### ISSUE TITLE
Thousand Sons - Ritual of the Damned - cult psychic powers

### ISSUE THREAD

**Issue by StuxAlpha** [BSData/wh40k#6618]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:**
All cult units in the detachment should have the cult psychic power. Current release only characters have the power. Rubrics and Scarab Occult should get it too.

**Comment by Mad-Spy** [comment]
Seems to be a problem with BS. The data is there, but it only updates for the unit Sorcerors if you make a change to that model _after_ setting the Cult. I'll see if I can find a workaround.

**Comment by Mad-Spy** [comment]
I haven't been able to find a decent solution to this that I like. As long as you select your Cult before adding the Rubrics or Scarabs (or make a change to those units after changing Cult), the correct Cult power will be displayed.
