### ISSUE TITLE
PA4 DA Chaplains

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6621]
**File/Catalogue:** Imperium - Dark Angels v126

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** 

Interrogator Chaplain has litanies of battle Twice. while Asmodai only have once. 
Asmodai knows 2 litanies not Interrogator Chaplain
Interrogator Chaplain in terminator can't select melee weapons, it can only replace stormbolter from terminator combi weapons list

**Comment by Thairne** [comment]
Interrogator Chaplain in terminator can't select melee weapons, it can only replace stormbolter from terminator combi weapons list

True, but the model can in Legends, which why the name is changed accordingly with a LEGENDS tag.
