### ISSUE TITLE
PA4 DA Relics

### ISSUE THREAD

**Issue by miku2020** [BSData/wh40k#6624]
**File/Catalogue:** Imperium - Dark Angels v126

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
There are few issues with relics
- heavenfall blade says always maximum 0. same with blade of burden
- Talonmaster cannot have anything from special Issue wargear because of Vehicle keyword.
- Phobos master is missing Deathwing options.

**Comment by Thairne** [comment]
Master in Phobos Armour does not have the Deathwing keyword though.
