### ISSUE TITLE
Imperium - Grey Knights: Sanctic Powers list not validating correctly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6633]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** For Grey Knights Purgation squads, Paladin squads, and the Doomglaive dreadnought are regestering roster errors for knowing assigning a known singular sanctic power.

**Comment by Peresh242** [comment]
This occurs for a number of units, Not only the ones mentioned above.

**Comment by tekton** [comment]
Duplicate of #6633
