### ISSUE TITLE
AM - Ogryn bodyguard Relic

### ISSUE THREAD

**Issue by Moon-Hunter** [BSData/wh40k#6637]
**File/Catalogue:** 

**BattleScribe version:** 2.03.11

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Ogryn bodyguard can take "The dagger of Tu'Sakh", but battlescribe don`t allow this.

**Comment by Mad-Spy** [comment]
He cannot because (as per Update 1.3) the Dagger is restricted to INFANTRY OFFICER models.
