### ISSUE TITLE
Dark Angels Issues

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k#6646]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** /No

**Description:** Two Issues 
1.  All DA Chaplains of all varieties get to choose 1 litanies of battle, and get Stoic Prosecution in addition to all others. also the spelling is wrong.
2.  The Deathwing Ancient cannot take Pennant of Remembrance
![Ancient 2020-01-27 143732](https://user-images.githubusercontent.com/17829946/73212727-78cbe080-4114-11ea-8dd8-7b01d4b73e17.png)

**Comment by Thairne** [comment]
Those were already fixed and will be available with the next release :)
