### ISSUE TITLE
Dark Angels maybe its me?

### ISSUE THREAD

**Issue by dalamar666** [BSData/wh40k#6647]
Your data is outdated. v122 vs v126 which is the current one IIRC.

_Originally posted by @Thairne in https://github.com/BSData/wh40k/issues/6642#issuecomment-578952925_

Incorrect Sir.

My version is v126

**Comment by dalamar666** [comment]
![dacat 2020-01-27 151408](https://user-images.githubusercontent.com/17829946/73214758-69e72d00-4118-11ea-97a8-8e9dbeecaffd.png)

**Comment by Mad-Spy** [comment]
Closing as this is a comment not an issue. I have reopened #6642
