### ISSUE TITLE
Imperium - Dark Angels: Relic validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6652]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** When I give any relic, the app gives an error that this relic has too many selections (maximum 0).

**Comment by Mr-Dartimon** [comment]
![Screenshot_20200128_183626](https://user-images.githubusercontent.com/60399517/73289523-26b2ba00-41fd-11ea-8602-5ddf089acaec.jpg)

**Comment by Mr-Dartimon** [comment]
Whenever I give any relic to charakter, the app provides an error that "relic has too many selections (maximum 0)"

**Comment by Mr-Dartimon** [comment]
I rechecked it. App provides an error when I choose Angel's Ambit from relics for any character or when I choose Heavenfall Blade from Main Armament for Primaris Lieutenant

**Comment by Mr-Dartimon** [comment]
I updated the data a few minutes ago, the error is gone

**Comment by Thairne** [comment]
ah weird, I think I typed a comment and didnt send it ~~
I was about saying as much that SOME relics were affected which was fixed, but not all. But all is well, then.
