### ISSUE TITLE
Inconsistant display of Explodes rule for Repulsor and Repulsor Executioner in different ctaz

### ISSUE THREAD

**Issue by TJ-paints-and-games** [BSData/wh40k#6660]
Hi all, will probably start with this by saying "Not a priority" as it it is there, however.....

I noticed that the Repulsor was "missing" its Explodes rule in its roster entry in Imperium - Space Marines so did some digging, it wasn't missing as such, just in the wrong place, and it turns out the display of the rule is inconsistant between the different Astartes catz's.

**Repulsor**
Blood Angels | Appears as separate table in roster entry
Dark Angels |  Appears in abilities in roster entry
Deathwatch | Appears in selection rules (i.e. right at the bottom of the roster when viewed)
Space Marines | Appears in selection rules
Space Wolves | Appears in selection rules

**Repulsor Executioner**
Blood Angels | Appears in selection rules
Dark Angels | Appears as separate table in roster entry
Deathwatch | Appears in selection rules
Space Marines | Appears in selection rules
Space Wolves | Appears in selection rules

~~In addition, for Space Wolves, the Repulsor does not have any default weapons pre-selected like the others. Repulsor Executioner is ok for all.~~ Moved to #6661 

Cheers.

**Comment by Mad-Spy** [comment]
At some point, after all the Marine data gets moved to a library, this will go away.

However, for now, although there are guidelines, the final decision on how to implement profiles and rules is up to the individual maintainers for each catalogue.
