### ISSUE TITLE
Heavenfall blade missing from Lieutenants options

### ISSUE THREAD

**Issue by jasarien** [BSData/wh40k#6662]
**File/Catalogue:** imperium dark angels, v127, wh40k v 1.4.6

**BattleScribe version:** 2.03.09

**Platform:** iOS

**Dropbox:** Yes

**Description:** The heavenfall blade does not appear as an option in the relics list for a Lieutenant. Even if I select a power sword, and then look at the relics it still isn’t available. 

I noticed that some ritual of the damned fixes were in this release, so I was hopeful, but it still seems to be an issue. 

It was a selectable option in the ‘power swords’ list before the ritual of the damned releases were made. 

![F0AF6093-DE46-4B30-8D9F-E1D5C1976F7B](https://user-images.githubusercontent.com/104444/73391267-84afd200-42cf-11ea-8335-a46e7f4db662.jpeg)
![63DC8E4F-2301-4A03-B3F6-AA1B70016D20](https://user-images.githubusercontent.com/104444/73391269-84afd200-42cf-11ea-9cc8-7023b22c3cdf.jpeg)

**Comment by Gingrel** [comment]
I believe this has already been fixed - check the closed issues

**Comment by jasarien** [comment]
There is a similar issue in the closed issues where selecting a heavenfall blade would produced a validation error. But since then, I can’t even select the relic. The option is not there anymore. This is a different issue.

**Comment by Gingrel** [comment]
I mentioned your problem (Heavenfall Blade not showing up) in the issue I raised the other day, and I chatted to Thairne about it on Discord. Either way, best to wait for Thairne to confirm but I thought I'd mention it just as an FYI

**Comment by jasarien** [comment]
Thanks, but I’m just reporting what I’m seeing after updating to the latest data after the release that says it resolves Ritual of the Damned issues, so I think it’s still an issue.

**Comment by Thairne** [comment]
Might be an iOS issue then, since it is there for me for Lieutenant and Primaris Lieutenant.

![grafik](https://user-images.githubusercontent.com/8590840/73436718-58399b80-434b-11ea-9000-30f7fcc077db.png)

The logic for the heavenfall blade unhides it if you're a DARK ANGEL or picked the Honored by the Rock Stratagem and have either a DA warlord or the Relics of the Rocks Stratagem. 
Nothing fancy there...
You do see the other relics, so thos criteria should be fulfilled...

**Comment by jasarien** [comment]
This is strange. Seems to be something in my existing list that is conflicting with those requirements. If do the same as you and make a new Dark Angels list with an unbound army, and add a lieutenant and select as warlord the heavenfall blade shows up, but not in my existing list.

I have 2 battalions, the lieutenant is in the first, with Azrael as the warlord, and the chapter selection is Dark Angels (not a successor). So, it should show?

**Comment by jasarien** [comment]
Ok, I've narrowed it down. I made a new list, added two battalions, and the heaven fall blade doesn't show up. I removed the second battalion, and the heaven fall blade now shows. It reproduces in Battlescribe desktop as well.

<img width="1559" alt="Screenshot 2020-01-30 at 09 50 13" src="https://user-images.githubusercontent.com/104444/73438506-0cd0be80-4346-11ea-899f-21c8c910dd5a.png">

**Comment by Thairne** [comment]
Oh I think I get it.
The conditional checks for ONE instance of DARK ANGELS... Once you have two, you obviously dont have ONE....
*dumbface*

**Comment by jasarien** [comment]
😅 hope that helps to get it fixed!

**Comment by Thairne** [comment]
Yes, yes it did ^^
