### ISSUE TITLE
No max unit size on Centurion Squads

### ISSUE THREAD

**Issue by MrRWJP** [BSData/wh40k#6663]
**File/Catalogue:** Imperium - Space Marines v129

**BattleScribe version:** 2.03.11.140

**Platform:** Windows

**Dropbox:** Yes

**Description:** There is no maximum limit set on the number of Centurions that can be included in a Centurion Assault Squad or Centurion Devastator Squad. Centurion Squads should only be able to take up to 3 additional Centurions in addition to the default Sergeant and 2 Centurions. (Space Marine Codex 2019 Pg 141 and Pg 149).

**Comment by acebaur** [comment]
This is a known app bug and we don't currently have a fix for it.
