### ISSUE TITLE
Tau Ghostkeel max support system wrong

### ISSUE THREAD

**Issue by tvb** [BSData/wh40k#6670]
**File/Catalogue:** Tau v53

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes

**Description:**

BS allows for 3 support systems on a Ghostkeel but the index clearly says only 2 items is allowed. AFAIK this has not been FAQed

![232030FA-EBC9-40AE-981C-661397B70358](https://user-images.githubusercontent.com/1263414/73489166-797da480-43aa-11ea-9b99-a476082bf2c5.jpeg)

**Comment by amis92** [comment]
Another case of https://github.com/BattleScribe/Release/issues/107

Data is correct, app is bugged.

**Comment by amis92** [comment]
Tracking now in #6672.
