### ISSUE TITLE
[PSA] BattleScribe doesn't validate some constraints

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6672]
Since v2.03.11[Desktop], 2.03.17[Android], 2.03.09[iOS], BattleScribe stopped validating some constraints, specifically those on entry links.

This results in multiple cases of wrong min/max or even no limits at all for various wargear, weapons, models, essentially any variable-amount entries.

It's an app bug, not a data issue, and we as data authors should not attempt to fix these on our side.

**Comment by OftKilted** [comment]
Additional visual example:
![F24B7064-1D71-47A6-B6CE-FD494F3D5C36](https://user-images.githubusercontent.com/17132967/73748177-e5ec0100-4726-11ea-97af-f0f68f1bce15.png)

**Comment by amis92** [comment]
Via https://github.com/BattleScribe/Release/issues/107#issuecomment-586532441

> Fixed in:
> Desktop 2.03.12.141
> Android 2.03.18.327
> iOS 2.03.10.145 (pending Apple review)
