### ISSUE TITLE
Imperium: Space Marines Missing Warlord Trait 

### ISSUE THREAD

**Issue by thealteredmind** [BSData/wh40k#6677]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Imperium-Space Marines lacks the option to give a warlord trait belonging to the Indominus Crusaders specialist detachment. There should be the option to take the Grey Sheild trait that belongs to that detachment.

**Comment by Mad-Spy** [comment]
@acebaur, most likely the link modifier bug. The SSEG unhides on selecting the Specialist Detachment, but the WLT doesn't.

**Comment by thealteredmind** [comment]
Is this something I can fix myself?
