### ISSUE TITLE
Chaos - Chaos Knights: Knights should be able to take BRB WLTs

### ISSUE THREAD

**Issue by Charlesfox9999** [BSData/wh40k#6681]
**File/Catalogue:**  Chaos knight

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux android

**Dropbox:** Yes/No

**Description:** Detailed issue description.

I have chosen the acastus knight porphyrion as my warlord. The only warlord traits choice are the warlord traits from the codex. I should be able to take the warlord traits from the base book also.

**Comment by Mad-Spy** [comment]
This is incorrect. The Warlord Trait page (p70) in the Codex clearly states that Knights cannot take a BRB Trait.
