### ISSUE TITLE
Grey Knights: Augurium Scrolls relic restriction

### ISSUE THREAD

**Issue by jakemco** [BSData/wh40k#6683]
**File/Catalogue:** Grey Knights

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Looking at the book, there's no additional restriction on when a character model can take the "Augurium Scrolls" relic, but when I switch my Paladin Ancient from "Storm Bolter and Falchion" to "Psilencer", I get the error: "Paladin Ancient cannot have any selections of Augrium Scrolls".

**Comment by Mad-Spy** [comment]
This Relic has been mistakenly hidden for models which do not have a Nemesis weapon, but it is not required that the model itself has such a weapon.

In addition, the name has a typo; it should be AUGURIUM Scrolls.

**Comment by tekton** [comment]
I was tired, ok? Thank you @jakemco
