### ISSUE TITLE
Imperium - Dark Angels: Relic Cerberus missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6685]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** The Relic Cerberus Super Heavy Tank Destroyer is missing from the Dark Angels Super Heavy Auxiliary detachment

**Comment by Thairne** [comment]
Update your data, it should be there in v127.
