### ISSUE TITLE
Dark Angels blade of burden relic missing

### ISSUE THREAD

**Issue by Etharin** [BSData/wh40k#6687]
**File/Catalogue:** Imperium - Dark Angels

**BattleScribe version:** 2.03.09

**Platform:** iOS

**Dropbox:** Yes

**Issue description:** The blade of burden relic doesn’t seem to have been added. I can’t add it under power sword for either a master or master in terminator armour. The heavenfall blade appears as an option though.

**Comment by Mad-Spy** [comment]
Appears to be fixed in DA v128. Will be in next release.

**Comment by Etharin** [comment]
Ah cool, thanks 😊
