### ISSUE TITLE
Ravenwing Talonmaster invalid Relics

### ISSUE THREAD

**Issue by rtho782** [BSData/wh40k#6688]
**File/Catalogue:** Imperium - Dark Angels v126

**Description:** Special Issue Wargear cannot be taken by vehicles as per P58 of the PA4 book: "Named characters and VEHICLES cannot be given any of the following Relics."

As such these items are not valid options for Ravenwing Talonmaster.

**Comment by Mad-Spy** [comment]
The only Relic which might be incorrect is the Corvus Oculus; all the other available Relics in v127 of the DA file are from the Codex and are therefore allowed.

**Comment by rtho782** [comment]
My bad, this is actually fixed in v128 as I've just downloaded.

Corvus Oculus is Ravenwing Talonmaster only, it's definitely allowed on the Talonmaster.
