### ISSUE TITLE
Imperium - Space Marines: Crusader Relics Stratagem is not unlocking Relics

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6692]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 3.11.14

**Platform:** Windows

**Dropbox:** No

**Description:** Under a black templars detatchment- I selected crusader relics.

This should allow me to upgrade a power sword on a sergeant or character to the sword of judgement. Previously I was able to do this, now I am not. I do not see any crusader relic options except on commanders.

**Comment by Mad-Spy** [comment]
Also, Stratagem is misspelled.
