### ISSUE TITLE
Imperium - Dark Angels: Blade of Burden missong on Master in Terminator Armor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6695]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** Warhammer 40,000 version 1.4.6 - Dark Angels-  Relic Item Blade of Bruden is not available to be used for on Master in Terminator armor. In Fact I cant find it anywhere. I've tried multiple routes. Checked online posts, and seems that only 1.4.5 had the option. Will someone please fix this?

**Comment by Thairne** [comment]
#6659
