### ISSUE TITLE
Imperium Astra Telepathica missing Sisters 

### ISSUE THREAD

**Issue by Prater40k** [BSData/wh40k#6696]
**File/Catalogue:** imperium Astra Telepathica 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Sisters of Silence should be an Elites choice for Astra Telepathica detachments, but I can’t find them anywhere.

**Comment by alphalas** [comment]
Incorrect, according to the index they are separate armies

**Comment by Prater40k** [comment]
![1428811C-EF72-44CC-BB9E-EA518EADA6B1](https://user-images.githubusercontent.com/60658499/73758941-d671b580-4730-11ea-8708-b84d7965573f.jpeg)
![F2B5C07A-D779-4AD6-9091-D9673992E8AE](https://user-images.githubusercontent.com/60658499/73758943-d671b580-4730-11ea-8d34-26ac11fb07de.jpeg)
How does the Index list them as seperate?  They have the Astra Telepathica keyword

**Comment by alphalas** [comment]
Just because they have the same key word doesn’t mean they’re from the same army. Sisters of silence are separate from AAT 
![600A3C03-9B15-4402-9F78-89CE73D336D8](https://user-images.githubusercontent.com/15703066/73767938-2e66e700-4746-11ea-9910-76c38236c212.png)
