### ISSUE TITLE
Report: Adepta Sororitas Arco-Flagellant and Preacher issues.

### ISSUE THREAD

**Issue by MagusRogue** [BSData/wh40k#6697]
File: Imperium - Adepta Sororitas v99

BattleScribe version: v2.03.11.140

Platform: Windows

Dropbox: No

Description: Warhammer 40,000 8th Edition version 122 - Adepta Sororitas- Ecclesiarchy Battle Conclave ability is not working correctly for the Arco-Flagellants.  Even though it shows up in No Force Slots when you add a Priest unit, if you select it and are using battle-forged detachments, it still counts as an elite slot and gives an error that you're used too many Elites if you already have your Elites slots filled.
Preachers cannot change their wargear. They only have laspistols and chainswords. Any other options needs to be labelled as a Legends option, since this is not official anymore and is a hold-over when they were just called Ministorum Priests. Probably should remove the choices altogether and add Ministorum Priest (Legends) to the No Forces Org Slot section.

**Comment by MagusRogue** [comment]
Finding some more issues.

Sister Superiors from all squads don't give errors if you try to give them more than one pistol or don't remove the pistol/boltgun/etc when selecting another weapon.

**Comment by MagusRogue** [comment]
lastly, the current version doesn't include the new Sororitas Errata:

Page 77 – Canoness
Change the first wargear option to read:
‘This model can be equipped with 1 plasma pistol, 1 power sword and 1 rod of office instead of 1 bolt pistol and 1 chainsword.’
Page 92 – Mortifiers
Change the second sentence of the unit description to read:
‘It can additionally contain up to 3 Mortifiers (Power Rating +3 per model).’

**Comment by MagusRogue** [comment]
Any Non-Seraphim/Zephyrim Sister Superior (so Battle Sister Squad, Celestial Squad, Dominion Squad, Retributor Squad), Power Axe needs to be labeled Legends under Additional Melee Weapon.

**Comment by alphalas** [comment]
ok so finally getting around to bug fixes. i have a feeling a lot of the "bugs" you reported are BS bugs, not data bugs. 
1, arcos
yup elite was no SE not RSE. fixed.
2, preacher.
![Screen Shot 2020-02-10 at 12 21 14 AM](https://user-images.githubusercontent.com/15703066/74123079-6d0ffd80-4b9b-11ea-9f6d-4e1c6f817567.png)
bs bug.
3, BS Bug.
4, canoness and morts are indeed correct - as a matter of fact morts were correct before the FAQ came out - I went with the unit size that was at the back of the book, not on the data sheet. I was correct.
5, again, BS Bug.
