### ISSUE TITLE
Space Wolves: old cost of Land Speeders

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6698]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Space wolves Land Speeders coast is not reflected changes in latest Chapter approved 2019.

**Comment by Mad-Spy** [comment]
Cost (70pts base) is correct in latest release.
