### ISSUE TITLE
Chaos - Death Guard - Plague Champion weapon options missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#670]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Under the Plague Marine Plague Champion weapon options, there is no entry for "power fist / bolt pistol" whixh is what the Dark Imperium model is equipped with. There should be an entry added for this wargear option. The Death Guard book included with Dark Imperium list the point value of the powe fist at 29 additional points, and 0 for the bolt pistol.

Thanks!

**Comment by skonk** [comment]
Set it to "Bolt pistol and other" and then select a Power Fist for the "other" part.

![snip20170706_3](https://user-images.githubusercontent.com/621514/27902875-3ee15e0c-622f-11e7-93aa-d2994b69ead1.png)

**Comment by cartag** [comment]
Point totals are matching index, which according to FAQ is the point last that should be followed. Invalid bug rep.

**Comment by cartag** [comment]
Point totals are matching index, which according to FAQ is the point last that should be followed. Invalid bug rep.
