### ISSUE TITLE
Lamentors in wrong catalogue

### ISSUE THREAD

**Issue by cwoac** [BSData/wh40k#6700]
**File/Catalogue:** Space Marine / Blood Angels

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

**Description:** 
Currently Lamentors are availiable as a successor chapter option under the Space Marine Catalogue and not in the Blood Angels catalogue. As they are canonically a BA successor, this is where they should be to give them the correct unit options.

**Comment by Mad-Spy** [comment]
GW's guidance is ambiguous and so they appear in both the Space Marines _and_ Blood Angels catalogue at present.
