### ISSUE TITLE
Chaos - Chaos Space Marines: Aspiring Sorcerer missing plasma pistol

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6704]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Rubric Marine Aspiring Sorcerer wargear options do not match Codex: Chaos Space Marines. Unlike the codex options, they have access to Force Swords and Force Axes and do not have access to Plasma Pistols.

**Comment by Mad-Spy** [comment]
This shows how often anyone plays Rubrics in CSM armies!

The Force weapon options are Index options. I don't think we've made an official decision on whether we're going to remove options which were in the Index, but are not in Legends, following the removal of the Index flowchart as per #6536
