### ISSUE TITLE
Grey Knights - Smite (Rites of Banishment) Tpyo

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k#6707]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** IOS 

**Dropbox:** No

**Description:** Rites of banishment is missing the word Visible. It should say “the closest visible enemy unit”.

**Comment by Mad-Spy** [comment]
Which catalogue is this in?

**Comment by SSSlippy** [comment]
This is grey knights.

**Comment by tekton** [comment]
It's taken from a really old (Index era) screen shot of what smite would be; thanks!
