### ISSUE TITLE
Craftworlds - Missing Fire Dragon Exarch Power Choices

### ISSUE THREAD

**Issue by KalChoedan** [BSData/wh40k#6713]
**File/Catalogue:**  Craftworlds v91

**Description:** 
Fire Dragon Exarch is missing 2 out of his 6 Exarch abilities:

**Tank Killer**
Your Exarch may re-roll one of the damage dice made by an attack using the Fire Pike, but only against VEHICLEs.

**Wall of Fire**
Your Dragon's Breath flamer wielding Exarch may forego his overwatch shot against a charging unit and roll 1d6. On a 2+, the charging enemy unit takes D3 mortal wounds.

(I don't have the publication to hand to confirm the exact wording, sorry.)

**Comment by Mad-Spy** [comment]
You need to give him the right weapon for these powers to appear.
