### ISSUE TITLE
Chapter Approved 2019 Update 1.0

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#6726]
Link below: https://www.warhammer-community.com/wp-content/uploads/2020/02/8fa9c5ab.pdf

- [x] Aeldari - Drukhari
- [x] Chaos - Daemons
- [x] Imperium - Adeptus Custodes
- [x] Imperium - Adeptus Mechanicus
- [x] Imperium - Adeptus Ministorum
- [x] Imperium - Astra Militarum
- [x] Imperium - Blood Angels
- [x] Imperium - Dark Angels
- [x] Imperium - Deathwatch
- [x] Imperium - FW Death Korps of Krieg
- [x] Imperium - FW Elysians
- [x] Imperium - Inquisition
- [x] Imperium - Space Marines
- [x] Imperium - Space Wolves
- [x] Necrons
- [x] Tyranids - Genestealer Cults
- [x] Unaligned - Monsters and Gribblies
- [x] Game System entries

**Comment by Mad-Spy** [comment]
@BSData/data-authors-wh40k, please check for updates to your catalogues.

**Comment by GenWilhelm** [comment]
GSC cat was pre-fixed at release (and thankfully nobody complained).

**Comment by amis92** [comment]
@BSData/data-admins-wh40k Can someone sign-off this as done? Space Wolves aren't checked, as well as game system.

**Comment by DrTobogganMD** [comment]
Verified. Closing.
