### ISSUE TITLE
T'au Empire - Rail Rifle Cost Error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#673]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Pathfinders rail rifle cost is 22 instead 27.
Thx, regards.

**Comment by amis92** [comment]
It's called `Pathfinder w/ Rail Rifle` because it's both, so it sums up Pathfinder's 5pts and Res 22pts. All is good.
