### ISSUE TITLE
Grey Knights - Master of the Warp Updates

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6732]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** The v52 Grey Knights only seem to have Masters of the Warp associated to the HQ units. Based on the the new Rituals book, every unit should have it.

**Comment by tekton** [comment]
Everything but vehicles that aren't psykers! It's being worked on...
