### ISSUE TITLE
AM: Tank Commander should be able to take Specialist Detachment Relic 

### ISSUE THREAD

**Issue by dragongame** [BSData/wh40k#6736]
**File/Catalogue:** 
Astra Militarum

**BattleScribe version:** 2.03.09

**Platform:** iOS

**Dropbox:** No

**Description:**
Select Vigilus First Tank Company
Make Tank Commander a Field Officer
Cannot select the relic.
If I make him a warlord, than I can select the relic.
![0FB89DBD-5466-40BA-97E3-EB34E968A1DA](https://user-images.githubusercontent.com/426094/74307541-eeb38700-4d65-11ea-9014-dfe2574fe5fa.png)
![4C160A4B-2D18-4888-B5A3-0FCCCE2D3A36](https://user-images.githubusercontent.com/426094/74307549-f115e100-4d65-11ea-8851-60c6cb1bbe53.png)

**Comment by Mad-Spy** [comment]
This is correct behaviour. Field Commander allows you to take the Warlord Trait of your Specialist Detachment, not the Relic.
A model must be otherwise entitled to a Relic before it can choose to take the one from its Specialist Detachment.

**Comment by dragongame** [comment]
> This is correct behaviour. Field Commander allows you to take the Warlord Trait of your Specialist Detachment, not the Relic.
> A model must be otherwise entitled to a Relic before it can choose to take the one from its Specialist Detachment.

But a Tank Commander is a character and can therefore take a relic!

**Comment by Mad-Spy** [comment]
Characters can only take Relics if:
1. They are the Warlord.
2. There is a Warlord of the same Faction in the Army.
3. The appropriate Stratagem has been taken to allow taking an additional Relic.

If the Relic does not appear in one of these cases (which is not clear from your report), then there is a bug. Otherwise, the behaviour is correct.

**Comment by dragongame** [comment]
Sorry but I am unable to find this kind of requirements, here is the except from the AM codex:
![E0C4FF22-AC85-4769-9903-87DFDDA5F99C](https://user-images.githubusercontent.com/426094/74407944-6bf8fd80-4e33-11ea-960d-1b86c000dea4.jpeg)

**Comment by tekton** [comment]
@dragongame Do you have someone/something else selected as a warlord?

**Comment by Mad-Spy** [comment]
It was clarified in the Vigilus Defiant Update that a model must be eligible to have a Relic via one of the methods I mention above in order to be able to take the Specialist Detachment Relic. It is **not** a completely free Relic.

![image](https://user-images.githubusercontent.com/29306451/74419258-889c3200-4e41-11ea-8e38-fd86bd270960.png)

**Comment by Mad-Spy** [comment]
I've just checked and you can correctly take the Hammer of Sunderance as long as there is an ASTRA MILITARUM Warlord in the Roster, and the Tank Commander is explicitly marked as being part of the Emperor's Fist Detachment. Everything is working as it should.

**Comment by dragongame** [comment]
It is working as you describe.
However, I cannot find the reason for this!
From the latest FAQ on Vigilus:

> Q: When paying Command Points to upgrade a Detachment
> into a Specialist Detachment, is the Relic they are able to give to
> a Character in addition to the Relic they would typically get
> from their Warlord’s faction?
> 
> A: No. The Relic(s) listed within a Specialist Detachment
> can be given to a Character from your army instead of
> one from your Warlord’s codex. Don’t forget, however,
> that many codexes contain Stratagems that enable you
> to gain additional Relics.

Where does this clarification you talk about come from. A source would be awesome, as I'm unable to find this restriction anywhere. (Possible stupid me)

**Comment by dragongame** [comment]
Okay, I had forgotten to select a Warlord in the other detachment yet. Thank you!
