### ISSUE TITLE
App times out on opening roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6745]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** Yes

**Description:** Everytime I open a roster file it takes forever to load.  Then times out and gives me a Battlescribe timed out notification.  I have been a supporter for years.  I have never had such a problem with Battlescribe.  I have uninstalled and deleted the repositories then reinstalled it to no avail.  Please help

**Comment by williamcaw** [comment]
iOS 2.03.10  responsive except for known large file

**Comment by fuckingenglish** [comment]
pc win 7 2.03.10 working as intended no errors

**Comment by Jonskichov** [comment]
Fixed: https://github.com/BattleScribe/Release/issues/107

**Comment by Jonskichov** [comment]
Not really enough information to act upon.

Presumably they're trying to open a big file?
