### ISSUE TITLE
Black Templars Master of Sanctity broken

### ISSUE THREAD

**Issue by MarshalLaeroth** [BSData/wh40k#6747]
**File/Catalogue:** 
Space Marines v129
**BattleScribe version:** v2.03.18.327

**Platform:** Android

**Dropbox:** No

**Description:** Newest update broke Chaplain Master of Sanctity option to allow Black Templar chaplains to take two Litanies of the Devout.  Gives a roster error -- now reads maximum of 1 Litany of the Devout, even with Master of Sanctity selected.

**Comment by acebaur** [comment]
I'm not able to replicate this error

**Comment by Mad-Spy** [comment]
Closing as this wasn't replicable and the OP has not provided any further info.
