### ISSUE TITLE
Imperium - Blood Angels: Death Company weapon validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6748]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Death Company Marine has 1 too many selections from Weapons (maximum 1)

Should be able to select 2 weapons. Any in the unit gets a bolt piston and one of the close combat weapons, and or trade the bolt pistol for a different ranged weapon.

**Comment by darkfiire1** [comment]
Same here happened after the update
