### ISSUE TITLE
Imperium - Astra Militarum: Catalogue is missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6749]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** Yes

**Description:** Version. V2.03.17.326

The astra militarum seems to be missing.

**Comment by MrRWJP** [comment]
Have you followed the instructions here: https://github.com/BSData/wh40k/issues/6573
