### ISSUE TITLE
Imperium - Astra Militarum - Tempestus Command Squad Validation Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#675]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Imperium - Astra Militarum v28
Selecting Militarum Tempestus Command Squad more than once (so having 2 or more in one detachment) triggers the following issue: Imperium - Astra Militarum v28 has 1 too many selections of Militarum Tempestus Command Squad (maximum 1)
I have looked into Index Imperium 2 and errata/FAQ and failed to find any limitation on how many units are allowed to be fielded per detachment.

**Comment by alphalas** [comment]
You need a Tempester for each command squad
