### ISSUE TITLE
Lore Master does not allow for additional Dominus psychic power

### ISSUE THREAD

**Issue by Typhus** [BSData/wh40k#6754]
**File/Catalogue:** Imperium - Grey Knights

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** According to the new Ritual of the Damned FAQ, the Lore Master warlord trait should allow for a Grey Knights character to know an additional psychic power from either the Sanctic discipline or the Dominus discipline, but the program issues an error if the character does not know a Sanctic power.

**Comment by tekton** [comment]
This was fixed in v54 or v53 and is definitely working in v55. Before the FAQ it required a Sanctic power, after the FAQ is doesn't!
