### ISSUE TITLE
Imperium - Space Marines: White Scars validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6756]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** 1) The Tempered by Wisdom White Scars stratagem does not work on the Khan on Bike HQ selection.
2) The White Scars Chapter specific litany from Psychic Awakening is not included in the list of litanies a Chaplain can select from.
3) A non-biker warlord can select the Master Rider Warlord Trait.

**Comment by acebaur** [comment]
#2 is not going to be fixed at this time. All Chapter specific litanies are just known to their respective chaplains. It will unecessarily bloat a very large cat.
