### ISSUE TITLE
Tau HQ Warlord has no option for Signature System (aka relic)

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6760]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Relic options missing from T'au. I attempted to give a HQ Warlord a Signiture System, but there was no option to do this.

**Comment by amis92** [comment]
You're either attempting to give SigSys to a named character, or you haven't *actually* selected your Warlord yet, or you did but he wasn't Tau.

I've confirmed all Commanders, Cadre Fireblade and Ethereal can take SigSystem once a Tau Warlord is selected.
