### ISSUE TITLE
Tau - Commander Shadowsun's pulse pistol has incorrect points cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6762]
**File/Catalogue:** Tau Empire v54

**BattleScribe version:** 2.03.18.327

**Platform:** Android

**Dropbox:** No

**Description:** Commander Shadowsun's pulse pistol currently costs 1 point, but should be 0, as all her wargear options (including drones) are included in her base price.

**Comment by amis92** [comment]
Damn!
