### ISSUE TITLE
Psychic Awakening: Saga of the Beast

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#6764]
Cover issue for implementation of Saga of the Beast

**Comment by PhilKaBoom** [comment]
Does Someone Work on the space wolves stuff of the publication and boxed set?

**Comment by amis92** [comment]
@tag8833 can you update Wiki/Publications table with specific release date? :)

**Comment by tag8833** [comment]
@amis92 Done.  Not sure if I should mark it as "In Use"  Because the Ork part is published but we are still waiting on space wolves.

**Comment by amis92** [comment]
You should indeed. The table describes publications as they are released, not how we implement them. 😊

**Comment by CrusherJoe** [comment]
Completed in release v1.4.16, just pushed.
