### ISSUE TITLE
Imperium - Adeptus Custodes: FW units need points updates

### ISSUE THREAD

**Issue by LaLongueCarabine** [BSData/wh40k#6767]
**File/Catalogue:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** no

**Description:** Adeptus Custodes FW units still not showing correct points values referenced in CA19 FAQ.

**Comment by GenWilhelm** [comment]
It all looks correct as far as I can see. What version of the file are you looking at?

**Comment by LaLongueCarabine** [comment]
1.4.8. I've deleted my data files and redownloaded 3 times and the points value of the caladius (and weapons) and the Aquilon terminators are off as far as I can see.

**Comment by LaLongueCarabine** [comment]
Correction CA19 FAQ. Not CA19

**Comment by GenWilhelm** [comment]
Aha! I had completely forgotten about those errata.

**Comment by fuckingenglish** [comment]
look at #6726
