### ISSUE TITLE
Imperium - Blood Angels: Death Company weapon validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6768]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** blood angels death company marines can’t take a bolt gun and chainsword as a valid loudout. uncheck the bolt pistol and chain sword option, select chain sword as melee weapon and bolt gun for ranged/melee weapon. Should see an error now

**Comment by farhanrahman** [comment]
Thanks for raising this issue. Just to add a bit more information, the link http://wahapedia.ru/wh40k8ed/factions/blood-angels/Death-Company further mentions that a bolt pistol can be replaced for boltgun, hand flamer, inferno pistol... and chainsword can be replaced for power axe, power fist and so on. In battlescribe any combination of using two of ranged and melee weapons other than the checkbox option “bolt pistol and chainsword” creates this error. In fact the death company manual from the packaging suggests configurations which can create this error.

**Comment by Mad-Spy** [comment]
Unable to replicate in Blood Angels v135.

Also, wahapedia is not an official source. The Codex and any related publications from GW are the official source.

**Comment by alphalas** [comment]
Since that part of the data has not changed since before the BattleScribe app bug happened, I’m going to go with update your app update your data.

**Comment by farhanrahman** [comment]
I have version 1.4.5 (released 17 feb 2020). I hope thats the right repo but with that version I can reproduce this error. Can you try it on your end and reopen this issue?

**Comment by Mad-Spy** [comment]
@farhanrahman, please update your data. The latest release of the data is v1.4.8 and the issue does not manifest in that version.

**Comment by farhanrahman** [comment]
![dc_loadout](https://user-images.githubusercontent.com/799243/74931250-1f836400-53d7-11ea-9ea7-efd8bd659e47.jpeg)
![error](https://user-images.githubusercontent.com/799243/74931257-2316eb00-53d7-11ea-8724-7e52d17fc843.jpeg)
![repo_version](https://user-images.githubusercontent.com/799243/74931258-23af8180-53d7-11ea-86b4-6c437d42779e.jpeg)

So I am using v1.4.8 with latest BattleScribe release (2.03.10). I have attached screen shots where I can reproduce this. I will try creating a new roster and see if the problem persists. Thanks @Mad-Spy
