### ISSUE TITLE
T'au - quality check

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#677]
Tasks:
* [x] It seems there are some incorrectly classified (model/unit/upgrade) entries all across catalogue. It should be fixed at some point.
* [ ] There are many abilities done as rules. They should probably be redone as profiles so as to align with most other catalogues (and enhance View UX).

**Comment by alphalas** [comment]
Piranha can be reduced to the single customizable selection(that is already in the entry) instead of having all the permutations of wargear options spelled out.

**Comment by xxkenaixx** [comment]
It seems that Markerlight Drones don't pay for the markerlight itself from what I can see. This might be the case on other units aswell that come with it as standard.

**Comment by amis92** [comment]
@xxkenaixx Drones specifically do not pay for any wargear as per header in Point Cost table. Other units do pay.
