### ISSUE TITLE
Imperium - Inquisition: Inquisition Stratagems should be available in non-Inq Detachments which have an Inquisitor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6771]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When adding an inquisition from non-Force org it doesn’t populate the pre-game inquisition strat for a warlord trait. (Love the new format, fyi)

**Comment by Mad-Spy** [comment]
You are not allowed to use a Faction's Stratagems unless you have a Detachment of that Faction, so you cannot give such an Inquisitor a Warlord Trait.

**Comment by tekton** [comment]
To be that guy: "If your army is Battle-forged and includes any INQUISITOR units, you have access to the Stratagems shown here, and can spend Command Points to activate them."

Inquisition is special and their strats are just tied to being in the army.

FWIW it used to work before things got moved, and the move was good :)

**Comment by Mad-Spy** [comment]
If we're talking about "Inquisitorial Mandate" (which I think we are?), it's an option on the model itself, not a "Stratagem" entry.
It appears to be working correctly as far as I can tell.
