### ISSUE TITLE
Imperium - Blood Angels: Phobos WLTs missing for Phobos Lieutenant

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6772]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Missing phobos warlord traits for "Lieutenants in Phobos Armour" when is selected as Warlord

**Comment by Mad-Spy** [comment]
Hide modifier is using Parent instead of Ancestor, so it doesn't trigger because the Lt _unit_ has the keywords, not the Lt itself.
