### ISSUE TITLE
Imperium - Blood Angels: Death Company weapon validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6780]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Death Company. When unchecking Weapons box for bolt pistol and chainsword, and selecting a Melee weapon and a Ranged/Melee weapon. Error:  Death Company Marine has 1 too many selections from Weapons (maximum 1).  Example: unchecking the Bolt pistol and chainsword and selecting a Power Axe and Hand flamer.

**Comment by Mad-Spy** [comment]
The Thunder Hammer condition is using a link ID when it should be using the SSE id.

**Comment by alphalas** [comment]
duplicate #6748
