### ISSUE TITLE
Imperium - Inquisition: Unable to add stats for Eisenhorn's Daemonhost in non-Inq Detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6782]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Imperium when taking  Eisenhorn he gets to take a Daemonhost there is a problem and that he does not have point or a data reference when being taken as a no force org

**Comment by williamcaw** [comment]
This would bring up the model to 120 points as it would be  as part of reinforcement cost.
