### ISSUE TITLE
Tyranids - Air wing

### ISSUE THREAD

**Issue by hatchetboy** [BSData/wh40k#679]
The Tyranid Air Wing doesn't seem to have the option to add Flyers.  This gives validation errors which cannot be resolved (and also means that you can't add Tyranid Flyers!)

**Comment by amis92** [comment]
@hatchetboy what Flyers do you refer to? Tyranids have no flyers.

**Comment by hatchetboy** [comment]
Yeah, those ones.  User is idiot.... :)
