### ISSUE TITLE
[Tau] Promising Pupil and Named Characters

### ISSUE THREAD

**Issue by srjek** [BSData/wh40k#6795]
**File/Catalogue:** T'au Empire.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No?

**Description:** The Promising Pupil Stratagem in Battlescribe does not appear to interact with most Named HQ units, particularly those where the rules specify they must take a specific warlord trait. If I'm reading the stratagem correctly they *should* apply.

The crux of the issue appears to be the named characters don't use the shared "Warlord Traits" selection group. However I don't see any way to say "Only this trait from the linked group can be selected", but instead seem to have to add constraints to every link in the selection group that scan their ancestors for the Named Character Tag/Category and hide their respective link. I've done this for 2 of the named characters locally, I can finish it for the rest of the named characters and do a pull request, but I don't know if there's a better way.

**Comment by Mad-Spy** [comment]
I suggest that you join the Discord server and speak to the T'au data author before attempting this kind of significant work.

**Comment by amis92** [comment]
I'm not going to argue either way - I've made the call to not allow them.

My reasoning is that the restriction on Named chars traits requires them to be a warlord so with the stratagem it wouldn't apply; allowing you to give Named chars any trait you want; and I feel strongly that it's very much not intended. You can call it an Assumed Amendment on my part.

Until FAQ drops I'm not changing my mind. After that we can go back to it. :)



----

PS
>  I don't see any way to say "Only this trait from the linked group can be selected"

Technically the most viable solution to require an item be selected for a particular parent is to make a modifier that sets "min 1 in parent" when ancestor is the unit which is restricted to that trait.

**Comment by Mad-Spy** [comment]
You can't give them _any_ Trait, but you can give them their specific Trait. That's how the similar Stratagems have been implemented for other catalogues.

**Comment by srjek** [comment]
> The T'au named characters have unit-specific Warlord Trait selection groups, so doing this would probably just involve making those groups visible when Promising Pupil is selected.

Another issue with the characters having their own selection groups is that they're not a part of the limits on the number of warlord traits across the roster (1 for the Warlord, +1 for each instance of Promising Pupil). But perhaps that could be solved with a "Promising Pupil" checkbox similar to the "Warlord" checkbox that already exists on HQ units. (Why didn't I think of this *last* night?)

> Technically the most viable solution to require an item be selected for a particular parent is to make a modifier that sets "min 1 in parent" when ancestor is the unit which is restricted to that trait.

That doesn't work in this particular case since the Warlord Trait selection is on all units when the Promising Pupil Stratagem is present (so you're nudged by the validation errors into using the extra trait on the named characters), but it sounds handy in general, I'll keep it in mind

> ...implemented for other catalogues. Currently, you can't even do that.

As a workaround to hold off until a FAQ, one can mark the unit as a warlord, select the trait, then unmark warlord. Battlescribe will complain about validation errors, but the trait selection will remain and is printed in the resulting roster.

**Comment by amis92** [comment]
Sadly the FAQ (#6884) did not touch the subject.

I think since Traits in general need a fix to correctly validate the limits, I'll allow usage of the Promising Pupil on named characters mostly because [Guideline 0](https://github.com/BSData/wh40k/wiki/Guidelines#0) - it's a *possibly* valid choice.
