### ISSUE TITLE
Adepta Sororitas - Celestine and Geminae Superia

### ISSUE THREAD

**Issue by gitGremlin** [BSData/wh40k#6798]
Currently, BScribe description for these two units reports that:

- Celestine can give a +1 invulnerable save to ADEPTA SORORITAS UNITS (when she actually can only give it to INFANTRY)
- Geminae Superia are not allowed Warlord Traits (they also can't take Relics)

**Comment by alphalas** [comment]
Celestine is fixed in next release, geminae already could neither take WLT or relics.
