### ISSUE TITLE
Imperium - Blood Angels: Death Company Weapon Totals

### ISSUE THREAD

**Issue by HannibalSelecta** [BSData/wh40k#6799]
**File/Catalogue:** Imperium - Blood Angels v135

**BattleScribe version:** 2.03.12

**Platform:** Windows/Android

**Dropbox:** Yes

**Description:** When choosing Death Company weapons it's currently only allowing 1 weapon total when you uncheck Bolt Pistol & Chainsword. You should be able to choose one from Melee and one from Ranged/Melee.

**Comment by alphalas** [comment]
Fixed in the next release
