### ISSUE TITLE
Orks: Error in Aux. Support Detachment

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6807]
**File:** Orks.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Relatively small issue, for the Auxilary support detachment you have to pick a Clan Kulture but if you do so this counts towards the limit of 'units' you can have so when you add in the unit you are wanting to use it pops up with the validation error as there are now two "units" in the detachment. 
For example: I'm wanting to use Ghazghull Thraka in a game and don't have a spare unit of troops to create a Patrol detachment for him so want to use the Auxilary Support detachment. To do so Clan Kultur obviously must be 'Goffs' to even be able to select him. I don't think there is currently a way to do it without having the validation error for either too many "units" or for not having the "Clan Kultur" irrespective of which other unit you add.

**Comment by Mad-Spy** [comment]
This issue is fixed in the latest release (v1.4.9). Please update your data.
