### ISSUE TITLE
Tyranids: Dimachaeron weapon text error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6808]
**File:** Tyranids.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Dimachaeron grasping talons and thorax spine-maw should be each "wound" (not hit) roll of 6+.

Thanks!

**Comment by GenWilhelm** [comment]
It was changed in the errata:

![image](https://user-images.githubusercontent.com/22036809/75434936-35020c00-594a-11ea-9a4c-6721bce1667d.png)
https://www.warhammer-community.com/wp-content/uploads/2019/09/imperial_armour_index_xenos-1.pdf
