### ISSUE TITLE
Imperium - Space Marines: Techmarine Wargear?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6827]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Techmarine isn't updated. The Techmarine has other options in the codex, for example you can't choose conversion beamer anymore, that's from the old index and is Legend nowadays. See latest Space Marine codex for correct wargear options and points.

**Comment by acebaur** [comment]
The Techmarine is correct. The conversion beamer is a Legends option which is Matched Play legal, therefore it is included.
