### ISSUE TITLE
Chaos - Death Guard: CA points not updated?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6831]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** The point list has not been updated for the latest chapter approved.
They are still the point values outlined in the official codex, which have been reduced in the latest (December 2019) chapter approved book. This renders battlescribe utterly useless for any death guard player, unless the list gets printed out and the point values manually changed with a pen.

**Comment by Mad-Spy** [comment]
Please can you provide specific examples of the issues, as changes to the points costs were made at the time of release.

**Comment by Mad-Spy** [comment]
Closing as there has been no update from the OP.
