### ISSUE TITLE
deathwatch intercessor sergeant bolt rifle cost

### ISSUE THREAD

**Issue by Darkdefiler** [BSData/wh40k#6834]
**File/Catalogue:** 

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** 

**Description:** Just updated data files, deathwatch intercessor sergeant bolt rifle cost is set to 1 point, think this is incorrect?
<img width="1261" alt="error" src="https://user-images.githubusercontent.com/40923281/75760909-04e2b080-5d30-11ea-88dc-e5053a5c672b.png">

**Comment by Mad-Spy** [comment]
Already fixed in #6504, will be in the next release.
