### ISSUE TITLE
Imperium - Deathwatch: Vanguard Sergeant weapon validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6835]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Deathwatch vanguard sergeant wargear options not allowing him to take more than one item example saying cannot have both pistol and a power sword.

**Comment by Mad-Spy** [comment]
Modifiers are using link IDs so they don't trigger.
