### ISSUE TITLE
Astropath points too high

### ISSUE THREAD

**Issue by info2345** [BSData/wh40k#6837]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Astropath points are listed at 26 rather than 15 with laspistol. This is incorrect.

**Comment by Mad-Spy** [comment]
Please ensure you have the latest version of the data. The cost is showing correctly in Astra Militarum v258.

**Comment by info2345** [comment]
ok, it appears that my data refuses to update
