### ISSUE TITLE
Imperium - Space Wolves: Blood Claw max unit size is being calculated incorrectly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6839]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Hey, so I am trying to add my squad of 15 blood claws and when I sub a plasma pistol or special weapon in for a standard blood claws it says my unit size it too big although the total unit size is still 15. So with the 2 weapon selection ( plasma pistol and flamer) it says my Max squad should be 13. I think this is wrong. Appreciate you!

**Comment by Mad-Spy** [comment]
The total unit size is being decremented, rather than the number of standard Blood Claws.

Also, I noticed that the WGPL is being included in the count of models for the unit. I think they should be extra on top, as with all other units that can take one.
