### ISSUE TITLE
Aeldari - Craftworlds: Star Glaive should not be mandatory for Legends Autarch

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6840]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Star glaive should not be a required purchase for a Legends Autarch. In fact, a Legends Autarch probably shouldn't be able to take a star glaive at all.

>This model can be equipped with one of the following instead of 1 star glaive: 1 fusion pistol; 1 shuriken pistol. If it is, it has the
following additional wargear options:

**Comment by FarseerVeraenthis** [comment]
Wasn't this already fixed...?

**Comment by GenWilhelm** [comment]
I opened #6828, then closed it after some discussion on Discord. No idea if anything has changed since then.

**Comment by Mad-Spy** [comment]
This is definitely fixed in the current release version. Closing.
