### ISSUE TITLE
Imperium - Dark Angels: Typo in Infiltrator Comms Array text

### ISSUE THREAD

**Issue by Detmud** [BSData/wh40k#6850]
friendlyDARK ANGELS (Space missing)

https://github.com/BSData/wh40k/commit/50ca1243764bcbafa4fa9a74f12ba203339d3442#commitcomment-37678152

Sorry to be a pain in the ass

**Comment by Mad-Spy** [comment]
@Detmud, quoting line numbers in a commit is not necessarily helpful as that is not how files are edited. It's better to let us know what entry is wrong.

**Comment by Detmud** [comment]
> @Detmud, quoting line numbers in a commit is not necessarily helpful as that is not how files are edited. It's better to let us know what entry is wrong.

Ohh sorry I thought those are just yaml or some kind of XML files you edit by hand.

Sorry about that will keep that in mind for the next time.
Thank you for your hard work I appreciate it.

**Comment by Mad-Spy** [comment]
Oh god, no. That would be a nightmare! If you download the PC version, you get the Data Editor in the package. You can open up the data files yourself and see how the editor parses the XML into the UI.

**Comment by Detmud** [comment]
Ahh thanks will have a look into that later at home.
