### ISSUE TITLE
Cannot pick Warlord Traits for Typhus

### ISSUE THREAD

**Issue by MechMK1** [BSData/wh40k#6853]
**File/Catalogue:** Chaos - Death Guard

**BattleScribe version:** 2.03.12

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Typhus is missing a link to the warlord traits. When selecting Typhus as Warlord, he cannot be assigned any Traits or Relics.

**Comment by Mad-Spy** [comment]
He is a Named Character and thus has a fixed Warlord Trait (which appears on the output when he is your Warlord) and may not be assigned Relics, as per the rules.

**Comment by MechMK1** [comment]
@Mad-Spy Thanks for the response. I was only looking at Typhus datasheet, not at p.97 with the warlord traits.
