### ISSUE TITLE
Imperium - Space Marines : Techmarine should have servo-harness in addition to servo-arm

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k#6854]
**File/Catalogue:** Imperium - Space Marines v133

**BattleScribe version:** 2.03.18

**Platform:** Android

Just spotted that Techmarine entry has a choice of servo-arm vs servo-harness, while according to codex, techmarine just can take the harness without removing anything. This means that it will have two servo-arms.

Minor thing thing though as initial servo-arm is free (so point values are ok), but it gives additional attack in melee no visible in unit spreadsheet

**Comment by Mad-Spy** [comment]
If you select a servo-harness, the Techmarine correctly has 2 servo-arms.

![image](https://user-images.githubusercontent.com/29306451/76423878-54b02000-639f-11ea-90b1-c0a5e0d174de.png)

However, on mobile, the default output option is "minimal" which suppresses the display of this option. Changing your output settings to "Full" and the 2 x servo-arm selection will be displayed.
