### ISSUE TITLE
Imperium - Space Wolves: Could Shock Assault and Bolter Discipline be linked to the relevant models?

### ISSUE THREAD

**Issue by Skirrrbyseadog** [BSData/wh40k#6861]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/Android

**Dropbox:** 

**Description:** Shock Assault and Bolter Discipline are missing from the relevant unit entries for Space Wolves.

**Comment by Mad-Spy** [comment]
This is because they are added as Force Rules, rather than being linked to each individual unit.

**Comment by Skirrrbyseadog** [comment]
Thank you, I see it now.

**Comment by alphalas** [comment]
it'll be in the next release
