### ISSUE TITLE
Imperium - Dark Angels: Some Relics missing?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6864]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Dark angels character by the new book of PA “Can” take new relics instead of those from the codex. Data source allow only relics from new book, but should be allowing to take all from codex (e.g. Shroud of Heroes, Eye of the Unseen.)
Thank you in advance.

**Comment by Mad-Spy** [comment]
Not sure what you mean? The Relics you mention _are_ available for eligible models in the current release, alongside the new ones from Ritual of the Damned.
