### ISSUE TITLE
BattleScribe v2.03.12.141

### ISSUE THREAD

**Issue by Bushelyard** [BSData/wh40k#6865]
**File/Catalogue:** Imperium - Death Korps of Krieg v124

**BattleScribe version:** 2.03.12.141

**Platform:** Windows
**Dropbox:** No

**Description:** Point value of Leman Russ Mars-Alpha Battle tanks is wrong. they are priced at 132 with thier basic wargear, it should be 132 without wargear. 132pts for the tank and 22pts for a battle cannon = 154. The problem is with all of the different battletanks of Mars-Alpha Battle Tanks.

**Comment by alphalas** [comment]
Perhaps you should consult chapter approved 2019
![0E2A2AAF-00F8-42A6-B71C-4F602D1C7720](https://user-images.githubusercontent.com/15703066/76242281-d3288880-620c-11ea-8227-159b2b4e8d90.png)

**Comment by Bushelyard** [comment]
Oh, thank you very much, my bad! XD
