### ISSUE TITLE
Imperium - Space Wolves: Incorrect text for "Target Priority" WLT

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6866]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hello,
I think the warlord trait "target priority" from phobos wolf lord (captain) has to be changed: it is only useable now for phobos units. Since new space marine codex, I think. 
Best wishes florian

**Comment by Mad-Spy** [comment]
The Space Marine Codex does not apply to Space Wolves. As such, the current publication they reference for these is the Vanguard PDF.

I expect they'll get an update when Saga of the Beast comes out as happened with Dark Angels and Blood Angels.
