### ISSUE TITLE
Imperium - Inquisition: NFO Inquisitors should be max 1 per roster

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#6869]
**File/Catalogue:** Imperium - Inquisition

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** Yes

**Description:** Title.

**Comment by williamcaw** [comment]
Imperium Cat’s . in  no force org .not multiple selections of inquisitors. Once a inquisitor is selected the rest are hidden.

**Comment by Mad-Spy** [comment]
Rules were changed in War of the Spider, so this is no longer valid.
