### ISSUE TITLE
Imperium - Space Wolves: Land Speeder cost updated in CA2019 Errata

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6876]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** V110 for wolves still indicates that a Land Speeder is 70pts (without wargear). The Errata to CA19 has changed this to 45 pts in line with other codex.

**Comment by CrusherJoe** [comment]
Fixed in latest update.
