### ISSUE TITLE
Death Korps of Krieg: Kommissar Cost

### ISSUE THREAD

**Issue by Waldmenschen** [BSData/wh40k#6877]
**File/Catalogue:** FW Death Korps of Krieg v124

**BattleScribe version:** 2.03.18.327

**Platform:** Android

**Dropbox:** No

**Description:**
I'm Not entirely Sure to be honest, but the commissar costs 30 pts, in Astra militarum it's only 16 pts what i believe it should be for Death Korps as well

**Comment by Mad-Spy** [comment]
30pts is correct as per Chapter Approved 2019.
