### ISSUE TITLE
Imperium - Space Marines: Lt in Phobos Armour PL cost should be 4

### ISSUE THREAD

**Issue by 40kNoob** [BSData/wh40k#6878]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
Which catalogue is this in?

**Comment by 40kNoob** [comment]
Warhammer 40000 8th edition v1.07

**Comment by Mad-Spy** [comment]
That's the data set. There are 4 catalogues which contain Lts in Phobos Armour: Space Marines, Dark Angels, Blood Angels and Space Wolves.

Which one has the problem?

**Comment by 40kNoob** [comment]
Sorry, new to this but I’ve been using the Space Marines one.
