### ISSUE TITLE
Codex Supplement: Iron Hands Update 1.1

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6880]
Published 2020-02-27

WHC link: https://www.warhammer-community.com/wp-content/uploads/2019/10/22137816.pdf
CC [22137816.pdf](https://github.com/BSData/wh40k/files/4323459/22137816.pdf)

Cogitated Martyrdom stratagem rewritten.

**Comment by acebaur** [comment]
In game Strat, not in BS
