### ISSUE TITLE
Psychic Awakening: The Greater Good Update 1.0

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6884]
Published 2020-03-11

WHC link: https://www.warhammer-community.com/wp-content/uploads/2020/03/588e817f.pdf
CC [588e817f.pdf](https://github.com/BSData/wh40k/files/4323504/588e817f.pdf)

**Comment by amis92** [comment]
Tau part done.

**Comment by GenWilhelm** [comment]
No changes to GSC.
