### ISSUE TITLE
Imperium - Blood Angels: Missing options for Hero of the Chapter and Death Company

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6885]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Option to give other character than warlard, warlord trait is unavailable(no Hero of the Chapter stratagem).
No other options for Death Company unit aside from bolt pistol&chainsword and thunder hammer. There should be option to replace its bolt pistol with a boltgun, hand flamer, inferno pistol, plasma pistol, power axe, power fist, power maul or power sword. There should be option to replace its chainsword with a power axe, power fist, power maul or power sword.

**Comment by Mad-Spy** [comment]
1. You need to have a Warlord in order to use Hero of the Chapter, at which point it will appear on relevant models.
2. You must un-check the bolt pistol & chainsword option (as they both need to be swapped) in order to make the additional options appear.
