### ISSUE TITLE
Chaos - Death Guard: Cultist Attacks with Brutal Assault Weapons

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#6892]
**File/Catalogue:** Chaos - Death Guard v76

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** Yes

**Description:** When a cultist and cultist champion in the same unit are both equipped with brutal assault weapons, the profile of the brutal assault weapon no longer states that the extra attack has already been included in the models' profiles.

**Comment by Mad-Spy** [comment]
Fixed by removing the extra attack on Cultists so their profile is consistent with the Codex. The model itself does not actually get an extra attack.
