### ISSUE TITLE
Imperium - Space Wolves: Blizzard Shield options do not include a default Blizzard Shield

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#6899]
The options which include a Blizzard Shield on a Wulfen Dreadnought do not have a min1/max1 constraint on the shield sub-option, so they are effectively 15pts cheaper than they should be.

Additionally, there is no min 1/max 1 on the Loadouts SEG, so you can include a Dread with no weapons without getting a validation error.

**Comment by CrusherJoe** [comment]
Good catch, thank you! Fixed in latest udpate.
