### ISSUE TITLE
Imperium - Deathwatch: Validation error when selecting Cyclone and Storm bolter

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6900]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Deathwatch Terminators error. When choosing Terminator w/ Heavy weapon, choosing cyclone missile launcher and storm bolter, it says too many selections from storm bolter (maximum 0)

**Comment by Mad-Spy** [comment]
The storm bolter in "Cyclone ML and Storm bolter" is modified to min0/max0 but with no condition, so it's never valid. Maybe it was mis-configured when doing #6399?
