### ISSUE TITLE
Imperium - Space Wolves: Thunderwolf unit missing twin Lightning Claws option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6905]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** When making a squad of Thunderwolf Calvary there is no option to give models a pair of wolf claws for 11 points only the option to give them 2 individual wolf claws for 7 points each but all other models with access to the Space Wolf Melee Weapons list have the option to take a pair of wolf claws

**Comment by CrusherJoe** [comment]
Should be fixed in latest update.
