### ISSUE TITLE
Genestealer Cult Incorrect costs 

### ISSUE THREAD

**Issue by Caecusscius** [BSData/wh40k#6913]
It lists the cost at 10 points for demo charges on Atalan Jackal Bikers- and I believe it should be 5.   

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
Cost was increased in CA2019
