### ISSUE TITLE
Imperium - Dark Angels: Chapter Selection is incorrectly limited to Max 1 in Roster

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6915]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.18

**Platform:** Android

**Dropbox:** No

**Description:** Anytime I make a chapter I get error saying too many chapter selected. No matter if i make 2 or 3 detachments....same error. Example....dark angels list using 3 detachment. Error right away....

**Comment by williamcaw** [comment]
It’s just to big

**Comment by Mad-Spy** [comment]
I think the problem here is that the "Chapter Selection" Configuration option is being limited to Max 1 in Roster (rather than Force) in DA?
