### ISSUE TITLE
Imperium - Space Wolves: Assault Plasma Incinerators should be 15pts each

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6916]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** the data entry for Hellbalsters, specifically in the space wolves section, the point cost for assault plasma incenerators is 97, when in reality it is actually 80.

would appreciate if you could change that, 

Cheers!

**Comment by Mad-Spy** [comment]
Cost is incrementing incorrectly by 16pts per model and also has a base cost of 17pts, causing it to calculate incorrectly.

**Comment by CrusherJoe** [comment]
Fixed in massive SW update coming today.
