### ISSUE TITLE
Imperium - Astra Militarum: Tank Aces should be available by 2 different methods

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6921]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.13

**Platform:** Windows

**Dropbox:** No

**Description:** Astra Militarum Tank Aces currently limited to only being selected from the Tank Ace stratagem, whilst rules allow to nominate a Tank Ace by not picking a Warlord Trait and allows for a maximum of 2. Current AM data doesn't allow for this to happen, preventing either taking a Tank Ace without the stratagem and no WT at all, or a second with the stratagem.

Suggestion is to include an option under the Warlord's Traits to nominate a Tank Ace instead and thus increase the available Tank Ace cap by +1.

**Comment by alphalas** [comment]
I hate checkboxes. fixed in next release
