### ISSUE TITLE
Death Guard Relics of Decay Missing Relic of decay option

### ISSUE THREAD

**Issue by jedoh5** [BSData/wh40k#6924]
**File/Catalogue:** Death Guard v79

**BattleScribe version:** 2.03.12

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Death Guard Relics of Decay not showing in full. Missing Relic of decay option _Plaguebringer_ on HQ Chaos Lord with Jump Pack [Legends]

**Comment by Mad-Spy** [comment]
Works fine if you give him a power sword as required.
