### ISSUE TITLE
Warhammer 40,000 8th Edition: Progeny of the Hive should be able to be taken multiple times

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6933]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Progeny of the Hive seems broken. I should be allowed to apply this more than once but it's not letting me. I am going by the rules in the Tyranid codex and the additional Psychic Awakening 3 - Blood of Baal.
I have tried updating my platform and this is still showing the error

**Comment by Mad-Spy** [comment]
It should work the same as Tank Aces does for AM.

**Comment by GenWilhelm** [comment]
Progeny of the Hive can only be used once per battle.
