### ISSUE TITLE
Imperium - FW Adeptus Astartes: Ivanus Enkomi should have access to Master of Sanctity Traits

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6937]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** Chaplain Ivanus Enkomi should have access to Master of Sanctity warlord traits when selected as warlord or with Hero of the Chapter

**Comment by WindstormSCR** [comment]
FW lib entry, but needs to be fixed by linking the appropriate stuff to the root link in the SM catalog(s)
