### ISSUE TITLE
Can not choose relics from Greater Good for Militarum Tempestus 

### ISSUE THREAD

**Issue by Dala86** [BSData/wh40k#6938]
When choosing a relic for Tempestor Prime in a Militarum Tempestus Detachment the new relics from Greater Good are not an option.

For older rosters where these relics are chosen Battlescribe shows an error and says these relics are not valid as choices and that they are hidden.

**Comment by alphalas** [comment]
Do you have the correct regiment selected for them? They are all regiment locked same as the normal guard regiment specific relics

**Comment by Dala86** [comment]
Hello, I had Psian Jakals chosen as a Regiment when I noticed the problem.
I could not choose "The Hounds Teeth" which is their specific relic.
When I switched to Kappic Eagles I could not choose their "Distraction
Charges" relic either.


Den tis 31 mars 2020 17:51Jon Kissinger <notifications@github.com> skrev:

**Comment by alphalas** [comment]
![4C4DF485-BDD5-4D0F-A748-3CF2A222BD6E](https://user-images.githubusercontent.com/15703066/78049636-496e6580-7349-11ea-9b83-823d8d5f50b0.png)
![270C3A55-E41B-4C6B-A3BB-982D6E9979BE](https://user-images.githubusercontent.com/15703066/78049648-4a9f9280-7349-11ea-8c1f-9093591d59d9.png)
Delete and re-download your data – I cannot verify the issue on my side on mobile.

**Comment by Dala86** [comment]
Thanks for the help! :)

Den tis 31 mars 2020 18:16Jon Kissinger <notifications@github.com> skrev:
