### ISSUE TITLE
Tank Aces not validating correctly

### ISSUE THREAD

**Issue by Gingrel** [BSData/wh40k#6945]
**File/Catalogue:** Imperium - Astra Militarum

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** Yes

**Description:** I'm getting a validation error when taking a Tank Ace ability instead of a Warlord Trait. I should be able to do this without using the Tank Ace stratagem.

**Comment by alphalas** [comment]
It's an App Bug, hopefully the next release fixes it.
