### ISSUE TITLE
Warhammer 40,000 8th Edition: Is it possible to add content from the CA19 Spearhead game type?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6947]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** No way to use the Spearhead game type, stratagems or detachment variations from Chapter Approved 2019.

**Comment by williamcaw** [comment]
What was the faction that you were using?

**Comment by DrTobogganMD** [comment]
As we are moving to 9th Ed. This Game Type will no longer be used.
