### ISSUE TITLE
Commissar and Lord Commissar

### ISSUE THREAD

**Issue by JustTeddyPls** [BSData/wh40k#6948]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:**

Commissars and Lord Commissars have the option to ”Display Astra Militarum Orders” as well as having the profile: ”Voice of Command”. The units lack the profile in the codex. 
Detachment used; Battallion - Astra Militarum v.263.

![33FC1476-C84E-46A1-9B81-E6BCE0B418D0](https://user-images.githubusercontent.com/63097298/78343948-e6c0d800-759b-11ea-909f-bcaed49f3a2e.png)
![D97D88A3-8B7F-4BEB-A8AE-C7F7B80B102D](https://user-images.githubusercontent.com/63097298/78343955-ea545f00-759b-11ea-98f6-8d1fcb7b53b1.png)

**Comment by Mad-Spy** [comment]
There is a Warlord Trait which allows them to give orders which is why they have it, however, the logic which should be hiding it except when they have that Trait is playing up.

I believe it will be fixed in the next version.
