### ISSUE TITLE
Cartag is editing users posts

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#695]
He needs to be fired.

**Comment by Thairne** [comment]
So, let me get this straight.
You come in here with a sense of entitlement and rude language, blame one of the longest and most active contributors that work to get you your free data updates in their spare time without proof and context and demand him to be fired?

**Comment by BaconCatBug** [comment]
Hey King Heresy, I get email notifications, deleting your post after the fact does nothing.

I don't care who Cartag is, it's unacceptable for them to edit other users posts because they are too immature to accept criticism.

**Comment by amis92** [comment]
@BaconCatBug

Hello,

it is very thoughtful of you to bring this fact to our attention. There has indeed been misbehavior on our part. We as a group are deeply committed to upholding our [Membership Guidelines](https://github.com/BSData/bsdata/wiki/Membership-Guidelines); anyone who does not follow them is held responsible by means deemed appropriate by me and other maintainers.

In this particular case, without going into details, you did manage to step on some members' toes *heavily* and it seems it might've snapped them. The action they took as a result has been inappropriate.

Everyone in the team can edit comments, FYI. This helps when fixing some vague reports or formatting gone wrong.

As to your suggestion of what action to take, it's finally up to me to decide. You *demanding* anything just proves I shouldn't follow that. You might get angry, we might get angry, but namecalling or demanding *specific* action be taken is just as not acceptable as the source of this saga.

I hope we can leave this behind us and continue on a more friendly note, or at the very least a neutral one. ✨ 💖 💬 👍 

*Live long and prosper* and *May the Force be with you* - choose favorite.

PS.  As much as I want us to continue working together, follow ons of this case presented in tone and form similar to the one in this isse *will* result in us burning bridges with you 🔥 Polite and not emotionally charged discussion is welcome. 🥂

**Comment by BaconCatBug** [comment]
It's fine. I've already reported you to GW legal. Let's hope they C&D you like the rest.

**Comment by amis92** [comment]
It feels like you've decided to pursue some kind of revenge. That is very sad.

Also GW is fully aware of us. You might've saved yourself the effort, but hopefully it'll at least make you feel better.
