### ISSUE TITLE
Duplicating units

### ISSUE THREAD

**Issue by WikkedTiki** [BSData/wh40k#6950]
**File/Catalogue:** 40k Necrons v61

**BattleScribe version:** 2.03.15.148

**Platform:** Windows

**Dropbox:** No

**Description:** Created a unit of 9 Tomblades with nebulascopes and shieldvanes. Clicked to duplicate the first bike, nothing happened. Manually entered the next 8 tomb blades for the unit. Duplicated the whole unit and it made 2 extra copies for the points cost of one. Tried it again, a single dupliacte created 2 extras for the price of one. 
![image](https://user-images.githubusercontent.com/29361456/78384551-99db0280-7597-11ea-8cbe-36f821055289.png)

**Comment by DrTobogganMD** [comment]
This is going to be an issue for battlescribe beta, not the data. Please re-raise the issue on the battlescribe repo. https://github.com/BattleScribe/Pre-Release/issues
