### ISSUE TITLE
Orks - The Kustom Job stratagem can only be used once

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6954]
**File/Catalogue:** Orks v74

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Using the Kustom Job stratagem can only be used once without generating errors. However, there is no limit on the amount of times that the Kustom Job stratagem can be used - only that each specific Kustom Job type is used once per army and only one per unit.

**Comment by grinxen** [comment]
This issue is still now adressed. It still screams that you have too many if you add more than one.
