### ISSUE TITLE
Tyranids - Genestealers can take unlimited wargear options

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6955]
**File/Catalogue:** Tyranids v64

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Several Genestealers wargear options have no hard caps on them:

- Scything Talons shouldn't be able to go higher than 20.
- Flesh Hooks shouldn't be able to go higher than 5.
- Acid Maws shouldn't be able to go higher than 5.

**Comment by GenWilhelm** [comment]
These constraints do exist in the data and have worked previously, so it must have been broken by the latest version of BattleScribe.

![image](https://user-images.githubusercontent.com/22036809/78397656-83f62d80-75e9-11ea-93da-2a5ec2e3675f.png)

I'll bring it up in the next meeting with Jonski (next week).

**Comment by DrTobogganMD** [comment]
Do you mean to have Max 0 and Max 20? I would think that no program could really deal with that ...

**Comment by GenWilhelm** [comment]
Yes, that's intentional. The Max 0 gets incremented depending on the number of models in the unit. Like I said, this worked correctly in previous versions of BScribe.

**Comment by DrTobogganMD** [comment]
This appears to be fixed in the latest Roster Builder
