### ISSUE TITLE
Genestealer Cults - Purestrain Genestealers can take unlimited amounts of Purestrain Talons

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6956]
**File/Catalogue:** Genestealer Cults v49

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Purestrain Talons can currently be taken as much as desired, but shouldn't be able to go higher than 20.

**Comment by GenWilhelm** [comment]
Same issue as #6955 - consolidating it into there.
