### ISSUE TITLE
Orks - Bigmek W/ KFF is 55 points including Wargear

### ISSUE THREAD

**Issue by LittleLetoni** [BSData/wh40k#6959]
**File/Catalogue: Orks v74** 

**BattleScribe version:** 2.03.20.329 & 2.03.14.143

**Platform:** Android & Windows

**Dropbox:** No

**Description:** Detailed issue description. Bigmek is updated to be 55 points including wargear (KFF, Slugga, Choppa, Stikkbombs) and can be accompanied by Grot Oiler (4 points)

**Comment by tag8833** [comment]
Fixed in the next publish.

**Comment by tag8833** [comment]
Fixed with this release:  https://github.com/BSData/wh40k/releases/tag/v1.4.15
