### ISSUE TITLE
Orks - Ork Mek Boss Buzzgob has incorrect wargear options

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6965]
**File/Catalogue:** Orks v74

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Ork Mek Boss Buzzgob can be selected without taking Nitnuckle and Lunk, but these are a mandatory selection for the unit and should always be included.
He can also take a Kustom Force Field in Battlescribe, but although his datasheet has the rules detailed for it, he has no actual way of taking it as a wargear option.

**Comment by tag8833** [comment]
> He **May** be accompanied by his two grot oilers
So they are definitely optional.  

The KFF thing is just confusing.  I agree with you he can't take that piece of wargear, but If I remove it as an option, someone will complain about me having removed it.  

The way I personally read it, he just has the KFF ability without the wargear choice, but when I originally published it that way people complained.  I've submitted it to GW twice seeking an FAQ and so far it hasn't been addressed.

I'm leaving this issue open in case you have a response, or anyone else feels like weighing in.

**Comment by Dunamis55** [comment]
As an addition, if he's going to have the option to take the KFF, shouldn't it be free for him, as he is 75 points including wargear?

**Comment by tag8833** [comment]
I agree.  I'll make it work that way next time I revise the file.
