### ISSUE TITLE
SM Librarians mixing Psychic powers with no error

### ISSUE THREAD

**Issue by xerusjoe** [BSData/wh40k#6966]
File: Space Marines v135

BattleScribe version: 2.03.14

Platform: Windows//Android

Dropbox:No

Description: Librarians should be giving an error when mixing psychic disciplines , but are not. 
An example of this would be a Librarian from the White Scars can have 2 powers from the Librarius Discipline or the Stormspeaking Discipline, but not 1 from each. At the same time, the Librarian in Phobos Armour can have 2 powers from the Obscuration Discipline or their native chapter's Discipline, but not 1 from each.

Relic Tome of Malcador would allow 1 additional psychic power that ignores this limitation. Currently the Tome does allow for an additional power without error.

**Comment by acebaur** [comment]
This is an app issue causing this. The logic on it hasn't changed.
