### ISSUE TITLE
Blood Angels Techmarine Servo Arm

### ISSUE THREAD

**Issue by Kohato** [BSData/wh40k#697]
**File/Catalogue:** Blood Angels

**BattleScribe version:** 2.01.03

**Platform:** All

**Dropbox:** No

**Description:** Blood Angels Techmarine is too greedy. He refuses to relinquish his servo-arm when taking a Jump Pack.

**Comment by Crowbar90** [comment]
Works fine on my sistem. Are you on BA v12?

**Comment by Kohato** [comment]
Ignore me, I apparently have v7 on my pc still.
