### ISSUE TITLE
Psychic Awakening: Pariah

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#6970]
Announced 2020-04-04 (Warhammer Preview Online 2) https://www.warhammer-community.com/2020/04/04/the-warhammer-preview-online-2-heroes-heretics-and-a-squirrelgw-homepage-post-1fw-homepage-post-1/

**Comment by DrTobogganMD** [comment]
I'd assign myself ... but we still have no idea if Necrons will be in it :(

**Comment by DrTobogganMD** [comment]
Preview 3 noted the factions: Sisters, Inq, and Crons.

**Comment by Mad-Spy** [comment]
This work has been released.
