### ISSUE TITLE
Imperium - Space Marines: Validation error on Tac Sergeant

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6972]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marine Tactical squad Sergeant says: "Space Marine Sergeant must have 1 more selections from Sgt Equipment (minimum 1)"
Have tried every combination but this error remains, Chapter selection is Imperial Fists if that could have anything to do with it?

BattleScribe v2.03.14.143

**Comment by acebaur** [comment]
I'm not replicating this, can you provide screenshots?
