### ISSUE TITLE
Orks: Validation error when selecting Ghazkhull

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6975]
**File:** Orks.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** Yes

**Description:** You can only add Ghazkull if no clan or Goff, is selected. If you do so and change clan, an error occur, saying that you can't have him.

**Comment by tag8833** [comment]
Fixed as part of this release:
https://github.com/BSData/wh40k/releases/tag/v1.4.16
