### ISSUE TITLE
Imperium - Space Wolves: Blood Claws not counting WGBL towards models for Special Weapons

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6984]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Blood Claws should be able to take two special weapons if the unit has 14 Blood claws and either a Wolf Guard Pack Leader or Wolf Guard Terminator Pack Leader. Rule says if the unit has as least 15 models, one Blood Claw may take an additional special weapon.

**Comment by Mad-Spy** [comment]
Looks like I forgot this when I redid the Blood Claw validation

**Comment by CrusherJoe** [comment]
Tricksy! But should be fixed now.
