### ISSUE TITLE
Dark Angels - Hellblaster "Assault Plasma Incinerator" Point Value

### ISSUE THREAD

**Issue by bflecken** [BSData/wh40k#6985]
**File/Catalogue:** Dark Angels/Space Wolves

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 
- Heavy support Unit "Hellblaster"
- Weapon option "Assault plasma incinerator"
- Correct value: 15pts. per weapon, see "Chapter Approved 2019"

**Comment by Mad-Spy** [comment]
Cost is incrementing by 16pts per model and also has a base cost of 17pts, so is calculating incorrectly.

**Comment by bflecken** [comment]
The point value of "Assault Plasma Incinerator" is still calculated with 17pts per weapon. 
All data files were updated today.
![hellblaster-value](https://user-images.githubusercontent.com/17409330/82131100-0883c080-97d2-11ea-86c5-97f40bdf8586.jpg)
