### ISSUE TITLE
Orks - Gunwagon is incorrectly using Forge World points for wargear

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6989]
**File/Catalogue:** Orks v75

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Gunwagon is using the Forge World version of a big shoota (is currently using the 6 points one but should be the 5 points one).

**Comment by alphalas** [comment]
The gunwagon is FW though

**Comment by tag8833** [comment]
Not Any more.   Now Gunwagon is just an ordinary battlewagon with a Killkannon via the Ork codex.

**Comment by alphalas** [comment]
....really? *sighs* ok don’t mind me
