### ISSUE TITLE
Orks - Battlewagon, Gunwagon, and Bonebreaka units have incorrect Kustom Job options

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6990]
**File/Catalogue:** Orks v75

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** When a Battlewagon, Gunwagon, or Bonebreaka has a zzap gun, the Kustom Job Zagzap is unavailable. In addition, the Da Boomer option is always available regardless of whether or not a killkannon is equipped.

**Comment by tag8833** [comment]
I've fixed the Zagzap.  Unfortunately, for now, I think we are going to have to just live with Da boomer and Zagzap being accessible to all Battlewagons.  The conditions necessary to constrain it based off of both unit type and wargear choices create a bunch of really unappealing choices.  Basically I would have to do Kustom Jobs different for just those 2 options, and then do some convoluted validation to make sure.
