### ISSUE TITLE
Imperial - Space Marines - Stormhawk Points Issue

### ISSUE THREAD

**Issue by Whiteraven15** [BSData/wh40k#700]
**File/Catalogue:**  Imperium - Space Marines

**BattleScribe version:** 2.01.

**Platform:** Android

**Description:** Stormhawk interceptor lists 2xAssault Cannons and uses the points costs for them. However, it shows with a Twin Assault Cannon, which is pointed different

Leads to a 7pt difference between the two.

**Comment by GenWilhelm** [comment]
This was changed a couple of days ago, do you have the most recent version (Space Marines v12)?

Which are you saying it should be? The index says "two assault cannons", which is what the catalogue current says it is.
