### ISSUE TITLE
T'au Empire: Typo in Manta Strike page ref

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7004]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.20

**Platform:** Android

**Dropbox:** No

**Description:** T'au Commander in XV85 suit: Manta Strike does not list the page ref. in the Codex, instead only "pvar".

**Comment by amis92** [comment]
Farsight p91
Commanders p92-93
XV8 103-104
Tactical Drones 109
