### ISSUE TITLE
Aeldari - Craftworlds: Unbound Force makes you choose Mixed Detachment?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7006]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Problem is as follows: if you start an Unbound Detachment of Craftworlds and try to give it a Craftworld Attribute, it gives a validation error. I've tested it with other Detachment types and it seems to function perfectly; Unbound Detachments, however, don't seem to work.

**Comment by Mad-Spy** [comment]
Taking an Unbound Detachment forces you to take the Mixed Detachment option, but I'm not sure why?

**Comment by FarseerVeraenthis** [comment]
You only get an attribute if you have a battle forged army. If you are unbound, it is impossible to confirm if you're actually battle forged compliant or not...
