### ISSUE TITLE
Imperium - Astra Militarum - Pask profile / Tech-priest Enginseer request

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#701]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Knight commander Pask is shown with a ballistic skill 3+ this is incorrect as he has a 2+.

 Adeptus Mechanicus unit Tech-priest Enginseer have the Astra millitarum faction key words but are currently unaccessible under the Astra millitarum faction builder.

**Comment by alphalas** [comment]
I'll get pask fixed - but the enginseer is in the cult mech file as he is in the cult mech section of the Index - https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions use the steps in there to add him to a guard force
