### ISSUE TITLE
Aeldari - Craftworlds: Yncarne is not registering as Ynnari for selecting Craftworld Attribute

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7018]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Ynnari does not appear to be an option when selecting The Yncarne as an HQ. Only after selecting the Visarch or Yvraine does the Ynnari option appear under the 'Craftworld Attribute'. The Yncarne still counts as a Ynnari HQ as far as I can tell from the rules and FAQs. 

Fiddling around I discovered that you could still use the Yncarne as an HQ, but you needed to add one of the other two Ynnari HQs, then switch Craftworld Attribute to Ynnari, add the Yncarne, remove the other HQ(s) and go on from there. I'm not sure if all rune abilities for farseers, spirit seers or warlocks are still accurate for the Ynnari list at that point.

**Comment by Mad-Spy** [comment]
This appears to be fixed in the current release. Closing.
