### ISSUE TITLE
Astra Militarum Scions costs wrong

### ISSUE THREAD

**Issue by fejjn** [BSData/wh40k#702]
**File/Catalogue:** astramilitarum all versions

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Astra Militarum Tempestus Scions costs 10 in Battlescribe but they should be costing 9 per dude instead..

**Comment by GenWilhelm** [comment]
Have you accounted for their hot-shot lasgun costing 1pt?

**Comment by fejjn** [comment]
Oh i have not. Sorry for that :/

**Comment by GenWilhelm** [comment]
No worries!
