### ISSUE TITLE
Imperium - Deathwatch: Incorrect cost for Primaris Apothecary

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7020]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** No

**Description:** Deathwatch Primaris Apothecary is listed as 68 pts were it should be 60 pts as of Chapter Approved 2019

**Comment by Mad-Spy** [comment]
68pts _is_ the cost written in Chapter Approved 2019.

**Comment by Regoso** [comment]
seems its in the errata of CA 2019 here https://www.warhammer-community.com/wp-content/uploads/2020/02/8fa9c5ab.pdf should be 1st page.
