### ISSUE TITLE
java.lang.NullPointerException when trying to import cat files

### ISSUE THREAD

**Issue by willemdh** [BSData/wh40k#7026]
**File/Catalogue:** Any cat file in this repo, such as "Imperium - Space Marines.cat"

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Not sure how I'm supposed to use this data. When I try to import one of the cat files, I always get the following error:

![image](https://user-images.githubusercontent.com/6462991/79686692-8b9d0f80-8242-11ea-9997-d532f8541ac4.png)

**Comment by amis92** [comment]
Hi. What are you trying to do? Where did you clone the repository, or how did you obtain the files?

What exactly version of the BattleScribe do you use?

**Comment by amis92** [comment]
For general information about catalogues and Data Editor, please browse https://github.com/BSData/catalogue-development/wiki

**Comment by willemdh** [comment]
Hi,

Version: BattleScribe v2.03.14.143

Cloned this repository: https://github.com/BSData/wh40k.git

Then tried to add:

![image](https://user-images.githubusercontent.com/6462991/79690804-9e244280-825c-11ea-8c25-fad6e64d9c26.png)

I'm trying to get better WH40K army lists in Battlescribe.

**Comment by Mad-Spy** [comment]
I'm not sure what you mean by "better" 40k lists. What are you trying achieve? Is there a change you're trying to make?

You can't need to add the files like that if you've cloned the repo. Make sure the files are in your Battlescribe data directory, then just open the roster editor and BS will pick them up automatically.

**Comment by amis92** [comment]
When you git-clone the repository, you need to put it in `/data` subfolder of the "Data location" you see in the window you shared (marked red):
![image](https://user-images.githubusercontent.com/2671396/79691109-0b84a300-825e-11ea-9ced-37f4b46a2962.png)

Then the BattleScribe will "see" the data automatically - no need to import it.

**Comment by willemdh** [comment]
> You can't need to add the files like that if you've cloned the repo. Make sure the files are in your Battlescribe data directory, then just open the roster editor and BS will pick them up automatically.

That did it, thanks!
