### ISSUE TITLE
Imperium - Space Wolves: Bjorn cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7027]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hey boss every time I open my sw files it says there’s a problem and also bjorn isn’t up to date on his points via the psychic awakening book

**Comment by Shoxaju** [comment]
Bjorn is currently 14 points more expensive than he should be, to clarify the above comment. He should be base 150 + wargear

**Comment by Mad-Spy** [comment]
Errors when loading rosters are usually caused when an item which you have selected has changed in the underlying data. It's unavoidable at times.

Bjorn's cost is correct in the current release. 150 + 22 (assault cannon) + 14 (heavy flamer).
