### ISSUE TITLE
Imperium - Space Marines: Phobos Librarian with Tome of Malcador should be able to select from Librarius discipline

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7028]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.14

**Platform:** Windows

**Dropbox:** Yes

**Description:** When I give a Librarian in Phobos Armour the Tome of Malcador there is not option to choose a Librarius power as per the Shadowspear FAQ: 

Q: If a Librarian in Phobos Armour has the Tome of Malcador Relic, does he know one additional power from the Librarius discipline or from the Obscuration discipline?
A: They know one additional power from the Librarius discipline.

**Comment by sjones71** [comment]
Space Marines: Librarian in a Salamanders Chapter with Tome of Malcador should be able to select from Librarius discipline as well. Currently states: "Librarian has 2 too many selections from  Promethian Discipline (maximum 0)" I thought this should go here to show that the problem looks to be with the tome, not Phobos Librarian. If this should be it's own thread please let me know to move.

**Comment by acebaur** [comment]
@sjones71 Any other librarian must select all their powers from a single discipline. Only the Phobos Librarian gets one power from the Librarius discipline and then the rest from the chapter or obscuration discipline

**Comment by sjones71** [comment]
That is incorrect. The entire point of this relic is to give a librarian access to powers outside Librarius. The wording of the relic itself does not mention any specific type of librarian at all: 

""LIBRARIAN model only. A model with this Relic knows one additional psychic power from any discipline they have access to.”

Excerpt From: Games Workshop Ltd. “Codex: Space Marines.”" (if for any reason I'm not supposed to quote from Games-Workshop books directly, please let me know and I'll edit to remove this)

I've looked through all Space Marine related faqs and nothing changes that wording at all. The Shadowspear faq does clarify that it does work that way for Phobos Librarians, but does not say that it does not work for other librarians in the same way.

**Comment by Mad-Spy** [comment]
The Shadowspear box was released _before_ Codex Marines 2.0. The Shadowspear FAQ refers to the OLD version of the Tome which did specify the Librarius discipline. The new version of the Tome is as per @sjones71 and only allows access to known disciplines.

The Shadowspear FAQ cannot be applied to Codex 2.0 because it was published beforehand.
