### ISSUE TITLE
Add Sorcerer on Palanquin of Nurgle to Death Guard Army List

### ISSUE THREAD

**Issue by Anthony2017** [BSData/wh40k#703]
**File/Catalogue:** Chaos - Death Guard

**BattleScribe version:** 2.01.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** FAQ 1 has added Sorcerer on Palanquin of Nurgle to the Death Guard Army List

**Comment by cartag** [comment]
Already updated.

**Comment by Anthony2017** [comment]
Sorry, didn't realize I need to resync my fork.  I resynced my github desktop app so thought all was well.  Sorry for the extra work.

**Comment by Anthony2017** [comment]
After starting fresh, I noticed V9 doesn't contain all the info needed to make Sorcerer on Palanquin of Nurgle available in the Death Guard List.  I'll create a new pull with the info.
