### ISSUE TITLE
Imperium - Dark Angels: Primaris Master missing weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7041]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.01

**Platform:** Android

**Dropbox:** No

**Description:** The dark angel primaris master should be able to be equipped with a auto bolt rifle and a power fist

**Comment by Mad-Spy** [comment]
He can. You need to drilldown into the "Auto bolt rifle and bolt pistol" option after selecting it. You'll notice that it has an orange tab on the left side, rather than a grey one to denote that it has sub-options.
