### ISSUE TITLE
The Points Value for Transuranic Arquebus Ranged Weapon Is wrong. 19pts instead of 12pts.

### ISSUE THREAD

**Issue by FinalCatch** [BSData/wh40k#7043]
**File/Catalogue:** 
Warhammer 40,000 v1.4.17
Imperium - Adeptus Mechanicus v68
**BattleScribe version:** 
2.03.15
**Platform:** 
Mac
**Description:** 

The Points Value for Transuranic Arquebus Ranged Weapon Is wrong. 19pts instead of 12pts.

This is present in the Skitarii Rangers, Troops Unit.

The Transuranic Arquebus Ranged Weapon points were set to 12pts in Chapter Approved '2019 page 22 of the Munitorum Field Manual.

**Comment by Thairne** [comment]
Look again:
You pay for the weapon AN the guy wielding it.

![grafik](https://user-images.githubusercontent.com/8590840/80190303-5c0c4f80-8614-11ea-9993-4ddea7ac329c.png)

**Comment by FinalCatch** [comment]
Ah right sorry about that. I'm still not a pro with Table Top Simulator.
