### ISSUE TITLE
Imperium - Inquisition: Jokaero Weaponsmith Abilities incorrect

### ISSUE THREAD

**Issue by spambidextrous** [BSData/wh40k#7047]
**File/Catalogue:** Imperium: Inquisition v40

**BattleScribe version:** 2.03.15

**Platform:** Windows

**Dropbox:** No

**Description:**

1. The Index: Inquisition (White Dwarf - Nov 2019, p.34) datasheet for this unit does not have the Ability "Quarry". The BattleScribe entry has "Quarry" Ability. This needs to be removed.

2. The wording of the "Inconceivable Customisation" Ability in the The Index: Inquisition datasheet reads as follows:

> At the start of your Shooting phase, you can select one friendly `<ORDO>` unit within 3" of this model and roll one D6; apply the result from the following table to the selected unit until the end of the turn.

The BattleScribe entry has the following wording, which is therefore incorrect:

> At the start of the Shooting phase, you can roll a D6 for one friendly `<ORDO>` unit within 3" of this model and apply the result from the following table to that unit for the remainder of the phase.

![Jokaero datasheet](https://user-images.githubusercontent.com/64229391/80150837-ffc41400-85b0-11ea-9c93-6ff882b15e1d.png)

**Comment by alphalas** [comment]
Update your data.

**Comment by Mad-Spy** [comment]
The unit does not have Quarry in v40, but the text for Inconceivable Customisation is definitely incorrect.

**Comment by alphalas** [comment]
Was it FAQ'd?
the text OP cites is *NOT* the text in the file.
because it has <ORDO> keywords OP didn't mention.

**Comment by Mad-Spy** [comment]
Because he delimited them with angle brackets and Github hides them. <the>

**Comment by alphalas** [comment]
..... I hate HTML bullshit

**Comment by spambidextrous** [comment]
Hmm, I definitely have v40 (and just deleted and updated my data) but when I view the unit BS shows the unit as per the attached screenshot, with "Quarry" listed in the "Abilities". Any ideas what is causing this?

![Jokaero BS image](https://user-images.githubusercontent.com/64229391/80319109-87ef2700-8806-11ea-96a8-41048c8dd95e.png)
