### ISSUE TITLE
Fallen: Sorcerer cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7051]
**File:** Fallen.catz

**BattleScribe version:** 2.03.21

**Platform:** Android

**Dropbox:** No

**Description:** Fallen Sorcerer with jump-pack show wrong point value. Compare with Chaos Space Marine equivalent entry

**Comment by erosbonazzi** [comment]
If you compare the Sorcerer with jump-pack cost of CSM and Fallen you'll find the costs are different. Thats a bug you should kindly fix. Thanks

**Comment by Mad-Spy** [comment]
@erosbonazzi are you the person who raised this issue? Spamming requests for fixes is not appreciated.

The issue was fixed two days ago and will be in the next data release.

**Comment by erosbonazzi** [comment]
I apologize. It's the first time I report a bug I couldn't understand the system. Fortunately now I created a profile and I know how to manage it in a proper way. Thanks for your service
