### ISSUE TITLE
Basic Craftworld autarch missing wargear options

### ISSUE THREAD

**Issue by QLM-Master** [BSData/wh40k#7058]
**File/Catalogue:** 
Warhammer 40k Craftworld eldar, autarch
**BattleScribe version:** 2.03.15

**Platform:** Windows 10 home

**Dropbox:** No

**Description:**
autarch is equipped with starglaive by default and has no alternative wargear available on options column
autarch (legends) and autarch with warp jump generator included for contrast, they seem to be fine.
bug persisted after re-downloading the data files after UI update, as well as occuring on two different PCs (both windows 10, one desktop one laptop), so im fairly certain its not a bad file on my end

![bugreport 1](https://user-images.githubusercontent.com/64338402/80294669-de8e2f80-8738-11ea-9e2d-6e0ed536d98a.PNG)
![bugreport 2](https://user-images.githubusercontent.com/64338402/80294673-e2ba4d00-8738-11ea-8646-2ac6cdfbd481.PNG)
![bugreport 3](https://user-images.githubusercontent.com/64338402/80294675-e64dd400-8738-11ea-8a53-8bf819b67b1d.PNG)

**Comment by Mad-Spy** [comment]
That's correct. The Codex Autarch may not swap his wargear. Only the version from the Legends PDF can do so.
