### ISSUE TITLE
Error on deathwatch terminator weapons

### ISSUE THREAD

**Issue by MiquelAdell** [BSData/wh40k#706]
**File/Catalogue:** Warhammer 40,000 8th Edition 

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** what? No, i guess

**Description:** 
![screen shot 2017-07-07 at 15 46 57](https://user-images.githubusercontent.com/4996457/27961213-4c996b8e-632e-11e7-8430-78619aec1245.png)

On the dethwatch terminator selection screen if you hover over "power lance and stormbolter" the tooltip has mixed information from "power maul and storm bolter".

**Comment by GenWilhelm** [comment]
Fixed in ddfc07deba3266f87e9b52403114593e6699d19c.

**Comment by MiquelAdell** [comment]
Thanks :-D
