### ISSUE TITLE
Blood Angels Sucessor WLT not showing

### ISSUE THREAD

**Issue by acebaur** [BSData/wh40k#7062]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

For BA successors the BA WLT traits are not showing up due to the logic hiding it if 0 selections of Blood Angels in the Roster. Per Blood of Baal all successors should have access to the BA WLT

**Comment by alphalas** [comment]
The only successor this applies to is Lamentors - FT are specifically restricted to the FT WLT table instead
