### ISSUE TITLE
REFERENCE: SPACE MARINE CATALOGUE SEPARATION 

### ISSUE THREAD

**Issue by acebaur** [BSData/wh40k#7063]
Just wanted to put this here so everyone can track the progress on the separation of the SM catalog into separate chapters. I'm currently in phase 1 which is getting the separate catalogs in a functional state. From there we will fix the Chapter Selector and other small fixes including the current bugs on C:SM.  To note, I will not be fixing minor bugs on C:SM until this separation is complete. 

 If you want to check out the data yourself the branch is located here https://github.com/BSData/wh40k/tree/I-broke-all-the-SM-lists

I make no guarantees about the functionality of any of the catalogs in that branch as it is all currently WIP. 

Finally, if you have numerous SM lists that you'd like to keep the time to start saving them is now. Once the separation is complete any existing lists will be inaccessible.

NOTE: THESE CHANGES ONLY AFFECT CODEX SPACE MARINES. ALL OTHER SM ARE UNAFFECTED

PHASE 1 IS COMPLETE
So the catalogs are now separated into their various chapters. In order to create a new roster you will need to choose the correct catalog for your corresponding chapter. The catalogs are now named "Imperium - Adeptus Astartes - <Chapter>"

You can still view your old rosters that are currently existing, but a lot of stuff has been removed, namely relics, WLT, all special Characters and disciplines. 

PHASE 2: BUGS!
I'm currently working through both new and existing bugs for the various chapters. Bear with me on this, I'm working as fast as I can to push out releases to get these fixed. Please report bugs as you find them but PLEASE make sure you check to see if it's already been reported.

**Comment by amis92** [comment]
@acebaur can you **add** to the top of the OP here some summary of changes so when we direct people who don't know what happened they can read up on it?

Like, you know, bullet points for changes for attention, and then maybe suggestions how to port old rosters? I mean I don't know what people might not know, but
![image](https://user-images.githubusercontent.com/2671396/83669925-a1884900-a5d2-11ea-9b53-4832c94bb550.png)

**Comment by acebaur** [comment]
Updated with info and Phase 2

**Comment by A-Huge-Amoeba** [comment]
How do you creat a successor chapter for a chapter that doesnt know its founding chapter e.g. Blood Ravens?

**Comment by alphalas** [comment]
You pick one, just like the codex says

**Comment by fuckingenglish** [comment]
Any status?

**Comment by DrTobogganMD** [comment]
@fuckingenglish Status on what?

**Comment by DrTobogganMD** [comment]
Killed by exterminatus! (And it's been done ferever)
