### ISSUE TITLE
Tau has some wrong weapon limits

### ISSUE THREAD

**Issue by thecoslime** [BSData/wh40k#7068]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Tau xv8 and xv25 battle suits have errors in their restrictions. The xv8's can't take any upgraded iridium armor and the xv25s can't use any fusions as a weapon choice if they only; have one per 3 models, however, if I add two to the list for both (which you can't do under the rules) it allows it as not an error. That's all I have found on my list. yes I have the new data

**Comment by amis92** [comment]
I'll just blindly guess it's a new BattleScribe's bug. Needs verification though, and I don't have time now.

**Comment by DrTobogganMD** [comment]
This one's valid, for the iridium at least. I'm not sure what OP means about the Fusion Blasters, you could have 3 per suit if you wanted, no issue with rules there. 

The max in parent is incremented to 1 for every 3 suits in the unit, but decreased by one for each selection of the Iridium armor. Meaning the first one taken sets max to 0.
![image](https://user-images.githubusercontent.com/16939161/80748650-e0fed980-8aea-11ea-9757-3baeba5532f4.png)

**Comment by amis92** [comment]
@DrTobogganMD OP meant Fusion Blasters on XV25s.

**Comment by DrTobogganMD** [comment]
Ah, the issue there is validating on links. That's always been spotty and is currently a no go. Fixing now.

**Comment by DrTobogganMD** [comment]
Fixed ... It's not the most svelte fix in the world, but it works.

**Comment by thecoslime** [comment]
Thank you guys so much.
