### ISSUE TITLE
Typo in Shadow Spectres Prism Rifle

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#707]
**File/Catalogue:** Craftworlds v11

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** 
Shadow Spectres: "each following **attak**" is misspelled in the Prism Rifle (Coherent) ability.

Also, did they change type between editions? The FW website has them under Fast Attack, but they're in Elites in the cat?

**Comment by GenWilhelm** [comment]
Looks like they're elites in the index.
