### ISSUE TITLE
Chaos Daemons: DP has no psychic power options

### ISSUE THREAD

**Issue by the84thHOSS** [BSData/wh40k#7072]
File/Catalogue: Chaos - Daemons v74

**BattleScribe version:** v2.03.22.332

**Platform:**Android

**Dropbox:** No

**Description:**
The Daemon Prince unit does not contain an option to select any Psychic powers, regardless of Mark.

Thanks!

**Comment by williamcaw** [comment]
It’s there tap on the democratic  allegiance  Again to access the powers of that chaos god. This is some  what not intuitive to most users.

**Comment by Mad-Spy** [comment]
You just need to actually look at the UI. Items with sub-selections have an orange tab on the left rather than a grey one.

**Comment by the84thHOSS** [comment]
Ah! I see where it is, now! Thanks!
