### ISSUE TITLE
Imperium - Adeptus Custodes Sagittarum Guard missing combi-style rules

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k#7074]
**File/Catalogue:** Imperium - Adeptus Custodes

**BattleScribe version:** 2.03.22

**Platform:** Windows/Android

**Dropbox:** No

**Description:** The Adrastus Bolt Caliver on Sagittarum Custodians has 2 profiles, which have a combi-weapon style rule that allows them to shoot both profiles at a -1 to hit (https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/Forgeworld_Custodes_Datasheets.pdf).  This isn't seen when viewing the roster or hovering over them, where it just lists both of their profiles.

**Comment by williamcaw** [comment]
It’s also missing under the assault 1 profile” For each hit roll of 1 made for attacks made with this weapon, the bearer’s unit suffers 1 mortal wound after shooting with this weapon.”

**Comment by Citronnade** [comment]
Thanks for pointing that out--I realized now I linked the *beta* version of the datasheets, which for some reason is the one that's linked on the downloads page on Forge World.  The proper reference for the datasheets is https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/Warhammer_40000/40K_Adeptus_Custodes_FW_Datasheets.pdf, which still has the -1 to hit rule but no longer has the mortal wounds on 1s on all Adrathic weapons.
