### ISSUE TITLE
Imperium - Space Marines: Custom character rules missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7076]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.17

**Platform:** Windows

**Dropbox:** No

**Description:** Cities of Death - Battle Honor system and custom character creation does not seem to work for the Space Marines when chapter selection Salamanders is selected. The exception for this is the Techmarine HQ which seems to still be able to select the custom character option. None of the units can recieve battle honors thought. As i am currently trapped inside like the rest of the world my family and i are running a campaign and would really appreciate if this could be fixed in the near future.

**Comment by acebaur** [comment]
This is because of how bloated SM is right now so it was stripped out to help with load times. While a fix is in progress this will not be addressed until the separation of the catalogs is finished.
