### ISSUE TITLE
Ghostkeel Battlesuit error when selecting "Gatling Burst Cannon" 

### ISSUE THREAD

**Issue by Blakeizen** [BSData/wh40k#7080]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows and Android

**Dropbox:** Yes/No

**Description:** When building a list, regardless of stratagems, other signature systems the Ghostkeel unit returns an issue of "maximum 0" when upgrading selecting the Signature System "Gatling Burst Cannon"
![Screenshot_20200430-095931](https://user-images.githubusercontent.com/64597223/80720940-9d48a780-8acb-11ea-940d-40e6a78a54cf.png)

**Comment by DrTobogganMD** [comment]
OP is correct. The constraint modifier for the Proto system requires a Burst Cannon entry. Ghostkeels get a 2x Burst Cannon entry.

**Comment by amis92** [comment]
@DrTobogganMD cookie for you! 

[![cookies gif](https://media.giphy.com/media/Y09s2Frxp7wpBGXTyt/200w_d.gif)](https://giphy.com/gifs/food-cookie-chocolat-Y09s2Frxp7wpBGXTyt)
