### ISSUE TITLE
Craftworlds - Missing options for Exarch Powers

### ISSUE THREAD

**Issue by doerek80** [BSData/wh40k#7081]
**File/Catalogue: Aeldari Craftworlds

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** Yes

**Description:** Some of the alternative Exarch Powers from Phoenix Rising are missing (e.g. Piercing Strike for the Banshee Exarch or Rain of Death for the Dark Reaper Exarch)

**Comment by Mad-Spy** [comment]
Those powers require specific weapons to be equipped. Equip those weapons and the powers will be made visible.
