### ISSUE TITLE
[Anon] Bug report: Imperium - Space Marines - Iron Hands Blessing of the Machine God

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7082]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.16

**Platform:** Windows

**Dropbox:** No

**Description:** It's about the rules from the codex supplement, specifically Iron Hands. When I select this chapter for Space Marines the rule "the flesh is weak" is applied, but I can't find anywhere the rule "blessing of the machine god" from the codex supplement, even when al I have created is a single Iron Hands detachment and that rule should be applied. I'm not mixing chapters either.

Thank you for your time!

**Comment by acebaur** [comment]
Showing up fine for me.

**Comment by Pelurpo** [comment]
I'm sorry I messed up, I mean the "Calculated Fury" rule, not the "Blessing of the machine god" spell.
As you can see in the picture I have selected a Batallion Detachment, chapter selection Iron Hands, Battleforged, Detachment, and Matched play options. Still, can't find it.

Thank you for your time once again!
![image](https://user-images.githubusercontent.com/64611164/80751221-b41de700-8b29-11ea-9b92-02a8cafaafa4.png)
