### ISSUE TITLE
8th Edition Data 

### ISSUE THREAD

**Issue by grahamsj** [BSData/wh40k#7083]
**File/Catalogue:** Warhammer 40k, 8th edition

**BattleScribe version:** 2.03.17.156

**Platform:** Windows

**Dropbox:** No

**Description:** I have uninstalled and reinstalled Battlescribe, but I can only download 7th edition from the 'add data' section. 8th edition is missing, and the github does not have the requisite .bsr file.

**Comment by Mad-Spy** [comment]
See #1703. It'll be back eventually.
