### ISSUE TITLE
ALL SPACE MARINES

### ISSUE THREAD

**Issue by CurtDaOrk** [BSData/wh40k#7086]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Chapter relics and codex relics do not flag up when equiped when you should be paying cp for them

**Comment by DrTobogganMD** [comment]
You’ll need to be clearer. What do you mean by “flag up”

**Comment by CurtDaOrk** [comment]
Sorry you know when you equip somthing and it flags up saying you can not do this because such and such conditions have not been met.
Or another example when you over equip wargear.
Again sorry not the best explainer a friend alerted me to the issue

**Comment by CurtDaOrk** [comment]
![Screenshot_20200502-193226](https://user-images.githubusercontent.com/56549280/80872722-b27c2c80-8cab-11ea-957f-eecc3c793813.jpg)

**Comment by CurtDaOrk** [comment]
See above picture have selected the relic but not red exclamation mark saying its a problem

**Comment by DrTobogganMD** [comment]
Do you have a warlord set elsewhere in the list?

**Comment by CurtDaOrk** [comment]
Yes i do bud

**Comment by DrTobogganMD** [comment]
Then what’s the issue?

**Comment by CurtDaOrk** [comment]
Thought you had to pay the extra cp for another character to have a relic

**Comment by DrTobogganMD** [comment]
Oh your warlords also has a relic set? Then yes.

**Comment by CurtDaOrk** [comment]
Yeah it does not flag up saying you have to do this when a different character that isnt your warlord is given a relic

**Comment by DrTobogganMD** [comment]
That is because there is no rule preventing that. Relics can be given to any character after fulfilling the requirements, normally that your warlord is of the same faction. You’ll want to read the codex for exact wording.

**Comment by CurtDaOrk** [comment]
Cool so i gave give out relics for free happy days

**Comment by DrTobogganMD** [comment]
Again. Please read your codex. You can give one relic to any character provided your warlord is of the same faction. It does not have to be the warlord. 

BattleScribe properly shows an error when attempting to give two different characters a relic without the stray.

**Comment by CurtDaOrk** [comment]
Yeah fully understand but dont you have to pay cp for it?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CurtDaOrk** [comment]
Massive apologies i forgot to give the warlord a relic what a cock

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DrTobogganMD** [comment]
You do for a second character to get a relic. If you’re saying BattleScribe doesn’t give an error because you can go to -cp on your total, that is not a data validation we do.

**Comment by CurtDaOrk** [comment]
Ok buddy cheers for the help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
