### ISSUE TITLE
Tau Crisis Suit Error

### ISSUE THREAD

**Issue by ConnorO79** [BSData/wh40k#7088]
**File/Catalogue:** Tau Army List

**BattleScribe version:** 2.03.

**Platform:** iOS

**Dropbox:** No

**Description:** Detailed issue description.

When selecting Crisis Iridium Suits, you can have 1 for every 3 models in the unit. But there is an error stating maximum 0, when selecting 2 or 3 iridium suits with 6 or 9 models respectively. But there is no error when selecting more iridium suits than is allowed.

Please help, thank you!

**Comment by amis92** [comment]
@DrTobogganMD you were fixing this, but only for the "1 iridium when taking 3 suits" case, or would that fix this as well?

**Comment by DrTobogganMD** [comment]
Yep, this should be fixed as well:

![image](https://user-images.githubusercontent.com/16939161/80960397-6249bb00-8dce-11ea-80ff-989091604886.png)

**Comment by ConnorO79** [comment]
Oh wonderful, thank you!
Looking forward to the release :)

**Comment by Mad-Spy** [comment]
Appears to be fixed in released version of T'au v58.
