### ISSUE TITLE
Ynnari - Wraithseer not Selectable as HQ in Ynnari Detachments

### ISSUE THREAD

**Issue by Miyth** [BSData/wh40k#709]
**File/Catalogue:** Aeldari - Ynnari v12

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** It looks like the Wraithseer is missing as an HQ choice in a Ynnari detachment. (It shows up normally in the Craftworlds detachments.) Irillyth is appearing normally in the Ynnari lists, so it looks like he may have gotten skipped over accidentally.

**Comment by FarseerVeraenthis** [comment]
related to #710 - the rest of the forgeworld units are due to be added in the next merge that creates the Ynnari CAT, the Wraithseer was in the second batch of models I uploaded so it is currently completely missing from the Ynnari CAT.
It will be there in the next few days :+1:

**Comment by USSX-Hares** [comment]
Should be fixed in #729
