### ISSUE TITLE
Astra Militarum missing relics

### ISSUE THREAD

**Issue by VolcanicToast** [BSData/wh40k#7090]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows
**Dropbox:** No

**Description:** Two of the militarum tempestus regiments relics are not showing up. The Emperors Fury of the 43rd Iotan Dragons and the Blessed Bolt Pistol of the 9th Iotan Gorgonnes are both missing.

**Comment by alphalas** [comment]
Cannot duplicate on BS v2.03.18. update app and data.
