### ISSUE TITLE
Closes on Sub Menu

### ISSUE THREAD

**Issue by CameronWThomas** [BSData/wh40k#7095]
**File/Catalogue:** 

**BattleScribe version:** 2.03.17

**Platform:** Windows

**Dropbox:** No

**Description:** Selecting the pencil icon on the top right opens a "support battlescribe" menu. Clicking the "X" on the top right of this closes all of battlescribe instead of just that menu. It works fine when clicking "mayble later", however clicking the x prompts a close

**Comment by Mad-Spy** [comment]
We are not the developers of Battlescribe. Please report any issues with the app via the methods described on the app website.
