### ISSUE TITLE
Imperium - Space Wolves: Characters are unable to access Companion's Blade

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7097]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.22

**Platform:** Android

**Dropbox:** Yes

**Description:** Characters who use a Power Sword or a Master Crafted Power Sword (Champion of the Chapter, for instance) MUST have access to Relic of the Fang 'Companion's Blade' . This is not happening now.

**Comment by Mad-Spy** [comment]
Looks like a logic issue; the condition group should be an AND, rather than an OR.
