### ISSUE TITLE
Ynnari - Some fw unit not appearing.

### ISSUE THREAD

**Issue by Naaris** [BSData/wh40k#710]
Windows/iOS/Android

The following appear on the above platforms:
Irillyth
Corsair Reaver band
Corsair Skyreaver band
Corsair Clouddancer band
Phoenix

Missing are:
Wraithseer
Hornets
Nightwings
Shadow spectres
Wasp Assault Walkers
Lynx
Warphunter
Scorpion
Cobra

All of these units appear when taking CW Eldar as the catalogue type.

**Comment by FarseerVeraenthis** [comment]
they will be added in the next merge 😄

**Comment by USSX-Hares** [comment]
Should be fixed in #729

**Comment by USSX-Hares** [comment]
@FarseerVeraenthis, could you accept the request?

**Comment by FarseerVeraenthis** [comment]
Merged, should be ready on the next release :smile: :+1:
