### ISSUE TITLE
Chaos - Thousand Sons: Helbrute validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7104]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.22

**Platform:** Android

**Dropbox:** No

**Description:** El Hellbrute da error cuando le equipo el lanzamisiles en uno de sus brazos. Lanzamisiles y Láser dan error, pero si se pueden poner. Pasa lo mismo en el de la Death Guard. Gracias.

**Comment by DrTobogganMD** [comment]
"The Hellbrute fails when the missile launcher is fitted to one of its arms. Missile launchers and lasers give error, but if they can be put. The same is true of the Death Guard. Thank you."

**Comment by Mad-Spy** [comment]
Duplicate of #7075
