### ISSUE TITLE
Imperium - Space Marines: Marksman's Honours text incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7106]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.22

**Platform:** Android

**Dropbox:** No

**Description:** The warlord trait: Marksman Honors for the Vanguard SM traits is listed differently than the latest SM codex.

**Comment by Mad-Spy** [comment]
Looks exactly the same to me:

![image](https://user-images.githubusercontent.com/29306451/81913259-9fc8f800-95c7-11ea-81f7-832dee6a188f.png)

![image](https://user-images.githubusercontent.com/29306451/81913295-ab1c2380-95c7-11ea-8860-7271d4616e19.png)
