### ISSUE TITLE
Imperium - Death Korps of Krieg - Mars-Alpha Pattern Leman Russ

### ISSUE THREAD

**Issue by Technomancy1** [BSData/wh40k#7108]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** The Mars-Alpha Pattern Leman Russ should have access to a hull mounted Plasma Cannon for 10 points and Multi-Melta for 15 points, that follows the standard Plasma Cannon profile and Multi-Melta profile for the Mars-Alpha Leman Russ. Neither of these options are currently available. They should be available for all Leman Russ variants available to the DKoK. This, to my knowledge, has not been errata'd out, and appears on WaHaPedia as an option.
![Capture](https://user-images.githubusercontent.com/65088180/81482434-f370c580-9204-11ea-97a4-db70aad6cb6a.PNG)

**Comment by alphalas** [comment]
PLEASE do not cite Wahapedia. check the books.

that being said you are correct.

**Comment by Technomancy1** [comment]
The information was gathered from the books. The FAQ's were checked for an errata. Wahapedia was used to verify that nothing was changed, as they always seem to be up to date more than anywhere else.

**Comment by alphalas** [comment]
@Technomancy1 they tend to be about as incorrect as we are sometimes - there are people who treat it like the word of god, hence my statement.
