### ISSUE TITLE
DeathWatch Aggressor wrong number of wounds

### ISSUE THREAD

**Issue by WayneScott97** [BSData/wh40k#7109]
File/Catalogue: DeathWatch v87

BattleScribe version: 2.03.

Platform: Windows

Dropbox: No

Description: In battle scribe the DeathWatch  Aggressor has 3 wounds but according to the Codex they have 2 wounds.
![Annotation 2020-05-09 121251](https://user-images.githubusercontent.com/18448766/81482805-966a1500-91ee-11ea-8e6f-408aa6798a2b.jpg)
![Annotation 2020-05-09 121319](https://user-images.githubusercontent.com/18448766/81482806-966a1500-91ee-11ea-823f-ca4bf302392b.jpg)

**Comment by Joklost** [comment]
The Aggressor datasheet has been errata'ed. You can find the errata on [Warhammer Community](https://www.warhammer-community.com/faqs/#warhammer-40000) site.
![image](https://user-images.githubusercontent.com/9192329/81494411-0fc63e00-92a9-11ea-9127-2277731572ac.png)
