### ISSUE TITLE
Ghostkeel Battlesuit

### ISSUE THREAD

**Issue by Geminozjusz** [BSData/wh40k#7113]
**File/Catalogue:** Warhammer 40,000 v1.4.19

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Wrong cost of TAU; ELITE Ghostkeel Battlesuit; SUPPORT SYSTEMS Shield generator
Should be 30 points.

**Comment by amis92** [comment]
Chapter Approved/Munitorum Field Manual 2019 Edition says:
![image](https://user-images.githubusercontent.com/2671396/81541227-14572900-9373-11ea-9388-e57e4621af0f.png)

**Comment by Geminozjusz** [comment]
Oh sorry I've checked it on wahapedia, guess i was wrong.

pon., 11 maj 2020, 10:35 użytkownik Amadeusz Sadowski <
notifications@github.com> napisał:
