### ISSUE TITLE
Blood angel warlord traits seem to only be available if you select hero of the chapter. If you create a new list and select a hq as your warlord the blood angel specific warlord traits arent available for selection. 

### ISSUE THREAD

**Issue by gribble77** [BSData/wh40k#7116]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by alphalas** [comment]
It will be fixed in the next release.
