### ISSUE TITLE
Imperium - Space Wolves: Venerable Chaplain Dreadnaught does not have Wolf Priest options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7117]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.22

**Platform:** Android

**Dropbox:** No

**Description:** When selecting the Venerable Chaplain Dreadnought HQ, does not have the keyword Priest or any of the related rules/options for a psyker unit. No litanies, disciplines, smite, etc.

**Comment by Mad-Spy** [comment]
A Chaplain Venerable Dreadnought does not have the WOLF PRIEST keyword which would provide access to Litanies. It is also not a PSYKER.
