### ISSUE TITLE
Warhammer 40,000 Blood Angels Death Company Weapons

### ISSUE THREAD

**Issue by thekingpysces** [BSData/wh40k#7118]
**File/Catalogue:** 

**BattleScribe version:** 2.03.19

**Platform:** Windows

**Dropbox:** No

**Description:** When using blood angels, in warhammer 40k. It only allows death company marines too take either a bolt pistol and chainsword, or a thunder hammer. However Death company should be able to take a much greater variety of weapons.

**Comment by alphalas** [comment]
Uncheck the chainsword/bolt pistol option
