### ISSUE TITLE
Chapter/House/Swarm rules not displaying

### ISSUE THREAD

**Issue by Hivetyrant36** [BSData/wh40k#7120]
**File/Catalogue:** Warhammer 40000 1.4.19

**BattleScribe version:** 2.03.19

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** When I hover over the Household choices, Chapters, or hive fleet, the pop up only shows what the rule is called and that it was made with battle scribe. https://imgur.com/8zEyjbq

**Comment by alphalas** [comment]
That’s likely because the flavor text was not added by the author. Read your codex.

**Comment by Hivetyrant36** [comment]
That's why I posted here. Is this not the group that made the files for 40k? Seems a bit prissy.

**Comment by Hivetyrant36** [comment]
Like just add the flavor text or show me how to or something. Don't just fucking close people's tickets they would like some help on. Why are all warhammer fans such unrelenting narcissists?

**Comment by Hivetyrant36** [comment]
Like you can literally go fuck yourself

**Comment by Hivetyrant36** [comment]
Jon can go fuck himself, this isn’t resolved. At least say “ok yeah we missed that one.” Fuckers Will – HiveTyrant36  From: Jon KissingerSent: Wednesday, May 13, 2020 8:20 PMTo: BSData/wh40kCc: Hivetyrant36; AuthorSubject: Re: [BSData/wh40k] Chapter/House/Swarm rules not displaying (#7120) Closed #7120.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by alphalas** [comment]
Because the data files are specifically made to supplement your codex, not replace it. We the data editors still expect you the user to have your books so you can reference them and understand the way your army works

**Comment by DrTobogganMD** [comment]
@Hivetyrant36 your issue is best brought up to the developer, not the data team. The data is indeed in the file and you would see that once you choose to view roster. This thread is being locked because there is no further need for discussion.
