### ISSUE TITLE
Some codecies house/hive fleet do not have rule text

### ISSUE THREAD

**Issue by Hivetyrant36** [BSData/wh40k#7121]
**File/Catalogue:** Warhammer 40k v128

**BattleScribe version:** 2.03.19

**Platform:** Windows/IOS

**Dropbox:** No

**Description:** When I hover over the Household choices, or hive fleet, the pop up only shows what the rule is called and that it was made with battle scribe. There is no text for the actual rule. The other codecies seem to have this. https://imgur.com/8zEyjbq

**Comment by DrTobogganMD** [comment]
As I noted in your other issue, the data is present. Your pop ups not showing tooltips is likely an app bug. That would be best addressed in the BattleScribe repo github.com/BattleScribe

**Comment by Hivetyrant36** [comment]
Thank you for the explanation, that makes a lot more sense.
