### ISSUE TITLE
Chaos - Death Guard - Helbrute cannot have any selections of missile launcher

### ISSUE THREAD

**Issue by ThatMurloc** [BSData/wh40k#7124]
**File/Catalogue:** Death Guard v80

**BattleScribe version:** 2.03.19

**Platform:** Windows

**Dropbox:** No

**Description:** Whenever I try to put a missile launcher on my helbrute on any of his fists. It gives me an error and says "Helbrute cannot have any selections of Missile launcher (hidden).

**Comment by Mad-Spy** [comment]
It's a bug in the app. We're waiting on a fix.
