### ISSUE TITLE
Harlequins Psychic Awakening

### ISSUE THREAD

**Issue by Kroq9Gar** [BSData/wh40k#7125]
**File/Catalogue:** Aeldari - Harlequins

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** Adding Harlequin Psychic Awakening data, to be officially released in June but leaked in detail. I added them myself this afternoon, using the Craftworlds Exarch Powers as a basis for the format of Pivotal Roles. Completely new to this so unsure about how to progress, but I have the updated data file for you if wanted.

**Comment by amis92** [comment]
@Kroq9Gar https://github.com/BSData/catalogue-development/wiki/Getting-Started
