### ISSUE TITLE
Imperium - Imperial Guard Company Commander Gets No Warlord Traits

### ISSUE THREAD

**Issue by milsebones** [BSData/wh40k#7130]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Mac

**Dropbox:** No

**Description:** Imperial Guard Company Commander selected as warlord. When try to pick a trait, displays error: Company Commander has 1 too many selections from Warlord Traits (maximum 0)

**Comment by alphalas** [comment]
Do you have a Tank Ace without having taken the Tank Ace Stratagem/Have 2 Tank Aces in your list with the stratagem? If so, you cannot take a warlord trait.

**Comment by alphalas** [comment]
![59603E63-5850-4D5F-AD89-CE77327E8D86](https://user-images.githubusercontent.com/15703066/82105388-1c9fc300-96e9-11ea-8d7f-5976105a9310.png)

**Comment by milsebones** [comment]
Ahhhhhh... Now I see. I did not know the Tank Aces had that downside. Thank
you. Sorry to have bothered you.

milse
