### ISSUE TITLE
Blood Angel Captain Cannot Take Warlord Traits

### ISSUE THREAD

**Issue by Romasterer** [BSData/wh40k#7133]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Romasterer** [comment]
Bug says "Captain cannot have any selections of Warlord Traits (Codex: Blood Angels) (hidden)
This error did not show up before I updated battlescribe today.

**Comment by alphalas** [comment]
And it will be fixed in the next release
