### ISSUE TITLE
Add Banner stratagems to Daemons catalogue

### ISSUE THREAD

**Issue by myworldinbnw** [BSData/wh40k#7137]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 
Add an possibility to add stratagems for example a Plague Banner to a Plaguebearers unit!

**Comment by williamcaw** [comment]
Is it before set up or after during play?

**Comment by myworldinbnw** [comment]
Before setup. You set a demon banner (a strategem) to a specific group of
Plaugebearers. You exchange hit for a Deamonic Icon.

--
Med vänlig hälsning

*Mats Olsson*
FOOD AND BEVERAGE, SOCIAL MEDIA COORDINATOR, ENVIROMENT COORDINATOR
Clarion Collection Hotel Carlscrona

m: +46 733989131 <+46%20733989131> e-mail: mats.olsson@choice.se

Clarion Collection Hotel Carlscrona har ett franchiseavtal med Nordic
Choice Hotels. För ytterligare information om Nordic Choice Hotels besök
www.choice.se. Hotellet ägs och drivs av Winn Hotel Group AB, för
information besök www.winn.se

**Comment by Mad-Spy** [comment]
@myworldinbnw not exchange as such, you get the abilities on top of the normal banner.
