### ISSUE TITLE
Repository not visible on Appspot again.

### ISSUE THREAD

**Issue by tolmik** [BSData/wh40k#7142]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows 10

**Dropbox:** Yes

**Description:** The wh40k repository is not listed on https://battlescribedata.appspot.com/#/repos and not visible in the data manager inside BattleScribe.

**Comment by Mad-Spy** [comment]
Yes, it happens sometimes. You'll just need to be patient.

**Comment by amis92** [comment]
See #1706
