### ISSUE TITLE
Imperium - Space Marines: White Scars Khans should have access to Chapter Master stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7144]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.23

**Platform:** Android

**Dropbox:** Yes

**Description:** White Scars brigade detachment:

Captain on bike has the stratagem for chapter master, however the name does not change, and the chapter master reroll description does not change either. 

Khan and Khan on bike do not have the option for chapter master.

**Comment by acebaur** [comment]
Captain on a bike has the correct logic, but BS isn't hiding the Rites of Battle and showing Chapter Master as it should. Khan on a bike will be fixed in the next update.
