### ISSUE TITLE
Aeldari - Craftworlds: Ynnari Psykers should not have access to Runes of Fortune powers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7147]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.03.23

**Platform:** Android

**Dropbox:** No

**Description:** Ynnari detachment bug:
Runes of fortune can only be taken on a craftworld detachment (pg 36 of psychic awekening, Phoenix rising) as such ynnari psychers cant change their smite to a runes of fortune power
Bug confirmed to:
Farseer
Farseer skyrunner
Spiritseer
Warlock (conclave, skyrunner, skyrunner conclave)
Bonesinger
Henlock wraithfighter

**Comment by Mad-Spy** [comment]
You're not exactly correct. The rule is the Runes of Fortune can be taken by <CRAFTWORLD> PSYKER models. Models in an YNNARI Detachment replace <CRAFTWORLD> with REBORN ASURYANI, and lose their eligibilty for that reason.

**Comment by FarseerVeraenthis** [comment]
Actually, to be completely accurate, "YNNARI PSYKERS must know their powers from the Revenant Discipline" so... all Psykers should only have the Revenant discipline available if Ynnari is selected.
There is a chance I'll get this done Soon(TM), I had a look at what would be required to fix the other Ynnari issues and generally tidy them up and I think I know what needs doing... I just have to actually do it...!!

**Comment by Mad-Spy** [comment]
@FarseerVeraenthis They already only have access to Revenant in Ynnari Detachments for their main powers. Rune of Fortunes is the ability to swap Smite for something else, which shouldn't be allowed.

**Comment by FarseerVeraenthis** [comment]
Argh! You're right, got my runes mixed up...!
