### ISSUE TITLE
Cost of the Twin Punisher Gatling cannon should be 60pts

### ISSUE THREAD

**Issue by Millambr** [BSData/wh40k#7151]
Imperium/Astra Militarum

BattleScribe version: 2.03.19

Platform: Windows

Dropbox: No

Description: Cost of the Twin Punisher Gatling cannon was changed from 40pts to 60pts in the FAQ for Chapter approved 2019, but is still showing as 40pts in battlescibe when added to the Vulture.
Is the same in the other catalogues the can take a Vulture like Elysian Drop troops

**Comment by Mad-Spy** [comment]
Something must have gone wrong with #7070

**Comment by alphalas** [comment]
best I can tell the data is correct on GitHub - update your data.
