### ISSUE TITLE
Imperium - Deathwatch: Deathwatch intercessor sergeant missing thunder hammer selection

### ISSUE THREAD

**Issue by Taseon** [BSData/wh40k#7156]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
Correct in Deathwatch v89. Closing.
