### ISSUE TITLE
Imperium - Astra Militarum.catz is corrupted

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7165]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.02.23

**Platform:** Android

**Dropbox:** No

**Description:** (. . .)/Imperium - Astra Militarum.catz is corrupted and cannot interact with anything that could try and reference it.

**Comment by acebaur** [comment]
Do you have 7th edition files on your device?

**Comment by amis92** [comment]
Might be a case of https://github.com/BSData/wh40k/issues/6573
