### ISSUE TITLE
Cypher and Fallen are gone

### ISSUE THREAD

**Issue by Carparts1** [BSData/wh40k#7167]
**File/Catalogue:** 
[Warhammer 40,000 8th Edition - Copy.zip](https://github.com/BSData/wh40k/files/4701602/Warhammer.40.000.8th.Edition.-.Copy.zip)

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** They are nowhere to be found

**Comment by Mad-Spy** [comment]
What do you mean "they are gone"? They are still in the Fallen catalogue, where they have been since April 2019.
