### ISSUE TITLE
Dark Angels Missing Repulsor Executioner

### ISSUE THREAD

**Issue by ParmaSeanCheese** [BSData/wh40k#7170]
**File/Catalogue:** 

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:**No

**Description:** The Windows version of Battle scribe is missing the repulsor executioner on the Dark Angels heavy support area.

**Comment by Mad-Spy** [comment]
It is in v128 of the Dark Angels file. Make sure you have the latest version of the data files.
