### ISSUE TITLE
Tau units not adding points for Shas'vre upcharge

### ISSUE THREAD

**Issue by Zaanzabar** [BSData/wh40k#7176]
**File/Catalogue:** Tau Empire.cat

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** No

**Description:** 
Tau units for Stealth Suit Team and Crisis Suit Team do not charge points for Shas'vre upgrade.  Should be 6pts and 3pts respectively.

Also, Stealth Suit Team doesn't add +1 power when you add 2 tactical drones.

**Comment by amis92** [comment]
@Zaanzabar and where are costs for Shas'vre upgrades given (printed)? As far as I can tell, they are free; there's no cost for it anywhere I can find.

**Comment by amis92** [comment]
The fix is only for XV25 PL cost.

**Comment by Zaanzabar** [comment]
Thanks, that's what I get for trusting wahapedia for my numbers.
