### ISSUE TITLE
[Anon] Bug report: Imperium - Red Scorpion Characters C:SM

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7178]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.24

**Platform:** Android

**Dropbox:** No

**Description:** Red Scorpion characters Casan Sabius and Sirae Karagon arent showing on any of the marine chapters.

**Comment by acebaur** [comment]
They weren't in the FW index, so I missed them. They will be in the next release.

Thanks!
