### ISSUE TITLE
Imperium - Space Wolves - Logan Grimnar constraint error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#718]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** Yes

**Description:** While using spearhead formation, selecting Logan Grimnar as a HQ choice, the following roster error: has 1 too many selection of Logan Grimnar (maximum 0)

Data is updated to latest version.

**Comment by ilaunchbury** [comment]
I'm unable to replicate this issue in Space Wolves v5. Please check you have the latest data and try again.
