### ISSUE TITLE
Imperium - Raven Guard: Error when trying to open rosters

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7184]
**File:** Imperium - Raven Guard.catz

**BattleScribe version:** 2.03.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I go to open a roster an error message reading “ Problems Loading Data Files” comes up stating 
“ There are problems with one or more of the data files needed for this roster. You should notify the author of the data files to let them know about the issue”.

**Comment by acebaur** [comment]
Not having this issue. are you on mobile or PC? When you update data make sure you click Delete existing data first

**Comment by fuckingenglish** [comment]
i had to reload the data file twice to even select most army's . time out on app spot just re download the file.

**Comment by Mad-Spy** [comment]
@fuckingenglish are you the person who raised this issue?

**Comment by fuckingenglish** [comment]
no but had the same problem as the person that raised the issue

**Comment by Mad-Spy** [comment]
No update from OP. Closing.
