### ISSUE TITLE
Blood Angels - Patrol Detachment -> Elite -> Dreadnought missing Heavy Flamer on Melee Weapon Arm

### ISSUE THREAD

**Issue by jacobschellenberg** [BSData/wh40k#7185]
**File/Catalogue:** 
Blood Angels

**BattleScribe version:** 2.03.24.335

**Platform:** Android

**Dropbox:** No

**Description:** Detailed issue description.
I cannot add a Heavy Flamer to the Melee Weapon Arm of a Dreadnought for Blood Angels, but it is available in the Blood Angels codex.

**Comment by Mad-Spy** [comment]
You need to drill-down into the melee arm to see the option to swap.
