### ISSUE TITLE
Imperium - Blood Angels: Captain should be able to take a relic blade and a storm shield

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7187]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:** No

**Description:** For some reason the Blood Angels captain cannot take a Relic Blade and Storm Shield even though it has the same rules as the Ultramarine captain which can take both.

**Comment by Mad-Spy** [comment]
You're correct. The recent ruling to allow models to use multiple bullet points independently should apply, allowing him to swap his original chainsword for a relic blade, then swap his boltgun for another chainsword which can then be swapped for a storm shield.
