### ISSUE TITLE
Black Templars - Missing Specialist Detachment 'Sword Brethren' 

### ISSUE THREAD

**Issue by dl7vxgIAd0S** [BSData/wh40k#7189]
**File/Catalogue:**  Black Templars v6

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description.

Specialist Detachment currently only lists 'Indomitus Crusaders' as an option. This is from the Vigilus Defiant rulebook.

**Comment by Mad-Spy** [comment]
The Show/Hide condition needs to change to being a Primary Catalogue condition or the Detachment needs to move out of the Library

**Comment by acebaur** [comment]
I fixed this already. will be out in the next release
