### ISSUE TITLE
Necrons - Necron Warriors lack Reanimation Protocols Rule

### ISSUE THREAD

**Issue by toadchild** [BSData/wh40k#719]
**File/Catalogue:** Necrons v6

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:**

When adding Necron Warriors, the Reanimation Protocols rules text appears on the roster, but the Warriors unit itself does not say that it has the rule.  Immortals correctly have the rule listed.  I've included a screenshot for reference.

![reanimation](https://user-images.githubusercontent.com/1512358/27981404-82102b9c-6340-11e7-86e3-2dde4cd205dc.png)

**Comment by toadchild** [comment]
A roster with just Warriors:

![reanimation2](https://user-images.githubusercontent.com/1512358/27981482-e260c7cc-6340-11e7-99a1-ecc1c3a209a7.png)

**Comment by GenWilhelm** [comment]
For some reason it doesn't show on minimal output. Seems like a BattleScribe bug, rather than a data issue.
If you enable advanced options and can change it to full output, it should appear.

**Comment by Kohato** [comment]
Gen is correct. It is tied to the warriors. It is a battlescribe bug, nothing to be done in the data.

**Comment by toadchild** [comment]
I played around with it and figured out the issue.  The line that shows rules/weapons is hidden for units that don't pay points for their weapons.  If I change the cost of Gauss Falyers to 1 point in the data editor, then both "Reanimation Protocols" and "10x Gauss Flayers [10 pts]" appear.  It seems there needs to be at least one item that has a cost for it to show them at all.  Presumably that is why full output shows it - it includes items that are free.
