### ISSUE TITLE
Ultramarines - Victrix Honour Guard don't move to NFO when Calgar is in a Detachment

### ISSUE THREAD

**Issue by gluck3d** [BSData/wh40k#7190]
**File/Catalogue:** Imperium - Adeptus Astertes - Ultramarines v6

**BattleScribe version:** 2.03.24

**Platform:** Android

**Description:** NFO tab doesn't appear when trying to add Victrix Honour Guard when Calgar is present (should take no slot according to codex and it is how it has worked before split).

Steps:
1) Create a new force for Ultramarines/Batallion for ex
2) Select Ultramarines for Chapter Selection
3) Add Marneus Calgar to HQ

Expected:
There should be No Force Org tab with a possibility to add Victrix Honour Guard

Actual:
No NFO tab. Victrix Honour Guard can be added only to Elites tab

**Comment by DrTobogganMD** [comment]
This very well could be related to the bug I put on BS proper regarding mobile and primary category modification.
