### ISSUE TITLE
Aeldari - Drukhari: Hekatrix Bloodbrides Attacks value incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7193]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.20

**Platform:** Windows

**Dropbox:** No

**Description:** Hekatrix Bloodbrides have 2 attacks, they should have 3 (And the unit leader (Syren) should have 4) as per their update in legends.
https://www.warhammer-community.com/wp-content/uploads/2019/12/f51f9967.pdf

**Comment by FarseerVeraenthis** [comment]
good catch, that's quite a buff from the index version...!
