### ISSUE TITLE
9th Edition Army Building validation

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#7196]
As we know a little about how list-building is going to work in 9th, with Battle Size controlling points limit and base CP and deductions for each Detachment, I thought I'd open a task to gather ideas on how to implement it. Any input is welcome.

![image](https://user-images.githubusercontent.com/29306451/83955636-d30c4900-a84c-11ea-96bb-4dfda733fe9e.png)

![image](https://user-images.githubusercontent.com/29306451/83955651-0f3fa980-a84d-11ea-916f-1c50f28712e4.png)

**Comment by Mad-Spy** [comment]
I tried implementing Battle Size as a top-level Force and then Detachments as children, but the points validation is screwy because it doesn't count Child Forces even if you tell it to (unless I'm doing it wrong).

Also, you can't actually hide Force Entries (checking hidden does nothing) so currently we'd have to duplicate all the Detachment entries to make sure they didn't appear in the dropdown.

**Comment by alphalas** [comment]
I’m of the Mindset we just have it be a selector to replace the battleforged cp tickbox, and if you really wanna be fancy have some points validation(ala HH minimum points for Low), otherwise that’s it.

**Comment by acebaur** [comment]
@Mad-Spy so a system like we have for AoS wouldn't work with the detachments?

I'd that's the case I think we just have a strat that replaces the battleforged like alphalas said. Then we could have each detachment cost points with a the Warlord checkbox adding the CP back in

**Comment by DrTobogganMD** [comment]
The detachment/CP validation has been added to master in prep for 9e. This can be closed.
