### ISSUE TITLE
Imperium - Space Wolves - Wolf Claw cost

### ISSUE THREAD

**Issue by Gnofry** [BSData/wh40k#720]
It seems that taking two Wolf Claws or two Lightning Claws on a model doesn't appropriately trigger the reduced cost.

**Comment by FarseerVeraenthis** [comment]
File version 6 does not have this issue.

**Comment by Gnofry** [comment]
![image](https://user-images.githubusercontent.com/17345182/28547210-d9d2e3a2-709b-11e7-85cd-9cf12a9eb1d8.png)

Version 6 certainly does have this issue.

**Comment by penguin20000** [comment]
Looks like i missed the Wolf Guard. Is this the only unit left with the option missing?

May have helped FarseerVeraenthis if the unit/model was mentioned in the original bug report.

I'll fix it now

**Comment by Gnofry** [comment]
When the issue was created two weeks ago, every wolf claw was not appropriately costed. As of my testing in version 6, Wolf Guard, Wolf Guard on Bikes, and Thunderwolf Cavalry do not have the twin Wolf Claw option.

**Comment by Gnofry** [comment]
Of course, many more units will need to have the option added due to the FAQ, but I imagine that will be covered separate to any specific issue.

**Comment by FarseerVeraenthis** [comment]
Hang on a minute, those units are setup to select their claws on either side, if you pick two the cost updates automatically... 
I checked last night and both wolfguard and thunder wolf cav are setup like that - selecting two claws separately automatically  updates the cost

**Comment by FarseerVeraenthis** [comment]
Or at least, it appeared to for me last night, but yeah, that screenshot rather shows differently... I :heart: battlescribe!
