### ISSUE TITLE
Imperium - Adeptus Mechanicus: Manipulus and Daedalosus should not be able to take Vigilus WLTs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7202]
**File:** Imperium - Adeptus Mechanicus.catz

**BattleScribe version:** 1.50.00

**Platform:** Android

**Dropbox:** No

**Description:** Battlescribe allows Tech Priest Manipulus and Daedalosus to take Vigilus Defiant WL traits. RAW they can't.

**Comment by Mad-Spy** [comment]
Only TECH PRIEST DOMINUS models can get the necessary keyword in the Vigilus Detachments.
