### ISSUE TITLE
Quantity Bug for Iron Hands Weapons

### ISSUE THREAD

**Issue by Areadbhair** [BSData/wh40k#7203]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** adding weapons to an Ironhands unit that has the option of taking multiples of it automatically gives at least 2 copies off of one click, worst offender is Lieutenant at 20 chainswords on a single click

**Comment by Mad-Spy** [comment]
I'm not able to replicate this issue at all on a clean list. Are you opening an old list, or is this a new one? Are you using the new Iron Hands catalogue?

If all else fails, try deleting the downloaded data from your machine and then re-downloading it.

**Comment by acebaur** [comment]
I am also not able to replicate this on PC or mobile. Are you sure you don't have a macro enabled on your mouse?

**Comment by Mad-Spy** [comment]
No update from OP. Closing.
