### ISSUE TITLE
Primaris Lieutenants missing warlord trait

### ISSUE THREAD

**Issue by mihem72** [BSData/wh40k#7207]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

I am using battlescribe on my windows computer and i have updated to the latest datafile.
I have made a Salamander list.
If i chose a primaris Lieutenant as warlord the option to chose warlord trait does not appear.
I have a librarian in Phobos armor but it keep telling me there´s an error when i chose psychic powers from the promethean discipline.

**Comment by Mad-Spy** [comment]
Are you making your Salamanders list using the Salamanders catalogue, or is it an old list which is using the Space Marines catalogue?

The consolidated Space Marines catalogue is no longer valid and you should rebuild your list in the appropriate Chapter catalogue to ensure all selections work correctly.

**Comment by mihem72** [comment]
I am using the list using the Salamanders catalogue.
Otherwise i wouldnt be able to use Adrax agatome to.
The weird thing is that the warlord problem only appears when using a primaris lieutenant as warlord.
If i try to make my librarian a warlord i can chose a warlors trait for the librarian, but not if i chose i lieutenant.

**Comment by Mad-Spy** [comment]
@acebaur You've mistakenly put the WLTs and Relics on all types of Lieutenants at the Unit level when they should be at the model level. You'll need to make the model entries shared, then rebuild the units in each catalogue using the shared entry so you can attach the SSEGs in the right place.

**Comment by mihem72** [comment]
No i have not put the WLT on all lieutenants. 
The weird thing is i can only chose relice on unit lvl and not on model lvl.
I can put a bullet in warlord on model lvl, but i cannot chose a wlt.

**Comment by mihem72** [comment]
i have tried all kinds of lieutenants and the problem is still the same...
It´s so annoying when someone change how battlescribe works and leave the program with so many errors...
And the problem with the librarian that can gets error when chosing psychic powers from promethean discipline is not only me who have that problem. I have a friend who is WS player with the same problem with his librarian.

**Comment by mihem72** [comment]
I have tried making list with the other SM chapters.
It seems like the problem with the librarian only occurs when i chose Salamanders.
The problem with the lieutenant that doesn't get to chose what WLT they want appears no matter what chapter i chose.

**Comment by acebaur** [comment]
@mihem72 Well I'm sorry that the catalog currently has some bugs. If you had any idea how big of a task it was to separate the chapters into separate catalogs so that when running multiple detachments it wouldn't crash people's mobile devices then maybe you'd be more understanding. Please keep in mind that we are volunteers and do this in our spare time and any project of this size is bound to have some issues.

**Comment by mihem72** [comment]
I am sorry if you feel my text has been some kind of personal attack because that has never been my intention. I am well aware that it is a very big job so keep everything updated and making sure there are no problems and i am very happy for all the work you guys are putting into this project.
