### ISSUE TITLE
Blood Angels: Aggressors are added with duplicated wargear

### ISSUE THREAD

**Issue by corivera** [BSData/wh40k#7208]
The point calculation for Aggressors in the Blood Angels catalog is way off. A base unit with boltstorm gauntlets should be 110, but the default cost is now 143 due to duplicated weapons. Increasing the squad size to 6 brings the total to 542 points, with 5 base aggressors being equipped with 25 gauntlets and grenade launchers.

As an aside, the weapon picking options for Blood Angels weapons in particular are cumbersome. Using a similar selection style as Inceptors would likely solve both issues.

**Comment by Mad-Spy** [comment]
Appears that the per-model choice of wargear is being duplicated due to the SEG being marked as "collective" when it doesn't need to be.

**Comment by corivera** [comment]
Opened a PR with a fix for it.

**Comment by corivera** [comment]
@alphalas Pulled down the latest version of the catalog, and it seems like the Aggressor weapon point costs aren't being multiplied by the number of models in the unit.

**Comment by corivera** [comment]
Also looks like the Weapon Options don't have a default value set.
