### ISSUE TITLE
Imperium - Astartes ????: Unable to create multi-detachment lists

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7211]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** After the most recent update I cannot create Astartes lists with more than one detachment. It sits there and just locks up on the creating roster notification.

**Comment by acebaur** [comment]
can you be more specific? Which chapter? If it's Codex SM, are you using the individual chapter catalogs?

**Comment by fuckingenglish** [comment]
the same reasoning behind opening one detachment at a time still applies from before pre splitting of the  sm catalog if you are running a older device apply or not have low ram mode enabled . I'd still recommend loading one at a time .

**Comment by Mad-Spy** [comment]
No update from OP to give any details. Closing.
