### ISSUE TITLE
Magister Sevrin Loth

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k#7225]
**File/Catalogue:** Warhammer 40,000 v1.5.2

**BattleScribe version:** 2.03.21.165

**Platform:** Windows

**Dropbox:** No

**Description:** Magister Sevrin Loth (Red Scorpions special character) currently only has access to the psychic powers of the Librarius Discipline as it was originally listed in Index Imperium I, which was correct when Imperial Armour Index - Forces of the Adeptus Astartes was originally released.  However, the updated Librarius Discipline in Codex: Space Marines should supersede this list, and Magister Sevrin Loth should have access to all six psychic powers now.

**Comment by acebaur** [comment]
Unless there is a FAQ that I am unaware of, Loth's entry specifically references Index Imperium 1. Therefore he does not have access to anything from C:SM
