### ISSUE TITLE
Imperium - Deathwatch: Intercessor Sgt missing hand flamer option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7228]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Deathwatch Intercessors data seems to be missing hand flamer weapon options for sergeants.

**Comment by Mad-Spy** [comment]
Deathwatch Intercessors have never been given that option as far as I can find. If you have evidence otherwise, please update this issue and we'll reopen it.
