### ISSUE TITLE
Salamanders Lieutenants cannot have Lieutenants

### ISSUE THREAD

**Issue by Sleep-Frog** [BSData/wh40k#7234]
**File/Catalogue:** Imperium - Adeptus Astartes - Salamanders v8

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Updated my data, noticed that the lieutenants entry in my roster was broken.  Added a fresh Lieutenants entry and customized it, but the roster won't validate because "Lieutenants cannot have any selections of Lieutenant (hidden)".  Created a new roster with a patrol detachment and add one Lieutenants unit, which shows the same error.  Deleting the sole Lieutenant in the unit clears the validation error, but that obviously isn't very useful, and on Android at least gives no UI to add another one.  Possibly set to a group of 0-0 instead of 1-2?

**Comment by acebaur** [comment]
Lt had to be reworked and have new Root Entries, Make sure you check "Delete existing data" first when you update.

**Comment by Sleep-Frog** [comment]
Re-updated with delete existing data checked, problem persists as described.  Any other possible fixes?

**Comment by amis92** [comment]
@Sleep-Frog can you reproduce on a new roster as well? Sometimes BattleScribe doesn't correctly "update" older rosters. :(
