### ISSUE TITLE
Lieutenant "Cannot have any selections of Lt (Hidden)"

### ISSUE THREAD

**Issue by Sleep-Frog** [BSData/wh40k#7235]
File/Catalogue: Imperium - Adeptus Astartes - Salamanders v8

BattleScribe version: 2.03.25

Platform: Android

Dropbox: No

Description: Updated my data, noticed that the lieutenants entry in my roster was broken. Added a fresh Lieutenants entry and customized it, but the roster won't validate because "Lieutenants cannot have any selections of Lieutenant (hidden)". Created a new roster with a patrol detachment and add one Lieutenants unit, which shows the same error. Deleting the sole Lieutenant in the unit clears the validation error, but that obviously isn't very useful, and on Android at least gives no UI to add another one. Possibly set to a group of 0-0 instead of 1-2?

Acebaur closed a similar issue and suggested deleting existing data in the update, but after taking that step the problem persists as described.  I apologize if making a new entry since the other was closed is not the proper way to proceed but I did want to make it clear that the suggested fix doesn't resolve the issue.

**Comment by acebaur** [comment]
ah I see why. The Show Primaris only is set to 0 selections instead of 1. It'll be fixed in the next release
