### ISSUE TITLE
No field Commander options for Enginseers

### ISSUE THREAD

**Issue by Shoesington** [BSData/wh40k#7236]
**Adeptus Mechanicus** 

**BattleScribe version:** 2.03.25.338

**Platform:** Android

**Dropbox:** No?

**Description:** Cannot give Enginseers Field Commander role. Entry appears, but cannot select trait, only shows option of None

**Comment by Shoesington** [comment]
https://discordapp.com/channels/558412685981777922/569676136028700699/722641485929119744
Here's where I talked to Valor about the issue.

**Comment by Mad-Spy** [comment]
Duplicate of #7224
