### ISSUE TITLE
Imperium - Imperial Fists: Relic validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7237]
**File:** Imperium - Imperial Fists.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Fist of Terra and fist of vengeance can be added to units without a power fist
Imperial fist relics can also be added to crimson fist units without requiring -1CP

**Comment by acebaur** [comment]
CF do not have access to Relics of the Fist that are IF only. All successors have access to Special Issue Wargear. We have two lists of these(even though they appear as one in the supplement), one that is present in every supplement and one that is specific to the IF supplement.
