### ISSUE TITLE
Imperium - Space Marines (various) - Dreadnought missing twin heavy bolter

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#724]
**File/Catalogue:** Dark Angels v16 / Space Marines v12 / Space Wolves v5 / Grey Knights v5

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** Dreadnought should be able to replace its assault cannon with a twin heavy bolter.

- [x] Dark Angels
- [x] Space Marines
- [x] Space Wolves
- [x] Grey Knights

**Comment by tekton** [comment]
How did we all miss that? Or did it get removed from gst or something? 😈

**Comment by alphalas** [comment]
Twin HB is a FW option, innit?

**Comment by tekton** [comment]
@alphalas it's on page 11 of the Imperial Index

The GK one did have it but it wasn't showing up for some reason, it is now after I refreshed data on Windows, Mac, and mobile, btw.

**Comment by GenWilhelm** [comment]
The default SM units were all built once, then copied from there weren't they? So if it was missed the first time, then all copies will be missing the option.
