### ISSUE TITLE
Blood Angels Aggressor Issue

### ISSUE THREAD

**Issue by rktrevor** [BSData/wh40k#7242]
**File/Catalogue:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Aggressors Squad not showing correct calculation of weapons, only calculates 1 cost of Boltstorm instead of 3 when selection of the option.

**Comment by Mad-Spy** [comment]
This issue is already resolved and will be in the next data release.
