### ISSUE TITLE
Sisters Cannoness

### ISSUE THREAD

**Issue by Khaine1969** [BSData/wh40k#7245]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Cannoness cannot choose bolter as a standard "non legends" option...should be able to take bolter, powersword, and rod of office as standard options

**Comment by alphalas** [comment]
It was FAQ’d - rod of office comes with plasma and power sword now
