### ISSUE TITLE
issues w/chaos knights

### ISSUE THREAD

**Issue by sirloin869** [BSData/wh40k#7248]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
no vows/stratagems & points issues (w/o sources-knowledge): so, there doesnt see to be an option for giving iconoclasts there stratagem-mainly the 3 "vows" found in the codex-,& the infernals are missing the "surge" chart. Also, the pts.values are vastly different than in the codex(havent found new source so far, so i mite be wrong&will have to search more)for the despoiler w/ sword&guantlet[305 in codex vs.372 in prog.]. All I've found so far, best regards

**Comment by Mad-Spy** [comment]
Please edit this issue to contain some actual details.

**Comment by Mad-Spy** [comment]
Stratagems are only included in the data if they have a direct effect on list building. The Vows do not. Same with the Surge table. The data set is a player aid, not a replacement for the Codex.

Points values are updated in Chapter Approved every year, and Battlescribe is kept up to date with that. Also, the cost for a Despoiler with Sword and Gauntlet is _excluding_ wargear; you need to pay for the sword, gauntlet and heavy stubber which is what brings the cost up.

**Comment by sirloin869** [comment]
Hello.

I was wondering if the program still supported Warhammer 8th edition. I didn't see it after my update, and it's not on my Kindle Fire after download. Thanks in advance for any update, best regards

Jamie

________________________________
