### ISSUE TITLE
Add Valerian and Aleya to Custodes/SoS

### ISSUE THREAD

**Issue by hags0770** [BSData/wh40k#7250]
**File/Catalogue:**  Warhammer 40000 v1.5.2

**BattleScribe version:** 2.03.25.338

**Platform:** andriod

**Dropbox:** No

**Description:** 
No option for either faction to add Valerian and Aleya as a unit option

**Comment by fuckingenglish** [comment]
you technically opened this in #6870 Madspy

**Comment by DrTobogganMD** [comment]
So technically I don't think these can actually be taken in any battleforged army. They'd need to be added for unbound only in Imperium catalogues.

**Comment by hags0770** [comment]
Wouldnt the talons of the emperor rule from psychic awakening allow them to be taken with the custodes, allowing the custodes to remain battle forged.  Because it allows units with the sisters of silence key word, which aleya has to be part of a custodes detachment, and it still remains a custode detachment, and doesnt effect detachment abilities

**Comment by hags0770** [comment]
> So technically I don't think these can actually be taken in any battleforged army. They'd need to be added for unbound only in Imperium catalogues.

**Comment by alphalas** [comment]
No because they only have Imperium as a faction keyword.

**Comment by DrTobogganMD** [comment]
@WindstormSCR When this is added. PL Update changed them to PL10 total.
