### ISSUE TITLE
Aeldari: Craftworlds - Howling Banshees have incorrect point values

### ISSUE THREAD

**Issue by Scrant0** [BSData/wh40k#7254]
File/Catalogue: Aeldari - Craftworlds v93

BattleScribe version: 2.03.15

Platform: iOS

Dropbox: No

Description: I think the Howling Banshees have incorrect point values.  Psychic Awakening - Phoenix Rising gives them a value of 9 per model not including wargear (making them 13 total with 4 pt. power sword).  The point value in BS is 7 per model (11 total with 4 pt. power sword).  I think I checked all my bases and there haven't been any other changes since Phoenix Rising, but please let me know if I missed something!

**Comment by Mad-Spy** [comment]
Chapter Approved 2019 came out after Phoenix Rising and lowered the cost to 7pts per model.
