### ISSUE TITLE
Blood angels Thunder Hammer Bug

### ISSUE THREAD

**Issue by Carlsonsten** [BSData/wh40k#7256]
Hey, I found a bug in the blood angels battlescribe list.
The issue is with the power Hammer points value when you favourite the character carrying it. 
When you add the favourite to the list the thunder hammer only costs the pre faq change 16 points instead of the full 40p.
The same issue partially appears when you duplicate a characte with a hammer.
The first duplicate appears with the 16 point hammer but the second duplicate has the correct point value.
When you remove either of the correct point value characters the third one that had the lower points corrects itelf.
Characters affected are the captain, captain on bike, lieutnants and the techmarine.

**Comment by Mad-Spy** [comment]
This is a BS bug, rather than anything wrong with the data. As you say, it corrects itself if you make an edit to the Roster or character.

Please report it to the Battlescribe developer via https://github.com/Battlescribe/Release
