### ISSUE TITLE
Engine War rules missing publicationId in XML

### ISSUE THREAD

**Issue by AdrianTudC** [BSData/wh40k#7257]
**File/Catalogue:** 
Adeptus Mechanicus

**BattleScribe version:** 
2.03.

**Platform:** 
any

**Dropbox:** 
No

**Description:** 
Looking at the XML data generated for an AdMech army, the canticles of omnissiah rules are missing `publicationId` attribute. 

Example:
`<rule id="60e1-437b-7d8f-d5c6::1341-df13-3a13-9b91" name="Canticles of the Omnissiah - Mars: Panegyric Procession" hidden="false">`

**Comment by Mad-Spy** [comment]
It is up to the data author whether or not they include book references on their data.
