### ISSUE TITLE
Imperium - Astra Militarum: Commissars displaying Voice of Command when they should not

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7259]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Commissars have voice of command special rule. They do not receive this. It should only be available if they are selected as a warlord and has the correct trait.

~~Stratagem Operative Requisition Sanctioned does not add units to no force organisation slot.~~

**Comment by Mad-Spy** [comment]
The Assassin added to your Force by Operative Requistion Sanctioned is chosen immediately before the game, not during list building.

**Comment by alphalas** [comment]
This is a Battlescribe App bug, not a data bug.
