### ISSUE TITLE
Death Guard - Possessed have incorrect wargear options

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#7261]
**File/Catalogue:** Chaos - Death Guard v82

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Possessed are able to take an Icon of Despair in Battlescribe, but there is no option to allow them to do so in the Death Guard codex or FAQ.

**Comment by Mad-Spy** [comment]
This is an annoying one. Index Possessed had the option (which is where this came from), CSM Possessed have always had the option, but DG ones don't!

Given that the FoF is now gone, I suppose I'll have to take it out.
