### ISSUE TITLE
Imperium - Astra Militarum: Lord Commissar should not have Voice of Command

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7262]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.00

**Platform:** Android

**Dropbox:** No

**Description:** It says that Lord commissar has the voice of command but  they dont.

**Comment by alphalas** [comment]
duplicate of #7251 ((and like 6 other reports...

**Comment by alphalas** [comment]
https://github.com/BattleScribe/Release/issues/218
