### ISSUE TITLE
Imperium - Ultramarines: Relics of the Chapter not working

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7264]
**File:** Imperium - Ultramarines.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The Relics of The Chapter stratagem seems to be not working.  I can select the free relic as normal but any attempts to choose additional relics beyond the free relic using the stratagem produces the error: has 1 too many selections from chapter relics (maximum 1).  I get this error with multiple different roster arrangements, warlord selections, and even in mixed imperium rosters featuring ultramarines.  I apologize if this is a known issue or if the problem is on my end, but I saw no other reports with this issue.

**Comment by acebaur** [comment]
Will be fixed in the next release

**Comment by LedZepan** [comment]
Thank you for the update :3.  Sorry if that had already been stated somewhere.  Still learning!
