### ISSUE TITLE
Imperium - Astra Militarum: Custom Regiments do not prevent standard Regiments being selected

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7266]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** You can take 2 custom regiments doctrines and a named regiment doctrine. This should produce an error when list building as it should be either or.

**Comment by alphalas** [comment]
it's an App bug, not data bug.

**Comment by alphalas** [comment]
https://github.com/BattleScribe/Release/issues/218
