### ISSUE TITLE
Imperium - Astra Militarum: Hide Regimental Doctrine text in SHADs.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7267]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The Super-Heavy Auxiliary Detachment should not have access to regimental doctrines. This should be hidden for this detachment.

**Comment by alphalas** [comment]
It's an app bug, not a data bug.

**Comment by alphalas** [comment]
https://github.com/BattleScribe/Release/issues/218
