### ISSUE TITLE
Imperium - Astra Militarum: Request to add Officio Prefectus Command Tank Stratagem

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#7268]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Officio Prefectus Command Tank stratagem is missing.

**Comment by Mad-Spy** [comment]
This Stratagem is used at the beginning of the game, not during list building. Normally, such Stratagems are not included in the data set. However, an argument could be made for it.
