### ISSUE TITLE
Looking for custom codex

### ISSUE THREAD

**Issue by TheKnightofNi** [BSData/wh40k#7269]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

Description:
I need someone with experience to contact me regarding making an Angry Marines repository for me to use. Willing to pay a reasonable price for someone to make it for me.

**Comment by Mad-Spy** [comment]
You're better off asking on the Data Authors Discord (https://discord.gg/KqPVhds), rather than here.

Having said that, that Codex is 70 datasheets plus all the other add-on stuff, so it's not going to be cheap!
