### ISSUE TITLE
REFERENCE: Release Thread

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k#7274]
Data Developers - Please use this issue to push new releases if doing so via comment.

# Explainer

- Create an issue comment that starts with `/release` on the first line.
- Second (non-empty) line will be used as a release title/name.
- All following lines will be interpreted as a release description/body.
- Description (even if empty) will always be appended with a comparison link to the previous release, unless there is no previous release.

# How to

Add a comment with one of the following to push a release:

### For a standard release:
*given latest release v2.2.2, will create a release v2.2.3 (increases patch)*
> /release
>
> This is title of v2.3.0

### For a Chapter Approved/Big FAQ initial releases (game-wide updates):
*given latest release v2.2.2, will create a release v2.3.0 (increases minor, resets patch)*
> /release bump=minor
>
> This is title of v2.3.0

### For a new game edition:
*given latest release v2.2.2, will create a release v3.0.0 (increases major, resets minor and patch)*
> /release bump=major
>
> This is title of v3.0.0

**Comment by DrTobogganMD** [comment]
/release
Pariah Is Here!

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/160985362)
Created release:
[v1.5.4](https://github.com/BSData/wh40k/releases/tag/v1.5.4)
**Pariah Is Here!**

**Comment by Mad-Spy** [comment]
/release
The End of 8th Edition
This is the final release of Warhammer 40,000 8th Edition. No more fixes will be done on 8th Edition. Any issues found between now and the 9th Edition release will be resolved in (or after) that release when it comes.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/172687900)
Created release:
[v1.5.5](https://github.com/BSData/wh40k/releases/tag/v1.5.5)
**The End of 8th Edition**

**Comment by amis92** [comment]
/release tag=v8.5.5
The End of 8th Edition
This is the final release of Warhammer 40,000 8th Edition. No more fixes will be done on 8th Edition. Any issues found between now and the 9th Edition release will be resolved in (or after) that release when it comes.

This is also the first release following a new versioning scheme, where Major version corresponds to the game Edition,
the Minor to the major game updates, and the Patch is for regular release bumps.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/172697625)
Created release:
[v8.5.5](https://github.com/BSData/wh40k/releases/tag/v8.5.5)
**The End of 8th Edition**

**Comment by DrTobogganMD** [comment]
/release
Fuc it! Well do it live!

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/185072493)
Created release:
[v9.0.1](https://github.com/BSData/wh40k/releases/tag/v9.0.1)
**Fuc it! Well do it live!**

**Comment by DrTobogganMD** [comment]
/release
The Only Good Bug Is A Dead Bug! Join Battlescribe Today! Would You Like To Know More?

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/186440250)
Created release:
[v9.0.2](https://github.com/BSData/wh40k/releases/tag/v9.0.2)
**The Only Good Bug Is A Dead Bug! Join Battlescribe Today! Would You Like To Know More?**

**Comment by DrTobogganMD** [comment]
/release
https://www.youtube.com/watch?v=5wQSXBhnxl8

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/187856833)
Created release:
[v9.0.3](https://github.com/BSData/wh40k/releases/tag/v9.0.3)
**https://www.youtube.com/watch?v=5wQSXBhnxl8**

**Comment by DrTobogganMD** [comment]
/release
https://www.youtube.com/watch?v=5wQSXBhnxl8

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/187909538)
Created release:
[v9.0.3](https://github.com/BSData/wh40k/releases/tag/v9.0.3)
**https://www.youtube.com/watch?v=5wQSXBhnxl8**

**Comment by DrTobogganMD** [comment]
/release
My name is Señor Supremo, You killed my Phaeron. Prepare to Die.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/189387174)
Created release:
[v9.0.4](https://github.com/BSData/wh40k/releases/tag/v9.0.4)
**My name is Señor Supremo, You killed my Phaeron. Prepare to Die.**

**Comment by DrTobogganMD** [comment]
/release
Hello. My Name Is Joe And Java 8 Kicked My Ass.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/190771549)
Created release:
[v9.0.5](https://github.com/BSData/wh40k/releases/tag/v9.0.5)
**Hello. My Name Is Joe And Java 8 Kicked My Ass.**

**Comment by DrTobogganMD** [comment]
/release
*Racks Minigun* Oh, I **know** what the Wargamers like.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/191685029)
Created release:
[v9.0.6](https://github.com/BSData/wh40k/releases/tag/v9.0.6)
***Racks Minigun* Oh, I **know** what the Wargamers like.**

**Comment by DrTobogganMD** [comment]
/release
Someone should tell Sanguinary Guard that it's a tid bit cold outside.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/192716411)
Created release:
[v9.0.7](https://github.com/BSData/wh40k/releases/tag/v9.0.7)
**Someone should tell Sanguinary Guard that it's a tid bit cold outside.**

**Comment by DrTobogganMD** [comment]
/release
8 Days in and I'm spent. Someone tell me a funny release title.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/194134042)
Created release:
[v9.0.8](https://github.com/BSData/wh40k/releases/tag/v9.0.8)
**8 Days in and I'm spent. Someone tell me a funny release title.**

**Comment by DrTobogganMD** [comment]
/release
In other news: Rich man makes a Pringles can fly using only fire. 

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/195582196)
Created release:
[v9.0.9](https://github.com/BSData/wh40k/releases/tag/v9.0.9)
**In other news: Rich man makes a Pringles can fly using only fire.**

**Comment by DrTobogganMD** [comment]
/release
Primaris - (UK) IPA: /ˈpɹaɪməɹis/ taking over being the best, main, or excellent from others while being late to the party and under costed.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/196988123)
Created release:
[v9.0.10](https://github.com/BSData/wh40k/releases/tag/v9.0.10)
**Primaris - (UK) IPA: /ˈpɹaɪməɹis/ taking over being the best, main, or excellent from others while being late to the party and under costed.**

**Comment by DrTobogganMD** [comment]
/release
Coming Soon: Primaris Warp Troopers. Equipped with the latest Elda...Imperium weaponry - Warp Pack and Death Spinners!

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/198542746)
Created release:
[v9.0.11](https://github.com/BSData/wh40k/releases/tag/v9.0.11)
**Coming Soon: Primaris Warp Troopers. Equipped with the latest Elda...Imperium weaponry - Warp Pack and Death Spinners!**

**Comment by DrTobogganMD** [comment]
/release
Did you miss me? Here, have some PL updates. Don't say I never gave you anything.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/206412435)
Created release:
[v9.0.12](https://github.com/BSData/wh40k/releases/tag/v9.0.12)
**Did you miss me? Here, have some PL updates. Don't say I never gave you anything.**

**Comment by DrTobogganMD** [comment]
/release
We're still here. Every time you ask about a C&D, the Imperium steals another Eldar weapon.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/211371417)
Created release:
[v9.0.13](https://github.com/BSData/wh40k/releases/tag/v9.0.13)
**We're still here. Every time you ask about a C&D, the Imperium steals another Eldar weapon.**

**Comment by DrTobogganMD** [comment]
/release
Trazyn is the Primarch of the Blood Ravens. Change my mind.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/218758276)
Created release:
[v9.0.14](https://github.com/BSData/wh40k/releases/tag/v9.0.14)
**Trazyn is the Primarch of the Blood Ravens. Change my mind.**

**Comment by DrTobogganMD** [comment]
/release
Confirmed: Eradicators to 85ppm in October

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/225988856)
Created release:
[v9.0.15](https://github.com/BSData/wh40k/releases/tag/v9.0.15)
**Confirmed: Eradicators to 85ppm in October**

**Comment by DrTobogganMD** [comment]
/release
Outriders have many uses, both for dakka and stabba.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/238752047)
Created release:
[v9.0.16](https://github.com/BSData/wh40k/releases/tag/v9.0.16)
**Outriders have many uses, both for dakka and stabba.**

**Comment by DrTobogganMD** [comment]
/release
In This Week’s Issue, Updates to the superior balancing system of 40k: PL

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/249123928)
Created release:
[v9.0.17](https://github.com/BSData/wh40k/releases/tag/v9.0.17)
**In This Week’s Issue, Updates to the superior balancing system of 40k: PL**

**Comment by DrTobogganMD** [comment]
/release
DMCA Letter Received. Thanks for all the fish.

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/260018758)
Created release:
[v9.0.18](https://github.com/BSData/wh40k/releases/tag/v9.0.18)
**DMCA Letter Received. Thanks for all the fish.**

**Comment by Mad-Spy** [comment]
/release
What’s all this fuss over a Departmento Munitorum Change Authorization?

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/260797491)
Created release:
[v9.0.19](https://github.com/BSData/wh40k/releases/tag/v9.0.19)
**What’s all this fuss over a Departmento Munitorum Change Authorization?**

**Comment by DrTobogganMD** [comment]
/release 
The one without a witty title

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/266106752)
Created release:
[v9.0.20](https://github.com/BSData/wh40k/releases/tag/v9.0.20)
**The one without a witty title**

**Comment by DrTobogganMD** [comment]
/release
Ahriman: “Remember the time I cursed my entire legion?” BSData: “Hold my Release Title.”

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/271727213)
Created release:
[v9.0.21](https://github.com/BSData/wh40k/releases/tag/v9.0.21)
**Ahriman: “Remember the time I cursed my entire legion?” BSData: “Hold my Release Title.”**

**Comment by DrTobogganMD** [comment]
Closing Release Thread - Beginning a new monthly thread to make comment count ... readable.
