### ISSUE TITLE
Inner Fire Description

### ISSUE THREAD

**Issue by chancelang** [BSData/wh40k#7275]
**File/Catalogue:** Imperium - Grey Knights v55

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Details text for Inner Fire is wrong.

**Comment by chancelang** [comment]
**Imperium - Grey Knights.cat**

`ln 8528`

~Empyrean Domination~ has a warp charge value of 5. If manifested...

Inner Fire has a warp charge value of 5. If manifested...

**Comment by chancelang** [comment]
Tried to submit the fix but no permission to push 🙂

**Comment by Mad-Spy** [comment]
@chancelang you'll need to fork the repo, make the changes on that copy and then submit a pull request.

**Comment by chancelang** [comment]
Tried with the online editor, it worked create a branch https://github.com/BSData/wh40k/pull/7276
