### ISSUE TITLE
Dark Angels - Angels of Death Rule

### ISSUE THREAD

**Issue by Detmud** [BSData/wh40k#7281]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Rule Angels of Death is missing on a lot of Profiles

**Comment by Thairne** [comment]
Its on the bottom of the roster output as a force rule.

**Comment by Detmud** [comment]
Well the interseccors don't have the angels of death tag
