### ISSUE TITLE
Blood angels aggressors weapon cost 

### ISSUE THREAD

**Issue by acebaur** [BSData/wh40k#7283]
The weapon cost isn't duplicating for each aggressor in the sqaud and is only counting once. 

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by alphalas** [comment]
It’s fixed in the current release.
