### ISSUE TITLE
Codex Assasin Operative Requisition does not cost 2 CP any more

### ISSUE THREAD

**Issue by macfenchel123** [BSData/wh40k#7284]
The entry Operative Requisition Sctioned is now free with the War of the Spider book.

**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Mad-Spy** [comment]
The War of the Spider content has not been incorporated into the data set yet.
