### ISSUE TITLE
Dark Angels Units missing Tag for Angels of Death

### ISSUE THREAD

**Issue by Detmud** [BSData/wh40k#7285]
**File/Catalogue:** Dark Angels

**BattleScribe version:** 2.03.21

**Platform:** Mac

**Dropbox:** No

**Description:** PA: RotD Page 35 “All DARK ANGELSunits in Codex: Dark Angels(excluding SERVITORS) gain the Angels of Death ability”. This is not yet reflected by the DA DAtafile  and inconsistent with other Datafiles.

**Ultramarines:**
> Intercessor Squad
>Selections: Bolt rifle
>Rules: Angels of Death
>Abilities: Combat Squads, Weapon: Bolt rifle

**Dark Angels:**
>Intercessor Squad
>Rules: And They Shall Know No Fear, Defenders of Humanity
>Abilities: Combat Squads
>Bolt rifles
>    Selections: Bolt rifle
>    Weapon: Bolt rifle

**Comment by Thairne** [comment]
Work is currently being done to switch DA over to a library so it shares all units with Space marines and their supplements.
