### ISSUE TITLE
Imperium Salamanders - Custom Characters Available for some but not others.

### ISSUE THREAD

**Issue by Skagul** [BSData/wh40k#7289]
**File/Catalogue:** Warhammer 40,000 v1.5.2 - Imperium - Adeptus Astartes - Salamanders

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** Yes
Example Roster file: https://www.dropbox.com/s/9o5pvefdfv84ny7/Custom%20Characters.rosz?dl=0 

**Description:** After you select GameType "Narrative" You can make your Techmarine a custom characters but not a Captain

To replicate.

Create a new Roster
Select Salamanders > Batallion > Set Salamander Chapter.
Add "Gametype"  Set to Narrative (under the Narrative box" "Narrative Narrative"

Add a Techmarine
And add a Captain to from HQ

Techmarine can be Custom character but the Captain can't

Other HQ options that can't be Custom but should are: 
Librarian, Normal, Primaris, Terminator & Phobos
Captain, Normal, Primaris, Terminator, "On Bike" & Phobos
Lieutenant, Normal, Primaris & Phobos

**Comment by Mad-Spy** [comment]
The Custom Character code was removed before the SM split to improve performance. It has not yet been added back in to the individual Chapter catalogues.

The Techmarine must just have been missed when it was removed.

**Comment by acebaur** [comment]
Also at this point I am waiting for 9th before adding in anything for narrative.
