### ISSUE TITLE
Imperium - Space Wolves - Njal Stormcaller constraint error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#733]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** When creating a Space Wolves, it is generating an error stating that  I have too many selections of Njal Stormcaller (maximum 0)

I only have one in my force, I am generating a Battalion detachment.

**Comment by ilaunchbury** [comment]
I'm unable to replicate this in the latest Space Wolves catalogue, v5. Please make sure you have the latest data and try again.
