### ISSUE TITLE
CSM Hellbrute Missing combi bolter or heavy flamer

### ISSUE THREAD

**Issue by maedrosimirdan** [BSData/wh40k#740]
**File/Catalogue:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** Index: Chaos - Helbrute on page 33. "This model may incorporate a combi-bolter or heavy flamer into each Helbrute fist." The option is not available on either Helbrute fist.

**Comment by GenWilhelm** [comment]
It's right there on the fist:

![helbrute](https://user-images.githubusercontent.com/22036809/27997038-23b68f5c-64e7-11e7-8951-aaff3532e87c.png)
