### ISSUE TITLE
Necrons - Warriors need Reanimation Protocols reanimating

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#745]
**File:** Necrons.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** When viewing/printing Roster the Necron warriors units do not display the Nme ability "Reanimation protocols", despite it is shown in the individual information before printing.
The rest of units that have this ability, show the Name of the abbility (the description is at the end) but not in Warriors, as they don?t have it

**Comment by Kohato** [comment]
It's there. It's a battlescribe bug that has to do with 0 cost wargear (if a model has it, it doesnt' show things for some reason)

**Comment by Kohato** [comment]
I've brought up the bug to the developer.
