### ISSUE TITLE
Imperium - Astra Militarum - Platoon commander missing profile

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#757]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Platoon commander doesnt show his statistics ws bs and everything just his equipment,
Tempestus command squad says it cannot be selexted because maximum is 0

**Comment by alphalas** [comment]
You need to take a tempestor for the command squad.
