### ISSUE TITLE
Imperium - FW Death Korps of Krieg V2 - points cost errors/unit size errors

### ISSUE THREAD

**Issue by jShepherddog** [BSData/wh40k#760]
**File/Catalogue:** 

**BattleScribe version:** v2.01.03.90

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
**Death Korps Grenadier Squad** 
- the Hot-shot Lasgun is set to (no Cost), it should be 1 point 
![image](https://user-images.githubusercontent.com/30080443/28077971-4589bafa-6631-11e7-83aa-d53f546b264a.png)

**Death Korps Infantry Squad** 
- the DK Guardsman w/Special Weapon is set to start at 4 points, This should be 5 points.
- a warning is thrown for having 1 too many selections of Death Korps Watch Master (Maximun 0) - the Maximun should be set to 1
![image](https://user-images.githubusercontent.com/30080443/28077884-0a156ec4-6631-11e7-9874-ddc8e10a3639.png)

**Death Korps of Krieg Command Squad** 
As there can only be 4 veterans in the unit (no more/no less), wargear options should only be added to Command Squad Veterans, IE Standard Bearer should be a wargear option for a single Command Squad Veteran, should not be adding another standard bear model as this brings the unit over the Max 4 models and there is no way for the points to add up correctly or work around this if you want to add a standard bearer.
![image](https://user-images.githubusercontent.com/30080443/28077834-d8848cbe-6630-11e7-8bd2-bdf30ccc3fbd.png)

**Death Korps Quartermaster Cadre**
-Quartermaster is spelt Quartertmaster incorrectly
-The option to add Death Korps Medicae-servitor is listed as (no Cost) this should be 2 points
![image](https://user-images.githubusercontent.com/30080443/28077759-9f82093c-6630-11e7-9526-365aaa062059.png)

**Comment by Zeshi91** [comment]
Errors:
**DKoK Marshal** 
- Missing 'Momento Mori' Upgrade

Points Costs Errors:

**DKoK Death Rider Squadron Commander**
- Hunting Lance listed with (No cost) but should cost 2 pts.

**Heavy Mortar Battery**
- Heavy mortar listed with 65 points/piece but it costs only 60 points

Spelling Error:

Rapier and not Raiper Laser Destroyer 

Suggestions:

**Centaur Light Assault Vehicle**
- it is always equipped with 2 Heavy Stubber, maybe equip them automatically and make the hunter missile a tick box?

**Death Rider Squadron**
- Death Riders can´t change their hunting lance, maybe equip them automatically?

Keep up the good work!

**Comment by alphalas** [comment]
@jShepherddog for your third point - you remove a regular veteran.

**Comment by Zeshi91** [comment]
BS will still throw an error because the special veterans are not classified as command squad veterans.

**Comment by jShepherddog** [comment]
@alphalas If I remove the regular veteran, The points will not add up correctly as the Standard Bearer entry doesn't include the base 7 points cost for the veteran. It only counts the 5 points for the banner.  Also, BS throws a error because the standard bearer is not classified as command squad veterans as @Zeshi91 mentioned is the same issue with the special weapon veterans. Thanks for looking into this!

**Comment by alphalas** [comment]
Ah ok I see. Sorry lol
