### ISSUE TITLE
Aeldari - Craftworlds - Eldar Nightwing missing Crystal Targeting Matrix

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#761]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** The eldar nightwing is listed as 140 points and is not listed as having a Crystal targeting matrix. Per imperial armour index xenos p. 68 it should have a crystal targeting matrix and cost 145 points.

**Comment by FarseerVeraenthis** [comment]
yup, seems to be missing, I'll get to it :smile:
