### ISSUE TITLE
Chaos - Thousand Sons - Smoke Launcher points to Twin Heavy Bolter instead of Smoke Launcher

### ISSUE THREAD

**Issue by Anthony2017** [BSData/wh40k#763]
**File/Catalogue:** Chaos - Thousand Sons

**BattleScribe version:** 2.01.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** The view selection for Rhino shows Twin Heavy Bolter instead of Smoke Launcher.  The Data Editor shows the Shared Selection Entries --> Smoke Launchers as having a Twin Heavy Bolter instead of a Smoke Launcher.

**Comment by ilaunchbury** [comment]
Fixed in https://github.com/Anthony2017/wh40k/commit/f1ad200c67d93da97c88d89d87220a2ea9cd4a11
