### ISSUE TITLE
Imperium - FW Death Korps death rider Squadron Commander missing demo charges

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k#766]
**File/Catalogue:** 
IMPERIUM- FW Death Korps of krieg v2

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** na

**Description:** the death Korps death rider Squadron commander is missing the option for demo charges.

**Comment by CrusherJoe** [comment]
Fixed in v4 of DKOK catalog file.
