### ISSUE TITLE
Imperium FW Death Korps Death Rider Ridermasters and officer free lances

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k#767]
**File/Catalogue:** 
IMPERIUM- FW Death Korps of Krieg v2
**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes/No

**Description** the ridemaster and squadron commander have no cost for their hunting lances. It should be 2 points.

**Comment by CrusherJoe** [comment]
This should be addressed in the v3 release of the catalog.
