### ISSUE TITLE
FW Death Korps of Krieg problem

### ISSUE THREAD

**Issue by DeathKorps** [BSData/wh40k#770]
**Imperium-FW Death Korps of Krieg**

**BattleScribe version:** 2.01.

**Platform:** Android

**Description** App will always say "Death Korps Infantry Squad has 1 too many selections of Death Korps Watch Master (maximum 0)"

**Comment by GenWilhelm** [comment]
Fixed in e6f60c4cce32f24c91262db8e6fc170d620eaafd (Death Korps v3).
Should be released tonight.
