### ISSUE TITLE
Tyranids V9 - Sporocyts

### ISSUE THREAD

**Issue by nOograss** [BSData/wh40k#771]
**File/Catalogue:** Tyranids V9

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** 

**Description:** Although the unit 'SPOROCYT' is in the file, it is not visible in the heavy unit section.

**Comment by GenWilhelm** [comment]
It's a fortification, rather than a heavy support, so make sure you're using a detachment that has access to fortifications.

**Comment by nOograss** [comment]
Thank you
