### ISSUE TITLE
Chaos - Chaos Space Marines - Helbrute options missing on Mobile?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#774]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Helbrute does not currently have options for integrated combi-bolter or heavy flamer for Helbrute fists.

"This model may incorporate a combi-bolter or heavy flamers into each Helbrute fist."

Need to be added to "Helbrute Fist options":
Helbrute fist w/ combi-bolter (42 points)
Helbrute fist w/ heavy flamer (57 points)

Need to be added to "Multi-melta options":
Helbrute fist w/ combi-bolter (42 points)
Helbrute fist w/ heavy flamer (57 points)

**Comment by darkscion0** [comment]
Note that these options are available in the windows application but not on mobile/tablet.

**Comment by ilaunchbury** [comment]
I'm unable to replicate this in the Android app using CSM v10.. I can add ranged weapons to either or both Helbrute fists.
