### ISSUE TITLE
Imperium (all sub sets)

### ISSUE THREAD

**Issue by rsochia** [BSData/wh40k#783]
You can build a detachment using the faction keyword imperium. This allows you to take anything in imperium index 1 and 2 in a single detachment. I do not see how this option is implemented in the forces option.

Basically a this time I am adding an inquisitor to my space marine detachment, but you can in theory have any imperium faction keyword in the same detachment.

**Comment by Zeshi91** [comment]
![testestest](https://user-images.githubusercontent.com/30057221/28150039-4080ccb2-6792-11e7-8d40-231bdd1ba0a0.PNG)

You can. Click on the first army and then add a second entry. The second entry will contribute to the total detachment.

**Comment by alphalas** [comment]
Trust me, you don't want an all Imperium Cat; for the simple reason it will be so massive it will not load. The way it is implemented now is the best way to make it work with the limitations of BattleScribe
