### ISSUE TITLE
Chaos Daemons - Daemon Prince of Chaos Wounds charateristics

### ISSUE THREAD

**Issue by Olsen370** [BSData/wh40k#789]
**File/Catalogue:** Chaos - Daemons.cat

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Wound characteristic for Daemon Prince of Chaos has to be "8" instead of "10". Daemon Prince of Chaos with wings has the correct Wounds characteristic. See Chaos-FAQ: 
"Page 105 – Daemon Prince of Chaos, profile line
Change the Wounds characteristic to read ‘8’."

**Comment by GenWilhelm** [comment]
FAQ was implemented today. It should be released tonight.
