### ISSUE TITLE
Imperium - Space Wolves - Thunderwolf missing Wolf Claw option

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#796]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Spaces Wolves - Thunderwolf Calvary - Add wolf claw to options to replace bolt pistol.

**Comment by penguin20000** [comment]
Dupe of #712 :)
