### ISSUE TITLE
Imperium - FW Death Korps of Krieg v5 - Pricing Error

### ISSUE THREAD

**Issue by Zeshi91** [BSData/wh40k#801]
**File/Catalogue:**  Imperium - FW Death Korps of Krieg v5

**BattleScribe version:** 2.01.03

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 

Death Rider Command Squad has only 1 Hunting Lance listed right now (total 62 points) but every rider has one and the price should be 68 points.

Some minor reversed letters that could be ignored:

Rapier Laser Destroyer: the weapon itself is mentioned as 'Raiper'

Death Rider Squadron: Kreig steed instead of Krieg Steed

Thank you.

**Comment by CrusherJoe** [comment]
Okay...I think I finally have the Death Riders all sorted out, as well as the spelling corrections. Should be consistently correct now.
