### ISSUE TITLE
Imperium - FW Adeptus Astartes - Relic Validation bugged

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#802]
**File:** Imperium - FW Adeptus Astartes.catz

**BattleScribe version:** 1.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** The data isn't recognising unit types from other factions (such as normal non-FW Astartes) to validate the Relic rule. Selecting a relic unit will show the whole detachment as invalid unless you have another FW Astartes unit of the same type (Elites, heavy support etc.) so in my example I am trying to add a Relic Leviathan Dread alongside my Land raider crusader (both heavy support)

Also selecting 2 of the same gun on a Relic Leviathan Dreadnought doesn't double the points cost (e.g. 2 x Grav Bombard Cannon only calculates 50pts rather than 100)

Thanks and keep up the good work!

**Comment by Crowbar90** [comment]
Please check that FW Adeptus Astartes is the parent force, rather than the child force. Unfortunately, validation only works if FW Adeptus Astartes is the parent force, you can check the wiki for more info. https://github.com/BSData/wh40k/wiki/Using-FW-Relic-units

**Comment by Crowbar90** [comment]
I just checked the weapons cost issue, it works correctly. Please make sure you have the latest version of the files.
