### ISSUE TITLE
Imperium- FW Death Korps of Krieg Death Rider Command Squad not charging for lances

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k#805]
**File/Catalogue:** 
Imperium- Death Korps of Krieg v5

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** The Death Korps Death Rider Command Squadron is charging for a single lance for 4 riders. 2 points a lance should be 8 total. Charging only 2. Squad should be 68 points. Coming up as only 62.

**Comment by CrusherJoe** [comment]
This has been corrected in v6 of the cat. It will be in the next release.
