### ISSUE TITLE
Aeldari - Drukhari - Grotesque w/ weapon of torture missing second weapon

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#808]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Grotesque with Weapons of Torture

In current version the model replaces both Melee Weapons with one Weapon of Torture.
Rules say the model replaces one Melee Weapon with one Weapon of Torture.

That means the remaining Melee Weapon and its costs are missing.

**Comment by Toreador13** [comment]
Fixed in V12
