### ISSUE TITLE
FW - Heretic Astartes Update [Sonic Dreadnought]

### ISSUE THREAD

**Issue by Guardbuddy** [BSData/wh40k#809]
**File/Catalogue:** Chaos Heretic Astartes? Might be Chaos Space Marines?

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Detailed issue description: FW's latest FAQ clarified that the Emperor's Children Legion can take Sonic Dreadnoughts by using the Helbrute template and replacing its multi-melta with dual blastmasters as well as an optional doom siren.  I am not entirely sure if the unit needs an entirely separate unit entry under FW Heretic Astartes or to be added under the existing Helbrute weapon options.

**Comment by GenWilhelm** [comment]
In my opinion it should be in the FW catalogue, since it was a Forge World model and it's rules are from the Imperial Armour FAQ.

**Comment by ilaunchbury** [comment]
I've rolled this issue into the other FAQ updates under #810 as there are other units that need to be added.
