### ISSUE TITLE
Orks - Where are the Grot Tanks??

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#826]
**File:** Orks.catz

**BattleScribe version:** 2.00.34

**Platform:** Android

**Dropbox:** No

**Description:** Where are The grot tanks? I cant find them on BS....

**Comment by GenWilhelm** [comment]
Grot Tanks are currently hidden until you have a Big Mek in the same detachment.

Perhaps this should be handled with a constraint, rather than show/hide, as per the guidelines?

**Comment by tag8833** [comment]
I didn't realize that was part of the guidelines.  I'll get it updated.
