### ISSUE TITLE
Chaos - FW Renegade and Heretics - Mutant Rabbles giving strange validation error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#831]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Getting a weird error on Renegade Mutant Rabbles which I can't work out how to clear.
"All renegade Mutant Rabbles must have the same number of selections from Mutant Weapons"

This doesn't seem to be to do with taking the same number of weapons as there are models in the unit (which is a separate error, working correctly). What is it?

**Comment by Penallegion** [comment]
removed collective from weapon choice
