### ISSUE TITLE
Imperium - Grey Knights - Dreadknight profile missing some stats?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#839]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Hi there

For the Grey Knights, the Dreadknights is missing a movement numbers and a ballistic skill number, they are both right now shown as a *

Sorry if this isnt the correct place/way to do it.

**Comment by FarseerVeraenthis** [comment]
there should be a "Wound Track" table to replicate the table shown on the datasheet

**Comment by tekton** [comment]
That's weird, I did do that...wonder if it's the same as another bug I had. Will check when I get back to my desk.

**Comment by tekton** [comment]
The wound table is already there underneath things

![dreadknight_wound_table](https://user-images.githubusercontent.com/137810/28288514-48090ad4-6af4-11e7-964b-e8d140b77642.png)
