### ISSUE TITLE
Space Wolves

### ISSUE THREAD

**Issue by Speri777** [BSData/wh40k#8474]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

- [x] Cyclone Missile launcher free for terminator in long fang squad

- [ ] Warlord trait and relics for wolf lord on thunderwolf N/A

- [x] Wolf lord on thunderwolf doesnt have advance and charge, neither does normal TWC. They have reroll charges. I could be wrong with this but i thought they gained advanced and charge.

 - [x] Many units including primaris captain have the 'headstrong' ability (not sure if this is incorrect or not just seemed odd) but a lot of units have this when only bloodclaws had it before

**Comment by Technoblazed** [comment]
Can't replicate WLoT not showing traits/relics, make sure you have him as your warlord and/or in your roster.
