### ISSUE TITLE
Imperium - Dark Angels - Libby doesn't know SMITE?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#854]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.03

**Platform:** Mac

**Dropbox:** No

**Description:** Dark Angels Librarians don't seem to have SMITE -power. I understood it was for everyone. I really could be wrong.

**Comment by ilaunchbury** [comment]
All Librarians should know Smite. DA Libbys know Smite + 2 powers from Interromancy, so Smite needs to be added to their profile.

Also, Interromancy is misspelled in the cat; it should have 2 r's.
