### ISSUE TITLE
Tyranid - Genestealer - Point Cost

### ISSUE THREAD

**Issue by elodingens** [BSData/wh40k#855]
**File/Catalogue:** 
Tyranid

**BattleScribe version:**
2.01.05

**Platform:** 
Android (other maybe effected)

**Dropbox:** 
No

**Description:** 
- Genestealers are 10 points per Modell, see Index: Xenos 2 Page 56
- So Default Unit should be 50 Points (current 60 Points) and every Modell more should be 10 Points (current 12 Points)

**Comment by GenWilhelm** [comment]
Genestealers are 10ppm without any wargear. However, every genestealer must take rending claws, which are 2pts each. Therefore, each genestealer costs 12pts after it pays for wargear.
