### ISSUE TITLE
Chaos - Daemons: Plaguebearers have incorrect rule

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#858]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Under plague bearers, it says if you take a morale check and roll a 1, you get d6 bloodletters.

**Comment by ilaunchbury** [comment]
What version of the Chaos Daemons catalogue is this in? I can't replicate it in V10.

**Comment by ilaunchbury** [comment]
Unable to reproduce in current version.
