### ISSUE TITLE
Chaos - Daemons: Plague Drones have incorrect weapon strength

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#859]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Under plague drones, deaths head says you get strength 44.

**Comment by ilaunchbury** [comment]
What version of the Chaos - Daemons catalogue do you have? I cannot replicate this in v10.
