### ISSUE TITLE
Chaos - Heretic Astartes - Berzerkers can take a chainsword AND a chainaxe! 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#860]
Hello,

Last update changed the mechanics for selecting gear on Khorne Berzerkers.

It should be possible to equip a chainsword AND a chainaxe (by replacing bolt Pistol), latest update does not allow this. 

![img_2014](https://user-images.githubusercontent.com/16340056/28328445-99ba534a-6bb4-11e7-8dfa-7803552dcef9.PNG)
![img_2015](https://user-images.githubusercontent.com/16340056/28328446-99bc87d2-6bb4-11e7-8e16-234e35276f6c.PNG)

**Comment by ilaunchbury** [comment]
I don't see why you would want to any more, but fixed anyway :)

**Comment by Drachnyen** [comment]
Easy choice:   They have 2 attack base with chainaxe (S6) + one extra attack for chainsword (S5), factor this twice since they attack 2x in the fight phase and you can literally attack 4 times in a single turn!  You get much more mileage with axe+Sword than keeping the puny bolter :)

A unit of 10 Berzerkers generate 31 attacks per fight phase, for a whopping 62 attacks per round.

**Comment by Drachnyen** [comment]
And... thanks a lot for the quick fixes, much appreciated :)
