### ISSUE TITLE
Space wolves

### ISSUE THREAD

**Issue by Speri777** [BSData/wh40k#8628]
Warhammer 40,000 x9.1.1 - Space Wolves

**BattleScribe version:** 2.03.

**Platform:** Windows

**Dropbox:** Yes/No

Landspeeders can only take heavy bolter or multi melta no option for second weapon e.g. missiles

wolf lord on thunderwolf thunderhammer points are incorrect. At the moment it's 20 points in Battlescribe it's 40 points (according to https://www.warhammer-community.com/wp-content/uploads/2020/10/GamaHDmpGRQShG3u.pdf)

Thankyou!

**Comment by Valorcalls** [comment]
The entry for Land Speeder can only take 1 gun.

**Comment by Mad-Spy** [comment]
As per Valor's comment, the Landspeeders are implemented as per their datasheets.

The Wolf Lord's TH is fixed in the next release.

**Comment by Speri777** [comment]
Thanks for your help guys
