### ISSUE TITLE
Separation of FW from Space Marines preventing force org options

### ISSUE THREAD

**Issue by lebowski89** [BSData/wh40k#864]
**File/Catalogue:** Imperium - Space Marines.cat / Imperium - FW Adeptus Astartes.cat

**BattleScribe version:** 2.01.03.90

**Platform:** All

**Dropbox:** No

**Description:** Is there a reason FW Adeptus Astartes units are in their own cat? It's preventing me from adding them to the same detachment as Space Marines cat units, unless I'm missing something?

**Comment by Zeshi91** [comment]
New Roster -> add the cat space marines -> click on the now new cat space marines -> add the fw space marine cat. done.

**Comment by lebowski89** [comment]
Aha! Thank you, thought I must have been missing something.
