### ISSUE TITLE
Chaos - Chaos Space Marines - CSMs should be able to take heavy weapon at 5 models.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#865]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Space Marines: It creates are warning when choose a Marine with a heavy weapon when the unit only has 5 models (even it is legal ruleswise).

**Comment by ilaunchbury** [comment]
Yep! Completely misread that line and made things more complicated than they needed to be.

They can now have a heavy/special OR a plasma at any valid number of models, plus an extra heavy/special at 10+.
