### ISSUE TITLE
Chaos - Chaos Space Marines - Berzerkers weapon choice

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#866]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Khorne Berzerkers cannot choose to be armed with Chain Axes and Chainswords, however this is a viable option as per the data sheet. The only option you have is Chain axe/Bolt Pistol, or Chainsword/Bolt Pistol. It's missing Chainaxe/Chainsword. 
Thanks for your great work though - Keep it up!

**Comment by ilaunchbury** [comment]
Thanks for your report. This issue has already been fixed and will be in the next release.
