### ISSUE TITLE
Magnus the red not in thousand sons

### ISSUE THREAD

**Issue by Audiopunk** [BSData/wh40k#875]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by GenWilhelm** [comment]
He's a Lord of War. Have you included a detachment that allows a Lord of War?

**Comment by Audiopunk** [comment]
Ooooo jebus... Am I really that dumb?

**Comment by ilaunchbury** [comment]
He's definitely available as a LoW.
