### ISSUE TITLE
Chaos - Thousand Sons: a few issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#881]
**File:** Chaos - Thousand Sons.catz

**BattleScribe version:** 2.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** 

- The Sorcerer in Terminator Armour can't select Psi-Skills; 
- Point value of the warpflamer hast to be 15 instead of 13 points; 
- The soulreaper cannon has no point value and has to be 20

**Comment by ilaunchbury** [comment]
Actually no Sorcerers had the psychic power options.
