### ISSUE TITLE
Imperium - FW Death Korps of Krieg - Please include Errata updates

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#882]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** The Index has received an Errata document whose contents need to be added to this force, this includes Grenadier Weapons Teams with Heavy Flamers, mandatory 2x Lasgun Arrays on the Storm Chimera, mandatory Autocannon on the Storm Chimera, and the Armour upgrade for the Storm Chimera being a 10-point option.

Also, the Heavy Bolter weapon option should be costed at 8 points, not 10.

**Comment by jShepherddog** [comment]
adding it here Since its part of the new FAQ. The Death Korps Heavy Weapon Team has no option for a Twin Heavy Stubber. Thanks for keeping this up to date!

**Comment by alphalas** [comment]
Should all be fixed in the next release.
