### ISSUE TITLE
Imperium FW Elysians- Special Weapons Squad Size Issues

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k#891]
**File/Catalogue:** 
Imperium FW Elysians v4
**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes/No

**Description:** Detailed issue description.
Elysian Special Weapon Squad- Consists of 6 guardsme, 3 with special weapons. Right now, BS is only indicating and charging for 3 with special weapons and not the 3 regular guardsmen

**Comment by alphalas** [comment]
i'm not seeing it - charges the proper 30pts per squad base.
