### ISSUE TITLE
Imperium- FW Elysians Imperial Armour Errata

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k#893]
**File/Catalogue:** 
Imperium- FW Elysians v4

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes/No

**Description:** 
Tauros gains the Aerial Drop Special Rule
Elysian Ranged Weapons option for all characters/sarges needs boltgun added (1 point) (except on Drop Troop Squad)
Breacher charges are 1 use only

**Comment by alphalas** [comment]
This all will be in the next release
