### ISSUE TITLE
Blood angels assault sgt

### ISSUE THREAD

**Issue by f1r3warr10r** [BSData/wh40k#900]
**File/Catalogue:** When I try to choose warhead for a blood angels assault squad but I only get eviscerator and/or that shield. No drop to various power weaps and pistols.

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Crowbar90** [comment]
Leave regular wargear selected, then under "Regular wargear" you can choose
whatever you want.

Il ven 21 lug 2017, 05:41 f1r3warr10r <notifications@github.com> ha scritto:

**Comment by f1r3warr10r** [comment]
Thanks
