### ISSUE TITLE
Chaos - Death Guard: Incorrect cost for Noxious Blightbringer

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#901]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** Yes

**Description:** Noxious Blightbringer is listed as an 80pt model, but is a 73pt model

**Comment by ilaunchbury** [comment]
The model is 73 pts _without wargear_, its plasma pistol is 7 pts. 80 points total.
