### ISSUE TITLE
Deathwatch Castellan of the Black Vault not recognizing extra relic properly

### ISSUE THREAD

**Issue by asdf2134** [BSData/wh40k#9013]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

![image](https://user-images.githubusercontent.com/73708488/101812218-12ac3a00-3ae9-11eb-8588-f83f34e253b7.png)

![image](https://user-images.githubusercontent.com/73708488/101812358-3e2f2480-3ae9-11eb-9d68-c1162442f70c.png)

Here I have a Primaris Chaplain on bike. I give him 'benediction of fury' (relic 1), and make him my warlord. I pay 1CP for 'A Vigil Unmatched' to give him an extra warlord trait. I give him 'The Imperium's Sword' and 'Castellan of the Black Vault'. CotBV allows me an extra relic, one of a set of 3, and they must be unique. So of those 3 I choose 'digital weapons' (relic 2). I believe this follows the rules as described.

But now I have the error that I simultaneously have too many and too few relics lol. I'm sure this is just an edge case for BS to handle, though if I've made an error in the above then let me know. Thanks!

**Comment by Valorcalls** [comment]
You have to pick the 2nd relic inside of the warlord trait, not in the default list.

**Comment by asdf2134** [comment]
I don't understand, I only see sections for Chapter Relics and Warlord Traits, not one within the other. 

![image](https://user-images.githubusercontent.com/73708488/101813097-48055780-3aea-11eb-96cf-bd8240a62dc6.png)
![image](https://user-images.githubusercontent.com/73708488/101813137-55badd00-3aea-11eb-9823-17405c447ca9.png)

**Comment by Valorcalls** [comment]
Click on the error for Castellan of the black vault to open it and select the relic

**Comment by asdf2134** [comment]
Oh perfect thank you! Didn't know it worked like that. Can close issue.
