### ISSUE TITLE
Chaos - Heretic Astartes - printing issues with Berzerkers 

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#902]
Hello,

This is more of a feature request, here is the issue :  
Berzerkers tend to be used in high numbers, the current unit creation mechanism allow for individual customization for each Berzerker, leading to lines after lines of the same information displayed.  This has 2 adverse effects:
1) on the army roster it's hard to quickly see how many zerkers are fielded (you need to count each line individually)
2) trying to print the army roster creates some issues as the entry is very long (creates strange page breaks)

Example : 

![img_2028](https://user-images.githubusercontent.com/16340056/28462780-d1f90e62-6dea-11e7-98f0-ba8ed50378e5.PNG)

Suggested solution:
Since Berzerkers only have 3 permutations, maybe use those 3 explicitly instead of allowing for full customization mechanism

Permutations are 
1. Bolt Pistol + chainsword
2. Bolt Pistol + chain axe
3. Chainsword + Chain axe

This is purely cosmetic, there might be other ways to fix this, thank you for your considerations

**Comment by ilaunchbury** [comment]
You're right,, it probably could do with tidying up.

As you can only take 2 plasma pistols, I'll leave them as they are now.

**Comment by Drachnyen** [comment]
Thanks guys 🥇
