### ISSUE TITLE
Imperium - Sisters of Silence - Weapon cost not incrementing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#903]
**File:** Imperium - Sisters of Silence.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When you add more than 5 Witchseekers, it's not adding the additional 9pts for the flamers

**Comment by ilaunchbury** [comment]
This sounds like the known bug with Battlescribe where weapon costs do not increment for child forces. Try adding your detachment at the top level.

**Comment by alphalas** [comment]
it's definitely not a data issue.
