### ISSUE TITLE
Imperium - Dark Angels - Devastators with heavy weapons don't charge for the model

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#907]
**File/Catalogue:** Dark Angels v17

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** The models in the "Heavy Weapons" section of the Devastator's Space Marines group should cost 13pts each before charging for their heavy weapon.

**Comment by ilaunchbury** [comment]
test
