### ISSUE TITLE
Chaos: Renegades & Heretics Index - Renegade Militia & Renegade Disciples

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k#909]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** The format for creating this unit is confusing.  eg: When selecting a special weapon, validation still requires 9 lasrifles for 9 militia, the squad actually has 8 lasrifles and 1 special weapon.  Another example is that adding a special weapon team doesn't seem to reduce the number of regular militia in your squad, when a special weapon team should replace 2 regular militia.  

Suggestion: Change to work like the Astra Militarium Infantry Squad.  It seems to work correctly.

Note: I included both renegade militia and renegade disciples, because one is just the elite version of the same unit.  They build the same.

**Comment by spesselves** [comment]
Additionally Disciple weapons teams show up as WS and BS 5+, but they are 3+ just like all other Disciples models.

**Comment by Penallegion** [comment]
Should be done now, waiting for pull request to come through
