### ISSUE TITLE
Astra Militarum - Infantry Squad

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k#910]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** When adding a heavy weapon team to the squad, the validation error says "Infantry Squad has 1 too many selections from Guardsmen (maximum 8)."  The number should actually be 7.  Changing the value of Guardsmen to 7 DOES remove the error, not 8.

**Comment by alphalas** [comment]
That's obviously a BS bug if having 7 removes the error.

**Comment by Wyvern350** [comment]
But the validation error tooltip is still wrong.  Are you saying that's an error in Battlescribe on the backend?

**Comment by alphalas** [comment]
yes.

**Comment by alphalas** [comment]
Because if having the correct number of models removes the error tooltip, obviously the constraint is working as intended.
