### ISSUE TITLE
Tyranids - Genestealer Cults: Points cost incorrect for Neophyte Heavy Weapons Team

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#914]
**File:** Tyranids - Genestealer Cults.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Genestealer Cults neophytes heavy weapon team cost's 5 points base instead of 10. It should be the cost of two neophytes.

**Comment by GenWilhelm** [comment]
A Neophyte Hybrid unit costs 5 points per model in the unit. A weapons team is a single model, ergo it increases the cost of the unit by 5 points.
