### ISSUE TITLE
Imperium - Astra Militarum: unable to switch weapons on units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#918]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** I can't edit the weapons of units which are able to equip different weapons (such as Lord Commissars, non-conscript guardsmen, scions, all vehicles, etc.) which renders this useless for making an army list for matched play.

Select any unit which, in the index, is listed as being able to equip different weapons from their default equipped weapons (selecting them on battlescribe), and you'll notice that there is no way for them to equip a different weapon. Sure, for casual play using power levels, this isn't an issue, but, for matched play, where you need to calculate points costs carefully, with each weapon having different points costs, this is useless.

Please fix.

**Comment by ilaunchbury** [comment]
These all seem to be working for me in the Windows Roster Builder? See below a Lord Commissar with Power Axe and Plasma pistol.

![image](https://user-images.githubusercontent.com/29306451/28492353-799730c2-6ef9-11e7-9610-c60339a14687.png)

Can you provide a screenshot showing the problem?

**Comment by GenWilhelm** [comment]
There's a bug in BattleScribe at the moment where the right panel starts completely collapsed. If you can't see any option for the current selection, you need to drag the rightmost column out to the left.

![rightmost](https://user-images.githubusercontent.com/22036809/28492455-392d96d6-6efc-11e7-8584-26a5d67b8d6d.png)
