### ISSUE TITLE
Imperium - FW Death Korps of Krieg - Karis Venner / Death Rider Command / Combat Engineers

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#923]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** 1) Karis Venner needs to cost 10 more points for his Momento Mori.  He also should come stock with the hot shot laspistol as its obligatory wargear.

2) Death Rider Command Squadron should be locked wargear as it has no options.

**Comment by jigoralpsi** [comment]
Additional: Krieg Combat Engineers should be able to have a maximum of 9 engineers with shotguns, instead of 7. Currently, when trying to make a 10-man squad, the tenth man throws an error for too many men.

**Comment by Rottenflieger** [comment]
Additional: Heavy Bolters are incorrectly listed as 10 points across the whole Death Korps list, when the index lists them as 8.

**Comment by GenericCola** [comment]
Just a question about this-- Karis Venner doesn't say he is equipped with a Momento Mori in his data sheet... it is instead listed as a special rule called "Momento Mori."

What is the precedent for making the assumption that this is actually a piece of wargear?
