### ISSUE TITLE
Files gone from BattleScribe and AppSpot

### ISSUE THREAD

**Issue by Summer-Fox** [BSData/wh40k#929]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** I recently started using BattleScribe, and successfully downloaded the 40k 8th edition files through the BattleScribe Data Editor. However, today, I went to update the files and received several error messages. I deleted my local files and tried to download the 8th edition catalogue again, but it has disappeared from the list of available data repositories. Poking around online, it is also gone from the BattleScribe Data Files AppSpot web-page. The other GW games, Frostgrave, Warmachine, and the others are all still there. 8th edition seems to be the only missing game as far as I can tell. Can anyone else access the 8th edition files through these methods, or explain why it's been taken down?

![battlescribe appspot ss](https://user-images.githubusercontent.com/30395105/28504095-af7be8fa-6fde-11e7-89f5-046cd796ade6.jpg)

**Comment by alphalas** [comment]
We're not even sure why things fall off of appspot like this – just give it a day or two and it should come back up.

**Comment by alphalas** [comment]
as to how to get them in the interim: https://github.com/BSData/wh40k-7th-edition/issues/3823

**Comment by Summer-Fox** [comment]
Ha, thanks! You're the best. I really appreciate your assistance. I'm one-hundred percent new to GitHub, so this guide is incredibly helpful.

**Comment by ilaunchbury** [comment]
Files are back on Appspot now.
