### ISSUE TITLE
Chaos - Chaos Space Marines - Heavy Weapon Terminator missing CC Weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#936]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Terminator with Heavy Weapon option is missing option to swap out close combat weapons.

**Comment by ilaunchbury** [comment]
This is fixed in v17 of the Chaos Space Marine catalogue, which is in 1.0.38 which just released.
