### ISSUE TITLE
Chaos - Heretic Astartes - Chaos units forced to take a Mark of Chaos

### ISSUE THREAD

**Issue by Drachnyen** [BSData/wh40k#937]
Hello!

The last update forces sorcerers to take a mark of Chaos or an error is generated.
Taking a mark of chaos is optional and should not be mandatory. 
Note: The army is built using Black Legion force org

Thanks in advance,

**Comment by Drachnyen** [comment]
Update!  Basically all generic HQs are affected by this : Dark Apostle, Chaos Lords and Warpsmith

**Comment by ilaunchbury** [comment]
You can choose to have "No Mark of Chaos" in the list of Marks. Doing it this way improves the visibility of Icons for those units which can take them and means you can't forget to have that option where possible.

**Comment by Drachnyen** [comment]
Ah!  Didn't notice this change.

Is it possible to default to No chaos Mark instead of "none"? 

![img_2042](https://user-images.githubusercontent.com/16340056/28542997-50f67332-708c-11e7-8791-b88d5d68fde4.PNG)

**Comment by ilaunchbury** [comment]
I wish it was but it breaks the functionality to hide invalid marks when selecting World Eaters or Emperor's Children. When the Codex gets released, it will probably be sensible to split them out into separate catalogues, at which point this can be improved.

**Comment by Drachnyen** [comment]
Alright no biggie 
Also loving the new berzerker profiles, thanks :)
Thanks a lot for your help on the CSM catalogue.
