### ISSUE TITLE
Imperium - FW Adeptus Astartes Missing MALAKIM PHOROS

### ISSUE THREAD

**Issue by Shangzilla** [BSData/wh40k#941]
**File/Catalogue: Imperium - FW Adeptus Astartes.cat** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** HQ MALAKIM PHOROS is missing from HQ choices

**Comment by ilaunchbury** [comment]
He's in the catalogue but is missing a Primary Category.
