### ISSUE TITLE
Sergeant Chronus Missing Whirlwind Option

### ISSUE THREAD

**Issue by Summer-Fox** [BSData/wh40k#942]
**File/Catalogue:** Space Marines v18

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** In the "Index Imperium 1" book, on page 70, it says that Sergeant Chronus can be an upgrade for a Whirlwind tank. However, when selecting him in the BattleScribe roster, the Whirlwind is not listed as an option.

**Comment by flakpanda** [comment]
The fix will be released this weekend. There is a lot of prep work done on the catalog already from the leaks.

**Comment by FarseerVeraenthis** [comment]
This appears to have been fixed, he definitely has the option in version 27!!
