### ISSUE TITLE
Imperium - Dark Angels - Devastator upgrades don't include cost of Marine

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#943]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** When I create a Dark Angels devastator squad, the cost of the weapon (eg. Lascannon 25 points) is adding to the squad, but counts also as a marine. The cost of the marine is not taken into effect. So, to make a full 10-man devastator squad you have a sergeant, 9x marines, and your 4 heavy weapon options. The unit entry then says you have a sergeant and 13x marines. You then get a roster error that says there are too many marines in the unit. If the weapon upgrade is going to count as a marine, the cost of the marine should be added to the weapon (+13), like it is in the tactical squads when you add a heavy or special weapon. A Lascannon marine should cost 38 points, not 25.

**Comment by ilaunchbury** [comment]
This has already been raised in #907 and will be fixed soon.
