### ISSUE TITLE
Imperium - Space Marines: Company Veteran on Bike Weapon option 

### ISSUE THREAD

**Issue by DaniBisi** [BSData/wh40k#946]
File/Catalogue: Space Marines v18

BattleScribe version: 2.01.

Platform: Linux/

Company Veterans on Bikes can't take plasma-gun and combi-Plasma but currently the can and no error will appear.

This is my solution about that problem
[Company Veterans on Bikes.txt](https://github.com/BSData/wh40k/files/1172457/Company.Veterans.on.Bikes.txt)

I cloned the repo but i cannot commit (obviously) nor make a pull request.

**Comment by ilaunchbury** [comment]
If you fork the repo and then clone your fork, you'll be able to push your changes to the fork and then create a pull request back into the master for @flakpanda to review.

**Comment by flakpanda** [comment]
Don't bother forking. I'll have to do it. I have done prep work for this
weekend from the leaks.

**Comment by DaniBisi** [comment]
i already did it.
Take a look, thank you.
