### ISSUE TITLE
Chaos - Chaos Space Marines: Noise Marine strength incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#948]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** Yes

**Description:** NOISE MARINES are showing a Strength value of 5, when it should be 4

**Comment by ilaunchbury** [comment]
This is fixed in the latest release, except for the Champion, which I forgot, and have now fixed.
