### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Centaur missing 2nd Heavy Stubber

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#955]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 1.03.90

**Platform:** Windows

**Dropbox:** Yes

**Description:** Death Korps Centaur Light Assault Carrier comes with two heavy stubbers, but there is a warning this unit can only have one.

https://i.imgur.com/RmoPNJT.png

**Comment by alphalas** [comment]
Duplicate issue - will be fixed in next release for DK

**Comment by Shuro** [comment]
The title is missleading. It doesn't miss the 2nd Heavy Stubber, it just has wrong limits.

**Comment by alphalas** [comment]
Yup; I'm aware.
