### ISSUE TITLE
Imperium - Adeptus Ministorum: Sororitas Rhino missing cost for storm bolter

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#957]
**File:** Imperium - Adeptus Ministorum.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** When you increase the number of storm bolters on an Adepta Sororitas Rhino, it does not add 2 points to the value of the vehicle. (It remains 75 pts)

**Comment by alphalas** [comment]
Sounds like the child detachment bug - I'll check it out

**Comment by alphalas** [comment]
Yup - works fine normally. Known BS bug.
