### ISSUE TITLE
Imperium - Blood Angels: Assault Sergeant weapon choice error

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#958]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.04

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Hello,
there's no melee weapons and pistol option for the assault squad sergent except the eviscerator.

**Comment by ilaunchbury** [comment]
Leave regular wargear selected, then under "Regular wargear" you can choose
whatever you want.
