### ISSUE TITLE
Interceptor rule error

### ISSUE THREAD

**Issue by thefbgnome** [BSData/wh40k#962]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** The Interceptor rule ( for SM StormTalon and StormHawk) is incorrect it should be a +1to hit for models that CAN FLY (currently says cannot FLY... [wich is the Strafing Run Rule that other Flyers Have])

**Comment by ilaunchbury** [comment]
Thanks for your report. This issue has already been raised in #944 and will be fixed soon.
