### ISSUE TITLE
Chaos Daemon - Pink and Brimstone Horrors not adding points correctly

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#963]
Pink and Brimstone horrors are reported as 5 and 2 points respectively regardless of how many are in the unit rather than per model.

Pink Horrors work correctly.

**Comment by ilaunchbury** [comment]
It's working OK for me in the Windows client. What OS are you using? Are your Daemons a parent or child force?

![image](https://user-images.githubusercontent.com/29306451/28608805-ef8a5560-71d9-11e7-85b1-80726e2896d7.png)

**Comment by BaconCatBug** [comment]
Child Force, on Windows.

**Comment by ilaunchbury** [comment]
Sounds like the Battlescribe bug which causes costs to not increment for child forces. I'm afraid you'll have to wait for BS to fix it. Sorry.
