### ISSUE TITLE
Imperium - Death Korps of Krieg - Heavy Quad Launcher

### ISSUE THREAD

**Issue by Disciple90** [BSData/wh40k#975]
Heavy Quad Launcher lacks weapon and stat profile. 
![screenshot_2017-07-26-22-50-01-1](https://user-images.githubusercontent.com/30486922/28654117-657f932a-7257-11e7-9ee1-bd487b46bbb4.png)

**Comment by CrusherJoe** [comment]
Should be fixed in DKOK v14.
