### ISSUE TITLE
Imperium - Sisters of Silence - Vigilators points

### ISSUE THREAD

**Issue by Marina42** [BSData/wh40k#981]
Each Vigilator is 19pts (11pts for the sister and 8pts for the sword).

It currently shows the correct pts value for the minimum unit, but each vigilator you add only adds 11pts instead of 19pts.

**Comment by ilaunchbury** [comment]
This sounds like the known bug in Battlescribe where child forces don't update upgrade costs, as it works fine for me with a parent force of Sisters. We're waiting on a fix.
