### ISSUE TITLE
Chaos - Renegades & Heretics Disciple Squad

### ISSUE THREAD

**Issue by Wyvern350** [BSData/wh40k#982]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** A disciple squad is minimum 5 models. for 3 PL.  1) Disciple Champion, 2) Disciple with Voxcaster, 3) Disciple with Special Weapon, 4) Disciple with Lasgun.  When I select any other Disciple for #5, it increases the PL to 6 like I just added the next tier of models, which should be 6-10 total.

**Comment by Penallegion** [comment]
Should be fixed in upcomming update
