### ISSUE TITLE
Dark Angels Primaris

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#985]
The following units from Codex: Space Marines may be from the Dark Angels chapter:

- Aggressor Squad
- Hellblaster
- Inceptor
- Intercessor
- Primaris Apothecary
- Primaris Captain
- Primaris Chaplain
- Primaris Librarian
- Redemptor Dreadnought
- Reiver Squad
- Repulsor

[Source](https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf)

**Comment by GenWilhelm** [comment]
Also includes:

- Primaris Apothecary
- Primaris Chaplain
- Repulsor

[Source](https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf)

**Comment by DacierCellius** [comment]
This issue is not fixed. I have the updated patch and BA side is great, however the Primaris units on the DA does not have the correct point cost and is not editable. Please fix this.
