### ISSUE TITLE
Space Wolves Primaris

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#986]
The following units from Codex: Space Marines may be from the Space Wolves chapter:

- [x] Aggressor Squad
- [x] Hellblaster
- [x] Inceptor
- [x] Intercessor
- [x] Primaris Captain
- [x] Primaris Chaplain
- [x] Primaris Librarian
- [x] Redemptor Dreadnought
- [x] Reiver Squad
- [x] Repulsor

[Source](https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf)

**Comment by GenWilhelm** [comment]
Also includes:

- Primaris Chaplain
- Repulsor

[Source](https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf)

**Comment by WulfyMcWulf** [comment]
Worth noting that as per the linked GW PDF, Space Wolves cannot take a Primaris Apothecary. Although they can take a Chaplain which they've never been able to before. Weird.

**Comment by FarseerVeraenthis** [comment]
closed by #1267
