### ISSUE TITLE
Deathwatch Primaris

### ISSUE THREAD

**Issue by GenWilhelm** [BSData/wh40k#987]
The following units from Codex: Space Marines may be from the Deathwatch chapter:

- [x] Aggressor Squad
- [x] Hellblaster
- [x] Inceptor
- [x] Intercessor
- [x] Primaris Apothecary
- [x] Primaris Captain
- [x] Primaris Chaplain
- [x] Primaris Librarian
- [x] Redemptor Dreadnought
- [x] Reiver Squad
- [x] Repulsor

[Source](https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf)

**Comment by WindstormSCR** [comment]
This now Includes inceptors, intercessors and the repulsor.

Source: https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf

**Comment by Inquisitorbane0069** [comment]
Per Game's Workshop website Deathwatch may now include all Primaris Marines. See source Document PDF Download: https://www.games-workshop.com/resources/PDF/Downloads/K3ns3JDOGE2asjf/Primaris-week-4/IORF435R4_ENG_Primaris_Marines_Release_04_July_29th.pdf

**Comment by MrRta1910** [comment]
I would like to assist in keeping this catalogue up-to-date

**Comment by flakpanda** [comment]
@MrRta1910, another has express interest in maintaining DW prior to you. they will be maintaining them.
