### ISSUE TITLE
Chaos - Chaos Space Marines: Defiler has incorrect weapon profiles.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#990]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Heretic Astartes Defiler has incorrect weapon profiles. It does not have a Gorestorm cannon, it should be a twin heavy flamer (range 8, str 5, 2d6 shots, ap -1). It also has a twin Reaper Autocannon with 8 shots instead of the 4 shots listed.

**Comment by ilaunchbury** [comment]
The Gorestorm is definitely wrong, but the listing in the Index states it has a single auto-cannon, not a twin one and it's not been FAQ'd otherwise.
