### ISSUE TITLE
Canticles of the Omnissiah, html formatting bugged.

### ISSUE THREAD

**Issue by Gm383** [BSData/wh40k#992]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Currently the html for the Canticles of the Omnissiah when viewing the roster outputs as:
`&lt;ol&gt;&lt;br/&gt;
                    &lt;li&gt; &lt;b&gt;Incantation of the Iron Soul&lt;/b&gt; You can re-roll failed Morale tests for affected units.&lt;/li&gt;  &lt;br/&gt;
                    &lt;li&gt; &lt;b&gt;Litany of the Electromancer&lt;/b&gt; Roll a D6 for each enemy unit that is within 1" of any affected units; on a roll of 6, the unit being rolled for suffers D3 mortal wounds.&lt;/li&gt;   &lt;br/&gt;
                    &lt;li&gt; &lt;b&gt;Chant of the Remorseless Fist&lt;/b&gt; You can re-roll any failed hit rolls of 1 for affected units in the Fight phase.&lt;/li&gt;   &lt;br/&gt;
                    &lt;li&gt; &lt;b&gt;Shroudpsalm&lt;/b&gt; Affected units gain the bonus to their armour saving throws as if they were in cover. Units already in cover are unaffected.&lt;/li&gt;   &lt;br/&gt;
                    &lt;li&gt; &lt;b&gt;Invocation of Machine Might&lt;/b&gt; Affected units have +1 Strength. &lt;/li&gt;  &lt;br/&gt;
                    &lt;li&gt; &lt;b&gt;Benediction of the Omnissiah&lt;/b&gt; You can re-roll failed hit rolls of 1 for affected units in the shooting phase&lt;/li&gt; &lt;br/&gt;
                    &lt;/ol&gt;`

Rather than:
`<ol><br/>
                    <li> <b>Incantation of the Iron Soul</b> You can re-roll failed Morale tests for affected units.</li>  <br/>
                    <li> <b>Litany of the Electromancer</b> Roll a D6 for each enemy unit that is within 1" of any affected units; on a roll of 6, the unit being rolled for suffers D3 mortal wounds.</li>   <br/>
                    <li> <b>Chant of the Remorseless Fist</b> You can re-roll any failed hit rolls of 1 for affected units in the Fight phase.</li>   <br/>
                    <li> <b>Shroudpsalm</b> Affected units gain the bonus to their armour saving throws as if they were in cover. Units already in cover are unaffected.</li>   <br/>
                    <li> <b>Invocation of Machine Might</b> Affected units have +1 Strength. </li>  <br/>
                    <li> <b>Benediction of the Omnissiah</b> You can re-roll failed hit rolls of 1 for affected units in the shooting phase</li> <br/>
                    </ol>`

A simple find and replace from `&lt;` to `<` and `&gt;` to `>` fixes the problem from the user side, but still.

**Comment by amis92** [comment]
It should be completely stripped of HTML tags.

**Comment by Gm383** [comment]
Don't you still want to retain the list format for each canticle?

**Comment by GenWilhelm** [comment]
The latest version of BattleScribe escapes HTML tags, so the only thing a rule can now display is plain text with no line breaks.

**Comment by Kohato** [comment]
We'd love to retain a list format. However BS dev escaped all HTML so we have no way to do that.

**Comment by GenWilhelm** [comment]
Apparently the new version (2.01.04 on desktop) allows line breaks in rules, so that's a start.
