### ISSUE TITLE
Chaos - FW Renegade and Heretics: Disciple PL is calculating incorrectly

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#993]
**File:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 1.03.90

**Platform:** Windows

**Dropbox:** No

**Description:** The Disciple entry is incorrect in how it calculates the unit's Power. 
When you add either a Chaos Sigil/Vox-Caster/Special Weapon or create a Heavy Weapon Team this equips the current members of the unit. 
In order to fully equip the unit with all of the above options you would have to then add additional squad members by increasing the unit's power, as the RAW (rules as written) state that you can't equip the same model with multiple options.
e.g. "One model may be equipped with a Chaos Sigil. One OTHER model can be equipped with a Vox-caster."
When I create a Disciple unit and allocate a Heavy Weapon Team it shouldn't add the next bracket of Power (+3) for totalling up the correct amount of squad members because no additional squad members are added.
Currently if you add a heavy weapons team and then state how many of the remaining 2 members (not including the Disciple Champion, are equipped either with lasguns or autoguns, the unit's power is increased incorrectly.

**Comment by Penallegion** [comment]
i am quite certain i fixed all this in last update, have you tried updating your data files?
